table DEMANDA
	lineageTag: 182b720d-6326-4228-98d7-210f6202ebb6

	column Demanda
		dataType: string
		lineageTag: 676ca88e-a0a8-4c82-97c3-a126adb099ac
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Asunto
		dataType: string
		lineageTag: 64ddaccd-25ca-4135-9664-e8ee96c4e32a
		summarizeBy: none
		sourceColumn: Asunto

		annotation SummarizationSetBy = Automatic

	column 'Estado de la Demanda'
		dataType: string
		lineageTag: 049dfaf6-b1f8-4da9-a90c-9f91d992b9e5
		summarizeBy: none
		sourceColumn: Estado de la Demanda

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: e6b82e8e-a6ae-4a4e-9ac4-49609dac1443
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Porfolio
		dataType: string
		lineageTag: 286443d6-e880-439a-9dae-4a9f484a6aea
		summarizeBy: none
		sourceColumn: Porfolio

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: a1cf5c7a-9347-4003-8865-cc611278ae2b
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Subcategoria
		dataType: string
		lineageTag: d92b27ef-4ee3-414a-81fa-893aafeb52b6
		summarizeBy: none
		sourceColumn: Subcategoria

		annotation SummarizationSetBy = Automatic

	column 'Magnitud de la Demanda'
		dataType: string
		lineageTag: dd91ddd7-33f8-4d87-ab43-9a4960b669f4
		summarizeBy: none
		sourceColumn: Magnitud de la Demanda

		annotation SummarizationSetBy = Automatic

	column 'Solicitado Por'
		dataType: string
		lineageTag: 940d2102-7beb-4d24-b38a-e3e76a75181a
		summarizeBy: none
		sourceColumn: Solicitado Por

		annotation SummarizationSetBy = Automatic

	column 'Gestor de Demanda'
		dataType: string
		lineageTag: 7b2fc06f-81f3-4921-8eac-a907e3d480fa
		summarizeBy: none
		sourceColumn: Gestor de Demanda

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a85624e9-509f-45fc-9432-fd02c99ff9bd
		summarizeBy: none
		sourceColumn: Abierto

		variation Variation
			isDefault
			relationship: eaab0078-40e3-485e-a629-179465b82256
			defaultHierarchy: LocalDateTable_750dd793-4367-4f9e-8abf-0d0d7ffee21f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Cerrado
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: c19bfd3a-978f-4933-8b91-ff43aca38b10
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: ae63e30d-531d-44d6-a33a-6316868f349d
			defaultHierarchy: LocalDateTable_65c62125-213a-4b38-8f29-256b17b85b13.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fecha de solicitud'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 75865799-2b6d-40dd-bb98-b6269bb99f56
		summarizeBy: none
		sourceColumn: Fecha de solicitud

		variation Variation
			isDefault
			relationship: 41e97711-78fd-46e9-b6d6-be25cbaa76c2
			defaultHierarchy: LocalDateTable_d534bfe4-89c0-4303-975b-9024e3fc6c9c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fecha de Registro'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a982a5d7-24d2-45e8-9e68-8a7c9f600db5
		summarizeBy: none
		sourceColumn: Fecha de Registro

		variation Variation
			isDefault
			relationship: de9794bd-e2aa-45a0-8cec-5b8b9df4c000
			defaultHierarchy: LocalDateTable_cac40654-8f19-4db0-8fd7-e33d5394b18e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fecha de Cualificacion'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 600119f2-bb56-4ea6-a135-767fbe05e5c4
		summarizeBy: none
		sourceColumn: Fecha de Cualificacion

		variation Variation
			isDefault
			relationship: 20d9eb2e-c1ee-4d73-a7d9-7cc3061d61a6
			defaultHierarchy: LocalDateTable_37aa175b-7b25-4559-96eb-1a8f6c80d7d1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fecha del Primer Comité'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: da285149-683d-4293-b1e0-9cc2ff391528
		summarizeBy: none
		sourceColumn: Fecha del Primer Comité

		variation Variation
			isDefault
			relationship: 70edffd8-bd15-4185-bbe9-85ead9ac9794
			defaultHierarchy: LocalDateTable_5abcab73-cba0-4c92-9c1d-14fbc50c3a17.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fecha de Analisis'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 557d5c7a-14f6-44b1-8e4d-853d473fc3cf
		summarizeBy: none
		sourceColumn: Fecha de Analisis

		variation Variation
			isDefault
			relationship: 7120b31f-7050-44d2-805d-b69c059f5509
			defaultHierarchy: LocalDateTable_07668c45-0c7c-415c-9eda-02adb8f400b7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fecha del Segundo Comité'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: fdd1ccfc-9eae-41f9-aa6a-4307466df778
		summarizeBy: none
		sourceColumn: Fecha del Segundo Comité

		variation Variation
			isDefault
			relationship: ea98d9b3-3374-471a-b8f0-26b28f9a281d
			defaultHierarchy: LocalDateTable_db5569db-42e4-41c4-9f03-61ede66e23ae.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fecha de Aprobacion'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: afbeb130-56b6-4787-ae45-f32e957bb933
		summarizeBy: none
		sourceColumn: Fecha de Aprobacion

		variation Variation
			isDefault
			relationship: 1158d5d5-68f4-452b-9de9-4e9eb11fb819
			defaultHierarchy: LocalDateTable_d6373fb1-3138-4f31-8a57-6f6093ddbb41.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fecha de Rechazo'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3d2a6d85-d757-4480-b90d-66db73e9ed7c
		summarizeBy: none
		sourceColumn: Fecha de Rechazo

		variation Variation
			isDefault
			relationship: 0d1cd602-80d6-4d36-9774-4d6c373912c7
			defaultHierarchy: LocalDateTable_c66f9bc4-a6b2-4dde-a184-77a63e944f8d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fecha de estado'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 34be7d9a-c493-4413-ba45-ccd0c4b40b52
		summarizeBy: none
		sourceColumn: Fecha de estado

		variation Variation
			isDefault
			relationship: 5b1901e1-d278-4dd3-b3aa-d2fc99b38b98
			defaultHierarchy: LocalDateTable_f143f4e0-f991-4d74-bba0-db1a476f07a9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fecha Inicio Estimada'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 6714438b-f3ab-449e-b634-75631682b92c
		summarizeBy: none
		sourceColumn: Fecha Inicio Estimada

		variation Variation
			isDefault
			relationship: 5f230dd1-d09d-4451-9549-1e5413f2ebbd
			defaultHierarchy: LocalDateTable_d3523cd2-b3f3-4dc7-93af-409212cc057f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Fecha Objetivo'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bb0fb05f-422b-4e7c-9269-40523d326542
		summarizeBy: none
		sourceColumn: Fecha Objetivo

		variation Variation
			isDefault
			relationship: 40547edd-2c22-46d9-8467-b6b44e1f2793
			defaultHierarchy: LocalDateTable_785c76e4-258c-4acb-b7e1-9d94479112c8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Programa
		dataType: string
		lineageTag: 383ed427-4767-49e5-9a59-998877441697
		summarizeBy: none
		sourceColumn: Programa

		annotation SummarizationSetBy = Automatic

	column Estrategia
		dataType: string
		lineageTag: 7371ef04-cd1d-48c4-b6f1-680eafde04d5
		summarizeBy: none
		sourceColumn: Estrategia

		annotation SummarizationSetBy = Automatic

	column Destacado
		dataType: string
		lineageTag: ea645ebf-0bfe-45c1-89c7-eb6e9aaeddae
		summarizeBy: none
		sourceColumn: Destacado

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio'
		dataType: string
		lineageTag: 417ee92a-1a2b-4b3b-96a6-2bcc4ce82acd
		summarizeBy: none
		sourceColumn: Aplicación de Negocio

		annotation SummarizationSetBy = Automatic

	column 'Aplicaciones Impactadas'
		dataType: string
		lineageTag: 7238eef2-d735-4276-9937-2bce058bc6c4
		summarizeBy: none
		sourceColumn: Aplicaciones Impactadas

		annotation SummarizationSetBy = Automatic

	column 'Porfolios Afectados'
		dataType: string
		lineageTag: e43bf8c2-10a4-4c71-b72e-8baf722ef80d
		summarizeBy: none
		sourceColumn: Porfolios Afectados

		annotation SummarizationSetBy = Automatic

	column 'Fecha de fin real'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fe58c375-bc2a-444e-9e2b-ce1a1d7eb03f
		summarizeBy: none
		sourceColumn: Fecha de fin real

		variation Variation
			isDefault
			relationship: 153c2389-784c-456f-a439-30eb6138f678
			defaultHierarchy: LocalDateTable_b356e575-1dbb-4b1f-9a1e-8f267991ada2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Presupuesto  Capex'
		dataType: double
		lineageTag: 1a1a7485-a070-4fe5-b747-abd432f5a894
		summarizeBy: sum
		sourceColumn: Presupuesto  Capex

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Presupuesto  Opex'
		dataType: double
		lineageTag: e36e2bf4-22cc-4326-bf96-1159d5b74de8
		summarizeBy: sum
		sourceColumn: Presupuesto  Opex

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Presupuesto Total'
		dataType: double
		lineageTag: 1ad5caad-4aca-4bb4-9ad2-efcc9d7d3302
		summarizeBy: sum
		sourceColumn: Presupuesto Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Jefe de proyecto'
		dataType: string
		lineageTag: 9226b4b0-622d-4078-9680-007a99a495cc
		summarizeBy: none
		sourceColumn: Jefe de proyecto

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: bb84d316-4c65-4b2f-968a-0cc9f641fa3d
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Fase
		dataType: string
		lineageTag: f3219ac9-9076-4428-8857-d19391d82397
		summarizeBy: none
		sourceColumn: Fase

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0c7b6620-6090-4caa-9d60-369b57c085af
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: 44b0131e-90f2-4f3a-b336-ac46eccc0323
			defaultHierarchy: LocalDateTable_a7a1cbce-5ee6-468a-aa35-7d8b9bda7916.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fecha fin real'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6673f6fd-5566-472e-a84d-1a81f7049bcb
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: 4087911d-c03a-438b-bb43-2d68ed7ab6ba
			defaultHierarchy: LocalDateTable_2231437c-6062-49a2-ba48-43a4bce7b38e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Porcentaje completado'
		dataType: double
		lineageTag: 90ca62e5-dc5e-4dbb-ac14-683d5979f176
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fecha Inicio Planificada'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 76b0d3b6-6f00-4ee5-865c-04d085ab325e
		summarizeBy: none
		sourceColumn: Fecha Inicio Planificada

		variation Variation
			isDefault
			relationship: 453f230b-6b57-45fb-b5cd-893e20e92d28
			defaultHierarchy: LocalDateTable_36cb80ff-840c-4356-8881-d0d805f07173.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fecha fin Planificada'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 24f2d5bb-2d94-4ed7-9996-506de6bf0ff4
		summarizeBy: none
		sourceColumn: Fecha fin Planificada

		variation Variation
			isDefault
			relationship: 3c88b8e9-b2e8-4737-baee-d3566ff278e2
			defaultHierarchy: LocalDateTable_0551e8fd-1387-481b-ae57-bbd8dd8ecc7d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Esfuerzo Total'
		dataType: double
		lineageTag: 795a4233-87c5-4d34-9911-a084ecf9016e
		summarizeBy: sum
		sourceColumn: Esfuerzo Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ID Plan'
		dataType: string
		lineageTag: d099e8c7-1f59-4949-8874-f915c865183a
		summarizeBy: none
		sourceColumn: ID Plan

		annotation SummarizationSetBy = Automatic

	partition DEMANDA = m
		mode: import
		queryGroup: ARCHIVOS_TRATADOS
		source =
				let
				    Source = DEMANDA_RAW,
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(Source, {{"Fecha del Segundo Comité", each Text.BeforeDelimiter(_, " "), type text}}),
				    #"Extracted Text Before Delimiter1" = Table.TransformColumns(#"Extracted Text Before Delimiter", {{"Fecha del Primer Comité", each Text.BeforeDelimiter(_, " "), type text}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Extracted Text Before Delimiter1",{{"Demanda", type text}, {"Asunto", type text}, {"Estado de la Demanda", type text}, {"Prioridad", type text}, {"Porfolio", type text}, {"Tipo", type text}, {"Subcategoria", type text}, {"Magnitud de la Demanda", type text}, {"Solicitado Por", type text}, {"Gestor de Demanda", type text}, {"Motivo no avance / rechazo", type text}, {"Abierto", type date}, {"Cerrado", type date}, {"Fecha de solicitud", type date}, {"Fecha de Registro", type date}, {"Fecha de Cualificacion", type date}, {"Fecha del Primer Comité", type date}, {"Fecha de Analisis", type date}, {"Fecha del Segundo Comité", type date}, {"Fecha de Aprobacion", type date}, {"Fecha de Rechazo", type date}, {"Fecha de estado", type date}, {"Fecha Inicio Estimada", type date}, {"Fecha Objetivo", type date}, {"Programa", type text}, {"Estrategia", type text}, {"Destacado", type text}, {"Aplicación de Negocio", type text}, {"Aplicaciones Impactadas", type text}, {"Porfolios Afectados", type text}, {"Fecha de fin real", type date}, {"Presupuesto  Capex", type number}, {"Presupuesto  Opex", type number}, {"Presupuesto Total", type number}, {"Fecha Entrada Diferido", type date}, {"Fecha Salida Diferido", type date}, {"Fecha de inicio aprobada", type date}, {"Jefe de proyecto", type text}, {"Número", type text}, {"Fase", type text}, {"Fecha de inicio real", type date}, {"Fecha fin real", type date}, {"Porcentaje completado", Percentage.Type}, {"Jefe de proyecto (Project Manager)", type text}, {"Fecha Inicio Planificada", type date}, {"Fecha fin Planificada", type date}, {"Mejora", type text}, {"Demanda Planificada", type text}, {"Estado del Primer Comité", type text}, {"Estado del Segundo Comité", type text}, {"Esfuerzo Total", type number}, {"Externalización", type text}, {"ID Plan", type text}, {"En Alcance", type text}, {"Objetivo", type text}, {"Situación Actual", type text}, {"Categoría", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Changed Type",{"Externalización", "En Alcance", "Objetivo", "Situación Actual", "Categoría", "Demanda Planificada", "Estado del Primer Comité", "Estado del Segundo Comité", "Motivo no avance / rechazo", "Fecha Entrada Diferido", "Fecha Salida Diferido", "Fecha de inicio aprobada", "Mejora", "Jefe de proyecto (Project Manager)"}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas quitadas", each ([Estado de la Demanda] = "Aprobado" or [Estado de la Demanda] = "Completado")),
				    #"Filas filtradas1" = Table.SelectRows(#"Filas filtradas", each [Cerrado] >= AÑO_ACTUAL or [Cerrado] = null),
				    #"Filas filtradas2" = Table.SelectRows(#"Filas filtradas1", each true)
				in
				    #"Filas filtradas2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

