table ERROR_KEY_BUDGET
	lineageTag: b950c8b6-4033-425d-8299-8a535f5ecaed

	column 'Tabla Origen'
		dataType: string
		lineageTag: 08814c62-7c4b-40ec-bddb-f75e2d510836
		summarizeBy: none
		sourceColumn: Tabla Origen

		annotation SummarizationSetBy = Automatic

	column 'FECHA IMPACTO BUDGET'
		dataType: dateTime
		formatString: Short Date
		lineageTag: fb6f816b-9211-4998-8deb-ff301d2b27c8
		summarizeBy: none
		sourceColumn: FECHA IMPACTO BUDGET

		variation Variación
			isDefault
			relationship: 3ea94d2a-91bb-4835-ac07-02db35da3dd2
			defaultHierarchy: LocalDateTable_37cac62a-2ce6-4bb3-90c2-ee31ccb04b1f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'COSTE IMPACTO BUDGET'
		dataType: double
		lineageTag: b4e70ea2-f834-4b14-97ae-e610cacb6a4b
		summarizeBy: sum
		sourceColumn: COSTE IMPACTO BUDGET

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'DEMANDA IMPACTO BUDGET'
		dataType: string
		lineageTag: ce018f12-116d-4e7e-a7b6-e04a42a91c8f
		summarizeBy: none
		sourceColumn: DEMANDA IMPACTO BUDGET

		annotation SummarizationSetBy = Automatic

	column Proveedor
		dataType: string
		lineageTag: ce6aafcf-d460-4097-bce2-c7071cec3389
		summarizeBy: none
		sourceColumn: Proveedor

		annotation SummarizationSetBy = Automatic

	column 'Documento Compras'
		dataType: string
		lineageTag: 6b2ea402-1606-4876-9243-39509bf1ca32
		summarizeBy: none
		sourceColumn: Documento Compras

		annotation SummarizationSetBy = Automatic

	column Posición
		dataType: string
		lineageTag: a4d69ea1-c22d-4614-a8e8-e18622255775
		summarizeBy: none
		sourceColumn: Posición

		annotation SummarizationSetBy = Automatic

	column 'Texto explicativo'
		dataType: string
		lineageTag: ea95aea3-1ec6-4388-8b15-6f68ca983906
		summarizeBy: none
		sourceColumn: Texto explicativo

		annotation SummarizationSetBy = Automatic

	column 'Descripción Cuenta'
		dataType: string
		lineageTag: 502423c6-5994-40cd-b399-1e45c8b92fd9
		summarizeBy: none
		sourceColumn: Descripción Cuenta

		annotation SummarizationSetBy = Automatic

	column 'Doc. Referencia'
		dataType: string
		lineageTag: ab7740d7-a471-466b-9884-953a37fed936
		summarizeBy: none
		sourceColumn: Doc. Referencia

		annotation SummarizationSetBy = Automatic

	column 'Clase Doc. Referencia'
		dataType: string
		lineageTag: ef5643d3-b2d7-400b-ad8b-9e0a4ae16d0f
		summarizeBy: none
		sourceColumn: Clase Doc. Referencia

		annotation SummarizationSetBy = Automatic

	column 'Texto Cabecera Doc'
		dataType: string
		lineageTag: a192dd98-81a4-46b5-9be3-9ba03d57323f
		summarizeBy: none
		sourceColumn: Texto Cabecera Doc

		annotation SummarizationSetBy = Automatic

	column Cantidad
		dataType: double
		lineageTag: 605b4934-d29f-425a-9c91-df7f063068a2
		summarizeBy: sum
		sourceColumn: Cantidad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Unidad
		dataType: string
		lineageTag: f040ebc8-4785-47ec-a5e7-135ce45fe1d6
		summarizeBy: none
		sourceColumn: Unidad

		annotation SummarizationSetBy = Automatic

	column Orden
		dataType: string
		lineageTag: 0d5c6f1d-c1df-4b02-a695-df9b75b187f2
		summarizeBy: none
		sourceColumn: Orden

		annotation SummarizationSetBy = Automatic

	column Tagetik
		dataType: string
		lineageTag: cd130a29-5de2-4af5-bca9-a0d07552a090
		summarizeBy: none
		sourceColumn: Tagetik

		annotation SummarizationSetBy = Automatic

	column 'Documento CO'
		dataType: string
		lineageTag: bf66cc02-b58d-4cc9-9dae-1873ac94964e
		summarizeBy: none
		sourceColumn: Documento CO

		annotation SummarizationSetBy = Automatic

	column ERROR_KP
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4015bd9e-5b0d-40e5-965f-48b086bac04a
		summarizeBy: none
		sourceColumn: ERROR_KP

		annotation SummarizationSetBy = Automatic

	column KEY_BUDGET
		dataType: string
		lineageTag: 858935f7-5f79-496c-a88f-d0643957ffcb
		summarizeBy: none
		sourceColumn: KEY_BUDGET

		annotation SummarizationSetBy = Automatic

	column ERROR_KB
		dataType: string
		lineageTag: 90d442eb-f724-4d12-bd6e-0794281c8c85
		summarizeBy: none
		sourceColumn: ERROR_KB

		annotation SummarizationSetBy = Automatic

	column Ignorar
		dataType: string
		lineageTag: 81abe6ea-07ad-4dd3-b4ff-eb318b60ed11
		summarizeBy: none
		sourceColumn: Ignorar

		annotation SummarizationSetBy = Automatic

	column KEY_PEDIDO
		dataType: string
		lineageTag: b16a1f8d-7db3-42ef-90d1-4ac8f6bc73c2
		summarizeBy: none
		sourceColumn: KEY_PEDIDO

		annotation SummarizationSetBy = Automatic

	column 'ID PROVISION'
		dataType: string
		lineageTag: 2e333e83-7b52-47e4-8245-3398287f6224
		summarizeBy: none
		sourceColumn: ID PROVISION

		annotation SummarizationSetBy = Automatic

	column Sociedad
		dataType: string
		lineageTag: 1a2c3863-4641-41b1-a30d-519179201236
		summarizeBy: none
		sourceColumn: Sociedad

		annotation SummarizationSetBy = Automatic

	column 'Contrato Marco'
		dataType: string
		lineageTag: eb8a7ee6-c140-483e-aa43-474c26ff8d63
		summarizeBy: none
		sourceColumn: Contrato Marco

		annotation SummarizationSetBy = Automatic

	column 'Solicitud de Pedido'
		dataType: string
		lineageTag: f46b811a-95aa-41fb-bf31-26d07af97184
		summarizeBy: none
		sourceColumn: Solicitud de Pedido

		annotation SummarizationSetBy = Automatic

	column 'Texto de cabecera'
		dataType: string
		lineageTag: 7bcbe0df-5716-4762-9716-d24fa45bab38
		summarizeBy: none
		sourceColumn: Texto de cabecera

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3a4a8d24-f411-416d-bf20-f3149bf5acb0
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 28d827a9-20d0-40cf-8e31-04abf6b70e17
			defaultHierarchy: LocalDateTable_0e4559db-fe5d-43b8-93aa-609f1791d4c0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Solicitante
		dataType: string
		lineageTag: d8a51d98-1de5-4997-ba29-317bc91029c1
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column 'Número de imputación'
		dataType: string
		lineageTag: 4f6bdac9-1234-4843-a3c7-4a82de27cded
		summarizeBy: none
		sourceColumn: Número de imputación

		annotation SummarizationSetBy = Automatic

	column 'Texto de posición'
		dataType: string
		lineageTag: bf5dcc3a-d6e1-4e61-8155-070919a697fa
		summarizeBy: none
		sourceColumn: Texto de posición

		annotation SummarizationSetBy = Automatic

	column Coste
		dataType: double
		lineageTag: 5a3baf31-a750-49cc-8ba4-e489fc0d9e02
		summarizeBy: sum
		sourceColumn: Coste

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fecha de Entrega'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c9fa5642-eed7-47f2-9bfd-7ef3ba9b495d
		summarizeBy: none
		sourceColumn: Fecha de Entrega

		variation Variación
			isDefault
			relationship: 8dc6e2c2-0039-48d8-a5e0-d6e744d84f3a
			defaultHierarchy: LocalDateTable_7c446649-9cf0-4ba8-851e-6794bbaaad22.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Indicador Liberación'
		dataType: string
		lineageTag: 07ba7a2f-4d92-45ac-ab1b-69c50c48b947
		summarizeBy: none
		sourceColumn: Indicador Liberación

		annotation SummarizationSetBy = Automatic

	column 'Indicador de borrado'
		dataType: string
		lineageTag: 6419552e-e772-42c3-9432-66d6042f52ef
		summarizeBy: none
		sourceColumn: Indicador de borrado

		annotation SummarizationSetBy = Automatic

	column Observaciones
		dataType: string
		lineageTag: 3448a205-575d-4067-a86d-9749c9ac4810
		summarizeBy: none
		sourceColumn: Observaciones

		annotation SummarizationSetBy = Automatic

	column 'Tipo pedido'
		dataType: string
		lineageTag: 72ed9476-2c1c-4431-9f1c-95104d6bbcc2
		summarizeBy: none
		sourceColumn: Tipo pedido

		annotation SummarizationSetBy = Automatic

	column Demanda
		dataType: string
		lineageTag: 1d7afcf0-7789-4924-a0e7-27f6271ba331
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column 'Proveedor Nombre'
		dataType: string
		lineageTag: 55b5393f-7c33-49c5-a250-760c8a7215e7
		summarizeBy: none
		sourceColumn: Proveedor Nombre

		annotation SummarizationSetBy = Automatic

	partition ERROR_KEY_BUDGET = m
		mode: import
		queryGroup: CHECK_ERROR
		source =
				let
				    Origen = IMPACTO_BUDGET,
				    Combine_Pedidos = Table.Combine({#"Origen", #"PEDIDOS"}),
				    Filtrado = Table.SelectRows(Combine_Pedidos, each ([ERROR_KB] = true))
				in
				    Filtrado

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Exception

