table IMPACTO_BUDGET
	lineageTag: 441734d2-3d2e-4a7a-9425-8229bbd4c9cc

	column Proveedor
		dataType: string
		lineageTag: 456a5284-1387-4365-b075-2e3ac05aa3e4
		summarizeBy: none
		sourceColumn: Proveedor

		annotation SummarizationSetBy = Automatic

	column Orden
		dataType: string
		lineageTag: 5ce6df2d-71ed-4517-8771-d427ff87f938
		summarizeBy: none
		sourceColumn: Orden

		annotation SummarizationSetBy = Automatic

	column Tagetik
		dataType: string
		lineageTag: 04b260e9-972d-405b-a421-b18023e332ba
		summarizeBy: none
		sourceColumn: Tagetik

		annotation SummarizationSetBy = Automatic

	column KEY_PEDIDO
		dataType: string
		lineageTag: 55fa7f87-c342-42dd-a26d-b7c800490ee2
		summarizeBy: none
		sourceColumn: KEY_PEDIDO

		annotation SummarizationSetBy = Automatic

	column KEY_BUDGET
		dataType: string
		lineageTag: 13010cf5-7030-47f6-b9c3-8dc27257ae92
		summarizeBy: none
		sourceColumn: KEY_BUDGET

		annotation SummarizationSetBy = Automatic

	column 'Texto explicativo'
		dataType: string
		lineageTag: e420e151-8445-4cef-bb3a-0aaaba0ddcc5
		summarizeBy: none
		sourceColumn: Texto explicativo

		annotation SummarizationSetBy = Automatic

	column 'Doc. Referencia'
		dataType: string
		lineageTag: faeffc78-7ca5-4595-a911-b992cb9210a5
		summarizeBy: none
		sourceColumn: Doc. Referencia

		annotation SummarizationSetBy = Automatic

	column 'Clase Doc. Referencia'
		dataType: string
		lineageTag: b8faf4f5-676d-4df2-baab-8803abd28d1b
		summarizeBy: none
		sourceColumn: Clase Doc. Referencia

		annotation SummarizationSetBy = Automatic

	column 'Texto Cabecera Doc'
		dataType: string
		lineageTag: 4e6e3044-694d-4375-8501-f14ebfd9241d
		summarizeBy: none
		sourceColumn: Texto Cabecera Doc

		annotation SummarizationSetBy = Automatic

	column 'Documento CO'
		dataType: string
		lineageTag: 6e673a50-77fc-4da6-9ca7-402e4c418732
		summarizeBy: none
		sourceColumn: Documento CO

		annotation SummarizationSetBy = Automatic

	column Unidad
		dataType: string
		lineageTag: f87153e1-fb10-43e7-a9c7-8b06eacd6cf3
		summarizeBy: none
		sourceColumn: Unidad

		annotation SummarizationSetBy = Automatic

	column Cantidad
		dataType: double
		lineageTag: 1e9e48aa-9ead-43f6-9b84-7ab1b4d57941
		summarizeBy: sum
		sourceColumn: Cantidad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Posición
		dataType: string
		lineageTag: 13bd1d0d-e8ea-4a63-8dca-905c63aafa9f
		summarizeBy: none
		sourceColumn: Posición

		annotation SummarizationSetBy = Automatic

	column 'Descripción Cuenta'
		dataType: string
		lineageTag: 097d7c29-40b1-45c0-8e53-04189de1be68
		summarizeBy: none
		sourceColumn: Descripción Cuenta

		annotation SummarizationSetBy = Automatic

	column 'ID PROVISION'
		dataType: string
		lineageTag: 83d641cf-027f-4992-8397-9f9e278b0bd2
		summarizeBy: none
		sourceColumn: ID PROVISION

		annotation SummarizationSetBy = Automatic

	column 'Documento Compras'
		dataType: string
		lineageTag: 579c3bc3-595d-4863-98ee-4bdbd4c68852
		summarizeBy: none
		sourceColumn: Documento Compras

		annotation SummarizationSetBy = Automatic

	column 'Tabla Origen'
		dataType: string
		lineageTag: a9be22eb-2a78-4581-83be-702cce28aa1a
		summarizeBy: none
		sourceColumn: Tabla Origen

		annotation SummarizationSetBy = Automatic

	column 'FECHA IMPACTO BUDGET'
		dataType: dateTime
		formatString: Short Date
		lineageTag: da03a65f-eddf-47ce-9d7d-d342a3ed0b18
		summarizeBy: none
		sourceColumn: FECHA IMPACTO BUDGET

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'COSTE IMPACTO BUDGET'
		dataType: double
		lineageTag: 08d77d34-2496-4a28-8921-6014879563a2
		summarizeBy: sum
		sourceColumn: COSTE IMPACTO BUDGET

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'DEMANDA IMPACTO BUDGET'
		dataType: string
		lineageTag: aa77b80f-e1e2-4291-aa2d-c4d864a77dc1
		summarizeBy: none
		sourceColumn: DEMANDA IMPACTO BUDGET

		annotation SummarizationSetBy = Automatic

	column ERROR_KB
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3424db1f-fe4a-459b-abbc-71bb24c22d37
		summarizeBy: none
		sourceColumn: ERROR_KB

		annotation SummarizationSetBy = Automatic

	column ERROR_KP
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3a4f3b55-f3c9-42ce-9871-1c182c1cf316
		summarizeBy: none
		sourceColumn: ERROR_KP

		annotation SummarizationSetBy = Automatic

	column Ignorar
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4db07df0-1190-4636-a421-48fbf2e7412d
		summarizeBy: none
		sourceColumn: Ignorar

		annotation SummarizationSetBy = Automatic

	partition IMPACTO_BUDGET = m
		mode: import
		queryGroup: TABLAS_AUXILIARES
		source =
				let
				    Source = Table.Combine({RECEPCIONES, RECEPCIONES_HISTORICO, COMPROMETIDO, PROVISIONES}),
				    #"Columnas reordenadas" = Table.ReorderColumns(Source,{"Tabla Origen", "FECHA IMPACTO BUDGET", "COSTE IMPACTO BUDGET", "DEMANDA IMPACTO BUDGET", "Proveedor", "Documento Compras", "Posición", "Texto explicativo", "Descripción Cuenta", "Doc. Referencia", "Clase Doc. Referencia", "Texto Cabecera Doc", "Cantidad", "Unidad", "Orden", "Tagetik", "Documento CO", "KEY_BUDGET", "KEY_PEDIDO", "Id Partida Forecast", "Descripción partida Forecast", "Solicitante", "Tipo Provisión", "Horas"}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Columnas reordenadas",{"Descripción partida Forecast", "Solicitante", "Tipo Provisión", "Horas"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas quitadas",{{"FECHA IMPACTO BUDGET", type date}, {"COSTE IMPACTO BUDGET", type number}, {"Cantidad", type number}, {"ERROR_KP", type logical}, {"ERROR_KB", type logical}, {"Ignorar", type logical}, {"Proveedor", type text}, {"Documento Compras", type text}, {"Posición", type text}, {"Texto explicativo", type text}, {"Descripción Cuenta", type text}, {"Doc. Referencia", type text}, {"Clase Doc. Referencia", type text}, {"Texto Cabecera Doc", type text}, {"Unidad", type text}, {"Orden", type text}, {"Tagetik", type text}, {"Documento CO", type text}, {"KEY_BUDGET", type text}, {"KEY_PEDIDO", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"Id Partida Forecast", "ID PROVISION"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

