table PEDIDOS
	lineageTag: ff2d07ec-f46c-44ec-8508-4a3bda30f994

	column Sociedad
		dataType: string
		lineageTag: 6bd01113-e5ab-4d22-805e-8a2118a3788f
		summarizeBy: none
		sourceColumn: Sociedad

		annotation SummarizationSetBy = Automatic

	column 'Contrato Marco'
		dataType: string
		lineageTag: bd1af83b-bf24-4a6d-a89c-45a2d12e5a7e
		summarizeBy: none
		sourceColumn: Contrato Marco

		annotation SummarizationSetBy = Automatic

	column 'Solicitud de Pedido'
		dataType: string
		lineageTag: b5aced9b-4260-4e3f-a799-7c0d16060a7d
		summarizeBy: none
		sourceColumn: Solicitud de Pedido

		annotation SummarizationSetBy = Automatic

	column 'Documento Compras'
		dataType: string
		lineageTag: 3c26ce69-735a-4cac-a620-5de630e915f8
		summarizeBy: none
		sourceColumn: Documento Compras

		annotation SummarizationSetBy = Automatic

	column 'Texto de cabecera'
		dataType: string
		lineageTag: f0892f81-8bb1-4532-92e1-39cb516d0d2d
		summarizeBy: none
		sourceColumn: Texto de cabecera

		annotation SummarizationSetBy = Automatic

	column Proveedor
		dataType: string
		lineageTag: cf08878e-8c23-4482-b57a-bf594be9f9fa
		summarizeBy: none
		sourceColumn: Proveedor

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: f9312271-7361-4482-88d8-153aafdde8c1
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: bd56e3ab-322b-4aa7-a968-c6a0801c7347
			defaultHierarchy: LocalDateTable_f1f210de-3f2b-4338-a431-b50f2ed61339.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Solicitante
		dataType: string
		lineageTag: be4c23e9-7ad2-454a-b0ae-d84ce9a5e7e2
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column Posición
		dataType: string
		lineageTag: b1a1b1b5-6e8d-4dd6-960b-489fda00279c
		summarizeBy: none
		sourceColumn: Posición

		annotation SummarizationSetBy = Automatic

	column 'Número de imputación'
		dataType: string
		lineageTag: baa4cea3-6c6d-42da-995b-409eec745a40
		summarizeBy: none
		sourceColumn: Número de imputación

		annotation SummarizationSetBy = Automatic

	column 'Texto de posición'
		dataType: string
		lineageTag: 77365930-f7d5-4cef-b5db-f7f10c913d9e
		summarizeBy: none
		sourceColumn: Texto de posición

		annotation SummarizationSetBy = Automatic

	column Orden
		dataType: string
		lineageTag: a7f84fc8-cbfd-4faf-b98d-7f9a729e354f
		summarizeBy: none
		sourceColumn: Orden

		annotation SummarizationSetBy = Automatic

	column Tagetik
		dataType: string
		lineageTag: 6d063197-8b81-4221-b1f0-86f8a16a49b5
		summarizeBy: none
		sourceColumn: Tagetik

		annotation SummarizationSetBy = Automatic

	column Cantidad
		dataType: double
		lineageTag: 182a9824-15cf-4b9b-9f35-c5635f8d4082
		summarizeBy: sum
		sourceColumn: Cantidad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Unidad
		dataType: string
		lineageTag: 6c284457-f36a-47e4-84f0-fd4e0274ffe6
		summarizeBy: none
		sourceColumn: Unidad

		annotation SummarizationSetBy = Automatic

	column Coste
		dataType: double
		lineageTag: 55a90261-d03a-4e69-b673-86c1aef32a6b
		summarizeBy: sum
		sourceColumn: Coste

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fecha de Entrega'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6aee8fc1-cf68-40bf-8e2e-d7d4dc3446bd
		summarizeBy: none
		sourceColumn: Fecha de Entrega

		variation Variación
			isDefault
			relationship: 3ff865f8-e0ba-43a0-85aa-a7636f92ca14
			defaultHierarchy: LocalDateTable_b4925520-f139-45b9-ad83-27f00f8731c9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Indicador Liberación'
		dataType: string
		lineageTag: c222096c-70d1-4f84-9539-9886d09c6a2b
		summarizeBy: none
		sourceColumn: Indicador Liberación

		annotation SummarizationSetBy = Automatic

	column 'Indicador de borrado'
		dataType: string
		lineageTag: 9338ca1e-979d-4094-9078-be0a0f4f1717
		summarizeBy: none
		sourceColumn: Indicador de borrado

		annotation SummarizationSetBy = Automatic

	column Ignorar
		dataType: string
		lineageTag: 45ada00c-a127-48d2-8966-21f127aba9c8
		summarizeBy: none
		sourceColumn: Ignorar

		annotation SummarizationSetBy = Automatic

	column Observaciones
		dataType: string
		lineageTag: 6d75584d-04a6-4d68-8c8a-569396dd9aea
		summarizeBy: none
		sourceColumn: Observaciones

		annotation SummarizationSetBy = Automatic

	column 'Tipo pedido'
		dataType: string
		lineageTag: f6b70470-7ae6-4f78-9300-f1ad9094b4b1
		summarizeBy: none
		sourceColumn: Tipo pedido

		annotation SummarizationSetBy = Automatic

	column Demanda
		dataType: string
		lineageTag: 037fbcef-15b6-47ab-a05f-05410624eefd
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column KEY_PEDIDO
		dataType: string
		lineageTag: c12e6876-4af4-4800-b0b8-4df82c753fb0
		summarizeBy: none
		sourceColumn: KEY_PEDIDO

		annotation SummarizationSetBy = Automatic

	column KEY_BUDGET
		dataType: string
		lineageTag: 63270cce-711b-4f03-8f47-0c804370092e
		summarizeBy: none
		sourceColumn: KEY_BUDGET

		annotation SummarizationSetBy = Automatic

	column 'Tabla Origen'
		dataType: string
		lineageTag: f0af9815-98ab-4979-af94-b5d97ded17fa
		summarizeBy: none
		sourceColumn: Tabla Origen

		annotation SummarizationSetBy = Automatic

	column 'Proveedor Nombre'
		dataType: string
		lineageTag: 66151cfe-1641-4398-b460-a8c2db4922a1
		summarizeBy: none
		sourceColumn: Proveedor Nombre

		annotation SummarizationSetBy = Automatic

	column ERROR_KB
		dataType: string
		lineageTag: 908a0b74-4f90-4df4-8947-da5f581f6c73
		summarizeBy: none
		sourceColumn: ERROR_KB

		annotation SummarizationSetBy = Automatic

	partition PEDIDOS = m
		mode: import
		queryGroup: ARCHIVOS_TRATADOS
		source =
				let
				    Source = PEDIDOS_RAW,
				    Tipado = Table.TransformColumnTypes(Source,{{"Orden", type text}, {"Tagetik", type text}, {"Cantidad", type number}, {"Importe", type number}, {"Fecha Pedido", type date}, {"Documento Compras", type text}, {"Texto de cabecera", type text}, {"Solicitud de Pedido", type text}, {"Sociedad", type text}, {"Contrato Marco", type text}, {"Proveedor", type text}, {"Solicitante", type text}, {"Número de imputación", type text}, {"Texto de posición", type text}, {"Fecha de Entrega", type date}, {"Indicador Liberación", type text}, {"Indicador de borrado", type text}, {"Tipo pedido", type text}, {"Demanda", type text}, {"Ignorar", type text}, {"Observaciones", type text}, {"Posición", type text}}),
				    Renombrado = Table.RenameColumns(Tipado,{{"Importe", "Coste"}, {"Fecha Pedido", "Fecha"}}),
				    #"Sanitizar Proveedor" = Table.ReplaceValue(Renombrado,null,"-",Replacer.ReplaceValue,{"Proveedor"}),
				    #"Sanitizar proveedor 2" = Table.ReplaceValue(#"Sanitizar Proveedor","","-",Replacer.ReplaceValue,{"Proveedor"}),
				    #"Add KEY_PEDIDO" = Table.AddColumn(#"Sanitizar proveedor 2", "KEY_PEDIDO", each [Documento Compras]&"_"&[Posición]&"_"&[Orden]),
				    #"Add KEY_BUDGET" = Table.AddColumn(#"Add KEY_PEDIDO", "KEY_BUDGET", each [Orden]&"_"&[Tagetik]),
				    #"Tipado 2" = Table.TransformColumnTypes(#"Add KEY_BUDGET",{{"KEY_BUDGET", type text}, {"KEY_PEDIDO", type text}}),
				    Personalizado1 = Table.AddColumn(#"Tipado 2", "Proveedor Nombre", each
				     let
				             match = Table.SelectRows(PROVEEDORES, (p) => p[Proveedor] = [Proveedor]),
				             firstMatch = if Table.RowCount(match) > 0 then match{0}[Nombre] else [Proveedor]
				    in
				        firstMatch
				),
				    #"Add ERROR_KB (vlookup)" = Table.AddColumn(#"Personalizado1", "ERROR_KB", each
				     let
				        match = Table.SelectRows(PRESUPUESTO, (r) => r[KEY_BUDGET] = [KEY_BUDGET] and r[Año] = Date.Year(AÑO_ACTUAL)),
				        firstMatch = if Table.RowCount(match) > 0 then null else true
				    in
				        firstMatch
				),
				    Filtrado = Table.SelectRows(#"Add ERROR_KB (vlookup)", each ([Ignorar] = null)),
				    #"Add TABLA_ORIGEN" = Table.AddColumn(Filtrado, "Tabla Origen", each "Pedidos", type text)
				in
				    #"Add TABLA_ORIGEN"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

