table Fechas_LB
	lineageTag: 51975e5b-324d-4379-b829-1b16490c75b8

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 88d6963e-0e2c-4117-af50-9b5b119766f1
		summarizeBy: none
		sourceColumn: Date

		variation Variación
			isDefault
			relationship: 9afff7a6-45af-424d-93ba-3f6f3cd49e3d
			defaultHierarchy: LocalDateTable_170ca19b-ffb1-4833-b8e0-ada47aa29e09.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date_1er_día_mes
		dataType: dateTime
		formatString: Long Date
		lineageTag: f0b404d0-eadd-4d8b-8b20-bd0aa3ce80e3
		summarizeBy: none
		sourceColumn: Date_1er_día_mes

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date_ult_día_mes
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc68ebf5-69be-49a5-9e49-d7c8856a8ec9
		summarizeBy: none
		sourceColumn: Date_ult_día_mes

		variation Variación
			isDefault
			relationship: 419d4a2e-ad23-4b39-bdf3-d78754d6253d
			defaultHierarchy: LocalDateTable_050c3977-02ff-49be-a013-21f02b82b1a7.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MesNombreComp
		dataType: string
		lineageTag: 6dd8cf5b-46c7-40bd-a6d7-7e52de004e00
		summarizeBy: none
		sourceColumn: MesNombreComp
		sortByColumn: MesNumero

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MesNombreCorto
		dataType: string
		lineageTag: 71efc903-031a-449b-89c5-5bf3d6682a01
		summarizeBy: none
		sourceColumn: MesNombreCorto
		sortByColumn: MesNumero

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MesNumero
		dataType: int64
		formatString: 0
		lineageTag: 0bdb8a88-172a-403f-bd1a-c2d12b4455f6
		summarizeBy: sum
		sourceColumn: MesNumero

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: int64
		formatString: 0
		lineageTag: dbb99190-904e-43bb-84cd-6124d3fa9c15
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column SERVICE_P
		dataType: string
		lineageTag: cadfe7f9-a41d-4831-8757-a0c43df8f5d6
		summarizeBy: none
		sourceColumn: SERVICE_P

		annotation SummarizationSetBy = Automatic

	column AñoContrato
		dataType: string
		lineageTag: ae09c48f-0379-4602-bea8-1529eea43b60
		summarizeBy: none
		sourceColumn: AñoContrato

		annotation SummarizationSetBy = Automatic

	column Mes_Año
		dataType: string
		lineageTag: 3182f993-c36b-423c-8579-95237ac001d1
		summarizeBy: none
		sourceColumn: Mes_Año

		annotation SummarizationSetBy = Automatic

	column Mes_Año_v2
		dataType: string
		lineageTag: 9d1c64c9-7ade-4bc9-9145-fe5249e3cbdc
		summarizeBy: none
		sourceColumn: Mes_Año_v2

		annotation SummarizationSetBy = Automatic

	column Periodo_num
		dataType: int64
		formatString: 0
		lineageTag: 2fdee008-3350-4ea9-bd11-afc34e0d82e6
		summarizeBy: sum
		sourceColumn: Periodo_num

		annotation SummarizationSetBy = Automatic

	column Periodo_num_order
		dataType: string
		lineageTag: 1cba80fa-4686-42eb-bb49-52218461da7b
		summarizeBy: none
		sourceColumn: Periodo_num_order

		annotation SummarizationSetBy = Automatic

	column Periodo
		dataType: string
		lineageTag: 2a14651f-211a-488f-bbec-992b91f5ced5
		summarizeBy: none
		sourceColumn: Periodo

		annotation SummarizationSetBy = Automatic

	column Anio_chart
		dataType: string
		lineageTag: c0c1ea48-d9aa-4620-82e2-4edf1bae0cbe
		summarizeBy: none
		sourceColumn: Anio_chart

		annotation SummarizationSetBy = Automatic

	column 'Periodo Contrato'
		dataType: string
		lineageTag: 95acf96f-8b44-4628-9d7d-4d8fc406d54e
		summarizeBy: none
		sourceColumn: Periodo Contrato

		annotation SummarizationSetBy = Automatic

	partition Fechas_LB = m
		mode: import
		queryGroup: 'Parámetros globales'
		source =
				let
				    Duracion = Duration.TotalDays (FF-FI) + 1,
				    ListaFechas = List.Dates(FI,Duracion,#duration(1,0,0,0)),
				    TablaFechas = Table.FromList(ListaFechas, Splitter.SplitByNothing(), type table [Date = date], null, ExtraValues.Error),
				    #"Inicio del mes insertado" = Table.AddColumn(TablaFechas, "Date_1er_día_mes", each Date.StartOfMonth([Date]), type date),
				    Personalizado1 = Table.AddColumn(#"Inicio del mes insertado", "Date_ult_día_mes", each Date.EndOfMonth([Date]), type date),
				    ColumnaMes = Table.AddColumn(Personalizado1,"MesNombreComp", each Date.MonthName([Date]), type text),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(ColumnaMes,{{"MesNombreComp", Text.Proper, type text}}),
				    #"Agregar columna personalizada" = Table.AddColumn(#"Poner En Mayúsculas Cada Palabra", "MesNombreCorto", each Text.Start(Text.Proper(Date.ToText([Date], "MMM")), 3), type text),
				    ColumnaNroMes = Table.AddColumn(#"Agregar columna personalizada","MesNumero", each Date.Month([Date]), Int64.Type),
				    ColumnaAño = Table.AddColumn(ColumnaNroMes,"Año", each Date.Year([Date]), Int64.Type),
				    #"Columna condicional agregada" = Table.AddColumn(ColumnaAño, "SERVICE_P", each if [Date] >= FI and [Date] < Date.From(DateTime.LocalNow()) then 1 else 0),
				    #"Columna condicional agregada1" = Table.AddColumn(#"Columna condicional agregada", "AñoContrato", each if [MesNumero] >= StartofFiscalYear then "Año " & Text.From([Año] + 1 - 2021) else "Año " & Text.From([Año] - 2021)),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columna condicional agregada1","Año 0",null,Replacer.ReplaceValue,{"AñoContrato"}),
				    #"Columna combinada insertada" = Table.AddColumn(#"Valor reemplazado", "Mes_Año", each Text.Combine({"", [MesNombreComp], " ", Text.From([Año], "es-ES")}), type text),
				    #"Texto insertado después del delimitador1" = Table.AddColumn(#"Columna combinada insertada", "Mes_Año_v2", each Text.AfterDelimiter(Text.From([Date], "es-ES"), "/"), type text),
				    Periodo_num = Table.AddColumn(#"Texto insertado después del delimitador1", "Periodo_num", each if [MesNumero] >= StartofFiscalYear then [MesNumero] - StartofFiscalYear + 1 else if [MesNumero] < StartofFiscalYear then [MesNumero] - StartofFiscalYear + 12 + 1 else null, type text),
				    #"Columna condicional agregada2" = Table.AddColumn(Periodo_num, "Periodo_num_order", each if [AñoContrato] = null then null else [Periodo_num]),
				    #"Texto insertado después del delimitador" = Table.AddColumn(#"Columna condicional agregada2", "Periodo", each "P" & Number.ToText([Periodo_num]), type text),
				    #"Texto remplazado insertado" = Table.AddColumn(#"Texto insertado después del delimitador", "Anio_chart", each Text.Replace([AñoContrato], "ño ", "") & "-" & [Periodo] & " " & [Mes_Año_v2], type text),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Texto remplazado insertado",{{"Periodo_num", Int64.Type}}),
				    #"Periodo Contrato" = Table.AddColumn(#"Tipo cambiado","Periodo Contrato", each Text.AfterDelimiter([Anio_chart], "-"), type text)
				in
				    #"Periodo Contrato"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

