table 'Parametros KGI11'
	excludeFromModelRefresh
	lineageTag: 6490dd06-4b44-4ca9-b132-b1cd78767813

	column Prioridad
		dataType: string
		lineageTag: 42806245-f120-4e5d-8abb-89ce8570c72f
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'T. Resolución Máximo (Jornadas laborales)'
		dataType: int64
		formatString: 0
		lineageTag: 1c875bcf-cf4a-4b1f-b988-4915b833d495
		summarizeBy: sum
		sourceColumn: T. Resolución Máximo (Jornadas laborales)

		annotation SummarizationSetBy = Automatic

	column '% cumplimiento Objetivo'
		dataType: double
		lineageTag: 7835a568-3621-4f97-b22d-64e44e898055
		summarizeBy: sum
		sourceColumn: % cumplimiento Objetivo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pesos %'
		dataType: double
		lineageTag: 79fef44b-8645-4bb6-9218-f0df5f1c58d2
		summarizeBy: sum
		sourceColumn: Pesos %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Puntos de KGI11'
		dataType: string
		lineageTag: 369de3b2-0196-41ae-93d1-b5506ecd922a
		summarizeBy: none
		sourceColumn: Puntos de KGI11

		annotation SummarizationSetBy = Automatic

	column KGI
		dataType: string
		lineageTag: 8ef31e65-15b0-41ff-8344-24a92adccbb5
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	partition 'Parametros KGI11-efbac5a5-2860-4c30-9a16-04cd7ccd28f6' = m
		mode: import
		queryGroup: Parametros
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(globalPath & kgi & xlsx), null, true),
				    #"P_KGI11_Sheet" = Origen{[Item="P_KGI11",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"P_KGI11_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Prioridad", type text}, {"T. Resolución Máximo (Jornadas laborales)", Int64.Type}, {"% cumplimiento Objetivo", type number}, {"Pesos %", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

