table 'Parametros Generales KGIs'
	excludeFromModelRefresh
	lineageTag: 2c92b736-c1e8-48a1-b036-8c15bf2e17c4

	column KGI
		dataType: string
		lineageTag: 5a8c9452-f3b5-40bd-886a-6c2b5db093a9
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	column Descripción
		dataType: string
		lineageTag: 402209ba-7e1b-4192-a9a4-767257b87c49
		summarizeBy: none
		sourceColumn: Descripción

		annotation SummarizationSetBy = Automatic

	column 'Puntos por KGI'
		dataType: int64
		formatString: 0
		lineageTag: 86c1bd79-ab92-4a2d-ac57-e83d11ba955f
		summarizeBy: sum
		sourceColumn: Puntos por KGI

		annotation SummarizationSetBy = Automatic

	column 'Puntos Obtenidos' = ('Parametros Generales KGIs'[Puntos por KGI]*1)
		formatString: 0
		lineageTag: 513b7e99-f72a-435d-bf01-c7e41f6194e5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Parametros Generales KGIs-0a9d686e-8b1f-4685-94bc-a1c8ecae7c87' = m
		mode: import
		queryGroup: Parametros
		source =
				let
				    Source = Excel.Workbook(Web.Contents(globalPath & kgi & xlsx), null, true),
				    #"P_GS_KGIS_Sheet" = Source{[Item="P_GS_KGIS",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"P_GS_KGIS_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"KGI", type text}, {"Descripción", type text}, {"Puntos por KGI", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

