table 'Parametros KGI12_P'
	lineageTag: 6a4403c0-937c-4796-865c-11b964e0d94a

	column 'Prioridad Hitos Evolutivos'
		dataType: string
		lineageTag: ac4c80a2-0910-4c7a-a4d4-6a3a6f5ed653
		summarizeBy: none
		sourceColumn: Prioridad Hitos Evolutivos

		annotation SummarizationSetBy = Automatic

	column 'Tasa de Desviación Máxima'
		dataType: double
		lineageTag: 36159fee-8a90-4ef3-8f79-06423b71b16f
		summarizeBy: sum
		sourceColumn: Tasa de Desviación Máxima

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% cumplimiento Objetivo'
		dataType: double
		lineageTag: 0cf04cf9-b14a-4ed0-b178-045ae6bddf36
		summarizeBy: sum
		sourceColumn: % cumplimiento Objetivo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pesos %'
		dataType: double
		lineageTag: cada592c-2289-4722-8a62-11255ca178a6
		summarizeBy: sum
		sourceColumn: Pesos %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Puntos de KGI12'
		dataType: int64
		formatString: 0
		lineageTag: dfbf7aec-f9a4-452c-a1c0-5c0de0192659
		summarizeBy: sum
		sourceColumn: Puntos de KGI12

		annotation SummarizationSetBy = Automatic

	column KGI
		dataType: string
		lineageTag: f7734482-a72e-4087-afb4-87a12012fa15
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	partition 'Parametros KGI12_P-8c8b160a-f046-428b-90cf-1fd805bf258f' = m
		mode: import
		queryGroup: Parametros
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(globalPath & kgi & xlsx), null, true),
				    #"P_KGI12 PRO_Sheet" = Origen{[Item="P_KGI12 PRO",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"P_KGI12 PRO_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Prioridad Hitos Evolutivos", type text}, {"Tasa de Desviación Máxima", type number}, {"% cumplimiento Objetivo", type number}, {"Pesos %", type number}, {"Puntos de KGI12", Int64.Type}, {"KGI", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

