table 'PRO - Alegaciones del Servicio KGI22'
	lineageTag: 1251323d-827b-4a6b-8670-a91920fe3fc6

	column 'ID Alegación'
		dataType: string
		lineageTag: d281bba8-b574-4741-84e6-d9f69907fdd2
		summarizeBy: none
		sourceColumn: ID Alegación

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: b684e055-4dd4-40e2-be24-1e8ab733aafc
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Entrada alegada'
		dataType: string
		lineageTag: 0f108c70-2bc1-468a-9ef8-aaa58d66146b
		summarizeBy: none
		sourceColumn: Entrada alegada

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: aea079d6-f790-495d-b1ba-44d75233031c
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: string
		lineageTag: 629b0e98-3376-4f90-9795-0c2dae6f7dda
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		annotation SummarizationSetBy = Automatic

	column Clasificación
		dataType: string
		lineageTag: 703e8e19-ac91-44b6-b82d-3da98beb1a12
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 6a7b938c-48b6-44c7-a073-275fbfab57e0
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: 8b4b7482-5f2f-471e-a1e2-605a4f2cbfa5
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: def6c512-ff20-4ff0-a8e9-7c85ecb43ed4
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: a7e5be5c-810f-4b98-a88e-4d1cb835925d
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 27d8e676-4c08-4623-8fad-965b6e4c36db
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado - Copy

		variation Variación
			isDefault
			relationship: 1c56f23f-f125-4424-ac5c-6d70bedc7da0
			defaultHierarchy: LocalDateTable_c56f3f91-7a68-4935-89c7-b9223bd66da4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Solicitante
		dataType: string
		lineageTag: dacbbba7-ce3f-4c2d-8ec6-4d2a7df50256
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column 'Comentarios AE'
		dataType: string
		lineageTag: 937b255f-64db-4598-b0c8-bcead397cfc5
		summarizeBy: none
		sourceColumn: Comentarios AE

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI22-a82fb82a-d193-4cf7-930a-5c80b5df6989' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Source = #"PRO - Alegaciones del Servicio",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([ANS] = "KGI 2-2"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

