table 'PRO - Incidencias con SLA_A'
	lineageTag: d1296dd7-561b-4c3c-b048-cf2dfed4e3d6

	column Número
		dataType: string
		lineageTag: 1e7b3017-1cc9-4fae-ba47-979ac9756b45
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 8de15a88-8bd7-4db6-8658-a6eae6ac6e06
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Subcategoría
		dataType: string
		lineageTag: 0f7b5381-cbda-4d36-bf06-33f798fa811c
		summarizeBy: none
		sourceColumn: Subcategoría

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: c47b8288-6bae-4f64-ad76-af2d2218f3d1
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 08918815-4d4e-4224-adb3-09893573e6d6
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: 618c746f-c13d-4acd-8351-8b96ded3f049
			defaultHierarchy: LocalDateTable_9956014c-20d7-4ffd-aad1-abaa1933034e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Resuelto
		dataType: dateTime
		formatString: General Date
		lineageTag: aa70f034-6649-400e-b5c9-6493a839dcaa
		summarizeBy: none
		sourceColumn: Resuelto

		variation Variation
			isDefault
			relationship: 3c6d2f1d-93d4-40c1-b28c-e59129435d72
			defaultHierarchy: LocalDateTable_9b37082e-1340-4c52-84e6-f843f0d5ab8c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 6df64914-ed78-4eb0-8e87-e152b723712b
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8146212a-5560-46cc-a6d9-66f50230c408
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: a87743ab-58f3-4a78-a0a8-148e9e31ee05
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: 50d916eb-71f9-454b-9be4-1e63dc6b4feb
			defaultHierarchy: LocalDateTable_842716ec-50cb-4aa3-9510-61e1eea618e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Etapa
		dataType: string
		lineageTag: 95404b74-1592-4193-862d-2222a4323740
		summarizeBy: none
		sourceColumn: Etapa

		annotation SummarizationSetBy = Automatic

	column 'Código de resolución'
		dataType: string
		lineageTag: bb8607f0-4f07-4f93-91f4-3cd0c531a20b
		summarizeBy: none
		sourceColumn: Código de resolución

		annotation SummarizationSetBy = Automatic

	column 'Volver a abrir recuento'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1333af4b-edcb-40cb-9982-40958af241c4
		summarizeBy: none
		sourceColumn: Volver a abrir recuento

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Solución'
		dataType: string
		lineageTag: c03489c9-d998-495f-8f8e-4e60d3f6cdd9
		summarizeBy: none
		sourceColumn: Tipo de Solución

		annotation SummarizationSetBy = Automatic

	column Duración_1
		dataType: int64
		formatString: 0
		lineageTag: 0833747a-a606-4e43-8415-ed38a78a7ecc
		summarizeBy: sum
		sourceColumn: Duración_1

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: string
		lineageTag: 2fcab259-d1d6-405b-82a5-527799b4eb64
		summarizeBy: none
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: int64
		formatString: 0
		lineageTag: b0f6c871-4142-42c4-ab88-e638cd14ee21
		summarizeBy: sum
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column 'ID de correlación'
		dataType: string
		lineageTag: e66729c8-32c8-4615-ad55-facdc57826d8
		summarizeBy: none
		sourceColumn: ID de correlación

		annotation SummarizationSetBy = Automatic

	column Principal
		dataType: string
		lineageTag: 72bef3a5-3d54-4ded-819d-6fdb68ac17af
		summarizeBy: none
		sourceColumn: Principal

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: b401c054-eb9f-49f4-819c-afcdb1efb3d7
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 49c4617a-3c79-4271-865c-0e233353f39a
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: a2a3037f-e24a-4c95-a319-37ce8e6ce8f1
			defaultHierarchy: LocalDateTable_87c670c4-cd2f-42d4-9803-ad740d09bf58.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 6381f765-b8c7-43a5-bde9-c15ab406a3b3
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column 'Estado del incidente'
		dataType: string
		lineageTag: 28e548b7-5341-46c6-b365-0c35f4f25798
		summarizeBy: none
		sourceColumn: Estado del incidente

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA_A-975bedd0-f3ff-45c0-b38f-d15ceeede48f' = m
		mode: import
		queryGroup: KGIs_II
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(globalPath & incidencias & xlsx), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Número", type text}, {"Breve descripción", type text}, {"Subcategoría", type text}, {"Prioridad", type text}, {"Abierto", type datetime}, {"Cerrado", type datetime}, {"Resuelto", type datetime}, {"Duración", Int64.Type}, {"Duración del negocio", Int64.Type}, {"Infringido", type logical}, {"Tiempo original de incumplimiento", type datetime}, {"Estado del incidente", type text}, {"Etapa", type text}, {"Código de resolución", type text}, {"Volver a abrir recuento", Int64.Type}, {"Tipo de Solución", type text}, {"Duración_1", Int64.Type}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Changed Type",{{"Volver a abrir recuento", type logical}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = PRO - Incidencias con SLA_A

	annotation PBI_NavigationStepName = Navegación

