table 'PRO - Planificaciones PRJ y ENH con SLA_M'
	lineageTag: 109e7e29-1534-4d47-a62d-c06c9917b558

	column Demanda
		dataType: string
		lineageTag: efa6d7a3-5d5d-40c1-b9dc-efe473e8cb89
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 97b62488-4e6b-4ed9-9064-c0e2b56b747a
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 827c393d-97b7-4f51-9873-6c0337f04770
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9476ef8a-5877-427a-b48b-1a93e01f1741
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variation
			isDefault
			relationship: fd4b799a-e636-4850-9165-5103041c1f6e
			defaultHierarchy: LocalDateTable_cbe44c7a-b1cf-4d00-a27e-e5063836a862.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 4eba730b-bc1b-4a4c-83d1-4760e9ae8b55
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: 6770b43e-0534-4729-a041-62edffecbe3f
		summarizeBy: none
		sourceColumn: Inicio

		variation Variation
			isDefault
			relationship: 2fc0c468-7c8c-4a4a-8d0c-cfdca082f41f
			defaultHierarchy: LocalDateTable_3b7dc721-8d9d-4a09-9c14-c575fb4024ba.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: 32c8721f-5870-4a95-aaca-885bddcc574c
		summarizeBy: none
		sourceColumn: Fin

		variation Variation
			isDefault
			relationship: ae7d02c7-d061-4a82-b922-a24f4616d1cc
			defaultHierarchy: LocalDateTable_e52f7151-aa87-4747-a6fb-0c6eebaf8376.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1ad7c574-0604-4754-bce4-40443619e936
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: ec56ba0a-0bdc-48be-9b65-11f245a7f2fe
			defaultHierarchy: LocalDateTable_c2eadd93-34ab-4f0b-8e7d-d7f09e29571b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: b89a7248-8cda-4cdb-844b-fa0c33d89d43
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: a8b0b940-9db3-4cdb-8e34-9cc0cdda63cf
			defaultHierarchy: LocalDateTable_909091cb-d835-454e-a1a9-e5c4cc0f6e39.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: 9cb6cbda-a076-418e-a458-685b119bf305
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: a472676e-2e53-4e33-a8ef-5106c4a1199d
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 0de6eafc-af73-46bc-a9d9-868dea4db072
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 69564ece-bd48-4c3c-908c-f5fac8dcc051
		summarizeBy: none
		sourceColumn: Fecha fin real - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: 97092955-f558-439a-a740-e93d0c7611ae
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: 6491d785-240e-4e02-b552-0268c70baf5d
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Duración Planificada LB'
		dataType: double
		lineageTag: e55e3d9e-6217-4436-a1af-019a3f2cab67
		summarizeBy: sum
		sourceColumn: Duración Planificada LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real LB'
		dataType: double
		lineageTag: a36a2861-44ac-48f3-b872-1c5a1551ae5d
		summarizeBy: sum
		sourceColumn: Duración real LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa de desviación'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 04cbbdd1-abb5-4b79-b86a-a4f733e0a82b
		summarizeBy: sum
		sourceColumn: Tasa de desviación

		annotation SummarizationSetBy = Automatic

	column 'Estimación incumplida'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ff542d31-0764-4d22-94a4-a15ff9bb2d59
		summarizeBy: none
		sourceColumn: Estimación incumplida

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: b34fc185-0563-4bc3-98c4-72b20df68db6
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: 54c94ae3-2932-4a5d-885f-1a94eff38929
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Servicio'
		dataType: string
		lineageTag: c5edd640-6b57-4de3-8816-3bbaf32aab25
		summarizeBy: none
		sourceColumn: Tipo de Servicio

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 2ffe9ba0-5dc2-4a15-86e7-71fe6ef14d58
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Lote
		dataType: string
		lineageTag: 90ab0898-6e4c-4374-ad13-6a0843902232
		summarizeBy: none
		sourceColumn: Lote

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Planificaciones PRJ y ENH con SLA_M'[Número])
		lineageTag: 61b4ed3d-76f4-48d4-83ad-e744e5c813c2
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Fecha límite planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 36b89178-3853-4968-8f39-6f8f7208bb60
		summarizeBy: none
		sourceColumn: Fecha límite planificada

		variation Variación
			isDefault
			relationship: 8c0074b4-0a08-463a-a79e-3819a6445621
			defaultHierarchy: LocalDateTable_61d7a5a4-2611-4743-bf2e-c9ded1a254f2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Nombre de proyecto'
		dataType: string
		lineageTag: 287184bc-f8a4-4bb3-a6ce-35aa95264888
		summarizeBy: none
		sourceColumn: Nombre de proyecto

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones PRJ y ENH con SLA_M-c4488ef7-b8a5-455a-a73c-cefca85f53ea' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    URL = sharepointsource & Entorno & sharepointsource2 & prjs & xlsx,
				Origen = Excel.Workbook(Web.Contents(URL), null, true),
				#"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Promoted Headers",{{"Fecha de finalización planificada", "Fecha límite planificada"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado1",{{"Demanda", type text}, {"Número", type text}, {"Tipo de Proyecto", type text}, {"Prioridad", type text}, {"Jefe de proyecto (Project Manager)", type text}, {"Aplicación de Negocio ", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha límite planificada", type datetime}, {"Nombre", type text}, {"Inicio", type datetime}, {"Fin", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Nombre de proyecto", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Tipo de Servicio", each "Proyectos"),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"Nombre de proyecto", "Nombre de PRJ o MEJ"}}),
				
				    //Une tablas de Mejoras y Proyectos de Mantenimiento de Aplicaciones
				    #"Appended Query" = Table.Combine({#"Renamed Columns", #"PRO - Planificaciones ENH"}),
				    #"Appended Query1" = Table.Combine({#"Appended Query", #"PRO - Planificaciones MA"}),
				
				    //Homologa las prioridades
				    #"AllReplace" = [#"1 - Crítica" = "Alta", #"2 - Alta" = "Alta", #"3 - Moderada" = "Media",#"4 - Baja" = "Baja",#"5 - Muy Baja" = "Baja"],    
				    #"Replaced Value" = Table.TransformColumns( #"Appended Query1",{{"Prioridad",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    
				    //Nueva columna "Fecha (1er día de mes)"
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced Value", "Fecha fin real", "Fecha fin real - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Fecha fin real - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Fecha fin real - Copy", Date.StartOfMonth, type date}}),
				
				    //Nueva columna "Duración planificada de línea base"    
				    #"Added Custom1" = Table.AddColumn(#"Calculated Start of Month", "Duración Planificada LB", each [Fin]-[Inicio]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Duración Planificada LB", type number}}),
				
				   //Nueva columna "Duración real para cálculo con planificación de línea base" 
				    #"Added Custom2" = Table.AddColumn(#"Changed Type1", "Duración real LB", 
				    each if [Nombre] <> "" then ([Fecha fin real]-[Fecha de inicio real]) else ""),
				    
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom2",{{"Duración real LB", type number}}),
				
				    //Nueva columna "Tasa de desviación"
				    #"Added Custom3" = Table.AddColumn(#"Changed Type2", "Tasa de desviación",
				    each if [Nombre] = "" then (([Duración real]-[Duración planificada])/[Duración planificada]) 
				                          else (([Duración real LB]-[Duración Planificada LB])/[Duración Planificada LB])),
				 
				    //Quita los proyectos y mejoras que tienen por error duración real o planificada = 0
				    #"Filtered Rows1" = Table.SelectRows(#"Added Custom3", each ([Duración real] <> 0) and ([Duración planificada] <> 0)),
				
				    //Columna "Estimación incumplida"
				    #"Added Custom4" = Table.AddColumn(#"Filtered Rows1", "Estimación incumplida",
				    each if [Prioridad]="Alta" and [Tasa de desviación]>0 then "TRUE" else
				         if [Prioridad]="Media" and [Tasa de desviación]>0.05 then "TRUE" else
				         if [Prioridad]="Baja" and [Tasa de desviación]>0.10 then "TRUE" else "FALSE"),
				
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom4",{{"Tasa de desviación", Percentage.Type}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type3", {"Número"}),
				
				    //Une con las alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Removed Duplicates", {"Número"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"Estado"}, {"PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Estimación incumplida" si la alegación es aceptada
				    #"Replaced Value5" = Table.ReplaceValue(#"Renamed Columns1",each [Estimación incumplida],each if [Estado_Alegación] = "1 - Aprobada" then "FALSE" else [Estimación incumplida],Replacer.ReplaceValue,{"Estimación incumplida"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value5",{{"Estimación incumplida", type logical}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Changed Type4", {"Aplicación de Negocio "}, Lote_Aplicacion_relacion, {"Aplicación de negocio"}, "Lote_Aplicación_relación", JoinKind.LeftOuter),
				    #"Se expandió Lote_Aplicación_relación" = Table.ExpandTableColumn(#"Consultas combinadas", "Lote_Aplicación_relación", {"Lote"}, {"Lote_Aplicación_relación.Lote"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Se expandió Lote_Aplicación_relación",{{"Lote_Aplicación_relación.Lote", "Lote"}})
				in
				    #"Columnas con nombre cambiado"
				```

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = PRO - Planificaciones PRJ y ENH con SLA_M

	annotation PBI_NavigationStepName = Navegación

