table 'PRO - Incidencias con SLA_P_y_A_Abiertas_KGI13'
	lineageTag: 47697943-8a95-4600-8e94-de491db9f6bb

	column Número
		dataType: string
		lineageTag: 9c9ee115-7011-4b21-8882-5fa4cbcb785e
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 9f012fa0-d121-44b0-974d-b03f2fd88ac2
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 7d28ae6b-be23-4c0d-91bb-07fcc9eb8979
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 68bf7d8a-22ef-42c5-88cb-492a4fda370b
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: 27a3928f-9e37-4c7f-86d1-5378152cd18e
			defaultHierarchy: LocalDateTable_e232f784-546d-4a9c-80ad-eb06e1df0355.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		lineageTag: 6e4577c5-faef-4e4a-a1c4-c0e4d8fba35e
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bbcfc1d6-ddd9-449e-8386-7e793e55a3d6
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 543a95d1-4946-48b0-9a93-5d227cf4f1e6
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: ae03dd8b-3244-49fc-a4e8-60414ab8a646
			defaultHierarchy: LocalDateTable_9e9f0108-fb5b-45f2-81f5-aee5a692e792.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: b9801563-f5c4-4058-b56f-4acf3f2160c7
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: string
		lineageTag: 7dc88b9c-41b5-4654-98c0-30d578b66f56
		summarizeBy: none
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 846bd9ae-dc7e-45f7-a4c4-15f64c273132
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: ad52960f-11b0-45f4-ad66-e41bdc6458e4
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column Resuelto
		dataType: dateTime
		formatString: General Date
		lineageTag: 7c43a255-97bc-42b8-a8bc-6935a56a5817
		summarizeBy: none
		sourceColumn: Resuelto

		variation Variación
			isDefault
			relationship: 50717696-0c99-4de1-ba62-dffc4b3e707b
			defaultHierarchy: LocalDateTable_e44cffd7-7954-44a3-9a73-0bb36ec9435c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Código de resolución'
		dataType: string
		lineageTag: 8dec1b62-730c-4840-9029-87680318dee0
		summarizeBy: none
		sourceColumn: Código de resolución

		annotation SummarizationSetBy = Automatic

	column 'Volver a abrir recuento'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8b9e345c-01f8-4fb5-87dd-07a52a1a703e
		summarizeBy: none
		sourceColumn: Volver a abrir recuento

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Solución'
		dataType: string
		lineageTag: 5b105210-93ad-41d9-8ee3-fa749a2ea8f9
		summarizeBy: none
		sourceColumn: Tipo de Solución

		annotation SummarizationSetBy = Automatic

	column 'ID de correlación'
		dataType: string
		lineageTag: 689808ec-07b0-4c44-a942-1efecd239d6e
		summarizeBy: none
		sourceColumn: ID de correlación

		annotation SummarizationSetBy = Automatic

	column Principal
		dataType: string
		lineageTag: f7a5a45a-cd96-4715-9ec2-5de010bd1235
		summarizeBy: none
		sourceColumn: Principal

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: 55d7fc19-088d-4c68-9071-303e54266d9e
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: string
		lineageTag: e2f4b799-3ef2-4068-a4c4-ceb5b5e18e2f
		summarizeBy: none
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column 'Estado de la incidencia'
		dataType: string
		lineageTag: de1f1550-b2b1-47bb-b6bb-1c23df7636bd
		summarizeBy: none
		sourceColumn: Estado de la incidencia

		annotation SummarizationSetBy = Automatic

	column Etapa
		dataType: string
		lineageTag: b9b4972d-96cc-452f-aabe-af28fd94b546
		summarizeBy: none
		sourceColumn: Etapa

		annotation SummarizationSetBy = Automatic

	column Duración_1
		dataType: string
		lineageTag: 37c215e8-cf1b-4700-b09e-cbf7d78d84b9
		summarizeBy: none
		sourceColumn: Duración_1

		annotation SummarizationSetBy = Automatic

	column 'Lote_Aplicación_relación.Lote'
		dataType: string
		lineageTag: b96391e4-9309-4d86-884c-7f7b08e5506a
		summarizeBy: none
		sourceColumn: Lote_Aplicación_relación.Lote

		annotation SummarizationSetBy = Automatic

	column 'Abierta - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b9de1da9-9c3d-4dd3-87fa-18dead25b39e
		summarizeBy: none
		sourceColumn: Abierta - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA_P_y_A_Abiertas_KGI13'[Número])
		lineageTag: bb6f24c5-a933-46b3-8574-7abcb3b65b23
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: ec9e133a-2731-4049-92c6-5f06f5630eef
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 8d4c1389-6fb3-4bdf-9402-ed0eca8763bc
			defaultHierarchy: LocalDateTable_a7c0313e-71d6-426f-afc9-6aa18f6f9031.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: a5516c27-a27c-4d61-97c2-9c0019bb2fe4
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column 'Estado del incidente'
		dataType: string
		lineageTag: 1d485e48-fc5f-4775-86ee-e0b70699581c
		summarizeBy: none
		sourceColumn: Estado del incidente

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA_P_y_A_Abiertas_KGI13-049ff6fb-5618-4fef-8ac0-00cc3137868a' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Source = #"PRO - Incidencias con SLA_P_y_A_Abiertas",
				
				    //Unificar Prioridades, según definición del KGI13
				    #"Replaced Value" = Table.ReplaceValue(Source, "Crítica", "Alta",Replacer.ReplaceText,{"Prioridad"})
				  
				in
				    #"Replaced Value"
				```

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = PRO - Incidencias con SLA_P_y_A_Abiertas_KGI13

	annotation PBI_NavigationStepName = Navigation

