table 'PRO - Jira - Defectos con SLA - UAT - Detalle'
	lineageTag: cbbb107a-773f-455a-8df8-2610965a41b6

	column Lote
		dataType: string
		lineageTag: 7f6ea550-c573-4fb6-9f88-756f03e94ded
		summarizeBy: none
		sourceColumn: Lote

		annotation SummarizationSetBy = Automatic

	column Components
		dataType: string
		lineageTag: 268e33a4-cfb6-43f9-9a98-1297230dcd26
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 9197f175-2361-4287-8b2f-0e33c6b99022
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: b796c98f-3a2b-4644-be1a-5f7f5d59a51d
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: a0fcd964-8149-4bf8-adfa-e1138bfb7938
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: c8fd3a0f-9b27-42bc-985c-f0ce3b51c8be
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 306a7a52-154f-4c67-a916-52e608ab6485
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 88a22e21-9fe7-4530-80c9-e9604ea2747a
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: c0a0b91c-499b-42e5-9a1b-cd3d90c2c7ef
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 7db99a60-9ab6-4d58-9d2a-4989389f68c3
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 0216ac39-5be2-451b-9359-dec9140db438
		summarizeBy: none
		sourceColumn: Created

		variation Variación
			isDefault
			relationship: 179750b6-44b9-4eda-a5f1-7869ede4e515
			defaultHierarchy: LocalDateTable_119e4157-ae9d-41ea-97d5-3ffccd440d94.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 2f5d951e-9192-4906-abcb-1bc74ec78b16
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: e3506ed8-a63d-402a-aaf7-86714fb4207b
		summarizeBy: none
		sourceColumn: Resolved

		variation Variación
			isDefault
			relationship: 973888ed-79c7-4d96-b0f1-16c631bd36cd
			defaultHierarchy: LocalDateTable_573383fb-1664-4f20-9e20-f8f8b2693481.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: f1d36f54-666f-4cd8-a554-85fe4c1a747f
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Value (Bugs)'
		dataType: string
		lineageTag: c52eb4d2-3486-4b5d-bdb7-646fed4e63a7
		summarizeBy: none
		sourceColumn: Value (Bugs)

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Status'
		dataType: string
		lineageTag: edc573a4-f2dc-4cbf-8f57-0f09d1be25b8
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9a7a1f8f-266e-4f92-acf7-c67c2a905285
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved

		variation Variación
			isDefault
			relationship: 9cd1a7f2-5207-40fd-9886-bd29ac690626
			defaultHierarchy: LocalDateTable_2f3f2e94-403b-489a-9cce-32ff6cd7e44c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status'
		dataType: string
		lineageTag: 48c43e58-a9f5-4f1d-a198-96d45573e10a
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba'
		dataType: string
		lineageTag: 2255ae1a-051d-4467-a937-df81589b4719
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Pruebas con SLA.Priority'
		dataType: string
		lineageTag: 5a3d557c-8cab-4fa0-a239-59ae321cbbe4
		summarizeBy: none
		sourceColumn: PRO - Jira - Pruebas con SLA.Priority

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Pruebas con SLA.Status'
		dataType: string
		lineageTag: e7078206-afb5-45e5-944a-842d7cba4710
		summarizeBy: none
		sourceColumn: PRO - Jira - Pruebas con SLA.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 12063ee4-635f-4600-8f95-1baa3596dcce
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: 469f5380-8bda-46fb-b3c7-6686f6380482
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Priority'
		dataType: string
		lineageTag: d3c10f60-4088-4fb8-ade2-2399be104029
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Priority

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Defectos con SLA - UAT - Detalle-12eab267-1ac7-4501-b75a-7ffaf3903f0b' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = #"PRO - Jira - Defectos con SLA",
				
				    #"Filtered Rows" = Table.SelectRows(Source, each Text.Contains([#"PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba"], "UAT")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [Estado_Alegación] <> "1 - Aprobada")
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

