table 'PRO - Alegaciones del Servicio KGI21'
	lineageTag: ddbb78d3-9279-49c4-9109-79cf26b52c17

	column 'ID Alegación'
		dataType: string
		lineageTag: 4218b24f-854b-4982-b023-5af6c462490f
		summarizeBy: none
		sourceColumn: ID Alegación

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: efe1b0b9-83eb-4768-83dd-2be5495514bc
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Entrada alegada'
		dataType: string
		lineageTag: c69013e3-85bf-491e-8c1d-e03730651dac
		summarizeBy: none
		sourceColumn: Entrada alegada

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: 5953541e-8a84-4bfa-ae72-9d8834938f78
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: string
		lineageTag: 004c1b73-8ebd-4a00-8355-09271447532e
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		annotation SummarizationSetBy = Automatic

	column Clasificación
		dataType: string
		lineageTag: ca9f9282-0476-42e2-bbd2-97b08195cd7b
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 3d62a741-4a7e-4ded-a924-0e0cd04e0dff
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: d4b843fa-7118-48f9-b879-8a28e396999c
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 5e848941-2231-4057-8cbf-3cc841bc1849
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: d1df66e3-f075-4473-b71a-eeb1dee38b87
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f7cb49cf-1f76-47d6-9d9a-0deefc652f5d
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado - Copy

		variation Variación
			isDefault
			relationship: 68ab0335-55c9-4e98-99b8-c3cbaed208fe
			defaultHierarchy: LocalDateTable_7811f2c6-64e8-4715-b182-7151d8713b83.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Solicitante
		dataType: string
		lineageTag: a697a7c4-f31e-47be-92ad-b87e576ebd33
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column 'Comentarios AE'
		dataType: string
		lineageTag: 2f7c1a4b-5168-4cfd-80fc-7ac38a33d045
		summarizeBy: none
		sourceColumn: Comentarios AE

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI21-b36ba7f8-1741-4732-9cb2-a7f206f9b924' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Source = #"PRO - Alegaciones del Servicio",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([ANS] = "KGI 2-1"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

