table 'PRO - Incidencias con SLA_P_y_A_Abiertas'
	lineageTag: 3e9bf117-b97b-42a9-82d0-8d7cd5978f08

	column Número
		dataType: string
		lineageTag: 715cc7c2-47f8-4ab3-8346-51618461ab82
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: b2d1a3b7-ac3c-4d2d-b203-d0dbcd285ddf
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: dc2ca3a8-fc6d-4ad0-8b78-796b991ea629
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: d99c0261-5f02-49db-a0ba-ebb194caf72c
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 7e60baed-cfb2-42ab-b3cc-86cb76c840d4
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: b1b25c2b-d9ec-42d5-9f1f-501a968ae94e
			defaultHierarchy: LocalDateTable_b0a601c1-f5c2-4f69-9ade-5e19c8ea8131.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		lineageTag: dc8ec644-ad3d-4f2f-b2a1-639d50e3378b
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estado de la incidencia'
		dataType: string
		lineageTag: c76c89be-31da-405d-a0df-397229406c85
		summarizeBy: none
		sourceColumn: Estado de la incidencia

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 9f8f9ccc-0c06-4ea7-a14d-a3963c674115
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 60b5d610-b386-4506-83b3-1677373e821e
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column Resuelto
		dataType: dateTime
		formatString: General Date
		lineageTag: b90a6c12-a9c8-4d11-bf1d-e1b71e4fdd71
		summarizeBy: none
		sourceColumn: Resuelto

		variation Variación
			isDefault
			relationship: ccff2219-0984-4677-b312-6ffb06bf6022
			defaultHierarchy: LocalDateTable_d088e808-064c-4fd0-8a43-79e67ddd13f5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Código de resolución'
		dataType: string
		lineageTag: 930df9d3-64bc-4119-9201-e5183be79637
		summarizeBy: none
		sourceColumn: Código de resolución

		annotation SummarizationSetBy = Automatic

	column 'Volver a abrir recuento'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4c46b0f0-bc1f-4724-8810-e998ed0df9a7
		summarizeBy: none
		sourceColumn: Volver a abrir recuento

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Solución'
		dataType: string
		lineageTag: c07e2411-6d90-4b16-ad53-3ad39c9c73a0
		summarizeBy: none
		sourceColumn: Tipo de Solución

		annotation SummarizationSetBy = Automatic

	column 'ID de correlación'
		dataType: string
		lineageTag: f5e4a7ab-a4ba-48e8-8ccc-911b100b68e8
		summarizeBy: none
		sourceColumn: ID de correlación

		annotation SummarizationSetBy = Automatic

	column Principal
		dataType: string
		lineageTag: 364585c6-7aea-4679-b266-bf28e16fcfc9
		summarizeBy: none
		sourceColumn: Principal

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: 1c3b7f4e-8a0b-4123-916d-ec82e912f05b
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Lote_Aplicación_relación.Lote'
		dataType: string
		lineageTag: 4f311e51-6084-4410-ab23-2fc45a9fb9a9
		summarizeBy: none
		sourceColumn: Lote_Aplicación_relación.Lote

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: string
		lineageTag: 0e513e90-246d-40f4-a581-d8ee71ce6635
		summarizeBy: none
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d3163fc8-8c2b-48f4-85f3-ca3ec4679259
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: c9e0830b-f4a3-461c-ba38-a33222b93273
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variación
			isDefault
			relationship: bf87c8ce-91be-40d7-8e1f-5913fb94500e
			defaultHierarchy: LocalDateTable_fb055cf4-8fb7-4b55-bd23-4ec21d5d32f9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Etapa
		dataType: string
		lineageTag: 0374dada-1ffc-4fe2-8292-d0660a9743e9
		summarizeBy: none
		sourceColumn: Etapa

		annotation SummarizationSetBy = Automatic

	column Duración_1
		dataType: string
		lineageTag: 082765bc-1f08-4428-b12e-acb859e24871
		summarizeBy: none
		sourceColumn: Duración_1

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: string
		lineageTag: 1df40a74-24f6-41bc-a932-3595536dd00f
		summarizeBy: none
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Abierta - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f9a1ea41-0d41-4ddf-b5ff-5ecff4e954cd
		summarizeBy: none
		sourceColumn: Abierta - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA_P_y_A_Abiertas'[Número])
		lineageTag: bd8cb33b-0cd8-40ac-a46d-ddfcc1288e14
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: f84babb8-6a63-44d0-a8d2-2ca2789959c5
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: c931e35c-3eba-4da6-aab0-92a29f000f73
			defaultHierarchy: LocalDateTable_c390814f-41ed-4b72-a579-e9c2eb266f55.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Estado del incidente'
		dataType: string
		lineageTag: c1cd4ce7-cabc-4582-9bfd-060b71c5fd14
		summarizeBy: none
		sourceColumn: Estado del incidente

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: aa6ba840-d3b0-4837-a3bf-1905cb974044
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA_P_y_A_Abiertas-4a3c2bdf-d9cf-4cdd-9832-99d81a25d932' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    URL = sharepointsource & Entorno & sharepointsource2 & incidencias_previas & xlsx,
				    Origen = Excel.Workbook(Web.Contents(URL), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Encabezados promovidos",{{"Usuarios interesados", "Duración del negocio"}, {"Causa probable", "Infringido"}, {"Lista de notas de trabajo", "Tiempo original de incumplimiento"}, {"Estado", "Estado de la incidencia"}, {"Entrada del usuario", "Etapa"}, {"Tiempo de trabajo", "Duración_1"}, {"Número de reasignación", "Porcentaje de negocio trascurrido"}}),
				
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Número", type text}, {"Breve descripción", type text}, {"Subcategoría", type text}, {"Prioridad", type text}, {"Abierto", type datetime}, {"Cerrado", type datetime}, {"Resuelto", type datetime}, {"Duración", Int64.Type},  {"Infringido", type logical}, {"Tiempo original de incumplimiento", type datetime}, {"Estado de la incidencia", type text}, {"Etapa", type text}, {"Código de resolución", type text}, {"Volver a abrir recuento", type logical}, {"Tipo de Solución", type text},  {"Porcentaje de negocio trascurrido", Int64.Type}, {"ID de correlación", type text}, {"Principal", type text}}),
				
				    #"Appended Query" = Table.Combine({#"Tipo cambiado", #"PRO - Incidencias con SLA_A"}),
				
				
				//Homologa las prioridades
				    #"AllReplace" = [#"1 - Crítica" = "Crítica", #"2 - Alta" = "Alta", #"3 - Moderada" = "Media",#"3 - Media" = "Media",#"4 - Baja" = "Baja",#"5 - Muy Baja" = "Baja"],    
				    #"Replaced Value" = Table.TransformColumns(#"Appended Query",{{"Prioridad",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    
				
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced Value", "Abierto", "Abierta - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Abierta - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Abierta - Copy", Date.StartOfMonth, type date}}),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Calculated Start of Month",{{"Subcategoría", "Sistema"}}),
				     //Une con tabla de alegaciones KGI13_23
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Número"}, #"PRO - Alegaciones del Servicio KGI13_23", {"ID"}, "PRO - Alegaciones del Servicio KGI13_23", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio KGI13_23" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio KGI13_23", {"ANS", "Estado"}, {"PRO - Alegaciones del Servicio KGI13_23.ANS", "PRO - Alegaciones del Servicio KGI13_23.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio KGI13_23",{{"PRO - Alegaciones del Servicio KGI13_23.ANS", "ANS_Alegado"}, {"PRO - Alegaciones del Servicio KGI13_23.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Estado" si la alegación es aceptada
				    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns1",each [Estado de la incidencia],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI 1-3" then "Cancelado" else [Estado de la incidencia],Replacer.ReplaceValue,{"Estado de la incidencia"}),
				
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",each [Estado de la incidencia],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI 2-3" then "Cancelado" else [Estado de la incidencia],Replacer.ReplaceValue,{"Estado de la incidencia"}),
				    #"Filtered Rows3" = Table.SelectRows(#"Replaced Value3", each [Estado de la incidencia] <> "Cancelado"),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows3", {"Número"}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Removed Duplicates", {"Grupo de asignación"}, Lote_Aplicacion_relacion, {"Grupo de Asignación"}, "Lote_Aplicación_relación", JoinKind.LeftOuter),
				    #"Se expandió Lote_Aplicación_relación" = Table.ExpandTableColumn(#"Consultas combinadas", "Lote_Aplicación_relación", {"Lote"}, {"Lote_Aplicación_relación.Lote"}),
				    #"Duplicados quitados" = Table.Distinct(#"Se expandió Lote_Aplicación_relación", {"Número"})
				in
				    #"Duplicados quitados"
				```

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = PRO - Incidencias con SLA_P_y_A_Abiertas

	annotation PBI_NavigationStepName = Navigation

