table 'PRO - Alegaciones del Servicio KGI24'
	lineageTag: c1042974-28fc-4844-bd41-f391db364ed4

	column 'ID Alegación'
		dataType: string
		lineageTag: 26a6cf24-e66b-4879-a311-bd0e5e9ec862
		summarizeBy: none
		sourceColumn: ID Alegación

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: 9fe71f2d-ee14-4915-a475-4c0897a5c936
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Entrada alegada'
		dataType: string
		lineageTag: 0b276dd9-119c-4ded-a9b4-e2e82a2420cf
		summarizeBy: none
		sourceColumn: Entrada alegada

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: 42b7289f-5c54-45c5-9215-e5bfca0e6e2b
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: string
		lineageTag: 3c9fe91d-6476-4264-9ff6-ed76b28e221c
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		annotation SummarizationSetBy = Automatic

	column Clasificación
		dataType: string
		lineageTag: 08542712-7470-4425-a5bf-1a09d8d82a26
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: a85bc384-092e-4d59-b786-83e26e4a599e
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: f53b81be-47ff-4703-9916-9c61bac65ebc
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: a0be411b-ef47-4dc1-968a-66e2df0805ec
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: 482ea365-f190-42b4-8481-2cf03330b421
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3496e239-9b40-4526-b84a-6e02d64937df
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado - Copy

		variation Variación
			isDefault
			relationship: 30e52f16-a79b-48e5-9126-8f73d45f0e7c
			defaultHierarchy: LocalDateTable_acb4ecf6-b85c-4566-9263-8eae4db29203.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Solicitante
		dataType: string
		lineageTag: 03dcc5e2-838b-4770-b6b9-5fa98fe9a433
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column 'Comentarios AE'
		dataType: string
		lineageTag: 0881cc1d-97f2-4237-b062-2ea136244e06
		summarizeBy: none
		sourceColumn: Comentarios AE

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI24-cf443284-1583-4b3f-bcca-529ee2a0ce62' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Source = #"PRO - Alegaciones del Servicio",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([ANS] = "KGI 2-4"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

