table 'PRO - Planificaciones PRJ y ENH con SLA_M - Relación Incidencias'
	lineageTag: 37dbd5f7-71d0-4671-99a2-505105a0d6f9

	column Demanda
		dataType: string
		lineageTag: 7c79bae8-086d-4be2-b0e7-93589e00a176
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 8ce7c1c6-bef7-4285-9ce9-c0c443a6ffe3
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 477722e7-0e89-4bb6-a585-adc258ba43c1
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 33a0f6b3-45be-4d82-b45b-b48e77e57239
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: 57142fcc-b7cf-4fc1-b94d-01c58a65ecf4
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: 195b6024-5890-4280-98af-15e0c84b1063
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 30c2b367-7210-4547-a7ad-c5942f49fe6a
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variación
			isDefault
			relationship: 83163870-79c3-4c05-b700-fa4cfc17df0a
			defaultHierarchy: LocalDateTable_b527b51c-2536-4d1d-833f-cca1ab9dd417.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha límite planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 28084bd9-7ddc-4a6d-8831-91da5f0ad6d1
		summarizeBy: none
		sourceColumn: Fecha límite planificada

		variation Variación
			isDefault
			relationship: a9b12ac1-fd85-4932-9cf9-3f0fd3960a3a
			defaultHierarchy: LocalDateTable_91caf68d-f9f0-409f-98ad-c09d3c0d4964.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 58bc40e2-f525-4282-9c19-d8f4f98447d5
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: bcb5778a-a937-406c-b381-7a603258afa3
		summarizeBy: none
		sourceColumn: Inicio

		variation Variación
			isDefault
			relationship: 40d660c8-b9e2-4f97-8efe-e217449213cf
			defaultHierarchy: LocalDateTable_a29d1282-0c2e-48e8-a82e-7ec29dbac694.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: 0d22851c-d848-4069-89d4-16161d378c5c
		summarizeBy: none
		sourceColumn: Fin

		variation Variación
			isDefault
			relationship: 73d08513-60d1-4663-803b-1520f2504a5e
			defaultHierarchy: LocalDateTable_a29d0b72-7f01-4cc3-9d62-3a10fb7b3711.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0e521f50-d4b1-4608-8d9a-41cacb9655cf
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variación
			isDefault
			relationship: 8a0076ec-f766-4072-9579-815f171aa5ad
			defaultHierarchy: LocalDateTable_3266b0ca-8ac5-43dd-b3d5-66340a7df79d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8e51b2df-aba3-4385-9769-72b6d7e467ff
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variación
			isDefault
			relationship: bb36ba36-9cd3-48a0-9de5-13cfff19f73e
			defaultHierarchy: LocalDateTable_7070938d-209c-4db1-bb80-fb44a5283dbb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: be89b758-147e-418d-ab8c-6083cbef130d
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: 9fe31534-5c5f-48e4-af95-b864adb37a5a
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 1c8fb3c6-64fd-49be-bf60-1ad7103aa08e
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: a8abc486-3264-4ecc-864b-080266049a92
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Servicio'
		dataType: string
		lineageTag: b638e995-bed2-4572-be62-b1f13ef00e92
		summarizeBy: none
		sourceColumn: Tipo de Servicio

		annotation SummarizationSetBy = Automatic

	column 'Nombre de proyecto'
		dataType: string
		lineageTag: 61862a3f-dce5-41f0-8eb0-a974d43cb3b4
		summarizeBy: none
		sourceColumn: Nombre de proyecto

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 38bcbec3-916e-4aae-8d6e-5da3ac453306
		summarizeBy: none
		sourceColumn: Fecha fin real - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración Planificada LB'
		dataType: double
		lineageTag: f2db1e36-4bab-44bd-b29c-5466c9d68012
		summarizeBy: sum
		sourceColumn: Duración Planificada LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real LB'
		dataType: double
		lineageTag: d77691a4-d65d-4d49-b1a7-49a61d1b0bf5
		summarizeBy: sum
		sourceColumn: Duración real LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa de desviación'
		dataType: double
		lineageTag: 857d1aa8-9b5b-4adc-8178-7f0982c7730f
		summarizeBy: sum
		sourceColumn: Tasa de desviación

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimación incumplida'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4c2fc734-a430-4a38-8fb8-3801b1798690
		summarizeBy: none
		sourceColumn: Estimación incumplida

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 61e36acd-5463-455d-b5b0-f10e8a08f976
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column Lote
		dataType: string
		lineageTag: 3cd97091-32a2-4ab5-8e87-8b7a2ab5fbdf
		summarizeBy: none
		sourceColumn: Lote

		annotation SummarizationSetBy = Automatic

	column 'Incidencias Relacionadas.Incidente'
		dataType: string
		lineageTag: 8dd1e90a-6ccd-4d1a-adea-0ef2549386df
		summarizeBy: none
		sourceColumn: Incidencias Relacionadas.Incidente

		annotation SummarizationSetBy = Automatic

	column ServiceNow_Incidencias = CONCATENATE("https://acciona.service-now.com/incident.do?sysparm_query=number%3d", 'PRO - Planificaciones PRJ y ENH con SLA_M - Relación Incidencias'[Incidencias Relacionadas.Incidente])
		lineageTag: 7b28a9c5-4c41-436f-bfa1-877cd8a930cf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ServiceNow_Tarea = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Planificaciones PRJ y ENH con SLA_M - Relación Incidencias'[Número])
		lineageTag: f6a48c84-726f-4236-b943-19abe49311a7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones PRJ y ENH con SLA_M - Relación Incidencias-67948396-4b5f-4cb5-b2d6-f8e954fe94e5' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Origen = #"PRO - Planificaciones PRJ y ENH con SLA_M",
				    #"Consultas combinadas" = Table.NestedJoin(Origen, {"Número"}, #"Incidencias Relacionadas", {"Tarea"}, "Incidencias Relacionadas", JoinKind.LeftOuter),
				    #"Se expandió Incidencias Relacionadas" = Table.ExpandTableColumn(#"Consultas combinadas", "Incidencias Relacionadas", {"Incidente"}, {"Incidencias Relacionadas.Incidente"}),
				    #"Filas filtradas" = Table.SelectRows(#"Se expandió Incidencias Relacionadas", each ([Incidencias Relacionadas.Incidente] <> null))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

