table 'PRO - Jira - Defectos con SLA'
	lineageTag: 4cedaa1f-3f26-45b9-ad2a-65922e99d9f5

	column Components
		dataType: string
		lineageTag: 0e609169-ed86-4975-8379-af3ee7c134ce
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 051468b2-4650-40d6-b053-4f8145304ce0
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: b22e7725-86d2-4b53-8b59-893cf1e408cf
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: fd1df121-189a-4995-a6b5-20c5f3684ab1
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 97ec0fc5-dbe8-4f07-838d-fe4dc4205b96
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 3b3f9858-f914-4601-a323-81f80ba1bedc
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: d7a73c04-de63-4200-8de6-5c8d05a524d6
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 104eb896-5813-43f4-985b-bf3133a1d8b5
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 97c46844-06c0-4d81-b316-f5b9b5749a07
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: b77809cf-4572-4b05-ba4b-61489ba4ee80
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 65ea9571-c66b-455e-a135-9fb2a9e5c120
			defaultHierarchy: LocalDateTable_75732222-5cf5-43a7-aa9a-91a0f2bdbdf4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: b953f759-024d-4d2d-bcf2-f3d31ac7baa6
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: d419bd01-f820-4aed-8f54-3b171e8fa94b
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: 950430a8-a8a9-4152-881b-e6485b5ed1c0
			defaultHierarchy: LocalDateTable_dfb0493d-f256-4af0-b4c9-b00b73cd76cc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: f50ebbfc-affe-4397-89f4-e601896687bd
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Value (Bugs)'
		dataType: string
		lineageTag: 13e3e355-688a-40cc-a541-3685a431be36
		summarizeBy: none
		sourceColumn: Value (Bugs)

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Status'
		dataType: string
		lineageTag: 99be4b7b-c2be-4c41-afb0-29e8f7297595
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: f4546384-4dac-4a90-b38d-06bea1bbfdab
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved

		variation Variation
			isDefault
			relationship: 959a1d9a-a3d2-4fe8-8a91-353286185dd2
			defaultHierarchy: LocalDateTable_4523824c-503e-4f43-985d-0dac67ee3934.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status'
		dataType: string
		lineageTag: 7bcd5031-0996-4f1e-b4ba-6d86bab31cf6
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba'
		dataType: string
		lineageTag: eb37a454-99e0-4da5-9c91-dd6d0fc9aa49
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Pruebas con SLA.Priority'
		dataType: string
		lineageTag: 034968a5-6398-4cac-b5f3-a0447b7b6ae0
		summarizeBy: none
		sourceColumn: PRO - Jira - Pruebas con SLA.Priority

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Pruebas con SLA.Status'
		dataType: string
		lineageTag: 9ba5571c-6a14-49d8-b3cb-5728f612e68e
		summarizeBy: none
		sourceColumn: PRO - Jira - Pruebas con SLA.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f4a2adbb-5507-431c-acb1-51d06f941871
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved - Copy

		variation Variation
			isDefault
			relationship: 55e8f64e-23f1-446a-b0e7-cc2575c5fedd
			defaultHierarchy: LocalDateTable_8a54f5c0-0663-4d38-9175-dc93c9443319.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: 674f2423-de07-4cef-9742-dacf534b0794
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column Lote
		dataType: string
		lineageTag: b1a2209e-1156-4cb6-803e-dae3eca354a0
		summarizeBy: none
		sourceColumn: Lote

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Priority'
		dataType: string
		lineageTag: 05b4a101-c49e-459b-b708-bbc2849f9c87
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Priority

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Defectos con SLA-c529664e-4ce4-4b6a-8d96-3f11a751901e' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    URL = sharepointsource & Entorno & sharepointsource2 & pruebas_defectos & xlsx,
				    Source = Excel.Workbook(Web.Contents(URL), null, true),
				    Tests_Sheet = Source{[Item="Bugs",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Tests_Sheet, [PromoteAllScalars=true]),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Components", type text}, {"Project", type text}, {"Issue Type", type text}, {"Key", type text}, {"Summary", type text}, {"Assignee", type text}, {"Reporter", type text}, {"Priority", type text}, {"Status", type text}, {"Created", type datetime}, {"Linked Issues", type text}, {"Sub-tasks", type text}, {"Tipo de prueba", type text}, {"Resolved", type datetime}}),
				
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Linked Issues", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {"Linked Issues.1", "Linked Issues.2", "Linked Issues.3", "Linked Issues.4", "Linked Issues.5", "Linked Issues.6", "Linked Issues.7", "Linked Issues.8", "Linked Issues.9", "Linked Issues.10", "Linked Issues.11", "Linked Issues.12", "Linked Issues.13", "Linked Issues.14", "Linked Issues.15", "Linked Issues.16", "Linked Issues.17", "Linked Issues.18", "Linked Issues.19", "Linked Issues.20", "Linked Issues.21", "Linked Issues.22", "Linked Issues.23", "Linked Issues.24", "Linked Issues.25", "Linked Issues.26", "Linked Issues.27", "Linked Issues.28", "Linked Issues.29", "Linked Issues.30", "Linked Issues.31", "Linked Issues.32", "Linked Issues.33", "Linked Issues.34", "Linked Issues.35", "Linked Issues.36", "Linked Issues.37", "Linked Issues.38", "Linked Issues.39", "Linked Issues.40", "Linked Issues.41", "Linked Issues.42", "Linked Issues.43", "Linked Issues.44", "Linked Issues.45", "Linked Issues.46", "Linked Issues.47", "Linked Issues.48", "Linked Issues.49", "Linked Issues.50", "Linked Issues.51", "Linked Issues.52", "Linked Issues.53", "Linked Issues.54", "Linked Issues.55", "Linked Issues.56", "Linked Issues.57", "Linked Issues.58", "Linked Issues.59", "Linked Issues.60", "Linked Issues.61", "Linked Issues.62", "Linked Issues.63", "Linked Issues.64", "Linked Issues.65", "Linked Issues.66", "Linked Issues.67", "Linked Issues.68", "Linked Issues.69", "Linked Issues.70", "Linked Issues.71", "Linked Issues.72", "Linked Issues.73", "Linked Issues.74", "Linked Issues.75", "Linked Issues.76", "Linked Issues.77", "Linked Issues.78", "Linked Issues.79", "Linked Issues.80", "Linked Issues.81", "Linked Issues.82", "Linked Issues.83", "Linked Issues.84", "Linked Issues.85", "Linked Issues.86", "Linked Issues.87", "Linked Issues.88", "Linked Issues.89", "Linked Issues.90", "Linked Issues.91", "Linked Issues.92", "Linked Issues.93", "Linked Issues.94", "Linked Issues.95", "Linked Issues.96", "Linked Issues.97", "Linked Issues.98", "Linked Issues.99", "Linked Issues.100"}),
				
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{
				        {"Linked Issues.1", type text}, 
				        {"Linked Issues.2", type text}, 
				        {"Linked Issues.3", type text},
				        {"Linked Issues.4", type text},
				        {"Linked Issues.5", type text},
				        {"Linked Issues.6", type text},
				        {"Linked Issues.7", type text},
				        {"Linked Issues.8", type text},
				        {"Linked Issues.9", type text},
				        {"Linked Issues.10", type text}
				        }),
				
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type1", {"Components","Project", "Issue Type", "Key", "Summary", "Assignee", "Reporter", "Priority", "Status", "Created", "Sub-tasks", "Resolved"}, "Attribute", "Value (Bugs)"),
				    
				    //Une con las Historias (Relación Defecto con la tabla de Historias y Ejecuciones)
				    #"Merged Queries" = Table.NestedJoin(#"Unpivoted Columns", {"Value (Bugs)"}, #"PRO - Jira - Historias y Ejecuciones", {"Value (Stories)"}, "PRO - Jira - Historias y Ejecuciones", JoinKind.LeftOuter),
				    #"Expanded PRO - Jira - Historias y Ejecuciones" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Jira - Historias y Ejecuciones", {"Priority", "Status", "Resolved", "PRO - Jira - Ejecuciones.Status", "PRO - Jira - Ejecuciones.Tipo de prueba"}, {"PRO - Jira - Historias y Ejecuciones.Priority", "PRO - Jira - Historias y Ejecuciones.Status", "PRO - Jira - Historias y Ejecuciones.Resolved", "PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status", "PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba"}),
				    #"Filas filtradas" = Table.SelectRows(#"Expanded PRO - Jira - Historias y Ejecuciones", each ([#"PRO - Jira - Historias y Ejecuciones.Resolved"] <> null)),
				    
				    //Une con los Tests (Relación Defecto con su Test)
				    #"Merged Queries1" = Table.NestedJoin(#"Filas filtradas", {"Value (Bugs)"}, #"PRO - Jira - Pruebas con SLA", {"Key"}, "PRO - Jira - Pruebas con SLA", JoinKind.LeftOuter),
				    #"Expanded PRO - Jira - Pruebas con SLA" = Table.ExpandTableColumn(#"Merged Queries1", "PRO - Jira - Pruebas con SLA", {"Priority", "Status"}, {"PRO - Jira - Pruebas con SLA.Priority", "PRO - Jira - Pruebas con SLA.Status"}),
				
				//Homologa las prioridades
				    #"AllReplace" = [#"Highest" = "Grave", #"High" = "Grave", #"Medium" = "Media",#"Low" = "Leve",#"Lowest" = "Leve"],    
				    #"Replaced Value" = Table.TransformColumns(#"Expanded PRO - Jira - Pruebas con SLA",{{"Priority",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    
				    //Ajuste de campo de Hitorias & Ejecuciones para relacionar a fechas Dashboard
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced Value", "PRO - Jira - Historias y Ejecuciones.Resolved", "PRO - Jira - Historias y Ejecuciones.Resolved - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"PRO - Jira - Historias y Ejecuciones.Resolved - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"PRO - Jira - Historias y Ejecuciones.Resolved - Copy", Date.StartOfMonth, type date}}),
				
				    //Une con las alegaciones
				    #"Merged Queries2" = Table.NestedJoin(#"Calculated Start of Month", {"Key"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries2", "PRO - Alegaciones del Servicio", {"Estado"}, {"PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Renamed Columns1", {"Components"}, Lote_Aplicacion_relacion, {"Aplicación de negocio"}, "Lote_Aplicación_relación", JoinKind.LeftOuter),
				    #"Se expandió Lote_Aplicación_relación" = Table.ExpandTableColumn(#"Consultas combinadas", "Lote_Aplicación_relación", {"Lote"}, {"Lote_Aplicación_relación.Lote"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Se expandió Lote_Aplicación_relación",{{"Lote_Aplicación_relación.Lote", "Lote"}}),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Columnas con nombre cambiado", {"Value (Bugs)"}, #"PRO - Jira - Pruebas con SLA", {"Key"}, "PRO - Jira - Pruebas con SLA", JoinKind.LeftOuter)
				in
				    #"Consultas combinadas1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

