table 'PRO - Jira - Defectos con SLA - FUN Sin Lote'
	lineageTag: 6e1c3a6d-d321-4095-9460-2825bb955edf

	column 'PRO - Jira - Historias y Ejecuciones.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c2b15496-b985-4c08-aa44-f2b0e89bdd7b
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved - Copy

		variation Variación
			isDefault
			relationship: ce51a646-851a-4670-b517-1c5fdad8ca3f
			defaultHierarchy: LocalDateTable_e0ff65f1-7ffd-4201-9fe9-937d7412b929.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Priority
		dataType: string
		lineageTag: 05935e4e-6744-4a2f-88f5-be1ea3e1abc7
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column 'Defectos Funcionales'
		dataType: int64
		formatString: 0
		lineageTag: 574f2523-bb1e-4436-a7de-ea3561bdc00b
		summarizeBy: sum
		sourceColumn: Defectos Funcionales

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Defectos con SLA - FUN Sin Lote-300e74a2-6ca7-4f1d-b4de-5ce015672eb7' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = #"PRO - Jira - Defectos con SLA",
				
				    #"Filtered Rows" = Table.SelectRows(Source, each ([#"PRO - Jira - Historias y Ejecuciones.Status"] = "Done") and ([#"PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba"] = "Pruebas Funcionales")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [Estado_Alegación] <> "1 - Aprobada"),
				
				    #"Grouped Rows" = Table.Group(#"Filtered Rows1", {"PRO - Jira - Historias y Ejecuciones.Resolved - Copy", "Priority"}, {{"Defectos Funcionales", each Table.RowCount(_), Int64.Type}})
				in
				    #"Grouped Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

