table 'PRO - Jira - Pruebas con SLA'
	lineageTag: 11cd2a56-c897-4baf-9d87-43c9f2667002

	column Components
		dataType: string
		lineageTag: bcd5182b-bee5-4759-b621-0fb0a3a75eeb
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 8d55ce25-2f7b-4b8f-b98f-a8cad9156671
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: 9fe804af-214a-4bf2-99c6-a14c7ddc0735
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 151cfd36-3d2d-40e0-9940-4dc02c61f5c5
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 90ed9a95-bd01-461d-a463-0c173c62da46
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 057e7ac0-8b55-46b9-85ef-42a68b137705
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 76ab4cea-8667-4865-8afd-de728fc55665
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: e762523d-b35e-4816-9162-4be5b990c947
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 51a266a0-4c8a-440d-b53d-39cf9fc3a6d3
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 7e7141f3-858d-478f-8402-08eed7a52585
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 60ef18b5-4367-4c33-ae94-7e7b87933a37
			defaultHierarchy: LocalDateTable_da3f77a5-cec4-4970-a42b-aa5096e5066e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: a791e676-680c-4979-805b-2b4b3aa9f76d
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column 'Tipo de prueba'
		dataType: string
		lineageTag: 4fcbad78-e7b2-448e-9220-fdd7882f9fa0
		summarizeBy: none
		sourceColumn: Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: 37ca5d61-9e6e-40ac-942b-faf0915c2c42
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: d4ed8bca-b1c1-4ee3-a90c-fa8bc12accb8
			defaultHierarchy: LocalDateTable_120e3cc7-e3f3-4a7e-bde6-112eb07f9899.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 74efb841-bbc3-4443-b987-b42e18352067
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Value (Tests)'
		dataType: string
		lineageTag: 87a2e94d-3a9c-4026-852e-2afb77d2b966
		summarizeBy: none
		sourceColumn: Value (Tests)

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias.Key'
		dataType: string
		lineageTag: 325ad84f-18bc-4c17-98d5-516d972dd4e0
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias.Key

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias.Status'
		dataType: string
		lineageTag: 03b76519-5602-413b-a09c-149ed40daa39
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: 64976ad1-6c2e-4bd6-8647-fbc3194b201b
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias.Resolved

		variation Variation
			isDefault
			relationship: 901a5652-e3df-424a-8eb5-9998c09892e6
			defaultHierarchy: LocalDateTable_a3fd6922-efff-4d7d-afbe-231406991c43.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column UAT = IF ( CONTAINSSTRING('PRO - Jira - Pruebas con SLA'[Tipo de prueba],"UAT"),1,0)
		formatString: 0
		lineageTag: 86439930-0fa6-4d4c-8109-837d8a76378f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column FUN = IF ( CONTAINSSTRING('PRO - Jira - Pruebas con SLA'[Tipo de prueba],"Funcional"),1,0)
		formatString: 0
		lineageTag: f7fe0dca-06d6-4066-b1c4-7d0a50cb3d96
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Servicio'
		dataType: string
		lineageTag: ad565f3c-f20a-4ead-a2f4-36e7d3d48b8e
		summarizeBy: none
		sourceColumn: Tipo de Servicio

		annotation SummarizationSetBy = Automatic

	column 'Resolved - Copia'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0b3c4167-9779-4220-af85-621d0d3eea00
		summarizeBy: none
		sourceColumn: Resolved - Copia

		annotation SummarizationSetBy = Automatic

	column Lote
		dataType: string
		lineageTag: a4608ded-9762-4def-b903-45664e0b5221
		summarizeBy: none
		sourceColumn: Lote

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Pruebas con SLA-61f24a68-5eb8-43f1-8370-d881916bc54a' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    URL = sharepointsource & Entorno & sharepointsource2 & pruebas_defectos & xlsx,
				    Source = Excel.Workbook(Web.Contents(URL), null, true),
				    Tests_Sheet = Source{[Item="Tests",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Tests_Sheet, [PromoteAllScalars=true]),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Components", type text}, {"Project", type text}, {"Issue Type", type text}, {"Key", type text}, {"Summary", type text}, {"Assignee", type text}, {"Reporter", type text}, {"Priority", type text}, {"Status", type text}, {"Created", type datetime}, {"Linked Issues", type text}, {"Sub-tasks", type text}, {"Tipo de prueba", type text}, {"Resolved", type datetime}}),
				
				    //Separa los Linked Issues de cada Test
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Linked Issues", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {
				        "Linked Issues.1",
				        "Linked Issues.2",
				        "Linked Issues.3",
				        "Linked Issues.4",
				        "Linked Issues.5",        
				        "Linked Issues.6",        
				        "Linked Issues.7",        
				        "Linked Issues.8",       
				        "Linked Issues.9",
				        "Linked Issues.10"        
				        }),
				
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{
				        {"Linked Issues.1", type text}, 
				        {"Linked Issues.2", type text}, 
				        {"Linked Issues.3", type text},
				        {"Linked Issues.4", type text},
				        {"Linked Issues.5", type text},
				        {"Linked Issues.6", type text},
				        {"Linked Issues.7", type text},
				        {"Linked Issues.8", type text},
				        {"Linked Issues.9", type text},
				        {"Linked Issues.10", type text}
				        }),
				
				    //Transforma la separación en tipo lista (Cada Test Link con el Test al cual está relacionado)
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type1", {"Components","Project", "Issue Type", "Key", "Summary", "Assignee", "Reporter", "Priority", "Status", "Created", "Sub-tasks", "Tipo de prueba", "Resolved"}, "Attribute", "Value (Tests)"),
				
				    //Une con las Historias
				    #"Merged Queries" = Table.NestedJoin(#"Unpivoted Columns", {"Value (Tests)"}, #"PRO - Jira - Historias", {"Key"}, "PRO - Jira - Historias", JoinKind.LeftOuter),
				    #"Expanded PRO - Jira - Historias" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Jira - Historias", {"Key", "Status", "Resolved"}, {"PRO - Jira - Historias.Key", "PRO - Jira - Historias.Status", "PRO - Jira - Historias.Resolved"}),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Expanded PRO - Jira - Historias", "Resolved", "Resolved - Copia"),
				    #"Inicio del mes calculado" = Table.TransformColumns(#"Columna duplicada",{{"Resolved - Copia", Date.StartOfMonth, type datetime}}),
				    
				
				    //Homologa las prioridades
				    #"AllReplace" = [#"Highest" = "Grave", #"High" = "Grave", #"Medium" = "Media",#"Low" = "Leve",#"Lowest" = "Leve"],    
				    #"Replaced Value" = Table.TransformColumns(#"Inicio del mes calculado",{{"Priority",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value", "Tipo de Servicio", each if Text.Contains([Project], "Mtto") then "Mtto. Evolutivo" else "Proyectos"),
				    #"Consultas combinadas" = Table.NestedJoin(#"Added Conditional Column", {"Components"}, Lote_Aplicacion_relacion, {"Aplicación de negocio"}, "Lote_Aplicación_relación", JoinKind.LeftOuter),
				    #"Se expandió Lote_Aplicación_relación" = Table.ExpandTableColumn(#"Consultas combinadas", "Lote_Aplicación_relación", {"Lote"}, {"Lote_Aplicación_relación.Lote"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Se expandió Lote_Aplicación_relación",{{"Lote_Aplicación_relación.Lote", "Lote"}})
				in
				    #"Columnas con nombre cambiado"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

