table 'PRO - Jira - Defectos con SLA - FUN - Detalle'
	lineageTag: 7db85bc0-eba0-4051-9840-496407bd08c4

	column Components
		dataType: string
		lineageTag: e4224f78-7ffa-4466-b01b-440485a2afe5
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: c270f7aa-95c9-4a4a-b99f-48cec9ba0f34
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: 45ced9a4-95bf-4d6a-b857-3f90d34c1f55
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: a026d31d-8efc-415a-b483-e769e6d4f983
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 9e726657-41a8-4cfe-8028-e5c4a3a2c9e7
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 82f1b497-4381-47e4-b31f-3157c9765d8b
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: d9fb1e11-694a-43dd-8e77-f9fba5d47b48
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: fc4cb7bb-c6b7-4905-87a8-582f33581442
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 020c9061-b592-4803-81d2-24b013307750
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: ca92e1a8-6ac6-4de5-81ce-bd6cce49a13a
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: b606a951-db1d-4745-b6f5-d4b9b7d9c7e3
			defaultHierarchy: LocalDateTable_5ee0558c-c30a-4c85-9729-47e3b26a8b16.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 901d7b31-b2b5-46f6-ac78-c17230096adc
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: 8e4c0da1-2342-40a0-a4d0-46088952a6cc
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: 0a63252e-5978-41ab-929e-b236bcdc81e5
			defaultHierarchy: LocalDateTable_e25738bf-0ac5-4f30-b5c5-bb738d3cb418.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 23455d31-1636-492b-830d-143f6c1b2749
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Value (Bugs)'
		dataType: string
		lineageTag: 0ed30ab3-f081-49e8-bc7c-694c3c0d7cd2
		summarizeBy: none
		sourceColumn: Value (Bugs)

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Status'
		dataType: string
		lineageTag: 471a848c-6be9-40a4-9fb3-bdd4f5ba90c6
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: 570e5695-5228-44c6-be44-0390a4d98c14
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status'
		dataType: string
		lineageTag: a8e665a4-b5c5-42bd-9cac-901662a257d6
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba'
		dataType: string
		lineageTag: 88e0f9a5-d0c4-4d1f-9850-84e06c577962
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Pruebas con SLA.Priority'
		dataType: string
		lineageTag: 7a60dc63-0ef0-42c4-8de9-d200ca395964
		summarizeBy: none
		sourceColumn: PRO - Jira - Pruebas con SLA.Priority

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Pruebas con SLA.Status'
		dataType: string
		lineageTag: 071d041d-7ef0-4b03-8be7-f4e38071571b
		summarizeBy: none
		sourceColumn: PRO - Jira - Pruebas con SLA.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b03bccf5-14c1-4320-aa98-4919cd659fe0
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved - Copy

		variation Variation
			isDefault
			relationship: d4919915-bfec-4ced-97a1-3836acf81f1e
			defaultHierarchy: LocalDateTable_e500c7ea-84d5-4ef1-ac31-bed1cb2d26ae.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: afcda295-b9ff-4bbe-9fe9-f40525358785
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column Lote
		dataType: string
		lineageTag: b18ca090-4587-4bc1-aeac-d28d60d98d07
		summarizeBy: none
		sourceColumn: Lote

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Priority'
		dataType: string
		lineageTag: 428f49e0-7a47-4d4e-88fc-1af8832664dc
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Priority

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Defectos con SLA - FUN - Detalle-fdad26b4-5d9f-4d4d-b271-fd433890918a' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = #"PRO - Jira - Defectos con SLA",
				
				    #"Filtered Rows1" = Table.SelectRows(Source, each ([Estado_Alegación] <> "1 - Aprobada") and ([#"PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba"] = "Pruebas Funcionales"))
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

