table 'PRO - Planificaciones MA'
	lineageTag: e3edb737-7e3f-4f49-a8ab-b1aa47971fba

	column Demanda
		dataType: string
		lineageTag: c98ab40c-0fcb-4df6-9a5c-88a2b7e7855a
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 25965d12-d2f6-4633-aebb-2b5db2d0618b
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 87cc3f20-35f8-40b4-8a7f-39826b2bd7d0
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 8d534da7-401f-4070-b45a-8ab736e497c9
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: 75fc4b40-06c0-4f11-8448-ccdaf69ddb98
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: 412de8d2-6c6a-44f2-b724-4b748fd20f06
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 44e5cab3-8356-4eb8-822e-585214fcf1ee
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variation
			isDefault
			relationship: f1c2ff19-dc45-4733-8784-9e02b822521b
			defaultHierarchy: LocalDateTable_644e9fda-3758-4fae-9e15-df3d35706a7d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha límite planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1267e834-5ce6-4f1c-9eb2-a00da28e8d6a
		summarizeBy: none
		sourceColumn: Fecha límite planificada

		variation Variation
			isDefault
			relationship: 1ae4f115-06f5-4390-98e8-c517a86181c0
			defaultHierarchy: LocalDateTable_ace832ad-73d1-4c4a-aa40-fd51a45c9598.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: e22eade7-5574-4d1b-bb9d-2b835eead17c
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: 7c832efa-5492-4226-a953-765783c7d3d5
		summarizeBy: none
		sourceColumn: Inicio

		variation Variation
			isDefault
			relationship: 48cbcbc7-fc1c-4fc6-b397-2cbce740b4ea
			defaultHierarchy: LocalDateTable_ddf43091-aa12-45da-a017-7f828e5d2402.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: b9dd42c5-e231-4653-b592-2aa4f82dc869
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: 26bcd3c3-82fa-4731-b5e6-c30cc4441105
			defaultHierarchy: LocalDateTable_f36d0a80-9527-472e-aaa5-7fca701fd1c2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: b43e2779-cbd2-403a-8af2-0bec2fbe12b6
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: 94553bf3-6316-4935-8766-27a39c78b951
			defaultHierarchy: LocalDateTable_89940140-1b60-4c13-a603-b9525703d81d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: d55ba76f-9d72-4e5a-95f6-02280648ed51
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: 11dbf459-146e-4926-a9ce-a66195484422
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: cf46b205-aa13-44a9-a106-3e431c3aa29b
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: 26d43cdb-6e6b-41ae-b18e-63a2765ff502
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Servicio'
		dataType: string
		lineageTag: 476d9d9e-bb8a-4868-b9d1-0185e69e18c4
		summarizeBy: none
		sourceColumn: Tipo de Servicio

		annotation SummarizationSetBy = Automatic

	column 'Nombre de proyecto'
		dataType: string
		lineageTag: f68f2dd5-58a6-4a66-bc89-5e68d9197eed
		summarizeBy: none
		sourceColumn: Nombre de proyecto

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: bb31f8db-170a-4d6e-aadf-b2c47f5bf229
		summarizeBy: none
		sourceColumn: Fin

		variation Variación
			isDefault
			relationship: 4b7914c4-4a29-451b-937c-990266d2c23d
			defaultHierarchy: LocalDateTable_453f5e1c-d849-4a13-87f8-4f99ce1320f8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones MA-79bd6986-2989-4c18-863a-41eff1683ea9' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = Excel.Workbook(Web.Contents(globalPath & evos & xlsx), null, true),
				    #"Page 1_Sheet" = Source{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Promoted Headers",{{"Fecha de finalización derivada de", "Fecha final derivada de"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Número", type text}, {"Número_1", type text}, {"Tipo de Proyecto", type text}, {"Prioridad", type text}, {"Jefe de proyecto (Project Manager)", type text}, {"Aplicación de Negocio ", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha fin planificada", type datetime}, {"Nombre de subtarea", type text}, {"Fecha de inicio derivada de", type datetime}, {"Fecha final derivada de", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Breve descripción", type text}}),
				
				    //Homologa cabeceras para realizar posterior Append con PRJs
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Número", "Demanda"}, {"Número_1", "Número"}, {"Nombre de subtarea", "Nombre"}, {"Fecha de inicio derivada de", "Inicio"}, {"Fecha final derivada de", "Fin"}, {"Breve descripción", "Nombre de PRJ o MEJ"}, {"Fecha fin planificada", "Fecha límite planificada"}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Renamed Columns", "Tipo de Servicio", each "Mtto. Evolutivo")
				
				in
				    #"Personalizada agregada"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

