table 'PRO - Incidencias con SLA_P_y_A_KGI22'
	lineageTag: ce45c9dc-a14b-4b14-9339-91da34557ce9

	column Número
		dataType: string
		lineageTag: 3b15b5d8-2cee-4443-b306-0e56fbffdd34
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 1f017427-ec34-4787-82bd-079c69013a36
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: d8a9946c-a0dc-4393-a198-8749ac51982d
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 74975182-ece7-48f1-9bbf-186e6776e435
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 174f9722-314b-438e-8103-57da625ca9e8
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: 66b1ae4a-d1e1-4ab5-942c-8cc8f4184e3b
			defaultHierarchy: LocalDateTable_4c033515-6796-44ec-8d70-13811cd593a8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 09efd8dd-3b63-455c-9bf0-d948b420e3a3
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 19482179-6455-45e9-8c9d-d2b748976bc1
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: string
		lineageTag: 85a464a1-ab29-4ddb-a0b9-590fd434c8c5
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		lineageTag: 28b25328-749a-4df3-8ceb-ffe113ba9a12
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc0c3dab-336b-43ed-90f5-011c8bccd9c1
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ANS_Alegado
		dataType: string
		lineageTag: c969d9e4-44b4-469b-835b-886add88a643
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 17b4cd3e-0368-462c-82ee-e7cc58171f2d
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column N_Reabierta = ```
			IF('PRO - Incidencias con SLA_P_y_A_KGI22'[Volver a abrir recuento] = True,1) 
			```
		formatString: 0
		lineageTag: f72c7604-dfbb-4ab8-8eab-caeda58d88a9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Resuelto
		dataType: dateTime
		formatString: General Date
		lineageTag: 3617a964-9c16-4374-aa22-7e1d80bac584
		summarizeBy: none
		sourceColumn: Resuelto

		variation Variación
			isDefault
			relationship: 4f6c4c2a-097e-498c-853d-35dd89163a30
			defaultHierarchy: LocalDateTable_dd05a1d0-f710-4f10-9705-c4c8ea6a952f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Código de resolución'
		dataType: string
		lineageTag: 812f8ba0-0cfa-45b4-b282-9d0ddb15e72f
		summarizeBy: none
		sourceColumn: Código de resolución

		annotation SummarizationSetBy = Automatic

	column 'Volver a abrir recuento'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 24bc5311-b57f-47a2-b5e4-d98017e72d6b
		summarizeBy: none
		sourceColumn: Volver a abrir recuento

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Solución'
		dataType: string
		lineageTag: 50bad10e-9c29-422e-ab7b-d8cceeb435d1
		summarizeBy: none
		sourceColumn: Tipo de Solución

		annotation SummarizationSetBy = Automatic

	column 'ID de correlación'
		dataType: string
		lineageTag: 40d3db61-d74f-4208-9ad1-c0981a1d6c5a
		summarizeBy: none
		sourceColumn: ID de correlación

		annotation SummarizationSetBy = Automatic

	column Principal
		dataType: string
		lineageTag: 2a68efb2-762d-4950-bd40-f9ab855b8d2e
		summarizeBy: none
		sourceColumn: Principal

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: 835c393b-5978-403f-a933-dcbe19b0f680
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: int64
		formatString: 0
		lineageTag: 9e5eaf36-d53b-46cb-bf7a-bad0052058e2
		summarizeBy: sum
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column 'Estado de la incidencia'
		dataType: string
		lineageTag: 27581615-6fc0-4c9b-9343-501a455f7001
		summarizeBy: none
		sourceColumn: Estado de la incidencia

		annotation SummarizationSetBy = Automatic

	column Etapa
		dataType: string
		lineageTag: 30b1b096-7c35-48c7-9cac-5ebd26061d37
		summarizeBy: none
		sourceColumn: Etapa

		annotation SummarizationSetBy = Automatic

	column Duración_1
		dataType: string
		lineageTag: 415da15f-8750-459e-80da-786386551284
		summarizeBy: none
		sourceColumn: Duración_1

		annotation SummarizationSetBy = Automatic

	column 'Lote_Aplicación_relación.Lote'
		dataType: string
		lineageTag: a747c29b-1ac7-46ea-b4fc-2cb0111211b0
		summarizeBy: none
		sourceColumn: Lote_Aplicación_relación.Lote

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA_P_y_A_KGI22'[Número])
		lineageTag: 51893c69-16d8-4ecf-bc4a-93fa74059c7f
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: c9556714-6956-4125-ad9f-b8870f4612cc
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: ab11419e-3c44-4009-8d97-1825dc3489b4
			defaultHierarchy: LocalDateTable_599db50c-3cde-4999-a8db-c73ba668f732.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: eeda5c56-918e-498c-b3a9-dcda55458544
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column 'Estado del incidente'
		dataType: string
		lineageTag: f4248346-29f4-4502-83c7-d96e5855c780
		summarizeBy: none
		sourceColumn: Estado del incidente

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA_P_y_A_KGI22-cfad9582-c26a-47e0-a884-c82df30fa290' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Source = #"PRO - Incidencias con SLA_P_y_A",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"ANS_Alegado", "Estado_Alegación"}),
				    
				    //Une con tabla de alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"Número"}, #"PRO - Alegaciones del Servicio KGI22", {"ID"}, "PRO - Alegaciones del Servicio KGI22", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio KGI22" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio KGI22", {"ANS", "Estado"}, {"PRO - Alegaciones del Servicio KGI22.ANS", "PRO - Alegaciones del Servicio KGI22.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio KGI22",{{"PRO - Alegaciones del Servicio KGI22.ANS", "ANS_Alegado"}, {"PRO - Alegaciones del Servicio KGI22.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Infringido" si la alegación es aceptada
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1",each [Volver a abrir recuento],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI 2-2" then "FALSE" else [Volver a abrir recuento],Replacer.ReplaceValue,{"Volver a abrir recuento"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"Volver a abrir recuento", type logical}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = PRO - Incidencias con SLA_P_y_A_KGI22

	annotation PBI_NavigationStepName = Navigation

