table 'PRO - Planificaciones PRJ y ENH con SLA - Incumplidas'
	lineageTag: d69e3487-3266-4255-bfd3-994ffd8409de

	column Prioridad
		dataType: string
		lineageTag: 28785bf9-d1f4-4384-8ec7-56853c8fdbd4
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c97454b6-e573-4147-9ea2-3cc2fba8cf8f
		summarizeBy: none
		sourceColumn: Fecha fin real - Copy

		variation Variation
			isDefault
			relationship: ed40dea1-9f23-462b-9c96-83482be26a80
			defaultHierarchy: LocalDateTable_78257d1d-f0f2-4de7-b37f-1b1a24dfb4eb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Estimación Incumplida'
		dataType: int64
		lineageTag: 68092945-4302-4f12-95b0-19a0cc017182
		summarizeBy: sum
		sourceColumn: Estimación Incumplida

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Lote
		dataType: string
		lineageTag: 1de561bf-6afb-4f9b-b7f1-61b54d9c39d0
		summarizeBy: none
		sourceColumn: Lote

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones PRJ y ENH con SLA - Incumplidas-897bbd85-3dae-4c27-b0ca-b3e8fa06d500' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = #"PRO - Planificaciones PRJ y ENH con SLA_M",
				
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Estimación incumplida] = true)),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"Prioridad", "Fecha fin real - Copy", "Lote"}, {{"Estimación Incumplida", each Table.RowCount(_), Int64.Type}})
				in
				    #"Grouped Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

