table 'PRO - Jira - Entregables con SLA'
	lineageTag: 7bba06e8-8c18-4de2-884e-776f5800c308

	column 'Issue Type'
		dataType: string
		lineageTag: 830e254d-efea-4fad-a093-1d243edc60d3
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 2625b44b-9ab2-4a1e-92a7-e3857da5cc76
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: e71d608f-9515-499d-a3d4-5d4488b6f96d
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Components
		dataType: string
		lineageTag: 868e1609-4206-451b-8999-1d1d285466c5
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 190d03d5-a58b-485a-a8d3-00213914300e
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 6bde7941-34a1-416b-bf2c-308c6505037f
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 611a67cb-74af-439c-95d7-50692264db19
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 5f8805b8-962a-4048-bfff-516492a9c476
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'End Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 7163bc2d-0fd7-4dc8-b8a2-b53f9fa01cc5
		summarizeBy: none
		sourceColumn: End Date

		variation Variation
			isDefault
			relationship: d4b3148d-e3f0-408f-ad66-e40bd535cfe3
			defaultHierarchy: LocalDateTable_1c4405a5-e746-4d71-8b52-f0037ad20c4f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'End Real Date'
		dataType: string
		lineageTag: 43485110-11c3-45ab-9f68-06f8645096d9
		summarizeBy: none
		sourceColumn: End Real Date

		annotation SummarizationSetBy = Automatic

	column 'Linked Issues'
		dataType: string
		lineageTag: 2005aa28-2995-4f6d-b287-083f0ee48087
		summarizeBy: none
		sourceColumn: Linked Issues

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 4361ced5-0bad-47cc-a586-ac8e01b8d246
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: ddb4a5c7-3ec7-4d84-ae7e-6a343a6cc89d
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: 9b72112f-6fff-48bc-94a7-d04e91d59ccc
			defaultHierarchy: LocalDateTable_f1be6c47-0ab0-498b-8cf5-fb6ced484fb1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Rechazado
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 561624a3-3222-43c3-9ccd-d327e11ec248
		summarizeBy: none
		sourceColumn: Rechazado

		annotation SummarizationSetBy = Automatic

	column 'Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 13d4a726-31bc-41ae-83ca-fdfaa72e68c7
		summarizeBy: none
		sourceColumn: Resolved - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: 8640839d-2ac0-4e4e-9650-f85b3e1ec479
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Deliverable type'
		dataType: string
		lineageTag: 31ff85c3-39bb-4826-9c56-54c9796be7dc
		summarizeBy: none
		sourceColumn: Deliverable type

		annotation SummarizationSetBy = Automatic

	column 'Approval status'
		dataType: string
		lineageTag: c8edad96-7045-4182-94ff-6011bbc86b50
		summarizeBy: none
		sourceColumn: Approval status

		annotation SummarizationSetBy = Automatic

	column Descripcion = IF(CONTAINSSTRING('PRO - Jira - Entregables con SLA'[Project],"Mtto"),"Mantenimiento", "Proyecto")
		lineageTag: e2d9fc9a-2d44-4461-a4a3-c90166d68dc6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Servicio'
		dataType: string
		lineageTag: 9b2813aa-548d-4925-aba6-99b3f2a5afa3
		summarizeBy: none
		sourceColumn: Tipo de Servicio

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: c864a37f-0a92-4b98-8011-f1684d6f5f55
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Lote
		dataType: string
		lineageTag: 7519654a-835f-44e9-a788-2368bee541d6
		summarizeBy: none
		sourceColumn: Lote

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Entregables con SLA-5c54ffc6-de48-4fc9-8b50-725b12f7f0a8' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				   URL = sharepointsource & Entorno & sharepointsource2 & pruebas_defectos & xlsx,
				Origen = Excel.Workbook(Web.Contents(URL), null, true),
				#"Entregables Rechazados_Sheet" = Origen{[Item="Entregables",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Entregables Rechazados_Sheet", [PromoteAllScalars=true]),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Issue Type", type text}, {"Deliverable type", type text}, {"Project", type text}, {"Key", type text}, {"Components", type text}, {"Summary", type text}, {"Priority", type text}, {"Assignee", type text}, {"Status", type text}, {"Approval status", type text}, {"End Date", type datetime}, {"End Real Date", type text}, {"Linked Issues", type text}, {"Sub-tasks", type text}, {"Resolved", type datetime}, {"Rechazos", type logical}}),
				
				//Homologa las prioridades
				    #"AllReplace" = [#"Highest" = "Grave", #"High" = "Grave", #"Medium" = "Grave",#"Low" = "Leve",#"Lowest" = "Leve"],    
				    #"Replaced Value" = Table.TransformColumns(#"Changed Type",{{"Priority",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    
				    //Renombra la Prioridad por "Tipo" de incumplimiento como dice el ANS
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"Priority", "Tipo"}, {"Rechazos", "Rechazado"}}),
				
				   
				
				    //Copia el campo Resolved para relacionar a la tabla fechas
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "Resolved", "Resolved - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Resolved - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Resolved - Copy", Date.StartOfMonth, type date}}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Calculated Start of Month",null,false,Replacer.ReplaceValue,{"Rechazado"}),
				
				    //Une con las alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value5", {"Key"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"Estado"}, {"PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Rechazado" si la alegación es aceptada
				    #"Replaced Value6" = Table.ReplaceValue(#"Renamed Columns1",each [Rechazado],each if [Estado_Alegación] = "1 - Aprobada" then "FALSE" else [Rechazado],Replacer.ReplaceValue,{"Rechazado"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value6",{{"Rechazado", type logical}}),
				
				    #"Create Column" = Table.AddColumn(#"Changed Type4", "Tipo de Servicio", each if Text.Contains([Project], "Mtto") then "Mtto. Evolutivo" else "Proyectos"),
				    #"Consultas combinadas" = Table.NestedJoin(#"Create Column", {"Components"}, Lote_Aplicacion_relacion, {"Aplicación de negocio"}, "Lote_Aplicación_relación", JoinKind.LeftOuter),
				    #"Se expandió Lote_Aplicación_relación" = Table.ExpandTableColumn(#"Consultas combinadas", "Lote_Aplicación_relación", {"Lote"}, {"Lote_Aplicación_relación.Lote"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Se expandió Lote_Aplicación_relación",{{"Lote_Aplicación_relación.Lote", "Lote"}})
				
				in
				    #"Columnas con nombre cambiado"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

