table 'PRO - Estimaciones con SLA'
	lineageTag: 49454177-886d-413a-a921-383d48d6c721

	column Creado
		dataType: dateTime
		formatString: General Date
		lineageTag: 4614cdb5-764a-4bc2-adbe-1338caf297fd
		summarizeBy: none
		sourceColumn: Creado

		variation Variation
			isDefault
			relationship: c0611801-5c18-4987-8879-fd5ec90bc80e
			defaultHierarchy: LocalDateTable_4154b662-4c11-4acc-a8d5-92bda6f30c47.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: aa157447-4ce7-49bd-999f-8c1417a19a12
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio'
		dataType: string
		lineageTag: db5044c5-e016-405e-8c5c-7bcc274eb43d
		summarizeBy: none
		sourceColumn: Aplicación de Negocio

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: db7b0849-7daa-46aa-bae4-1047982e4118
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Tarea
		dataType: string
		lineageTag: 59edffe5-0ae7-4317-8e85-a5385fe48a87
		summarizeBy: none
		sourceColumn: Tarea

		annotation SummarizationSetBy = Automatic

	column Etapa
		dataType: string
		lineageTag: eae2b2d8-e28e-49e7-87b6-dd1328ad276f
		summarizeBy: none
		sourceColumn: Etapa

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de negocio restante'
		dataType: int64
		formatString: 0
		lineageTag: ce9f6ac8-de7d-4491-949d-f0af39d45519
		summarizeBy: sum
		sourceColumn: Tiempo de negocio restante

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: int64
		formatString: 0
		lineageTag: eb8c9a7c-85df-43fd-9077-cfc5ef8edf61
		summarizeBy: sum
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: a1ae6ca1-77b0-4d62-b094-885bdb12479d
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Hora de inicio'
		dataType: dateTime
		formatString: General Date
		lineageTag: df97c16c-63c7-42ae-a0e6-55d0be11d44b
		summarizeBy: none
		sourceColumn: Hora de inicio

		variation Variation
			isDefault
			relationship: 6ec0d742-c0d5-4084-a395-f93e42d2f643
			defaultHierarchy: LocalDateTable_6680e904-7959-4182-97d6-20c73bd3c6cc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de pausa'
		dataType: string
		lineageTag: b0d55004-6c44-41f0-9418-2a13ca140c88
		summarizeBy: none
		sourceColumn: Tiempo de pausa

		annotation SummarizationSetBy = Automatic

	column 'Hora de finalización'
		dataType: dateTime
		formatString: General Date
		lineageTag: 603874f4-57ba-4444-9d8e-67c3b4e29003
		summarizeBy: none
		sourceColumn: Hora de finalización

		variation Variation
			isDefault
			relationship: ae9a7f90-d090-4d82-acf4-55ce3d95b525
			defaultHierarchy: LocalDateTable_4993cfe9-4249-4821-9e60-ca1e53d9538c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: 4f5eb927-a648-4b8b-9451-79af3eb90e2c
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Hora de finalización - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f97dfe6d-827f-4ed4-a1cb-5e2a5719a1d1
		summarizeBy: none
		sourceColumn: Hora de finalización - Copy

		variation Variation
			isDefault
			relationship: 65367430-15c7-4d2e-96e0-d485ed918178
			defaultHierarchy: LocalDateTable_41e01205-b8dc-49df-ae85-bd7a2fee388d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 29c2f4c1-6d30-4186-823c-e0609d46906e
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 64c918c5-c1c6-47b8-a669-efa3841bc183
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: bc911d91-735f-46d5-b0b4-90e241c875d5
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Hora de infracción'
		dataType: dateTime
		formatString: General Date
		lineageTag: 214134ab-b4f5-4eb3-bd81-3b4bc27db627
		summarizeBy: none
		sourceColumn: Hora de infracción

		variation Variation
			isDefault
			relationship: a4af2088-38f3-4cd1-8c80-eced946c6a1e
			defaultHierarchy: LocalDateTable_7bf73a75-129b-41e3-95a6-8e72ebf7240c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Duración D:HH:MM:SS' =
			
			VAR VDUR13 = 'PRO - Estimaciones con SLA'[Duración del negocio]
			  RETURN INT
			    (VDUR13/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR13/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR13/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR13,60)),2)
		lineageTag: 1be62269-1fe7-410c-b0ea-bdb0dfb8d6a6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: 213eab71-b953-4e96-97ba-f39b9e029603
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Duración excedida'
		dataType: string
		lineageTag: 693b019d-6ec1-46a1-ad63-25a92fc4c196
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column 'Duración_EX D:HH:MM:SS' =
			
			VAR VDUR13_EX = 'PRO - Estimaciones con SLA'[Duración excedida]
			  RETURN INT
			    (VDUR13_EX/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR13_EX/3600,24)),2)&" HH"
		lineageTag: 4fe12059-0566-44d0-a924-27f7d5f33a15
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Lote
		dataType: string
		lineageTag: 613f74f5-79a0-4fd0-95be-47565ee7f45b
		summarizeBy: none
		sourceColumn: Lote

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Estimaciones con SLA'[Tarea])
		lineageTag: 0d885b14-dda9-4405-8836-e22e2fbe37f2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Estimaciones con SLA-5a40b48a-1e50-4be9-880e-a8884b495a6d' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    URL = sharepointsource & Entorno & sharepointsource2 & estimaciones & xlsx,
				Origen = Excel.Workbook(Web.Contents(URL), null, true),
				#"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Creado", type datetime}, {"Número", type text}, {"Aplicación de Negocio", type text}, {"Prioridad", type text}, {"Tarea", type text}, {"Etapa", type text}, {"Tiempo de negocio restante", Int64.Type}, {"Duración del negocio", Int64.Type}, {"Porcentaje de negocio trascurrido", Percentage.Type}, {"Hora de inicio", type datetime}, {"Tiempo de pausa", type any}, {"Hora de finalización", type datetime}, {"Grupo de asignación", type text}, {"Infringido", type logical}, {"Hora de infracción", type datetime}, {"Duración", Int64.Type}}),
				    
				    //Genera Columna de Cerrado
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Hora de finalización", "Hora de finalización - Copy"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Duplicated Column",{{"Hora de finalización - Copy", type date}}),
				    #"Inserted Start of Month" = Table.AddColumn(#"Changed Type1", "Start of Month", each Date.StartOfMonth([#"Hora de finalización - Copy"]), type date),
				   
				   //Homologa las prioridades
				    #"AllReplace" = [#"1 - Crítica" = "Alta", #"2 - Alta" = "Alta", #"3 - Moderada" = "Media",#"4 - Baja" = "Baja",#"5 - Muy Baja" = "Baja"],    
				    #"Replaced Value" = Table.TransformColumns(#"Inserted Start of Month",{{"Prioridad",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    
				    //Pone "Nuevo Servicio" sobre Estimaciones de Demandas que no son Evolutivos
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",         "",             "Nuevo Servicio",Replacer.ReplaceValue,{"Aplicación de Negocio"}),
				
				    //Une con las alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value1", {"Tarea"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"Estado"}, {"PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Infringido" si la alegación es aceptada
				    #"Replaced Value6" = Table.ReplaceValue(#"Renamed Columns",each [Infringido],each if [Estado_Alegación] = "1 - Aprobada" then "FALSE" else [Infringido],Replacer.ReplaceValue,{"Infringido"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value6",{{"Infringido", type logical}}),
				
				    //Elimina los duplicados, y deja el último SLA finalizado
				    #"Sorted Rows" = Table.Buffer(Table.Sort(#"Changed Type2",{{"Hora de finalización - Copy", Order.Descending}})),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"Tarea"}),
				    
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Duplicates",{{"Duración", "Duración SLA"}}),
				
				    //Nuevo campo de Duración Excedida, respecto a SLA
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "Duración excedida", 
				    each if ([Duración del negocio]-[Duración SLA])<0 then 0 else 
				    ([Duración del negocio]-[Duración SLA])),
				    #"Divided Column" = Table.TransformColumns(#"Added Custom", {{"Porcentaje de negocio trascurrido", each _ / 100, Percentage.Type}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Divided Column", {"Grupo de asignación"}, Lote_Aplicacion_relacion, {"Grupo Asignación Estimaciones"}, "Lote_Aplicación_relación", JoinKind.LeftOuter),
				    #"Se expandió Lote_Aplicación_relación1" = Table.ExpandTableColumn(#"Consultas combinadas", "Lote_Aplicación_relación", {"Lote"}, {"Lote_Aplicación_relación.Lote"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Se expandió Lote_Aplicación_relación1",{{"Lote_Aplicación_relación.Lote", "Lote"}})
				in
				    #"Columnas con nombre cambiado"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

