table 'PRO - Incidencias con SLA - Críticas'
	lineageTag: 54347f42-f316-4025-aa02-ccf8c3a3a132

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0f620e0d-6da1-405f-a8c9-274cf9855b12
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Número
		dataType: string
		lineageTag: 65b6d513-d07c-4f08-b797-b020c0ae4fb5
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 10b422d3-bb4e-4775-8d03-180f4a1d1eb5
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 2a8ebaa6-819a-4b66-a00b-304932199090
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: a0247a70-90d3-43af-8d87-773df57bd618
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: df3f57d9-ef15-4646-954e-eaa420dac074
			defaultHierarchy: LocalDateTable_3f06b27f-0510-4dd2-8d37-7f92ac44a3e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		lineageTag: 418288fc-2f0b-42d5-80f5-e75862a32365
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 21150445-c11b-4b2b-b9dc-c06c22eb76ca
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: string
		lineageTag: 7ce717fa-6d20-4749-a5ea-4072dfff8849
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: e935390a-0934-48dc-8d64-74dcc167c809
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		lineageTag: 5f9fa1d1-bc01-473e-9c2a-82afbeb4660d
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ANS_Alegado
		dataType: string
		lineageTag: cbdf9201-e329-4891-9118-0657315b41d3
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: c571961d-212c-4ac0-b1c0-1bc072bfd393
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column Resuelto
		dataType: dateTime
		formatString: General Date
		lineageTag: 4f34c8cc-b00c-4817-bf21-b01b2b09aaa4
		summarizeBy: none
		sourceColumn: Resuelto

		variation Variación
			isDefault
			relationship: 5bb956d8-6ffb-48df-a622-576df888b54c
			defaultHierarchy: LocalDateTable_476391fa-b9d4-46f0-9e6d-55ef7dfab0cf.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Código de resolución'
		dataType: string
		lineageTag: cc1e9d04-6775-424e-916a-b63a5e2db0de
		summarizeBy: none
		sourceColumn: Código de resolución

		annotation SummarizationSetBy = Automatic

	column 'Volver a abrir recuento'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fee7703b-bec0-4c50-943d-ebfa5249a733
		summarizeBy: none
		sourceColumn: Volver a abrir recuento

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Solución'
		dataType: string
		lineageTag: ae946505-727c-44e9-9028-585233ced4ed
		summarizeBy: none
		sourceColumn: Tipo de Solución

		annotation SummarizationSetBy = Automatic

	column 'ID de correlación'
		dataType: string
		lineageTag: d880d9ce-b9f5-438d-b589-9ce186caee16
		summarizeBy: none
		sourceColumn: ID de correlación

		annotation SummarizationSetBy = Automatic

	column Principal
		dataType: string
		lineageTag: 28953ab2-b95d-4cde-8fd7-bf53d458b479
		summarizeBy: none
		sourceColumn: Principal

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: 168be09c-aaca-4390-83e8-1a4c91b14fd1
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: int64
		formatString: 0
		lineageTag: 9fd1eb44-a5d2-4f53-b45b-a844f8e1c187
		summarizeBy: sum
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column 'Estado de la incidencia'
		dataType: string
		lineageTag: 80b1b567-0e91-4193-957d-39c3236ceb7a
		summarizeBy: none
		sourceColumn: Estado de la incidencia

		annotation SummarizationSetBy = Automatic

	column Etapa
		dataType: string
		lineageTag: 8b651161-6fb0-4cd5-9121-40ed2108d8aa
		summarizeBy: none
		sourceColumn: Etapa

		annotation SummarizationSetBy = Automatic

	column Duración_1
		dataType: string
		lineageTag: 7a9b6765-7bfb-4301-b623-e3044fbd2da6
		summarizeBy: none
		sourceColumn: Duración_1

		annotation SummarizationSetBy = Automatic

	column 'Lote_Aplicación_relación.Lote'
		dataType: string
		lineageTag: c6917a31-17aa-4800-b7f6-5f3e4de91e4d
		summarizeBy: none
		sourceColumn: Lote_Aplicación_relación.Lote

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 5eaae3c7-1854-45c8-a931-6c3e090cb752
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 6dbf0279-890d-40b3-a2f3-82ae6c501ac1
			defaultHierarchy: LocalDateTable_3c9d5abb-fd83-43e4-8afe-7f97ff7af87a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: a8793f58-a3e2-4b22-b7f5-1c1c4822dd8a
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column 'Estado del incidente'
		dataType: string
		lineageTag: 6b84bb15-65e5-4190-b6e6-4151cce7e88c
		summarizeBy: none
		sourceColumn: Estado del incidente

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA - Críticas-3d482670-727d-48d4-bcc2-80f967e74dae' = m
		mode: import
		queryGroup: KGIs_II
		source =
				let
				    Source = #"PRO - Incidencias con SLA_P_y_A",
				    #"Filtered Rows" = Table.SelectRows(Source, each (
				        [Prioridad] = "Crítica"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

