table 'PRO - Planificaciones ENH'
	lineageTag: 524d3c9c-bc42-4c9b-b53e-3b03107a7793

	column Prioridad
		dataType: string
		lineageTag: b24a42a2-5c44-49cc-b88e-a0937ad6d1d8
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: f18c17e7-c219-4963-ac51-7739e76511e1
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: a7e1ca5e-ec6c-4742-ad89-07ba9490ef81
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 056a1726-9f0e-4974-b0e6-2c8155f1c2a6
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variation
			isDefault
			relationship: f0ac69d1-74c4-477c-bbf3-25f8da328df2
			defaultHierarchy: LocalDateTable_befbb3cf-edff-4711-be3c-e4d621d8d9e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha límite planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 80f3f809-67c8-4111-8577-36c70107bf71
		summarizeBy: none
		sourceColumn: Fecha límite planificada

		variation Variation
			isDefault
			relationship: e03c0d1d-d449-473a-9df5-c056ff95f569
			defaultHierarchy: LocalDateTable_6eea4b99-fcc3-4a06-b65b-48208e52226d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: f8300f77-a921-43fd-92c1-bf46ee882ccb
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: c5b5717a-51ac-49ee-b6ce-883405bad741
		summarizeBy: none
		sourceColumn: Inicio

		variation Variation
			isDefault
			relationship: 36e51c88-9c9e-4b5d-8ee2-886059cf8757
			defaultHierarchy: LocalDateTable_3dec0e66-0613-4adb-acfa-301fdf0b27c9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: b9d5c687-2292-4216-838a-6e7d6d3544cc
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: adea5bb8-1431-45e3-8c6d-816ca9a188f9
			defaultHierarchy: LocalDateTable_540c6fb8-a493-4f6b-b868-407172f4dba2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5a7787e1-6ff4-4624-8652-ed46ddf7170a
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: 1d7a852b-7c39-42bc-9de6-c121f816a844
			defaultHierarchy: LocalDateTable_db190ea0-f337-4efb-be85-5370ece8b6d3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: b8f073b1-5307-4c96-9c6e-21a0a9f66950
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: 22604ba0-6111-484f-a2e2-4a258fdb0b9a
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 71b16a76-a07d-4f40-8515-1b9ec925f656
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: c85000a0-dce9-4c01-9f38-6fd20a9cea08
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Servicio'
		dataType: string
		lineageTag: 4e00da36-66fa-491b-98f8-7b434819504a
		summarizeBy: none
		sourceColumn: Tipo de Servicio

		annotation SummarizationSetBy = Automatic

	column Demanda
		dataType: string
		lineageTag: 4d6dfb86-54d0-4c19-9ded-927aadb43186
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 7f693d69-bd2b-4dff-9867-bae41a00f7b8
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: c5c7b37a-74d0-48c0-ba9e-c05f44a7e98e
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: f28288d4-5d6c-4f03-9b01-866a4fd88e70
		summarizeBy: none
		sourceColumn: Fin

		variation Variación
			isDefault
			relationship: c932f2e4-36de-4d97-9a48-8ac9167caf67
			defaultHierarchy: LocalDateTable_83955aab-e707-4680-be85-f8a160eecf56.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones ENH-2190f109-9151-4b94-b221-5786518bc69d' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Source = Excel.Workbook(Web.Contents(globalPath & mejs & xlsx), null, true),
				    #"Page 1_Sheet" = Source{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Demanda", type text}, {"Mejora", type text}, {"Aplicación de Negocio", type text}, {"Prioridad", type text}, {"Abierto por", type text}, {"Grupo de asignación", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha fin planificada", type datetime}, {"Principal", type text}, {"Fecha Inicio Estimada", type datetime}, {"Fecha Fin Estimada", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Breve descripción", type text}}),
				    
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{
				        {"Abierto por",             "Jefe de proyecto (Project Manager)"}, 
				        {"Grupo de asignación",     "Aplicación de Negocio "}, 
				        {"Principal",               "Nombre"}, 
				        {"Fecha Inicio Estimada",   "Inicio"}, 
				        {"Fecha Fin Estimada", "Fin"},
				        {"Breve descripción",       "Nombre de PRJ o MEJ"}}),
				    
				    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns", null, "",Replacer.ReplaceValue,{"Nombre"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value2", "Tipo de Servicio", each "Mtto. Evolutivo"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Added Custom",{{"Mejora", "Número"}, {"Aplicación de Negocio", "Tipo de Proyecto"}, {"Fecha fin planificada", "Fecha límite planificada"}})
				
				in
				    #"Columnas con nombre cambiado"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

