table 'Resumen KGI12_E'
	lineageTag: 80b889eb-aeba-4d3d-acfc-9470dd71d214

	measure 'Puntos de KGI12_M' =
			
			var _KGI12_V = MIN('Resumen KGI12_E'[Puntos de KGI12])
			return
			IF(ISBLANK(_KGI12_V),30,_KGI12_V)
		lineageTag: 6c8a69a8-0902-4813-85eb-bfb3fcb2619e

	measure 'Peso Obtenido KGI12_M' = 1-SUM('Resumen KGI12_E'[Peso No Obtenido %])
		lineageTag: 97c158e1-9f4d-4bc7-9f9c-5c4dbdee1b8d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Puntos Obtenidos KGI12_M' = [Peso Obtenido KGI12_M]*[Puntos de KGI12_M]
		lineageTag: 9e2b0715-0f22-4f4a-a587-952159406181

	column Prioridad
		dataType: string
		lineageTag: 1baf980e-449b-48ba-84f7-a260086236e3
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 656e89f8-53d4-431b-ad6d-d0019c1d2d0e
		summarizeBy: none
		sourceColumn: Fecha fin real - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Cump. Objetivo %'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 30edcfcf-377e-46b0-98a8-f16a58b2b4bf
		summarizeBy: sum
		sourceColumn: Cump. Objetivo %

		annotation SummarizationSetBy = Automatic

	column 'Peso %'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: ec081794-9b0d-46e4-98ba-77c93f299e03
		summarizeBy: sum
		sourceColumn: Peso %

		annotation SummarizationSetBy = Automatic

	column 'Planificaciones Cumplidas' = 'Resumen KGI12_E'[Total Planificaciones]-'Resumen KGI12_E'[Planificaciones Incumplidas]
		formatString: 0
		lineageTag: f7f8448e-9691-435b-a400-83e24edf5c6e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Cump. Real %' = ('Resumen KGI12_E'[Planificaciones Cumplidas])/('Resumen KGI12_E'[Total Planificaciones])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: f7a5ca1d-e19d-4e62-ab56-54a727f2291a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ¿Cumple? = IF('Resumen KGI12_E'[Cump. Real %]>='Resumen KGI12_E'[Cump. Objetivo %],"Si","No")
		lineageTag: 4381397e-4952-4e29-a28e-ea3751452019
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Peso Obtenido %' = IF('Resumen KGI12_E'[¿Cumple?]="Si",'Resumen KGI12_E'[Peso %],0)
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 95396440-82d2-48f5-b151-57957b262fea
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column KGI
		dataType: string
		lineageTag: 788dd2b7-93c8-45b2-b059-7ced15fe5751
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	column 'Peso No Obtenido %' = IF('Resumen KGI12_E'[¿Cumple?]="No",'Resumen KGI12_E'[Peso %],0)
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 04f68dd0-fbaf-4db7-88a4-96c43c029ec3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Total Planificaciones'
		dataType: int64
		formatString: 0
		lineageTag: 523d91e1-55b7-41c2-9a52-7a41d94fb7d4
		summarizeBy: sum
		sourceColumn: Total Planificaciones

		annotation SummarizationSetBy = Automatic

	column 'Puntos de KGI12'
		dataType: string
		lineageTag: 642dddc1-5816-4c1b-ad47-612dbecb6b68
		summarizeBy: none
		sourceColumn: Puntos de KGI12

		annotation SummarizationSetBy = Automatic

	column 'Planificaciones Incumplidas'
		dataType: double
		formatString: 0
		lineageTag: 3f4a8981-f26a-4b52-b868-9fd5ab479beb
		summarizeBy: sum
		sourceColumn: Planificaciones Incumplidas

		annotation SummarizationSetBy = Automatic

	column Lote
		dataType: string
		lineageTag: 69d1e5e4-1f24-4616-82cd-2bfe8b56d957
		summarizeBy: none
		sourceColumn: Lote

		annotation SummarizationSetBy = Automatic

	partition 'Resumen KGI12_E-92fbc821-a30e-445a-bc7f-df91b496157d' = m
		mode: import
		queryGroup: Resumen
		source = ```
				let
				    Source = #"PRO - Planificaciones PRJ y ENH con SLA_M",
				    #"Filtered Rows1" = Table.SelectRows(Source, each Text.Contains([Tipo de Servicio], "Mtto.")),
				    //Agrupar Total Planificaciones
				    #"Grouped Rows" = Table.Group(#"Filtered Rows1", {"Prioridad", "Fecha fin real - Copy", "Lote"}, {{"Total Planificaciones", each Table.RowCount(_), Int64.Type}}),
				    
				    //Unir Total Planificaciones Incumplidas
				    #"Merged Queries" = Table.NestedJoin(#"Grouped Rows", {"Prioridad", "Fecha fin real - Copy", "Lote"}, #"PRO - Planificaciones PRJ y ENH con SLA - Incumplidas", {"Prioridad", "Fecha fin real - Copy", "Lote"}, "PRO - Planificaciones PRJ y ENH con SLA - Incumplidas", JoinKind.LeftOuter),    
				    #"Expanded PRO - Planificaciones PRJ y ENH con SLA - Incumplidas" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Planificaciones PRJ y ENH con SLA - Incumplidas", {"Estimación Incumplida"}, {"Planificaciones Incumplidas"}),    
				    
				    //Unir Tabla de Parámetros 
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded PRO - Planificaciones PRJ y ENH con SLA - Incumplidas", {"Prioridad"}, #"Parametros KGI12_E", {"Prioridad Hitos Evolutivos"}, "Parametros KGI1-2", JoinKind.LeftOuter),    
				    #"Expanded Parametros KGI1-2" = Table.ExpandTableColumn(#"Merged Queries1", "Parametros KGI1-2", {"% cumplimiento Objetivo", "Pesos %"}, {"Parametros KGI1-2.% cumplimiento Objetivo", "Parametros KGI1-2.Pesos %"}),    
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Parametros KGI1-2",{{"Parametros KGI1-2.% cumplimiento Objetivo", "Cump. Objetivo %"}, {"Parametros KGI1-2.Pesos %", "Peso %"}}),
				    
				    #"Sorted Rows" = Table.Sort(#"Renamed Columns1",{{"Fecha fin real - Copy", Order.Ascending}}),
				    
				    //Añadir otras columnas de valores constantes
				    #"Added Custom" = Table.AddColumn(#"Sorted Rows", "KGI", each "KGI1-2"),    
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Puntos de KGI12", each 30),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Added Custom1",null,0,Replacer.ReplaceValue,{"Planificaciones Incumplidas"})
				in
				    #"Valor reemplazado"
				```

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = Resumen KGI12_E

	annotation PBI_NavigationStepName = Navigation

