table 'SERV_NOW incident'
	lineageTag: a5428685-7bc3-42df-b268-8850e2f5e284

	measure Conteo = ```
			
			COALESCE(
			    COUNTROWS('SERV_NOW incident'),
			    0
			)
			
			
			
			```
		formatString: 0
		lineageTag: b7e6f5a1-83f1-4336-901f-672cde9851ab

		changedProperty = IsHidden

	measure Incidencias_Criticas = ```
			COALESCE(CALCULATE(
			    COUNTROWS('SERV_NOW incident'),
			    'SERV_NOW incident'[Prioridad] = "1 - Critical",
			    'SERV_NOW incident'[Estado] = "In progress",'SERV_NOW incident'[Estado] = "On hold"
			), 0)
			
			```
		formatString: 0
		lineageTag: 97f62b77-a76e-47a6-8a0d-025a9df3bafb

		changedProperty = IsHidden

	measure Incidencias_Altas = ```
			COALESCE(CALCULATE(
			    COUNTROWS('SERV_NOW incident'),
			    'SERV_NOW incident'[Prioridad] = "2 - High",
			    'SERV_NOW incident'[active] = TRUE()
			), 0)
			
			```
		formatString: 0
		lineageTag: b15a82a4-a7fc-40a3-a83b-f4a8a986e8a7

		changedProperty = IsHidden

	measure Incidencias_Moderadas = ```
			COALESCE(CALCULATE(
			    COUNTROWS('SERV_NOW incident'),
			    'SERV_NOW incident'[Prioridad] = "3 - Moderate",
			    'SERV_NOW incident'[active] = TRUE()
			), 0)
			
			```
		formatString: 0
		lineageTag: aa7070a7-d168-42d5-8473-a683cfe569bf

		changedProperty = IsHidden

	measure Incidencias_Bajas = ```
			COALESCE(CALCULATE(
			    COUNTROWS('SERV_NOW incident'),
			    'SERV_NOW incident'[Prioridad] = "4 - Low",
			    'SERV_NOW incident'[active] = TRUE()
			), 0)
			
			```
		formatString: 0
		lineageTag: 309b11a0-375f-41f7-ad26-736049efd157

		changedProperty = IsHidden

	measure Incidencias_Muybajas = ```
			COALESCE(CALCULATE(
			    COUNTROWS('SERV_NOW incident'),
			    'SERV_NOW incident'[Prioridad] = "5 - Very Low",
			    'SERV_NOW incident'[Estado] = "In progress",'SERV_NOW incident'[Estado] = "On hold"
			), 0)
			
			```
		formatString: 0
		lineageTag: 5d8a5195-533a-4f77-8d23-410c5b90b727

		changedProperty = IsHidden

	measure Tiempo_Medio_critical = ```
			
			CALCULATE(
			    AVERAGE('SERV_NOW incident'[TiempoEnDias]),
			    'SERV_NOW incident'[Prioridad] = "1 - Critical",
			    'SERV_NOW incident'[TiempoEnDias] <> 0
			)
			
			```
		lineageTag: c34c2c61-118d-4dba-bdeb-ee8dccd87bba

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tiempo_Medio_altas = ```
			
			CALCULATE(
			    AVERAGE('SERV_NOW incident'[TiempoEnDias]),
			    'SERV_NOW incident'[Prioridad] = "2 - High",
			    'SERV_NOW incident'[TiempoEnDias] <> 0  -- Excluye los registros con TiempoEnDias igual a 0
			)
			
			```
		lineageTag: 16575aae-6f67-4e7e-8dfa-1547e2c7bf38

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tiempo_Medio_moderate = ```
			
			CALCULATE(
			    AVERAGE('SERV_NOW incident'[TiempoEnDias]),
			    'SERV_NOW incident'[Prioridad] = "3 - Moderate",
			    'SERV_NOW incident'[TiempoEnDias] <> 0
			)
			
			```
		lineageTag: aa67d41d-f1b2-40db-a334-3c57aea72790

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tiempo_Medio_low = ```
			
			CALCULATE(
			    AVERAGE('SERV_NOW incident'[TiempoEnDias]),
			    'SERV_NOW incident'[Prioridad] = "4 - Low",
			    'SERV_NOW incident'[TiempoEnDias] <> 0
			)
			
			```
		lineageTag: d7ea1aec-36b3-45c7-a87b-9d70400ad51d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tiempo_Medio_very_low = ```
			
			CALCULATE(
			    AVERAGE('SERV_NOW incident'[TiempoEnDias]),
			    'SERV_NOW incident'[Prioridad] = "5 - Very Low",
			    'SERV_NOW incident'[TiempoEnDias] <> 0
			)
			
			```
		lineageTag: a31f8521-c9f6-4d89-96e7-e4e462657296

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Semana_Actual = ```
			WEEKNUM(TODAY(), 2)
			
			```
		formatString: 0
		lineageTag: 60038c3d-abe9-41f7-a84c-4ca6de29f6fc

		changedProperty = IsHidden

	measure 'Semana número' = "semana " & [Semana_Actual]
		lineageTag: 350c14cb-e75a-4e11-ab04-f315732121a4

	measure 'Semana total' = "Total semana " & [Semana_Actual]
		lineageTag: 4aa2f8a9-a3d2-495a-9162-22bc00dc0787

	measure Semana_Anterior = ```
			
			VAR SemanaActual = WEEKNUM(TODAY(), 2)  -- Semana actual
			VAR SemanaAnterior = IF(SemanaActual = 1, 52, SemanaActual - 1)  -- Si la semana actual es 1, la anterior será 52
			RETURN SemanaAnterior
			
			```
		formatString: 0
		lineageTag: cee7d59e-f1db-46c6-a880-59a5fa5a7e72

	measure 'Semana_anterior total' = "Total semana " & [Semana_Anterior]
		lineageTag: 974541b9-5406-4cb5-b330-c9f9d84f2591

	measure IncidenciasAbiertas_SemanaAnterior = ```
			
			VAR FechaHoy = TODAY()
			VAR SemanaActual = WEEKNUM(FechaHoy, 2)
			VAR AnioActual = YEAR(FechaHoy)
			VAR SemanaAnterior = IF(SemanaActual = 1, 52, SemanaActual - 1)
			VAR AnioAnterior = IF(SemanaActual = 1, AnioActual - 1, AnioActual)
			RETURN
			COALESCE(
			    CALCULATE(
			        COUNTROWS('SERV_NOW incident'),
			        WEEKNUM('SERV_NOW incident'[opened_at], 2) = SemanaAnterior,
			        YEAR('SERV_NOW incident'[opened_at]) = AnioAnterior
			    ),
			    0
			)
			
			```
		formatString: 0
		lineageTag: 650299fb-971e-4e2b-aa32-91139497bafd

	measure IncidenciasCerradas_SemanaAnterior = ```
			
			VAR FechaHoy = TODAY()
			VAR SemanaActual = WEEKNUM(FechaHoy, 2)
			VAR AnioActual = YEAR(FechaHoy)
			VAR SemanaAnterior = IF(SemanaActual = 1, 52, SemanaActual - 1)
			VAR AnioAnterior = IF(SemanaActual = 1, AnioActual - 1, AnioActual)
			RETURN
			COALESCE(
			    CALCULATE(
			        COUNTROWS('SERV_NOW incident'),
			        WEEKNUM('SERV_NOW incident'[closed_at], 2) = SemanaAnterior,
			        YEAR('SERV_NOW incident'[closed_at]) = AnioAnterior
			    ),
			    0
			)
			
			
			```
		formatString: 0
		lineageTag: ed2ee58b-0874-494c-998a-913148290af7

	measure IncidenciasResueltas_SemanaAnterior = ```
			
			VAR FechaHoy = TODAY()
			VAR SemanaActual = WEEKNUM(FechaHoy, 2)
			VAR AnioActual = YEAR(FechaHoy)
			VAR SemanaAnterior = IF(SemanaActual = 1, 52, SemanaActual - 1)
			VAR AnioAnterior = IF(SemanaActual = 1, AnioActual - 1, AnioActual)
			RETURN
			COALESCE(
			    CALCULATE(
			        COUNTROWS('SERV_NOW incident'),
			        WEEKNUM('SERV_NOW incident'[resolved_at], 2) = SemanaAnterior,
			        YEAR('SERV_NOW incident'[resolved_at]) = AnioAnterior
			    ),
			    0
			)
			
			
			```
		formatString: 0
		lineageTag: ff02d3e2-6ea7-4733-8a05-af934b823bef

	measure Medida_Tarjeta_Limpia = ```
			
			VAR Total = [Conteo]
			RETURN
			IF(
			    ISBLANK(Total) || Total = 0,
			    UNICHAR(8203),  -- invisible
			    INT(Total)  -- Elimina los decimales (redondeo hacia abajo)
			)
			
			
			```
		lineageTag: 15e914fe-bdc8-42b3-8736-90228cc32c65

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9c3be986-fb63-4d8f-bbb5-99936d64f682
		summarizeBy: none
		sourceColumn: active

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Técnico
		dataType: string
		lineageTag: 46a332fd-b28c-4e43-b924-ff5d975d6c97
		summarizeBy: none
		sourceColumn: Técnico

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: f2169d3c-daee-4d47-9f29-dd8571d8224f
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: 3afdd7d4-0bcd-4a1c-ac38-35bb00a1aac6
			defaultHierarchy: LocalDateTable_c93d9251-87e8-4c8a-b5f6-ea1188e04d89.'Jerarquía de fechas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dv_hold_reason
		dataType: string
		lineageTag: 2654ba88-26ac-48cf-8f1e-d3d899ec36d4
		summarizeBy: none
		sourceColumn: dv_hold_reason

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Tarea
		dataType: string
		lineageTag: 300d17f8-fca8-4249-917f-6d25645736b3
		summarizeBy: none
		sourceColumn: Tarea

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: e1cbb149-6543-4d35-81fa-764191e1ee41
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: 00d8ceff-bb3f-410b-bf54-60bf9aad99ee
			defaultHierarchy: LocalDateTable_caf1c68c-bf28-4d6f-9e5c-269329f5ceb8.'Jerarquía de fechas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 108a07c3-8a01-477a-8092-fb2556286839
		summarizeBy: none
		sourceColumn: Prioridad

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column resolved_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 27232b34-50f8-4fa6-b166-7b786b285f3f
		summarizeBy: none
		sourceColumn: resolved_at

		variation Variación
			isDefault
			relationship: 6472bd03-9a54-456c-8038-e83de51ab076
			defaultHierarchy: LocalDateTable_23fb2d31-b9a8-4300-81dc-cd5da37d0cbe.'Jerarquía de fechas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Descripción
		dataType: string
		lineageTag: aca957bc-2126-4678-b6bd-50cd402132cc
		summarizeBy: none
		sourceColumn: Descripción

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 55538654-ea1f-4ec3-b316-25be91e07f14
		summarizeBy: none
		sourceColumn: Estado

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dv_u_incident_diagnostic
		dataType: string
		lineageTag: 967d0696-703c-4d4e-a1c1-e676b3a0ec82
		summarizeBy: none
		sourceColumn: dv_u_incident_diagnostic

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Dia_Abierto = ```
			FORMAT('SERV_NOW incident'[opened_at], "dddd")
			
			```
		lineageTag: 91f1dba5-bd18-42d6-828f-a7aee38d0b2b
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Dia_Cerrado = ```
			FORMAT('SERV_NOW incident'[closed_at], "dddd")
			
			```
		lineageTag: 5e002954-3a3f-4ab2-b657-45b95e380f17
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Dia_Resuelto = ```
			FORMAT('SERV_NOW incident'[resolved_at], "dddd")
			
			```
		lineageTag: d6508b08-3ae7-417b-bb61-fb5bdc52e057
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dv_u_subcategory_module
		dataType: string
		lineageTag: 3db7e39e-0d44-43b1-9db2-042055dd991d
		summarizeBy: none
		sourceColumn: dv_u_subcategory_module

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Tiempo_Resolucion = ```
			DATEDIFF('SERV_NOW incident'[opened_at].[Date], 'SERV_NOW incident'[resolved_at].[Date], DAY)
			
			```
		formatString: 0
		lineageTag: 2f5b8cd0-a099-45a3-9bc1-9937800de9ea
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Numero_Semana_abierta = ```
			
			IF(
			    'SERV_NOW incident'[opened_at] >= DATE(2025, 1, 1),  -- Solo considera fechas a partir de 2025
			    WEEKNUM('SERV_NOW incident'[opened_at], 2),  -- Calcula el número de semana
			    BLANK()  -- Si la fecha es anterior a 2025, no se calcula la semana
			)
			
			
			```
		formatString: 0
		lineageTag: 8e434ed3-c897-4fcb-8487-4fd538c0cc3f
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Estado_Apertura = ```
			IF(
			    NOT(ISBLANK('SERV_NOW incident'[opened_at])), 
			    "Abierto", 
			    "Cerrado"
			)
			
			```
		lineageTag: 81ca5d26-692e-432c-828a-786af384e084
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Estado_cerrado = ```
			IF(
			    NOT(ISBLANK('SERV_NOW incident'[closed_at])), 
			    "cerrado", 
			    ""
			)
			
			```
		lineageTag: 699d5e08-65c2-41d3-bacc-4c3ad06cd024
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Numero_Semana_cerrada =
			
			IF(
			    'SERV_NOW incident'[closed_at] >= DATE(2025, 1, 1),  -- Solo considera fechas a partir de 2025
			    WEEKNUM('SERV_NOW incident'[closed_at], 2),  -- Calcula el número de semana
			    BLANK()  -- Si la fecha es anterior a 2025, no se calcula la semana
			)
		formatString: 0
		lineageTag: 19650f16-3ffe-4baa-bdd9-c088aa5a2292
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Numero_Semana_Resuelta =
			
			IF(
			    'SERV_NOW incident'[resolved_at] >= DATE(2025, 1, 1),  -- Solo considera fechas a partir de 2025
			    WEEKNUM('SERV_NOW incident'[resolved_at], 2),  -- Calcula el número de semana
			    BLANK()  -- Si la fecha es anterior a 2025, no se calcula la semana
			)
		formatString: 0
		lineageTag: dbcaa247-9fc9-49e2-ab26-f987bb44ab98
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Lunes_Anterior_abierto =
			
			VAR DiaSemana = WEEKDAY('SERV_NOW incident'[opened_at], 2)  -- 2 hace que la semana empiece el lunes (Lunes = 1, Domingo = 7)
			VAR FechaInicio = 'SERV_NOW incident'[opened_at]
			RETURN
			    IF(
			        DiaSemana = 1,  -- Si es lunes, la fecha no cambia
			        FechaInicio,
			        FechaInicio - DiaSemana + 1  -- Si no es lunes, retrocede al lunes anterior
			    )
		formatString: Short Date
		lineageTag: 9a80feac-70d1-4003-b013-1a18b87d66cd
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Lunes_Anterior_cerrada =
			
			VAR DiaSemana = WEEKDAY('SERV_NOW incident'[closed_at], 2)  -- 2 hace que la semana empiece el lunes (Lunes = 1, Domingo = 7)
			VAR FechaInicio = 'SERV_NOW incident'[closed_at]
			var Fecha=
			    IF(
			        DiaSemana = 1,  -- Si es lunes, la fecha no cambia
			        FechaInicio,
			        FechaInicio - DiaSemana + 1  -- Si no es lunes, retrocede al lunes anterior
			    )
			RETURN IF(ISBLANK('SERV_NOW incident'[closed_at]),BLANK(),Fecha)
		formatString: Short Date
		lineageTag: a27b132f-c379-43c6-aecb-38df28a04467
		summarizeBy: none

		variation Variación
			isDefault
			relationship: 8b69a4ff-56e4-4829-95a8-91af8c510ac2
			defaultHierarchy: LocalDateTable_1b46fa84-2d7f-4c22-9fc6-23625de78656.'Jerarquía de fechas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Primer_Dia_Mes_abierto = ```
			
			VAR FechaInicio = 'SERV_NOW incident'[opened_at]
			VAR MesActual = MONTH(FechaInicio)  -- Obtiene el mes de la fecha de apertura
			VAR AnoActual = YEAR(FechaInicio)  -- Obtiene el año de la fecha de apertura
			RETURN 
			    DATE(AnoActual, MesActual, 1)  -- Devuelve el primer día del mes actual
			
			```
		formatString: Short Date
		lineageTag: f35bc3a0-677c-4a55-93c7-7b9300c51573
		summarizeBy: none

		variation Variación
			isDefault
			relationship: 85c6e606-62ff-42b7-95e4-159adbf6e97d
			defaultHierarchy: LocalDateTable_99bdc36d-0ea7-4df4-8249-62abea8c6c7a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Primer_Dia_Mes_Cerrado = ```
			
			VAR FechaCierre = 'SERV_NOW incident'[closed_at]  -- Referencia a la fecha de cierre
			VAR FechaInicio = IF(NOT(ISBLANK(FechaCierre)), DATEVALUE(FechaCierre), BLANK())  -- Si la fecha de cierre no está en blanco, convierte a solo fecha
			VAR MesActual = IF(NOT(ISBLANK(FechaInicio)), MONTH(FechaInicio), BLANK())  -- Obtiene el mes si la fecha no está en blanco
			VAR AnoActual = IF(NOT(ISBLANK(FechaInicio)), YEAR(FechaInicio), BLANK())  -- Obtiene el año si la fecha no está en blanco
			RETURN 
			    IF(
			        NOT(ISBLANK(FechaInicio)),  -- Si la fecha no está en blanco
			        DATE(AnoActual, MesActual, 1),  -- Devuelve el primer día del mes
			        BLANK()  -- Si la fecha está en blanco, devuelve BLANK()
			    )
			
			
			```
		formatString: Short Date
		lineageTag: 1ba04542-1daa-496a-8910-69f11380847b
		summarizeBy: none

		variation Variación
			isDefault
			relationship: bd140cee-e67b-4e45-ac46-c90f91263e9f
			defaultHierarchy: LocalDateTable_f2878cf3-e7c3-49a1-8f82-7882eaa5b5ec.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Subcategoría = ```
			
			VAR Valor = TRIM('SERV_NOW incident'[dv_u_subcategory_module])
			RETURN
			IF(
			    Valor = "" || ISBLANK(Valor),
			    "Sin categorizar",
			    Valor
			)
			
			```
		lineageTag: 79097884-5b57-436e-9fdb-42551759e36e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Diagnostico =
			
			VAR Valor = TRIM('SERV_NOW incident'[dv_u_incident_diagnostic])
			RETURN
			IF(
			    Valor = "" || ISBLANK(Valor),
			    "Sin categorizar",
			    Valor
			)
		lineageTag: 17216bfd-2e3e-45de-8b0a-931db0966069
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Mes_Año = ```
			FORMAT('SERV_NOW incident'[opened_at], "mmm yyyy")
			
			```
		lineageTag: 7a885746-a2c9-4780-a1ca-a6938cdaa32e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column dv_u_subcategory
		dataType: string
		lineageTag: 86d6f6f4-ebaf-484f-85f2-3c13246c730c
		summarizeBy: none
		sourceColumn: dv_u_subcategory

		annotation SummarizationSetBy = Automatic

	column calendar_stc
		dataType: int64
		formatString: 0
		lineageTag: e4fd596a-4ec9-4368-a604-1687a9e869bf
		summarizeBy: sum
		sourceColumn: calendar_stc

		annotation SummarizationSetBy = Automatic

	column TiempoEnDias = ```
			ROUND('SERV_NOW incident'[calendar_stc] / 86400, 2)
			
			
			```
		lineageTag: ccbca7e0-066c-4634-a066-d42a14c6cbce
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dv_assignment_group
		dataType: string
		lineageTag: 6b52d856-96f0-48c2-a693-7768e20014cf
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column Incidencia_Relevante = ```
			
			VAR FechaLimite = TODAY() - 14
			RETURN
			IF(
			    'SERV_NOW incident'[active] = TRUE()
			    || 'SERV_NOW incident'[opened_at] >= FechaLimite
			    || 'SERV_NOW incident'[closed_at] >= FechaLimite
			    || 'SERV_NOW incident'[resolved_at] >= FechaLimite,
			    "Sí",
			    "No"
			)
			
			```
		lineageTag: 35939057-ad34-4cbc-aa9d-4a9ee876c7e7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'SERV_NOW incident' = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("QECCDWH.acciona.int,60001"),
				    DWH = Origen{[Name="DWH"]}[Data],
				    SERV_NOW_incident = DWH{[Schema="SERV_NOW",Item="incident"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(SERV_NOW_incident, each ([dv_assignment_group] = "EJE.SOPCRM365_EXT.AE")),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Filas filtradas",{"active", "dv_assigned_to", "dv_assignment_group", "calendar_stc", "closed_at", "dv_hold_reason", "number", "opened_at", "dv_priority", "resolved_at", "short_description", "dv_state", "dv_u_incident_diagnostic", "dv_u_subcategory", "dv_u_subcategory_module"}),
				    #"Filas filtradas3" = Table.SelectRows(#"Otras columnas quitadas", each true),
				    #"Filas filtradas1" = Table.SelectRows(#"Filas filtradas3", each true),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Filas filtradas1",{{"short_description", "Descripción"}, {"number", "Tarea"}, {"dv_assigned_to", "Técnico"}, {"dv_state", "Estado"}, {"dv_priority", "Prioridad"}}),
				    #"Filas filtradas2" = Table.SelectRows(#"Columnas con nombre cambiado", each ([Estado] <> "Canceled"))
				in
				    #"Filas filtradas2"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

