table 'Cambios de Alcance'
	lineageTag: 0b10cf8b-fe0a-4092-996d-bc46e0d438e3

	column Número
		dataType: string
		lineageTag: 1725ce16-1398-444b-a3ee-3462c0c9ae87
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Numero_Asociado
		dataType: string
		lineageTag: 8b6f2534-f4f8-48cb-9810-222afc17c8b1
		summarizeBy: none
		sourceColumn: Numero_Asociado

		annotation SummarizationSetBy = Automatic

	column Activo
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ab4931a6-24cb-4fb5-8a73-a61cb4a2c954
		summarizeBy: none
		sourceColumn: Activo

		annotation SummarizationSetBy = Automatic

	column Descripción
		dataType: string
		lineageTag: dead74e7-0304-4b6c-b84e-d4982e5aa8b3
		summarizeBy: none
		sourceColumn: Descripción

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: f03c97ce-73c9-4531-b3e0-f2d30f8613ad
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Fecha de estado'
		dataType: dateTime
		formatString: General Date
		lineageTag: bc18d3a1-814c-4978-8498-5b9901ebeb1b
		summarizeBy: none
		sourceColumn: Fecha de estado

		variation Variación
			isDefault
			relationship: c890e641-2f31-4629-93e2-8ddec5d1b504
			defaultHierarchy: LocalDateTable_abddb964-281f-417e-9192-876934a44f75.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Aprobación
		dataType: string
		lineageTag: 589f3e2c-86eb-4783-9933-06c7906312d7
		summarizeBy: none
		sourceColumn: Aprobación

		annotation SummarizationSetBy = Automatic

	column Creado
		dataType: dateTime
		formatString: General Date
		lineageTag: 3a00e803-ee36-49a8-a6fc-13785917e88c
		summarizeBy: none
		sourceColumn: Creado

		variation Variación
			isDefault
			relationship: 353c053c-ffac-4d4b-8c89-c3afca1d7f2c
			defaultHierarchy: LocalDateTable_294d8284-852a-4f92-96a2-be7145581bc4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Creado por'
		dataType: string
		lineageTag: c8dbec8c-aa8c-4d6a-a163-db484e783065
		summarizeBy: none
		sourceColumn: Creado por

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: 67c7a440-9f09-4756-a5bc-c299be47f4f9
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column Impacto
		dataType: string
		lineageTag: 2c57ecce-9d31-4686-ab74-d9475678f714
		summarizeBy: none
		sourceColumn: Impacto

		annotation SummarizationSetBy = Automatic

	column 'Inicio real'
		dataType: string
		lineageTag: fb2c3b06-9222-4af3-8079-bebf84afac15
		summarizeBy: none
		sourceColumn: Inicio real

		annotation SummarizationSetBy = Automatic

	column 'Finalización real'
		dataType: string
		lineageTag: 7f0ac3fb-b5e7-4e63-a5ab-d0858adc9c8e
		summarizeBy: none
		sourceColumn: Finalización real

		annotation SummarizationSetBy = Automatic

	column ZCC_Coste_Asociado_CambioAlcance = BLANK()
		formatString: 0
		lineageTag: 8067b682-429d-410e-a982-2a3d77f719dd
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Título
		dataType: string
		lineageTag: 55396e59-f664-4393-8872-2eb724c80252
		summarizeBy: none
		sourceColumn: Título

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 03e1ceba-cee6-450e-991a-eb62952eaca3
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Fecha de vencimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: bf0e00ff-ea8e-4dea-9862-ed3eb7f292ca
		summarizeBy: none
		sourceColumn: Fecha de vencimiento

		variation Variación
			isDefault
			relationship: b14bbd47-3058-4867-802e-5d137712429a
			defaultHierarchy: LocalDateTable_3d55f504-7a3e-4860-ac0a-54aef24649d6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Coste estimado'
		dataType: double
		lineageTag: d37355e3-f7c4-4909-b457-6099477c4ec8
		summarizeBy: sum
		sourceColumn: Coste estimado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fecha de Aprobación'
		dataType: dateTime
		formatString: General Date
		lineageTag: a097f98b-6e47-40b9-b83c-79d5fade7a4c
		summarizeBy: none
		sourceColumn: Fecha de Aprobación

		variation Variación
			isDefault
			relationship: 0349442f-14ee-4458-96d7-1723df454bd7
			defaultHierarchy: LocalDateTable_f6e41839-0eb5-437d-9233-20532f162137.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Asignado a'
		dataType: string
		lineageTag: fdd4c765-a5f2-4d2e-9f5b-dd2ac2d005e1
		summarizeBy: none
		sourceColumn: Asignado a

		annotation SummarizationSetBy = Automatic

	partition 'Cambios de Alcance' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(Web.Contents("https://acciona365.sharepoint.com/sites/EN_TIC_COORD_PRO/Documentos%20compartidos/Ejecucion/EN_COORD_CDM-CAMBIOS-ALCANCE.xlsx"), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Número", type text}, {"Título", type text}, {"Número_1", type text}, {"Activo", type logical}, {"Descripción", type text}, {"Prioridad", type text}, {"Estado", type text}, {"Fecha de estado", type datetime}, {"Aprobación", type text}, {"Fecha de vencimiento", type datetime}, {"Creado", type datetime}, {"Creado por", type text}, {"Grupo de asignación", type text}, {"Impacto", type text}, {"Inicio real", type any}, {"Finalización real", type any}, {"Coste estimado", type number}, {"Fecha de Aprobación", type datetime}, {"Asignado a", type any}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"Número_1", "Numero_Asociado"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

