table 'SERV_NOW_EN V_rm_enhancement Enlazado_a_Completa'
	lineageTag: 86fdf714-78ee-45db-bba2-6d5e2318a583

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3f19e1dd-4ff3-45de-9310-7c67d26d9028
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column activity_due
		dataType: dateTime
		formatString: General Date
		lineageTag: 94618234-ddf6-4379-b7b2-2b9f36feaf01
		summarizeBy: none
		sourceColumn: activity_due

		variation Variación
			isDefault
			relationship: b5216cfd-b55d-484f-b12d-eeba8a530610
			defaultHierarchy: LocalDateTable_073d8181-e4e4-4d9e-b24e-627e29abb015.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column actual_benefits
		dataType: double
		lineageTag: 3fdbad54-8a51-4326-8d42-1f9d17cb0c9c
		summarizeBy: sum
		sourceColumn: actual_benefits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column additional_assignee_list
		dataType: string
		lineageTag: 8059a3d4-8d38-4bf1-92e9-76972b6e2f69
		summarizeBy: none
		sourceColumn: additional_assignee_list

		annotation SummarizationSetBy = Automatic

	column allow_dates_outside_schedule
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7e60e1d9-0f11-4616-8da9-fab3382a4888
		summarizeBy: none
		sourceColumn: allow_dates_outside_schedule

		annotation SummarizationSetBy = Automatic

	column approval
		dataType: string
		lineageTag: 7e791546-a1c6-4b2a-aa35-5c60d623a2ab
		summarizeBy: none
		sourceColumn: approval

		annotation SummarizationSetBy = Automatic

	column dv_approval
		dataType: string
		lineageTag: 11041bbd-a764-454a-8d20-03a984ac2d6c
		summarizeBy: none
		sourceColumn: dv_approval

		annotation SummarizationSetBy = Automatic

	column approval_history
		dataType: string
		lineageTag: 0ef00891-0741-4aa0-927f-1ea079e92840
		summarizeBy: none
		sourceColumn: approval_history

		annotation SummarizationSetBy = Automatic

	column approval_set
		dataType: dateTime
		formatString: General Date
		lineageTag: 2940beca-4701-41c5-a0e2-6eb0b82e4055
		summarizeBy: none
		sourceColumn: approval_set

		variation Variación
			isDefault
			relationship: b232c44d-890d-4b04-bdf7-616c5a76c21c
			defaultHierarchy: LocalDateTable_735214b5-4fec-494d-b0db-3c4acdf4fbc2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column assigned_to
		dataType: string
		lineageTag: 6e93f010-7fe4-425f-a6c0-c73cb454fcd9
		summarizeBy: none
		sourceColumn: assigned_to

		annotation SummarizationSetBy = Automatic

	column dv_assigned_to
		dataType: string
		lineageTag: 763b49dc-dba5-4d96-9811-740b5e50608f
		summarizeBy: none
		sourceColumn: dv_assigned_to

		annotation SummarizationSetBy = Automatic

	column assignment_group
		dataType: string
		lineageTag: 800bb4d1-c2b2-45e9-b6ea-d9a200550a28
		summarizeBy: none
		sourceColumn: assignment_group

		annotation SummarizationSetBy = Automatic

	column dv_assignment_group
		dataType: string
		lineageTag: 2256347c-9faa-4998-9445-cd01ae224722
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column benefits
		dataType: double
		lineageTag: 7e08b976-2141-4995-b0ff-f2df221833d6
		summarizeBy: sum
		sourceColumn: benefits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column budget_cost
		dataType: double
		lineageTag: d450d8e1-b98c-4625-a51b-a5e8653f91dc
		summarizeBy: sum
		sourceColumn: budget_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column business_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: df4e174e-43d5-4a37-81bd-67d0823aed7c
		summarizeBy: none
		sourceColumn: business_duration

		variation Variación
			isDefault
			relationship: b5461c07-61ef-4b0f-bbf4-82a086b7fb7f
			defaultHierarchy: LocalDateTable_f1842a85-eeea-413b-b42c-17a8614943b1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_business_duration
		dataType: string
		lineageTag: 21e67b42-ddc6-4d33-a7f0-0ea2a580b951
		summarizeBy: none
		sourceColumn: dv_business_duration

		annotation SummarizationSetBy = Automatic

	column business_service
		dataType: string
		lineageTag: 9f40e3ed-abf7-4e1c-91e5-b5f33397b9d7
		summarizeBy: none
		sourceColumn: business_service

		annotation SummarizationSetBy = Automatic

	column dv_business_service
		dataType: string
		lineageTag: 04822513-af48-4d95-88bf-00b29df0ca2a
		summarizeBy: none
		sourceColumn: dv_business_service

		annotation SummarizationSetBy = Automatic

	column calculation_type
		dataType: string
		lineageTag: 15a6433c-516c-4e17-9872-01cc207a2e75
		summarizeBy: none
		sourceColumn: calculation_type

		annotation SummarizationSetBy = Automatic

	column dv_calculation_type
		dataType: string
		lineageTag: 9a72bb20-f135-432e-990a-43a45a84c556
		summarizeBy: none
		sourceColumn: dv_calculation_type

		annotation SummarizationSetBy = Automatic

	column calendar_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: a380be00-091e-41b3-9300-d0674eeb77c7
		summarizeBy: none
		sourceColumn: calendar_duration

		variation Variación
			isDefault
			relationship: b6ffd6e5-8681-4999-ae88-d37c3fc44ce1
			defaultHierarchy: LocalDateTable_75db3d80-b690-4825-987c-f8c6bf58da21.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_calendar_duration
		dataType: string
		lineageTag: 41853d98-ac55-4ef6-a963-49d3d1962eea
		summarizeBy: none
		sourceColumn: dv_calendar_duration

		annotation SummarizationSetBy = Automatic

	column capex_cost
		dataType: double
		lineageTag: 3e021a7d-2990-460c-bd15-9c4ac39f424d
		summarizeBy: sum
		sourceColumn: capex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column close_notes
		dataType: string
		lineageTag: 6011e5c8-8826-48ef-aa6f-dc166f3450d5
		summarizeBy: none
		sourceColumn: close_notes

		annotation SummarizationSetBy = Automatic

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 6a3d6e88-a7e0-49c2-a0e8-d5637fce87d9
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: aba77b3a-9884-4788-884c-6ddc4178f526
			defaultHierarchy: LocalDateTable_7da8eb2e-50f8-4ec4-ba9e-beb1d395e712.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column closed_by
		dataType: string
		lineageTag: 1133fe18-650b-4d82-99c6-9233474a09c3
		summarizeBy: none
		sourceColumn: closed_by

		annotation SummarizationSetBy = Automatic

	column dv_closed_by
		dataType: string
		lineageTag: 3e136bac-5432-4717-bf3e-950fc3975739
		summarizeBy: none
		sourceColumn: dv_closed_by

		annotation SummarizationSetBy = Automatic

	column cmdb_ci
		dataType: string
		lineageTag: dd5491b0-045f-40ce-b4ac-29ffbb7bd547
		summarizeBy: none
		sourceColumn: cmdb_ci

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci
		dataType: string
		lineageTag: 5007b2c0-fe7b-4199-890f-5b25caf35efc
		summarizeBy: none
		sourceColumn: dv_cmdb_ci

		annotation SummarizationSetBy = Automatic

	column cmdb_ci_business_app
		dataType: string
		lineageTag: 4016a502-0b01-4901-8b08-132008fd6215
		summarizeBy: none
		sourceColumn: cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci_business_app
		dataType: string
		lineageTag: 60d78434-da18-430f-b0e9-23983ebd0a35
		summarizeBy: none
		sourceColumn: dv_cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column comments
		dataType: string
		lineageTag: c9e21e84-1dbe-4490-8c3d-ac0ce7416ea8
		summarizeBy: none
		sourceColumn: comments

		annotation SummarizationSetBy = Automatic

	column comments_and_work_notes
		dataType: string
		lineageTag: 4b5fc348-9f8b-4df6-af06-348eaf795429
		summarizeBy: none
		sourceColumn: comments_and_work_notes

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 2ad09abc-de42-4673-8ef6-f5677d9638e4
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column dv_company
		dataType: string
		lineageTag: 3a68a68d-14f2-457c-91f4-a4d4d6302d3b
		summarizeBy: none
		sourceColumn: dv_company

		annotation SummarizationSetBy = Automatic

	column constraint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 28cb50a3-ce2c-4fc5-b67d-9c3f007e521b
		summarizeBy: none
		sourceColumn: constraint_date

		variation Variación
			isDefault
			relationship: ec2d0590-5b20-4171-9966-4c7d6f6ffa9d
			defaultHierarchy: LocalDateTable_4adccb37-f557-4609-b583-c30cb6a9b0e5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column contact_type
		dataType: string
		lineageTag: 03942791-3151-405e-8f58-dac42cd1a1cc
		summarizeBy: none
		sourceColumn: contact_type

		annotation SummarizationSetBy = Automatic

	column dv_contact_type
		dataType: string
		lineageTag: be5a9e5d-0141-48a3-9bab-88ed77ab084f
		summarizeBy: none
		sourceColumn: dv_contact_type

		annotation SummarizationSetBy = Automatic

	column correlation_display
		dataType: string
		lineageTag: 798a1523-117b-4244-9759-d51963becb71
		summarizeBy: none
		sourceColumn: correlation_display

		annotation SummarizationSetBy = Automatic

	column correlation_id
		dataType: string
		lineageTag: a4547332-3a15-419a-8582-894eba5f2b83
		summarizeBy: none
		sourceColumn: correlation_id

		annotation SummarizationSetBy = Automatic

	column cost
		dataType: double
		lineageTag: 47e88ccf-fe8d-490d-a72c-102308ffce43
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column critical_path
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7bbdb15c-ed71-4db3-8fd8-241b95fd44f7
		summarizeBy: none
		sourceColumn: critical_path

		annotation SummarizationSetBy = Automatic

	column delivery_plan
		dataType: string
		lineageTag: 1f59aa4d-9b9f-4166-beda-22166f12da34
		summarizeBy: none
		sourceColumn: delivery_plan

		annotation SummarizationSetBy = Automatic

	column dv_delivery_plan
		dataType: string
		lineageTag: bf8cd753-8b09-4d00-a9b8-3fdc9f4d6a12
		summarizeBy: none
		sourceColumn: dv_delivery_plan

		annotation SummarizationSetBy = Automatic

	column delivery_task
		dataType: string
		lineageTag: 81755a04-0f35-4275-ad17-34512559f9fc
		summarizeBy: none
		sourceColumn: delivery_task

		annotation SummarizationSetBy = Automatic

	column dv_delivery_task
		dataType: string
		lineageTag: 12e03853-b775-40fd-a310-a144e628844f
		summarizeBy: none
		sourceColumn: dv_delivery_task

		annotation SummarizationSetBy = Automatic

	column dependency
		dataType: string
		lineageTag: f26aff3b-3b79-4521-bbbe-64424a3f778d
		summarizeBy: none
		sourceColumn: dependency

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 604871c9-bc95-44bd-aa79-e36e2727e99a
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column due_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 26ee0489-235b-4464-897c-f60cd65222bf
		summarizeBy: none
		sourceColumn: due_date

		variation Variación
			isDefault
			relationship: 75074d59-5e6b-48a0-a0ae-221deebfef32
			defaultHierarchy: LocalDateTable_81b45a57-8e14-453c-aca8-b8cbe66d72c5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 206ddd0b-8eeb-4b75-8055-af9538d15c8a
		summarizeBy: none
		sourceColumn: duration

		variation Variación
			isDefault
			relationship: ffac4c31-ed18-4486-a926-b1669632d0e9
			defaultHierarchy: LocalDateTable_d4497b19-fb7c-43cb-88d9-132d960e6f1d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_duration
		dataType: string
		lineageTag: 2e4df960-1b17-4f55-849b-44a93f87ddc6
		summarizeBy: none
		sourceColumn: dv_duration

		annotation SummarizationSetBy = Automatic

	column effort
		dataType: dateTime
		formatString: General Date
		lineageTag: 472d1c6d-c2ce-4c92-9ffa-9d25c043138b
		summarizeBy: none
		sourceColumn: effort

		variation Variación
			isDefault
			relationship: e5666633-70e7-4bed-a49e-f56e46e51fd1
			defaultHierarchy: LocalDateTable_0ac3d876-81bd-446e-ad08-965633b0fcc1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_effort
		dataType: string
		lineageTag: 0bf5521d-c2e3-4bab-b96c-37929ba6983d
		summarizeBy: none
		sourceColumn: dv_effort

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 5c2fe3d0-341d-49ac-9e8c-e9f99fdf1ef6
		summarizeBy: none
		sourceColumn: end_date

		variation Variación
			isDefault
			relationship: 9d93c07e-3d6e-4407-b1a7-449913d5e36e
			defaultHierarchy: LocalDateTable_2b5881be-a5ec-41ee-b282-eb7b5915f803.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column end_date_derived_from
		dataType: string
		lineageTag: 4e75c123-b2f1-4d27-9575-e124c5021f51
		summarizeBy: none
		sourceColumn: end_date_derived_from

		annotation SummarizationSetBy = Automatic

	column dv_end_date_derived_from
		dataType: string
		lineageTag: 81662386-da8d-4138-9721-bafa9ffa81ce
		summarizeBy: none
		sourceColumn: dv_end_date_derived_from

		annotation SummarizationSetBy = Automatic

	column escalation
		dataType: int64
		formatString: 0
		lineageTag: c2bf16c3-b4bf-4ed1-ad90-f4ee07b61afa
		summarizeBy: sum
		sourceColumn: escalation

		annotation SummarizationSetBy = Automatic

	column dv_escalation
		dataType: string
		lineageTag: 72a8632d-79bb-4ca5-9bda-4c548b2fae8c
		summarizeBy: none
		sourceColumn: dv_escalation

		annotation SummarizationSetBy = Automatic

	column expected_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 454fb8ff-5676-48a9-a847-d3bafeaee019
		summarizeBy: none
		sourceColumn: expected_start

		variation Variación
			isDefault
			relationship: 9eaf22a9-6abd-4340-8e91-ae90334f7de7
			defaultHierarchy: LocalDateTable_26a80d65-f18d-4149-92d4-abf357230374.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column follow_up
		dataType: dateTime
		formatString: General Date
		lineageTag: d2c0765a-2372-4eea-9055-4f868638f9f4
		summarizeBy: none
		sourceColumn: follow_up

		variation Variación
			isDefault
			relationship: 69b29370-d209-47b8-b1ea-af502f7ab466
			defaultHierarchy: LocalDateTable_a95cb3c4-e3e6-47d7-a78f-30cba6a8972f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column group_list
		dataType: string
		lineageTag: 564fcc5d-bb1f-4719-9a3c-07327575e150
		summarizeBy: none
		sourceColumn: group_list

		annotation SummarizationSetBy = Automatic

	column has_conflict
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6cc73617-7e06-4700-8ac7-3453c92ee123
		summarizeBy: none
		sourceColumn: has_conflict

		annotation SummarizationSetBy = Automatic

	column html_description
		dataType: string
		lineageTag: 74ae123e-e271-45bc-bfa8-e2e89e6d42f1
		summarizeBy: none
		sourceColumn: html_description

		annotation SummarizationSetBy = Automatic

	column impact
		dataType: int64
		formatString: 0
		lineageTag: b3db63ca-790b-4a22-b698-4d0c883ef6c0
		summarizeBy: sum
		sourceColumn: impact

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: aa5a0008-e25f-4cc2-86de-fdd01190deec
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column key_milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1f904752-0697-42b8-bf70-41e7d950a86a
		summarizeBy: none
		sourceColumn: key_milestone

		annotation SummarizationSetBy = Automatic

	column knowledge
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4dd71501-4c15-4793-884c-aea397b4eecf
		summarizeBy: none
		sourceColumn: knowledge

		annotation SummarizationSetBy = Automatic

	column level
		dataType: int64
		formatString: 0
		lineageTag: e423d661-de60-4dba-991e-56cea77705f0
		summarizeBy: sum
		sourceColumn: level

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 644116ee-04ff-4f46-b7fd-900f1b46ff84
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column dv_location
		dataType: string
		lineageTag: 62519cc8-9a28-4f60-9bcf-c944222ac98f
		summarizeBy: none
		sourceColumn: dv_location

		annotation SummarizationSetBy = Automatic

	column made_sla
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ceb2930e-1bf1-46a1-8cbc-7c394a1dba80
		summarizeBy: none
		sourceColumn: made_sla

		annotation SummarizationSetBy = Automatic

	column milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 22c79372-3deb-4fc4-8d7d-de56719686e2
		summarizeBy: none
		sourceColumn: milestone

		annotation SummarizationSetBy = Automatic

	column mpp_task_id
		dataType: int64
		formatString: 0
		lineageTag: f09e4f1d-0c87-4c3c-aa0e-d823aab944c6
		summarizeBy: sum
		sourceColumn: mpp_task_id

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: 31921c5f-6b53-441a-8025-cde45a0458cd
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: ed5a12d3-215b-47d9-b574-3af67cc416d0
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: 8a90b891-f8cc-4fc0-ad51-877cdf2fd50c
			defaultHierarchy: LocalDateTable_e527cad6-c33b-4f92-b75f-45e5a17ccb1d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column opened_by
		dataType: string
		lineageTag: 286eacc3-5523-49d0-b9a1-24eceaa40e94
		summarizeBy: none
		sourceColumn: opened_by

		annotation SummarizationSetBy = Automatic

	column dv_opened_by
		dataType: string
		lineageTag: 2ef348d8-1b23-4a89-9ad3-894a26311e59
		summarizeBy: none
		sourceColumn: dv_opened_by

		annotation SummarizationSetBy = Automatic

	column opex_cost
		dataType: double
		lineageTag: 618feb90-d547-415b-8df8-5d2ae494b377
		summarizeBy: sum
		sourceColumn: opex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order
		dataType: int64
		formatString: 0
		lineageTag: 1f230f94-edae-4574-a43d-64150bcbac36
		summarizeBy: sum
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	column orig_sys_id
		dataType: string
		lineageTag: 4ea1f34e-5239-492f-8529-e769e9512e7b
		summarizeBy: none
		sourceColumn: orig_sys_id

		annotation SummarizationSetBy = Automatic

	column dv_orig_sys_id
		dataType: string
		lineageTag: f7907cdd-0b71-44d5-8d17-0b5264e4d0f4
		summarizeBy: none
		sourceColumn: dv_orig_sys_id

		annotation SummarizationSetBy = Automatic

	column orig_top_task_id
		dataType: string
		lineageTag: 78609e68-e445-45ab-bcdd-60d65b74df80
		summarizeBy: none
		sourceColumn: orig_top_task_id

		annotation SummarizationSetBy = Automatic

	column dv_orig_top_task_id
		dataType: string
		lineageTag: 0ac81630-4dd5-41e2-8afc-e5995a7bba9d
		summarizeBy: none
		sourceColumn: dv_orig_top_task_id

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: 3ee72240-8df6-4532-afe7-3a24684c3238
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: 1062a530-eaa2-490d-8879-9d5853e269eb
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column percent_complete
		dataType: double
		lineageTag: 73b26ef1-202f-48cb-a34b-ec887c1e591d
		summarizeBy: sum
		sourceColumn: percent_complete

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column phase_type
		dataType: string
		lineageTag: 48c022cb-5f82-4b37-849f-bcf95b5ce37b
		summarizeBy: none
		sourceColumn: phase_type

		annotation SummarizationSetBy = Automatic

	column dv_phase_type
		dataType: string
		lineageTag: 21b730ec-6273-49f1-b4ce-e9491830ba46
		summarizeBy: none
		sourceColumn: dv_phase_type

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: int64
		formatString: 0
		lineageTag: 5db3e06a-b2d8-465b-baaa-38cf0dbef6bd
		summarizeBy: sum
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: 3c20392f-4dc2-47d0-a133-755a87a5d3f0
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: 619824e8-b2cb-4a9f-9cf6-48de6c21cd69
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column dv_product
		dataType: string
		lineageTag: 3ba09c8d-a7a9-4c68-b880-492f05844959
		summarizeBy: none
		sourceColumn: dv_product

		annotation SummarizationSetBy = Automatic

	column reassignment_count
		dataType: int64
		formatString: 0
		lineageTag: c113f310-9e60-47a1-b64f-bfdfe91ac3ac
		summarizeBy: sum
		sourceColumn: reassignment_count

		annotation SummarizationSetBy = Automatic

	column rejection_goto
		dataType: string
		lineageTag: 0eb5abf6-60df-4e73-b86d-c66292efc71a
		summarizeBy: none
		sourceColumn: rejection_goto

		annotation SummarizationSetBy = Automatic

	column dv_rejection_goto
		dataType: string
		lineageTag: 31f646dd-c3f4-4915-968f-99b27f44f2e6
		summarizeBy: none
		sourceColumn: dv_rejection_goto

		annotation SummarizationSetBy = Automatic

	column relation_applied
		dataType: string
		lineageTag: e17b9279-984a-4fc6-a46a-b0f593e75326
		summarizeBy: none
		sourceColumn: relation_applied

		annotation SummarizationSetBy = Automatic

	column dv_relation_applied
		dataType: string
		lineageTag: e636771e-1427-4087-bdb5-0edd7983473a
		summarizeBy: none
		sourceColumn: dv_relation_applied

		annotation SummarizationSetBy = Automatic

	column remaining_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 8f93a119-1301-49ba-afaf-7dfe0979cf93
		summarizeBy: none
		sourceColumn: remaining_duration

		variation Variación
			isDefault
			relationship: 74d2b937-ffbf-4038-ab0b-f039044599e3
			defaultHierarchy: LocalDateTable_48ffef4d-7ccc-4952-b2b8-56de8885e055.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_remaining_duration
		dataType: string
		lineageTag: 8aaef9b3-2b87-41fc-a72c-a68b8763f53f
		summarizeBy: none
		sourceColumn: dv_remaining_duration

		annotation SummarizationSetBy = Automatic

	column remaining_effort
		dataType: dateTime
		formatString: General Date
		lineageTag: 047bdd4c-8b63-43aa-84f7-333879bcbbb9
		summarizeBy: none
		sourceColumn: remaining_effort

		variation Variación
			isDefault
			relationship: 65309796-95b9-4b54-beef-4e1de754f028
			defaultHierarchy: LocalDateTable_5f4a0f48-92b9-4a2a-827d-303ee57426dc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_remaining_effort
		dataType: string
		lineageTag: bb6c2c37-3256-4554-822e-7177c1b88c3d
		summarizeBy: none
		sourceColumn: dv_remaining_effort

		annotation SummarizationSetBy = Automatic

	column resource_allocated_cost
		dataType: double
		lineageTag: 46b05ee1-4d46-44bc-a289-a52d803a75bb
		summarizeBy: sum
		sourceColumn: resource_allocated_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column resource_planned_cost
		dataType: double
		lineageTag: 11d77b72-0930-4612-9e47-fb07a35eefaa
		summarizeBy: sum
		sourceColumn: resource_planned_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rollup
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 709a52f7-a40b-4e8b-9452-614126cf5f26
		summarizeBy: none
		sourceColumn: rollup

		annotation SummarizationSetBy = Automatic

	column route_reason
		dataType: int64
		formatString: 0
		lineageTag: a90bee08-2311-4779-8735-572d336ec6b8
		summarizeBy: sum
		sourceColumn: route_reason

		annotation SummarizationSetBy = Automatic

	column dv_route_reason
		dataType: string
		lineageTag: b1491404-4acf-418d-9582-80abd39c038e
		summarizeBy: none
		sourceColumn: dv_route_reason

		annotation SummarizationSetBy = Automatic

	column schedule_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: e6eb612b-0bdb-4d28-9665-8824a8bb0c55
		summarizeBy: none
		sourceColumn: schedule_end_date

		variation Variación
			isDefault
			relationship: 4e50fb69-d766-4829-9107-c2a4502138ba
			defaultHierarchy: LocalDateTable_df6604cc-41d6-45d5-845f-4bc0c8021732.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column schedule_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b4b3b167-ee5f-4f64-a021-e1eb9be00ba1
		summarizeBy: none
		sourceColumn: schedule_start_date

		variation Variación
			isDefault
			relationship: 30f05fed-0681-4956-8fbb-c576369ab4a1
			defaultHierarchy: LocalDateTable_85eeeac7-e92b-43ab-86be-1990d23a7e9c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column service_offering
		dataType: string
		lineageTag: bfd4f8c0-24b2-4464-9106-6a41055774bd
		summarizeBy: none
		sourceColumn: service_offering

		annotation SummarizationSetBy = Automatic

	column dv_service_offering
		dataType: string
		lineageTag: 0488658e-a931-4bcc-ab3e-3cc36ac46819
		summarizeBy: none
		sourceColumn: dv_service_offering

		annotation SummarizationSetBy = Automatic

	column shadow
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ebff4206-567a-4f2f-874e-dfa52bc0a543
		summarizeBy: none
		sourceColumn: shadow

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: 095b5ba9-8e01-4f06-a47f-3b9e47072ae8
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column skills
		dataType: string
		lineageTag: a209395a-3d7a-48f3-88a2-54bf94f32394
		summarizeBy: none
		sourceColumn: skills

		annotation SummarizationSetBy = Automatic

	column sla_due
		dataType: dateTime
		formatString: General Date
		lineageTag: 758d4f01-9952-41fc-8093-4435ba496d90
		summarizeBy: none
		sourceColumn: sla_due

		variation Variación
			isDefault
			relationship: 804195b1-2e7b-42a5-aeda-42e77ada51b4
			defaultHierarchy: LocalDateTable_3411e8cc-14e2-4574-92c2-44de6d6b93cc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: bdf28723-06e7-47d9-81ba-273efe56bef9
		summarizeBy: none
		sourceColumn: start_date

		variation Variación
			isDefault
			relationship: 81796242-d658-47d2-8309-55fcd53b5879
			defaultHierarchy: LocalDateTable_544f61a0-0641-43bc-b854-a6193e304ef6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column start_date_derived_from
		dataType: string
		lineageTag: 3e89611b-cc59-443e-ac54-c748e90346c2
		summarizeBy: none
		sourceColumn: start_date_derived_from

		annotation SummarizationSetBy = Automatic

	column dv_start_date_derived_from
		dataType: string
		lineageTag: 31511049-f99f-448f-8c13-2c06597346bd
		summarizeBy: none
		sourceColumn: dv_start_date_derived_from

		annotation SummarizationSetBy = Automatic

	column state
		dataType: int64
		formatString: 0
		lineageTag: bc54daa6-e77f-496b-8c29-cf7c9b80363f
		summarizeBy: sum
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: 9059b477-ea18-4294-bd0d-975e308a9d62
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 8beb7775-d045-4876-9fef-fbf6aef9ab74
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column dv_status
		dataType: string
		lineageTag: 4b9c4f2f-e76b-49a9-9e6e-f9a16ccb553a
		summarizeBy: none
		sourceColumn: dv_status

		annotation SummarizationSetBy = Automatic

	column sub_tree_root
		dataType: string
		lineageTag: 7c16d256-dbe2-4d21-bb49-b483276e6526
		summarizeBy: none
		sourceColumn: sub_tree_root

		annotation SummarizationSetBy = Automatic

	column dv_sub_tree_root
		dataType: string
		lineageTag: ab23fc5a-aa52-4f74-9364-fef0dee786b3
		summarizeBy: none
		sourceColumn: dv_sub_tree_root

		annotation SummarizationSetBy = Automatic

	column sys_class_name
		dataType: string
		lineageTag: 386fd675-4352-4024-97a3-e670a570a54e
		summarizeBy: none
		sourceColumn: sys_class_name

		annotation SummarizationSetBy = Automatic

	column dv_sys_class_name
		dataType: string
		lineageTag: 3013e778-1b3c-4ac7-af91-bab49eb2d5a5
		summarizeBy: none
		sourceColumn: dv_sys_class_name

		annotation SummarizationSetBy = Automatic

	column sys_created_by
		dataType: string
		lineageTag: 71537e15-f57e-438a-97af-8cfa067bf484
		summarizeBy: none
		sourceColumn: sys_created_by

		annotation SummarizationSetBy = Automatic

	column sys_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: dfb782e2-c936-4966-8e74-83cc78b01e2a
		summarizeBy: none
		sourceColumn: sys_created_on

		variation Variación
			isDefault
			relationship: d1a8529c-162d-4875-b403-8db1b2ad11f9
			defaultHierarchy: LocalDateTable_d4499adf-d161-4fb9-a369-145bc335c1d8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column sys_domain
		dataType: string
		lineageTag: f9178ebf-5551-410a-bcad-453bbbb7ab61
		summarizeBy: none
		sourceColumn: sys_domain

		annotation SummarizationSetBy = Automatic

	column sys_domain_path
		dataType: string
		lineageTag: 1bb3ce14-30e7-492f-87df-486ac5358c76
		summarizeBy: none
		sourceColumn: sys_domain_path

		annotation SummarizationSetBy = Automatic

	column 'mejora.sys_id'
		dataType: string
		lineageTag: cc52eb10-6d98-4ec1-860a-81ddf63b358e
		summarizeBy: none
		sourceColumn: mejora.sys_id

		annotation SummarizationSetBy = Automatic

	column sys_mod_count
		dataType: int64
		formatString: 0
		lineageTag: 2e231189-bf73-4e4a-92d9-f71b2cf7172d
		summarizeBy: sum
		sourceColumn: sys_mod_count

		annotation SummarizationSetBy = Automatic

	column sys_tags
		dataType: string
		lineageTag: 815a913b-b6f2-40db-b3e7-08f8cdf70432
		summarizeBy: none
		sourceColumn: sys_tags

		annotation SummarizationSetBy = Automatic

	column sys_updated_by
		dataType: string
		lineageTag: f95937a7-14b7-4421-bf3c-b39223df7b2e
		summarizeBy: none
		sourceColumn: sys_updated_by

		annotation SummarizationSetBy = Automatic

	column sys_updated_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 96f97b72-6d3b-48c3-9f2a-5f046bed9177
		summarizeBy: none
		sourceColumn: sys_updated_on

		variation Variación
			isDefault
			relationship: 49bfd054-ce9b-4f33-8b35-2ec1ab5d8bae
			defaultHierarchy: LocalDateTable_a8578e71-f2ef-417f-be19-6dc712a0c637.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column task
		dataType: string
		lineageTag: 5a317b5e-31c8-49ff-9c21-b3e45c4c1510
		summarizeBy: none
		sourceColumn: task

		annotation SummarizationSetBy = Automatic

	column task_effective_number
		dataType: string
		lineageTag: 34607459-5e1a-49c0-a892-f779b0247f00
		summarizeBy: none
		sourceColumn: task_effective_number

		annotation SummarizationSetBy = Automatic

	column task_for
		dataType: string
		lineageTag: 4e32f170-efd2-4593-acb6-39489317f74e
		summarizeBy: none
		sourceColumn: task_for

		annotation SummarizationSetBy = Automatic

	column dv_task_for
		dataType: string
		lineageTag: 29b26a8e-1f5a-47c3-b29d-a8519b1a2ef4
		summarizeBy: none
		sourceColumn: dv_task_for

		annotation SummarizationSetBy = Automatic

	column time_card_at_top_task
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7a6ac9d5-3d71-4a19-ba53-b03b3ac45bdd
		summarizeBy: none
		sourceColumn: time_card_at_top_task

		annotation SummarizationSetBy = Automatic

	column time_constraint
		dataType: string
		lineageTag: aea0e7b1-37cd-4cda-934c-4c848164c207
		summarizeBy: none
		sourceColumn: time_constraint

		annotation SummarizationSetBy = Automatic

	column dv_time_constraint
		dataType: string
		lineageTag: 49d381c8-dca4-4d24-bf16-a3161bb6f3fa
		summarizeBy: none
		sourceColumn: dv_time_constraint

		annotation SummarizationSetBy = Automatic

	column time_worked
		dataType: dateTime
		formatString: General Date
		lineageTag: 9023eb88-87a0-4164-ba41-9a499e8e6955
		summarizeBy: none
		sourceColumn: time_worked

		variation Variación
			isDefault
			relationship: b02e7814-31a5-4d35-99e6-5d65271f36d1
			defaultHierarchy: LocalDateTable_5ae2dc0f-336b-40c1-9d0a-cd20f9598884.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_time_worked
		dataType: string
		lineageTag: ec343d97-0565-4f92-be10-d5c4f144c9eb
		summarizeBy: none
		sourceColumn: dv_time_worked

		annotation SummarizationSetBy = Automatic

	column top_portfolio
		dataType: string
		lineageTag: 223fbf7c-111c-41d6-9f1a-6df7b7531cce
		summarizeBy: none
		sourceColumn: top_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_top_portfolio
		dataType: string
		lineageTag: cd35742f-6e80-41cc-ad2f-73a237bec633
		summarizeBy: none
		sourceColumn: dv_top_portfolio

		annotation SummarizationSetBy = Automatic

	column top_program
		dataType: string
		lineageTag: 9fb7cd09-c198-423f-b470-4d1493821dc0
		summarizeBy: none
		sourceColumn: top_program

		annotation SummarizationSetBy = Automatic

	column dv_top_program
		dataType: string
		lineageTag: e36e9091-90cf-43ac-aebf-faaa6c3332b1
		summarizeBy: none
		sourceColumn: dv_top_program

		annotation SummarizationSetBy = Automatic

	column top_task
		dataType: string
		lineageTag: ae652538-b526-4bd3-8475-edb27bec610a
		summarizeBy: none
		sourceColumn: top_task

		annotation SummarizationSetBy = Automatic

	column dv_top_task
		dataType: string
		lineageTag: 0ed51cd1-b899-4dd9-acbc-ab9543efc92d
		summarizeBy: none
		sourceColumn: dv_top_task

		annotation SummarizationSetBy = Automatic

	column u_acciona_priority
		dataType: int64
		formatString: 0
		lineageTag: fba6a997-6bd1-451d-a92f-f70c9b9687af
		summarizeBy: sum
		sourceColumn: u_acciona_priority

		annotation SummarizationSetBy = Automatic

	column u_business_application
		dataType: string
		lineageTag: 5cdb8482-d6c0-400e-81b8-8ea6837a8b47
		summarizeBy: none
		sourceColumn: u_business_application

		annotation SummarizationSetBy = Automatic

	column dv_u_business_application
		dataType: string
		lineageTag: 58b45bbf-7499-4ea1-8327-4a2db7e70be5
		summarizeBy: none
		sourceColumn: dv_u_business_application

		annotation SummarizationSetBy = Automatic

	column u_business_line
		dataType: string
		lineageTag: d7510d94-3a74-4676-9cc5-87ff4a66651d
		summarizeBy: none
		sourceColumn: u_business_line

		annotation SummarizationSetBy = Automatic

	column dv_u_business_line
		dataType: string
		lineageTag: f82c6f2a-a2cb-40db-bdf7-b41de116b36d
		summarizeBy: none
		sourceColumn: dv_u_business_line

		annotation SummarizationSetBy = Automatic

	column u_catalog
		dataType: string
		lineageTag: 41caf8a1-27fb-412d-882d-e1853630e04b
		summarizeBy: none
		sourceColumn: u_catalog

		annotation SummarizationSetBy = Automatic

	column dv_u_catalog
		dataType: string
		lineageTag: 363e7223-b0f8-4a61-ba61-6b48e4c6918b
		summarizeBy: none
		sourceColumn: dv_u_catalog

		annotation SummarizationSetBy = Automatic

	column u_department
		dataType: string
		lineageTag: 55748a9d-44f6-4634-9156-90c1f9398c52
		summarizeBy: none
		sourceColumn: u_department

		annotation SummarizationSetBy = Automatic

	column dv_u_department
		dataType: string
		lineageTag: 0d051d0a-b082-4495-b580-222bf0fcae6f
		summarizeBy: none
		sourceColumn: dv_u_department

		annotation SummarizationSetBy = Automatic

	column u_execution_type
		dataType: string
		lineageTag: df62e960-b6a6-4df7-acbc-06c8b9430f8f
		summarizeBy: none
		sourceColumn: u_execution_type

		annotation SummarizationSetBy = Automatic

	column dv_u_execution_type
		dataType: string
		lineageTag: e184edd0-5f1c-4bef-9ef2-4c2918710dcc
		summarizeBy: none
		sourceColumn: dv_u_execution_type

		annotation SummarizationSetBy = Automatic

	column u_external_vendor
		dataType: string
		lineageTag: 71a9881e-6699-4db9-9131-35d2f7cdc8ef
		summarizeBy: none
		sourceColumn: u_external_vendor

		annotation SummarizationSetBy = Automatic

	column dv_u_external_vendor
		dataType: string
		lineageTag: b1911bc3-a61c-4341-8083-43a39126f630
		summarizeBy: none
		sourceColumn: dv_u_external_vendor

		annotation SummarizationSetBy = Automatic

	column u_metal
		dataType: string
		lineageTag: 79629f42-867d-4d5b-b48e-6b417417f05f
		summarizeBy: none
		sourceColumn: u_metal

		annotation SummarizationSetBy = Automatic

	column dv_u_metal
		dataType: string
		lineageTag: 56227732-3092-412d-9c67-a7d161b86218
		summarizeBy: none
		sourceColumn: dv_u_metal

		annotation SummarizationSetBy = Automatic

	column u_phone
		dataType: string
		lineageTag: a683271b-5025-4817-a33a-9923127d6642
		summarizeBy: none
		sourceColumn: u_phone

		annotation SummarizationSetBy = Automatic

	column u_previous_groups
		dataType: string
		lineageTag: ec6e7c4f-8278-453f-9052-14d4f568ce8f
		summarizeBy: none
		sourceColumn: u_previous_groups

		annotation SummarizationSetBy = Automatic

	column u_progress
		dataType: double
		lineageTag: 19c67a69-1cc0-46e2-8e8c-b92f1c6300d2
		summarizeBy: sum
		sourceColumn: u_progress

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_ref_country
		dataType: string
		lineageTag: 8b5851de-4eea-4cdf-a937-29ec2df51da1
		summarizeBy: none
		sourceColumn: u_ref_country

		annotation SummarizationSetBy = Automatic

	column dv_u_ref_country
		dataType: string
		lineageTag: 7ac776fe-46cb-497c-b1a8-e856c7f5b14c
		summarizeBy: none
		sourceColumn: dv_u_ref_country

		annotation SummarizationSetBy = Automatic

	column u_responded
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 715fd21b-8827-4101-845d-8dee8eace61f
		summarizeBy: none
		sourceColumn: u_responded

		annotation SummarizationSetBy = Automatic

	column u_size
		dataType: string
		lineageTag: cfd83536-67fa-49e6-93ba-92ea5310d52f
		summarizeBy: none
		sourceColumn: u_size

		annotation SummarizationSetBy = Automatic

	column dv_u_size
		dataType: string
		lineageTag: 33acff03-51be-40f8-baa6-53672b754a00
		summarizeBy: none
		sourceColumn: dv_u_size

		annotation SummarizationSetBy = Automatic

	column u_state_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1123c62f-f6b0-4142-b5ef-096211ad5f3c
		summarizeBy: none
		sourceColumn: u_state_date

		variation Variación
			isDefault
			relationship: 97f3275a-c40c-4eda-995d-4fefefdbaaa7
			defaultHierarchy: LocalDateTable_c2a2365d-5885-4d62-ae57-823ede8b2aa3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column universal_request
		dataType: string
		lineageTag: 0a2a077e-fd80-48cb-be41-fd5c28f03c3f
		summarizeBy: none
		sourceColumn: universal_request

		annotation SummarizationSetBy = Automatic

	column dv_universal_request
		dataType: string
		lineageTag: 28362eb2-6c88-4f37-9156-25a667a70612
		summarizeBy: none
		sourceColumn: dv_universal_request

		annotation SummarizationSetBy = Automatic

	column upon_approval
		dataType: string
		lineageTag: 13f2d579-d1bb-4205-bb9b-e28bc39d59dc
		summarizeBy: none
		sourceColumn: upon_approval

		annotation SummarizationSetBy = Automatic

	column dv_upon_approval
		dataType: string
		lineageTag: 2564586c-d21d-4f84-96d2-d794b3c06545
		summarizeBy: none
		sourceColumn: dv_upon_approval

		annotation SummarizationSetBy = Automatic

	column upon_reject
		dataType: string
		lineageTag: af1c89d5-1f20-4517-a067-77e65586a59e
		summarizeBy: none
		sourceColumn: upon_reject

		annotation SummarizationSetBy = Automatic

	column dv_upon_reject
		dataType: string
		lineageTag: 9bf43430-ec22-452f-9e0c-7b126f200b5c
		summarizeBy: none
		sourceColumn: dv_upon_reject

		annotation SummarizationSetBy = Automatic

	column urgency
		dataType: int64
		formatString: 0
		lineageTag: 5b73b5dd-656c-49bf-be38-973e3a807bc8
		summarizeBy: sum
		sourceColumn: urgency

		annotation SummarizationSetBy = Automatic

	column dv_urgency
		dataType: string
		lineageTag: e469ffe0-ad51-4dfe-a102-1206118f7e25
		summarizeBy: none
		sourceColumn: dv_urgency

		annotation SummarizationSetBy = Automatic

	column user_input
		dataType: string
		lineageTag: be267f4a-54f1-4552-bdab-3dc4de9b9962
		summarizeBy: none
		sourceColumn: user_input

		annotation SummarizationSetBy = Automatic

	column variables
		dataType: string
		lineageTag: d9b0cf4c-96c1-4294-8c54-11cbc74f0daf
		summarizeBy: none
		sourceColumn: variables

		annotation SummarizationSetBy = Automatic

	column version
		dataType: int64
		formatString: 0
		lineageTag: e4c05a05-cf9f-4395-88eb-61902e105f88
		summarizeBy: sum
		sourceColumn: version

		annotation SummarizationSetBy = Automatic

	column watch_list
		dataType: string
		lineageTag: 312a8c9a-ad56-471e-91ff-6194d1bd90ac
		summarizeBy: none
		sourceColumn: watch_list

		annotation SummarizationSetBy = Automatic

	column wbs
		dataType: string
		lineageTag: b082fe51-c816-4928-954b-4f03014997e2
		summarizeBy: none
		sourceColumn: wbs

		annotation SummarizationSetBy = Automatic

	column wbs_order
		dataType: int64
		formatString: 0
		lineageTag: a9627149-76a8-4a66-a90d-80441d6cc04e
		summarizeBy: sum
		sourceColumn: wbs_order

		annotation SummarizationSetBy = Automatic

	column wf_activity
		dataType: string
		lineageTag: ecd8e25c-e33a-4755-b4bd-e64f458e2c80
		summarizeBy: none
		sourceColumn: wf_activity

		annotation SummarizationSetBy = Automatic

	column dv_wf_activity
		dataType: string
		lineageTag: 3cc9525d-d049-4576-aa1e-347911b24ca7
		summarizeBy: none
		sourceColumn: dv_wf_activity

		annotation SummarizationSetBy = Automatic

	column work_cost
		dataType: double
		lineageTag: df605bd8-5be0-418a-b932-88413f9a9a1e
		summarizeBy: sum
		sourceColumn: work_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column work_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 5c8943be-bf7e-466c-9914-f9ac60b4ae09
		summarizeBy: none
		sourceColumn: work_duration

		variation Variación
			isDefault
			relationship: 8848286a-88e3-4116-a7bd-38413d095a4c
			defaultHierarchy: LocalDateTable_e857815b-0651-41b5-bdb2-04bc6ea1c73c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_work_duration
		dataType: string
		lineageTag: c1756ecc-5fb5-47da-8646-3d2696ff8466
		summarizeBy: none
		sourceColumn: dv_work_duration

		annotation SummarizationSetBy = Automatic

	column work_effort
		dataType: dateTime
		formatString: General Date
		lineageTag: d4db5dbe-7b23-427c-a3d0-0ac41da388f3
		summarizeBy: none
		sourceColumn: work_effort

		variation Variación
			isDefault
			relationship: 3f0ad287-4f36-43fc-8b91-7b5f5e9c7b5e
			defaultHierarchy: LocalDateTable_1bbf5aa0-d7d0-41ed-bae9-e21739ee6d7e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_work_effort
		dataType: string
		lineageTag: 0456252e-eca7-4855-a72c-b934ed3ebd2d
		summarizeBy: none
		sourceColumn: dv_work_effort

		annotation SummarizationSetBy = Automatic

	column work_end
		dataType: dateTime
		formatString: General Date
		lineageTag: 7df0e789-8d25-4ff1-9fa9-8fa4bfc64cee
		summarizeBy: none
		sourceColumn: work_end

		variation Variación
			isDefault
			relationship: 7d3545ab-f975-4f94-9f08-3d17e079e949
			defaultHierarchy: LocalDateTable_60f42c05-7c06-402a-9489-4c4415568351.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column work_notes
		dataType: string
		lineageTag: 6f8077f6-c93d-4f07-b341-1e137c2aff0f
		summarizeBy: none
		sourceColumn: work_notes

		annotation SummarizationSetBy = Automatic

	column work_notes_list
		dataType: string
		lineageTag: 6d97027b-7852-4573-b591-184cb68973e4
		summarizeBy: none
		sourceColumn: work_notes_list

		annotation SummarizationSetBy = Automatic

	column work_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 653c57f3-b4bb-408a-a924-cc2e9323e1b3
		summarizeBy: none
		sourceColumn: work_start

		variation Variación
			isDefault
			relationship: 0b289c63-5bb1-410c-a97a-8fd06a1c5ce6
			defaultHierarchy: LocalDateTable_d035497b-1806-44cc-887b-d530c4607111.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column UnionConDemanda
		dataType: string
		lineageTag: 7bf78dcf-989c-4db4-b1c5-c56a929b1dd3
		summarizeBy: none
		sourceColumn: UnionConDemanda

		annotation SummarizationSetBy = Automatic

	partition 'SERV_NOW_EN V_rm_enhancement Enlazado_a_Completa' = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("QECCDWH.ACCIONA.INT:60001"),
				    DWH = Origen{[Name="DWH"]}[Data],
				    SERV_NOW_EN_V_rm_enhancement = DWH{[Schema="SERV_NOW_EN",Item="V_rm_enhancement"]}[Data],
				    #"Consultas combinadas" = Table.NestedJoin(SERV_NOW_EN_V_rm_enhancement, {"sys_id"}, Demandas, {"related_records"}, "Demandas", JoinKind.LeftOuter),
				    #"Se expandió Demandas" = Table.ExpandTableColumn(#"Consultas combinadas", "Demandas", {"sys_id"}, {"Demandas.sys_id"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Se expandió Demandas",{{"sys_id", "mejora.sys_id"}, {"Demandas.sys_id", "UnionConDemanda"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

