table 'SERV_NOW_EN V_pm_project_task_Evolutivos'
	lineageTag: ab2a75e9-ec29-493a-bd42-8aa96db035ca

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ba9d0cda-304b-4130-aeed-3168121a4b9e
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column activity_due
		dataType: dateTime
		formatString: General Date
		lineageTag: 7e78b2ea-877b-4d27-ba22-2280a7b7c63b
		summarizeBy: none
		sourceColumn: activity_due

		variation Variación
			isDefault
			relationship: e395cd10-678e-4c8e-baca-9efb61fc9742
			defaultHierarchy: LocalDateTable_5b17a8a3-4b85-49bf-b4ed-525f2e29890f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column actual_benefits
		dataType: double
		lineageTag: cea42bb3-5088-4098-ac06-5183a5255e0c
		summarizeBy: sum
		sourceColumn: actual_benefits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column additional_assignee_list
		dataType: string
		lineageTag: eeeaf7ac-e9e2-4fdf-b8df-857bba910a1a
		summarizeBy: none
		sourceColumn: additional_assignee_list

		annotation SummarizationSetBy = Automatic

	column agile_rollup_dates
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9668e197-6813-40cc-80a0-fdc026542721
		summarizeBy: none
		sourceColumn: agile_rollup_dates

		annotation SummarizationSetBy = Automatic

	column allow_dates_outside_schedule
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a4a3835e-6502-47bd-a1a8-79a5a81cff2e
		summarizeBy: none
		sourceColumn: allow_dates_outside_schedule

		annotation SummarizationSetBy = Automatic

	column approval
		dataType: string
		lineageTag: 68e5c6b4-cd97-403f-848c-e89a591dc610
		summarizeBy: none
		sourceColumn: approval

		annotation SummarizationSetBy = Automatic

	column dv_approval
		dataType: string
		lineageTag: ecfcc0c4-ddb4-461c-bf5b-68c296059fd3
		summarizeBy: none
		sourceColumn: dv_approval

		annotation SummarizationSetBy = Automatic

	column approval_history
		dataType: string
		lineageTag: e83d8683-bb9b-4d0f-8993-bf0fe27b3bb4
		summarizeBy: none
		sourceColumn: approval_history

		annotation SummarizationSetBy = Automatic

	column approval_set
		dataType: dateTime
		formatString: General Date
		lineageTag: bc7df449-7449-48b0-ae1e-82e1acdc42ac
		summarizeBy: none
		sourceColumn: approval_set

		variation Variación
			isDefault
			relationship: 41a70510-b113-41e2-933d-d8261b82a27a
			defaultHierarchy: LocalDateTable_d79234a1-e834-46ba-ad10-5c0571e75aa3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column assigned_to
		dataType: string
		lineageTag: 371a37de-51ec-4347-affa-6ea04eac1a6a
		summarizeBy: none
		sourceColumn: assigned_to

		annotation SummarizationSetBy = Automatic

	column dv_assigned_to
		dataType: string
		lineageTag: 46676804-06f9-4c03-8325-bfdf8590bf99
		summarizeBy: none
		sourceColumn: dv_assigned_to

		annotation SummarizationSetBy = Automatic

	column assignment_group
		dataType: string
		lineageTag: bd3ce493-3465-4e58-ab4d-a04de52b6b7c
		summarizeBy: none
		sourceColumn: assignment_group

		annotation SummarizationSetBy = Automatic

	column dv_assignment_group
		dataType: string
		lineageTag: a2a6f183-6655-4abe-aefc-6515267f2dc3
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column benefits
		dataType: double
		lineageTag: 1a277506-bbfe-4d9d-921d-9a4e258d2499
		summarizeBy: sum
		sourceColumn: benefits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column budget_cost
		dataType: double
		lineageTag: 53db71f8-0527-446a-999a-5d54ea047b3b
		summarizeBy: sum
		sourceColumn: budget_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column business_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 5a4e6737-b38d-4064-b562-c156990ee22b
		summarizeBy: none
		sourceColumn: business_duration

		variation Variación
			isDefault
			relationship: f7ded615-d35a-4f9f-80d0-6260b46ceec4
			defaultHierarchy: LocalDateTable_4c4def8b-e041-41df-8b4e-3ef46bee8ec5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_business_duration
		dataType: string
		lineageTag: 2e7a8c6c-df2a-42b8-b9ba-527ac55cfbf9
		summarizeBy: none
		sourceColumn: dv_business_duration

		annotation SummarizationSetBy = Automatic

	column business_service
		dataType: string
		lineageTag: d2aca374-40ce-4d8d-a50e-8b0276a52832
		summarizeBy: none
		sourceColumn: business_service

		annotation SummarizationSetBy = Automatic

	column dv_business_service
		dataType: string
		lineageTag: bfffb15b-645c-481d-80e9-af6b3df5434a
		summarizeBy: none
		sourceColumn: dv_business_service

		annotation SummarizationSetBy = Automatic

	column calculation_type
		dataType: string
		lineageTag: d81861f2-6db3-4654-a2da-267aa925c557
		summarizeBy: none
		sourceColumn: calculation_type

		annotation SummarizationSetBy = Automatic

	column dv_calculation_type
		dataType: string
		lineageTag: 9b01ee92-3d37-4b6e-a112-5570c40a2ab9
		summarizeBy: none
		sourceColumn: dv_calculation_type

		annotation SummarizationSetBy = Automatic

	column calendar_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 79c246c9-b544-44c2-913a-71be8c023725
		summarizeBy: none
		sourceColumn: calendar_duration

		variation Variación
			isDefault
			relationship: 0cd85b88-227c-41ba-aab2-16ab9f0b69ed
			defaultHierarchy: LocalDateTable_54f23a4d-4ab7-4fa8-9d16-d1cc1b039f7b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_calendar_duration
		dataType: string
		lineageTag: 3c05b23c-17ed-4389-b6a4-0881a2ff49c5
		summarizeBy: none
		sourceColumn: dv_calendar_duration

		annotation SummarizationSetBy = Automatic

	column capex_cost
		dataType: double
		lineageTag: 26ea55ab-07f5-4078-999e-cabd22a39029
		summarizeBy: sum
		sourceColumn: capex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column close_notes
		dataType: string
		lineageTag: 0c9d6166-c78f-4d26-9d69-ad9f461b4248
		summarizeBy: none
		sourceColumn: close_notes

		annotation SummarizationSetBy = Automatic

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 7611f8d0-e8bd-4e2c-8991-7278b5e889fd
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: 263aa612-dfdd-4695-b079-678da455be3a
			defaultHierarchy: LocalDateTable_8fd248a9-a807-43fa-bd52-cb2912193f60.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column closed_by
		dataType: string
		lineageTag: 82b4f05b-ca17-4045-a421-7cc412a4f0e7
		summarizeBy: none
		sourceColumn: closed_by

		annotation SummarizationSetBy = Automatic

	column dv_closed_by
		dataType: string
		lineageTag: e7ff9d73-c5b1-4505-9f8c-1cb84db019a4
		summarizeBy: none
		sourceColumn: dv_closed_by

		annotation SummarizationSetBy = Automatic

	column cmdb_ci
		dataType: string
		lineageTag: 14785569-53e9-495e-85c7-04c9a555654c
		summarizeBy: none
		sourceColumn: cmdb_ci

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci
		dataType: string
		lineageTag: 9ed65b68-0e20-4488-9f70-f1c767e494f9
		summarizeBy: none
		sourceColumn: dv_cmdb_ci

		annotation SummarizationSetBy = Automatic

	column cmdb_ci_business_app
		dataType: string
		lineageTag: 5d795dc5-00da-46ca-bd45-b0f55e4f41a3
		summarizeBy: none
		sourceColumn: cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci_business_app
		dataType: string
		lineageTag: 1b5655e7-ba55-48fc-90d1-b63dc0734139
		summarizeBy: none
		sourceColumn: dv_cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column comments
		dataType: string
		lineageTag: e11dc018-40ef-4837-a995-79782650f1d0
		summarizeBy: none
		sourceColumn: comments

		annotation SummarizationSetBy = Automatic

	column comments_and_work_notes
		dataType: string
		lineageTag: 52357bf3-4b6c-4edf-ae90-d80c60ae5ebd
		summarizeBy: none
		sourceColumn: comments_and_work_notes

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 3dc20cd7-e5fc-4495-8f05-89fa01d90740
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column dv_company
		dataType: string
		lineageTag: 14c46c53-0f07-4fd3-84df-cd8acb9d81e5
		summarizeBy: none
		sourceColumn: dv_company

		annotation SummarizationSetBy = Automatic

	column constraint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: dbe996b7-ca39-45f5-ae9a-a3caf7575457
		summarizeBy: none
		sourceColumn: constraint_date

		variation Variación
			isDefault
			relationship: 5eb72587-1b34-4fba-901c-66886f13871c
			defaultHierarchy: LocalDateTable_c4c8f953-cf59-48e9-883d-ad1ac128d81a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column contact_type
		dataType: string
		lineageTag: 779a4a86-fe1c-42f3-8a11-ca07c258ddbf
		summarizeBy: none
		sourceColumn: contact_type

		annotation SummarizationSetBy = Automatic

	column dv_contact_type
		dataType: string
		lineageTag: c6f57a93-7ecc-4ae1-bc34-0dca433209f5
		summarizeBy: none
		sourceColumn: dv_contact_type

		annotation SummarizationSetBy = Automatic

	column correlation_display
		dataType: string
		lineageTag: 9e62fbe9-a613-4fee-9b24-8ddffeebf863
		summarizeBy: none
		sourceColumn: correlation_display

		annotation SummarizationSetBy = Automatic

	column correlation_id
		dataType: string
		lineageTag: 937fad61-785e-406e-9f0d-388d54669b1a
		summarizeBy: none
		sourceColumn: correlation_id

		annotation SummarizationSetBy = Automatic

	column cost
		dataType: double
		lineageTag: 4870e8a3-ed95-4cbe-a00b-5b1cdec66dd7
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column critical_path
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 582762e2-44f6-42e5-843b-c2ecece1c8a1
		summarizeBy: none
		sourceColumn: critical_path

		annotation SummarizationSetBy = Automatic

	column delivery_plan
		dataType: string
		lineageTag: 4845b366-33f9-42c0-b9b2-3bed88614641
		summarizeBy: none
		sourceColumn: delivery_plan

		annotation SummarizationSetBy = Automatic

	column dv_delivery_plan
		dataType: string
		lineageTag: dc6837fd-2f81-43a1-b7b9-2691de35bf1c
		summarizeBy: none
		sourceColumn: dv_delivery_plan

		annotation SummarizationSetBy = Automatic

	column delivery_task
		dataType: string
		lineageTag: 2988f60e-5d58-43cb-895e-2bc2c2c8774a
		summarizeBy: none
		sourceColumn: delivery_task

		annotation SummarizationSetBy = Automatic

	column dv_delivery_task
		dataType: string
		lineageTag: dc0008b2-a5e1-496c-858a-298ad5520dea
		summarizeBy: none
		sourceColumn: dv_delivery_task

		annotation SummarizationSetBy = Automatic

	column dependency
		dataType: string
		lineageTag: 0eecff90-090a-40f5-afbd-57e46e9f6ddb
		summarizeBy: none
		sourceColumn: dependency

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 83c565b4-3b44-4405-8a5e-14e25c9d1ef4
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column due_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 149a06b7-72f2-41c5-859e-84dbbe4dcf5d
		summarizeBy: none
		sourceColumn: due_date

		variation Variación
			isDefault
			relationship: 506ab7dd-fc87-4237-bdfa-79d3da826bc5
			defaultHierarchy: LocalDateTable_7181c3de-2092-4661-aa99-0d913c4b4464.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column duration
		dataType: dateTime
		formatString: General Date
		lineageTag: f0ecc965-c0dd-43ef-a72f-102fd62e3791
		summarizeBy: none
		sourceColumn: duration

		variation Variación
			isDefault
			relationship: a6fbd21b-faa9-486a-a789-acba639e9a5d
			defaultHierarchy: LocalDateTable_9a8765e9-2275-4f8a-963d-6d31fe291bcd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_duration
		dataType: string
		lineageTag: d56d4b85-7784-4090-ae7c-781420967d50
		summarizeBy: none
		sourceColumn: dv_duration

		annotation SummarizationSetBy = Automatic

	column effort
		dataType: dateTime
		formatString: General Date
		lineageTag: 880f8e2a-6ece-4924-9062-d0fb175011e7
		summarizeBy: none
		sourceColumn: effort

		variation Variación
			isDefault
			relationship: 3fb51f03-a0c0-4d18-9b2f-99f6f24a85b4
			defaultHierarchy: LocalDateTable_e7f09874-c15a-4736-852c-52b664a1c228.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_effort
		dataType: string
		lineageTag: d3690b51-e14d-459f-9e66-5cba13150891
		summarizeBy: none
		sourceColumn: dv_effort

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3364e6d1-4170-45f2-9c00-44b77d0f8a86
		summarizeBy: none
		sourceColumn: end_date

		variation Variación
			isDefault
			relationship: 73c9209c-01d8-4830-b720-19a0aaa69d03
			defaultHierarchy: LocalDateTable_686d1fb8-b4d2-4f12-8bdb-a5ecda5add0b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column end_date_derived_from
		dataType: string
		lineageTag: 65d30547-9ac0-451b-93a2-56a2f399ed2a
		summarizeBy: none
		sourceColumn: end_date_derived_from

		annotation SummarizationSetBy = Automatic

	column dv_end_date_derived_from
		dataType: string
		lineageTag: acea1b03-06ce-4f5d-837d-3c27fd3e1518
		summarizeBy: none
		sourceColumn: dv_end_date_derived_from

		annotation SummarizationSetBy = Automatic

	column end_sprint
		dataType: string
		lineageTag: 59aa95a8-4149-4f91-9259-5f2ae6ffbda7
		summarizeBy: none
		sourceColumn: end_sprint

		annotation SummarizationSetBy = Automatic

	column dv_end_sprint
		dataType: string
		lineageTag: b756e6f1-547f-4f16-993f-f41e0147bde6
		summarizeBy: none
		sourceColumn: dv_end_sprint

		annotation SummarizationSetBy = Automatic

	column escalation
		dataType: int64
		formatString: 0
		lineageTag: d430497b-787d-4ea3-8b65-236f7a8392b4
		summarizeBy: sum
		sourceColumn: escalation

		annotation SummarizationSetBy = Automatic

	column dv_escalation
		dataType: string
		lineageTag: 50f657ae-8a29-4ddb-b8d7-344039d0f4a3
		summarizeBy: none
		sourceColumn: dv_escalation

		annotation SummarizationSetBy = Automatic

	column expected_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 9083e832-a809-41f8-bb3c-b5a3bb7a606f
		summarizeBy: none
		sourceColumn: expected_start

		variation Variación
			isDefault
			relationship: 49c141cb-f65e-4c5b-8ff9-e2f83ee7c964
			defaultHierarchy: LocalDateTable_47429e17-396e-4eb4-8565-e27d34f2c129.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column follow_up
		dataType: dateTime
		formatString: General Date
		lineageTag: fc5a9c25-ce9a-46dd-98d7-287e003dab8c
		summarizeBy: none
		sourceColumn: follow_up

		variation Variación
			isDefault
			relationship: f69d00ea-3b66-49f8-9ac4-f91168c116ce
			defaultHierarchy: LocalDateTable_1d7c0367-12a7-413a-aa5b-efefc5335455.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column group_list
		dataType: string
		lineageTag: e1220ae1-e588-4adc-854a-64fedb2ceb2d
		summarizeBy: none
		sourceColumn: group_list

		annotation SummarizationSetBy = Automatic

	column has_conflict
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3041c4d7-122f-4096-ad1c-f3f11962611a
		summarizeBy: none
		sourceColumn: has_conflict

		annotation SummarizationSetBy = Automatic

	column html_description
		dataType: string
		lineageTag: 80957fce-9665-409e-8bdb-db723c9ed4d0
		summarizeBy: none
		sourceColumn: html_description

		annotation SummarizationSetBy = Automatic

	column impact
		dataType: int64
		formatString: 0
		lineageTag: a62cd30b-d471-49bf-86be-2535eea0de4c
		summarizeBy: sum
		sourceColumn: impact

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: 3d479333-b0ef-4ffc-86ba-c170c6caf320
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column key_milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7a481292-b61f-477a-985d-e7f383f79321
		summarizeBy: none
		sourceColumn: key_milestone

		annotation SummarizationSetBy = Automatic

	column knowledge
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1f8fc4a5-2a71-412b-8c18-31d5e76a2fe1
		summarizeBy: none
		sourceColumn: knowledge

		annotation SummarizationSetBy = Automatic

	column level
		dataType: int64
		formatString: 0
		lineageTag: bac4c9f8-6c92-4d57-918b-35a74b349257
		summarizeBy: sum
		sourceColumn: level

		annotation SummarizationSetBy = Automatic

	column link
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d1519eba-f0f6-4b31-a356-756051c5303f
		summarizeBy: none
		sourceColumn: link

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 8603b1c3-aa5f-45b2-8d6f-68dbda6b9372
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column dv_location
		dataType: string
		lineageTag: fe6cf392-01ae-4452-898c-2ec7f843b0c9
		summarizeBy: none
		sourceColumn: dv_location

		annotation SummarizationSetBy = Automatic

	column made_sla
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 703a3f00-a1a6-4ef2-8dd8-e997ba0b4bd5
		summarizeBy: none
		sourceColumn: made_sla

		annotation SummarizationSetBy = Automatic

	column milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 99f155c1-e061-4edc-9997-3df4a3674f77
		summarizeBy: none
		sourceColumn: milestone

		annotation SummarizationSetBy = Automatic

	column mpp_task_id
		dataType: int64
		formatString: 0
		lineageTag: fe851fbc-5ff8-4d16-a5db-b39ab6cd2b94
		summarizeBy: sum
		sourceColumn: mpp_task_id

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: 2dbb1a77-91a1-4adb-9f9f-2cef2a78068d
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 07e3a828-ef2a-4a11-a2f2-b87007411674
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: e609b6ca-5c29-42eb-8207-380fce551231
			defaultHierarchy: LocalDateTable_7a4a5b60-73e3-4430-a008-8dd938a78b6c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column opened_by
		dataType: string
		lineageTag: dba58786-67af-4bbb-bad4-c4c85fd9bdf9
		summarizeBy: none
		sourceColumn: opened_by

		annotation SummarizationSetBy = Automatic

	column dv_opened_by
		dataType: string
		lineageTag: 253da4dd-3cf8-4904-980c-10e143561cec
		summarizeBy: none
		sourceColumn: dv_opened_by

		annotation SummarizationSetBy = Automatic

	column opex_cost
		dataType: double
		lineageTag: b772505f-b7f4-496c-9c53-9df2aa310c19
		summarizeBy: sum
		sourceColumn: opex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order
		dataType: int64
		formatString: 0
		lineageTag: 11e8478a-bd44-48ff-838b-e29436761954
		summarizeBy: sum
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	column orig_sys_id
		dataType: string
		lineageTag: b6c8e6f4-4aa3-4de6-99d7-c5eb22b600c9
		summarizeBy: none
		sourceColumn: orig_sys_id

		annotation SummarizationSetBy = Automatic

	column dv_orig_sys_id
		dataType: string
		lineageTag: afad290d-8269-4016-9a1b-9d15b68e1040
		summarizeBy: none
		sourceColumn: dv_orig_sys_id

		annotation SummarizationSetBy = Automatic

	column orig_top_task_id
		dataType: string
		lineageTag: 85f9d2ff-9cce-4b8c-9e4a-f34e62e7e08c
		summarizeBy: none
		sourceColumn: orig_top_task_id

		annotation SummarizationSetBy = Automatic

	column dv_orig_top_task_id
		dataType: string
		lineageTag: 699cdbb4-c492-4748-a175-2324212d891c
		summarizeBy: none
		sourceColumn: dv_orig_top_task_id

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: 3ddb3a65-e1d3-42b1-a8ec-c8142a5c40e0
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: 8e81b08d-ae72-48de-9ac2-82d84e900e56
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column percent_complete
		dataType: double
		lineageTag: f276036f-a765-4084-8943-aaf78789c90f
		summarizeBy: sum
		sourceColumn: percent_complete

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column phase_type
		dataType: string
		lineageTag: 9c7324c2-8d87-4986-97be-7f386b3d9c46
		summarizeBy: none
		sourceColumn: phase_type

		annotation SummarizationSetBy = Automatic

	column dv_phase_type
		dataType: string
		lineageTag: baa6aab1-8a50-4ad2-8bdc-00693c24c771
		summarizeBy: none
		sourceColumn: dv_phase_type

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: int64
		formatString: 0
		lineageTag: 860c77c3-fed5-4257-9648-a2e546ead8b0
		summarizeBy: sum
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: 4179f0e7-b3fb-4d48-be1e-569e300028a2
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column project
		dataType: string
		lineageTag: 1209e7c9-b633-4381-9aa8-dd899340dccb
		summarizeBy: none
		sourceColumn: project

		annotation SummarizationSetBy = Automatic

	column reassignment_count
		dataType: int64
		formatString: 0
		lineageTag: 52f21c85-dc4e-45e3-9a42-869a31a2db68
		summarizeBy: sum
		sourceColumn: reassignment_count

		annotation SummarizationSetBy = Automatic

	column rejection_goto
		dataType: string
		lineageTag: f80b8a5b-02c1-48ca-916f-7d18ae9f89a5
		summarizeBy: none
		sourceColumn: rejection_goto

		annotation SummarizationSetBy = Automatic

	column dv_rejection_goto
		dataType: string
		lineageTag: 183ff7d0-fa38-4669-874c-2bd27595a762
		summarizeBy: none
		sourceColumn: dv_rejection_goto

		annotation SummarizationSetBy = Automatic

	column relation_applied
		dataType: string
		lineageTag: 2ae7589a-ebb6-4776-8c68-57507f8c1d42
		summarizeBy: none
		sourceColumn: relation_applied

		annotation SummarizationSetBy = Automatic

	column dv_relation_applied
		dataType: string
		lineageTag: cc3ddcba-26e6-4920-b3f8-c998a0dfd065
		summarizeBy: none
		sourceColumn: dv_relation_applied

		annotation SummarizationSetBy = Automatic

	column remaining_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 93463cb7-5787-4ae9-a8ce-9eb6d69799b2
		summarizeBy: none
		sourceColumn: remaining_duration

		variation Variación
			isDefault
			relationship: 0d9cda67-0e9f-4468-93c4-a761fbe96b53
			defaultHierarchy: LocalDateTable_72554088-dd05-46f2-baa2-4e8b804bbbe4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_remaining_duration
		dataType: string
		lineageTag: f0fd8be1-672a-4e78-83ef-79d1acd485ec
		summarizeBy: none
		sourceColumn: dv_remaining_duration

		annotation SummarizationSetBy = Automatic

	column remaining_effort
		dataType: dateTime
		formatString: General Date
		lineageTag: 90c0862b-94f1-4138-b997-74d16dbbbaf5
		summarizeBy: none
		sourceColumn: remaining_effort

		variation Variación
			isDefault
			relationship: 02182cc3-76cd-4aae-aaf9-1d63535b322a
			defaultHierarchy: LocalDateTable_2ae42cc9-a8d7-41fd-83d9-300ee9e967a9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_remaining_effort
		dataType: string
		lineageTag: 847079ef-ed19-40bf-ae24-b574b76f6722
		summarizeBy: none
		sourceColumn: dv_remaining_effort

		annotation SummarizationSetBy = Automatic

	column resource_allocated_cost
		dataType: double
		lineageTag: 894f7da0-c419-4a17-8b71-8a23c1d91c6e
		summarizeBy: sum
		sourceColumn: resource_allocated_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column resource_planned_cost
		dataType: double
		lineageTag: fd7775d1-ece5-4bc6-b972-178e74d591de
		summarizeBy: sum
		sourceColumn: resource_planned_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rollup
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 574cde89-8ee9-4fd1-bbe0-8d66b3f2d810
		summarizeBy: none
		sourceColumn: rollup

		annotation SummarizationSetBy = Automatic

	column route_reason
		dataType: int64
		formatString: 0
		lineageTag: 48097380-cfb3-4618-9b6a-8d106ca85a08
		summarizeBy: sum
		sourceColumn: route_reason

		annotation SummarizationSetBy = Automatic

	column dv_route_reason
		dataType: string
		lineageTag: cd6ef111-4b08-4c16-822c-d8ea7ee2b606
		summarizeBy: none
		sourceColumn: dv_route_reason

		annotation SummarizationSetBy = Automatic

	column schedule_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9b4e0b05-e6d6-404d-bfeb-b9bbdedf0f9c
		summarizeBy: none
		sourceColumn: schedule_end_date

		variation Variación
			isDefault
			relationship: 8f0cdc47-fafd-4ba4-acaa-2995f3aa78fd
			defaultHierarchy: LocalDateTable_b36e50ac-2e11-4564-8ebf-4d636c56730d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column schedule_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4749e6a3-67dc-4b2e-ac6f-2357ebf7ab6c
		summarizeBy: none
		sourceColumn: schedule_start_date

		variation Variación
			isDefault
			relationship: fe73f24c-fa55-4357-9436-d804035d2aa0
			defaultHierarchy: LocalDateTable_5c74ea78-1cdc-46f7-8385-1d719f446817.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column scrum_team
		dataType: string
		lineageTag: 48090989-dda3-4587-97cf-600b65e96307
		summarizeBy: none
		sourceColumn: scrum_team

		annotation SummarizationSetBy = Automatic

	column dv_scrum_team
		dataType: string
		lineageTag: d8bf72a6-5da0-49f8-a74c-23724e7e4868
		summarizeBy: none
		sourceColumn: dv_scrum_team

		annotation SummarizationSetBy = Automatic

	column service_offering
		dataType: string
		lineageTag: fde21a96-fd44-4cd0-b533-50661378433c
		summarizeBy: none
		sourceColumn: service_offering

		annotation SummarizationSetBy = Automatic

	column dv_service_offering
		dataType: string
		lineageTag: 19ea45a8-6d15-4fae-9eb7-d6c4be5a60a9
		summarizeBy: none
		sourceColumn: dv_service_offering

		annotation SummarizationSetBy = Automatic

	column shadow
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 87d0d692-dd21-47ef-a52c-d10c9252ad86
		summarizeBy: none
		sourceColumn: shadow

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: 1793c827-e74b-4fea-81b2-adef9e8b8e5e
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column skills
		dataType: string
		lineageTag: befcb135-c5ac-4169-80c7-c5446d1c630e
		summarizeBy: none
		sourceColumn: skills

		annotation SummarizationSetBy = Automatic

	column sla_due
		dataType: dateTime
		formatString: General Date
		lineageTag: a6af0e18-b3fe-43bd-b4ff-9989b2dbdd0a
		summarizeBy: none
		sourceColumn: sla_due

		variation Variación
			isDefault
			relationship: c18da7f5-637b-4f19-9a1f-ffcd15e7765c
			defaultHierarchy: LocalDateTable_ce03cc7b-56a7-419c-bc40-6be809f9c304.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9e95868e-3a23-4381-97e4-a681a84f610e
		summarizeBy: none
		sourceColumn: start_date

		variation Variación
			isDefault
			relationship: a1b2560a-23be-4577-a4f2-27a9ebfd377d
			defaultHierarchy: LocalDateTable_56ae663b-4ce3-49fb-b184-46ee14e64280.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column start_date_derived_from
		dataType: string
		lineageTag: 41e92676-0376-4641-aa18-935ed08d38c2
		summarizeBy: none
		sourceColumn: start_date_derived_from

		annotation SummarizationSetBy = Automatic

	column dv_start_date_derived_from
		dataType: string
		lineageTag: 794c42a8-28e3-42df-bec5-45f32dbc9f58
		summarizeBy: none
		sourceColumn: dv_start_date_derived_from

		annotation SummarizationSetBy = Automatic

	column start_sprint
		dataType: string
		lineageTag: 2166d310-ea00-40b9-b004-583e8e1e8f1a
		summarizeBy: none
		sourceColumn: start_sprint

		annotation SummarizationSetBy = Automatic

	column dv_start_sprint
		dataType: string
		lineageTag: f4b88b4e-f445-42a1-ba9d-a99ae2082f25
		summarizeBy: none
		sourceColumn: dv_start_sprint

		annotation SummarizationSetBy = Automatic

	column state
		dataType: int64
		formatString: 0
		lineageTag: a02e9fb4-49c3-4d2d-9e7c-0dc04d23b9a1
		summarizeBy: sum
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: c8a75704-e097-43cf-b3a1-3b77c6c51e74
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: a2ff18b4-afaf-4275-be8d-bb7526eb27dd
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column dv_status
		dataType: string
		lineageTag: 741cb0c7-d566-4722-a059-d4dc92f75a57
		summarizeBy: none
		sourceColumn: dv_status

		annotation SummarizationSetBy = Automatic

	column sub_tree_root
		dataType: string
		lineageTag: 6e2f7ebe-9066-4a95-afd1-b9ed1a447ac5
		summarizeBy: none
		sourceColumn: sub_tree_root

		annotation SummarizationSetBy = Automatic

	column dv_sub_tree_root
		dataType: string
		lineageTag: 1b53474d-7ddc-4d1c-a085-9320d938e232
		summarizeBy: none
		sourceColumn: dv_sub_tree_root

		annotation SummarizationSetBy = Automatic

	column sys_class_name
		dataType: string
		lineageTag: 8a1697c4-b44d-45c4-aedc-047857f79896
		summarizeBy: none
		sourceColumn: sys_class_name

		annotation SummarizationSetBy = Automatic

	column dv_sys_class_name
		dataType: string
		lineageTag: 7bfe56f9-42d9-45bc-bf70-b87fbf43595d
		summarizeBy: none
		sourceColumn: dv_sys_class_name

		annotation SummarizationSetBy = Automatic

	column sys_created_by
		dataType: string
		lineageTag: 2506e2f9-2bb7-4efe-a38e-66109b3ec02c
		summarizeBy: none
		sourceColumn: sys_created_by

		annotation SummarizationSetBy = Automatic

	column sys_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 4ac4180e-ca82-4bef-bfec-0c0486dc6aed
		summarizeBy: none
		sourceColumn: sys_created_on

		variation Variación
			isDefault
			relationship: 274a38fd-7374-4931-8eaa-baa9e9b991e8
			defaultHierarchy: LocalDateTable_5c9afd21-44cc-4a98-bb09-7a023d66cd9e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column sys_domain
		dataType: string
		lineageTag: 197560c1-2723-4496-a1f0-0e758dbe03c0
		summarizeBy: none
		sourceColumn: sys_domain

		annotation SummarizationSetBy = Automatic

	column sys_domain_path
		dataType: string
		lineageTag: 8928acb7-bfa9-496e-97f5-da3c7c15c13e
		summarizeBy: none
		sourceColumn: sys_domain_path

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: af66db57-c646-4d5b-a49f-093d6747cf6b
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column sys_mod_count
		dataType: int64
		formatString: 0
		lineageTag: 04da8d17-bfb0-46b6-afb3-67bb40742462
		summarizeBy: sum
		sourceColumn: sys_mod_count

		annotation SummarizationSetBy = Automatic

	column sys_tags
		dataType: string
		lineageTag: 9efd4186-10a0-459c-a8a0-04633beffc0d
		summarizeBy: none
		sourceColumn: sys_tags

		annotation SummarizationSetBy = Automatic

	column sys_updated_by
		dataType: string
		lineageTag: c7b53f63-63f6-4527-af4d-0829acc04330
		summarizeBy: none
		sourceColumn: sys_updated_by

		annotation SummarizationSetBy = Automatic

	column sys_updated_on
		dataType: dateTime
		formatString: General Date
		lineageTag: d8fe07e9-28e9-433e-9eb0-92d3e4d16c74
		summarizeBy: none
		sourceColumn: sys_updated_on

		variation Variación
			isDefault
			relationship: 40bacba8-f121-4038-aaca-51e71625f1be
			defaultHierarchy: LocalDateTable_80d8c6c9-8de3-422c-b5a7-a3073396addf.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column task
		dataType: string
		lineageTag: 263fd66b-4c55-48eb-b086-9bf809c073e7
		summarizeBy: none
		sourceColumn: task

		annotation SummarizationSetBy = Automatic

	column task_effective_number
		dataType: string
		lineageTag: 384ea151-3135-4290-84af-ea050075ba3d
		summarizeBy: none
		sourceColumn: task_effective_number

		annotation SummarizationSetBy = Automatic

	column task_for
		dataType: string
		lineageTag: 4a04830e-e211-4956-a1f2-34c6b273c67e
		summarizeBy: none
		sourceColumn: task_for

		annotation SummarizationSetBy = Automatic

	column dv_task_for
		dataType: string
		lineageTag: 4d1706c8-3f7b-401a-be4d-234a336c87e7
		summarizeBy: none
		sourceColumn: dv_task_for

		annotation SummarizationSetBy = Automatic

	column test_plan
		dataType: string
		lineageTag: 386610c6-454b-4904-b43e-8a773a560043
		summarizeBy: none
		sourceColumn: test_plan

		annotation SummarizationSetBy = Automatic

	column dv_test_plan
		dataType: string
		lineageTag: 32471e1e-ad57-4226-9a33-ca475797603f
		summarizeBy: none
		sourceColumn: dv_test_plan

		annotation SummarizationSetBy = Automatic

	column time_card_at_top_task
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a5a15fdd-4719-40d8-b515-74f7796e4751
		summarizeBy: none
		sourceColumn: time_card_at_top_task

		annotation SummarizationSetBy = Automatic

	column time_constraint
		dataType: string
		lineageTag: 60548a61-1695-4f26-be1c-d6c52416d1af
		summarizeBy: none
		sourceColumn: time_constraint

		annotation SummarizationSetBy = Automatic

	column dv_time_constraint
		dataType: string
		lineageTag: ce962cb1-6e65-4867-9362-b7ecd306a21d
		summarizeBy: none
		sourceColumn: dv_time_constraint

		annotation SummarizationSetBy = Automatic

	column time_worked
		dataType: dateTime
		formatString: General Date
		lineageTag: 670e6ee4-e890-42ad-b2ce-c7a9d6aa5e60
		summarizeBy: none
		sourceColumn: time_worked

		variation Variación
			isDefault
			relationship: 1a3e4fba-73fd-43d4-bef1-caeee2f7cd5b
			defaultHierarchy: LocalDateTable_52f566ec-016c-466d-9050-e4704acb04af.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_time_worked
		dataType: string
		lineageTag: 8e4170e0-ced8-4e35-9220-85a37466991b
		summarizeBy: none
		sourceColumn: dv_time_worked

		annotation SummarizationSetBy = Automatic

	column top_portfolio
		dataType: string
		lineageTag: 28404ffa-7f40-494e-97bd-acd4ecdc1a51
		summarizeBy: none
		sourceColumn: top_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_top_portfolio
		dataType: string
		lineageTag: c3ea1c2d-7257-4bf5-8592-9a967c73b3f8
		summarizeBy: none
		sourceColumn: dv_top_portfolio

		annotation SummarizationSetBy = Automatic

	column top_program
		dataType: string
		lineageTag: bb2accb9-aef0-4956-afdf-290667138906
		summarizeBy: none
		sourceColumn: top_program

		annotation SummarizationSetBy = Automatic

	column dv_top_program
		dataType: string
		lineageTag: 7133e529-9bcc-4aa1-91b6-0ec03f2969b9
		summarizeBy: none
		sourceColumn: dv_top_program

		annotation SummarizationSetBy = Automatic

	column top_task
		dataType: string
		lineageTag: d84a247a-1c44-4de3-9723-2069b2fe9783
		summarizeBy: none
		sourceColumn: top_task

		annotation SummarizationSetBy = Automatic

	column dv_top_task
		dataType: string
		lineageTag: d02b3c2b-863a-423e-9274-c5c600b14778
		summarizeBy: none
		sourceColumn: dv_top_task

		annotation SummarizationSetBy = Automatic

	column u_acciona_priority
		dataType: int64
		formatString: 0
		lineageTag: 3a7248da-ae8e-4538-9d4c-0eca69793569
		summarizeBy: sum
		sourceColumn: u_acciona_priority

		annotation SummarizationSetBy = Automatic

	column u_business_line
		dataType: string
		lineageTag: 0e674549-6114-4b46-affb-037248eb94a0
		summarizeBy: none
		sourceColumn: u_business_line

		annotation SummarizationSetBy = Automatic

	column dv_u_business_line
		dataType: string
		lineageTag: 248d1085-da93-458f-895c-57feb63712a8
		summarizeBy: none
		sourceColumn: dv_u_business_line

		annotation SummarizationSetBy = Automatic

	column u_catalog
		dataType: string
		lineageTag: 84662117-8949-43fe-bce7-187f4592aa03
		summarizeBy: none
		sourceColumn: u_catalog

		annotation SummarizationSetBy = Automatic

	column dv_u_catalog
		dataType: string
		lineageTag: 64d91471-e923-4921-8cb7-43b437a0e8b1
		summarizeBy: none
		sourceColumn: dv_u_catalog

		annotation SummarizationSetBy = Automatic

	column UnionConDemanda
		dataType: string
		lineageTag: 0478e6f3-30dc-48cd-bd33-f2897395bc5b
		summarizeBy: none
		sourceColumn: UnionConDemanda

		annotation SummarizationSetBy = Automatic

	column dv_u_demand
		dataType: string
		lineageTag: 2f8e63e5-8e14-43c6-8277-bcf8c6101636
		summarizeBy: none
		sourceColumn: dv_u_demand

		annotation SummarizationSetBy = Automatic

	column u_department
		dataType: string
		lineageTag: fa724a30-4b0b-4fe4-8889-f7a110ac6f6b
		summarizeBy: none
		sourceColumn: u_department

		annotation SummarizationSetBy = Automatic

	column dv_u_department
		dataType: string
		lineageTag: 28dcbcdf-5efe-4d76-b79c-aabbd90ff674
		summarizeBy: none
		sourceColumn: dv_u_department

		annotation SummarizationSetBy = Automatic

	column u_estado_evolutivo
		dataType: string
		lineageTag: ecb92c16-b8d0-4e9a-867d-f6751e8b9200
		summarizeBy: none
		sourceColumn: u_estado_evolutivo

		annotation SummarizationSetBy = Automatic

	column dv_u_estado_evolutivo
		dataType: string
		lineageTag: d9755fd5-c3db-46e2-a10d-84b98a560f07
		summarizeBy: none
		sourceColumn: dv_u_estado_evolutivo

		annotation SummarizationSetBy = Automatic

	column u_external_vendor
		dataType: string
		lineageTag: 87a6f8d7-729d-4b1e-be1f-cc004e55e2f0
		summarizeBy: none
		sourceColumn: u_external_vendor

		annotation SummarizationSetBy = Automatic

	column dv_u_external_vendor
		dataType: string
		lineageTag: 17b3ec2d-694a-4214-be4d-8f23ba53b460
		summarizeBy: none
		sourceColumn: dv_u_external_vendor

		annotation SummarizationSetBy = Automatic

	column u_metal
		dataType: string
		lineageTag: a01c2c5e-b79b-4a75-acc3-a63d493333a9
		summarizeBy: none
		sourceColumn: u_metal

		annotation SummarizationSetBy = Automatic

	column dv_u_metal
		dataType: string
		lineageTag: 2e96c496-af0e-408d-be93-944d82901de7
		summarizeBy: none
		sourceColumn: dv_u_metal

		annotation SummarizationSetBy = Automatic

	column u_phone
		dataType: string
		lineageTag: 9145bbf3-0321-49a8-978c-757fa9f09462
		summarizeBy: none
		sourceColumn: u_phone

		annotation SummarizationSetBy = Automatic

	column u_previous_groups
		dataType: string
		lineageTag: 49d46171-1a45-4857-adbd-c39c45df3421
		summarizeBy: none
		sourceColumn: u_previous_groups

		annotation SummarizationSetBy = Automatic

	column u_progress
		dataType: double
		lineageTag: 58f2d27f-bb1a-433c-9731-3b2a9b5df345
		summarizeBy: sum
		sourceColumn: u_progress

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_ref_country
		dataType: string
		lineageTag: 9ac480ae-d1e0-4682-ab4f-176bef24da45
		summarizeBy: none
		sourceColumn: u_ref_country

		annotation SummarizationSetBy = Automatic

	column dv_u_ref_country
		dataType: string
		lineageTag: 466aed92-ba25-42c2-9c9d-db7ae326fd81
		summarizeBy: none
		sourceColumn: dv_u_ref_country

		annotation SummarizationSetBy = Automatic

	column u_responded
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3d2fcc63-4684-482f-a756-ff7bdf2b49db
		summarizeBy: none
		sourceColumn: u_responded

		annotation SummarizationSetBy = Automatic

	column u_size
		dataType: string
		lineageTag: abbf0425-61bb-490b-9ef3-ce1fc27e0e89
		summarizeBy: none
		sourceColumn: u_size

		annotation SummarizationSetBy = Automatic

	column dv_u_size
		dataType: string
		lineageTag: 1879f517-fcbd-4c4b-bbb6-6e495a2e9312
		summarizeBy: none
		sourceColumn: dv_u_size

		annotation SummarizationSetBy = Automatic

	column u_state_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0bf6bc5f-9712-430a-9e11-b6337d5eb446
		summarizeBy: none
		sourceColumn: u_state_date

		variation Variación
			isDefault
			relationship: bed0b63b-45df-494c-9b8e-6ef3c7cbd298
			defaultHierarchy: LocalDateTable_8fb0a120-576b-41f4-bb8b-fea651d2eed0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_version
		dataType: string
		lineageTag: edf5fefa-c535-44aa-bbfd-a917ffbbffe7
		summarizeBy: none
		sourceColumn: u_version

		annotation SummarizationSetBy = Automatic

	column universal_request
		dataType: string
		lineageTag: dc540de9-b76e-447c-a055-d76f6ba4678f
		summarizeBy: none
		sourceColumn: universal_request

		annotation SummarizationSetBy = Automatic

	column dv_universal_request
		dataType: string
		lineageTag: 92d30e80-ad0c-4ac8-b48a-1a70fb7085a3
		summarizeBy: none
		sourceColumn: dv_universal_request

		annotation SummarizationSetBy = Automatic

	column upon_approval
		dataType: string
		lineageTag: b1f38381-dbb1-47af-b7f8-7f40e4415023
		summarizeBy: none
		sourceColumn: upon_approval

		annotation SummarizationSetBy = Automatic

	column dv_upon_approval
		dataType: string
		lineageTag: e25db7e0-3f37-4ec4-b649-57c933deb174
		summarizeBy: none
		sourceColumn: dv_upon_approval

		annotation SummarizationSetBy = Automatic

	column upon_reject
		dataType: string
		lineageTag: a6d99f8f-4a9e-46d4-bd31-59ad67718dc7
		summarizeBy: none
		sourceColumn: upon_reject

		annotation SummarizationSetBy = Automatic

	column dv_upon_reject
		dataType: string
		lineageTag: a3846467-526c-4933-93d9-198b73e8e1c7
		summarizeBy: none
		sourceColumn: dv_upon_reject

		annotation SummarizationSetBy = Automatic

	column urgency
		dataType: int64
		formatString: 0
		lineageTag: a4b69ab9-15c1-4408-891a-4c031952175a
		summarizeBy: sum
		sourceColumn: urgency

		annotation SummarizationSetBy = Automatic

	column dv_urgency
		dataType: string
		lineageTag: 04b3965f-1566-4935-8d0a-c88d45d7f4cf
		summarizeBy: none
		sourceColumn: dv_urgency

		annotation SummarizationSetBy = Automatic

	column user_input
		dataType: string
		lineageTag: 95c4df58-0980-428e-96c9-b719ae6348aa
		summarizeBy: none
		sourceColumn: user_input

		annotation SummarizationSetBy = Automatic

	column variables
		dataType: string
		lineageTag: 82dc7e5c-fab8-4d14-ad55-9d8bb6b88821
		summarizeBy: none
		sourceColumn: variables

		annotation SummarizationSetBy = Automatic

	column version
		dataType: int64
		formatString: 0
		lineageTag: 9ccc3023-48b2-475d-b512-af47de46dbc0
		summarizeBy: sum
		sourceColumn: version

		annotation SummarizationSetBy = Automatic

	column watch_list
		dataType: string
		lineageTag: 5ae6f00a-f658-4bfc-93bd-e24d46ff9aa9
		summarizeBy: none
		sourceColumn: watch_list

		annotation SummarizationSetBy = Automatic

	column wbs
		dataType: string
		lineageTag: 33aef1c4-8a5e-44af-8d33-ed830e657d40
		summarizeBy: none
		sourceColumn: wbs

		annotation SummarizationSetBy = Automatic

	column wbs_order
		dataType: int64
		formatString: 0
		lineageTag: b3864cbd-ee6e-49dd-a953-5a72af840f12
		summarizeBy: sum
		sourceColumn: wbs_order

		annotation SummarizationSetBy = Automatic

	column wf_activity
		dataType: string
		lineageTag: 3b1030a5-8048-4d05-b26e-b41d7cd9b9e8
		summarizeBy: none
		sourceColumn: wf_activity

		annotation SummarizationSetBy = Automatic

	column dv_wf_activity
		dataType: string
		lineageTag: a7db1231-7a53-4ff9-b334-5e6482fa24cc
		summarizeBy: none
		sourceColumn: dv_wf_activity

		annotation SummarizationSetBy = Automatic

	column work_cost
		dataType: double
		lineageTag: 29c93b91-26f0-48cf-8722-4798d42287ec
		summarizeBy: sum
		sourceColumn: work_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column work_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 639dc23a-f0d3-4e99-ad1d-666ef9fe6ea8
		summarizeBy: none
		sourceColumn: work_duration

		variation Variación
			isDefault
			relationship: 07733e2f-a737-4810-98cd-2897b1abd07a
			defaultHierarchy: LocalDateTable_38807090-11f8-4377-9814-e4cf7b137d5f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_work_duration
		dataType: string
		lineageTag: 65ebd93e-0305-4ca7-840e-5ac54c0e26dc
		summarizeBy: none
		sourceColumn: dv_work_duration

		annotation SummarizationSetBy = Automatic

	column work_effort
		dataType: dateTime
		formatString: General Date
		lineageTag: 93d0896e-1a3b-4b85-b408-b94c198cd869
		summarizeBy: none
		sourceColumn: work_effort

		variation Variación
			isDefault
			relationship: bd60d9a2-65f3-48d1-98c5-8243ebc368de
			defaultHierarchy: LocalDateTable_bc9e71b8-516a-4d07-bfaa-2e4c7bd445f3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_work_effort
		dataType: string
		lineageTag: 649b297c-fe56-4579-9874-76f244f45cb2
		summarizeBy: none
		sourceColumn: dv_work_effort

		annotation SummarizationSetBy = Automatic

	column work_end
		dataType: dateTime
		formatString: General Date
		lineageTag: d48afbae-3d5b-4ad0-9df2-ba1e6a6907d6
		summarizeBy: none
		sourceColumn: work_end

		variation Variación
			isDefault
			relationship: a1c17126-b6ed-4f53-830e-94d1dae63d34
			defaultHierarchy: LocalDateTable_9396823c-5c83-4f9a-8dbf-a1eb377dbf2c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column work_notes
		dataType: string
		lineageTag: 3378db8e-1a7a-4ab7-811f-9a505cb9c725
		summarizeBy: none
		sourceColumn: work_notes

		annotation SummarizationSetBy = Automatic

	column work_notes_list
		dataType: string
		lineageTag: 564e8c98-6d96-4f79-9fee-2f72d01abd69
		summarizeBy: none
		sourceColumn: work_notes_list

		annotation SummarizationSetBy = Automatic

	column work_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 0041736a-b875-4563-baf2-e7c744891e26
		summarizeBy: none
		sourceColumn: work_start

		variation Variación
			isDefault
			relationship: f4475498-7da4-4f47-9e13-a1f1750a2d6a
			defaultHierarchy: LocalDateTable_8eaedf08-ccfc-4f23-8425-5e8add42213a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'SERV_NOW_EN V_pm_project_task_Evolutivos' = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("QECCDWH.ACCIONA.INT:60001"),
				    DWH = Origen{[Name="DWH"]}[Data],
				    SERV_NOW_EN_V_pm_project_task = DWH{[Schema="SERV_NOW_EN",Item="V_pm_project_task"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(SERV_NOW_EN_V_pm_project_task, each ([u_demand] <> "")),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Filas filtradas",{{"u_demand", "UnionConDemanda"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Exception

