table 'SERV_NOW_EN V_rm_enhancement'
	lineageTag: c66068ca-c4e9-4e74-bfc0-761fce662ac0

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1bebfe43-58e5-4f27-b626-406027460522
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column activity_due
		dataType: dateTime
		formatString: General Date
		lineageTag: 1c608347-afbb-47a9-883d-e9b758de1c67
		summarizeBy: none
		sourceColumn: activity_due

		variation Variación
			isDefault
			relationship: e9d3c918-8c8e-407d-96d4-a617c41b7ba0
			defaultHierarchy: LocalDateTable_cb9b36ad-b90e-4d7d-845c-f0090b13b185.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column actual_benefits
		dataType: double
		lineageTag: 2aafee03-30fe-42c3-9553-1f2f31d169c9
		summarizeBy: sum
		sourceColumn: actual_benefits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column additional_assignee_list
		dataType: string
		lineageTag: 0fe3e3ea-296d-40c9-a9fd-3f417c908743
		summarizeBy: none
		sourceColumn: additional_assignee_list

		annotation SummarizationSetBy = Automatic

	column allow_dates_outside_schedule
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1ad3bbed-6f4c-4569-8b05-a7433ab15314
		summarizeBy: none
		sourceColumn: allow_dates_outside_schedule

		annotation SummarizationSetBy = Automatic

	column approval
		dataType: string
		lineageTag: 0b51f233-e4f8-46cc-91bc-d244086f4cea
		summarizeBy: none
		sourceColumn: approval

		annotation SummarizationSetBy = Automatic

	column dv_approval
		dataType: string
		lineageTag: 18188ad0-b3f8-4043-af53-6612e77b38fa
		summarizeBy: none
		sourceColumn: dv_approval

		annotation SummarizationSetBy = Automatic

	column approval_history
		dataType: string
		lineageTag: e7c0566d-2d40-4911-9398-e59e449ab22c
		summarizeBy: none
		sourceColumn: approval_history

		annotation SummarizationSetBy = Automatic

	column approval_set
		dataType: dateTime
		formatString: General Date
		lineageTag: 35bdf1eb-71b1-4418-83bc-df4ceaa9fdfa
		summarizeBy: none
		sourceColumn: approval_set

		variation Variación
			isDefault
			relationship: 59d8f313-8893-4c53-87f4-6cd5eb1070ff
			defaultHierarchy: LocalDateTable_a6518b9a-84ff-4407-bb78-ac26a15f247c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column assigned_to
		dataType: string
		lineageTag: ccf20272-d6e5-4ee3-9ccd-f1d7e447a77a
		summarizeBy: none
		sourceColumn: assigned_to

		annotation SummarizationSetBy = Automatic

	column dv_assigned_to
		dataType: string
		lineageTag: a7ac74b6-82aa-4bb8-81cf-23d720c321c2
		summarizeBy: none
		sourceColumn: dv_assigned_to

		annotation SummarizationSetBy = Automatic

	column assignment_group
		dataType: string
		lineageTag: f61695df-b80f-4725-aab7-9d36d7b7641d
		summarizeBy: none
		sourceColumn: assignment_group

		annotation SummarizationSetBy = Automatic

	column dv_assignment_group
		dataType: string
		lineageTag: 7130d1a2-c0af-490d-be78-2072ec1fa6d3
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column benefits
		dataType: double
		lineageTag: b1aa0268-89aa-454c-bb25-99cdafdc352a
		summarizeBy: sum
		sourceColumn: benefits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column budget_cost
		dataType: double
		lineageTag: d60f08bf-a12d-46f6-8cde-1ac59100beee
		summarizeBy: sum
		sourceColumn: budget_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column business_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 99f3a900-2497-4239-aa24-fc53ec1554fd
		summarizeBy: none
		sourceColumn: business_duration

		variation Variación
			isDefault
			relationship: 6ac11596-247a-48b7-858e-8edddf3c087a
			defaultHierarchy: LocalDateTable_0338d658-1e0c-4d2e-b9d1-61463b1bfde1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_business_duration
		dataType: string
		lineageTag: 188fd17d-af06-4cc5-a530-6da1102d2bec
		summarizeBy: none
		sourceColumn: dv_business_duration

		annotation SummarizationSetBy = Automatic

	column business_service
		dataType: string
		lineageTag: 3242b582-64c8-460c-9deb-9f0552c40743
		summarizeBy: none
		sourceColumn: business_service

		annotation SummarizationSetBy = Automatic

	column dv_business_service
		dataType: string
		lineageTag: 622f951b-5b56-4b4a-a05e-7912aec334f5
		summarizeBy: none
		sourceColumn: dv_business_service

		annotation SummarizationSetBy = Automatic

	column calculation_type
		dataType: string
		lineageTag: 351bccc6-d1ab-4b50-8289-eb9ca4ef2521
		summarizeBy: none
		sourceColumn: calculation_type

		annotation SummarizationSetBy = Automatic

	column dv_calculation_type
		dataType: string
		lineageTag: 26c8a2ee-3904-44a2-b345-d356896f37f1
		summarizeBy: none
		sourceColumn: dv_calculation_type

		annotation SummarizationSetBy = Automatic

	column calendar_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 00555324-e500-40fd-b835-9b61bebf2f0d
		summarizeBy: none
		sourceColumn: calendar_duration

		variation Variación
			isDefault
			relationship: bcf38550-b977-4a3b-b7a2-251b25113ad6
			defaultHierarchy: LocalDateTable_8b484b36-3bf4-476c-91eb-f84702a875f1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_calendar_duration
		dataType: string
		lineageTag: 40626b84-7334-433b-8337-a33e9df6504f
		summarizeBy: none
		sourceColumn: dv_calendar_duration

		annotation SummarizationSetBy = Automatic

	column capex_cost
		dataType: double
		lineageTag: 6c5aab88-8b9d-4cb9-8637-cbe5adfcb044
		summarizeBy: sum
		sourceColumn: capex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column close_notes
		dataType: string
		lineageTag: a3682f61-478a-4ab5-951e-5dcb1152bb20
		summarizeBy: none
		sourceColumn: close_notes

		annotation SummarizationSetBy = Automatic

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: fb47d143-80dd-4efd-b33f-264217eb8f0c
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: a00b7dbf-4126-4627-a050-ebd7c1a5412c
			defaultHierarchy: LocalDateTable_7fece560-b149-432c-a735-5e109c1f899a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column closed_by
		dataType: string
		lineageTag: c8b5d01b-59ae-457a-bfbf-33a4bda2f7bd
		summarizeBy: none
		sourceColumn: closed_by

		annotation SummarizationSetBy = Automatic

	column dv_closed_by
		dataType: string
		lineageTag: ab99d388-2cd6-45d4-b8d8-6df0ccc1dbc7
		summarizeBy: none
		sourceColumn: dv_closed_by

		annotation SummarizationSetBy = Automatic

	column cmdb_ci
		dataType: string
		lineageTag: da882674-417e-483e-8eae-8d0821bb2f0f
		summarizeBy: none
		sourceColumn: cmdb_ci

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci
		dataType: string
		lineageTag: 39240ce8-9ef2-4cc1-8be1-b438b863d142
		summarizeBy: none
		sourceColumn: dv_cmdb_ci

		annotation SummarizationSetBy = Automatic

	column cmdb_ci_business_app
		dataType: string
		lineageTag: c884e810-2e3f-4c22-bc24-f6e1b59caf07
		summarizeBy: none
		sourceColumn: cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci_business_app
		dataType: string
		lineageTag: 57f9add1-9994-4bf7-8687-34289717f15e
		summarizeBy: none
		sourceColumn: dv_cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column comments
		dataType: string
		lineageTag: 1f7434c6-b0a1-4889-a526-7155bdf68236
		summarizeBy: none
		sourceColumn: comments

		annotation SummarizationSetBy = Automatic

	column comments_and_work_notes
		dataType: string
		lineageTag: a18faf7a-b8c4-4d02-95ad-013009c3a9a9
		summarizeBy: none
		sourceColumn: comments_and_work_notes

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: f5bd325b-1cdb-4095-878d-b418cc3f77c5
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column dv_company
		dataType: string
		lineageTag: 793a257e-894b-4f9b-8b8e-51ab5b5d4dbc
		summarizeBy: none
		sourceColumn: dv_company

		annotation SummarizationSetBy = Automatic

	column constraint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0680578d-b173-462f-a635-1aa1f76e71fe
		summarizeBy: none
		sourceColumn: constraint_date

		variation Variación
			isDefault
			relationship: 7b72efca-dce5-4a4b-b285-a9092066c75c
			defaultHierarchy: LocalDateTable_96eed581-5e80-4048-ae1f-323a31ceb1d5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column contact_type
		dataType: string
		lineageTag: 66d8228e-25a1-4c5a-86bb-cecac8fde296
		summarizeBy: none
		sourceColumn: contact_type

		annotation SummarizationSetBy = Automatic

	column dv_contact_type
		dataType: string
		lineageTag: 982366cc-ab96-4200-94de-4be252ae1e31
		summarizeBy: none
		sourceColumn: dv_contact_type

		annotation SummarizationSetBy = Automatic

	column correlation_display
		dataType: string
		lineageTag: c37ae454-8ce3-479d-91cc-c22abb9464c8
		summarizeBy: none
		sourceColumn: correlation_display

		annotation SummarizationSetBy = Automatic

	column correlation_id
		dataType: string
		lineageTag: 6a75fb84-aeb4-46fb-87b7-06888b0b6409
		summarizeBy: none
		sourceColumn: correlation_id

		annotation SummarizationSetBy = Automatic

	column cost
		dataType: double
		lineageTag: 2c451e25-5879-4369-a0c2-c302ef408af0
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column critical_path
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 113e3598-da67-4507-ac43-74239ba53932
		summarizeBy: none
		sourceColumn: critical_path

		annotation SummarizationSetBy = Automatic

	column delivery_plan
		dataType: string
		lineageTag: c07cec96-0154-4758-a67a-c002bbc44107
		summarizeBy: none
		sourceColumn: delivery_plan

		annotation SummarizationSetBy = Automatic

	column dv_delivery_plan
		dataType: string
		lineageTag: a64794d4-4388-46ec-9a0a-87ac95380bb7
		summarizeBy: none
		sourceColumn: dv_delivery_plan

		annotation SummarizationSetBy = Automatic

	column delivery_task
		dataType: string
		lineageTag: 3008ea72-5463-4853-b8a2-648bc4427416
		summarizeBy: none
		sourceColumn: delivery_task

		annotation SummarizationSetBy = Automatic

	column dv_delivery_task
		dataType: string
		lineageTag: a88f67c2-f84f-4fa1-a44d-e3ab48a271bd
		summarizeBy: none
		sourceColumn: dv_delivery_task

		annotation SummarizationSetBy = Automatic

	column dependency
		dataType: string
		lineageTag: 727f236b-583c-4b0f-8625-3f54ebd0aa9d
		summarizeBy: none
		sourceColumn: dependency

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: a901120f-6607-40c1-b4db-9a5288f3fde8
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column due_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1ec5149d-236f-450f-8c7f-65cea7f38b64
		summarizeBy: none
		sourceColumn: due_date

		variation Variación
			isDefault
			relationship: 1a88ff37-458e-4624-96d1-abfcc3551c9b
			defaultHierarchy: LocalDateTable_f0ed43b6-a68a-4e5a-85ee-507e8e68eafd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column duration
		dataType: dateTime
		formatString: General Date
		lineageTag: e0cfa820-fa57-4dae-9def-801d546ea818
		summarizeBy: none
		sourceColumn: duration

		variation Variación
			isDefault
			relationship: 8e03fdd3-6eb1-4981-8b14-646b01ec7ef4
			defaultHierarchy: LocalDateTable_5fc442d6-8037-429b-b117-9d98dcf8b8db.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_duration
		dataType: string
		lineageTag: ab055307-0b6b-4df2-aaa6-d5660f66c7bf
		summarizeBy: none
		sourceColumn: dv_duration

		annotation SummarizationSetBy = Automatic

	column effort
		dataType: dateTime
		formatString: General Date
		lineageTag: 8afeac67-0225-428b-a9f7-a637d1c34419
		summarizeBy: none
		sourceColumn: effort

		variation Variación
			isDefault
			relationship: d0de0907-8e15-4a91-b39e-6421f84d337d
			defaultHierarchy: LocalDateTable_862eba7a-ec01-45fa-8a1f-c29b70235d3b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_effort
		dataType: string
		lineageTag: 7bcd7141-ce12-429f-9281-993894d8635b
		summarizeBy: none
		sourceColumn: dv_effort

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: eee83d09-bbc0-42e1-b193-9518d1a49283
		summarizeBy: none
		sourceColumn: end_date

		variation Variación
			isDefault
			relationship: b2983041-332d-4311-9da3-04181286e29e
			defaultHierarchy: LocalDateTable_b9793397-4584-48a4-9fca-448b8fbac6ab.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column end_date_derived_from
		dataType: string
		lineageTag: 039cc1f7-3714-41b7-8744-f014c9ca3bbf
		summarizeBy: none
		sourceColumn: end_date_derived_from

		annotation SummarizationSetBy = Automatic

	column dv_end_date_derived_from
		dataType: string
		lineageTag: ef84ea88-3ec8-4c39-b8b3-0b89077ce180
		summarizeBy: none
		sourceColumn: dv_end_date_derived_from

		annotation SummarizationSetBy = Automatic

	column escalation
		dataType: int64
		formatString: 0
		lineageTag: 363dcef5-5715-4af4-b5e0-98c3a7fa49f9
		summarizeBy: sum
		sourceColumn: escalation

		annotation SummarizationSetBy = Automatic

	column dv_escalation
		dataType: string
		lineageTag: dca6bf42-31e0-4bec-995e-ecbfbc89c3a3
		summarizeBy: none
		sourceColumn: dv_escalation

		annotation SummarizationSetBy = Automatic

	column expected_start
		dataType: dateTime
		formatString: General Date
		lineageTag: e831576a-4404-49d3-90c2-3e771b5b20b8
		summarizeBy: none
		sourceColumn: expected_start

		variation Variación
			isDefault
			relationship: eb0c2d06-885e-4c8c-8262-8fdcb55b524a
			defaultHierarchy: LocalDateTable_f597dd1a-ba81-4b16-9fa6-4cee99141fd2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column follow_up
		dataType: dateTime
		formatString: General Date
		lineageTag: f0865d1d-9124-4a8b-b425-f2f38b367ad5
		summarizeBy: none
		sourceColumn: follow_up

		variation Variación
			isDefault
			relationship: 5c3e9bf3-82ba-49c8-914b-a3280ba94d7d
			defaultHierarchy: LocalDateTable_38fbf666-f50c-4ef4-a625-7c0b8844221d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column group_list
		dataType: string
		lineageTag: 3354cb0d-b8bb-4360-a386-3dd8dfd2aa91
		summarizeBy: none
		sourceColumn: group_list

		annotation SummarizationSetBy = Automatic

	column has_conflict
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4212fc03-66d5-49a0-b270-22944833b014
		summarizeBy: none
		sourceColumn: has_conflict

		annotation SummarizationSetBy = Automatic

	column html_description
		dataType: string
		lineageTag: 19495d7b-d645-46c7-ab05-431ed1999a61
		summarizeBy: none
		sourceColumn: html_description

		annotation SummarizationSetBy = Automatic

	column impact
		dataType: int64
		formatString: 0
		lineageTag: 52dc5cc3-e783-45a3-9663-3742d76e13bc
		summarizeBy: sum
		sourceColumn: impact

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: c1fb91b5-0560-4854-b27b-4f54200cac5a
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column key_milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0a92dbee-5d00-4456-a5e1-138905246bce
		summarizeBy: none
		sourceColumn: key_milestone

		annotation SummarizationSetBy = Automatic

	column knowledge
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8df88417-70a6-4d14-852d-0b351494bc3b
		summarizeBy: none
		sourceColumn: knowledge

		annotation SummarizationSetBy = Automatic

	column level
		dataType: int64
		formatString: 0
		lineageTag: 4a514f58-8bc5-4eb1-88b8-e36d11329cc1
		summarizeBy: sum
		sourceColumn: level

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 5d2e7ba1-c687-4e90-aa50-5a2fbe3e79fb
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column dv_location
		dataType: string
		lineageTag: 746470dd-4fa1-47e5-a59d-3bd2e9b10dd6
		summarizeBy: none
		sourceColumn: dv_location

		annotation SummarizationSetBy = Automatic

	column made_sla
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bebd7a6d-c39a-4568-98d2-175a6468a998
		summarizeBy: none
		sourceColumn: made_sla

		annotation SummarizationSetBy = Automatic

	column milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2c87af22-a388-4019-abdf-f7e340fc8747
		summarizeBy: none
		sourceColumn: milestone

		annotation SummarizationSetBy = Automatic

	column mpp_task_id
		dataType: int64
		formatString: 0
		lineageTag: dd44482e-4e27-49ee-9664-5f429a653e61
		summarizeBy: sum
		sourceColumn: mpp_task_id

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: cf452263-1e5b-4a27-bb62-3449ba1b650c
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 68e97349-2c59-42e1-9f7c-91c50d0bffc9
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: b7b41da9-26f2-4ffb-aae9-1dd7ae8135d9
			defaultHierarchy: LocalDateTable_420e2a30-50b3-4308-8b81-0dfa48807b49.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column opened_by
		dataType: string
		lineageTag: aed74aed-8941-44e1-9040-a30652168ea1
		summarizeBy: none
		sourceColumn: opened_by

		annotation SummarizationSetBy = Automatic

	column dv_opened_by
		dataType: string
		lineageTag: 3aca99a0-6f0e-4de3-a69a-1b83a1dd0ddd
		summarizeBy: none
		sourceColumn: dv_opened_by

		annotation SummarizationSetBy = Automatic

	column opex_cost
		dataType: double
		lineageTag: a25b63e3-c06f-44d0-a347-92fbb1fe9807
		summarizeBy: sum
		sourceColumn: opex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order
		dataType: int64
		formatString: 0
		lineageTag: c14ca156-652b-4a1d-be99-8ece9f58ce8d
		summarizeBy: sum
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	column orig_sys_id
		dataType: string
		lineageTag: 22ef5352-9b9f-49b0-af62-5b3ad714500b
		summarizeBy: none
		sourceColumn: orig_sys_id

		annotation SummarizationSetBy = Automatic

	column dv_orig_sys_id
		dataType: string
		lineageTag: 41e0726a-159a-45d8-b983-b21ba5043dbf
		summarizeBy: none
		sourceColumn: dv_orig_sys_id

		annotation SummarizationSetBy = Automatic

	column orig_top_task_id
		dataType: string
		lineageTag: 6831637c-2cdd-452b-aa41-be5612e0b2e4
		summarizeBy: none
		sourceColumn: orig_top_task_id

		annotation SummarizationSetBy = Automatic

	column dv_orig_top_task_id
		dataType: string
		lineageTag: ffdc8bd5-8e59-49fd-9628-29a44b7611db
		summarizeBy: none
		sourceColumn: dv_orig_top_task_id

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: b75e357c-7603-4d93-9d55-b488eeff3775
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: 29e9f39c-aa8f-45d6-80e9-f40875d4dfa3
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column percent_complete
		dataType: double
		lineageTag: ea240464-dce4-4581-9d0d-94a4593f78ba
		summarizeBy: sum
		sourceColumn: percent_complete

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column phase_type
		dataType: string
		lineageTag: f3fe985d-b07d-4ec3-a1c7-812cf9a520df
		summarizeBy: none
		sourceColumn: phase_type

		annotation SummarizationSetBy = Automatic

	column dv_phase_type
		dataType: string
		lineageTag: 9200c972-78fd-4f43-bd38-5a40c28cf5fc
		summarizeBy: none
		sourceColumn: dv_phase_type

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: int64
		formatString: 0
		lineageTag: 500d0637-8713-415d-a162-15951cb73750
		summarizeBy: sum
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: ed23b67f-0e56-45a9-8367-4a4ad4411fb4
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: 5096453c-cc66-48de-a17a-61bcc23b8336
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column dv_product
		dataType: string
		lineageTag: 48e50baa-9237-4a87-9aad-5cf68eeaf1ad
		summarizeBy: none
		sourceColumn: dv_product

		annotation SummarizationSetBy = Automatic

	column reassignment_count
		dataType: int64
		formatString: 0
		lineageTag: 9ffd3a5b-61a0-484c-9baf-00d384d8b82d
		summarizeBy: sum
		sourceColumn: reassignment_count

		annotation SummarizationSetBy = Automatic

	column rejection_goto
		dataType: string
		lineageTag: 36fa93a6-072c-402c-a617-eb706faab8f8
		summarizeBy: none
		sourceColumn: rejection_goto

		annotation SummarizationSetBy = Automatic

	column dv_rejection_goto
		dataType: string
		lineageTag: 8fb80519-5683-4aad-83a3-ffe16d288552
		summarizeBy: none
		sourceColumn: dv_rejection_goto

		annotation SummarizationSetBy = Automatic

	column relation_applied
		dataType: string
		lineageTag: 4e640039-3f1b-48af-92ee-ef098b908e5a
		summarizeBy: none
		sourceColumn: relation_applied

		annotation SummarizationSetBy = Automatic

	column dv_relation_applied
		dataType: string
		lineageTag: 11687779-e1dd-4fdc-adf3-1f82c7265cd0
		summarizeBy: none
		sourceColumn: dv_relation_applied

		annotation SummarizationSetBy = Automatic

	column remaining_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 3a66be27-c8e9-4b91-ae98-4d897f10a5f6
		summarizeBy: none
		sourceColumn: remaining_duration

		variation Variación
			isDefault
			relationship: 88f4d40e-a563-4af9-bc0c-b88d19c5994e
			defaultHierarchy: LocalDateTable_d46e6a61-eff5-4505-9ea1-0ad0d43a678f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_remaining_duration
		dataType: string
		lineageTag: fda61ba6-1671-48c8-a864-84d97e2a0dab
		summarizeBy: none
		sourceColumn: dv_remaining_duration

		annotation SummarizationSetBy = Automatic

	column remaining_effort
		dataType: dateTime
		formatString: General Date
		lineageTag: 1d633ba6-5366-4b42-96fc-3d0621c8f906
		summarizeBy: none
		sourceColumn: remaining_effort

		variation Variación
			isDefault
			relationship: ae99ab3d-c8e0-4ee8-8a10-fa7e70b29c54
			defaultHierarchy: LocalDateTable_7fdce9f4-037d-4d16-a7ef-acee11760946.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_remaining_effort
		dataType: string
		lineageTag: 0f4955d9-ec9c-4485-9686-918337cc3853
		summarizeBy: none
		sourceColumn: dv_remaining_effort

		annotation SummarizationSetBy = Automatic

	column resource_allocated_cost
		dataType: double
		lineageTag: ebc41f7d-e05f-4142-bb58-58e541b638ca
		summarizeBy: sum
		sourceColumn: resource_allocated_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column resource_planned_cost
		dataType: double
		lineageTag: 24c88994-7f96-460a-846d-f72bd4e2b2f9
		summarizeBy: sum
		sourceColumn: resource_planned_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rollup
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e31cd0a6-94df-4fe6-bfe9-0afe027cf675
		summarizeBy: none
		sourceColumn: rollup

		annotation SummarizationSetBy = Automatic

	column route_reason
		dataType: int64
		formatString: 0
		lineageTag: 56213323-83e6-48fe-afe1-d98b5508c4d3
		summarizeBy: sum
		sourceColumn: route_reason

		annotation SummarizationSetBy = Automatic

	column dv_route_reason
		dataType: string
		lineageTag: a11da439-f74a-4c88-b107-d2506527f69a
		summarizeBy: none
		sourceColumn: dv_route_reason

		annotation SummarizationSetBy = Automatic

	column schedule_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0f7ab9e0-d8ee-4a98-abda-15873be0ab71
		summarizeBy: none
		sourceColumn: schedule_end_date

		variation Variación
			isDefault
			relationship: c722261e-02ff-452a-8a21-200ac1439f5d
			defaultHierarchy: LocalDateTable_28031778-6c10-49cf-ad3d-5feb985e8ef6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column schedule_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 67395ddb-35c6-47a4-8dd0-fc3fd677e048
		summarizeBy: none
		sourceColumn: schedule_start_date

		variation Variación
			isDefault
			relationship: 2a1287c7-43cc-43bc-9308-9c81f4fbefd2
			defaultHierarchy: LocalDateTable_0570b213-1f8e-4211-817e-f7fb6dddda6f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column service_offering
		dataType: string
		lineageTag: 61672922-2797-4768-a679-b23bbc59c87f
		summarizeBy: none
		sourceColumn: service_offering

		annotation SummarizationSetBy = Automatic

	column dv_service_offering
		dataType: string
		lineageTag: f9f02bef-3ad1-466f-b496-0a440dacf949
		summarizeBy: none
		sourceColumn: dv_service_offering

		annotation SummarizationSetBy = Automatic

	column shadow
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6f5e5ba7-0b2b-4819-9a36-395abf533ce9
		summarizeBy: none
		sourceColumn: shadow

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: 15278699-0e31-462e-bb70-422e07e03bc4
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column skills
		dataType: string
		lineageTag: a4f80909-2836-449b-bf85-930050087e15
		summarizeBy: none
		sourceColumn: skills

		annotation SummarizationSetBy = Automatic

	column sla_due
		dataType: dateTime
		formatString: General Date
		lineageTag: 15bf4129-0c1a-415f-8dd3-4fb74fe5d79d
		summarizeBy: none
		sourceColumn: sla_due

		variation Variación
			isDefault
			relationship: 47d5c20f-4848-49e8-92d2-a374c6b4a0d5
			defaultHierarchy: LocalDateTable_b410a054-f39c-4d10-9d65-85034e29bf6e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b595f607-5528-4acf-84f0-19c610e61e41
		summarizeBy: none
		sourceColumn: start_date

		variation Variación
			isDefault
			relationship: 970c6ab0-e367-4fb8-a633-d47f98211286
			defaultHierarchy: LocalDateTable_226f8b2e-12d0-4445-b398-5d6dcea62f40.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column start_date_derived_from
		dataType: string
		lineageTag: a1a048f7-e3be-4bfc-a0ee-211bde060b0c
		summarizeBy: none
		sourceColumn: start_date_derived_from

		annotation SummarizationSetBy = Automatic

	column dv_start_date_derived_from
		dataType: string
		lineageTag: 06151086-a7e8-4bef-b5e9-5187120aa64a
		summarizeBy: none
		sourceColumn: dv_start_date_derived_from

		annotation SummarizationSetBy = Automatic

	column state
		dataType: int64
		formatString: 0
		lineageTag: 738a7f36-df53-4a17-9f93-bad05b5ef714
		summarizeBy: sum
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: e1e61971-6c41-43a1-b7c1-8314c2a8ac3e
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: ad33e4f5-094c-4121-85ef-1abacf91607a
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column dv_status
		dataType: string
		lineageTag: 0a0682b3-a105-48d8-a37b-4a8800192a46
		summarizeBy: none
		sourceColumn: dv_status

		annotation SummarizationSetBy = Automatic

	column sub_tree_root
		dataType: string
		lineageTag: 9ea125c5-1dae-472b-b5f7-f10127dbc277
		summarizeBy: none
		sourceColumn: sub_tree_root

		annotation SummarizationSetBy = Automatic

	column dv_sub_tree_root
		dataType: string
		lineageTag: b7fc84c1-3629-4f82-ad65-d4db1f660d77
		summarizeBy: none
		sourceColumn: dv_sub_tree_root

		annotation SummarizationSetBy = Automatic

	column sys_class_name
		dataType: string
		lineageTag: 94d1bbf8-d02f-424b-9e41-71a20bdcb6d5
		summarizeBy: none
		sourceColumn: sys_class_name

		annotation SummarizationSetBy = Automatic

	column dv_sys_class_name
		dataType: string
		lineageTag: 1872f063-9e21-4608-b808-e2409488a7bb
		summarizeBy: none
		sourceColumn: dv_sys_class_name

		annotation SummarizationSetBy = Automatic

	column sys_created_by
		dataType: string
		lineageTag: c1a9c1e6-238a-4085-82c0-896c48954dd9
		summarizeBy: none
		sourceColumn: sys_created_by

		annotation SummarizationSetBy = Automatic

	column sys_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 7f6d7515-fdfd-4861-ae40-fa7b3cdd21af
		summarizeBy: none
		sourceColumn: sys_created_on

		variation Variación
			isDefault
			relationship: 812f353d-449f-404b-9b5c-2c770c220ed8
			defaultHierarchy: LocalDateTable_2aec0a65-79c5-4c61-b431-fbeb572f885a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column sys_domain
		dataType: string
		lineageTag: a9e13309-bc16-4958-9515-5eaa3e3acc20
		summarizeBy: none
		sourceColumn: sys_domain

		annotation SummarizationSetBy = Automatic

	column sys_domain_path
		dataType: string
		lineageTag: 207bfee3-4ad6-469d-a116-faa40f000c71
		summarizeBy: none
		sourceColumn: sys_domain_path

		annotation SummarizationSetBy = Automatic

	column 'mejora.sys_id'
		dataType: string
		lineageTag: d982e0ba-a621-4a8a-9cf3-04ce64f7a021
		summarizeBy: none
		sourceColumn: mejora.sys_id

		annotation SummarizationSetBy = Automatic

	column sys_mod_count
		dataType: int64
		formatString: 0
		lineageTag: cdc5a4c4-fbb2-432e-8655-5ea8c11e7e43
		summarizeBy: sum
		sourceColumn: sys_mod_count

		annotation SummarizationSetBy = Automatic

	column sys_tags
		dataType: string
		lineageTag: 54d3f48f-a1e2-4171-9bc7-8c2e9db7284b
		summarizeBy: none
		sourceColumn: sys_tags

		annotation SummarizationSetBy = Automatic

	column sys_updated_by
		dataType: string
		lineageTag: fde75320-e9f1-473b-a53a-49211fa1fd7f
		summarizeBy: none
		sourceColumn: sys_updated_by

		annotation SummarizationSetBy = Automatic

	column sys_updated_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 8ec955c0-3018-485e-bfc1-59270a87cc12
		summarizeBy: none
		sourceColumn: sys_updated_on

		variation Variación
			isDefault
			relationship: 9c308838-572f-4232-bd9b-f876b82e9733
			defaultHierarchy: LocalDateTable_50f8cfc3-2f77-4c53-b0da-5a15b8fe81e4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column task
		dataType: string
		lineageTag: df70b583-433b-474e-aa5e-2af3be8a93fd
		summarizeBy: none
		sourceColumn: task

		annotation SummarizationSetBy = Automatic

	column task_effective_number
		dataType: string
		lineageTag: 94e91be4-48eb-4685-bf93-9019a2ebc3b6
		summarizeBy: none
		sourceColumn: task_effective_number

		annotation SummarizationSetBy = Automatic

	column task_for
		dataType: string
		lineageTag: 8d87d347-ac89-454c-9345-2dddf21c5612
		summarizeBy: none
		sourceColumn: task_for

		annotation SummarizationSetBy = Automatic

	column dv_task_for
		dataType: string
		lineageTag: 177c7b4c-bacb-48f0-92d5-f74d9fd7e1d4
		summarizeBy: none
		sourceColumn: dv_task_for

		annotation SummarizationSetBy = Automatic

	column time_card_at_top_task
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2f16f818-92f4-4300-a633-0749757b8ffa
		summarizeBy: none
		sourceColumn: time_card_at_top_task

		annotation SummarizationSetBy = Automatic

	column time_constraint
		dataType: string
		lineageTag: ff20b02d-1982-4d3e-b721-a5fe3e613aff
		summarizeBy: none
		sourceColumn: time_constraint

		annotation SummarizationSetBy = Automatic

	column dv_time_constraint
		dataType: string
		lineageTag: e51b8b68-aced-40a5-84ab-98030502a382
		summarizeBy: none
		sourceColumn: dv_time_constraint

		annotation SummarizationSetBy = Automatic

	column time_worked
		dataType: dateTime
		formatString: General Date
		lineageTag: 434cbd2a-f908-4cc5-9a83-124ebd311e34
		summarizeBy: none
		sourceColumn: time_worked

		variation Variación
			isDefault
			relationship: 649d52e8-f44d-4f8a-933a-495de8018875
			defaultHierarchy: LocalDateTable_6db7fde0-e587-4458-97f0-9d127b83c84f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_time_worked
		dataType: string
		lineageTag: a3a6b054-e800-4fcc-a021-9f2f30e60e04
		summarizeBy: none
		sourceColumn: dv_time_worked

		annotation SummarizationSetBy = Automatic

	column top_portfolio
		dataType: string
		lineageTag: f56ab199-fadd-40d8-b555-c5a1b8df943f
		summarizeBy: none
		sourceColumn: top_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_top_portfolio
		dataType: string
		lineageTag: 0b2bfcae-d367-4451-9190-a74ed5f5e436
		summarizeBy: none
		sourceColumn: dv_top_portfolio

		annotation SummarizationSetBy = Automatic

	column top_program
		dataType: string
		lineageTag: 057862aa-e157-4e9f-b183-1bf97e887fa3
		summarizeBy: none
		sourceColumn: top_program

		annotation SummarizationSetBy = Automatic

	column dv_top_program
		dataType: string
		lineageTag: 5a3e95f1-669a-45bb-b50c-531832f7856f
		summarizeBy: none
		sourceColumn: dv_top_program

		annotation SummarizationSetBy = Automatic

	column top_task
		dataType: string
		lineageTag: 172d11f0-7a20-464f-baee-9945468172b0
		summarizeBy: none
		sourceColumn: top_task

		annotation SummarizationSetBy = Automatic

	column dv_top_task
		dataType: string
		lineageTag: 0dfef762-21ca-4447-ab6f-f977136847fa
		summarizeBy: none
		sourceColumn: dv_top_task

		annotation SummarizationSetBy = Automatic

	column u_acciona_priority
		dataType: int64
		formatString: 0
		lineageTag: 069273d3-defc-4c8e-b6e0-f549202fce38
		summarizeBy: sum
		sourceColumn: u_acciona_priority

		annotation SummarizationSetBy = Automatic

	column u_business_application
		dataType: string
		lineageTag: 080167ee-9f16-4993-9223-20f4e6e3bd85
		summarizeBy: none
		sourceColumn: u_business_application

		annotation SummarizationSetBy = Automatic

	column dv_u_business_application
		dataType: string
		lineageTag: 9c6dacc0-28ac-4ac3-8e9f-6e32877997fb
		summarizeBy: none
		sourceColumn: dv_u_business_application

		annotation SummarizationSetBy = Automatic

	column u_business_line
		dataType: string
		lineageTag: 2e551caa-2aa9-4fb5-8290-b58cc73a42fb
		summarizeBy: none
		sourceColumn: u_business_line

		annotation SummarizationSetBy = Automatic

	column dv_u_business_line
		dataType: string
		lineageTag: 5ab92ff9-e42e-44ea-be7d-365838ea335d
		summarizeBy: none
		sourceColumn: dv_u_business_line

		annotation SummarizationSetBy = Automatic

	column u_catalog
		dataType: string
		lineageTag: 93d239f7-17de-409c-abe8-c15bc8b8e003
		summarizeBy: none
		sourceColumn: u_catalog

		annotation SummarizationSetBy = Automatic

	column dv_u_catalog
		dataType: string
		lineageTag: de023944-cb08-41de-bbe0-1786b2b0bd61
		summarizeBy: none
		sourceColumn: dv_u_catalog

		annotation SummarizationSetBy = Automatic

	column u_department
		dataType: string
		lineageTag: d65fbc51-19ab-47c1-83f0-258e8d7e6911
		summarizeBy: none
		sourceColumn: u_department

		annotation SummarizationSetBy = Automatic

	column dv_u_department
		dataType: string
		lineageTag: a8a64790-ed6f-4ae8-8efe-7c394e6bac70
		summarizeBy: none
		sourceColumn: dv_u_department

		annotation SummarizationSetBy = Automatic

	column u_execution_type
		dataType: string
		lineageTag: 1471726b-6df0-4d02-aa70-26c276fb7a7a
		summarizeBy: none
		sourceColumn: u_execution_type

		annotation SummarizationSetBy = Automatic

	column dv_u_execution_type
		dataType: string
		lineageTag: e17662ac-1a7f-4338-8e3b-9133201e4bac
		summarizeBy: none
		sourceColumn: dv_u_execution_type

		annotation SummarizationSetBy = Automatic

	column u_external_vendor
		dataType: string
		lineageTag: c730f268-af5b-45fe-9f4c-4af2d1948198
		summarizeBy: none
		sourceColumn: u_external_vendor

		annotation SummarizationSetBy = Automatic

	column dv_u_external_vendor
		dataType: string
		lineageTag: a29c96a4-dcf2-41ae-911a-94928aea27d3
		summarizeBy: none
		sourceColumn: dv_u_external_vendor

		annotation SummarizationSetBy = Automatic

	column u_metal
		dataType: string
		lineageTag: f06ae7d4-7536-410f-b3d4-ec56efb17e06
		summarizeBy: none
		sourceColumn: u_metal

		annotation SummarizationSetBy = Automatic

	column dv_u_metal
		dataType: string
		lineageTag: 316a7399-b3e2-43e7-be38-747e058f25ed
		summarizeBy: none
		sourceColumn: dv_u_metal

		annotation SummarizationSetBy = Automatic

	column u_phone
		dataType: string
		lineageTag: 13ee0384-4a92-4760-a9a9-739220c08c9e
		summarizeBy: none
		sourceColumn: u_phone

		annotation SummarizationSetBy = Automatic

	column u_previous_groups
		dataType: string
		lineageTag: 3a0203a3-5114-4016-8535-0a4ef61e465c
		summarizeBy: none
		sourceColumn: u_previous_groups

		annotation SummarizationSetBy = Automatic

	column u_progress
		dataType: double
		lineageTag: ac6a2ccd-cc24-4b1c-8fd0-02ff020b87f6
		summarizeBy: sum
		sourceColumn: u_progress

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_ref_country
		dataType: string
		lineageTag: fdd0c15a-19e2-43ef-b157-1332da16bf7c
		summarizeBy: none
		sourceColumn: u_ref_country

		annotation SummarizationSetBy = Automatic

	column dv_u_ref_country
		dataType: string
		lineageTag: a4b7be5a-f6a0-4e06-b969-810ca83b37e5
		summarizeBy: none
		sourceColumn: dv_u_ref_country

		annotation SummarizationSetBy = Automatic

	column u_responded
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0de29b17-4616-4381-abc8-f20b3a09ce77
		summarizeBy: none
		sourceColumn: u_responded

		annotation SummarizationSetBy = Automatic

	column u_size
		dataType: string
		lineageTag: b30c99e7-44d8-4e8e-bec5-14049517888e
		summarizeBy: none
		sourceColumn: u_size

		annotation SummarizationSetBy = Automatic

	column dv_u_size
		dataType: string
		lineageTag: 4f5e56e4-ccee-41c4-b5af-5ed5652b2bd6
		summarizeBy: none
		sourceColumn: dv_u_size

		annotation SummarizationSetBy = Automatic

	column u_state_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 37771209-bfee-4872-97f0-c59d10c2b5bc
		summarizeBy: none
		sourceColumn: u_state_date

		variation Variación
			isDefault
			relationship: 647043c6-b754-47f6-98cb-a52c2a076c55
			defaultHierarchy: LocalDateTable_a60a534f-fe04-409f-b432-89210314e5ef.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column universal_request
		dataType: string
		lineageTag: 82299cc4-18ac-483d-8e3c-98356821c153
		summarizeBy: none
		sourceColumn: universal_request

		annotation SummarizationSetBy = Automatic

	column dv_universal_request
		dataType: string
		lineageTag: 03467eee-37d5-4bb1-bfef-dc726e271b19
		summarizeBy: none
		sourceColumn: dv_universal_request

		annotation SummarizationSetBy = Automatic

	column upon_approval
		dataType: string
		lineageTag: 8351ef1c-eb4e-4e1e-924f-df37d654bac1
		summarizeBy: none
		sourceColumn: upon_approval

		annotation SummarizationSetBy = Automatic

	column dv_upon_approval
		dataType: string
		lineageTag: 902c4be8-65e4-4101-a9ab-c35c94b137c8
		summarizeBy: none
		sourceColumn: dv_upon_approval

		annotation SummarizationSetBy = Automatic

	column upon_reject
		dataType: string
		lineageTag: c3b4a9e1-537e-4542-bee0-5c66c1f3b806
		summarizeBy: none
		sourceColumn: upon_reject

		annotation SummarizationSetBy = Automatic

	column dv_upon_reject
		dataType: string
		lineageTag: 04ab14ff-a502-48ba-9dc4-d00e4250fb35
		summarizeBy: none
		sourceColumn: dv_upon_reject

		annotation SummarizationSetBy = Automatic

	column urgency
		dataType: int64
		formatString: 0
		lineageTag: 3deaf1fd-3d4e-47a4-a775-6b3c91f036cd
		summarizeBy: sum
		sourceColumn: urgency

		annotation SummarizationSetBy = Automatic

	column dv_urgency
		dataType: string
		lineageTag: 18ca90dd-ae3d-4e95-9aa6-6c2dbd8bd265
		summarizeBy: none
		sourceColumn: dv_urgency

		annotation SummarizationSetBy = Automatic

	column user_input
		dataType: string
		lineageTag: 732eb39a-b364-4df3-b0e4-1ee74f04bd1e
		summarizeBy: none
		sourceColumn: user_input

		annotation SummarizationSetBy = Automatic

	column variables
		dataType: string
		lineageTag: 8aeb31d2-e877-49ec-8b79-ddc1306d766e
		summarizeBy: none
		sourceColumn: variables

		annotation SummarizationSetBy = Automatic

	column version
		dataType: int64
		formatString: 0
		lineageTag: c83ca0c0-747f-4f6c-9dea-ddff7ea08780
		summarizeBy: sum
		sourceColumn: version

		annotation SummarizationSetBy = Automatic

	column watch_list
		dataType: string
		lineageTag: 91cce701-8608-416e-9b1e-ef3d82d02054
		summarizeBy: none
		sourceColumn: watch_list

		annotation SummarizationSetBy = Automatic

	column wbs
		dataType: string
		lineageTag: 4e5c7542-172f-4f8c-b8e5-881f7faae5ac
		summarizeBy: none
		sourceColumn: wbs

		annotation SummarizationSetBy = Automatic

	column wbs_order
		dataType: int64
		formatString: 0
		lineageTag: 897edf21-b6c3-4f5e-8704-51bacc8d7123
		summarizeBy: sum
		sourceColumn: wbs_order

		annotation SummarizationSetBy = Automatic

	column wf_activity
		dataType: string
		lineageTag: ca40ddb1-7e91-4bfb-8f8a-60e7af20842d
		summarizeBy: none
		sourceColumn: wf_activity

		annotation SummarizationSetBy = Automatic

	column dv_wf_activity
		dataType: string
		lineageTag: 9e71d82b-73cd-405a-a04a-22003233274d
		summarizeBy: none
		sourceColumn: dv_wf_activity

		annotation SummarizationSetBy = Automatic

	column work_cost
		dataType: double
		lineageTag: e1221a1d-44e9-44f1-a1bb-f0481190fb67
		summarizeBy: sum
		sourceColumn: work_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column work_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 04132e62-7dae-468b-ad7a-3a3c20c8b448
		summarizeBy: none
		sourceColumn: work_duration

		variation Variación
			isDefault
			relationship: 083afb41-3d32-4cf7-8f37-32a0014f56aa
			defaultHierarchy: LocalDateTable_7047474b-4bcc-4802-96c6-b914fc6caa69.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_work_duration
		dataType: string
		lineageTag: 9830f93b-178a-4a79-be50-3587632a511b
		summarizeBy: none
		sourceColumn: dv_work_duration

		annotation SummarizationSetBy = Automatic

	column work_effort
		dataType: dateTime
		formatString: General Date
		lineageTag: f7a2bee4-ce9c-45e3-9ae5-e98beff43806
		summarizeBy: none
		sourceColumn: work_effort

		variation Variación
			isDefault
			relationship: 5395e816-636f-4c6d-9c96-b0ece019c931
			defaultHierarchy: LocalDateTable_3b3f88a1-1eaa-4f20-8e12-36f459fec2cc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_work_effort
		dataType: string
		lineageTag: 4558bf9e-4842-405d-823c-405c4289d468
		summarizeBy: none
		sourceColumn: dv_work_effort

		annotation SummarizationSetBy = Automatic

	column work_end
		dataType: dateTime
		formatString: General Date
		lineageTag: 99a58899-34b3-4e7a-a213-e876af53af6b
		summarizeBy: none
		sourceColumn: work_end

		variation Variación
			isDefault
			relationship: 3489cf7d-c92f-40e4-b390-dee63ebdf9fa
			defaultHierarchy: LocalDateTable_954aa0e2-6dd7-47ee-b6a2-c3422a083d48.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column work_notes
		dataType: string
		lineageTag: 90ef57c6-aee4-4dcf-ac69-73d6bf1a4625
		summarizeBy: none
		sourceColumn: work_notes

		annotation SummarizationSetBy = Automatic

	column work_notes_list
		dataType: string
		lineageTag: 5f1fc545-26d0-4553-a49e-4dcc1a18b3c5
		summarizeBy: none
		sourceColumn: work_notes_list

		annotation SummarizationSetBy = Automatic

	column work_start
		dataType: dateTime
		formatString: General Date
		lineageTag: ebbb0675-4000-4704-beaf-c889c994c982
		summarizeBy: none
		sourceColumn: work_start

		variation Variación
			isDefault
			relationship: 57cdedbc-cd24-499b-9374-1a783d36dbd4
			defaultHierarchy: LocalDateTable_d0248124-f89d-4db2-b0db-8a916b2eeddf.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column UnionConDemanda
		dataType: string
		lineageTag: ff1bb85e-8ea0-4870-8f9a-f9e318e1891d
		summarizeBy: none
		sourceColumn: UnionConDemanda

		annotation SummarizationSetBy = Automatic

	partition 'SERV_NOW_EN V_rm_enhancement' = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("QECCDWH.ACCIONA.INT:60001"),
				    DWH = Origen{[Name="DWH"]}[Data],
				    SERV_NOW_EN_V_rm_enhancement = DWH{[Schema="SERV_NOW_EN",Item="V_rm_enhancement"]}[Data],
				    #"Consultas combinadas" = Table.NestedJoin(SERV_NOW_EN_V_rm_enhancement, {"sys_id"}, Demand_Details_Enhancement, {"related_records"}, "Demandas", JoinKind.LeftOuter),
				    #"Se expandió Demandas" = Table.ExpandTableColumn(#"Consultas combinadas", "Demandas", {"sys_id"}, {"Demandas.sys_id"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Se expandió Demandas",{{"sys_id", "mejora.sys_id"}, {"Demandas.sys_id", "UnionConDemanda"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

