table 'Tareas de Subproyecto'
	lineageTag: 6f4485a8-84c7-49fd-828c-c4bd1a4c8d5d

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8605abc6-e5ca-49c9-82a9-6373f01dfc0f
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column activity_due
		dataType: dateTime
		formatString: General Date
		lineageTag: d6eaa219-cad9-4a21-8471-6a608101a871
		summarizeBy: none
		sourceColumn: activity_due

		variation Variación
			isDefault
			relationship: 7a4cc80e-9681-42e8-8a8d-9355bac5be3d
			defaultHierarchy: LocalDateTable_7cc87f56-01be-468b-a7d2-a30a454fb3a8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column actual_benefits
		dataType: double
		lineageTag: ad46a88a-c172-4170-b53f-107ea8d84c3b
		summarizeBy: sum
		sourceColumn: actual_benefits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column additional_assignee_list
		dataType: string
		lineageTag: 226e76e8-a671-4f5a-bf74-b9928abed825
		summarizeBy: none
		sourceColumn: additional_assignee_list

		annotation SummarizationSetBy = Automatic

	column agile_rollup_dates
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b7c4df48-6ad0-4e1d-8cca-7395fd074176
		summarizeBy: none
		sourceColumn: agile_rollup_dates

		annotation SummarizationSetBy = Automatic

	column allow_dates_outside_schedule
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c0cfd6c2-3ed4-4920-bbfe-3814a5587477
		summarizeBy: none
		sourceColumn: allow_dates_outside_schedule

		annotation SummarizationSetBy = Automatic

	column approval
		dataType: string
		lineageTag: 6a108cc4-c5b2-47fd-b55d-a0527466fb67
		summarizeBy: none
		sourceColumn: approval

		annotation SummarizationSetBy = Automatic

	column dv_approval
		dataType: string
		lineageTag: 565ffd34-00aa-4a24-836d-e109d0580c7e
		summarizeBy: none
		sourceColumn: dv_approval

		annotation SummarizationSetBy = Automatic

	column approval_history
		dataType: string
		lineageTag: b6f0f621-83a1-4a78-9326-2938eb7bb0fb
		summarizeBy: none
		sourceColumn: approval_history

		annotation SummarizationSetBy = Automatic

	column approval_set
		dataType: dateTime
		formatString: General Date
		lineageTag: ffd26c8a-44f6-43ee-87d8-ce07fb30a08e
		summarizeBy: none
		sourceColumn: approval_set

		variation Variación
			isDefault
			relationship: e0ddef3d-5e28-4837-8687-782e373b920e
			defaultHierarchy: LocalDateTable_42d4329d-952f-4b70-b6d3-9a256b3f7215.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column assigned_to
		dataType: string
		lineageTag: 820ad064-a76c-48fe-9451-80320c6b7c0c
		summarizeBy: none
		sourceColumn: assigned_to

		annotation SummarizationSetBy = Automatic

	column dv_assigned_to
		dataType: string
		lineageTag: 97e29e53-0922-4976-9954-1615925c7900
		summarizeBy: none
		sourceColumn: dv_assigned_to

		annotation SummarizationSetBy = Automatic

	column assignment_group
		dataType: string
		lineageTag: 6c66653e-2fa5-42c4-868b-e0a680075401
		summarizeBy: none
		sourceColumn: assignment_group

		annotation SummarizationSetBy = Automatic

	column dv_assignment_group
		dataType: string
		lineageTag: f75f9a38-df6d-4bb3-98f1-8480dbeb9137
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column benefits
		dataType: double
		lineageTag: d28bf61b-c1e8-4ad7-ab20-699d402ab4d8
		summarizeBy: sum
		sourceColumn: benefits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column budget_cost
		dataType: double
		lineageTag: 8de3024c-5259-42e9-93f2-4c2421d6fb0b
		summarizeBy: sum
		sourceColumn: budget_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column business_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 5a1acbec-fba3-44bc-85d0-fb8983b98b78
		summarizeBy: none
		sourceColumn: business_duration

		variation Variación
			isDefault
			relationship: 30fdf8d1-9113-45f8-9c00-2e9772cf9ce8
			defaultHierarchy: LocalDateTable_dcc50680-17f1-46a3-a2e8-a92fb4aef128.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_business_duration
		dataType: string
		lineageTag: 42973a4a-dd4f-4a7e-86ad-ff8496d9f29b
		summarizeBy: none
		sourceColumn: dv_business_duration

		annotation SummarizationSetBy = Automatic

	column business_service
		dataType: string
		lineageTag: 46cadda1-20e5-4fac-aaaf-b88db3cae96f
		summarizeBy: none
		sourceColumn: business_service

		annotation SummarizationSetBy = Automatic

	column dv_business_service
		dataType: string
		lineageTag: dd6b64e2-751e-4611-bcac-02cef7ebd4c9
		summarizeBy: none
		sourceColumn: dv_business_service

		annotation SummarizationSetBy = Automatic

	column calculation_type
		dataType: string
		lineageTag: 6451a217-a8ba-4860-93e9-9fa542fde227
		summarizeBy: none
		sourceColumn: calculation_type

		annotation SummarizationSetBy = Automatic

	column dv_calculation_type
		dataType: string
		lineageTag: c540a2a3-7c0f-4f00-823a-d841d4b2e2ee
		summarizeBy: none
		sourceColumn: dv_calculation_type

		annotation SummarizationSetBy = Automatic

	column calendar_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: d2f11865-7bd3-4de1-9d31-bf0c344394d7
		summarizeBy: none
		sourceColumn: calendar_duration

		variation Variación
			isDefault
			relationship: 24966868-6660-41d5-abdd-2398f1ee495a
			defaultHierarchy: LocalDateTable_92eff153-437d-4a64-8072-7c5a793095be.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_calendar_duration
		dataType: string
		lineageTag: 846b9959-3b6a-4c6c-96b9-4580224b9f88
		summarizeBy: none
		sourceColumn: dv_calendar_duration

		annotation SummarizationSetBy = Automatic

	column capex_cost
		dataType: double
		lineageTag: a3a1fe53-6bb3-48fb-bfde-d285a7af8193
		summarizeBy: sum
		sourceColumn: capex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column close_notes
		dataType: string
		lineageTag: fe8511f0-8530-4ce6-be4f-c34ae3a06008
		summarizeBy: none
		sourceColumn: close_notes

		annotation SummarizationSetBy = Automatic

	column closed_at
		dataType: dateTime
		formatString: Short Date
		lineageTag: 17b7b468-15a5-4966-bbd0-523242eea6fa
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: 532bf9a0-17d9-4e0b-b495-1cdb652df0c5
			defaultHierarchy: LocalDateTable_5a694d38-6fdb-4cff-874b-44513764a416.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column closed_by
		dataType: string
		lineageTag: 7dec84bf-1032-447f-9b71-3de592927e3b
		summarizeBy: none
		sourceColumn: closed_by

		annotation SummarizationSetBy = Automatic

	column dv_closed_by
		dataType: string
		lineageTag: 1c71fbdd-eee5-4722-a5e7-cd3e1062889a
		summarizeBy: none
		sourceColumn: dv_closed_by

		annotation SummarizationSetBy = Automatic

	column cmdb_ci
		dataType: string
		lineageTag: a934c9df-5893-484a-bb19-579e4c458097
		summarizeBy: none
		sourceColumn: cmdb_ci

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci
		dataType: string
		lineageTag: f38f30a4-9cb2-4af8-a201-9594c764e863
		summarizeBy: none
		sourceColumn: dv_cmdb_ci

		annotation SummarizationSetBy = Automatic

	column cmdb_ci_business_app
		dataType: string
		lineageTag: 2962ceb7-6bab-4985-b7fa-87a8593440ba
		summarizeBy: none
		sourceColumn: cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci_business_app
		dataType: string
		lineageTag: c631a032-e6d1-43db-af7f-2a6e06d3c8d2
		summarizeBy: none
		sourceColumn: dv_cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column comments
		dataType: string
		lineageTag: 70d922ad-4f2d-45dd-bcce-1215fde3bebd
		summarizeBy: none
		sourceColumn: comments

		annotation SummarizationSetBy = Automatic

	column comments_and_work_notes
		dataType: string
		lineageTag: 2bea0123-a5a1-4f7a-b2a2-c385e5c99bc6
		summarizeBy: none
		sourceColumn: comments_and_work_notes

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 5605c03f-9c3f-4a09-a5df-471e210a401a
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column dv_company
		dataType: string
		lineageTag: cf7daa92-1c0a-4271-8cdb-5374e3ac9870
		summarizeBy: none
		sourceColumn: dv_company

		annotation SummarizationSetBy = Automatic

	column constraint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 27891c69-986d-4ca8-bbe4-de3debce8a69
		summarizeBy: none
		sourceColumn: constraint_date

		variation Variación
			isDefault
			relationship: cf1da335-f459-4879-93cc-ac73ac67b83f
			defaultHierarchy: LocalDateTable_035857ad-5def-4321-a06d-ad8aac939b67.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column contact_type
		dataType: string
		lineageTag: 09786934-4aaa-4110-a654-bbee91023879
		summarizeBy: none
		sourceColumn: contact_type

		annotation SummarizationSetBy = Automatic

	column dv_contact_type
		dataType: string
		lineageTag: 9e5585c4-3570-4044-8518-3d268fd0d214
		summarizeBy: none
		sourceColumn: dv_contact_type

		annotation SummarizationSetBy = Automatic

	column correlation_display
		dataType: string
		lineageTag: 43ce880d-8a1d-4698-80dd-527985920494
		summarizeBy: none
		sourceColumn: correlation_display

		annotation SummarizationSetBy = Automatic

	column correlation_id
		dataType: string
		lineageTag: 048404de-d7ce-4fda-ae33-2f85db730a7f
		summarizeBy: none
		sourceColumn: correlation_id

		annotation SummarizationSetBy = Automatic

	column cost
		dataType: double
		lineageTag: 23fcde1a-fc22-4466-af1a-5c3f49d48adb
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column critical_path
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0f5f47c2-face-4d69-a4ec-40d06380de31
		summarizeBy: none
		sourceColumn: critical_path

		annotation SummarizationSetBy = Automatic

	column delivery_plan
		dataType: string
		lineageTag: f95feecb-b664-447d-8009-a265344fdb7f
		summarizeBy: none
		sourceColumn: delivery_plan

		annotation SummarizationSetBy = Automatic

	column dv_delivery_plan
		dataType: string
		lineageTag: 512afab0-c598-448a-9319-a2b3ea449091
		summarizeBy: none
		sourceColumn: dv_delivery_plan

		annotation SummarizationSetBy = Automatic

	column delivery_task
		dataType: string
		lineageTag: 9a6ea259-650a-41e6-b711-bf278ce342e5
		summarizeBy: none
		sourceColumn: delivery_task

		annotation SummarizationSetBy = Automatic

	column dv_delivery_task
		dataType: string
		lineageTag: 83ca78a2-c895-41da-a22a-2f13dfbd1a05
		summarizeBy: none
		sourceColumn: dv_delivery_task

		annotation SummarizationSetBy = Automatic

	column dependency
		dataType: string
		lineageTag: 1351c91c-d1f5-4100-9aa3-b45fb8fb0aba
		summarizeBy: none
		sourceColumn: dependency

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 647a9d35-c76e-4e31-ac8a-9fef96f72205
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column due_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f7889fa1-6d40-44a9-98e4-c14efc900cc5
		summarizeBy: none
		sourceColumn: due_date

		variation Variación
			isDefault
			relationship: 5c50243a-b0c6-4c8d-a4b7-773dda183547
			defaultHierarchy: LocalDateTable_a09f0c57-12ff-4c05-a7aa-cc1bb97c4657.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column duration
		dataType: dateTime
		formatString: General Date
		lineageTag: fd821554-b1a5-4c9f-ad06-a7b18279655a
		summarizeBy: none
		sourceColumn: duration

		variation Variación
			isDefault
			relationship: fe41baaa-d29f-4c19-838c-085405d5e1a8
			defaultHierarchy: LocalDateTable_a8b1700f-0915-46c8-857c-3ea2226889bb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_duration
		dataType: string
		lineageTag: 2d106402-3ab4-4c33-bfd6-4e2fc48e010c
		summarizeBy: none
		sourceColumn: dv_duration

		annotation SummarizationSetBy = Automatic

	column effort
		dataType: dateTime
		formatString: General Date
		lineageTag: 8c5e3928-2286-4197-a23d-0fd841b4d795
		summarizeBy: none
		sourceColumn: effort

		variation Variación
			isDefault
			relationship: 06eb7444-2d92-444b-a8bc-97233e80126c
			defaultHierarchy: LocalDateTable_0b8e1d8f-721e-4d71-bf2e-22c53fd3418b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_effort
		dataType: string
		lineageTag: de21e87f-ddae-435d-8721-37638dabbbd7
		summarizeBy: none
		sourceColumn: dv_effort

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 71a62f07-1ecf-4b6b-8639-d1c35238fb88
		summarizeBy: none
		sourceColumn: end_date

		variation Variación
			isDefault
			relationship: 4e3bd157-b17d-4585-81a3-70cb5b363fc6
			defaultHierarchy: LocalDateTable_9137f436-d238-4d96-8903-236db6b951e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column end_date_derived_from
		dataType: string
		lineageTag: 9e6233df-224d-4dae-ae69-5d17904c32cd
		summarizeBy: none
		sourceColumn: end_date_derived_from

		annotation SummarizationSetBy = Automatic

	column dv_end_date_derived_from
		dataType: string
		lineageTag: c9b6be38-7794-4dfe-91f1-779f55f3a097
		summarizeBy: none
		sourceColumn: dv_end_date_derived_from

		annotation SummarizationSetBy = Automatic

	column end_sprint
		dataType: string
		lineageTag: 4172543d-4d5c-4ab7-87bd-b41591f92929
		summarizeBy: none
		sourceColumn: end_sprint

		annotation SummarizationSetBy = Automatic

	column dv_end_sprint
		dataType: string
		lineageTag: 3f31103c-6477-4a1d-86ab-2807d75ab2cd
		summarizeBy: none
		sourceColumn: dv_end_sprint

		annotation SummarizationSetBy = Automatic

	column escalation
		dataType: int64
		formatString: 0
		lineageTag: d6165a02-7f93-40f3-9199-0f0f3b774335
		summarizeBy: sum
		sourceColumn: escalation

		annotation SummarizationSetBy = Automatic

	column dv_escalation
		dataType: string
		lineageTag: 909a1ebb-2210-434e-ba6a-ca0abbfc1e7d
		summarizeBy: none
		sourceColumn: dv_escalation

		annotation SummarizationSetBy = Automatic

	column expected_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 2cc3796d-82d0-4dd2-89b4-1afd4b9bcc2b
		summarizeBy: none
		sourceColumn: expected_start

		variation Variación
			isDefault
			relationship: 1933cbf0-f7ee-4458-abef-65234dd6e205
			defaultHierarchy: LocalDateTable_de75457d-bbe4-4e6b-ae62-f584ae637a3c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column follow_up
		dataType: dateTime
		formatString: General Date
		lineageTag: 31d62b49-14cf-4ad0-afab-0d823e9f2e2b
		summarizeBy: none
		sourceColumn: follow_up

		variation Variación
			isDefault
			relationship: d8e2df41-d3b1-4eba-9f85-526292249a2c
			defaultHierarchy: LocalDateTable_6b94050c-d4b0-4811-b4aa-734feaf04c90.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column group_list
		dataType: string
		lineageTag: da01f477-3c2b-4dac-8b1c-2ec663efa21c
		summarizeBy: none
		sourceColumn: group_list

		annotation SummarizationSetBy = Automatic

	column has_conflict
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d5d6b734-137b-474c-8601-f2bdec873875
		summarizeBy: none
		sourceColumn: has_conflict

		annotation SummarizationSetBy = Automatic

	column html_description
		dataType: string
		lineageTag: d179b966-e373-4b5f-bef7-4daad2e11cce
		summarizeBy: none
		sourceColumn: html_description

		annotation SummarizationSetBy = Automatic

	column impact
		dataType: int64
		formatString: 0
		lineageTag: 029330d4-b86d-4bc0-8519-c8fce4c3c63b
		summarizeBy: sum
		sourceColumn: impact

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: 50ca573e-0047-45e6-b8b0-69a1cb1ee16b
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column key_milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c396072a-5290-40ab-b917-111c915fef66
		summarizeBy: none
		sourceColumn: key_milestone

		annotation SummarizationSetBy = Automatic

	column knowledge
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b1c29346-8133-474c-91bd-efe639dbeb68
		summarizeBy: none
		sourceColumn: knowledge

		annotation SummarizationSetBy = Automatic

	column level
		dataType: int64
		formatString: 0
		lineageTag: e6a978a0-9b03-407e-b159-c78e75e87809
		summarizeBy: sum
		sourceColumn: level

		annotation SummarizationSetBy = Automatic

	column link
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 11e72b2d-b72b-4c83-bb32-1b46c62db4f5
		summarizeBy: none
		sourceColumn: link

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 581102fe-8b6a-46a0-b1a1-ac8afc76bf79
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column dv_location
		dataType: string
		lineageTag: cdc473c4-ae5f-4f70-8715-8b7e7d0a0631
		summarizeBy: none
		sourceColumn: dv_location

		annotation SummarizationSetBy = Automatic

	column made_sla
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 879fd5c3-61bb-4ecb-a0e9-76c5bbda657c
		summarizeBy: none
		sourceColumn: made_sla

		annotation SummarizationSetBy = Automatic

	column milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9ffaa1d9-14b1-439d-87c7-1425d20d3b7c
		summarizeBy: none
		sourceColumn: milestone

		annotation SummarizationSetBy = Automatic

	column mpp_task_id
		dataType: int64
		formatString: 0
		lineageTag: ef1a0dbe-35ca-456a-a47e-a6a56e071e00
		summarizeBy: sum
		sourceColumn: mpp_task_id

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: 1eb0c520-29bb-4581-a26c-c67704c110d1
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: Short Date
		lineageTag: eb9e20a4-3205-48ed-84fd-6de45a788844
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: 4fe964cf-b088-4d1c-a9b9-97cf23546865
			defaultHierarchy: LocalDateTable_99684b52-9b03-4ef6-a607-800b4818baae.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column opened_by
		dataType: string
		lineageTag: d15f0e73-fb13-4aac-b539-9e174a4e838a
		summarizeBy: none
		sourceColumn: opened_by

		annotation SummarizationSetBy = Automatic

	column dv_opened_by
		dataType: string
		lineageTag: 9cf36a2f-26df-4e13-bc85-5b6172dc60bd
		summarizeBy: none
		sourceColumn: dv_opened_by

		annotation SummarizationSetBy = Automatic

	column opex_cost
		dataType: double
		lineageTag: 5640c5db-7d52-4aae-96da-a142961a1a20
		summarizeBy: sum
		sourceColumn: opex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order
		dataType: int64
		formatString: 0
		lineageTag: a3d2cd14-feab-4494-ac60-ece55d618247
		summarizeBy: sum
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	column orig_sys_id
		dataType: string
		lineageTag: c679bc34-2afc-4bd9-a63f-f3c4e29351b8
		summarizeBy: none
		sourceColumn: orig_sys_id

		annotation SummarizationSetBy = Automatic

	column dv_orig_sys_id
		dataType: string
		lineageTag: 0ee27339-ac76-4bb3-90bf-b67bfb79edc9
		summarizeBy: none
		sourceColumn: dv_orig_sys_id

		annotation SummarizationSetBy = Automatic

	column orig_top_task_id
		dataType: string
		lineageTag: eb85ed25-a223-4de6-a223-7b651cfb4691
		summarizeBy: none
		sourceColumn: orig_top_task_id

		annotation SummarizationSetBy = Automatic

	column dv_orig_top_task_id
		dataType: string
		lineageTag: 151b12eb-a263-4eb8-95cf-8d61fcddf78a
		summarizeBy: none
		sourceColumn: dv_orig_top_task_id

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: e83c9f3f-d4a3-4ac5-835f-1f208703cf85
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: 91e604bb-58e2-4692-82e8-f2bc0c0f80e4
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column percent_complete
		dataType: double
		lineageTag: 9f204607-f653-41d6-833e-3400c335f720
		summarizeBy: sum
		sourceColumn: percent_complete

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column phase_type
		dataType: string
		lineageTag: ad5fc3a9-7b5a-42a4-8a37-fe132251c263
		summarizeBy: none
		sourceColumn: phase_type

		annotation SummarizationSetBy = Automatic

	column dv_phase_type
		dataType: string
		lineageTag: 970f355f-c4c6-4e90-bbce-cc5d4d977d18
		summarizeBy: none
		sourceColumn: dv_phase_type

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: int64
		formatString: 0
		lineageTag: d4cfb94e-b7f0-4edb-b2b9-f8544c229ee1
		summarizeBy: sum
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: d43fce1e-63e4-45fe-8fa0-8df80fd2b8a9
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column project
		dataType: string
		lineageTag: 1cf1d754-2354-45f0-962e-51fdbe395792
		summarizeBy: none
		sourceColumn: project

		annotation SummarizationSetBy = Automatic

	column reassignment_count
		dataType: int64
		formatString: 0
		lineageTag: 03e506ed-b3a5-442a-98aa-185aef081779
		summarizeBy: sum
		sourceColumn: reassignment_count

		annotation SummarizationSetBy = Automatic

	column rejection_goto
		dataType: string
		lineageTag: da618f21-8c20-4825-8079-e8ee345b52a6
		summarizeBy: none
		sourceColumn: rejection_goto

		annotation SummarizationSetBy = Automatic

	column dv_rejection_goto
		dataType: string
		lineageTag: f5e5e4c6-e434-42ec-8275-8d313f628a44
		summarizeBy: none
		sourceColumn: dv_rejection_goto

		annotation SummarizationSetBy = Automatic

	column relation_applied
		dataType: string
		lineageTag: c113b36e-bdfc-427d-85e1-0e7b2d136c93
		summarizeBy: none
		sourceColumn: relation_applied

		annotation SummarizationSetBy = Automatic

	column dv_relation_applied
		dataType: string
		lineageTag: 75c392eb-c304-4d83-bfd0-148f8bee2c3b
		summarizeBy: none
		sourceColumn: dv_relation_applied

		annotation SummarizationSetBy = Automatic

	column remaining_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 612a487d-3701-45e0-b2bd-6a34c8f57308
		summarizeBy: none
		sourceColumn: remaining_duration

		variation Variación
			isDefault
			relationship: 5a985d8d-d3be-4878-81b4-7854eba58c57
			defaultHierarchy: LocalDateTable_22387c89-54f1-424f-b05a-4fd0baec25ce.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_remaining_duration
		dataType: string
		lineageTag: 245db8b5-8404-42ba-ab72-0ca188283f9d
		summarizeBy: none
		sourceColumn: dv_remaining_duration

		annotation SummarizationSetBy = Automatic

	column remaining_effort
		dataType: dateTime
		formatString: General Date
		lineageTag: d5905d4d-c391-4aa7-b9ed-78cf8038112b
		summarizeBy: none
		sourceColumn: remaining_effort

		variation Variación
			isDefault
			relationship: f77d77e3-9d2a-4722-9dae-d0a906013416
			defaultHierarchy: LocalDateTable_c8d63d13-4f58-4391-b022-31247a7da274.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_remaining_effort
		dataType: string
		lineageTag: 9cc4b2df-2010-4819-b1a7-5818a2fcd4c7
		summarizeBy: none
		sourceColumn: dv_remaining_effort

		annotation SummarizationSetBy = Automatic

	column resource_allocated_cost
		dataType: double
		lineageTag: 4602164c-e948-4501-afbd-f8bec6675026
		summarizeBy: sum
		sourceColumn: resource_allocated_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column resource_planned_cost
		dataType: double
		lineageTag: 2710887b-9581-4043-9d9d-015a474116a9
		summarizeBy: sum
		sourceColumn: resource_planned_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rollup
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3f69504c-2755-4123-b523-7973775920f4
		summarizeBy: none
		sourceColumn: rollup

		annotation SummarizationSetBy = Automatic

	column route_reason
		dataType: int64
		formatString: 0
		lineageTag: 073a92d2-743a-4896-aba1-0df1b61ff8a4
		summarizeBy: sum
		sourceColumn: route_reason

		annotation SummarizationSetBy = Automatic

	column dv_route_reason
		dataType: string
		lineageTag: 7c42d34c-adea-4cb1-bf01-4d944b03ab28
		summarizeBy: none
		sourceColumn: dv_route_reason

		annotation SummarizationSetBy = Automatic

	column schedule_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: e4303f20-7ea8-4929-91c6-b6e888589051
		summarizeBy: none
		sourceColumn: schedule_end_date

		variation Variación
			isDefault
			relationship: 4f58e84f-a092-4de3-be72-b6ebedc7b486
			defaultHierarchy: LocalDateTable_9ef47dc7-4179-466f-a552-d5c71adae207.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column schedule_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: ba4b3904-cbfc-435a-af55-100fd48bcc3d
		summarizeBy: none
		sourceColumn: schedule_start_date

		variation Variación
			isDefault
			relationship: f0327c5d-5b2c-4c1b-a14e-afbc88cde5dd
			defaultHierarchy: LocalDateTable_d45ee678-7e84-41bd-a202-2bc5358332b2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column scrum_team
		dataType: string
		lineageTag: 081c2cec-afcb-43ba-9f97-4dd244cb3f6c
		summarizeBy: none
		sourceColumn: scrum_team

		annotation SummarizationSetBy = Automatic

	column dv_scrum_team
		dataType: string
		lineageTag: 78163045-8899-4121-b4c7-be47c350b670
		summarizeBy: none
		sourceColumn: dv_scrum_team

		annotation SummarizationSetBy = Automatic

	column service_offering
		dataType: string
		lineageTag: b5dfa7e0-8d76-4814-a50b-ecf56cbf86a0
		summarizeBy: none
		sourceColumn: service_offering

		annotation SummarizationSetBy = Automatic

	column dv_service_offering
		dataType: string
		lineageTag: 2cb45486-a819-4ed1-a8dd-4cbd87d54b0d
		summarizeBy: none
		sourceColumn: dv_service_offering

		annotation SummarizationSetBy = Automatic

	column shadow
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b77c0736-cfad-4596-a7da-74a5ca0e85a3
		summarizeBy: none
		sourceColumn: shadow

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: d8f51417-5a05-4c57-8baf-681fd59fad83
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column skills
		dataType: string
		lineageTag: cf09e2ba-56e5-4bd3-98e6-4c40efe0b059
		summarizeBy: none
		sourceColumn: skills

		annotation SummarizationSetBy = Automatic

	column sla_due
		dataType: dateTime
		formatString: General Date
		lineageTag: bdfd79a0-7f0e-4b0c-81da-adfc8230ca7f
		summarizeBy: none
		sourceColumn: sla_due

		variation Variación
			isDefault
			relationship: fbee22f7-fe5a-4d7e-9a99-64dd840aa147
			defaultHierarchy: LocalDateTable_46ba0ea5-28b8-4e71-913f-7c75b3e92f2b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f88883f4-8e1c-4810-bed3-b86814bb2225
		summarizeBy: none
		sourceColumn: start_date

		variation Variación
			isDefault
			relationship: 29dbc081-5412-4b96-9c70-f132d383553c
			defaultHierarchy: LocalDateTable_bcf45754-7206-42ea-ad8b-5db6f4345b5e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column start_date_derived_from
		dataType: string
		lineageTag: 987c9c65-6894-4070-ab1a-5760b9062a17
		summarizeBy: none
		sourceColumn: start_date_derived_from

		annotation SummarizationSetBy = Automatic

	column dv_start_date_derived_from
		dataType: string
		lineageTag: a77e550d-b130-42b3-9101-bfa5ad0e9707
		summarizeBy: none
		sourceColumn: dv_start_date_derived_from

		annotation SummarizationSetBy = Automatic

	column start_sprint
		dataType: string
		lineageTag: 48583f76-bf6c-452d-8e73-b326940a7603
		summarizeBy: none
		sourceColumn: start_sprint

		annotation SummarizationSetBy = Automatic

	column dv_start_sprint
		dataType: string
		lineageTag: 62db600d-7952-45be-b9f9-045660468e55
		summarizeBy: none
		sourceColumn: dv_start_sprint

		annotation SummarizationSetBy = Automatic

	column state
		dataType: int64
		formatString: 0
		lineageTag: be7d0053-2b1a-4ff9-b68d-098f18d24ca4
		summarizeBy: sum
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: c7c67968-5b00-4792-a315-546d57cfddea
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 8e7cff95-d376-4475-b551-487445e11cad
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column dv_status
		dataType: string
		lineageTag: 8b43f5f8-b89a-4910-bbd8-383dd5ef33a7
		summarizeBy: none
		sourceColumn: dv_status

		annotation SummarizationSetBy = Automatic

	column sub_tree_root
		dataType: string
		lineageTag: 08c0909c-8809-436c-90b4-66f36d0e75e1
		summarizeBy: none
		sourceColumn: sub_tree_root

		annotation SummarizationSetBy = Automatic

	column dv_sub_tree_root
		dataType: string
		lineageTag: daa4af12-764f-4a0e-adfc-f681203b564d
		summarizeBy: none
		sourceColumn: dv_sub_tree_root

		annotation SummarizationSetBy = Automatic

	column sys_class_name
		dataType: string
		lineageTag: 49fd4aeb-c27a-4a22-bdb3-a4ce4f7b28c5
		summarizeBy: none
		sourceColumn: sys_class_name

		annotation SummarizationSetBy = Automatic

	column dv_sys_class_name
		dataType: string
		lineageTag: c3e6c226-15ad-4a80-98fb-dc70abf16c52
		summarizeBy: none
		sourceColumn: dv_sys_class_name

		annotation SummarizationSetBy = Automatic

	column sys_created_by
		dataType: string
		lineageTag: e6f921c8-c078-450a-a7bd-5ca2a4a65f86
		summarizeBy: none
		sourceColumn: sys_created_by

		annotation SummarizationSetBy = Automatic

	column sys_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: ab4de0c6-ccde-4d5d-8010-25f2db0c8b80
		summarizeBy: none
		sourceColumn: sys_created_on

		variation Variación
			isDefault
			relationship: 1f8285b7-59ba-4d4e-9eb6-cfaef50cef1e
			defaultHierarchy: LocalDateTable_454cd2f9-d9a8-415d-81fb-5b6760b60fd0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column sys_domain
		dataType: string
		lineageTag: 2aa0a96d-6501-45d2-9415-a1f5171efb62
		summarizeBy: none
		sourceColumn: sys_domain

		annotation SummarizationSetBy = Automatic

	column sys_domain_path
		dataType: string
		lineageTag: 894639cd-30ef-4c4e-ab36-176f789ed886
		summarizeBy: none
		sourceColumn: sys_domain_path

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: a50a2c3c-00b5-4b95-99a0-c50cd1a71ca7
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column sys_mod_count
		dataType: int64
		formatString: 0
		lineageTag: eb2f31e5-c92f-41e0-8066-6cb0ea74db35
		summarizeBy: sum
		sourceColumn: sys_mod_count

		annotation SummarizationSetBy = Automatic

	column sys_tags
		dataType: string
		lineageTag: 5ffeb772-f3cd-4068-a608-7bb56e6d29d6
		summarizeBy: none
		sourceColumn: sys_tags

		annotation SummarizationSetBy = Automatic

	column sys_updated_by
		dataType: string
		lineageTag: 75a5d359-3152-4ec3-a1e5-2e5c839dd937
		summarizeBy: none
		sourceColumn: sys_updated_by

		annotation SummarizationSetBy = Automatic

	column sys_updated_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 19a67c03-0a98-4171-a96f-07a4784a990a
		summarizeBy: none
		sourceColumn: sys_updated_on

		variation Variación
			isDefault
			relationship: 2ed7619d-9bb7-4bb3-b9d8-9dd02c450ff2
			defaultHierarchy: LocalDateTable_1092226d-3fba-4764-be1d-33883ea2164c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column task
		dataType: string
		lineageTag: f13f6de1-0eeb-4a6a-8a3a-309ca009b442
		summarizeBy: none
		sourceColumn: task

		annotation SummarizationSetBy = Automatic

	column task_effective_number
		dataType: string
		lineageTag: c246cb53-137a-4ff2-89e7-f9be97d80c31
		summarizeBy: none
		sourceColumn: task_effective_number

		annotation SummarizationSetBy = Automatic

	column task_for
		dataType: string
		lineageTag: a6afe4a7-6ddd-4be8-be2a-6564f8854b35
		summarizeBy: none
		sourceColumn: task_for

		annotation SummarizationSetBy = Automatic

	column dv_task_for
		dataType: string
		lineageTag: 544fcbf4-3f28-451c-abac-f7f18d2b24ac
		summarizeBy: none
		sourceColumn: dv_task_for

		annotation SummarizationSetBy = Automatic

	column test_plan
		dataType: string
		lineageTag: c42cc196-c54b-40b9-a329-35f4c63a86f3
		summarizeBy: none
		sourceColumn: test_plan

		annotation SummarizationSetBy = Automatic

	column dv_test_plan
		dataType: string
		lineageTag: 4fca58d5-c90b-4956-acf2-758886085ddb
		summarizeBy: none
		sourceColumn: dv_test_plan

		annotation SummarizationSetBy = Automatic

	column time_card_at_top_task
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 24e125d4-263b-4505-821d-1ebe484ca530
		summarizeBy: none
		sourceColumn: time_card_at_top_task

		annotation SummarizationSetBy = Automatic

	column time_constraint
		dataType: string
		lineageTag: bc37072c-fc2d-497d-8849-211c67bb3fb5
		summarizeBy: none
		sourceColumn: time_constraint

		annotation SummarizationSetBy = Automatic

	column dv_time_constraint
		dataType: string
		lineageTag: 96fe5c15-09e2-44e2-8cf1-306a474ca5ef
		summarizeBy: none
		sourceColumn: dv_time_constraint

		annotation SummarizationSetBy = Automatic

	column time_worked
		dataType: dateTime
		formatString: General Date
		lineageTag: 5b087599-2c68-41ca-a638-5784c8effa2e
		summarizeBy: none
		sourceColumn: time_worked

		variation Variación
			isDefault
			relationship: fd0936a2-7bdb-42c4-b910-5bd95f47d82a
			defaultHierarchy: LocalDateTable_676885eb-c3da-4984-8768-fec545a7f952.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_time_worked
		dataType: string
		lineageTag: 5b037ee9-a380-40a8-b3af-b565834d7a2b
		summarizeBy: none
		sourceColumn: dv_time_worked

		annotation SummarizationSetBy = Automatic

	column top_portfolio
		dataType: string
		lineageTag: efe76262-4d99-4062-b989-83c0c10a2e3c
		summarizeBy: none
		sourceColumn: top_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_top_portfolio
		dataType: string
		lineageTag: f7c67c2f-d47b-424d-b4ea-ea4c9e69a6e7
		summarizeBy: none
		sourceColumn: dv_top_portfolio

		annotation SummarizationSetBy = Automatic

	column top_program
		dataType: string
		lineageTag: e5c50f5c-9a0f-4fd3-a204-29ce3419f61c
		summarizeBy: none
		sourceColumn: top_program

		annotation SummarizationSetBy = Automatic

	column dv_top_program
		dataType: string
		lineageTag: 13e8a713-6701-42f4-9d43-10b9df9822e5
		summarizeBy: none
		sourceColumn: dv_top_program

		annotation SummarizationSetBy = Automatic

	column top_task
		dataType: string
		lineageTag: be7e17e6-f8a6-432f-b537-f3a327854f7d
		summarizeBy: none
		sourceColumn: top_task

		annotation SummarizationSetBy = Automatic

	column dv_top_task
		dataType: string
		lineageTag: aa312677-fffa-4b86-a28a-33c081a62768
		summarizeBy: none
		sourceColumn: dv_top_task

		annotation SummarizationSetBy = Automatic

	column u_acciona_priority
		dataType: int64
		formatString: 0
		lineageTag: 39c1a83f-7577-40ac-b6d9-06b58ada8635
		summarizeBy: sum
		sourceColumn: u_acciona_priority

		annotation SummarizationSetBy = Automatic

	column u_business_line
		dataType: string
		lineageTag: 2acf7115-1ff0-477e-a303-1e5486c3ab09
		summarizeBy: none
		sourceColumn: u_business_line

		annotation SummarizationSetBy = Automatic

	column dv_u_business_line
		dataType: string
		lineageTag: 54262a7f-7373-40dd-b3f4-ad072029f56e
		summarizeBy: none
		sourceColumn: dv_u_business_line

		annotation SummarizationSetBy = Automatic

	column u_catalog
		dataType: string
		lineageTag: ec2bc3a1-232e-42a3-9b66-e295b7e2973e
		summarizeBy: none
		sourceColumn: u_catalog

		annotation SummarizationSetBy = Automatic

	column dv_u_catalog
		dataType: string
		lineageTag: 7fde713b-cea7-43b8-8c01-068608690391
		summarizeBy: none
		sourceColumn: dv_u_catalog

		annotation SummarizationSetBy = Automatic

	column u_demand
		dataType: string
		lineageTag: 19fcd112-a6b5-4381-acb2-a501a7097f79
		summarizeBy: none
		sourceColumn: u_demand

		annotation SummarizationSetBy = Automatic

	column dv_u_demand
		dataType: string
		lineageTag: 1af7109c-84ab-4af4-8c01-044f90773e74
		summarizeBy: none
		sourceColumn: dv_u_demand

		annotation SummarizationSetBy = Automatic

	column u_department
		dataType: string
		lineageTag: 8bf39401-64fd-46fe-b7ab-fc4ca7ff42c5
		summarizeBy: none
		sourceColumn: u_department

		annotation SummarizationSetBy = Automatic

	column dv_u_department
		dataType: string
		lineageTag: c286ddd7-e8e4-4d40-aed2-96ece960967c
		summarizeBy: none
		sourceColumn: dv_u_department

		annotation SummarizationSetBy = Automatic

	column u_estado_evolutivo
		dataType: string
		lineageTag: 08977f5e-506f-451f-8325-533c4497df1f
		summarizeBy: none
		sourceColumn: u_estado_evolutivo

		annotation SummarizationSetBy = Automatic

	column dv_u_estado_evolutivo
		dataType: string
		lineageTag: e066c2bc-bc1a-477a-8e28-f6da83d52267
		summarizeBy: none
		sourceColumn: dv_u_estado_evolutivo

		annotation SummarizationSetBy = Automatic

	column u_external_vendor
		dataType: string
		lineageTag: ffe26b51-9463-4490-8ed4-b6c5f7337f40
		summarizeBy: none
		sourceColumn: u_external_vendor

		annotation SummarizationSetBy = Automatic

	column dv_u_external_vendor
		dataType: string
		lineageTag: f5ac4a16-a5a7-4b42-a66e-8e3d17d107f7
		summarizeBy: none
		sourceColumn: dv_u_external_vendor

		annotation SummarizationSetBy = Automatic

	column u_metal
		dataType: string
		lineageTag: 3bca1441-6adb-45c0-addf-d97641bb3517
		summarizeBy: none
		sourceColumn: u_metal

		annotation SummarizationSetBy = Automatic

	column dv_u_metal
		dataType: string
		lineageTag: d268e198-f287-4d8c-84a0-631e5da04ff1
		summarizeBy: none
		sourceColumn: dv_u_metal

		annotation SummarizationSetBy = Automatic

	column u_phone
		dataType: string
		lineageTag: 068c5436-ceb9-4e44-a292-be18fec0019c
		summarizeBy: none
		sourceColumn: u_phone

		annotation SummarizationSetBy = Automatic

	column u_previous_groups
		dataType: string
		lineageTag: 69f652a0-4c24-4618-a77d-914e9d7f7288
		summarizeBy: none
		sourceColumn: u_previous_groups

		annotation SummarizationSetBy = Automatic

	column u_progress
		dataType: double
		lineageTag: fc0d2dec-e94c-4c4a-81b1-138714754fbe
		summarizeBy: sum
		sourceColumn: u_progress

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_ref_country
		dataType: string
		lineageTag: 2ba31f9a-6a90-4fe6-ae0e-2b32c9d84bf7
		summarizeBy: none
		sourceColumn: u_ref_country

		annotation SummarizationSetBy = Automatic

	column dv_u_ref_country
		dataType: string
		lineageTag: e258a473-afd0-4ffb-add2-6128dc770492
		summarizeBy: none
		sourceColumn: dv_u_ref_country

		annotation SummarizationSetBy = Automatic

	column u_responded
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5551e0c7-0391-44b0-9b64-6b37b7e2b324
		summarizeBy: none
		sourceColumn: u_responded

		annotation SummarizationSetBy = Automatic

	column u_size
		dataType: string
		lineageTag: d9a1ac76-22a1-428f-ba2b-5f60780f13ee
		summarizeBy: none
		sourceColumn: u_size

		annotation SummarizationSetBy = Automatic

	column dv_u_size
		dataType: string
		lineageTag: ff6270dc-8291-4110-b1e5-44f93448f887
		summarizeBy: none
		sourceColumn: dv_u_size

		annotation SummarizationSetBy = Automatic

	column u_state_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 75db0492-b8ec-414c-9b48-875f80f2eaba
		summarizeBy: none
		sourceColumn: u_state_date

		variation Variación
			isDefault
			relationship: f8b81028-50ec-4a10-94be-2f2a7d23d66d
			defaultHierarchy: LocalDateTable_b122e5a8-d9eb-4373-95e8-4e9183d39a74.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_version
		dataType: string
		lineageTag: 40aa6933-1d4f-4060-afbd-0b96881526ec
		summarizeBy: none
		sourceColumn: u_version

		annotation SummarizationSetBy = Automatic

	column universal_request
		dataType: string
		lineageTag: 47cb6d8a-96b5-4160-b25f-08011f4ad942
		summarizeBy: none
		sourceColumn: universal_request

		annotation SummarizationSetBy = Automatic

	column dv_universal_request
		dataType: string
		lineageTag: 2ab18d60-63d8-481d-ae19-74b30d0a8cb8
		summarizeBy: none
		sourceColumn: dv_universal_request

		annotation SummarizationSetBy = Automatic

	column upon_approval
		dataType: string
		lineageTag: 85e4f025-5135-4c9c-9cb1-e3b155467882
		summarizeBy: none
		sourceColumn: upon_approval

		annotation SummarizationSetBy = Automatic

	column dv_upon_approval
		dataType: string
		lineageTag: 99757d41-29c1-41cc-b81b-93523f0c3992
		summarizeBy: none
		sourceColumn: dv_upon_approval

		annotation SummarizationSetBy = Automatic

	column upon_reject
		dataType: string
		lineageTag: 24807b8e-6d1c-4cb2-bb44-369f5c38d064
		summarizeBy: none
		sourceColumn: upon_reject

		annotation SummarizationSetBy = Automatic

	column dv_upon_reject
		dataType: string
		lineageTag: a4caf198-bd46-4fc0-a314-92766c08987b
		summarizeBy: none
		sourceColumn: dv_upon_reject

		annotation SummarizationSetBy = Automatic

	column urgency
		dataType: int64
		formatString: 0
		lineageTag: 06de27c0-b735-4d98-bb00-53f481b153b8
		summarizeBy: sum
		sourceColumn: urgency

		annotation SummarizationSetBy = Automatic

	column dv_urgency
		dataType: string
		lineageTag: 09b72353-436d-42b1-bac4-186e925313e0
		summarizeBy: none
		sourceColumn: dv_urgency

		annotation SummarizationSetBy = Automatic

	column user_input
		dataType: string
		lineageTag: 8fc59301-18c7-4149-a360-a898c8135341
		summarizeBy: none
		sourceColumn: user_input

		annotation SummarizationSetBy = Automatic

	column variables
		dataType: string
		lineageTag: 9c823fc0-2249-4f89-8315-bcc8266f5e50
		summarizeBy: none
		sourceColumn: variables

		annotation SummarizationSetBy = Automatic

	column version
		dataType: int64
		formatString: 0
		lineageTag: 581c4598-4a69-4fd6-a844-114f1050e343
		summarizeBy: sum
		sourceColumn: version

		annotation SummarizationSetBy = Automatic

	column watch_list
		dataType: string
		lineageTag: 3d6bbb4e-9934-445a-b213-7ff19a535421
		summarizeBy: none
		sourceColumn: watch_list

		annotation SummarizationSetBy = Automatic

	column wbs
		dataType: string
		lineageTag: 8bdd7431-8cab-4e71-8d7a-39c724b302e9
		summarizeBy: none
		sourceColumn: wbs

		annotation SummarizationSetBy = Automatic

	column wbs_order
		dataType: int64
		formatString: 0
		lineageTag: 79800c1b-856e-4a6e-9fd5-53a2ee2543da
		summarizeBy: sum
		sourceColumn: wbs_order

		annotation SummarizationSetBy = Automatic

	column wf_activity
		dataType: string
		lineageTag: 46024ef3-3b8b-493f-bd34-3aa90cb027f9
		summarizeBy: none
		sourceColumn: wf_activity

		annotation SummarizationSetBy = Automatic

	column dv_wf_activity
		dataType: string
		lineageTag: d9dffdf3-5e18-4b58-8489-908868628cb8
		summarizeBy: none
		sourceColumn: dv_wf_activity

		annotation SummarizationSetBy = Automatic

	column work_cost
		dataType: double
		lineageTag: 918a7c43-aaf0-42f8-9e05-fb31a516e721
		summarizeBy: sum
		sourceColumn: work_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column work_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: be0807d5-7676-477d-9691-1d6f838f8559
		summarizeBy: none
		sourceColumn: work_duration

		variation Variación
			isDefault
			relationship: 089c7787-66a2-44fe-9ca6-f129ef142c30
			defaultHierarchy: LocalDateTable_470c0265-eb34-4fb6-b6ee-912bb63eb8da.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_work_duration
		dataType: string
		lineageTag: bb583235-9cb7-4271-8236-153b0b46b370
		summarizeBy: none
		sourceColumn: dv_work_duration

		annotation SummarizationSetBy = Automatic

	column work_effort
		dataType: dateTime
		formatString: General Date
		lineageTag: 57d8542e-c818-4f8f-bbd3-5403c3b06b3f
		summarizeBy: none
		sourceColumn: work_effort

		variation Variación
			isDefault
			relationship: c05b26ab-4556-4c7e-851e-337d7759065d
			defaultHierarchy: LocalDateTable_85c585a7-dfad-45c0-b74a-71d82b9d2673.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_work_effort
		dataType: string
		lineageTag: e57bf9ce-801c-41f0-8a87-94bfcce024ba
		summarizeBy: none
		sourceColumn: dv_work_effort

		annotation SummarizationSetBy = Automatic

	column work_end
		dataType: dateTime
		formatString: General Date
		lineageTag: e9a6e224-fc7c-46c4-b794-4bba6fc0745e
		summarizeBy: none
		sourceColumn: work_end

		variation Variación
			isDefault
			relationship: 502d3d9c-99f4-4c98-a2d1-09bc0ea73e2a
			defaultHierarchy: LocalDateTable_b176c65f-7914-4c1b-912f-50e9be07c72f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column work_notes
		dataType: string
		lineageTag: 7869888f-706f-41e9-bf66-7c5777953f6d
		summarizeBy: none
		sourceColumn: work_notes

		annotation SummarizationSetBy = Automatic

	column work_notes_list
		dataType: string
		lineageTag: 8460b354-2a69-42be-9acc-6dd77be716f1
		summarizeBy: none
		sourceColumn: work_notes_list

		annotation SummarizationSetBy = Automatic

	column work_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 2c4a7600-90d1-453f-9d64-b20af8433fe8
		summarizeBy: none
		sourceColumn: work_start

		variation Variación
			isDefault
			relationship: d880f18f-4467-4925-98e3-53341c9f7a3c
			defaultHierarchy: LocalDateTable_0e5d4ed2-4c92-4535-ba1d-0ea886108262.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'Tareas de Subproyecto' = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("QECCDWH.ACCIONA.INT:60001"),
				    DWH = Origen{[Name="DWH"]}[Data],
				    SERV_NOW_EN_V_pm_project_task = DWH{[Schema="SERV_NOW_EN",Item="V_pm_project_task"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(SERV_NOW_EN_V_pm_project_task, each not Text.StartsWith([dv_parent], "PRJTASK")),
				    #"Filas filtradas1" = Table.SelectRows(#"Filas filtradas", each [dv_parent] <> null and [dv_parent] <> "")
				in
				    #"Filas filtradas1"

	annotation PBI_ResultType = Table

