table Componentes
	lineageTag: f90932ae-2113-482c-bdcf-7bfd011cf8c5

	column BI
		dataType: string
		lineageTag: d0a7a5cd-81c9-4960-a864-956230df5ad4
		summarizeBy: none
		sourceColumn: BI

		annotation SummarizationSetBy = Automatic

	column MERCADOS
		dataType: string
		lineageTag: f30c4ef9-1f3c-4b33-9520-9fcedc882425
		summarizeBy: none
		sourceColumn: MERCADOS

		annotation SummarizationSetBy = Automatic

	column EMS
		dataType: string
		lineageTag: 66731bab-011d-4c03-856d-7383ab30be70
		summarizeBy: none
		sourceColumn: EMS

		annotation SummarizationSetBy = Automatic

	column 'CRM Energia'
		dataType: string
		lineageTag: c848f950-8983-43b4-8260-af5fe4cc6161
		summarizeBy: none
		sourceColumn: CRM Energia

		annotation SummarizationSetBy = Automatic

	column LEGAL
		dataType: string
		lineageTag: ceec65eb-9262-4f9b-9a5b-309d32b4fe64
		summarizeBy: none
		sourceColumn: LEGAL

		annotation SummarizationSetBy = Automatic

	partition Componentes-52f57b4e-de8c-42d5-8f9a-5e7c1f7acde0 = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source =
				let
				    URL = sharepointSource & Entorno & componentesPath & xlsx,
				    Origen = Excel.Workbook(Web.Contents(URL), null, true),
				    Personalizado1 = Origen{[Name="Componentes Jira por Servicio"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Personalizado1, [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ENABLON", type text}, {"MAXIMO", type text}, {"IAR", type text}, {"AMS CORE GFI", type text}, {"SERVICENOW", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado1",{"MAXIMO", "IAR", "AMS CORE GFI", "SERVICENOW", "CRMSF", "GDOC", "LWAS", "RPA", "BESTINVER", "SAPHR", "BESTINVERAPP", "SAC", "SCS", "ENABLON"}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas quitadas", each ([BI] <> null))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

