table 'Parámetros - Pesos'
	lineageTag: 50e6623c-b2ff-4642-9797-c022567fa1bd

	column ID
		dataType: string
		lineageTag: 9680a294-5ffd-4d9e-9041-62b9d8707bbd
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column ID_KGI
		dataType: string
		lineageTag: 3cfedbca-8cd6-4edf-be1f-75cbb9a6e906
		summarizeBy: none
		sourceColumn: ID_KGI

		annotation SummarizationSetBy = Automatic

	column KGI_texto
		dataType: string
		lineageTag: 6d788fa8-4bfd-49b1-be4a-9364519561f2
		summarizeBy: none
		sourceColumn: KGI_texto

		annotation SummarizationSetBy = Automatic

	column Periodicidad
		dataType: string
		lineageTag: f35772db-13c9-413b-8708-7fccbae3ca0d
		summarizeBy: none
		sourceColumn: Periodicidad

		annotation SummarizationSetBy = Automatic

	column Id_Servicio
		dataType: int64
		formatString: 0
		lineageTag: a44f28eb-7e6c-4693-a694-15500176e449
		summarizeBy: sum
		sourceColumn: Id_Servicio

		annotation SummarizationSetBy = Automatic

	column Servicio_texto
		dataType: string
		lineageTag: 457c93f7-b244-4ea7-88ff-e4553bfde7cc
		summarizeBy: none
		sourceColumn: Servicio_texto

		annotation SummarizationSetBy = Automatic

	column 'Categ. Definición'
		dataType: string
		lineageTag: 28fa6b6a-0236-487f-a863-251746b1ada8
		summarizeBy: none
		sourceColumn: Categ. Definición

		annotation SummarizationSetBy = Automatic

	column 'ID_Categoria '
		dataType: int64
		formatString: 0
		lineageTag: 98da4ebf-1320-4a21-ba4e-c7a2f8b789cf
		summarizeBy: sum
		sourceColumn: "ID_Categoria "

		annotation SummarizationSetBy = Automatic

	column Categorización
		dataType: string
		lineageTag: 87182eb1-0e0f-4f5e-99d7-59cd676e74cb
		summarizeBy: none
		sourceColumn: Categorización
		sortByColumn: Orden_Prioridad

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Criterio medición'
		dataType: string
		lineageTag: 287f75f5-ef58-41cb-a9d6-5d8119816152
		summarizeBy: none
		sourceColumn: Criterio medición

		annotation SummarizationSetBy = Automatic

	column 'Umbral medición'
		dataType: double
		lineageTag: 8e07d1ab-e72b-4b92-9b80-eccbce3504b8
		summarizeBy: sum
		sourceColumn: Umbral medición

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cumplimiento Objetivo %'
		dataType: double
		lineageTag: d6d04b3b-584b-4f0b-8d52-0d957b6db2c2
		summarizeBy: sum
		sourceColumn: Cumplimiento Objetivo %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Peso dentro de KGI (%)'
		dataType: double
		lineageTag: 276334c6-759a-475f-b31b-75914b322e52
		summarizeBy: sum
		sourceColumn: Peso dentro de KGI (%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Peso del KGI dentro del servicio (%)'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 491702a2-1a56-4112-991a-69ea7ca092ba
		summarizeBy: sum
		sourceColumn: Peso del KGI dentro del servicio (%)

		annotation SummarizationSetBy = Automatic

	column 'Peso del servicio en el CdM (%)'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 383ce2d7-d632-4d56-bd62-56e416972eb8
		summarizeBy: sum
		sourceColumn: Peso del servicio en el CdM (%)

		annotation SummarizationSetBy = Automatic

	column 'Peso CdM (%)'
		dataType: double
		lineageTag: cc32896e-6f64-41f4-832d-622f13619819
		summarizeBy: sum
		sourceColumn: Peso CdM (%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nombre KGI'
		dataType: string
		lineageTag: 99deb713-daff-4714-901b-ebf7ac6bf86d
		summarizeBy: none
		sourceColumn: Nombre KGI

		annotation SummarizationSetBy = Automatic

	column Servicio
		dataType: string
		lineageTag: c57bfb51-f0a4-452a-a36b-68ce5c0abc37
		summarizeBy: none
		sourceColumn: Servicio

		annotation SummarizationSetBy = Automatic

	column 'Formato cálculo'
		dataType: string
		lineageTag: f263bfe6-52f6-4076-bae4-32f20125bf7e
		summarizeBy: none
		sourceColumn: Formato cálculo

		annotation SummarizationSetBy = Automatic

	column 'Criterio cumplimiento'
		dataType: string
		lineageTag: 83c1ea2f-6f19-48ee-b00e-76bf2ca6880d
		summarizeBy: none
		sourceColumn: Criterio cumplimiento

		annotation SummarizationSetBy = Automatic

	column 'Casos de aplicación'
		dataType: string
		lineageTag: b907cac3-8287-47c0-83fd-ff2d0ae8b346
		summarizeBy: none
		sourceColumn: Casos de aplicación

		annotation SummarizationSetBy = Automatic

	column Notas
		dataType: string
		lineageTag: d5a87e98-d808-4173-bc2a-0ad400efb901
		summarizeBy: none
		sourceColumn: Notas

		annotation SummarizationSetBy = Automatic

	column Orden_Prioridad = ```
			
			IF('Parámetros - Pesos'[Casos de aplicación]= "Prioridad Crítica", 0,
			    IF('Parámetros - Pesos'[Casos de aplicación]= "Prioridad Alta", 1,
			        IF('Parámetros - Pesos'[Casos de aplicación]= "Prioridad Media", 2, 
			            IF('Parámetros - Pesos'[Casos de aplicación]= "Prioridad Baja", 3,
			                IF('Parámetros - Pesos'[Casos de aplicación]= "Nivel de Impacto Grave", 4,
			                    IF('Parámetros - Pesos'[Casos de aplicación]= "Nivel de Impacto Medio", 5,
			                        IF('Parámetros - Pesos'[Casos de aplicación]= "Nivel de Impacto Leve", 6,
			                            IF('Parámetros - Pesos'[Casos de aplicación]= "Tipo de Incumplimiento Grave", 7,
			                                IF('Parámetros - Pesos'[Casos de aplicación]= "Tipo de Incumplimiento Medio", 8,
			                                    IF('Parámetros - Pesos'[Casos de aplicación]= "Tipo de Incumplimiento Leve", 9,
			                                        IF('Parámetros - Pesos'[Casos de aplicación]= "", 10,
			                                            IF('Parámetros - Pesos'[Casos de aplicación]= "1", 11,
			                                                9
			                                            ))))))))))))
			```
		formatString: 0
		lineageTag: e9c87dc7-1f97-4247-ad96-63fd832653a2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Parámetros - Pesos-b4f257d2-3f68-40a4-a23f-9f7930d4c0e6' = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source =
				let
				    URL = sharepointSource & Entorno & sharepointSource2 & "Parámetros_KGIs.xlsx",
				    Origen = Excel.Workbook(Web.Contents(URL), null, true),
				    #"Parámetros - Pesos_Sheet" = Origen{[Item="Hoja1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Parámetros - Pesos_Sheet", [PromoteAllScalars=true]),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Encabezados promovidos", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Filas en blanco eliminadas",{{"Id_Servicio", Int64.Type}, {"Periodicidad", type text}, {"KGI_texto", type text}, {"ID_KGI", type text}, {"ID", type text}, {"Servicio_texto", type text}, {"Categ. Definición", type text}, {"ID_Categoria ", Int64.Type}, {"Categorización", type text}, {"Criterio medición", type text}, {"Umbral medición", type number}, {"Cumplimiento Objetivo %", Percentage.Type}, {"Peso dentro de KGI (%)", Percentage.Type}, {"Peso del KGI dentro del servicio (%)", Percentage.Type}, {"Peso del servicio en el CdM (%)", Percentage.Type}, {"Peso CdM (%)", Percentage.Type}}),
				    #"Errores reemplazados" = Table.ReplaceErrorValues(#"Tipo cambiado", {{"Umbral medición", null}, {"Peso dentro de KGI (%)", null}, {"Peso del KGI dentro del servicio (%)", null}, {"Peso del servicio en el CdM (%)", null}, {"Peso CdM (%)", null}})
				in
				    #"Errores reemplazados"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

