table 'Ficha - dmn_demand'
	lineageTag: 2ab91f86-654e-44df-a6de-eb903e638223

	column approval_set
		dataType: dateTime
		formatString: General Date
		lineageTag: b1235b28-ad6b-4181-b7ff-e3cb3b4d1fcb
		summarizeBy: none
		sourceColumn: approval_set

		variation Variación
			isDefault
			relationship: 7ed804bd-35e8-49da-ae37-3a2e80402a4a
			defaultHierarchy: LocalDateTable_64e6cb95-c81d-4bb7-afcc-6907557074f2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_assigned_to
		dataType: string
		lineageTag: 5627f773-ac1b-4009-aac1-632b54fce3dc
		summarizeBy: none
		sourceColumn: dv_assigned_to

		annotation SummarizationSetBy = Automatic

	column dv_assignment_group
		dataType: string
		lineageTag: 2ac9f69e-46d6-4c68-840f-e5bff8f02cde
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column dv_business_duration
		dataType: string
		lineageTag: b51efa6d-5e5d-4085-b4e9-6ec35f7f9432
		summarizeBy: none
		sourceColumn: dv_business_duration

		annotation SummarizationSetBy = Automatic

	column capital_budget
		dataType: double
		lineageTag: 458196fb-4f3e-4849-b622-77daf79d15c9
		summarizeBy: sum
		sourceColumn: capital_budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dv_category
		dataType: string
		lineageTag: 45f83c5f-eae4-451d-bdb5-6266cdbdf377
		summarizeBy: none
		sourceColumn: dv_category

		annotation SummarizationSetBy = Automatic

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: adce2a4b-bbdb-4dc9-884b-dca94123fb0d
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: b3dc174d-fa7e-4a0a-bfaa-db8228176712
			defaultHierarchy: LocalDateTable_c890f7e4-2e62-4c86-b892-8c6446c5d0ba.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci_business_app
		dataType: string
		lineageTag: 53e72761-43c6-4365-956a-56daa6e62ebe
		summarizeBy: none
		sourceColumn: dv_cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column demand
		dataType: string
		lineageTag: 471ae785-ef1b-4b35-b582-155482d5745d
		summarizeBy: none
		sourceColumn: demand

		annotation SummarizationSetBy = Automatic

	column dv_demand_manager
		dataType: string
		lineageTag: f15c60d9-bd87-4739-8b4b-7bada796dfb0
		summarizeBy: none
		sourceColumn: dv_demand_manager

		annotation SummarizationSetBy = Automatic

	column dv_department
		dataType: string
		lineageTag: 4e59c787-640a-4e4d-9cf4-08d223faec30
		summarizeBy: none
		sourceColumn: dv_department

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: c18d2c08-625d-4a0b-8d4e-17ab8bf46742
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column enhancement
		dataType: string
		lineageTag: 9932679f-2ccd-41e4-b55d-712596ce9558
		summarizeBy: none
		sourceColumn: enhancement

		annotation SummarizationSetBy = Automatic

	column dv_enhancement
		dataType: string
		lineageTag: cad3bfb9-24dc-44b9-9eb2-4862249106b1
		summarizeBy: none
		sourceColumn: dv_enhancement

		annotation SummarizationSetBy = Automatic

	column dv_escalation
		dataType: string
		lineageTag: 264fa08f-a0c5-4b84-bb4b-a1b0fb778912
		summarizeBy: none
		sourceColumn: dv_escalation

		annotation SummarizationSetBy = Automatic

	column dv_expected_risk
		dataType: string
		lineageTag: e85ef5c0-e8f1-427d-a944-2bc780ebed77
		summarizeBy: none
		sourceColumn: dv_expected_risk

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: 9f340bee-8913-460f-8355-bd1a1170a7c8
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: 6cbe6250-d30a-46ce-a004-5e47d6b72f2f
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 7659a106-4e42-4fb9-ae6e-3acd9388d340
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: 43b50678-0baa-44b7-93f5-164c95e4a7d6
			defaultHierarchy: LocalDateTable_18e672a4-cd00-4d21-ad17-ff3acc184a30.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column operational_budget
		dataType: double
		lineageTag: 9212a32d-c205-440a-8ac8-84d2827e283c
		summarizeBy: sum
		sourceColumn: operational_budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column operational_outlay
		dataType: double
		lineageTag: 8496c48d-2f26-45da-8417-1636913c32fe
		summarizeBy: sum
		sourceColumn: operational_outlay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order
		dataType: int64
		formatString: 0
		lineageTag: 1068e755-5951-4736-a310-95951183fbbb
		summarizeBy: sum
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	column other_costs
		dataType: double
		lineageTag: 2e1a97be-7f8e-492b-b077-133ac9f998d6
		summarizeBy: sum
		sourceColumn: other_costs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column out_of_scope
		dataType: string
		lineageTag: 8bdf2643-9f1f-4edc-9668-e77523c6ecc8
		summarizeBy: none
		sourceColumn: out_of_scope

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: e4c54229-2aed-4c71-9f5c-67339723cc81
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: 9c337f67-5773-479a-baec-cebeb0976d5c
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column portfolio
		dataType: string
		lineageTag: 1b3778a1-8da6-43c1-a07c-fc53c60f4494
		summarizeBy: none
		sourceColumn: portfolio

		annotation SummarizationSetBy = Automatic

	column dv_portfolio
		dataType: string
		lineageTag: c7ae791b-a854-4d91-95ba-ec5e15cf074b
		summarizeBy: none
		sourceColumn: dv_portfolio

		annotation SummarizationSetBy = Automatic

	column primary_program
		dataType: string
		lineageTag: 89df5e86-226e-47b3-ab6a-28ae70150147
		summarizeBy: none
		sourceColumn: primary_program

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: 740d8cda-815d-4090-8ed8-973f44dbe151
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column project
		dataType: string
		lineageTag: 7aa19a89-b768-4c53-8f2c-c526ad65c5d0
		summarizeBy: none
		sourceColumn: project

		annotation SummarizationSetBy = Automatic

	column dv_project
		dataType: string
		lineageTag: 31cd88e4-ff4b-4398-b2fd-7ea6e9a67f2b
		summarizeBy: none
		sourceColumn: dv_project

		annotation SummarizationSetBy = Automatic

	column 'related_records.1'
		dataType: string
		lineageTag: 36886f50-fbd8-4a31-b0b9-3645edceccc7
		summarizeBy: none
		sourceColumn: related_records.1

		annotation SummarizationSetBy = Automatic

	column 'related_records.2'
		dataType: string
		lineageTag: a34706a6-2917-4668-be9c-5057fa3df5f9
		summarizeBy: none
		sourceColumn: related_records.2

		annotation SummarizationSetBy = Automatic

	column 'related_records.3'
		dataType: string
		lineageTag: 7c6e23bc-3905-4cbe-80b3-4498b1d7fc92
		summarizeBy: none
		sourceColumn: related_records.3

		annotation SummarizationSetBy = Automatic

	column 'related_records.4'
		dataType: string
		lineageTag: 4b7b1823-768a-4bfa-a75d-426ba79219e1
		summarizeBy: none
		sourceColumn: related_records.4

		annotation SummarizationSetBy = Automatic

	column 'related_records.5'
		dataType: string
		lineageTag: c201f42c-aec8-4c3d-b698-87efb84d59f3
		summarizeBy: none
		sourceColumn: related_records.5

		annotation SummarizationSetBy = Automatic

	column 'related_records.6'
		dataType: string
		lineageTag: 0cefb566-d9d2-437b-848e-80c040f4ebd7
		summarizeBy: none
		sourceColumn: related_records.6

		annotation SummarizationSetBy = Automatic

	column 'related_records.7'
		dataType: string
		lineageTag: 8db75497-017a-426b-a8ac-cf946faf8311
		summarizeBy: none
		sourceColumn: related_records.7

		annotation SummarizationSetBy = Automatic

	column 'related_records.8'
		dataType: string
		lineageTag: 53220487-8732-49c3-8c8f-82efdc01f840
		summarizeBy: none
		sourceColumn: related_records.8

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: 4b228ed6-691a-4d87-9d7f-02f3bfe48a62
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fca5bf7e-dee5-48dd-8e1c-eca3accc4bc0
		summarizeBy: none
		sourceColumn: start_date

		variation Variación
			isDefault
			relationship: 5f648275-703b-4081-aca9-ce7b821d188f
			defaultHierarchy: LocalDateTable_252deb47-6ffa-4f41-8a3c-7db2edd1f77f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: e37ec7b9-6873-4f0b-b112-2c1617bd4b35
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: 8b66dbab-35dd-4346-95ee-ab99f1bc032b
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column task_effective_number
		dataType: string
		lineageTag: 89edd985-e80f-4ad1-8560-4205b4b4a83c
		summarizeBy: none
		sourceColumn: task_effective_number

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 86d535d8-2ae1-4b82-8d82-75ff20d44862
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column dv_type
		dataType: string
		lineageTag: d1e6045e-e349-46ba-af03-56f167d2b5c2
		summarizeBy: none
		sourceColumn: dv_type

		annotation SummarizationSetBy = Automatic

	column u_actual_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 640f5dfc-b399-4b9a-9b08-f4138bf371e8
		summarizeBy: none
		sourceColumn: u_actual_end_date

		variation Variación
			isDefault
			relationship: ff1a0446-11b9-41fc-b959-2c67b112fdff
			defaultHierarchy: LocalDateTable_acd0b73c-e537-4b2e-820a-bb543a3b9d4c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_actual_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 51a46190-64e1-4292-95a5-a32b83accea7
		summarizeBy: none
		sourceColumn: u_actual_start_date

		variation Variación
			isDefault
			relationship: b9390e69-5c84-4e67-af44-75b37766946a
			defaultHierarchy: LocalDateTable_9a5288fe-cc02-4ebc-9596-755a5fa05d28.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_u_business_applications
		dataType: string
		lineageTag: 1347e0bb-d0f1-4ab2-80c5-d619c0e0e6f7
		summarizeBy: none
		sourceColumn: dv_u_business_applications

		annotation SummarizationSetBy = Automatic

	column u_demand_category
		dataType: string
		lineageTag: 35f5382f-da0d-495b-8245-9ac852961c23
		summarizeBy: none
		sourceColumn: u_demand_category

		annotation SummarizationSetBy = Automatic

	column dv_u_demand_category
		dataType: string
		lineageTag: 44e8e3ea-24f7-431c-8a60-d5edb6cd7a4f
		summarizeBy: none
		sourceColumn: dv_u_demand_category

		annotation SummarizationSetBy = Automatic

	column dv_u_second_commettee_state
		dataType: string
		lineageTag: 9fafed97-d0ca-4ef2-a4bd-b0206ab2be36
		summarizeBy: none
		sourceColumn: dv_u_second_commettee_state

		annotation SummarizationSetBy = Automatic

	column dv_u_second_committee_date
		dataType: string
		lineageTag: 06137fa5-2ba5-40ba-bc02-247691a7c344
		summarizeBy: none
		sourceColumn: dv_u_second_committee_date

		annotation SummarizationSetBy = Automatic

	column u_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 94612bcf-6022-4001-8f20-af1c65ae50ae
		summarizeBy: none
		sourceColumn: u_start_date

		variation Variación
			isDefault
			relationship: 2d16582b-2999-4a5a-a1ce-2fb46944f4dd
			defaultHierarchy: LocalDateTable_11a99e1c-bf54-473e-b16a-cb5783d4da0c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_state_date
		dataType: dateTime
		formatString: General Date
		lineageTag: a0ad2a41-4d78-4d74-8f25-6354770c561e
		summarizeBy: none
		sourceColumn: u_state_date

		variation Variación
			isDefault
			relationship: 09db6566-1fa7-4f3a-8383-3d3c1beb3114
			defaultHierarchy: LocalDateTable_45101ac4-364e-49b7-bcca-99b9372b157b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_subcategory
		dataType: string
		lineageTag: 7e74cc84-cf06-4b08-a1e2-d80049d8ec87
		summarizeBy: none
		sourceColumn: u_subcategory

		annotation SummarizationSetBy = Automatic

	column dv_u_subcategory
		dataType: string
		lineageTag: 050a06a2-6278-4864-acf2-c7cc83c0a6cc
		summarizeBy: none
		sourceColumn: dv_u_subcategory

		annotation SummarizationSetBy = Automatic

	column u_submission_date
		dataType: dateTime
		formatString: General Date
		lineageTag: fa6e32a3-c930-416a-9d00-0e6624516d9b
		summarizeBy: none
		sourceColumn: u_submission_date

		variation Variación
			isDefault
			relationship: 445b47f5-367f-4651-b768-e4ffcd40162b
			defaultHierarchy: LocalDateTable_92d37bf4-2e31-44cf-b442-7592eec455a6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_u_tic_unit
		dataType: string
		lineageTag: f89e6ba1-8c9f-4a05-a27a-fef7b9d46b6d
		summarizeBy: none
		sourceColumn: dv_u_tic_unit

		annotation SummarizationSetBy = Automatic

	column u_total_budget
		dataType: double
		lineageTag: 7a0aa291-5c0c-4c7c-b60a-07c1df2cc065
		summarizeBy: sum
		sourceColumn: u_total_budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dv_universal_request
		dataType: string
		lineageTag: 7920dcb9-1494-4c9f-ac5a-d86c1fb01ce8
		summarizeBy: none
		sourceColumn: dv_universal_request

		annotation SummarizationSetBy = Automatic

	column dv_urgency
		dataType: string
		lineageTag: 6297dba3-29e4-4484-96f2-8eb5545d8eda
		summarizeBy: none
		sourceColumn: dv_urgency

		annotation SummarizationSetBy = Automatic

	column work_end
		dataType: dateTime
		formatString: General Date
		lineageTag: 2a0f2e4c-32bf-4ca3-9bae-7b85ac1158c7
		summarizeBy: none
		sourceColumn: work_end

		variation Variación
			isDefault
			relationship: 886ea126-4388-4451-a46d-3bb453610650
			defaultHierarchy: LocalDateTable_5b9be61e-2b92-4893-abed-716563815be1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column work_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 9c790bfc-1f59-4f88-8613-99c162d4c0bf
		summarizeBy: none
		sourceColumn: work_start

		variation Variación
			isDefault
			relationship: 5ea1cc76-064d-43f2-8662-75f915fccb00
			defaultHierarchy: LocalDateTable_fbe3897a-9ddd-4485-bac2-2e51403ee0b3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Proyectos_Mejoras_generados
		dataType: string
		lineageTag: 3e949160-d174-45d7-8ec6-7aeaf7b49b04
		summarizeBy: none
		sourceColumn: Proyectos_Mejoras_generados

		annotation SummarizationSetBy = Automatic

	column 'Ficha - pm_project_task.number'
		dataType: string
		lineageTag: 720d2a93-de6e-4588-b2f6-8673bf660e16
		summarizeBy: none
		sourceColumn: Ficha - pm_project_task.number

		annotation SummarizationSetBy = Automatic

	column 'Ficha - pm_project_task.number.1'
		dataType: string
		lineageTag: be52a335-a3cb-44cc-84f2-668875d3fad8
		summarizeBy: none
		sourceColumn: Ficha - pm_project_task.number.1

		annotation SummarizationSetBy = Automatic

	column 'Ficha - pm_project_task.number.2'
		dataType: string
		lineageTag: c5fca87c-877f-4d0f-a271-8e5a5d125887
		summarizeBy: none
		sourceColumn: Ficha - pm_project_task.number.2

		annotation SummarizationSetBy = Automatic

	column 'Ficha - pm_project_task.number.3'
		dataType: string
		lineageTag: eea48a29-aca3-46d2-861c-ee6ec981bf7d
		summarizeBy: none
		sourceColumn: Ficha - pm_project_task.number.3

		annotation SummarizationSetBy = Automatic

	column 'Ficha - pm_project_task.number.4'
		dataType: string
		lineageTag: 4ded7fc7-98ae-4ec1-95e3-9893db0f5a3b
		summarizeBy: none
		sourceColumn: Ficha - pm_project_task.number.4

		annotation SummarizationSetBy = Automatic

	column 'Ficha - pm_project_task.number.5'
		dataType: string
		lineageTag: dad43ca3-902e-4b3c-8ca0-4fe5bdcc52a7
		summarizeBy: none
		sourceColumn: Ficha - pm_project_task.number.5

		annotation SummarizationSetBy = Automatic

	column 'Ficha - pm_project_task.number.6'
		dataType: string
		lineageTag: 19b0b3ed-5161-42d5-8cd6-0851e9aeddee
		summarizeBy: none
		sourceColumn: Ficha - pm_project_task.number.6

		annotation SummarizationSetBy = Automatic

	column 'Ficha - pm_project_task.number.7'
		dataType: string
		lineageTag: 43f3703a-8278-4234-b0d1-50f60bb2dfb2
		summarizeBy: none
		sourceColumn: Ficha - pm_project_task.number.7

		annotation SummarizationSetBy = Automatic

	column 'dv_size.1'
		dataType: string
		lineageTag: 70a324a6-421f-4094-bceb-227bd5d3c34c
		summarizeBy: none
		sourceColumn: dv_size.1

		annotation SummarizationSetBy = Automatic

	column 'dv_size.2'
		dataType: string
		lineageTag: 6dd8d384-33f6-4227-b75f-f9a7d41f0432
		summarizeBy: none
		sourceColumn: dv_size.2

		annotation SummarizationSetBy = Automatic

	column approved_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d2531c7d-6e90-4bff-8e4d-c348d35272ba
		summarizeBy: none
		sourceColumn: approved_end_date

		variation Variación
			isDefault
			relationship: f388878b-c6c3-4b04-8d77-beacf0ba176d
			defaultHierarchy: LocalDateTable_7de87549-a33d-45dc-bbe4-386ccf5b8352.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column approved_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0310866f-4662-43d1-8c5a-bf2a37d8203f
		summarizeBy: none
		sourceColumn: approved_start_date

		variation Variación
			isDefault
			relationship: eb53501d-99f1-4425-8f79-3bf13d5da7d6
			defaultHierarchy: LocalDateTable_b6e27933-cd52-48cb-92de-2a768a54b0ea.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column calculation_type
		dataType: string
		lineageTag: cba1d977-fb97-4248-abf6-9dd9dfb4c6de
		summarizeBy: none
		sourceColumn: calculation_type

		annotation SummarizationSetBy = Automatic

	column dv_calculation_type
		dataType: string
		lineageTag: 0a2ba5b8-2cc3-4211-8e71-ec6826bf8d78
		summarizeBy: none
		sourceColumn: dv_calculation_type

		annotation SummarizationSetBy = Automatic

	column contract
		dataType: string
		lineageTag: 356295f7-48ea-44e7-b0da-c61380a8f3b4
		summarizeBy: none
		sourceColumn: contract

		annotation SummarizationSetBy = Automatic

	column dv_contract
		dataType: string
		lineageTag: babc536c-0251-4463-aa58-fe5cc3ec2298
		summarizeBy: none
		sourceColumn: dv_contract

		annotation SummarizationSetBy = Automatic

	column model_id
		dataType: string
		lineageTag: 2b1fd5a7-6ee1-49f0-8f2b-3e24765061fe
		summarizeBy: none
		sourceColumn: model_id

		annotation SummarizationSetBy = Automatic

	column dv_model_id
		dataType: string
		lineageTag: d3dfc6d3-ca28-404f-92da-543e40f211a4
		summarizeBy: none
		sourceColumn: dv_model_id

		annotation SummarizationSetBy = Automatic

	column software_model
		dataType: string
		lineageTag: e1995700-e67b-4595-baae-388fd71da484
		summarizeBy: none
		sourceColumn: software_model

		annotation SummarizationSetBy = Automatic

	column dv_software_model
		dataType: string
		lineageTag: 88cb964a-95b5-4740-9fe0-f36d4b61468f
		summarizeBy: none
		sourceColumn: dv_software_model

		annotation SummarizationSetBy = Automatic

	column u_commented
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a6e9dca1-f211-4c65-8d94-e7f6b148e023
		summarizeBy: none
		sourceColumn: u_commented

		annotation SummarizationSetBy = Automatic

	column u_deferred_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 98e23e3c-ef9f-4165-883a-6047bc0a9eca
		summarizeBy: none
		sourceColumn: u_deferred_end_date

		variation Variación
			isDefault
			relationship: 86515d14-7948-4a4a-a2fd-fd81308d574e
			defaultHierarchy: LocalDateTable_96c04fc2-9454-4ef2-b3be-b32198279845.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_deferred_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f3266dda-27a2-4dea-a377-ebb9e0adde29
		summarizeBy: none
		sourceColumn: u_deferred_start_date

		variation Variación
			isDefault
			relationship: 628af2a2-b5b4-49be-b0b4-ff2a33cbad50
			defaultHierarchy: LocalDateTable_f028142e-1c17-4f22-9aac-83f2a1859787.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_digital_transformation
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 14fd7b1f-0231-4d7a-adc9-74ab5d086bb9
		summarizeBy: none
		sourceColumn: u_digital_transformation

		annotation SummarizationSetBy = Automatic

	column u_fases_rfi
		dataType: string
		lineageTag: f7d42191-3a73-4116-9caa-a2edd4c79ef5
		summarizeBy: none
		sourceColumn: u_fases_rfi

		annotation SummarizationSetBy = Automatic

	column dv_u_fases_rfi
		dataType: string
		lineageTag: 92f66b2b-d7f5-4b20-b8e1-2d64e0932af1
		summarizeBy: none
		sourceColumn: dv_u_fases_rfi

		annotation SummarizationSetBy = Automatic

	column u_operational_committee_comment
		dataType: string
		lineageTag: 8f617759-5d3a-4e8c-8015-170a3824ff62
		summarizeBy: none
		sourceColumn: u_operational_committee_comment

		annotation SummarizationSetBy = Automatic

	column u_origin_country_of_the_demand
		dataType: string
		lineageTag: c51bc8cc-85ea-43e2-a0b0-d20ca6144841
		summarizeBy: none
		sourceColumn: u_origin_country_of_the_demand

		annotation SummarizationSetBy = Automatic

	column u_payroll_area
		dataType: string
		lineageTag: 7f521468-3fa6-40b6-93f1-cf1078b6374b
		summarizeBy: none
		sourceColumn: u_payroll_area

		annotation SummarizationSetBy = Automatic

	column dv_u_payroll_area
		dataType: string
		lineageTag: e351d29e-d0f1-4872-af70-f43ab2e7448b
		summarizeBy: none
		sourceColumn: dv_u_payroll_area

		annotation SummarizationSetBy = Automatic

	column u_planned_capital
		dataType: double
		lineageTag: dcd57b8a-fd52-4069-a945-f04f06de25dc
		summarizeBy: sum
		sourceColumn: u_planned_capital

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_planned_operating
		dataType: double
		lineageTag: 869ecc14-5b11-452a-a98b-8fc10d60cf8d
		summarizeBy: sum
		sourceColumn: u_planned_operating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_program_manager
		dataType: string
		lineageTag: 74edfcd2-46b3-4632-8f94-03cd3e3f6a6d
		summarizeBy: none
		sourceColumn: u_program_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_program_manager
		dataType: string
		lineageTag: 87c3b319-7261-41b8-9fb5-41aa8634379f
		summarizeBy: none
		sourceColumn: dv_u_program_manager

		annotation SummarizationSetBy = Automatic

	column u_relevant_project_for_cio
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: dcc6ddb4-b0ca-4055-9f35-98f2dab11c96
		summarizeBy: none
		sourceColumn: u_relevant_project_for_cio

		annotation SummarizationSetBy = Automatic

	column u_rfi
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9efeba37-8f74-4fa3-8d00-5e6a9798b138
		summarizeBy: none
		sourceColumn: u_rfi

		annotation SummarizationSetBy = Automatic

	column u_selected_suppliers
		dataType: string
		lineageTag: 4f379db5-1d66-4f51-9f34-99cec705b3eb
		summarizeBy: none
		sourceColumn: u_selected_suppliers

		annotation SummarizationSetBy = Automatic

	column u_targets
		dataType: string
		lineageTag: e32f78d4-54ef-4ce2-9be0-0c072578ec94
		summarizeBy: none
		sourceColumn: u_targets

		annotation SummarizationSetBy = Automatic

	column u_total_planned_cost
		dataType: double
		lineageTag: 665c7e1e-5ad0-4260-9980-25e39a3e29cb
		summarizeBy: sum
		sourceColumn: u_total_planned_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dv_expense_type
		dataType: string
		lineageTag: 99597928-3040-477d-8d16-71c0d3b75a50
		summarizeBy: none
		sourceColumn: dv_expense_type

		annotation SummarizationSetBy = Automatic

	column expense_type
		dataType: string
		lineageTag: 2c0a9e85-0cd9-4d91-82e0-825221b732e1
		summarizeBy: none
		sourceColumn: expense_type

		annotation SummarizationSetBy = Automatic

	partition 'Ficha - dmn_demand' = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("QECCDWH.acciona.int,60001"),
				    DWH = Origen{[Name="DWH"]}[Data],
				    SERV_NOW_dmn_demand = DWH{[Schema="SERV_NOW",Item="dmn_demand"]}[Data],
				    #"Dividir columnas por delimitador" = Table.SplitColumn(SERV_NOW_dmn_demand, "related_records", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"related_records.1", "related_records.2", "related_records.3", "related_records.4", "related_records.5", "related_records.6", "related_records.7", "related_records.8"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Dividir columnas por delimitador",{{"related_records.1", type text}, {"related_records.2", type text}, {"related_records.3", type text}, {"related_records.4", type text}, {"related_records.5", type text}, {"related_records.6", type text}, {"related_records.7", type text}, {"related_records.8", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"active", "activity_due", "additional_assignee_list", "apm_idea_action", "dv_apm_idea_action", "approval", "dv_approval", "approval_history", "assessment_required", "assigned_to", "assignment_group", "assumptions", "barriers", "business_applications", "business_capabilities", "business_case", "business_duration", "business_service", "dv_business_service", "business_unit", "dv_business_unit", "calendar_duration", "dv_calendar_duration", "capital_outlay", "category", "change", "dv_change", "close_demand", "dv_close_demand", "close_notes", "closed_by", "dv_closed_by", "cmdb_ci", "dv_cmdb_ci", "cmdb_ci_business_app", "collaborators", "comments", "comments_and_work_notes", "company", "dv_company", "contact_type", "dv_contact_type", "correlation_display", "correlation_id", "defect", "dv_defect", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "demand_actual_cost", "demand_actual_effort", "dv_demand_actual_effort", "demand_manager", "department", "discount_rate", "due_date", "enablers", "escalation", "expected_risk", "expected_roi", "expected_start", "financial_benefit", "financial_return", "follow_up", "goal", "dv_goal", "goals", "group_list", "idea", "dv_idea", "impact", "impacted_business_units", "in_scope", "investment_class", "investment_type", "dv_investment_type", "irr_value", "knowledge", "labor_costs", "location", "dv_investment_class", "dv_location", "made_sla", "npv_value", "opened_by", "dv_opened_by", "dv_primary_program", "priority", "project_manager", "dv_project_manager", "rate_model", "dv_rate_model", "reassignment_count", "rejection_goto", "dv_rejection_goto", "requested_by", "resource_allocated_cost", "resource_planned_cost", "risk_of_not_performing", "risk_of_performing", "route_reason", "dv_route_reason", "score", "score_cost", "score_risk", "dv_score_risk", "score_size", "score_strategic_allignment", "score_value", "dv_score_value", "scrum_epic", "dv_scrum_epic", "scrum_story", "dv_scrum_story", "service_offering", "dv_service_offering", "size", "skills", "sla_due", "stage", "state", "strategic_objectives", "submitted_date", "submitter", "dv_submitter", "sys_class_name", "dv_sys_class_name", "sys_created_by", "sys_created_on", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "task_for", "dv_task_for", "time_worked", "dv_time_worked", "total_costs", "u_acciona_priority", "u_affected_portfolios", "u_ambito_global", "u_analysis_date", "u_approval_sent", "u_approved_date", "u_approver", "dv_u_approver", "u_architecture_analysis", "u_business_applications", "u_business_line", "dv_u_business_line", "u_catalog", "dv_u_catalog", "u_company", "dv_u_company", "u_concurrent_users", "dv_u_concurrent_users", "u_country", "dv_u_country", "u_criticality_level", "dv_u_criticality_level", "u_current_situation", "u_demand_type_description", "u_department", "dv_u_department", "u_dependencies", "u_due_date", "u_duration_to_manage_a_demand", "dv_u_duration_to_manage_a_demand", "u_duration_to_reach_analysis", "dv_u_duration_to_reach_analysis", "u_execution_type", "dv_u_execution_type", "u_external_vendor", "dv_u_external_vendor", "u_first_commettee_state", "dv_u_first_commettee_state", "u_first_committee_date", "dv_u_first_committee_date", "u_frecuency_of_use", "dv_u_frecuency_of_use", "u_impact", "dv_u_impact", "u_impacted_companies", "u_impacted_countries", "u_impacted_groups", "u_is_parent", "u_metal", "dv_u_metal", "u_module", "dv_u_module", "u_old_state", "u_openned_up", "u_parent_demand", "dv_u_parent_demand", "u_phone", "u_pilot", "u_planned_demand", "dv_u_planned_demand", "u_previous_groups", "u_priority_justification", "u_progress", "u_project_manager", "dv_u_project_manager", "u_qualification_date", "u_reasons_for_delay", "dv_u_reasons_for_delay", "u_ref_country", "dv_u_ref_country", "u_reg_country", "dv_u_reg_country", "u_reg_department", "dv_u_reg_department", "u_reg_division", "dv_u_reg_division", "u_reg_user", "dv_u_reg_user", "u_rejected_date", "u_relevant", "u_responded", "u_rfp", "dv_u_rfp", "u_run", "u_run_description", "u_second_commettee_state", "u_second_committee_date", "u_size", "dv_u_size", "u_sourcing", "u_status_report", "u_tic_unit", "u_time_to_manage_a_demand", "u_time_to_reach_analysis", "u_total_effort", "u_total_effort_req", "dv_u_total_effort_req", "u_total_planned_hours", "u_volume_impacted_users", "universal_request", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "urgency", "user_input", "variables", "visited_state", "watch_list", "wf_activity", "dv_wf_activity", "work_notes", "work_notes_list", "u_idl", "u_id_plan"}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Columnas quitadas", {"related_records.1"}, #"Ficha - pm_project", {"sys_id"}, "Ficha - pm_project", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project" = Table.ExpandTableColumn(#"Consultas combinadas", "Ficha - pm_project", {"number"}, {"Ficha - pm_project.number"}),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Se expandió Ficha - pm_project", {"related_records.2"}, #"Ficha - pm_project", {"sys_id"}, "Ficha - pm_project", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project1" = Table.ExpandTableColumn(#"Consultas combinadas1", "Ficha - pm_project", {"number"}, {"Ficha - pm_project.number.1"}),
				    #"Consultas combinadas2" = Table.NestedJoin(#"Se expandió Ficha - pm_project1", {"related_records.3"}, #"Ficha - pm_project", {"sys_id"}, "Ficha - pm_project", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project2" = Table.ExpandTableColumn(#"Consultas combinadas2", "Ficha - pm_project", {"number"}, {"Ficha - pm_project.number.2"}),
				    #"Consultas combinadas3" = Table.NestedJoin(#"Se expandió Ficha - pm_project2", {"related_records.4"}, #"Ficha - pm_project", {"sys_id"}, "Ficha - pm_project", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project3" = Table.ExpandTableColumn(#"Consultas combinadas3", "Ficha - pm_project", {"number"}, {"Ficha - pm_project.number.3"}),
				    #"Consultas combinadas4" = Table.NestedJoin(#"Se expandió Ficha - pm_project3", {"related_records.5"}, #"Ficha - pm_project", {"sys_id"}, "Ficha - pm_project", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project4" = Table.ExpandTableColumn(#"Consultas combinadas4", "Ficha - pm_project", {"number"}, {"Ficha - pm_project.number.4"}),
				    #"Consultas combinadas5" = Table.NestedJoin(#"Se expandió Ficha - pm_project4", {"related_records.6"}, #"Ficha - pm_project", {"sys_id"}, "Ficha - pm_project", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project5" = Table.ExpandTableColumn(#"Consultas combinadas5", "Ficha - pm_project", {"number"}, {"Ficha - pm_project.number.5"}),
				    #"Consultas combinadas6" = Table.NestedJoin(#"Se expandió Ficha - pm_project5", {"related_records.7"}, #"Ficha - pm_project", {"sys_id"}, "Ficha - pm_project", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project6" = Table.ExpandTableColumn(#"Consultas combinadas6", "Ficha - pm_project", {"number"}, {"Ficha - pm_project.number.6"}),
				    #"Consultas combinadas7" = Table.NestedJoin(#"Se expandió Ficha - pm_project6", {"related_records.8"}, #"Ficha - pm_project", {"sys_id"}, "Ficha - pm_project", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project7" = Table.ExpandTableColumn(#"Consultas combinadas7", "Ficha - pm_project", {"number"}, {"Ficha - pm_project.number.7"}),
				    #"Columnas combinadas" = Table.CombineColumns(#"Se expandió Ficha - pm_project7",{"Ficha - pm_project.number.7", "Ficha - pm_project.number.6", "Ficha - pm_project.number.5", "Ficha - pm_project.number.4", "Ficha - pm_project.number.3", "Ficha - pm_project.number.2", "Ficha - pm_project.number.1", "Ficha - pm_project.number"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"proyectos_generados"),
				    #"Consultas combinadas8" = Table.NestedJoin(#"Columnas combinadas", {"related_records.1"}, #"Ficha - rm_enhancement", {"sys_id"}, "Ficha - rm_enhancement", JoinKind.LeftOuter),
				    #"Se expandió Ficha - rm_enhancement" = Table.ExpandTableColumn(#"Consultas combinadas8", "Ficha - rm_enhancement", {"number"}, {"Ficha - rm_enhancement.number"}),
				    #"Consultas combinadas9" = Table.NestedJoin(#"Se expandió Ficha - rm_enhancement", {"related_records.2"}, #"Ficha - rm_enhancement", {"sys_id"}, "Ficha - rm_enhancement", JoinKind.LeftOuter),
				    #"Se expandió Ficha - rm_enhancement1" = Table.ExpandTableColumn(#"Consultas combinadas9", "Ficha - rm_enhancement", {"number"}, {"Ficha - rm_enhancement.number.1"}),
				    #"Consultas combinadas10" = Table.NestedJoin(#"Se expandió Ficha - rm_enhancement1", {"related_records.3"}, #"Ficha - rm_enhancement", {"sys_id"}, "Ficha - rm_enhancement", JoinKind.LeftOuter),
				    #"Se expandió Ficha - rm_enhancement2" = Table.ExpandTableColumn(#"Consultas combinadas10", "Ficha - rm_enhancement", {"number"}, {"Ficha - rm_enhancement.number.2"}),
				    #"Consultas combinadas11" = Table.NestedJoin(#"Se expandió Ficha - rm_enhancement2", {"related_records.4"}, #"Ficha - rm_enhancement", {"sys_id"}, "Ficha - rm_enhancement", JoinKind.LeftOuter),
				    #"Se expandió Ficha - rm_enhancement3" = Table.ExpandTableColumn(#"Consultas combinadas11", "Ficha - rm_enhancement", {"number"}, {"Ficha - rm_enhancement.number.3"}),
				    #"Consultas combinadas12" = Table.NestedJoin(#"Se expandió Ficha - rm_enhancement3", {"related_records.5"}, #"Ficha - rm_enhancement", {"sys_id"}, "Ficha - rm_enhancement", JoinKind.LeftOuter),
				    #"Se expandió Ficha - rm_enhancement4" = Table.ExpandTableColumn(#"Consultas combinadas12", "Ficha - rm_enhancement", {"number"}, {"Ficha - rm_enhancement.number.4"}),
				    #"Consultas combinadas13" = Table.NestedJoin(#"Se expandió Ficha - rm_enhancement4", {"related_records.5"}, #"Ficha - rm_enhancement", {"sys_id"}, "Ficha - rm_enhancement", JoinKind.LeftOuter),
				    #"Se expandió Ficha - rm_enhancement5" = Table.ExpandTableColumn(#"Consultas combinadas13", "Ficha - rm_enhancement", {"number"}, {"Ficha - rm_enhancement.number.5"}),
				    #"Consultas combinadas14" = Table.NestedJoin(#"Se expandió Ficha - rm_enhancement5", {"related_records.6"}, #"Ficha - rm_enhancement", {"sys_id"}, "Ficha - rm_enhancement", JoinKind.LeftOuter),
				    #"Se expandió Ficha - rm_enhancement6" = Table.ExpandTableColumn(#"Consultas combinadas14", "Ficha - rm_enhancement", {"number"}, {"Ficha - rm_enhancement.number.6"}),
				    #"Consultas combinadas15" = Table.NestedJoin(#"Se expandió Ficha - rm_enhancement6", {"related_records.7"}, #"Ficha - rm_enhancement", {"sys_id"}, "Ficha - rm_enhancement", JoinKind.LeftOuter),
				    #"Se expandió Ficha - rm_enhancement7" = Table.ExpandTableColumn(#"Consultas combinadas15", "Ficha - rm_enhancement", {"number"}, {"Ficha - rm_enhancement.number.7"}),
				    #"Consultas combinadas16" = Table.NestedJoin(#"Se expandió Ficha - rm_enhancement7", {"related_records.8"}, #"SERV_NOW rm_enhancement", {"sys_id"}, "SERV_NOW rm_enhancement", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW rm_enhancement" = Table.ExpandTableColumn(#"Consultas combinadas16", "SERV_NOW rm_enhancement", {"number"}, {"SERV_NOW rm_enhancement.number"}),
				    #"Columnas combinadas1" = Table.CombineColumns(#"Se expandió SERV_NOW rm_enhancement",{"Ficha - rm_enhancement.number.1", "Ficha - rm_enhancement.number.2", "Ficha - rm_enhancement.number.3", "Ficha - rm_enhancement.number.4", "Ficha - rm_enhancement.number.5", "Ficha - rm_enhancement.number.6", "Ficha - rm_enhancement.number.7", "SERV_NOW rm_enhancement.number"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Mejoras_generadas"),
				    #"Columnas combinadas2" = Table.CombineColumns(#"Columnas combinadas1",{"Ficha - rm_enhancement.number", "Mejoras_generadas"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Mejoras_generadas.1"),
				    #"Columnas combinadas3" = Table.CombineColumns(#"Columnas combinadas2",{"proyectos_generados", "Mejoras_generadas.1"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Proyectos_Mejoras_generados"),
				    #"Consultas combinadas17" = Table.NestedJoin(#"Columnas combinadas3", {"related_records.1"}, #"Ficha - pm_project_task", {"sys_id"}, "Ficha - pm_project_task", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project_task" = Table.ExpandTableColumn(#"Consultas combinadas17", "Ficha - pm_project_task", {"number"}, {"Ficha - pm_project_task.number"}),
				    #"Consultas combinadas18" = Table.NestedJoin(#"Se expandió Ficha - pm_project_task", {"related_records.2"}, #"Ficha - pm_project_task", {"sys_id"}, "Ficha - pm_project_task", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project_task1" = Table.ExpandTableColumn(#"Consultas combinadas18", "Ficha - pm_project_task", {"number"}, {"Ficha - pm_project_task.number.1"}),
				    #"Consultas combinadas19" = Table.NestedJoin(#"Se expandió Ficha - pm_project_task1", {"related_records.3"}, #"Ficha - pm_project_task", {"sys_id"}, "Ficha - pm_project_task", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project_task2" = Table.ExpandTableColumn(#"Consultas combinadas19", "Ficha - pm_project_task", {"number"}, {"Ficha - pm_project_task.number.2"}),
				    #"Consultas combinadas20" = Table.NestedJoin(#"Se expandió Ficha - pm_project_task2", {"related_records.4"}, #"Ficha - pm_project_task", {"sys_id"}, "Ficha - pm_project_task", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project_task3" = Table.ExpandTableColumn(#"Consultas combinadas20", "Ficha - pm_project_task", {"number"}, {"Ficha - pm_project_task.number.3"}),
				    #"Consultas combinadas21" = Table.NestedJoin(#"Se expandió Ficha - pm_project_task3", {"related_records.5"}, #"Ficha - pm_project_task", {"sys_id"}, "Ficha - pm_project_task", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project_task4" = Table.ExpandTableColumn(#"Consultas combinadas21", "Ficha - pm_project_task", {"number"}, {"Ficha - pm_project_task.number.4"}),
				    #"Consultas combinadas22" = Table.NestedJoin(#"Se expandió Ficha - pm_project_task4", {"related_records.6"}, #"Ficha - pm_project_task", {"sys_id"}, "Ficha - pm_project_task", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project_task5" = Table.ExpandTableColumn(#"Consultas combinadas22", "Ficha - pm_project_task", {"number"}, {"Ficha - pm_project_task.number.5"}),
				    #"Consultas combinadas23" = Table.NestedJoin(#"Se expandió Ficha - pm_project_task5", {"related_records.7"}, #"Ficha - pm_project_task", {"sys_id"}, "Ficha - pm_project_task", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project_task6" = Table.ExpandTableColumn(#"Consultas combinadas23", "Ficha - pm_project_task", {"number"}, {"Ficha - pm_project_task.number.6"}),
				    #"Consultas combinadas24" = Table.NestedJoin(#"Se expandió Ficha - pm_project_task6", {"related_records.8"}, #"Ficha - pm_project_task", {"sys_id"}, "Ficha - pm_project_task", JoinKind.LeftOuter),
				    #"Se expandió Ficha - pm_project_task7" = Table.ExpandTableColumn(#"Consultas combinadas24", "Ficha - pm_project_task", {"number"}, {"Ficha - pm_project_task.number.7"}),
				    #"Dividir columna por delimitador" = Table.SplitColumn(#"Se expandió Ficha - pm_project_task7", "dv_size", Splitter.SplitTextByDelimiter(":", QuoteStyle.Csv), {"dv_size.1", "dv_size.2"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Dividir columna por delimitador",{{"dv_size.1", type text}, {"dv_size.2", type text}}),
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado1", each ([dv_portfolio] = "EN.ACCIONA Solar" or [dv_portfolio] = "EN.Desarrollo de Negocio-G.clientes CRM" or [dv_portfolio] = "EN.Desarrollo de Negocio-G.Doc. & Otros" or [dv_portfolio] = "EN.Desarrollo de Negocio-Planificación y Control" or [dv_portfolio] = "EN.Financiero - Finanzas" or [dv_portfolio] = "EN.Gestión de la Energía - Análisis de mercados" or [dv_portfolio] = "EN.Gestión de la Energía - Comercial" or [dv_portfolio] = "EN.Gestión de la Energía - Mayorista" or [dv_portfolio] = "EN.Gestión de la Energía - Operaciones Comercialización" or [dv_portfolio] = "EN.Gestión de la Energía – Estudios, GdR y Trading" or [dv_portfolio] = "EN.I&C - Construcción" or [dv_portfolio] = "EN.I&C - Ingeniería y Ofertas" or [dv_portfolio] = "EN.I&C - Organización de proyectos" or [dv_portfolio] = "EN.Innovación" or [dv_portfolio] = "EN.Oficina de Estudios CEO" or [dv_portfolio] = "EN.Producción - CECOER" or [dv_portfolio] = "EN.Producción - Eólica" or [dv_portfolio] = "EN.Producción - Gestión de Activos" or [dv_portfolio] = "EN.Producción - HTFV" or [dv_portfolio] = "EN.QSE" or [dv_portfolio] = "EN.RRHH" or [dv_portfolio] = "EN.Serv. Energéticos - A. Recarga" or [dv_portfolio] = "EN.Serv. Energéticos - ESCO" or [dv_portfolio] = "EN.Supply Chain" or [dv_portfolio] = "EN.TIC - Aplicaciones"))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

