table Proyectos_Padre_Evo4&5
	lineageTag: 2793e489-59d8-4aa3-af2c-b28faaae4f3f

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ecdf97b2-b5ac-49db-a96d-ac26b9f2bbc3
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column demand
		dataType: string
		lineageTag: 3b6c6ebc-e2f5-4d4f-98c1-fd425a4f89cc
		summarizeBy: none
		sourceColumn: demand

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: 98ca7370-5d1b-4b1b-a8d6-ac4ec8c45dcb
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: a0caac76-909d-43f7-8481-2afe56609518
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column u_project_type
		dataType: string
		lineageTag: 2858315f-c47c-4ab4-becb-104ee5c7a93b
		summarizeBy: none
		sourceColumn: u_project_type

		annotation SummarizationSetBy = Automatic

	column dv_u_project_type
		dataType: string
		lineageTag: ea9c9e9e-0eef-4c63-b1a3-a23dc5547234
		summarizeBy: none
		sourceColumn: dv_u_project_type

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: 04617af5-b445-4ba7-95a0-4c44e5bdd365
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: 91461766-6ebe-4946-9bb1-0241f1750e6e
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column percent_complete
		dataType: double
		lineageTag: 78c85108-4b5a-4152-998d-70a4de4d671e
		summarizeBy: sum
		sourceColumn: percent_complete

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column primary_portfolio
		dataType: string
		lineageTag: de9634dd-b776-41a4-8ecb-7cb1193a27d6
		summarizeBy: none
		sourceColumn: primary_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_primary_portfolio
		dataType: string
		lineageTag: ab0107f8-f0e8-43af-97c8-798f11d2c60e
		summarizeBy: none
		sourceColumn: dv_primary_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: 1504bb11-73ff-4cb7-a145-d5430f4da55f
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: cf8809a0-78fe-483a-8f24-0eadaaef0827
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: 6c12e50f-b5e8-4ceb-8b16-df4853b8ca23
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column top_portfolio
		dataType: string
		lineageTag: df43e4f4-a552-4917-8019-87e61fceb419
		summarizeBy: none
		sourceColumn: top_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_top_portfolio
		dataType: string
		lineageTag: bfa2dd5e-dcfb-48ea-a428-14e0bfc9f46d
		summarizeBy: none
		sourceColumn: dv_top_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_top_task
		dataType: string
		lineageTag: a87953f4-82bb-4991-a267-b464ca423f72
		summarizeBy: none
		sourceColumn: dv_top_task

		annotation SummarizationSetBy = Automatic

	column top_task
		dataType: string
		lineageTag: 7d608fb5-10dc-4677-a553-94fb0b76bf7f
		summarizeBy: none
		sourceColumn: top_task

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: int64
		formatString: 0
		lineageTag: c1c9f9b0-1f6b-4888-a58b-ae62e0b9f85d
		summarizeBy: sum
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	column '_dv_priority - español'
		dataType: string
		lineageTag: 52ba0139-57bb-41ff-bb80-0a5516d950dd
		summarizeBy: none
		sourceColumn: _dv_priority - español

		annotation SummarizationSetBy = Automatic

	column dv_phase
		dataType: string
		lineageTag: d190ee1a-f4f0-45eb-a5bf-0b153bc18e40
		summarizeBy: none
		sourceColumn: dv_phase

		annotation SummarizationSetBy = Automatic

	column attr_based_planning
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a122009d-3d8e-419e-8c35-2dbb0f0d42ca
		summarizeBy: none
		sourceColumn: attr_based_planning

		annotation SummarizationSetBy = Automatic

	column auto_save
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 335acf5b-37c3-487a-bc78-c646188e0f3f
		summarizeBy: none
		sourceColumn: auto_save

		annotation SummarizationSetBy = Automatic

	column contract
		dataType: string
		lineageTag: 2722fc8f-ceed-46b8-b1f4-f4e1af852690
		summarizeBy: none
		sourceColumn: contract

		annotation SummarizationSetBy = Automatic

	column dv_contract
		dataType: string
		lineageTag: e86dbc59-dc71-4b37-a13e-9691fab87c33
		summarizeBy: none
		sourceColumn: dv_contract

		annotation SummarizationSetBy = Automatic

	column dv_expense_type
		dataType: string
		lineageTag: aa2538eb-a1e1-4aac-a1d2-2c57e0b8e56a
		summarizeBy: none
		sourceColumn: dv_expense_type

		annotation SummarizationSetBy = Automatic

	column dv_model_id
		dataType: string
		lineageTag: 84310c6a-3cad-4174-8610-ed8ee6d0b1e4
		summarizeBy: none
		sourceColumn: dv_model_id

		annotation SummarizationSetBy = Automatic

	column dv_software_model
		dataType: string
		lineageTag: 625064a1-dbe1-4fd0-8f6d-61316c54efd8
		summarizeBy: none
		sourceColumn: dv_software_model

		annotation SummarizationSetBy = Automatic

	column dv_u_devops_manager
		dataType: string
		lineageTag: 6bd81f3c-603d-4d92-8535-be41da12598d
		summarizeBy: none
		sourceColumn: dv_u_devops_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_pmo_manager
		dataType: string
		lineageTag: 3c316f76-576e-460e-b54c-42b0c2be9898
		summarizeBy: none
		sourceColumn: dv_u_pmo_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_qa_manager
		dataType: string
		lineageTag: 9cfcbe67-376b-4c80-bc98-b2ce58566be0
		summarizeBy: none
		sourceColumn: dv_u_qa_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_rfp_phases
		dataType: string
		lineageTag: 42ee349e-7f52-43a6-994d-2c89036d286f
		summarizeBy: none
		sourceColumn: dv_u_rfp_phases

		annotation SummarizationSetBy = Automatic

	column expense_type
		dataType: string
		lineageTag: 4ef6798d-2111-4412-9b32-e3652812ee39
		summarizeBy: none
		sourceColumn: expense_type

		annotation SummarizationSetBy = Automatic

	column group_resource_assignee
		dataType: string
		lineageTag: 8deb8163-720d-4392-bb7d-e8640829b64f
		summarizeBy: none
		sourceColumn: group_resource_assignee

		annotation SummarizationSetBy = Automatic

	column model_id
		dataType: string
		lineageTag: 5f5bd53c-43b5-4c79-9c75-b14324b1582a
		summarizeBy: none
		sourceColumn: model_id

		annotation SummarizationSetBy = Automatic

	column resource_assignee
		dataType: string
		lineageTag: 6bf40693-f261-4e72-b527-9f1e52191a08
		summarizeBy: none
		sourceColumn: resource_assignee

		annotation SummarizationSetBy = Automatic

	column software_model
		dataType: string
		lineageTag: afc9eb2f-d2ce-4fca-8076-1055f686ac35
		summarizeBy: none
		sourceColumn: software_model

		annotation SummarizationSetBy = Automatic

	column u_commented
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d1cfe988-d7bf-42e4-9299-811d65b8a6dd
		summarizeBy: none
		sourceColumn: u_commented

		annotation SummarizationSetBy = Automatic

	column u_devops_manager
		dataType: string
		lineageTag: 408aadac-572b-491b-846f-51b7f3f396a1
		summarizeBy: none
		sourceColumn: u_devops_manager

		annotation SummarizationSetBy = Automatic

	column u_impacted_applications
		dataType: string
		lineageTag: 0ded5751-178b-4e46-877e-38c3798332be
		summarizeBy: none
		sourceColumn: u_impacted_applications

		annotation SummarizationSetBy = Automatic

	column u_operational_committee_comment
		dataType: string
		lineageTag: 628c9e0c-d70f-4475-ab80-acf28735c287
		summarizeBy: none
		sourceColumn: u_operational_committee_comment

		annotation SummarizationSetBy = Automatic

	column u_project_typology
		dataType: string
		lineageTag: ef17c9bc-d6e1-4621-964b-d161d5317963
		summarizeBy: none
		sourceColumn: u_project_typology

		annotation SummarizationSetBy = Automatic

	column u_qa_manager
		dataType: string
		lineageTag: aa19e99e-bc95-426c-afd8-8817da884097
		summarizeBy: none
		sourceColumn: u_qa_manager

		annotation SummarizationSetBy = Automatic

	column u_relevant_project_for_cio
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f1823dee-06a9-4867-a562-fcf57ce8b791
		summarizeBy: none
		sourceColumn: u_relevant_project_for_cio

		annotation SummarizationSetBy = Automatic

	column u_rfp_phases
		dataType: string
		lineageTag: e4f02788-8dd9-4062-a0c8-afbaf52b798c
		summarizeBy: none
		sourceColumn: u_rfp_phases

		annotation SummarizationSetBy = Automatic

	column u_percent_complete_estimated
		dataType: double
		lineageTag: 300add43-0a66-433a-935c-4538e304230e
		summarizeBy: sum
		sourceColumn: u_percent_complete_estimated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Proyectos_Padre_Evo4&5-e9700026-013d-4f10-b594-379ca182de56 = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "DWH"),
				    SERV_NOW_pm_project = Origen{[Schema="SERV_NOW",Item="pm_project"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_pm_project,{"activity_due", "actual_benefits", "additional_assignee_list", "allow_dates_outside_schedule", "approval", "dv_approval", "approval_history", "approval_set", "approved_end_date", "approved_start_date", "assigned_to", "dv_assigned_to", "assignment_group", "dv_assignment_group", "assumptions", "backlog_definition", "dv_backlog_definition", "barriers", "benefits", "budget_cost", "business_applications", "business_capabilities", "business_case", "business_duration", "dv_business_duration", "business_service", "dv_business_service", "business_unit", "dv_business_unit", "calculation_type", "dv_calculation_type", "calendar_duration", "dv_calendar_duration", "capex_cost", "capex_estimate_to_completion", "capex_forecast_cost", "close_notes", "closed_at", "closed_by", "dv_closed_by", "cmdb_ci", "dv_cmdb_ci", "cmdb_ci_business_app", "dv_cmdb_ci_business_app", "comments", "comments_and_work_notes", "company", "dv_company", "constraint_date", "contact_type", "dv_contact_type", "correlation_display", "correlation_id", "cost", "critical_path", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "dv_demand", "department", "dv_department", "dependency", "description", "discount_rate", "due_date", "duration", "dv_duration", "effort", "dv_effort", "enablers", "end", "end_date", "end_date_derived_from", "dv_end_date_derived_from", "escalation", "dv_escalation", "estimate_to_completion", "execution_type", "dv_execution_type", "expected_start", "follow_up", "forecast_cost", "goal", "dv_goal", "goals", "group_list", "has_conflict", "impact", "dv_impact", "impacted_business_units", "in_scope", "investment_class", "dv_investment_class", "investment_type", "dv_investment_type", "irr_value", "key_milestone", "knowledge", "level", "location", "dv_location", "made_sla", "marked_for_delete", "milestone", "mpp_task_id", "npv_value", "opened_at", "opened_by", "dv_opened_by", "opex_cost", "opex_estimate_to_completion", "opex_forecast_cost", "order", "orig_sys_id", "dv_orig_sys_id", "orig_top_task_id", "dv_orig_top_task_id", "out_of_scope", "override_status", "phase", "phase_type", "dv_phase_type", "primary_program", "dv_primary_program", "project_schedule_date_format", "dv_project_schedule_date_format", "project_manager", "dv_project_manager", "project_type", "dv_project_type", "rate_model", "dv_rate_model", "reassignment_count", "rejection_goto", "dv_rejection_goto", "relation_applied", "dv_relation_applied", "remaining_duration", "dv_remaining_duration", "remaining_effort", "dv_remaining_effort", "resource_allocated_cost", "resource_planned_cost", "resources_from_resource_plan", "risk", "dv_risk", "risk_cost", "risk_of_not_performing", "risk_of_performing", "roi", "rollup", "route_reason", "dv_route_reason", "run_calc_brs", "schedule", "dv_schedule", "schedule_end_date", "schedule_start_date", "score", "score_risk", "dv_score_risk", "score_size", "dv_score_size", "score_value", "dv_score_value", "service_offering", "dv_service_offering", "shadow", "show_on_program_status_report", "skills", "sla_due", "start", "start_date", "start_date_derived_from", "dv_start_date_derived_from", "status", "dv_status", "strategic_objectives", "sub_tree_root", "dv_sub_tree_root", "sys_class_name", "dv_sys_class_name", "sys_created_by", "sys_created_on", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "task", "task_effective_number", "task_for", "dv_task_for", "time_card_at_top_task", "time_card_preference", "dv_time_card_preference", "time_component_from_planned", "time_constraint", "dv_time_constraint", "time_worked", "dv_time_worked", "time_zone", "title", "top_program", "dv_top_program", "u_acciona_priority", "u_affected_portfolios", "u_ambito_global", "u_benefit_check", "u_benefits", "u_business_line", "dv_u_business_line", "u_catalog", "dv_u_catalog", "u_changes", "u_changes_comments", "u_conditions_restrictions", "u_cost_comments", "u_costs", "u_current_situation", "u_deliverables", "u_deliverables_comments", "u_demand_type_description", "u_department", "dv_u_department", "u_dependencies", "u_deviation_in_costs", "u_deviation_in_duration", "u_digital_transformation", "u_eficiency_using_rrhh", "u_end_date_deviation", "u_external_vendor", "dv_u_external_vendor", "u_id_plan", "u_impacted_companies", "u_impacted_countries", "u_incidents", "u_incidents_comments", "u_indicator_1", "u_lessons_learned", "u_live_changes", "u_live_risks", "u_metal", "dv_u_metal", "u_monitoring_indicators", "u_outsourcing", "u_payroll_area", "dv_u_payroll_area", "u_phone", "u_planned_demand", "dv_u_planned_demand", "u_planned_resource_plan_effort", "u_previous_groups", "u_problems", "u_progress", "u_project_impact", "u_project_monitoring", "u_project_phase", "dv_u_project_phase", "u_reasons_for_delay_reject", "dv_u_reasons_for_delay_reject", "u_ref_country", "dv_u_ref_country", "u_relevant", "u_responded", "u_risks", "u_risks_comments", "u_run", "u_run_description", "u_schedule", "u_schedule_comments", "u_size", "dv_u_size", "u_state_date", "u_suggestions_to_improve", "u_sum_planned_hours", "u_sum_time_cards", "u_targets", "u_tic_unit", "dv_u_tic_unit", "u_url", "u_version", "u_volume_of_impacted_users", "universal_request", "dv_universal_request", "update_actual_effort_from_time_card", "dv_update_actual_effort_from_time_card", "update_score_on_value_change", "dv_update_score_on_value_change", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "urgency", "dv_urgency", "user_input", "value", "variables", "version", "watch_list", "wbs", "wbs_order", "wf_activity", "dv_wf_activity", "work_cost", "work_duration", "dv_work_duration", "work_effort", "dv_work_effort", "work_end", "work_notes", "work_notes_list", "work_start", "x_29185_external_f_total_financed", "dv_u_project_typology", "u_restrictions", "u_completion_criteria", "u_pmo_manager", "html_description"}),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Columnas quitadas",{"active", "demand", "sys_id", "number", "parent", "dv_parent", "percent_complete", "primary_portfolio", "dv_primary_portfolio", "dv_priority", "short_description", "state", "dv_state", "top_portfolio", "dv_top_portfolio", "dv_top_task", "u_project_type", "dv_u_project_type", "top_task"}),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Columnas reordenadas",{"state"}),
				    #"Columnas reordenadas1" = Table.ReorderColumns(#"Columnas quitadas1",{"active", "demand", "sys_id", "number", "u_project_type", "dv_u_project_type", "dv_parent", "parent", "percent_complete", "primary_portfolio", "dv_primary_portfolio", "dv_priority", "short_description", "dv_state", "top_portfolio", "dv_top_portfolio", "dv_top_task", "top_task"}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas reordenadas1", each ([dv_u_project_type] = "Applications Maintenance")),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Filas filtradas", "dv_priority", "_dv_priority - español"),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columna duplicada","1 - Critical","1 - Crítica",Replacer.ReplaceText,{"_dv_priority - español"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","2 - High","2 - Alta",Replacer.ReplaceText,{"_dv_priority - español"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","3 - Moderate","3 - Moderada",Replacer.ReplaceText,{"_dv_priority - español"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","4 - Low","4 - Baja",Replacer.ReplaceText,{"_dv_priority - español"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","5 - Very Low","5 - Muy baja",Replacer.ReplaceText,{"_dv_priority - español"})
				in
				    #"Valor reemplazado4"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

