table 'SERV_NOW PROYECTOS - Mto'
	lineageTag: 26aeee3a-27b5-4d81-a007-6da9f785a922

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: da7fddbb-1d59-450d-90a7-f0a623e0d419
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column cmdb_ci_business_app
		dataType: string
		lineageTag: 0f8f9466-0437-4653-8fc9-3a16bb1a48cf
		summarizeBy: none
		sourceColumn: cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci_business_app
		dataType: string
		lineageTag: 497eba7b-f978-48ec-8500-7e215a133905
		summarizeBy: none
		sourceColumn: dv_cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column demand
		dataType: string
		lineageTag: 36e6ad41-fea6-476b-bcb4-2e12f76230b9
		summarizeBy: none
		sourceColumn: demand

		annotation SummarizationSetBy = Automatic

	column dv_demand
		dataType: string
		lineageTag: 63c5c3d9-fba1-4f8d-8722-1809849f50a1
		summarizeBy: none
		sourceColumn: dv_demand

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: f4e089bb-f28c-4c77-9086-fbc6e59f423f
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 6bf487b4-f645-4ede-bf3e-625f5c6b75d0
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: 2367f576-b7f3-4af1-ba40-77bc759b84f5
			defaultHierarchy: LocalDateTable_804282ab-30b9-4e41-8391-b9fd6736981b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: 58adaa0b-995a-4712-bbdd-69d30c6932ee
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: 1f31814e-65b1-47cf-8420-6e727159aa9a
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column percent_complete
		dataType: double
		lineageTag: 3bdeb169-7d6c-4be4-a6fa-8150a85aa56f
		summarizeBy: sum
		sourceColumn: percent_complete

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column phase
		dataType: string
		lineageTag: 94c0677f-3937-4d1d-be67-28645aa8512e
		summarizeBy: none
		sourceColumn: phase

		annotation SummarizationSetBy = Automatic

	column dv_phase
		dataType: string
		lineageTag: e8fe7877-79f3-4449-981f-9c5cb70d33ac
		summarizeBy: none
		sourceColumn: dv_phase

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: int64
		formatString: 0
		lineageTag: 3029322f-06d5-4f34-8b80-496459c9cc3e
		summarizeBy: sum
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: 0a7ef2b4-cebf-458a-9767-53a8098fb2bf
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 750b2e7a-e2eb-4b32-a2f5-b9478509a488
		summarizeBy: none
		sourceColumn: start_date

		variation Variación
			isDefault
			relationship: bc24ac3f-965c-4186-9e0b-3e1c2c73fa89
			defaultHierarchy: LocalDateTable_cdb5c3e8-e979-465c-981b-d0500299dc2f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column state
		dataType: int64
		formatString: 0
		lineageTag: 6fefee5d-9750-493c-a2f2-754fcfb8bd79
		summarizeBy: sum
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: c552fc45-80d9-4761-86f8-78dcb33014df
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: 9cf6737a-f0a1-4417-837f-509a45472d88
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column top_task
		dataType: string
		lineageTag: 5693bd8c-4e87-4afb-9511-d4f7e429c27d
		summarizeBy: none
		sourceColumn: top_task

		annotation SummarizationSetBy = Automatic

	column dv_top_task
		dataType: string
		lineageTag: cfb0524c-b81f-4894-9590-3c7b9590c580
		summarizeBy: none
		sourceColumn: dv_top_task

		annotation SummarizationSetBy = Automatic

	column u_project_phase
		dataType: string
		lineageTag: 26b95ff7-6936-4db6-8dc0-34457ad51ec8
		summarizeBy: none
		sourceColumn: u_project_phase

		annotation SummarizationSetBy = Automatic

	column dv_u_project_phase
		dataType: string
		lineageTag: 7a01b8a8-f0f2-49d0-a62f-fc71213027e5
		summarizeBy: none
		sourceColumn: dv_u_project_phase

		annotation SummarizationSetBy = Automatic

	column u_project_type
		dataType: string
		lineageTag: f3670f1e-11ea-400d-a8a4-4b7aa204cc69
		summarizeBy: none
		sourceColumn: u_project_type

		annotation SummarizationSetBy = Automatic

	column dv_u_project_type
		dataType: string
		lineageTag: f03a384b-418e-4c68-b1f4-2087cd52e6f3
		summarizeBy: none
		sourceColumn: dv_u_project_type

		annotation SummarizationSetBy = Automatic

	column dv_u_project_typology
		dataType: string
		lineageTag: 838b8c25-ee42-4784-9d7f-97a26389c50e
		summarizeBy: none
		sourceColumn: dv_u_project_typology

		annotation SummarizationSetBy = Automatic

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 532f6bc0-e4b6-41f7-9b31-f2f509db95b2
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: 564fe75f-614b-4969-9c4d-ea1edba57fce
			defaultHierarchy: LocalDateTable_2683fbab-a984-460a-836e-a8213d70c79b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column attr_based_planning
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a1b0c8e3-7c26-43aa-b521-6a4fe57aeff4
		summarizeBy: none
		sourceColumn: attr_based_planning

		annotation SummarizationSetBy = Automatic

	column auto_save
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 97c74811-acb9-4a64-ad52-5486fcd4539d
		summarizeBy: none
		sourceColumn: auto_save

		annotation SummarizationSetBy = Automatic

	column contract
		dataType: string
		lineageTag: 4eeb4dd6-5c29-4fc3-9524-f2791f3e2c31
		summarizeBy: none
		sourceColumn: contract

		annotation SummarizationSetBy = Automatic

	column dv_contract
		dataType: string
		lineageTag: 280e3925-35b5-401e-a073-9c592afa27d2
		summarizeBy: none
		sourceColumn: dv_contract

		annotation SummarizationSetBy = Automatic

	column dv_expense_type
		dataType: string
		lineageTag: 982b5adb-57fb-45f8-aeb3-f449951acebd
		summarizeBy: none
		sourceColumn: dv_expense_type

		annotation SummarizationSetBy = Automatic

	column dv_model_id
		dataType: string
		lineageTag: 03be98fd-386f-48e6-805c-4978564e7afa
		summarizeBy: none
		sourceColumn: dv_model_id

		annotation SummarizationSetBy = Automatic

	column dv_software_model
		dataType: string
		lineageTag: 8b21b514-d8db-43a5-9930-4275a08723bc
		summarizeBy: none
		sourceColumn: dv_software_model

		annotation SummarizationSetBy = Automatic

	column dv_u_devops_manager
		dataType: string
		lineageTag: 8f9c0a8c-f34c-4007-9899-d8e934e80409
		summarizeBy: none
		sourceColumn: dv_u_devops_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_pmo_manager
		dataType: string
		lineageTag: 914e252e-18e0-47bf-82f5-9da2060f1d0e
		summarizeBy: none
		sourceColumn: dv_u_pmo_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_qa_manager
		dataType: string
		lineageTag: dc0cf23b-5085-4586-8bbc-0030f9312398
		summarizeBy: none
		sourceColumn: dv_u_qa_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_rfp_phases
		dataType: string
		lineageTag: 1e6dcf6e-a72f-495d-93e4-16d29fa126d9
		summarizeBy: none
		sourceColumn: dv_u_rfp_phases

		annotation SummarizationSetBy = Automatic

	column expense_type
		dataType: string
		lineageTag: 0bd4b564-3bd5-4a21-802e-d808666a4aaf
		summarizeBy: none
		sourceColumn: expense_type

		annotation SummarizationSetBy = Automatic

	column group_resource_assignee
		dataType: string
		lineageTag: dc0ebf35-7b5a-4b3d-b132-290cb1ac3fa7
		summarizeBy: none
		sourceColumn: group_resource_assignee

		annotation SummarizationSetBy = Automatic

	column model_id
		dataType: string
		lineageTag: 5eb0daf6-7014-46bd-b88b-e5b3823897a4
		summarizeBy: none
		sourceColumn: model_id

		annotation SummarizationSetBy = Automatic

	column resource_assignee
		dataType: string
		lineageTag: 3ba95940-372d-4748-b81e-4ff814710fc2
		summarizeBy: none
		sourceColumn: resource_assignee

		annotation SummarizationSetBy = Automatic

	column software_model
		dataType: string
		lineageTag: 024d04ef-d582-4d77-938e-f849f96fa9e1
		summarizeBy: none
		sourceColumn: software_model

		annotation SummarizationSetBy = Automatic

	column u_commented
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f974fd39-e96f-4aeb-96b0-86d2e844470b
		summarizeBy: none
		sourceColumn: u_commented

		annotation SummarizationSetBy = Automatic

	column u_devops_manager
		dataType: string
		lineageTag: 7955f922-f919-4d70-a053-e6ef8211c93a
		summarizeBy: none
		sourceColumn: u_devops_manager

		annotation SummarizationSetBy = Automatic

	column u_impacted_applications
		dataType: string
		lineageTag: 00a3f95f-ad93-4480-879c-9d0fa6900a5c
		summarizeBy: none
		sourceColumn: u_impacted_applications

		annotation SummarizationSetBy = Automatic

	column u_operational_committee_comment
		dataType: string
		lineageTag: ff121990-6e64-4e2f-90a4-7aaa6a3cda43
		summarizeBy: none
		sourceColumn: u_operational_committee_comment

		annotation SummarizationSetBy = Automatic

	column u_project_typology
		dataType: string
		lineageTag: 0c5977a8-2134-45d5-b739-424153e419eb
		summarizeBy: none
		sourceColumn: u_project_typology

		annotation SummarizationSetBy = Automatic

	column u_qa_manager
		dataType: string
		lineageTag: f23e250c-4c4e-476a-a1f3-a442dbcd7090
		summarizeBy: none
		sourceColumn: u_qa_manager

		annotation SummarizationSetBy = Automatic

	column u_relevant_project_for_cio
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5738a0f2-8e7d-41c5-b240-d568ecc52054
		summarizeBy: none
		sourceColumn: u_relevant_project_for_cio

		annotation SummarizationSetBy = Automatic

	column u_rfp_phases
		dataType: string
		lineageTag: 4a52fd45-a66b-475e-8af6-94a9aa9ef188
		summarizeBy: none
		sourceColumn: u_rfp_phases

		annotation SummarizationSetBy = Automatic

	column u_percent_complete_estimated
		dataType: double
		lineageTag: 3811ca78-60db-4b2a-8c17-edd33cbc6d08
		summarizeBy: sum
		sourceColumn: u_percent_complete_estimated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'SERV_NOW PROYECTOS - Mto-ce506cb8-d5e6-49d9-a994-4d2bdbe28937' = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "DWH"),
				    SERV_NOW_pm_project = Origen{[Schema="SERV_NOW",Item="pm_project"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_pm_project,{"activity_due", "actual_benefits", "additional_assignee_list", "allow_dates_outside_schedule", "approval", "dv_approval", "approval_history", "approval_set", "approved_end_date", "approved_start_date", "assigned_to", "dv_assigned_to", "assignment_group", "dv_assignment_group", "assumptions", "backlog_definition", "dv_backlog_definition", "barriers", "benefits", "budget_cost", "business_applications", "business_capabilities", "business_case", "business_duration", "dv_business_duration", "business_service", "dv_business_service", "business_unit", "dv_business_unit", "calculation_type", "dv_calculation_type", "calendar_duration", "dv_calendar_duration", "capex_cost", "capex_estimate_to_completion", "capex_forecast_cost", "close_notes", "closed_by", "dv_closed_by", "cmdb_ci", "dv_cmdb_ci", "comments", "comments_and_work_notes", "company", "dv_company", "constraint_date", "contact_type", "dv_contact_type", "correlation_display", "correlation_id", "cost", "critical_path", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "department", "dv_department", "dependency", "description", "discount_rate", "due_date", "duration", "dv_duration", "effort", "dv_effort", "enablers", "end", "end_date", "end_date_derived_from", "dv_end_date_derived_from", "escalation", "dv_escalation", "estimate_to_completion", "execution_type", "dv_execution_type", "expected_start", "follow_up", "forecast_cost", "goal", "dv_goal", "goals", "group_list", "has_conflict", "impact", "dv_impact", "impacted_business_units", "in_scope", "investment_class", "dv_investment_class", "investment_type", "dv_investment_type", "irr_value", "key_milestone", "knowledge", "level", "location", "dv_location", "made_sla", "marked_for_delete", "milestone", "mpp_task_id", "npv_value", "opened_by", "dv_opened_by", "opex_cost", "opex_estimate_to_completion", "opex_forecast_cost", "order", "orig_sys_id", "dv_orig_sys_id", "orig_top_task_id", "dv_orig_top_task_id", "out_of_scope", "override_status", "phase_type", "dv_phase_type", "primary_portfolio", "dv_primary_portfolio", "primary_program", "dv_primary_program", "project_manager", "dv_project_manager", "project_schedule_date_format", "dv_project_schedule_date_format", "project_type", "dv_project_type", "rate_model", "dv_rate_model", "reassignment_count", "rejection_goto", "dv_rejection_goto", "relation_applied", "dv_relation_applied", "remaining_duration", "dv_remaining_duration", "remaining_effort", "dv_remaining_effort", "resource_allocated_cost", "resource_planned_cost", "resources_from_resource_plan", "risk", "dv_risk", "risk_cost", "risk_of_not_performing", "risk_of_performing", "roi", "rollup", "route_reason", "dv_route_reason", "run_calc_brs", "schedule", "dv_schedule", "schedule_end_date", "schedule_start_date", "score", "score_risk", "dv_score_risk", "score_size", "dv_score_size", "score_value", "dv_score_value", "service_offering", "dv_service_offering", "shadow", "short_description", "show_on_program_status_report", "skills", "sla_due", "start", "start_date_derived_from", "dv_start_date_derived_from", "dv_status", "strategic_objectives", "sub_tree_root", "dv_sub_tree_root", "sys_class_name", "dv_sys_class_name", "sys_created_by", "sys_created_on", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "task", "task_effective_number", "task_for", "dv_task_for", "time_card_at_top_task", "time_card_preference", "dv_time_card_preference", "time_component_from_planned", "time_constraint", "dv_time_constraint", "time_worked", "dv_time_worked", "time_zone", "title", "top_portfolio", "dv_top_portfolio", "top_program", "dv_top_program", "u_acciona_priority", "u_affected_portfolios", "u_ambito_global", "u_benefit_check", "u_benefits", "u_business_line", "dv_u_business_line", "u_catalog", "dv_u_catalog", "u_changes", "u_changes_comments", "u_conditions_restrictions", "u_cost_comments", "u_costs", "u_current_situation", "u_deliverables", "u_deliverables_comments", "u_demand_type_description", "u_department", "dv_u_department", "u_dependencies", "u_deviation_in_costs", "u_deviation_in_duration", "u_digital_transformation", "u_eficiency_using_rrhh", "u_end_date_deviation", "u_external_vendor", "dv_u_external_vendor", "u_id_plan", "u_impacted_companies", "u_impacted_countries", "u_incidents", "u_incidents_comments", "u_indicator_1", "u_lessons_learned", "u_live_changes", "u_live_risks", "u_metal", "dv_u_metal", "u_monitoring_indicators", "u_outsourcing", "u_payroll_area", "dv_u_payroll_area", "u_phone", "u_planned_demand", "dv_u_planned_demand", "u_planned_resource_plan_effort", "u_previous_groups", "u_problems", "u_progress", "u_project_impact", "u_project_monitoring"}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas quitadas", each ([dv_u_project_type] = "Applications Maintenance")),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Filas filtradas",{"u_reasons_for_delay_reject", "dv_u_reasons_for_delay_reject", "u_ref_country", "dv_u_ref_country", "u_relevant", "u_responded", "u_risks", "u_risks_comments", "u_run", "u_run_description", "u_schedule", "u_schedule_comments", "u_size", "dv_u_size", "u_state_date", "u_suggestions_to_improve", "u_sum_planned_hours", "u_sum_time_cards", "u_targets", "u_tic_unit", "dv_u_tic_unit", "u_url", "u_version", "u_volume_of_impacted_users", "universal_request", "dv_universal_request", "update_actual_effort_from_time_card", "dv_update_actual_effort_from_time_card", "update_score_on_value_change", "dv_update_score_on_value_change", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "urgency", "dv_urgency", "user_input", "value", "variables", "version", "watch_list", "wbs", "wbs_order", "wf_activity", "dv_wf_activity", "work_cost", "work_duration", "dv_work_duration", "work_effort", "dv_work_effort", "work_end", "work_notes", "work_notes_list", "work_start", "x_29185_external_f_total_financed", "u_restrictions", "u_completion_criteria", "u_pmo_manager", "html_description"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Columnas quitadas1", each ([demand] = "")),
				    #"Columnas quitadas2" = Table.RemoveColumns(#"Filas filtradas1",{"status"})
				in
				    #"Columnas quitadas2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

