table 'Tabla - Business Application - ServiceNow'
	lineageTag: 1d99b239-286a-4a2a-b4fc-94cb10bfd670

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ed3cff48-8e0e-456d-a6ec-114580eb7c21
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: bc6fcd7d-4566-4cc9-8fd3-6e8dc87f5df1
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: 82b329d6-6525-45eb-91ce-40134668e42f
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	partition 'Tabla - Business Application - ServiceNow-965e0d44-e2fd-43f8-a07c-b20dd7ee448e' = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "DWH"),
				    SERV_NOW_cmdb_ci_business_app = Origen{[Schema="SERV_NOW",Item="cmdb_ci_business_app"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_cmdb_ci_business_app,{"active_user_count", "age", "apm_application_family", "dv_apm_application_family", "apm_application_profile", "dv_apm_application_profile", "apm_business_process", "dv_apm_business_process", "application_category", "dv_application_category", "application_manager", "dv_application_manager", "application_type", "dv_application_type", "appraisal_fiscal_type", "dv_appraisal_fiscal_type", "architecture_type", "dv_architecture_type", "asset", "dv_asset", "asset_tag", "assigned", "assigned_to", "dv_assigned_to", "assignment_group", "dv_assignment_group", "attestation_score", "attested", "attested_by", "dv_attested_by", "attested_date", "attributes", "audience_type", "dv_audience_type", "business_criticality", "dv_business_criticality", "business_unit", "dv_business_unit", "can_print", "category", "dv_category", "certified", "change_control", "dv_change_control", "checked_in", "checked_out", "cmdb_ot_entity", "dv_cmdb_ot_entity", "cmdb_software_product_model", "dv_cmdb_software_product_model", "comments", "company", "dv_company", "contract_end_date", "correlation_id", "cost", "cost_cc", "dv_cost_cc", "cost_center", "dv_cost_center", "currency", "dv_currency", "data_classification", "dv_data_classification", "delivery_date", "department", "dv_department", "discovery_source", "dv_discovery_source", "dns_domain", "due", "due_in", "dv_due_in", "duplicate_of", "dv_duplicate_of", "emergency_tier", "dv_emergency_tier", "environment", "dv_environment", "fault_count", "first_discovered", "fqdn", "gl_account", "install_date", "install_status", "dv_install_status", "install_type", "dv_install_type", "invoice_number", "ip_address", "it_application_owner", "dv_it_application_owner", "justification", "last_change_date", "last_discovered", "lease_id", "life_cycle_stage", "dv_life_cycle_stage", "life_cycle_stage_status", "dv_life_cycle_stage_status", "location", "dv_location", "mac_address", "maintenance_schedule", "dv_maintenance_schedule", "managed_by", "dv_managed_by", "managed_by_group", "dv_managed_by_group", "managed_domain", "manufacturer", "dv_manufacturer", "model_id", "dv_model_id", "model_number", "monitor", "next_assessment_date", "number", "operational_status", "dv_operational_status", "order_date", "organization_unit_count", "owned_by", "dv_owned_by", "platform", "dv_platform", "platform_host", "dv_platform_host", "po_number", "portfolio", "dv_portfolio", "product_support_status", "dv_product_support_status", "purchase_date", "schedule", "dv_schedule", "serial_number", "short_description", "skip_sync", "software_license", "dv_software_license", "start_date", "subcategory", "dv_subcategory", "support_group", "dv_support_group", "support_vendor", "dv_support_vendor", "supported_by", "dv_supported_by", "sys_class_name", "dv_sys_class_name", "sys_class_path", "sys_created_by", "sys_created_on", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "technology_stack", "dv_technology_stack",  "u_catalog", "dv_u_catalog", "dv_u_company_desired",  "dv_u_connectivity", "dv_u_country", "u_data_source", "dv_u_data_source", "u_detail_status", "dv_u_detail_status", "u_label", "u_manual_managed_by", "u_metal", "dv_u_metal", "u_moebius_billable", "u_moebius_cpd", "dv_u_moebius_cpd", "u_moebiusdisclaimer", "u_moebiussupport", "dv_u_owner", "dv_u_purchase_request_item", "dv_u_responsible_tic", "dv_u_service_provider", "dv_u_service_schedule", "dv_u_status", "dv_u_substatus", "u_urmoebius",  "u_zone", "dv_u_zone", "unverified", "url", "user_base", "dv_user_base", "vendor", "dv_vendor", "warranty_expiration", "work_notes", "x_avne2_addm_to_se_td_key", "x_nexsa_imc_nxt_engine", "dv_x_nexsa_imc_nxt_engine", "x_nexsa_imc_nxt_platform", "x_tsirm_tio_cmdb_asset_attributes", "dv_x_tsirm_tio_cmdb_asset_attributes", "ES_ACTIVO_SN", "FEC_BAJA"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

