table Demandas_Tasks
	lineageTag: 38f0c3a7-a6c8-44c1-9835-e33b97f5c45e

	measure UltimaActualizacion = MAX(Demandas_Tasks[opened_at])
		formatString: d/mm/yy
		lineageTag: 525f016f-f7f7-49a7-95ff-1243a0d10265

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure __UltimaActualizacion = today()
		formatString: Short Date
		lineageTag: 0c534ce6-1b88-4d51-82d9-c04c08c0674b

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9a7d1005-5a83-410e-b201-4c8685719219
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column approval
		dataType: string
		lineageTag: 56a5d8d7-1dbf-45b3-849d-6407a118fd09
		summarizeBy: none
		sourceColumn: approval

		annotation SummarizationSetBy = Automatic

	column dv_approval
		dataType: string
		lineageTag: ca1d7281-fd39-4ad3-8707-6a09cd0ab63d
		summarizeBy: none
		sourceColumn: dv_approval

		annotation SummarizationSetBy = Automatic

	column assigned_to
		dataType: string
		lineageTag: d13340ee-8003-499b-8fc4-d541232f2558
		summarizeBy: none
		sourceColumn: assigned_to

		annotation SummarizationSetBy = Automatic

	column dv_assigned_to
		dataType: string
		lineageTag: b716b999-e682-44a9-9f41-ec4c99f21774
		summarizeBy: none
		sourceColumn: dv_assigned_to

		annotation SummarizationSetBy = Automatic

	column assignment_group
		dataType: string
		lineageTag: e1766828-d0b7-4d79-9a83-59124344d0fd
		summarizeBy: none
		sourceColumn: assignment_group

		annotation SummarizationSetBy = Automatic

	column dv_assignment_group
		dataType: string
		lineageTag: 4f7090d2-2fc6-4431-85a4-0f2e5e4b375b
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 7871ed49-59de-4da6-9c01-208b29b78738
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: fdaad16c-d7c8-4e3b-b6c6-ccb80b56d9ee
			defaultHierarchy: LocalDateTable_14775f43-34bc-4995-a1e6-50588b485fee.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column closed_by
		dataType: string
		lineageTag: 0bc95fcc-1435-4f61-ac1c-196ba6cd1320
		summarizeBy: none
		sourceColumn: closed_by

		annotation SummarizationSetBy = Automatic

	column dv_closed_by
		dataType: string
		lineageTag: 9833b767-62c5-4d84-8c87-18892956706d
		summarizeBy: none
		sourceColumn: dv_closed_by

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: a88bca85-7245-40fa-87c5-4ba9434a3b2a
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column escalation
		dataType: int64
		formatString: 0
		lineageTag: b8bdc8a8-abb5-42b9-a2cb-d9101a6e86dc
		summarizeBy: sum
		sourceColumn: escalation

		annotation SummarizationSetBy = Automatic

	column dv_escalation
		dataType: string
		lineageTag: aed7ba43-fc48-489e-a359-937fa9117f23
		summarizeBy: none
		sourceColumn: dv_escalation

		annotation SummarizationSetBy = Automatic

	column group_list
		dataType: string
		lineageTag: a5c772e7-c878-414c-8f99-6e0f6bfa73a9
		summarizeBy: none
		sourceColumn: group_list

		annotation SummarizationSetBy = Automatic

	column impact
		dataType: int64
		formatString: 0
		lineageTag: f68238ef-8894-4d5e-bac7-e78d7049f6aa
		summarizeBy: sum
		sourceColumn: impact

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: f061f496-2edb-4bae-8efa-965226b7f4f3
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column knowledge
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d6cc71c6-1132-48c9-8939-5b27f89f5b54
		summarizeBy: none
		sourceColumn: knowledge

		annotation SummarizationSetBy = Automatic

	column made_sla
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7ade3505-5249-48e3-9e67-c54947c5d3be
		summarizeBy: none
		sourceColumn: made_sla

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: fcaa7aa1-7461-47cb-8f8f-c23b21bae1a7
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 774e7161-7c8f-408e-9c45-f306f2005139
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: 8bb977ab-1a87-4db7-8be8-7e33fd4b58b8
			defaultHierarchy: LocalDateTable_c91a5589-5941-4f90-9e1f-0ea18708135a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column opened_by
		dataType: string
		lineageTag: 24ce8299-6014-4f3b-bbb1-975985b5922c
		summarizeBy: none
		sourceColumn: opened_by

		annotation SummarizationSetBy = Automatic

	column dv_opened_by
		dataType: string
		lineageTag: e90731ce-602d-4925-9f89-c7b48700462a
		summarizeBy: none
		sourceColumn: dv_opened_by

		annotation SummarizationSetBy = Automatic

	column order
		dataType: int64
		formatString: 0
		lineageTag: de50cae3-2a37-40f0-bab9-335148e2b915
		summarizeBy: sum
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: 0e30ee85-ea6c-4108-8f11-578f961a9d82
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: be4b73e8-533e-404b-9966-d664c1f29de3
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: int64
		formatString: 0
		lineageTag: f78bfd36-6c09-4b95-ab21-23ec76bb5ef2
		summarizeBy: sum
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: c8dc79b9-ea25-4618-97f4-b59195c951f4
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column reassignment_count
		dataType: int64
		formatString: 0
		lineageTag: c77588fe-edbb-4345-a353-3c1641666826
		summarizeBy: sum
		sourceColumn: reassignment_count

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: 45bf3fc2-b207-4933-b081-3b3b030d2fe7
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column state
		dataType: int64
		formatString: 0
		lineageTag: 94743d57-4339-4fd0-a3d0-76833aa419e1
		summarizeBy: sum
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: b66b5ba6-6571-486f-83f1-9a8d395b1060
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column sys_class_name
		dataType: string
		lineageTag: cfd47858-0c0f-4738-9715-1f8bdd546e47
		summarizeBy: none
		sourceColumn: sys_class_name

		annotation SummarizationSetBy = Automatic

	column dv_sys_class_name
		dataType: string
		lineageTag: ad21393d-2df8-4a5e-b632-6ff7a43ef203
		summarizeBy: none
		sourceColumn: dv_sys_class_name

		annotation SummarizationSetBy = Automatic

	column sys_created_by
		dataType: string
		lineageTag: 77828bab-62a5-46d5-b3d3-84c7cfb1c50d
		summarizeBy: none
		sourceColumn: sys_created_by

		annotation SummarizationSetBy = Automatic

	column sys_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: cdddacfe-8c51-4a1b-9b62-f75946f856bd
		summarizeBy: none
		sourceColumn: sys_created_on

		variation Variación
			isDefault
			relationship: 8ed3a0a4-e73d-4021-baee-02e2b4353532
			defaultHierarchy: LocalDateTable_208ccd81-d4e8-4692-a8ab-d75ba9e6116a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column sys_domain
		dataType: string
		lineageTag: 9ae20c10-1a9c-4792-92f9-52742c37794f
		summarizeBy: none
		sourceColumn: sys_domain

		annotation SummarizationSetBy = Automatic

	column sys_domain_path
		dataType: string
		lineageTag: 51d616c7-195d-4d63-ad32-f1fe55a3502e
		summarizeBy: none
		sourceColumn: sys_domain_path

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: 26790d12-8d9c-4488-a42b-6d13d2c7c8e6
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column sys_mod_count
		dataType: int64
		formatString: 0
		lineageTag: 9e3008d9-9a92-4fe0-a12b-d15741c42a1b
		summarizeBy: sum
		sourceColumn: sys_mod_count

		annotation SummarizationSetBy = Automatic

	column sys_tags
		dataType: string
		lineageTag: eaff8f8d-e55a-47ce-86f6-1e8e0d56957e
		summarizeBy: none
		sourceColumn: sys_tags

		annotation SummarizationSetBy = Automatic

	column sys_updated_by
		dataType: string
		lineageTag: 471e68db-88f8-49ec-a321-57000835b501
		summarizeBy: none
		sourceColumn: sys_updated_by

		annotation SummarizationSetBy = Automatic

	column sys_updated_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 9528befa-8e27-4167-b7a8-cb3ee5a07aa1
		summarizeBy: none
		sourceColumn: sys_updated_on

		variation Variación
			isDefault
			relationship: fc33d8b6-3280-4eee-8b14-0b7a78af1927
			defaultHierarchy: LocalDateTable_90caf0c1-ab6f-46cd-9c1e-a326e5a36e5d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column task_effective_number
		dataType: string
		lineageTag: f77d0bee-9f0b-4f39-8380-a2758e48a53a
		summarizeBy: none
		sourceColumn: task_effective_number

		annotation SummarizationSetBy = Automatic

	column time_worked
		dataType: dateTime
		formatString: General Date
		lineageTag: 6c77e34c-26b7-4055-9de9-5440805aeba1
		summarizeBy: none
		sourceColumn: time_worked

		variation Variación
			isDefault
			relationship: 8666e4e6-21d3-43a7-af9f-fdd4fe19c7f2
			defaultHierarchy: LocalDateTable_23a697d5-9264-4783-b006-24d42d450839.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_time_worked
		dataType: string
		lineageTag: 2fc3a966-1c6d-42a0-b09d-e641f8a48a17
		summarizeBy: none
		sourceColumn: dv_time_worked

		annotation SummarizationSetBy = Automatic

	column u_acciona_priority
		dataType: int64
		formatString: 0
		lineageTag: ef5a1c65-623f-43c0-b1bb-15b0203605a0
		summarizeBy: sum
		sourceColumn: u_acciona_priority

		annotation SummarizationSetBy = Automatic

	column u_commented
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5a3cffba-c0b9-4902-9dc9-20847776a394
		summarizeBy: none
		sourceColumn: u_commented

		annotation SummarizationSetBy = Automatic

	column u_previous_groups
		dataType: string
		lineageTag: e3bebc5e-eeb2-49d7-9232-6610422940ee
		summarizeBy: none
		sourceColumn: u_previous_groups

		annotation SummarizationSetBy = Automatic

	column u_progress
		dataType: double
		lineageTag: 74c831d0-62a5-4ffa-ad08-9d73d6594eee
		summarizeBy: sum
		sourceColumn: u_progress

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_reason_for_rejection
		dataType: string
		lineageTag: bf9d56fc-d273-4276-bb95-2e906778f8cb
		summarizeBy: none
		sourceColumn: u_reason_for_rejection

		annotation SummarizationSetBy = Automatic

	column dv_u_reason_for_rejection
		dataType: string
		lineageTag: ed548e34-f946-49b9-9a18-3e064442d67c
		summarizeBy: none
		sourceColumn: dv_u_reason_for_rejection

		annotation SummarizationSetBy = Automatic

	column u_requested_by
		dataType: dateTime
		formatString: General Date
		lineageTag: 375a87d7-cbb7-4a63-9e83-f242ef017abd
		summarizeBy: none
		sourceColumn: u_requested_by

		variation Variación
			isDefault
			relationship: 1d04436e-1559-474d-8349-26fd691a7b91
			defaultHierarchy: LocalDateTable_992767da-2f0e-42ff-9079-432bdc0886b4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_responded
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cea2c6d7-b291-4ff9-bf36-79238dbb6e34
		summarizeBy: none
		sourceColumn: u_responded

		annotation SummarizationSetBy = Automatic

	column u_state_date
		dataType: dateTime
		formatString: General Date
		lineageTag: fc42f024-1b16-44ca-86b0-8319cd28cbaa
		summarizeBy: none
		sourceColumn: u_state_date

		variation Variación
			isDefault
			relationship: 9adf802c-6616-405b-8521-8c15bf139b23
			defaultHierarchy: LocalDateTable_26b6c099-05b7-4594-acc6-34e1f09121f6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column upon_approval
		dataType: string
		lineageTag: 2d80db82-0caa-4e9c-966d-e218d35cd796
		summarizeBy: none
		sourceColumn: upon_approval

		annotation SummarizationSetBy = Automatic

	column dv_upon_approval
		dataType: string
		lineageTag: dd2f7080-f4d4-4d0f-b8f9-20075bef9dc5
		summarizeBy: none
		sourceColumn: dv_upon_approval

		annotation SummarizationSetBy = Automatic

	column upon_reject
		dataType: string
		lineageTag: 2e8a7709-b4a6-4fdb-a381-f4016f8e143d
		summarizeBy: none
		sourceColumn: upon_reject

		annotation SummarizationSetBy = Automatic

	column dv_upon_reject
		dataType: string
		lineageTag: 522e647d-2dee-4db6-aea2-7cd3c627a7bc
		summarizeBy: none
		sourceColumn: dv_upon_reject

		annotation SummarizationSetBy = Automatic

	column urgency
		dataType: int64
		formatString: 0
		lineageTag: 00bca80a-003a-4488-a0da-f4e4de5d6715
		summarizeBy: sum
		sourceColumn: urgency

		annotation SummarizationSetBy = Automatic

	column dv_urgency
		dataType: string
		lineageTag: c36adfb1-8e40-493f-abf8-41f89719b93b
		summarizeBy: none
		sourceColumn: dv_urgency

		annotation SummarizationSetBy = Automatic

	column PortfolioDemanda = if('Demandas_Tasks'[dv_parent]=related(Demandas[number]), RELATED(Demandas[dv_portfolio]), "Vacio")
		lineageTag: 299470ed-1a25-4dd2-950b-b3003cbd497d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column TallajeDemanda = if('Demandas_Tasks'[dv_parent]=related(Demandas[number]), RELATED(Demandas[dv_size]), "Vacio")
		lineageTag: c0c44ab6-4a69-4600-8f99-2afc0b4820f1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DuracionCerradas = DATEDIFF(Demandas_Tasks[opened_at].[Date], Demandas_Tasks[closed_at].[Date], DAY)
		formatString: 0
		lineageTag: 16c86771-9f7b-4b5d-8729-6314788da181
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column AplicacionDemanda = if('Demandas_Tasks'[dv_parent]=related(Demandas[number]), RELATED(Demandas[dv_u_business_applications]), "Vacio")
		lineageTag: 5b644568-f310-4653-85cf-91817f1cf288
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _EsGrupoEstimacionSupply = if(CONTAINS(_GruposEstimacion, _GruposEstimacion[Grupo], Demandas_Tasks[dv_assignment_group]), Demandas_Tasks[dv_assignment_group], "No")
		lineageTag: 29b932c6-410c-4774-bc1b-23252f70f7c2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Util = if(or(Demandas_Tasks[_EsGrupoEstimacionSupply]="No",Demandas_Tasks[_EsAplicacionSupply]="No"), "No", "Si")
		lineageTag: f4dbf2b5-f391-4e7a-bc3e-ccb6087e75e2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column MesAño = FORMAT(Demandas_Tasks[opened_at],"YYYY MMM")
		lineageTag: c96784b9-2e39-4213-8b47-c88b7fcbe270
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column EstadoGeneral = if(OR(OR(Demandas_Tasks[dv_state]="Open",Demandas_Tasks[dv_state]="Pending"), Demandas_Tasks[dv_state]="Work in Progress"), "Abierta", "Cerrada")
		lineageTag: 6f815577-eb5d-4d8c-851b-ab091564d2b1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column TiempoAntiguedadBacklogDias = DATEDIFF(Demandas_Tasks[opened_at], today(), DAY)
		formatString: 0
		lineageTag: 06fb4cfd-48dc-4b72-889c-e93b4870bafc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column DuracionAbiertas = DATEDIFF(Demandas_Tasks[opened_at].[Date], today(), DAY)
		formatString: 0
		lineageTag: b8d61727-ef18-4674-bb96-b7c951972b29
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column _EsAplicacionSupply = if(CONTAINS(_Aplicaciones, _Aplicaciones[Aplicación de Negocio], Demandas_Tasks[AplicacionDemanda]), Demandas_Tasks[AplicacionDemanda], "No")
		lineageTag: 520f930d-6c01-4585-bbc8-f479e2c14875
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column MesAñoCerrada = FORMAT(Demandas_Tasks[closed_at],"YYYY MMM")
		lineageTag: d662dc9b-5e86-48d4-85e8-7215bf30b34a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DuracionDiasConParadas = if(Demandas_Tasks[dv_state]="Closed", DATEDIFF(Demandas_Tasks[opened_at],Demandas_Tasks[closed_at], DAY), DATEDIFF(Demandas_Tasks[opened_at], TODAY(), DAY))
		formatString: 0
		lineageTag: 1c8cca7f-5d7d-4425-8851-1b982137cfc5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '_dv_state - español'
		dataType: string
		lineageTag: 4d4c5000-01ff-4843-9865-9484ebf5a2de
		summarizeBy: none
		sourceColumn: _dv_state - español

		annotation SummarizationSetBy = Automatic

	column 'URL tarea' = CONCATENATE("https://acciona.service-now.com/u_demand_task.do?sysparm_query=number%3d", Demandas_Tasks[number])
		lineageTag: de2a395c-2b2c-4427-bf16-24815a2f5a64
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'URL Demanda' = CONCATENATE("https://acciona.service-now.com/dmn_demand.do?sysparm_query=number%3d", Demandas_Tasks[dv_parent])
		lineageTag: f4c46b24-7fe6-4771-a057-974d28f48295
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_dv_priority - español'
		dataType: string
		lineageTag: d3cad1d9-4d5e-4667-bab2-9a5194751427
		summarizeBy: none
		sourceColumn: _dv_priority - español

		annotation SummarizationSetBy = Automatic

	column '_Aplicacion ENERGIA' =
			if(
			    Demandas_Tasks[AplicacionDemanda] = RELATED (_Aplicaciones[Aplicación de Negocio]), RELATED(_Aplicaciones[Aplicación identificada por Energía]))
		lineageTag: 681f2a1d-daf6-4ff4-905f-ddc248a83ceb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column TallajeDemanda_SoloLetra = if('Demandas_Tasks'[dv_parent]=related(Demandas[number]), RELATED(Demandas[_dv_size - SoloLetra]), "Vacio")
		lineageTag: e62b5246-bf37-4138-9d74-d30b531859a0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Demandas_Tasks-73b415f5-96f8-4139-9eb7-fd0c99a23d2e = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("QECCDWH.acciona.int,60001"),
				    DWH = Origen{[Name="DWH"]}[Data],
				    SERV_NOW_u_demand_task = DWH{[Schema="SERV_NOW",Item="u_demand_task"]}[Data],
				    #"Eliminar columnas vacias" = Table.RemoveColumns(SERV_NOW_u_demand_task,{"activity_due", "additional_assignee_list", "approval_history", "approval_set", "business_duration", "dv_business_duration", "business_service", "dv_business_service", "calendar_duration", "dv_calendar_duration", "close_notes", "cmdb_ci", "dv_cmdb_ci", "cmdb_ci_business_app", "dv_cmdb_ci_business_app", "comments", "comments_and_work_notes", "company", "dv_company", "contact_type", "dv_contact_type", "contract", "dv_contract", "correlation_display", "correlation_id", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "due_date", "expected_start", "follow_up", "location", "dv_location", "rejection_goto", "dv_rejection_goto", "route_reason", "dv_route_reason", "service_offering", "dv_service_offering", "skills", "sla_due", "task_for", "dv_task_for", "u_business_line", "dv_u_business_line", "u_catalog", "dv_u_catalog", "u_department", "dv_u_department", "u_external_vendor", "dv_u_external_vendor", "u_metal", "dv_u_metal", "u_operational_committee_comment", "u_payroll_area", "dv_u_payroll_area", "u_phone", "u_ref_country", "dv_u_ref_country", "u_size", "dv_u_size", "universal_request", "dv_universal_request", "user_input", "variables", "watch_list", "wf_activity", "dv_wf_activity", "work_end", "work_notes", "work_notes_list", "work_start"}),
				    #"Filas filtradas" = Table.SelectRows(#"Eliminar columnas vacias", each [opened_at] > #datetime(2020, 8, 1, 0, 0, 0)),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Filas filtradas", "dv_state", "dv_state - Copia"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna duplicada",{{"dv_state - Copia", "_dv_state - español"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","Pending","Pendiente",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Closed","Cerrado",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","Open","Abierto",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","Reject","Rechazado",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","Work in Progress","En curso",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Columna duplicada1" = Table.DuplicateColumn(#"Valor reemplazado4", "dv_priority", "dv_priority - Copia"),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columna duplicada1",{{"dv_priority - Copia", "dv_priority - Español"}}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Columnas con nombre cambiado1","1 - Critical","1 - Crítica",Replacer.ReplaceText,{"dv_priority - Español"}),
				    #"Valor reemplazado6" = Table.ReplaceValue(#"Valor reemplazado5","5 - Very Low","5 - Muy Baja",Replacer.ReplaceText,{"dv_priority - Español"}),
				    #"Valor reemplazado7" = Table.ReplaceValue(#"Valor reemplazado6","4 - Low","4 - Baja",Replacer.ReplaceText,{"dv_priority - Español"}),
				    #"Valor reemplazado8" = Table.ReplaceValue(#"Valor reemplazado7","3 - Moderate","3 - Moderada",Replacer.ReplaceText,{"dv_priority - Español"}),
				    #"Valor reemplazado9" = Table.ReplaceValue(#"Valor reemplazado8","2 - High","2 - Alta",Replacer.ReplaceText,{"dv_priority - Español"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Valor reemplazado9", each true),
				    #"Columnas con nombre cambiado2" = Table.RenameColumns(#"Filas filtradas1",{{"dv_priority - Español", "_dv_priority - español"}}),
				    #"Filas filtradas2" = Table.SelectRows(#"Columnas con nombre cambiado2", each [number] <> "DTASK0005244")
				in
				    #"Filas filtradas2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

