table _Subcategorias
	lineageTag: 0e72bdb0-7758-4158-8092-a390bd450caa

	column Aplicacion
		dataType: string
		lineageTag: 06720f65-35db-42fe-9a02-e98875cb6f72
		summarizeBy: none
		sourceColumn: Aplicacion

		annotation SummarizationSetBy = Automatic

	column Subcat_BD
		dataType: string
		lineageTag: e2afa781-ce48-40d0-8f11-27958d67f0fc
		summarizeBy: none
		sourceColumn: Subcat_BD

		annotation SummarizationSetBy = Automatic

	partition _Subcategorias-7c5d0e28-efa4-4a1d-b044-faa3d09a6fb4 = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("lVddkts2DL4KJk/2dDOTaaeZSd9kWfGqjWzHcrc/6T7QEtfLRhI1lOTEfeodeoI9QJ9yBN+kJykAUrL8s97Nw3oJ4CMJAuBH6MOHF7Efv7ji39srliD4XMpU1apYo6EnsH325s03QBNwAP/9/Q/E0mxUImFW1ipXf0nDuLk0dyqDVGbg66I2olZVLXCelZJaG5gbjRhp1/Xm4Bm1EtACKtrlSMXQoBCrTE71JwJYAVBi24/hwoO4KctsC/69UAVhTpVBIc1696/gObxHu5dzPlWprmALb3HXxogKzfPGJPeikhCJQqxlLosa4m1VyxwG8yge2plGJ415KWnbduziegODAx9uVKVWKlP1dsjxRMBLeATRhWgiq1rtvhQYElNqiuqGXCdTq+k7yPPeZ+rjRslPiMhLPAse653G0+NKCU3u7KU7YQWiSCHTa0UQG3R/HEEcTOMA3scBpfFAbreJZYEBIptFnep4rUakRmNtkKephjAOPATTPxiL6n6lhUktMo3grSpEkSiJM7q0XT1q4UApygoedDGndfHXJcoeJZ54mAosQDzoSS6HFM3LAK4ZL/gB2sBR7RzIbTgqPrqLgxNa2w1F3JnsmCyLYB5OYRAWd9rkmF1diAwWstSVQn+25N2TkO46oWFLCQQ/002K1cVR2rp6edTMdTwK4UZkWE8Jl1uqit1DjvVCWculSQTeD6rxZ+H41iKPGCQBRyk8bD0dzX3cHm95pTOV8plgMHsXD52rj9v7K4yMSteyN8Up+hh7RBg1aHAE96ipP2+OtdCUDd4+d9Bl6PfmnjV3deIIEAkFg7LBUhJtxZyx7Gcd3ZJe8V+28wplSdcdE6BERjMOZL5a96KG32WRyuojHMMvGGlutPuSNhnvnegcWQprMFfovsa5F4y87yKC8ZZUWHnfvf6edjtWtbhgGiwmv0HkTb1JEAXTpQOf6rnCInrI6JeljY69yYw0btSjBnKuo1IaCyOKGoPHiZgZtZYFpfcr0Jb9VS420gh8EYz+UyZ1jz+G/CRcBBxwg63HPR9ePW7qasZLEgo3xDoTpi2UQ2WHHSmNHNmVUyvu6y/wZ8GiqzYr9Wo6bwpZ7QvZip19PPaiqLVaYW+TlTBGZ7ZIvDJDviAX98tdQHSrXE/mMOinBSO6xYjqatgucwnSrROH4SxCvne5Dotaro2g1gUcx9orPfujefXq29dRt/rXT+Q9w4WEgVdVsoYehx+R/HNQfEs4LS13nelM/CBiGn0mkD1Mc1Xgobi7OGh3mK4088mTGNupud1wC4MMPvaW3LKdas+ho1+jM2jSEnoSIg8sMAGI2Y/JEsZLeh4RToyKUasAm6mlzGRifWu7gSE3Hc8GM/N5k5/j3tNJfHes2uMoW8Y9M8caQs28JUR6RT3wVV84badC7HNSdLCC+NpbzE9aq2P7Qd8Xic8q1/1Oz2mYEUPsdvBx9a+J8PYC2bABxTZ9IvXa7B7uVEJrnOoI+Ytcgb47pBp8oaqa3g261k8Aur5eF21Try2njhah/5M/my4Xs3doOhA5htk2L8kxNyDdGBvvWK1pqW7oepBMq9pepUjLlWoqet6IXjj3tjl5AsO7FhJ7aEU7dMM9o2Am7aXdPbge+7zefn0k96qW9JkhHYXQNoOoySQzwUU7R2g0HlNk6B/J2HtA/9k4lNv40GVtchchJ7ANuQy7f/o7faIIftHOscFmED/J6NvQuXasub39Hw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Aplicacion = _t, Subcat_BD = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Aplicacion", type text}, {"Subcat_BD", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

