table Subcategoria_AUX
	lineageTag: ae5720c9-539e-4a03-8e1c-eb934863bf5f

	column Subcategoría
		dataType: string
		lineageTag: c13825fa-1d27-46b7-97aa-cff3f3c48878
		summarizeBy: none
		sourceColumn: Subcategoría

		annotation SummarizationSetBy = Automatic

	column Porfolio
		dataType: string
		lineageTag: 602e8288-7306-4029-92f8-7a50e38b27c8
		summarizeBy: none
		sourceColumn: Porfolio

		annotation SummarizationSetBy = Automatic

	column 'Unidad Tecnología'
		dataType: string
		lineageTag: 589b291d-5603-4d24-8567-1968f8620668
		summarizeBy: none
		sourceColumn: Unidad Tecnología

		annotation SummarizationSetBy = Automatic

	partition Subcategoria_AUX = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("tVzNcuM2En4VlE+erYkrtVubquyNphgNa4eWIiren0kOMAlrsKEILUA60ZzyDvsEc9xDTvMIfpN9kgVIWcORCaAboo+y+vsa/XU3AQig3727iKLkL+T7iv/8wNkvF68vkpurGW3oj+3XX//xmyjVfzEfSf+ZpNHFT6/fXRh7xWrFCAZxqz2AAatkmd6Qy7S+F3JLGy5qWpEV2wnFGyH3r6A8ebQkkcbuG14oEleiLclXJKmZ3OyhHMvrlNzSSkha8MdPNSl5/fhxywtKSka2TBa0FOpAxhSVUlSVMN/dsI0ouPiDoR37omNPft0x2fADwXe8pnXBmRT6cyyFUscwrpexHnosaiUqXnaakMvF2/wVCHkteblhINNeHXLdakDD6w0ItJRMtbuWqeag0jqNncCu8nQ0jaSNUEaVB1Y39BSjQ+4+fKBqBN7SUnaKZrQuRT/yx9/BJGbwsZA7ndqm46AbttWjOMX/WOuPebvbVXsSv6e8/nIou51mMYXAadVD51qHvlYYqehxXHocka6diiuuTorHgsA7GBpORPq/3/5DEtW0JRfqNZmXK7Ina0nLvjYmG3laN0zWunxMs09JnNG9kFx1xTUZ6UK3bV/qL8AqaqY+g/iH6R0tRfX4u34oUnX463+7D5O6WEaqa68rD6tuqYb8k9UlUz+TF++mcG/Q1gr1EN5n4TFhmi7cC7QDwz2A2/FsF0G9Ge41rFHP8Aft2uzxU9n265lCbHUT6gracj17ipfo2nBv0K4N9RDeteExYbo23Au0a8M9gLv2bBdBXRvuNaxrz/AHnmtXGZntDa3eD/3pmz+/yAyL9AGeV1G8Z8ymyPGj5lAkN3jmRPLC58sw4rBZEukrcG7EesH0VnKTrOb/IFl0E82TLLlZv1SDoR1hugxJfl6roSPB9hvaAabp0OSozgtlD24/tMPwHsS7gjZikuUv0XYAWmiTeanCWwowSkwDAeig7QKgAjcHnCuoFQD0YYUPIQaX+YPIo/niRUodRg0udwjdGSUPGy2q7GGU4NKH0cHLH8UX1gIwF4FtACSHtkKuc8C23YnM0GxOJa0bbdTV/kLyDatfol0mdA9tqclchrfdhFFjWnNCt9D2ndAluMWn9xn0GJhwGGGPiikHAH2cLCXf0gctGrlcSvEvVjSD08HDgWvanxI/Hco2si2e9Hz6KoQrrXUgnEkz4j1Z3DPZdBKdw7mQG1o/5dvEu5Nir0HiGfHxoL6TYz+j6v2doLLsKRf3vOB1l4qnJwaJE/MUPzmYjYquk0kuKip7rB5neVDIKJbEi2Slvxn8GQFPHj9VunSC8cPcR0XDHzolwrjerL+7tYGvudhSRfEKOICe2B1IRNQOFle8x6CQ4dpxnmjtQESwdhJnrGLb6gdqQLB2oC9aOxITrp3FFe9sFmUZPlorzBOrFYeI1MrhjPOLqzrRzgyynzsDgkdx+RRBkWFkQhG7tHszX5LLoefl00TzCi8eksyjHpINIR+S2aVfnqaLjFw+LXnMqngjaWVID1fhepZFP2dnAapO4sKj9SQ+EBmYxJ8tL+mKkctIKdaQwXXE55cRoUkI43MoHkYIlDeM3KJlL8phbTlYsZJ8bzJHLuMky3FyhlPaFQ3nhIkazm+r0XLLa138UifnYXiRsb9gKSpchYawOeozhA5YnSHUFg2P2dApkNpsFq1RqgHxdp2ABDBlgGRALbK/4xZ+QDxcCwtBmBYWMosW8zQjyUpPLygFnCh73E4YLFonhSXGNF+bu/ZaHnMHWz/fFeE1WbOKFX0fHZ5MyFXcebR2lc7jhcl4ng+Lzlk0/yEfvI+AUhMCtmsGQcOUgTA54zdrB/n5xQJU+E6sL3onGBO8k8gS+yJak0zc8YqhwnbD7BG7cbBg3RyWOM0viHn3clA8y/SaseClbiBF8jfRaokKHc1kVwNNBRMITevQzLyApeeoX/lWoFXyYN26eMBwJTxEltjzdB6Z+OI3qLDdMHvEbhwsWDeHJc5broTUDsRGPn685wUuyyC0PWoQHBY8iMqiwd/YHRH3X/6kTuJWNeZMCvfzGp7Krg6eCyYVnte6Hqd3lTgcb32fJxfDA5frVRr/NV7crFeLt71FrhctV4MjNqHMsfaVnrYKKjdGAWPBC3N8M7TC0CV5vJiMiMTMrKmMmsVx4zYV9eA8fSLK49nX8HxuIu7BUe0kpHNWX5HS7JH5XctLT/IX1X67ExNUkZfIXz8gCmzlAElhNQMjw1YLjBVcJ146XIVE2upwLGh/IdbYHN7tLRrlsZ6Jos35pvaYmfekS/550W01XLayeE8VG/thbXn8Xc0Kfxq2nuT0Y/j+uPi1+5M6APmVz+y4QtodxqcIrUtSiY2WXu+jPPA8zn0Wi2+/7S7z9NljukQavuUfmPQpa2YXRm7EL88Nuzefba9+x7e6fIbWRC8OuN4v8GY/pBpNZiV40/+WnAl2x1tlXlMzE3S32e7h69TcXjg5kAplkf++0vv3ohbV46eNeXt/T+Z6c8NkLUi6DieO+Z2ezdmmlbp5yjN4zLHsBIHO2FYXFg0nSOt7SVl3oaVpJT1jKEvz/wC6h/MPqqWSi3Cqz48kC9uiZm91L9Wgyhk1RhTIGN5RB6Pm9nSPmY9ldczOmbwxgDtHYwhvKvozuWh9ODF6/Nj0625/XvxIRJK8ZI6M+bH29HmxY7n0gpyJ9aLdWfbC/SnXcxpvmBkaOxy/mha+zNqKvYKlHsyAKQEoqasUwByOkoByjJYGFOwuESiLp1SgNN6Sub6ezUCV8cwQUQCnWEeen5na03lqOpa1Uxtnck6N3Tk4tfZKbcxOrnJ6NLcjEOJbSRxZsGPs6bBixvJiNXYmyIpyZ8oK86bM7IrM1qXdgvJlMUcka5zBkSkLwJ6mccBYjsYtnQkah7izM47xp6Ybcbd7Wz67fA3LFpgBk0AoqSunYA5HmqEco5mHgt3FAGXx1AeUxr85kbTQW2yzOwdPey4MZqtip3HtWBwox8bFjhrdv9jN3dsYO86zm7ED3Sn86f8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SUBCATEGORIA = _t, Porfolio = _t, #"Unidad Tecnología" = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"SUBCATEGORIA", type text}, {"Porfolio", type text}, {"Unidad Tecnología", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"SUBCATEGORIA", "Subcategoría"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

