table Traza_Demandas
	lineageTag: 98624387-fdb7-4b49-b2ef-3d5ff561fe1f

	column enhancement
		dataType: string
		lineageTag: 54d7d6d9-a5c0-46f3-add7-ba4a110587b2
		summarizeBy: none
		sourceColumn: enhancement

		annotation SummarizationSetBy = Automatic

	column dv_enhancement
		dataType: string
		lineageTag: c97d6b7d-70e4-4b3c-9a65-3b205501a85e
		summarizeBy: none
		sourceColumn: dv_enhancement

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: 6f2c3b1a-8fa0-4eba-8666-b1dfbb167d5a
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column portfolio
		dataType: string
		lineageTag: 8587291e-195f-4c09-b714-fc4853600117
		summarizeBy: none
		sourceColumn: portfolio

		annotation SummarizationSetBy = Automatic

	column dv_portfolio
		dataType: string
		lineageTag: 59b60ab5-bf0f-425e-914d-f10ab2f61529
		summarizeBy: none
		sourceColumn: dv_portfolio

		annotation SummarizationSetBy = Automatic

	column project
		dataType: string
		lineageTag: 56e66924-38e6-4d38-bcdd-691a88ef2d4a
		summarizeBy: none
		sourceColumn: project

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: 4dffd647-68c9-46af-8274-47d02395b0fc
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: e31a7dc7-f2dd-4a94-aea3-c4355d09084d
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column 'related_records.1'
		dataType: string
		lineageTag: 63e49dcb-1f40-4c0f-be88-7fdae467a7e5
		summarizeBy: none
		sourceColumn: related_records.1

		annotation SummarizationSetBy = Automatic

	column 'related_records.2'
		dataType: string
		lineageTag: 09f29f74-6133-4f56-97ae-9591a35a9352
		summarizeBy: none
		sourceColumn: related_records.2

		annotation SummarizationSetBy = Automatic

	column 'related_records.3'
		dataType: string
		lineageTag: de1e4570-e49d-4a59-93e8-7f530b1ff131
		summarizeBy: none
		sourceColumn: related_records.3

		annotation SummarizationSetBy = Automatic

	column 'related_records.4'
		dataType: string
		lineageTag: d614a80f-793a-4c58-a6d6-2109c0706aa5
		summarizeBy: none
		sourceColumn: related_records.4

		annotation SummarizationSetBy = Automatic

	column Proyecto1
		dataType: string
		lineageTag: ffb6cef7-ca82-45c5-aa30-7ddb77467f65
		summarizeBy: none
		sourceColumn: Proyecto1

		annotation SummarizationSetBy = Automatic

	column Proyecto2
		dataType: string
		lineageTag: 4476becd-ab52-45ba-bbd7-c8f9403c5a77
		summarizeBy: none
		sourceColumn: Proyecto2

		annotation SummarizationSetBy = Automatic

	column Proyecto3
		dataType: string
		lineageTag: dc629125-5924-4473-8892-15b4ed50cbeb
		summarizeBy: none
		sourceColumn: Proyecto3

		annotation SummarizationSetBy = Automatic

	column Proyecto4
		dataType: string
		lineageTag: 470bc4bd-2261-4de6-99f1-1d8402555480
		summarizeBy: none
		sourceColumn: Proyecto4

		annotation SummarizationSetBy = Automatic

	column Evolutivo1
		dataType: string
		lineageTag: 699c4b03-2eb7-4da7-a19f-09ba1d039c80
		summarizeBy: none
		sourceColumn: Evolutivo1

		annotation SummarizationSetBy = Automatic

	column Evolutivo2
		dataType: string
		lineageTag: 704f55a7-9269-42d5-8d31-eddb6f6a5d92
		summarizeBy: none
		sourceColumn: Evolutivo2

		annotation SummarizationSetBy = Automatic

	column Evolutivo3
		dataType: string
		lineageTag: 3dc5e039-b460-42ab-8cd2-8f4fac71f9a7
		summarizeBy: none
		sourceColumn: Evolutivo3

		annotation SummarizationSetBy = Automatic

	column Evolutivo4
		dataType: string
		lineageTag: 1661324b-c576-4ac6-a60c-9c4e5b929c4f
		summarizeBy: none
		sourceColumn: Evolutivo4

		annotation SummarizationSetBy = Automatic

	column TareaProyecto1
		dataType: string
		lineageTag: 57f3620f-6165-48af-85e7-02e928197c43
		summarizeBy: none
		sourceColumn: TareaProyecto1

		annotation SummarizationSetBy = Automatic

	column TareaProyecto2
		dataType: string
		lineageTag: f06a2933-0ce4-43bd-b8cd-2819b6f7e3da
		summarizeBy: none
		sourceColumn: TareaProyecto2

		annotation SummarizationSetBy = Automatic

	column TareaProyecto3
		dataType: string
		lineageTag: 08eebdac-99d7-4ec5-9880-6a2b5c9d0732
		summarizeBy: none
		sourceColumn: TareaProyecto3

		annotation SummarizationSetBy = Automatic

	column TareaProyecto4
		dataType: string
		lineageTag: 1c00f5ee-5768-44b8-a91d-8eca5683ee3a
		summarizeBy: none
		sourceColumn: TareaProyecto4

		annotation SummarizationSetBy = Automatic

	column Proyecto_generado = ```
			IF(
			    Traza_Demandas[Proyecto1] <> "0",
			    Traza_Demandas[Proyecto1],
			    IF(
			        Traza_Demandas[Proyecto2] <> "0",
			        Traza_Demandas[Proyecto2],
			        IF(
			            Traza_Demandas[Proyecto3] <> "0",
			            Traza_Demandas[Proyecto3],
			            IF(
			            Traza_Demandas[Proyecto4] <> "0",
			            Traza_Demandas[Proyecto4],
			            BLANK() 
			        )
			    )
			))
			```
		lineageTag: 16b491b0-2768-43d0-9065-a6655bc386ab
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Evolutivo_generado = ```
			IF(
			    Traza_Demandas[Evolutivo1] <> "0",
			    Traza_Demandas[Evolutivo1],
			    IF(
			        Traza_Demandas[Evolutivo2] <> "0",
			        Traza_Demandas[Evolutivo2],
			        IF(
			            Traza_Demandas[Evolutivo3] <> "0",
			            Traza_Demandas[Evolutivo3],
			            IF(
			            Traza_Demandas[Evolutivo4] <> "0",
			            Traza_Demandas[Evolutivo4],
			            BLANK() 
			        )
			    )
			))
			```
		lineageTag: 2c56d016-7ece-4ea1-8d1a-ecbdd03e56a7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column TareasProyecto_generado =
			
			VAR Tarea1 = Traza_Demandas[TareaProyecto1]
			VAR Tarea2 = Traza_Demandas[TareaProyecto2]
			VAR Tarea3 = Traza_Demandas[TareaProyecto3]
			VAR Tarea4 = Traza_Demandas[TareaProyecto4]
			RETURN
			    IF (
			        Tarea1 = "0" && Tarea2 = "0" && Tarea3 = "0" && Tarea4 = "0",
			        BLANK (),
			        IF (
			            Tarea1 <> "0",
			            Tarea1 &
			            IF (Tarea2 <> "0", ", " & Tarea2, "") &
			            IF (Tarea3 <> "0", ", " & Tarea3, "") &
			            IF (Tarea4 <> "0", ", " & Tarea4, ""),
			            IF (
			                Tarea2 <> "0",
			                Tarea2 &
			                IF (Tarea3 <> "0", ", " & Tarea3, "") &
			                IF (Tarea4 <> "0", ", " & Tarea4, ""),
			                IF (
			                    Tarea3 <> "0",
			                    Tarea3 &
			                    IF (Tarea4 <> "0", ", " & Tarea4, ""),
			                    IF (
			                        Tarea4 <> "0",
			                        Tarea4,
			                        BLANK ()
			                    )
			                )
			            )
			        )
			    )
		lineageTag: 94d366b1-079f-40a1-a1ad-124a15b896e6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Traza_demanda = ```
			
			VAR proyecto = Traza_Demandas[Proyecto_generado]
			VAR evolutivo = Traza_Demandas[Evolutivo_generado]
			VAR tarea = Traza_Demandas[TareasProyecto_generado]
			RETURN
			    IF (
			        proyecto = "" && evolutivo = "" && tarea = "",
			        BLANK (),
			        IF (
			            proyecto <> "",
			            proyecto &
			            IF (evolutivo <> "", ", " & evolutivo, "") &
			            IF (tarea <> "", ", " & tarea, ""),
			            IF (
			                evolutivo <> "",
			                evolutivo &
			                IF (tarea <> "", ", " & tarea, ""),
			                IF (
			                    tarea <> "",
			                    tarea, 
			                        BLANK ()
			                    )
			                )
			            )
			        )
			    
			```
		lineageTag: ff279a96-12c9-4212-aef0-809b045ed236
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column approved_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0f5a95ff-7553-4884-9b9a-ab0c1cf7871e
		summarizeBy: none
		sourceColumn: approved_end_date

		variation Variación
			isDefault
			relationship: df66e9e3-5dd7-42a4-93ec-615440b8d081
			defaultHierarchy: LocalDateTable_578a89ca-478f-4eb6-ae11-d2c36a0e1689.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column approved_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f3bf799a-a229-4ac3-949d-6165b7526cf4
		summarizeBy: none
		sourceColumn: approved_start_date

		variation Variación
			isDefault
			relationship: 580c9f97-547c-4226-9974-2a0e0371e08d
			defaultHierarchy: LocalDateTable_eeec3203-d61b-4a14-9b80-3ee5bc9041be.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column calculation_type
		dataType: string
		lineageTag: 5c83b167-2924-470a-bd62-adab509757ef
		summarizeBy: none
		sourceColumn: calculation_type

		annotation SummarizationSetBy = Automatic

	column dv_calculation_type
		dataType: string
		lineageTag: 19cf7276-c869-416f-b6de-e3b363222eee
		summarizeBy: none
		sourceColumn: dv_calculation_type

		annotation SummarizationSetBy = Automatic

	column contract
		dataType: string
		lineageTag: 29958c9b-923f-4671-b27c-b7b59f4f725d
		summarizeBy: none
		sourceColumn: contract

		annotation SummarizationSetBy = Automatic

	column dv_contract
		dataType: string
		lineageTag: fabe93a2-870f-4aad-89b0-8075a588c5af
		summarizeBy: none
		sourceColumn: dv_contract

		annotation SummarizationSetBy = Automatic

	column model_id
		dataType: string
		lineageTag: 13807969-031d-4f54-8605-a67c4de212e7
		summarizeBy: none
		sourceColumn: model_id

		annotation SummarizationSetBy = Automatic

	column dv_model_id
		dataType: string
		lineageTag: 857c7aec-979f-4e12-921e-2930b2c6084a
		summarizeBy: none
		sourceColumn: dv_model_id

		annotation SummarizationSetBy = Automatic

	column software_model
		dataType: string
		lineageTag: 0e9178fb-e29a-4e82-a296-4f06e5bbca0d
		summarizeBy: none
		sourceColumn: software_model

		annotation SummarizationSetBy = Automatic

	column dv_software_model
		dataType: string
		lineageTag: a6cda6bc-0f1b-4503-834f-1d2ec1b84cd2
		summarizeBy: none
		sourceColumn: dv_software_model

		annotation SummarizationSetBy = Automatic

	column u_commented
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3226f16e-4031-4d82-a7c1-3940cffca932
		summarizeBy: none
		sourceColumn: u_commented

		annotation SummarizationSetBy = Automatic

	column u_deferred_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: dd3fd4a1-9a1a-4450-8304-be5e62f934e4
		summarizeBy: none
		sourceColumn: u_deferred_end_date

		variation Variación
			isDefault
			relationship: a78835fc-0c0d-4eca-a38f-d07837200065
			defaultHierarchy: LocalDateTable_9ec30484-8082-4b85-8e6f-f65341d870d5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_deferred_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 407ef394-74da-4f72-b0a2-7d416826c2e9
		summarizeBy: none
		sourceColumn: u_deferred_start_date

		variation Variación
			isDefault
			relationship: 2a8d6e08-8d9c-4bc0-8d9e-b66c7b17634c
			defaultHierarchy: LocalDateTable_e51f5521-21db-4436-ad30-b2a29df2c73f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_digital_transformation
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e2a241e6-06f0-43c0-8e13-8da9d1a1863e
		summarizeBy: none
		sourceColumn: u_digital_transformation

		annotation SummarizationSetBy = Automatic

	column u_fases_rfi
		dataType: string
		lineageTag: a07a5f0f-541e-4d0e-b877-fce662791da1
		summarizeBy: none
		sourceColumn: u_fases_rfi

		annotation SummarizationSetBy = Automatic

	column dv_u_fases_rfi
		dataType: string
		lineageTag: bbcddc2c-6b64-467f-b4be-9bc989a52e75
		summarizeBy: none
		sourceColumn: dv_u_fases_rfi

		annotation SummarizationSetBy = Automatic

	column u_operational_committee_comment
		dataType: string
		lineageTag: ae82c472-388a-4a32-a111-38cf26735d69
		summarizeBy: none
		sourceColumn: u_operational_committee_comment

		annotation SummarizationSetBy = Automatic

	column u_origin_country_of_the_demand
		dataType: string
		lineageTag: 78047d7c-06b9-40f4-add2-2fc9c82816ca
		summarizeBy: none
		sourceColumn: u_origin_country_of_the_demand

		annotation SummarizationSetBy = Automatic

	column u_payroll_area
		dataType: string
		lineageTag: edfdc15d-510b-4ae2-8f87-aca05190e452
		summarizeBy: none
		sourceColumn: u_payroll_area

		annotation SummarizationSetBy = Automatic

	column dv_u_payroll_area
		dataType: string
		lineageTag: 7149dadd-54a0-4f0d-960d-c5792cffe373
		summarizeBy: none
		sourceColumn: dv_u_payroll_area

		annotation SummarizationSetBy = Automatic

	column u_planned_capital
		dataType: double
		lineageTag: 55ee87dd-f7fa-4d71-9f2c-da9ea3f032e2
		summarizeBy: sum
		sourceColumn: u_planned_capital

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_planned_operating
		dataType: double
		lineageTag: 6d21dbd7-9596-4b8b-ba86-c8eb674ba5f6
		summarizeBy: sum
		sourceColumn: u_planned_operating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_program_manager
		dataType: string
		lineageTag: 418c85a2-a72d-4c03-9d0c-9e74b407a5a3
		summarizeBy: none
		sourceColumn: u_program_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_program_manager
		dataType: string
		lineageTag: ecd6b1fc-6c94-4a67-9f0a-db0029832e17
		summarizeBy: none
		sourceColumn: dv_u_program_manager

		annotation SummarizationSetBy = Automatic

	column u_relevant_project_for_cio
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2504af76-a1fd-4890-9f15-f271d48a83a9
		summarizeBy: none
		sourceColumn: u_relevant_project_for_cio

		annotation SummarizationSetBy = Automatic

	column u_rfi
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 050e4f2e-5476-4d34-9934-1b75808155eb
		summarizeBy: none
		sourceColumn: u_rfi

		annotation SummarizationSetBy = Automatic

	column u_selected_suppliers
		dataType: string
		lineageTag: 7f710a87-12b3-47bf-b150-b35bf5ad1fe0
		summarizeBy: none
		sourceColumn: u_selected_suppliers

		annotation SummarizationSetBy = Automatic

	column u_targets
		dataType: string
		lineageTag: c4d92dd4-abab-48c2-9d7a-6400435e0377
		summarizeBy: none
		sourceColumn: u_targets

		annotation SummarizationSetBy = Automatic

	column u_total_planned_cost
		dataType: double
		lineageTag: a79be98b-dea9-43b7-a7b6-e1095ef8e399
		summarizeBy: sum
		sourceColumn: u_total_planned_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dv_expense_type
		dataType: string
		lineageTag: 2fdec100-be69-489d-a82c-0e524f74a153
		summarizeBy: none
		sourceColumn: dv_expense_type

		annotation SummarizationSetBy = Automatic

	column expense_type
		dataType: string
		lineageTag: e2cc9f44-ca97-4d54-9c72-b2c99e0f6a76
		summarizeBy: none
		sourceColumn: expense_type

		annotation SummarizationSetBy = Automatic

	partition Traza_Demandas = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("QECCDWH.acciona.int,60001"),
				    DWH = Origen{[Name="DWH"]}[Data],
				    SERV_NOW_dmn_demand = DWH{[Schema="SERV_NOW",Item="dmn_demand"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_dmn_demand,{"active", "activity_due", "additional_assignee_list", "apm_idea_action", "dv_apm_idea_action", "approval", "dv_approval", "approval_history", "approval_set", "assessment_required", "assigned_to", "dv_assigned_to", "assignment_group", "dv_assignment_group", "assumptions", "barriers", "business_applications", "business_capabilities", "business_case", "business_duration", "dv_business_duration", "business_service", "dv_business_service", "business_unit", "dv_business_unit", "calendar_duration", "dv_calendar_duration", "capital_budget", "capital_outlay", "category", "dv_category", "change", "dv_change", "close_demand", "dv_close_demand", "close_notes", "closed_at", "closed_by", "dv_closed_by", "cmdb_ci", "dv_cmdb_ci", "cmdb_ci_business_app", "dv_cmdb_ci_business_app", "collaborators", "comments", "comments_and_work_notes", "company", "dv_company", "contact_type", "dv_contact_type", "correlation_display", "correlation_id", "defect", "dv_defect", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "demand", "demand_actual_cost", "demand_actual_effort", "dv_demand_actual_effort", "demand_manager", "dv_demand_manager", "department", "dv_department", "description", "discount_rate", "due_date", "enablers", "escalation", "dv_escalation", "expected_risk", "dv_expected_risk", "expected_roi", "expected_start", "financial_benefit", "financial_return", "follow_up", "goal", "dv_goal", "goals", "group_list", "idea", "dv_idea", "impact", "dv_impact", "impacted_business_units", "in_scope", "investment_class", "dv_investment_class", "investment_type", "dv_investment_type", "irr_value", "knowledge", "labor_costs", "location", "dv_location", "made_sla", "npv_value", "opened_at", "opened_by", "dv_opened_by", "operational_budget", "operational_outlay", "order", "other_costs", "out_of_scope", "parent", "dv_parent", "primary_program", "dv_primary_program", "priority", "dv_priority", "dv_project", "project_manager", "dv_project_manager", "rate_model", "dv_rate_model", "reassignment_count", "rejection_goto", "dv_rejection_goto", "requested_by", "resource_allocated_cost", "resource_planned_cost", "risk_of_not_performing", "risk_of_performing", "route_reason", "dv_route_reason", "score", "score_cost", "score_risk", "dv_score_risk", "score_size", "score_strategic_allignment", "score_value", "dv_score_value", "scrum_epic", "dv_scrum_epic", "scrum_story", "dv_scrum_story", "service_offering", "dv_service_offering", "short_description", "size", "dv_size", "skills", "sla_due", "stage", "start_date", "state", "dv_state", "strategic_objectives", "submitted_date", "submitter", "dv_submitter", "sys_class_name", "dv_sys_class_name", "sys_created_by", "sys_created_on", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "task_effective_number", "task_for", "dv_task_for", "time_worked", "dv_time_worked", "total_costs", "dv_type", "u_acciona_priority", "u_actual_end_date", "u_actual_start_date", "u_affected_portfolios", "u_ambito_global", "u_analysis_date", "u_approval_sent", "u_approved_date", "u_approver", "dv_u_approver", "u_architecture_analysis", "u_business_applications", "dv_u_business_applications", "u_business_line", "dv_u_business_line", "u_catalog", "dv_u_catalog", "u_company", "dv_u_company", "u_concurrent_users", "dv_u_concurrent_users", "u_country", "dv_u_country", "u_criticality_level", "dv_u_criticality_level", "u_current_situation", "u_demand_category", "dv_u_demand_category", "u_demand_type_description", "u_department", "dv_u_department", "u_dependencies", "u_due_date", "u_duration_to_manage_a_demand", "dv_u_duration_to_manage_a_demand", "u_duration_to_reach_analysis", "dv_u_duration_to_reach_analysis", "u_execution_type", "dv_u_execution_type", "u_external_vendor", "dv_u_external_vendor", "u_first_commettee_state", "dv_u_first_commettee_state", "u_first_committee_date", "dv_u_first_committee_date", "u_frecuency_of_use", "dv_u_frecuency_of_use", "u_impact", "dv_u_impact", "u_impacted_companies", "u_impacted_countries", "u_impacted_groups", "u_is_parent", "u_metal", "dv_u_metal", "u_module", "dv_u_module", "u_old_state", "u_openned_up", "u_parent_demand", "dv_u_parent_demand", "u_phone", "u_pilot", "u_planned_demand", "dv_u_planned_demand", "u_previous_groups", "u_priority_justification", "u_progress", "u_project_manager", "dv_u_project_manager", "u_qualification_date", "u_reasons_for_delay", "dv_u_reasons_for_delay", "u_ref_country", "dv_u_ref_country", "u_reg_country", "dv_u_reg_country", "u_reg_department", "dv_u_reg_department", "u_reg_division", "dv_u_reg_division", "u_reg_user", "dv_u_reg_user", "u_rejected_date", "u_relevant", "u_responded", "u_rfp", "dv_u_rfp", "u_run", "u_run_description", "u_second_commettee_state", "dv_u_second_commettee_state", "u_second_committee_date", "dv_u_second_committee_date", "u_size", "dv_u_size", "u_sourcing", "u_start_date", "u_state_date", "u_status_report", "u_subcategory", "dv_u_subcategory", "u_submission_date", "u_tic_unit", "dv_u_tic_unit", "u_time_to_manage_a_demand", "u_time_to_reach_analysis", "u_total_budget", "u_total_effort", "u_total_effort_req", "dv_u_total_effort_req", "u_total_planned_hours", "u_volume_impacted_users", "universal_request", "dv_universal_request", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "urgency", "dv_urgency", "user_input", "variables", "visited_state", "watch_list", "wf_activity", "dv_wf_activity", "work_end", "work_notes", "work_notes_list", "work_start", "u_idl", "u_id_plan"}),
				    #"Dividir columna por delimitador" = Table.SplitColumn(#"Columnas quitadas", "related_records", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"related_records.1", "related_records.2", "related_records.3", "related_records.4"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Dividir columna por delimitador",{{"related_records.1", type text}, {"related_records.2", type text}, {"related_records.3", type text}, {"related_records.4", type text}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Tipo cambiado", {"related_records.1"}, pm_project, {"sys_id"}, "SERV_NOW pm_project", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW pm_project" = Table.ExpandTableColumn(#"Consultas combinadas", "SERV_NOW pm_project", {"number"}, {"SERV_NOW pm_project.number"}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Se expandió SERV_NOW pm_project",null,"",Replacer.ReplaceValue,{"SERV_NOW pm_project.number"}),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Valor reemplazado", {"related_records.2"}, pm_project, {"sys_id"}, "SERV_NOW pm_project", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW pm_project1" = Table.ExpandTableColumn(#"Consultas combinadas1", "SERV_NOW pm_project", {"number"}, {"SERV_NOW pm_project.number.1"}),
				    #"Consultas combinadas2" = Table.NestedJoin(#"Se expandió SERV_NOW pm_project1", {"related_records.3"}, pm_project, {"sys_id"}, "SERV_NOW pm_project", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW pm_project2" = Table.ExpandTableColumn(#"Consultas combinadas2", "SERV_NOW pm_project", {"number"}, {"SERV_NOW pm_project.number.2"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Se expandió SERV_NOW pm_project2",null,"",Replacer.ReplaceValue,{"SERV_NOW pm_project.number.1"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1",null,"",Replacer.ReplaceValue,{"SERV_NOW pm_project.number.2"}),
				    #"Consultas combinadas3" = Table.NestedJoin(#"Valor reemplazado2", {"related_records.4"}, pm_project, {"sys_id"}, "SERV_NOW pm_project", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW pm_project3" = Table.ExpandTableColumn(#"Consultas combinadas3", "SERV_NOW pm_project", {"number"}, {"SERV_NOW pm_project.number.3"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Se expandió SERV_NOW pm_project3",{{"SERV_NOW pm_project.number", "Proyecto1"}, {"SERV_NOW pm_project.number.1", "Proyecto2"}, {"SERV_NOW pm_project.number.2", "Proyecto3"}, {"SERV_NOW pm_project.number.3", "Proyecto4"}}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Columnas con nombre cambiado",null,"",Replacer.ReplaceValue,{"Proyecto4"}),
				    #"Consultas combinadas4" = Table.NestedJoin(#"Valor reemplazado3", {"related_records.1"}, rm_enhancement, {"sys_id"}, "rm_enhancement", JoinKind.LeftOuter),
				    #"Se expandió rm_enhancement" = Table.ExpandTableColumn(#"Consultas combinadas4", "rm_enhancement", {"number"}, {"rm_enhancement.number"}),
				    #"Consultas combinadas5" = Table.NestedJoin(#"Se expandió rm_enhancement", {"related_records.2"}, rm_enhancement, {"sys_id"}, "rm_enhancement", JoinKind.LeftOuter),
				    #"Se expandió rm_enhancement1" = Table.ExpandTableColumn(#"Consultas combinadas5", "rm_enhancement", {"number"}, {"rm_enhancement.number.1"}),
				    #"Consultas combinadas6" = Table.NestedJoin(#"Se expandió rm_enhancement1", {"related_records.3"}, rm_enhancement, {"sys_id"}, "rm_enhancement", JoinKind.LeftOuter),
				    #"Consultas combinadas7" = Table.NestedJoin(#"Consultas combinadas6", {"related_records.4"}, rm_enhancement, {"sys_id"}, "rm_enhancement.1", JoinKind.LeftOuter),
				    #"Se expandió rm_enhancement2" = Table.ExpandTableColumn(#"Consultas combinadas7", "rm_enhancement", {"number"}, {"rm_enhancement.number.2"}),
				    #"Se expandió rm_enhancement.1" = Table.ExpandTableColumn(#"Se expandió rm_enhancement2", "rm_enhancement.1", {"number"}, {"rm_enhancement.1.number"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Se expandió rm_enhancement.1",null,"",Replacer.ReplaceValue,{"rm_enhancement.number"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4",null,"",Replacer.ReplaceValue,{"rm_enhancement.number.1"}),
				    #"Valor reemplazado6" = Table.ReplaceValue(#"Valor reemplazado5",null,"",Replacer.ReplaceValue,{"rm_enhancement.number.2"}),
				    #"Valor reemplazado7" = Table.ReplaceValue(#"Valor reemplazado6",null,"",Replacer.ReplaceValue,{"rm_enhancement.1.number"}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Valor reemplazado7",{{"rm_enhancement.number", "Evolutivo1"}, {"rm_enhancement.number.1", "Evolutivo2"}, {"rm_enhancement.number.2", "Evolutivo3"}, {"rm_enhancement.1.number", "Evolutivo4"}}),
				    #"Consultas combinadas8" = Table.NestedJoin(#"Columnas con nombre cambiado1", {"related_records.1"}, pm_project_task, {"sys_id"}, "pm_project_task", JoinKind.LeftOuter),
				    #"Se expandió pm_project_task" = Table.ExpandTableColumn(#"Consultas combinadas8", "pm_project_task", {"number"}, {"pm_project_task.number"}),
				    #"Valor reemplazado8" = Table.ReplaceValue(#"Se expandió pm_project_task",null,"",Replacer.ReplaceValue,{"pm_project_task.number"}),
				    #"Columnas con nombre cambiado2" = Table.RenameColumns(#"Valor reemplazado8",{{"pm_project_task.number", "TareaProyecto1"}}),
				    #"Consultas combinadas9" = Table.NestedJoin(#"Columnas con nombre cambiado2", {"related_records.2"}, pm_project_task, {"sys_id"}, "pm_project_task", JoinKind.LeftOuter),
				    #"Se expandió pm_project_task1" = Table.ExpandTableColumn(#"Consultas combinadas9", "pm_project_task", {"number"}, {"pm_project_task.number"}),
				    #"Valor reemplazado9" = Table.ReplaceValue(#"Se expandió pm_project_task1",null,"",Replacer.ReplaceValue,{"pm_project_task.number"}),
				    #"Columnas con nombre cambiado3" = Table.RenameColumns(#"Valor reemplazado9",{{"pm_project_task.number", "TareaProyecto2"}}),
				    #"Consultas combinadas10" = Table.NestedJoin(#"Columnas con nombre cambiado3", {"related_records.3"}, pm_project_task, {"sys_id"}, "pm_project_task", JoinKind.LeftOuter),
				    #"Se expandió pm_project_task2" = Table.ExpandTableColumn(#"Consultas combinadas10", "pm_project_task", {"number"}, {"pm_project_task.number"}),
				    #"Columnas con nombre cambiado4" = Table.RenameColumns(#"Se expandió pm_project_task2",{{"pm_project_task.number", "TareaProyecto3"}}),
				    #"Valor reemplazado10" = Table.ReplaceValue(#"Columnas con nombre cambiado4",null,"",Replacer.ReplaceValue,{"TareaProyecto3"}),
				    #"Consultas combinadas11" = Table.NestedJoin(#"Valor reemplazado10", {"related_records.4"}, pm_project_task, {"sys_id"}, "pm_project_task", JoinKind.LeftOuter),
				    #"Se expandió pm_project_task3" = Table.ExpandTableColumn(#"Consultas combinadas11", "pm_project_task", {"number"}, {"pm_project_task.number"}),
				    #"Columnas con nombre cambiado5" = Table.RenameColumns(#"Se expandió pm_project_task3",{{"pm_project_task.number", "TareaProyecto4"}}),
				    #"Valor reemplazado11" = Table.ReplaceValue(#"Columnas con nombre cambiado5",null,"",Replacer.ReplaceValue,{"TareaProyecto4"}),
				    #"Valor reemplazado12" = Table.ReplaceValue(#"Valor reemplazado11","","0",Replacer.ReplaceValue,{"Proyecto1"}),
				    #"Valor reemplazado13" = Table.ReplaceValue(#"Valor reemplazado12","","0",Replacer.ReplaceValue,{"Proyecto2"}),
				    #"Valor reemplazado14" = Table.ReplaceValue(#"Valor reemplazado13","","0",Replacer.ReplaceValue,{"Proyecto3"}),
				    #"Valor reemplazado15" = Table.ReplaceValue(#"Valor reemplazado14","","0",Replacer.ReplaceValue,{"Proyecto4"}),
				    #"Valor reemplazado16" = Table.ReplaceValue(#"Valor reemplazado15","","0",Replacer.ReplaceValue,{"Evolutivo1"}),
				    #"Valor reemplazado17" = Table.ReplaceValue(#"Valor reemplazado16","","0",Replacer.ReplaceValue,{"Evolutivo2"}),
				    #"Valor reemplazado18" = Table.ReplaceValue(#"Valor reemplazado17","","0",Replacer.ReplaceValue,{"Evolutivo3"}),
				    #"Valor reemplazado19" = Table.ReplaceValue(#"Valor reemplazado18","","0",Replacer.ReplaceValue,{"Evolutivo4"}),
				    #"Valor reemplazado20" = Table.ReplaceValue(#"Valor reemplazado19","","0",Replacer.ReplaceValue,{"TareaProyecto1"}),
				    #"Valor reemplazado21" = Table.ReplaceValue(#"Valor reemplazado20","","0",Replacer.ReplaceValue,{"TareaProyecto2"}),
				    #"Valor reemplazado22" = Table.ReplaceValue(#"Valor reemplazado21","","0",Replacer.ReplaceValue,{"TareaProyecto3"}),
				    #"Valor reemplazado23" = Table.ReplaceValue(#"Valor reemplazado22","","0",Replacer.ReplaceValue,{"TareaProyecto4"}),
				    #"Filas filtradas" = Table.SelectRows(#"Valor reemplazado23", each Text.StartsWith([dv_portfolio], "EN."))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

