table _Elementos_Pedidos_Energia
	lineageTag: b2023b60-9e3d-42d9-b95d-b3113efaca2a

	column 'Elementos identificados por Energía'
		dataType: string
		lineageTag: 0ad6219e-2eec-431b-87bb-85637b3bb449
		summarizeBy: none
		sourceColumn: Elementos identificados por Energía

		annotation SummarizationSetBy = Automatic

	column 'Aplicación identificada por Energía'
		dataType: string
		lineageTag: 3f64128e-6c59-4610-b410-23cc2df98945
		summarizeBy: none
		sourceColumn: Aplicación identificada por Energía

		annotation SummarizationSetBy = Automatic

	column Elemento_CI
		dataType: string
		lineageTag: dd9b0705-5f08-434e-8c41-0fedc88d45bd
		summarizeBy: none
		sourceColumn: Elemento_CI

		annotation SummarizationSetBy = Automatic

	column 'cmdb_ci_appl.sys_id'
		dataType: string
		lineageTag: fe1534cb-d1e9-4a95-9329-d8d8624fad3f
		summarizeBy: none
		sourceColumn: cmdb_ci_appl.sys_id

		annotation SummarizationSetBy = Automatic

	partition _Elementos_Pedidos_Energia-d76e21d4-b8dc-46ae-8573-33b6b126c525 = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rRrJdts48lfwfFLeWONFXnOjKUZhP1Fkk7Kd7kwfuMA22hShBiklmn+aU39CfmyqwA2kIMnOzMUCasdSG+ivX48MwaKQmDwrRBgX+dHxUWB4RIUWPCcJJQ80K0JAWyldwJDD8OiP469HZuKQTywLs5iFKbEyKp43gFPAVPAS/uM/WgGVbi6IJ/gTSylgPCpgBHrT2gqWa9VbWRillMz4N0R2Jn3K70uasIJlz7hIMyBD0gH16e3AMsg4zF8iHoqkWhICNbS/MBGSYLVcphtivoQsUxe8hdQI+DVlrwHNckrMsUN+DaxKH4zATjf6kxZsDQdxAntE89VyRXM4lx2C1ox+I8uViF/CnOYkzBKS8mfYQBYjS0Ni8sVShDnZkCkHWxGv22K0ob8P77crsIYzjof5xMUC9pzmPysKzq46wZMTYhd0QZwwL6jQkj6A7M7BPLCcRSxlxUYK2Y/vy/M9gwQbULaQnsJwBBsIYIX4xLQb/e7tLRLCzz92iBv2r4bnjbaBUiSl19cXl1e3STS6vr05uxiNaEyT+OL08vbq7PbiTJHp+a557w8picEDaRrG7MffGbpxMDbRdM86ux4G5vAQndR7ezM6p9dPl0l0Qc/j29Ou3ptQ0WuCtwuKApaCxzSH8xzMrdnY8j8QmtVmWaUFN2jB2zmkLZcXN+dhdH2rtyW5UPfV8D4ShyfsCe51uTA4LLYOpTJw/AR0hRHoL++ZZ52foUVv4TvR8Ev7TuloFCc3F2fRzXmc3J4mlxfnZ2fRZRRdRHEURYp9RlyswpT9u9LhU3RRiJU2uEi5QbdozgGy8macn42unqJkx66E+3dF2Q7YcSAoN+NUox1IV3AokpoY5dq3lyIPk8aMH5M1e6aYGsjmhJN1mEKUB9QaltAY/3RzPTqPrs+S6EZj/Kg03jCsj2RKnyHHGMmaxZgkdLDW93zLs2cwqX97GLB6knQD2y644s+YG7Mw3WAoJWbKVwmmkTrpHUC3cqTlQZhCdI6V1LsD3PJhwhKQCjGWtMOufXeeCUrvVskzrZOdFqrjgvCc85QlkG55JhNHVHMAdgY5A+x6Ys8r0VL8taJi09Hyv0h5v1X3ORX5MdxgSCt5DhRlxrM8yNYZFA1pKvnyd5j4DpGtvb+MMUiVf5WTjsENsrC6BJCpsvBZJoEqj+CpHyZR5C2XmLepwHILmXvzlhJSR0F+p1lC81eyRbYX2crwHTLeZOEC7/Po6hKRGlCH3ppZ/uQ34hgzY2I51mxeMWnhHU4naCRXPD1I6wcOlgDlXwXa38CP5I6lKZ7p4wsHrwLPAqx4pdKt3kmu6FnzwJi4KKIZtdiJoBDxqrzdmbQ09mxizf5pug4A1HFL4VhT+8HyYdqOWiz40GO4pttXBgj24VoJHudpFWqmHhlA5b3gCaHXHzD278G1EtqSdTK2CNhv+ZCcllwUdZG5G7tLyi5+HWe18Vv7H1ABuYBBMnu07rCWXLDVot6NAcR2XMabiBSZ9sRHv65/1QrPkQVe9/RkIL+DApY8hOmqyVUdSI96Pracmq4aK97B1tANPXLxmmMEWtJYxq2B7ZrS0APoVo4D52m6s2Du35tz250Rx72zp/b8N+JNjfkn13ckwxvJWo8wDTKwoIFYhAXcmn+tTk/PryCmwHJlPsxZjgxvJFP93JZ+bnfvrgABawpdFd7NP2G1yi2XF/gQgU6WdyX7TyoDvoyD+3CKBN/9xTLnSmAjhmnCphlVyENJb6DR+cSdTRojOk7RQ3R5ZXNnl7trHh1rYcoN5mkowMNyGkLHSO4L2fyQQeD699JVDuBbSfN7/+7e9TCwK8N+1WP7LtzMLOPrMvl2T+YtNIpEqFlD4rBY8GfBEllDbYP2ZAgo0hj8QBigERmUwZ6KD7rssJu0t8KKU75bQCBdhhlN65XtwKn1glywl4aZLA3UWX8dTY2KJjUm96Hdu/GA96BHWF2RHaje6upqRV6Lell9YD8SMg4dVFPhttMenWmZrsx03Vmfii8WPGuo6lmPajw2nCag1pP+SaUQGgTkAbjPVepvDkqL6vF/nni7IswhfE+S94BvMHecv9a8HUjfhwzDAQe0oDPGmGzMxhhOrCAgc7cM1RYxPC9oHeodDH1dnw3fa+RUky2fnhjorwV9FtCMlWUr4U/EyHOq3Zl3cWxps12nYS5oIlthseiHilqqW0Y9R1H+8wK0tkAvlnJWSP6ukh6mn/NfoMOA5dcKmvy/De9xPkI5NXhk2JSUEaWskJol7sFv9yZlhDdX0JNDE1CFjb1IRYbtUzIoT03dRdSXs4KLjbTpTVSKVOUWyCDTm/coh4Km8hwF/QufDfOaRYdoeSEO1aW5MlTwUyOYk8HdNIQ2qY1xc2k7GnyQQKm85KNl9beFJg4WFskqLh9OrB9/p+Uj7B5Myy0DJFava7itbE17xf4BdF+OX+6R6gAsIwFWk2K1aAUepmslY2lnAgXcHCNNedw4wk5Ewzt2HSMgg7E9sefG1P7dkIVo7RJN/RS4U8PHvX4vvaLJm2/zfSKeEQQWNGd+IAPm3DdmwSeYSWXvZ1GyNzgSvoptZGLPCfgDGYeL8pHBhF1NZXv6JipNbVO/hffmOyjJkIyNeZ++ge7msuaOhquE7uZyvui4SuhuLn/sarhKqNJ5Uyj5wuULiwnWMnLVOpjCYUOI9mXzpgxb/Of5pwcYVz9K/56gR0FpgH2klLkNUagxSGC2EdIR8TkJHGZOocSo6sDqmwJek3cRK+8FxuQeY0v928MQI1mwDB+Oa0fbAd7iq58zWxYF0qce0/y14MuGtp33KWViFHKjtgB92jJ3lRXYNkSl/mI7riSqBgruiwM3pjrIzqSlcQ3o0HhUfoHsTJRuDzovd0nL/cIPnt9jmqbgphTkeSjvMIUiDUder7vlcEuxwcMvgeYEvyxpQGoHi59NIP2sIEOXaXVYfZHag9J1myjdzmKWyBf7vKn2DlPopGGJ12GuAJpetan0tyGa7uXziooClWNlQuvHoh0ojTYn/M4WXNXWQDTUrmWppOVUQ1cm68qL9NDu27Yd3BNDPiqpE/UdCxw+CYXsFmNafooXFcseXOfVCjd8a99l8T0kpvm5wjYThWbFCuUNscohemjLhY9ppjG1ZmPDJ5N7wx9jLNJDFS5oqN1vIDTvVii74Aony0yTuLg8ZajUH3Bfm1gB2bMIyTR8xRWEUVqeyWEK5RVOlN+Y6l8lX9XUOj4HDnhYLgGVGBapHJOWUXUfdqeflv+IoAUqFSx0sK9V3gBYb6pEvnSzWKIDNAOlwsb/BYFJ/dt5+ZIfj4+O1aGCr/4FQftJYy+y6ynqGwwXcFZ1KDv8QeonWd+of8d3IuSZ3Nvaz0//L1mdfhBbD7gwH4k9BwYs27RA9UzjF/DkuFgJWrfB8sXYWaVUNmyHCJTqmccrXI8s/TsTTZSc22YZpbYhyjsigNQXqP68ovzjvw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Elementos identificados por Energía" = _t, #"Aplicación identificada por Energía" = _t, Elemento_CI = _t, cmdb_ci_appl.sys_id = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Elementos identificados por Energía", type text}, {"Aplicación identificada por Energía", type text}, {"Elemento_CI", type text}, {"cmdb_ci_appl.sys_id", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

