table Elementos_AUX
	lineageTag: 7d471090-55ef-412e-9431-8734d5eacd00

	column Elemento
		dataType: string
		lineageTag: 1667056c-0b07-4179-8c71-2de8c50003b4
		summarizeBy: none
		sourceColumn: Elemento

		annotation SummarizationSetBy = Automatic

	column Porfolio
		dataType: string
		lineageTag: 47298dda-d3a2-47f8-976d-04818d8f0ae0
		summarizeBy: none
		sourceColumn: Porfolio

		annotation SummarizationSetBy = Automatic

	column Negocio
		dataType: string
		lineageTag: 70d5ed11-c409-4735-81f5-122b23131acf
		summarizeBy: none
		sourceColumn: Negocio

		annotation SummarizationSetBy = Automatic

	partition Elementos_AUX = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("vVzNcttGEn6VKZ3sKluV2q1NVXKDQJhGyiQYgrKdeHMYASN6SiCGmQEkM6e8wz7BHvfgkx9Bb7JPkhmQlCiJPegeUjmS6O9rfF9PAzP4+/TpJIqSH9k7MecVi8prWYiTVyfJ+DQywigtOfup1bdfS1lw+3+slTEnv736dDJNJul4HTngDf93+913//g+Sp/GsNdsWCZswM3nC8V12YPJowmLal6tGlkYFleqLS1DUgs9X/VAOyE5r4RhhaobzYvGrCFvZM3rQgqtLFf34w9uHmCTL0uhG4mOd7t5Nont5rO2nItG1nM6NFa1UZUseSNVzXhdsostmd06FjdOx6Wct/o+4vdW6NWxU50boc0rZi1YSGNshOlCksmIpbVpeFV1OLQ7Pw0SbGhUFJaZbyrMRrzmc7EQdcPylWnEYs0zFKaRt99qVgpWbYJvv3JLGtW3/62kkcZtWghd8FK5DADiKDlj5RJJXj1rnv//+R+WmKYtpbK1GZZTtmIzzcv1UHtOfWndCF3zjuR5Nb62gJU9ytgx9sx5Mju4rSK77e9JpGp7GLobKPKPvyX3RFW3X+2Bk5vNv//rfjx31knkpOrlaV+i5fJB7xy/sSkJ0F2MJz2gZSl7TupPCjG6GSmk+M4LYA1rM0qiwJ4ipcA2UPyZN+xXUZfCXLFn76bwbNjWCs0Q3mfhmihNF54F24HhGdDteHCKoN4MzxrWqAfkQ3ftdMQGq5ov3Irmn9//61l6lZgD3aEk3gP6krj/pG4kcqN7kMiL77ww4rB+I+YK7DJqFkpvJeNkOvyFjaJxNExGyXj2XA1GTkTpMiL5Ya1GVkLtN3ICStORyUmdF8oe3H7khOE9SE+FbcSxuPnAr8XTReRzNGNwMmxDBiYIb8pgRZTGDE6Cbc7gBOgGPTRDUJMGJw1r1PB06LOmvJYV+6D0lXEXeJei6C4Lv0iz+OU6Sbq+wr69dNzottg6td1EZ0rruail0G5vVyy7FLrpzAhnzPSc19sqOqVLrVYWoZ7Qzs6nZ+fZZEaTB6JQUkA0fre7expxEmfJdM0y0arc7Kzb+e2Wnb8xuOT2W7W+o0ME7o6qyFbmuttlIsnb2Zv3ECpP08yep74sKyWb7q4DXTeOo8cDHAnBDxwh4E1cjtjmZgqvNkcGkjFYAtgVLAPOEiybx4/dwPvdplmC5PC7giTBG4MkhLzpBFsScW1PGtKeSR6fQrAGEYk8LhGZkFYRWQG/BtkoytmLQTpMZ9G79NdolmZjlq0PwyMWxbH9HbE8exdNX5IMPJgZdvRgapzFB6eBPJ/MnrK+YZMoz5PxMJnmLBoP2GwajfM39hfR9iOQe5w/AjvS/CNkAvxP7AzYzmCKFZtUvDbsUmk24Iv1ff/YdlFlSJYH8sEuBxLijA0kh7zcztONXYrRXOtDevzpgyKd6KPBaLZhg2gWrhzGI/XDBAEuwGRIL5LZ6CAvADzeC4AgzAuADOnF6ONhXgB4vBcAQZgXABnSi+kgO8gLAI/3AiAI8wIgA7wYCjXXfPlZFuy9FDfE4yQKDfuAguNcQFFBHqR2+TfNaA3hA3kUe1BIoR4GQN/mb7w2CADrghA4TRAa0JOWblXRrFgu9DVxxCKwsEoEGCcYQQRpz+3Us7u23C2t3BOhsmYzUYnu0VpVbZ4NM7SZ+WG0HscO4kWaeVAOwOdRNDzPSRaCCNgdEIITDsJ9mlhULmQtTaPpF/GwBD2KEQwEAxBsfj+2D7WHWOHD9rrgA5MM8BF5tQ+EuWrUMkC5B9mn2wOlqPbQeDV3F3o18bTRD+1T7cNSZPt4vLqnYqn0/fsQJOFebJ9yL5gi3UsEav+YjmjTexjiUwphsAIhPKTr4+h+I0GbF+bR58UhNXo5AJ1ZNGMjdSErQdLph8E6/TicTj8HoHNylq5vhTfdAwO2zQtRVaIuhEVMaEUO4IIdCSDD2RRADHmX0uzZG+5xYG88UuReLKRD2XUrs7bEgxGLhxFNFQLs0YhAIxUjmCD9WhXCGBa1jVqsX4h7zaYTog8EEo8fBBakLwRGwJ+fK3mVi9qIztu0LqRdRhaSG5a/jaYTkk0BXLBbAWQ40wKIe73LU2Jn9UMxzkBYqhEQj0f3tRQ3Ic+qILB+5T1gvPQeIo92dzGQvW27x4BYriquBW2hRyHxu4FlwduCZewbGyP+RS5U2NiAsYixAYOJYwMm6tOeJUmYcACIUA0giZIBlj696w3kSz9IPEK9n4Bogp8M8MKedbeXBEke9OBg7T1AnOYeEkCr+9JAmp+ziDbK/TBYqR+HE+rngHS6i70l1yv33Ggh3FcmGqXJsiksHhcoNEhTKJSQR9SZD32+c9gshzi3ceFu9+O3ZFUwzK8NxuEVwhyQzlY2O0+dk59mQeI9ynEESAtwZIAXH5IzFkfvkvEgmrLheTQd0O7SIPGwF0gCnBdIMsgLccGyG2ukCX2QFM3g8QNLgXQESwd5Ius4ZhntOOcDeZR7UEixHgboGWK7Dr67Ds7cJ5fYO37l+olfVNtZ0M+5Oy3cf8snlnr79ajHm7y4kT0Tv17XwWWLEjffclcxtsuMx4BH6/U8iTBx6637wvIn36d6HHKmZXG1uc+7jnC31E93XutRxmqITq1rBddzV0gXIQupzIMoCl2Sx9nRiFjsTufKDZV7wLGod96rOxLl9j26B6/XHIl752Wwo5AORX3KSndvWF60suwpflatFkt1hFHUS9Q/flAU1JGDJMWNGRwZdbTgWNHjpJeONkIiG7V54yNvl8vKzsY/c1k/OCJ1MW6WvvuhOzB6G2fn8vbYenl30wgEuA/ilfL+LigYOJlm8fn0dR/fpNXFZ252X9F48HkpEHi3Bl9uGNZPaVdqbt28exgBhLtV3k5K93ak0tvr4r2f2AujBT6n5zDD83TfJ/XgPHHeG/HeptzdzN5LIy9kJZteFdkPP/SNA3fiFmysboiBiE//2RN9VLjz/I8snVl7Ng9dz1L3jmS0dPOhu+ZDw/Tvp2wmilpVt9/mlsEeEYbqwu5HrWw4gSmWF7aMwg4N268lBagWbR2y7wOxsOOEExBpfam56N5fbewQpiSbtBbXHdPPTcu1VATs/aELgttWtcsvt1PCPTI33/TGi1FbiZe4MuMpKCVHs/rKjyfxDAU0yd5hgUb7hwiapme4oHl6h85AFa07prYL1DABwglDYj+Dp/wAAC71fsC+su6P9JZwP8Rfrv2Y3tLcnYpd/PaSYE99fBhCkTw0nkr5UHC5PKh9NfOEewvnwfmr5wH2ltCFPVrq9hQQRhDKB5J4igdj4NKBmH2FA4O9ZQNR/qKBMH/JfvsL", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"dv_cat_item (Elemento)" = _t, Porfolio = _t, #"Equipo Negocio" = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"dv_cat_item (Elemento)", type text}, {"Porfolio", type text}, {"Equipo Negocio", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"Equipo Negocio", "Negocio"}, {"dv_cat_item (Elemento)", "Elemento"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

