table Peticiones
	lineageTag: 6e9c122c-1728-4543-858c-92add460d458

	measure __UltimaActualizacion = today()
		formatString: Short Date
		lineageTag: e9c26847-01a8-4515-ac84-8f7384b90b9c

	measure Medida
		lineageTag: b6f65a34-8397-468d-b8b6-27df5de49eb8

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9931a04a-4146-4b11-9422-1148b8fd2361
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column approval
		dataType: string
		lineageTag: 9712e81c-7592-449c-a013-9095ea5398d1
		summarizeBy: none
		sourceColumn: approval

		annotation SummarizationSetBy = Automatic

	column dv_approval
		dataType: string
		lineageTag: ce0568d1-8284-4e84-9078-f0ff1a441d00
		summarizeBy: none
		sourceColumn: dv_approval

		annotation SummarizationSetBy = Automatic

	column approval_history
		dataType: string
		lineageTag: c0ea310b-49fd-42ab-8614-64883fe51bd6
		summarizeBy: none
		sourceColumn: approval_history

		annotation SummarizationSetBy = Automatic

	column approval_set
		dataType: dateTime
		formatString: General Date
		lineageTag: d229fb90-b02b-4e92-a41f-88746b591503
		summarizeBy: none
		sourceColumn: approval_set

		variation Variación
			isDefault
			relationship: c639f4fe-c928-48d2-b1cc-f7d530db7940
			defaultHierarchy: LocalDateTable_3793851e-df57-4f95-99f7-46ed4a2a21fd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column assignment_group
		dataType: string
		lineageTag: 545da11a-eea4-4188-8ca0-d40b4dd135e6
		summarizeBy: none
		sourceColumn: assignment_group

		annotation SummarizationSetBy = Automatic

	column dv_assignment_group
		dataType: string
		lineageTag: c23cd0ac-521e-45bd-a3e2-e4344f25b543
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column business_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 2a2ba3aa-f577-40d4-96b3-7380f368d3e9
		summarizeBy: none
		sourceColumn: business_duration

		variation Variación
			isDefault
			relationship: d1142ec9-1a44-4f0c-8d7b-d55cc9a77654
			defaultHierarchy: LocalDateTable_f68280eb-bb5b-48a9-9514-f526273ef267.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column cat_item
		dataType: string
		lineageTag: 53033787-0ace-4b8d-b6bb-2db357ef4b29
		summarizeBy: none
		sourceColumn: cat_item

		annotation SummarizationSetBy = Automatic

	column dv_cat_item
		dataType: string
		lineageTag: 511e096b-723e-48af-af70-945b138709da
		summarizeBy: none
		sourceColumn: dv_cat_item

		annotation SummarizationSetBy = Automatic

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 2865b4e7-3393-4787-9fcb-eaee5b94067a
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: 36d19158-fa97-41b5-baa6-18f2ca8dcede
			defaultHierarchy: LocalDateTable_9a871fa0-b294-4e5f-81bd-fb338e744b93.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column closed_by
		dataType: string
		lineageTag: 13c5ad02-b3f5-4fb1-8c51-cf9169ae9001
		summarizeBy: none
		sourceColumn: closed_by

		annotation SummarizationSetBy = Automatic

	column dv_closed_by
		dataType: string
		lineageTag: d8c6db63-9edb-4510-bd61-5874a89a4d50
		summarizeBy: none
		sourceColumn: dv_closed_by

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: e0914d4c-54f1-462d-ba8c-69b8ec3ca0ac
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column dv_company
		dataType: string
		lineageTag: 50e147ec-9312-403c-b8ff-27bc77416052
		summarizeBy: none
		sourceColumn: dv_company

		annotation SummarizationSetBy = Automatic

	column due_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 393008dd-b870-4341-b5df-620de7cc0a5e
		summarizeBy: none
		sourceColumn: due_date

		variation Variación
			isDefault
			relationship: 8441d9f3-6ab2-4c0d-b68f-1214fc2b4c38
			defaultHierarchy: LocalDateTable_ddf129c8-b2e7-455d-ae1e-6275c24ddf9f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column impact
		dataType: int64
		formatString: 0
		lineageTag: 3195112a-eaa8-4287-8cb1-f7dc886d537f
		summarizeBy: sum
		sourceColumn: impact

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: 122225ea-b50a-44f9-97d1-f77eb287e8d0
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: f7020b63-1d08-4330-bb6f-0ce232ba7c27
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: becf1d4c-28d7-47d5-aebd-dc98514d1141
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: c1c1c1ce-9f2d-4e45-91de-ba02f903a795
			defaultHierarchy: LocalDateTable_7ed399e6-b07b-41bd-804a-bc7e0c47458e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column opened_by
		dataType: string
		lineageTag: 0cf4dec0-ec39-4387-91b7-122d17a95320
		summarizeBy: none
		sourceColumn: opened_by

		annotation SummarizationSetBy = Automatic

	column dv_opened_by
		dataType: string
		lineageTag: 5449eec7-5a17-41dc-9e5c-64fe5ba70d7e
		summarizeBy: none
		sourceColumn: dv_opened_by

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: int64
		formatString: 0
		lineageTag: c359f060-588a-49ac-ae2f-4a122be9ea7c
		summarizeBy: sum
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: 398347ed-098a-4fa0-ba9a-a04c462d1993
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column request
		dataType: string
		lineageTag: 4e2d1dd5-69de-4b23-86fb-48bf2b0404b3
		summarizeBy: none
		sourceColumn: request

		annotation SummarizationSetBy = Automatic

	column dv_request
		dataType: string
		lineageTag: 6e1e8a7c-8bd3-4e5b-bf5b-d3ee1a8015cd
		summarizeBy: none
		sourceColumn: dv_request

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: 7f4e213a-ae34-404c-b5c5-853b308483fc
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column stage
		dataType: string
		lineageTag: 283a5a94-285b-4301-9a00-f45106137d44
		summarizeBy: none
		sourceColumn: stage

		annotation SummarizationSetBy = Automatic

	column dv_stage
		dataType: string
		lineageTag: 4773d82f-add4-41af-9409-22fcaafcb671
		summarizeBy: none
		sourceColumn: dv_stage

		annotation SummarizationSetBy = Automatic

	column state
		dataType: int64
		formatString: 0
		lineageTag: 339161a7-1eda-4222-9860-91e46ae92b6d
		summarizeBy: sum
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: 14036bfe-43f0-4aa2-8f84-aacc2632acc0
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column sys_class_name
		dataType: string
		lineageTag: cb04673c-05a0-49a1-a35d-cefbf1532cd5
		summarizeBy: none
		sourceColumn: sys_class_name

		annotation SummarizationSetBy = Automatic

	column dv_sys_class_name
		dataType: string
		lineageTag: 2a4a3071-6739-4277-bea9-877ae04d4379
		summarizeBy: none
		sourceColumn: dv_sys_class_name

		annotation SummarizationSetBy = Automatic

	column sys_created_by
		dataType: string
		lineageTag: 54a55f4b-e938-4229-934c-1ff1e36464a1
		summarizeBy: none
		sourceColumn: sys_created_by

		annotation SummarizationSetBy = Automatic

	column sys_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: bba60e59-054d-4107-9bd3-8805aba6ad57
		summarizeBy: none
		sourceColumn: sys_created_on

		variation Variación
			isDefault
			relationship: 2b1347db-44fe-4184-8cc1-c22cd967f23f
			defaultHierarchy: LocalDateTable_6c24ad82-cd12-4dba-a70f-216e11d44c60.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: 043eb2bf-cec9-4d3b-a918-939456abad2f
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column u_business_line
		dataType: string
		lineageTag: cad143b5-9631-4b86-9ac3-6e923b5fc562
		summarizeBy: none
		sourceColumn: u_business_line

		annotation SummarizationSetBy = Automatic

	column dv_u_business_line
		dataType: string
		lineageTag: bd0bb569-38c6-40dc-92e1-04d465bbfd08
		summarizeBy: none
		sourceColumn: dv_u_business_line

		annotation SummarizationSetBy = Automatic

	column u_catalog
		dataType: string
		lineageTag: ac9ecf9c-cb9e-4893-bf61-582bc94a1270
		summarizeBy: none
		sourceColumn: u_catalog

		annotation SummarizationSetBy = Automatic

	column dv_u_catalog
		dataType: string
		lineageTag: d63f7de6-d281-48a8-9ee7-ad777edb7b67
		summarizeBy: none
		sourceColumn: dv_u_catalog

		annotation SummarizationSetBy = Automatic

	column u_department
		dataType: string
		lineageTag: dd7171a5-eadf-4792-b991-ab41a4e13be0
		summarizeBy: none
		sourceColumn: u_department

		annotation SummarizationSetBy = Automatic

	column dv_u_department
		dataType: string
		lineageTag: fc4f609e-1493-44a2-9f00-34da0605f186
		summarizeBy: none
		sourceColumn: dv_u_department

		annotation SummarizationSetBy = Automatic

	column u_pending_reason
		dataType: string
		lineageTag: 0e259299-d720-49fd-89ac-6598464c4788
		summarizeBy: none
		sourceColumn: u_pending_reason

		annotation SummarizationSetBy = Automatic

	column dv_u_pending_reason
		dataType: string
		lineageTag: d055a05e-85e6-4901-bf53-2d9ec63456a6
		summarizeBy: none
		sourceColumn: dv_u_pending_reason

		annotation SummarizationSetBy = Automatic

	column urgency
		dataType: int64
		formatString: 0
		lineageTag: 9a076d10-6dd5-49ff-945f-d38a34aa26c8
		summarizeBy: sum
		sourceColumn: urgency

		annotation SummarizationSetBy = Automatic

	column dv_urgency
		dataType: string
		lineageTag: 86d9dddd-25ed-4ef9-8b0b-e59c1fafb160
		summarizeBy: none
		sourceColumn: dv_urgency

		annotation SummarizationSetBy = Automatic

	column 'URL Peticion' = CONCATENATE("https://acciona.service-now.com/sc_req_item.do?sysparm_query=number%3d",'Peticiones'[number])
		lineageTag: a783196b-a966-4810-a481-22aa2d8ee4df
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column __EstadoGeneral_Peticiones = if(OR(OR('Peticiones'[dv_state]="Closed Complete",'Peticiones'[dv_state]="Closed Incomplete"), 'Peticiones'[dv_state]="Closed Skipped"), "Cerrada", "Abierta")
		lineageTag: 94b8d9db-9f94-497e-897b-a0c6bebd16f1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DuracionDias_peticiones = if('Peticiones'[__EstadoGeneral_Peticiones]="Cerrada", DATEDIFF('Peticiones'[opened_at],'Peticiones'[closed_at], DAY), DATEDIFF('Peticiones'[opened_at], TODAY(), DAY))
		formatString: 0
		lineageTag: c823e455-7d8f-47b0-bf05-6190f9292bd6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column _DiaAbierta_Info_BackLog = 'Peticiones'[opened_at].[Date]
		formatString: Short Date
		lineageTag: 2efc1c09-fe59-4277-80c9-e48350c4aa17
		summarizeBy: none

		variation Variación
			isDefault
			relationship: 9c93b58b-681e-4771-ac72-e441fb0293ba
			defaultHierarchy: LocalDateTable_ce2b3391-43af-44ea-955c-a852f00c4b6a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column _MyMesAño_Abierta_Info_BackLog = FORMAT('Peticiones'[_DiaAbierta_Info_BackLog],"YYYY MMM")
		lineageTag: 334ec270-7fd1-4518-89ac-688a0d80caec
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _DiaCerrada_Info_BackLog = 'Peticiones'[closed_at].[Date]
		formatString: General Date
		lineageTag: 3b81eacd-9b08-42a6-9a29-43b121422d6d
		summarizeBy: none

		variation Variación
			isDefault
			relationship: f50f5e27-04db-4c5d-a60f-9dca28075c9d
			defaultHierarchy: LocalDateTable_4d2a134c-5e88-4ad6-bc37-c52bac709fc5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column _MyMesAño_Cerrada_Info_BackLog = FORMAT('Peticiones'[_DiaCerrada_Info_BackLog],"YYYY MMM")
		lineageTag: e9defe01-b9cb-4cb9-919b-649a93036cb5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _EsElementoSupply = if(CONTAINS(_Elementos_Pedidos_Energia, _Elementos_Pedidos_Energia[Elementos identificados por Energía], 'Peticiones'[dv_cat_item]), "Si", "No")
		lineageTag: fd6225b0-57a6-440c-bd96-f3128a26219e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _Util_para_ENERGIA_Info_BackLog = if(not('Peticiones'[_EsElementoSupply] = "No"),"Si", "No")
		lineageTag: 95f4cde5-08f6-4fcc-97bf-ebd4a23adc8e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_dv_state - español'
		dataType: string
		lineageTag: 728b76b8-7915-4c78-937b-a77bc5243229
		summarizeBy: none
		sourceColumn: _dv_state - español

		annotation SummarizationSetBy = Automatic

	column _EsAplicacionSupply = if(Peticiones[_EsElementoSupply] = "Si", "Si", "No")
		lineageTag: 8d9cfe72-3677-4bf9-b4cb-9a9222847eac
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _AplicacionSupply = if(Peticiones[_EsAplicacionSupply] = "Si", LOOKUPVALUE(_Elementos_Pedidos_Energia[Aplicación identificada por Energía],_Elementos_Pedidos_Energia[Elementos identificados por Energía], [dv_cat_item]), "N/A")
		lineageTag: f2a866f5-194b-44e3-8db9-a661a40fca8c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _EsPeticionAprobadaRechazada = IF(ISBLANK(Peticiones[approval_set]),"No", "Si")
		lineageTag: dc86cb92-2bb3-4e2c-be5f-42f55e1cbab3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _DuracionDias_HastaAprobacion = if('Peticiones'[_EsPeticionAprobadaRechazada] = "Si", (DATEDIFF('Peticiones'[opened_at],'Peticiones'[approval_set], DAY)))
		formatString: 0
		lineageTag: 966a4056-6ffa-40ef-88b7-d95d741be01c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column _DuracionDias_DesdeAprobacion = if('Peticiones'[_EsPeticionAprobadaRechazada] = "Si", (DATEDIFF('Peticiones'[approval_set],'Peticiones'[closed_at], DAY)))
		formatString: 0
		lineageTag: 17768c94-504c-4837-afcb-1791b177df47
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column closed_at_SoloFecha = [closed_at]
		formatString: Short Date
		lineageTag: 53e8b4df-f93d-4eb9-b515-3be411e657bc
		summarizeBy: none

		variation Variación
			isDefault
			relationship: aada5b85-44bf-4d47-95a2-1352cbc1a1b3
			defaultHierarchy: LocalDateTable_7269f0a5-ac56-4785-bd02-1d0446d4d08f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column opened_at_SoloFecha = [opened_at]
		formatString: Short Date
		lineageTag: 5e8b8f20-5a76-4f37-a3f9-55353e91bc8f
		summarizeBy: none

		variation Variación
			isDefault
			relationship: 1afea173-ccf3-4553-99ae-6dab08842c44
			defaultHierarchy: LocalDateTable_97957957-b28e-4762-a250-41f0554200fb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column ELEMENTOSyCIs_ENERGIA = if (Peticiones[dv_cat_item] = "RPA Systems", Peticiones[_Elementos_Pedidos_Energia.CI_Texto], Peticiones[dv_cat_item])
		lineageTag: 4d6c6963-2ed0-4a3a-b4bd-01cea3ab17ee
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column APLICACION_DEFINTIVA_IDENTIF_ENERGIA = LOOKUPVALUE(_Elementos_Pedidos_Energia[Aplicación identificada por Energía],_Elementos_Pedidos_Energia[Elementos identificados por Energía], [ELEMENTOSyCIs_ENERGIA])
		lineageTag: ec02a9dd-3c02-4e8a-8cbe-4eea3ca40d15
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'sc_item_option_mtom.Variable_AffectedCI' = LOOKUPVALUE('SERV_NOW sc_item_option_mtom'[Variable_AffectedCI],'SERV_NOW sc_item_option_mtom'[dv_request_item], [number])
		lineageTag: 3dc683e4-a8ae-4189-9637-91ccd6e31417
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'sc_item_option_mtom.ValorEnSysID_Variable_AffectedCI' = LOOKUPVALUE('SERV_NOW sc_item_option_mtom'[ValorEnSysID_Variable_AffectedCI],'SERV_NOW sc_item_option_mtom'[dv_request_item], [number])
		lineageTag: 7bdacd20-ff3b-45e0-a294-d39faf05f107
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_Elementos_Pedidos_Energia.CI_Texto' = LOOKUPVALUE('_Elementos_Pedidos_Energia'[Elementos identificados por Energía],'_Elementos_Pedidos_Energia'[cmdb_ci_appl.sys_id], [sc_item_option_mtom.ValorEnSysID_Variable_AffectedCI])
		lineageTag: 5614890b-8dd9-4d74-9d2b-a71c0cd80434
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column NroMes-Abierta = ```
			'Peticiones'[Opened_at].[NroMes]
			
			```
		formatString: 0
		lineageTag: cb8f0377-d93d-4c8b-ae78-1125b7eb44bc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Año-Abierta = 'Peticiones'[Opened_at].[Año]
		formatString: 0
		lineageTag: f46e242e-7d72-462c-a8bc-05cc23b3a293
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Fecha_Apertura = DATE(Peticiones[Año-Abierta],Peticiones[NroMes-Abierta],1)
		formatString: Short Date
		lineageTag: 6c559696-b19b-403a-a581-819acc8f40a1
		summarizeBy: none

		variation Variación
			isDefault
			relationship: 9d310e57-855b-4a4f-85c3-48aa2f393015
			defaultHierarchy: LocalDateTable_8dd7aa05-9a39-477d-9ae1-03c1658f5929.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci
		dataType: string
		lineageTag: 1b434301-96e6-4b00-97c3-d3a21f1bb63a
		summarizeBy: none
		sourceColumn: dv_cmdb_ci

		annotation SummarizationSetBy = Automatic

	column cmdb_ci_business_app
		dataType: string
		lineageTag: 82248edb-4b28-4ff5-99ef-6bed7ab92e52
		summarizeBy: none
		sourceColumn: cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci_business_app
		dataType: string
		lineageTag: 81c99deb-b081-4963-9b77-5923fc87fe93
		summarizeBy: none
		sourceColumn: dv_cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column sc_catalog
		dataType: string
		lineageTag: 67d43072-d7b1-460d-876c-552a2f15a417
		summarizeBy: none
		sourceColumn: sc_catalog

		annotation SummarizationSetBy = Automatic

	column dv_sc_catalog
		dataType: string
		lineageTag: fac80bc3-47c0-4f30-aa46-e151691165b9
		summarizeBy: none
		sourceColumn: dv_sc_catalog

		annotation SummarizationSetBy = Automatic

	partition Peticiones-ff66ef94-742d-44b1-a3b0-f00a3c4b5868 = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "DWH"),
				    SERV_NOW_sc_req_item = Origen{[Schema="SERV_NOW",Item="sc_req_item"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(SERV_NOW_sc_req_item, each [opened_at] >= #datetime(2022, 1, 1, 0, 0, 0)),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Filas filtradas",{"u_ref_country", "dv_u_ref_country", "u_requested_for", "dv_u_requested_for", "u_responded", "u_size", "dv_u_size", "u_vendor_type", "dv_u_vendor_type", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "task_for", "dv_task_for", "time_worked", "dv_time_worked", "u_acciona_priority", "activity_due", "additional_assignee_list", "assigned_to", "dv_assigned_to", "backordered", "billable", "dv_business_duration", "business_service", "dv_business_service", "calendar_duration", "dv_calendar_duration", "close_notes", "cmdb_ci", "comments", "comments_and_work_notes", "configuration_item", "dv_configuration_item", "contact_type", "dv_contact_type", "context", "dv_context", "correlation_display", "correlation_id", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "description", "escalation", "dv_escalation", "estimated_delivery", "expected_start", "follow_up", "group_list", "knowledge", "location", "dv_location", "made_sla", "order", "order_guide", "dv_order_guide", "parent", "dv_parent", "price", "quantity", "reassignment_count", "recurring_frequency", "dv_recurring_frequency", "recurring_price", "rejection_goto", "dv_rejection_goto", "service_offering", "dv_service_offering", "skills", "sla_due", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "u_close_task", "u_external_vendor", "dv_u_external_vendor", "u_manual_priority", "u_metal", "dv_u_metal", "u_phone", "u_previous_groups", "u_progress", "u_state_date", "user_input", "variables", "watch_list", "wf_activity", "dv_wf_activity", "work_end", "work_notes", "work_notes_list", "work_start"}),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Columnas quitadas", "dv_state", "dv_state - Copia"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna duplicada",{{"dv_state - Copia", "_dv_state - español"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","Closed Complete","Cerrado completo",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Closed Incomplete","Cerrado incompleto",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","Open","Abierto",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","Closed Skipped","Cerrado omitido",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","On hold","En espera",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","Work in Progress","En curso",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Valor reemplazado5", each ([dv_u_catalog] = "Energía"))
				in
				    #"Filas filtradas1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

