table 'Tareas de Peticiones'
	lineageTag: 9b24bc50-4560-47c6-9acc-75df04e6fa82

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 266011fb-ecad-4bd2-a735-c5411d9bdad0
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column assigned_to
		dataType: string
		lineageTag: 15e3fb71-7347-44b2-a0ba-6b8e0ccc965c
		summarizeBy: none
		sourceColumn: assigned_to

		annotation SummarizationSetBy = Automatic

	column dv_assigned_to
		dataType: string
		lineageTag: 1b6e03c1-eb99-422d-bbf9-d6dd7bc449d6
		summarizeBy: none
		sourceColumn: dv_assigned_to

		annotation SummarizationSetBy = Automatic

	column assignment_group
		dataType: string
		lineageTag: 063b1372-e1c1-4284-a5b6-670f65d028db
		summarizeBy: none
		sourceColumn: assignment_group

		annotation SummarizationSetBy = Automatic

	column dv_assignment_group
		dataType: string
		lineageTag: a3e41914-2712-4482-b0e6-283a5a2dd967
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: c822a69f-a7cb-4a70-9023-a357ebeca907
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: f7c2f1ff-13a8-40fe-a057-8dca7148f2d5
			defaultHierarchy: LocalDateTable_3b14cbf9-74ad-4e65-9b3b-9b108f040fbe.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column closed_by
		dataType: string
		lineageTag: 36a5d5d4-2cd7-4986-9c7c-f7661b9fbc63
		summarizeBy: none
		sourceColumn: closed_by

		annotation SummarizationSetBy = Automatic

	column dv_closed_by
		dataType: string
		lineageTag: 926ea6aa-42f4-4e14-8121-f7dcecf29be2
		summarizeBy: none
		sourceColumn: dv_closed_by

		annotation SummarizationSetBy = Automatic

	column impact
		dataType: int64
		formatString: 0
		lineageTag: 9ff439ad-da07-445a-9de0-2827a9ad9f21
		summarizeBy: sum
		sourceColumn: impact

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: 537d58a5-f4de-4c93-8c71-ce6899fe235f
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: b52e27ea-8435-4b0f-88a9-efa5555af2b4
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: c7af269e-98f0-4d1d-9915-6445e65d41fa
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: 6ed32cc8-c4a6-4853-b891-dd2bb5a5f215
			defaultHierarchy: LocalDateTable_cd7ef9c5-b9bb-4e63-9cd3-5d6702af6771.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column opened_by
		dataType: string
		lineageTag: de3d18b5-f8ae-4c26-b2a2-9e6e9486f832
		summarizeBy: none
		sourceColumn: opened_by

		annotation SummarizationSetBy = Automatic

	column dv_opened_by
		dataType: string
		lineageTag: 48caf958-259e-45ba-8b0e-86a1969b5e92
		summarizeBy: none
		sourceColumn: dv_opened_by

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: 82c57de4-5475-4d0a-a148-c1aeb88be709
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: fcfea250-f829-4dab-b268-5ec68a29daca
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: int64
		formatString: 0
		lineageTag: 12ef2894-4e09-446c-b6be-4a1580ccdcca
		summarizeBy: sum
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: cbfa1bff-9fa7-42de-8436-58ca94a907b6
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column request
		dataType: string
		lineageTag: 091f7380-8f14-4e83-98ed-8905f64edf57
		summarizeBy: none
		sourceColumn: request

		annotation SummarizationSetBy = Automatic

	column dv_request
		dataType: string
		lineageTag: 5965e191-b00b-4ed3-ba65-0db5a79094c4
		summarizeBy: none
		sourceColumn: dv_request

		annotation SummarizationSetBy = Automatic

	column request_item
		dataType: string
		lineageTag: d339298f-3166-43d0-9f48-4e7f960ac653
		summarizeBy: none
		sourceColumn: request_item

		annotation SummarizationSetBy = Automatic

	column dv_request_item
		dataType: string
		lineageTag: 55a346a5-0a76-4ed3-bfb1-ea8ae9b82a70
		summarizeBy: none
		sourceColumn: dv_request_item

		annotation SummarizationSetBy = Automatic

	column state
		dataType: int64
		formatString: 0
		lineageTag: 95481cbb-fd51-411a-81b6-500eb703a3a4
		summarizeBy: sum
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: 819954c7-b9bc-45cf-b576-c13107f5c486
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column sys_created_by
		dataType: string
		lineageTag: 674ab722-6927-450b-9b4e-ea050f501b1c
		summarizeBy: none
		sourceColumn: sys_created_by

		annotation SummarizationSetBy = Automatic

	column sys_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 07940fbd-b18d-4adf-b0b1-09c5bc53d3f2
		summarizeBy: none
		sourceColumn: sys_created_on

		variation Variación
			isDefault
			relationship: 614a0ab8-bb9a-41b1-8c1e-9c5e09a523a4
			defaultHierarchy: LocalDateTable_14cba619-bd04-4da6-afbb-bc35092a3afa.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: ede33b32-c5ec-4f1a-a216-d14844aeb5e2
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column u_previous_groups
		dataType: string
		lineageTag: fb8983db-a8ed-4d14-ae85-e32448689b8a
		summarizeBy: none
		sourceColumn: u_previous_groups

		annotation SummarizationSetBy = Automatic

	column urgency
		dataType: int64
		formatString: 0
		lineageTag: 4da592ec-386b-46ba-bfb8-8580c6d21e5a
		summarizeBy: sum
		sourceColumn: urgency

		annotation SummarizationSetBy = Automatic

	column dv_urgency
		dataType: string
		lineageTag: 70f485dc-609e-4dc1-a6b5-16463881a8b8
		summarizeBy: none
		sourceColumn: dv_urgency

		annotation SummarizationSetBy = Automatic

	column _Peticiones_dv_cat_item = LOOKUPVALUE('Peticiones'[dv_cat_item],'Peticiones'[sys_id], [parent])
		lineageTag: de716806-58ee-4609-98d2-dcd52bbb75ed
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_dv_state - español'
		dataType: string
		lineageTag: 6b17e8f3-9496-426c-92c0-eb08808cafad
		summarizeBy: none
		sourceColumn: _dv_state - español

		annotation SummarizationSetBy = Automatic

	column 'URL Tarea' = CONCATENATE("https://acciona.service-now.com/sc_task.do?sysparm_query=number%3d",'Tareas de Peticiones'[number])
		lineageTag: 67fc457a-dcb9-4971-9473-fd2e8be74646
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column __EstadoGeneral_Tareas = if(OR(OR('Tareas de Peticiones'[dv_state]="Closed Complete",'Tareas de Peticiones'[dv_state]="Closed Incomplete"), 'Tareas de Peticiones'[dv_state]="Closed Skipped"), "Cerrada", "Abierta")
		lineageTag: 4f15b0df-d236-4242-a8e7-05d4452b05c9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DuracionDias_Tareas = if('Tareas de Peticiones'[__EstadoGeneral_Tareas]="Cerrada", DATEDIFF('Tareas de Peticiones'[opened_at],'Tareas de Peticiones'[closed_at], DAY), DATEDIFF('Tareas de Peticiones'[opened_at], TODAY(), DAY))
		formatString: 0
		lineageTag: 3058d7c1-7dba-4bfd-9c7f-bed54fcae5ba
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column DuracionAbiertas_hastaHoy = DATEDIFF('Tareas de Peticiones'[opened_at].[Date], today(), DAY)
		formatString: 0
		lineageTag: d9ea153e-5037-445b-95e5-d7e58f8026df
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column APLICACION_DEFINTIVA_IDENTIF_ENERGIA = LOOKUPVALUE('Peticiones'[APLICACION_DEFINTIVA_IDENTIF_ENERGIA],'Peticiones'[number], [dv_parent])
		lineageTag: 55e69916-4937-47ae-8546-7b647d0421cb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Peticiones.number'
		dataType: string
		lineageTag: e3941f1e-2235-440d-bd54-da408b84d538
		summarizeBy: none
		sourceColumn: Peticiones.number

		annotation SummarizationSetBy = Automatic

	column u_pending_reason
		dataType: string
		lineageTag: c1ae6fb7-15b6-4517-905e-60774a23cb38
		summarizeBy: none
		sourceColumn: u_pending_reason

		annotation SummarizationSetBy = Automatic

	column cmdb_ci
		dataType: string
		lineageTag: f0d16346-0c81-4312-b2fd-324c88e5cc02
		summarizeBy: none
		sourceColumn: cmdb_ci

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci
		dataType: string
		lineageTag: 8c7b62e0-938b-40f6-b404-67be61bd9272
		summarizeBy: none
		sourceColumn: dv_cmdb_ci

		annotation SummarizationSetBy = Automatic

	column cmdb_ci_business_app
		dataType: string
		lineageTag: 67a7a709-b701-4c97-8ca9-6f425ffc6e7b
		summarizeBy: none
		sourceColumn: cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column 'number - Copia'
		dataType: string
		lineageTag: f2eede8d-bb3c-4374-8df8-7a29116cc8aa
		summarizeBy: none
		sourceColumn: number - Copia

		annotation SummarizationSetBy = Automatic

	column cat_item
		dataType: string
		lineageTag: 26aa83e3-b417-4666-a1a2-df02c52c0e59
		summarizeBy: none
		sourceColumn: cat_item

		annotation SummarizationSetBy = Automatic

	column dv_cat_item
		dataType: string
		lineageTag: 75efb5cb-abcb-442d-a638-738fdaf7f0b4
		summarizeBy: none
		sourceColumn: dv_cat_item

		annotation SummarizationSetBy = Automatic

	column u_calendar_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8a9c8dbf-25df-4928-85a2-0a6fcf9fc957
		summarizeBy: none
		sourceColumn: u_calendar_date

		variation Variación
			isDefault
			relationship: 6f401d18-d131-4e10-bf81-1bbe35f0176f
			defaultHierarchy: LocalDateTable_c5f61d7c-ef1d-4e4e-89a5-fbde855631d3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_request_item_vars
		dataType: string
		lineageTag: 2fefe857-6a35-4fad-9e6b-b8a858512a78
		summarizeBy: none
		sourceColumn: u_request_item_vars

		annotation SummarizationSetBy = Automatic

	column u_rpt_mes
		dataType: int64
		formatString: 0
		lineageTag: 0912911f-96e6-4f27-bf4d-fdaf2abda246
		summarizeBy: sum
		sourceColumn: u_rpt_mes

		annotation SummarizationSetBy = Automatic

	column u_rpt_mttr
		dataType: dateTime
		formatString: General Date
		lineageTag: 4db51101-a43c-4699-845d-3d506e471947
		summarizeBy: none
		sourceColumn: u_rpt_mttr

		variation Variación
			isDefault
			relationship: 7039af10-ed1c-49de-9d67-30072f92b0a7
			defaultHierarchy: LocalDateTable_4ebc73cd-238f-4837-8f65-28f32ad46ae7.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_u_rpt_mttr
		dataType: string
		lineageTag: 05d3c7b7-a3b1-416d-8fdf-775b72d3f83d
		summarizeBy: none
		sourceColumn: dv_u_rpt_mttr

		annotation SummarizationSetBy = Automatic

	column u_rpt_old
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8f8560b8-bf78-4fbc-b3aa-ba71e0ebf8c2
		summarizeBy: none
		sourceColumn: u_rpt_old

		annotation SummarizationSetBy = Automatic

	column u_rpt_oldness
		dataType: dateTime
		formatString: General Date
		lineageTag: c6039325-9eb5-407e-a13c-92487b94eee1
		summarizeBy: none
		sourceColumn: u_rpt_oldness

		variation Variación
			isDefault
			relationship: 3aa98174-8b7e-4f58-a707-38a9e9d3bc19
			defaultHierarchy: LocalDateTable_ea3f9462-3501-4bc7-870c-d59393e516f1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_u_rpt_oldness
		dataType: string
		lineageTag: 93f8017d-cf12-4f33-bc95-5a24b2e82362
		summarizeBy: none
		sourceColumn: dv_u_rpt_oldness

		annotation SummarizationSetBy = Automatic

	partition 'Tareas de Peticiones-0234b031-dee3-4c88-a5c4-e53b142aaec0' = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "DWH"),
				    SERV_NOW_sc_task = Origen{[Schema="SERV_NOW",Item="sc_task"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_sc_task,{"activity_due", "additional_assignee_list", "approval", "dv_approval", "approval_history", "approval_set", "business_duration", "dv_business_duration", "business_service", "dv_business_service", "calendar_duration", "dv_calendar_duration", "calendar_stc", "close_notes","dv_cmdb_ci_business_app", "comments", "comments_and_work_notes", "company", "dv_company", "contact_type", "dv_contact_type", "contract", "dv_contract", "correlation_display", "correlation_id", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "description", "due_date", "escalation", "dv_escalation", "expected_start", "follow_up", "group_list", "knowledge", "location", "dv_location", "made_sla", "order", "reassignment_count", "rejection_goto", "dv_rejection_goto", "route_reason", "dv_route_reason", "sc_catalog", "dv_sc_catalog", "service_offering", "dv_service_offering", "short_description", "skills", "sla_due", "sys_class_name", "dv_sys_class_name", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "task_effective_number", "task_for", "dv_task_for", "time_worked", "dv_time_worked", "u_acciona_priority", "u_business_line", "dv_u_business_line", "u_catalog", "dv_u_catalog", "u_commented", "u_csc_area", "dv_u_csc_area", "u_department", "dv_u_department", "u_external_vendor", "dv_u_external_vendor", "u_item_task", "dv_u_item_task", "u_metal", "dv_u_metal", "u_operational_committee_comment", "u_payroll_area", "dv_u_payroll_area", "dv_u_pending_reason", "u_phone", "u_progress", "u_ref_country", "dv_u_ref_country", "u_responded", "u_size", "dv_u_size", "u_state_date", "u_var_sla", "u_vendor_type", "dv_u_vendor_type", "universal_request", "dv_universal_request", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "user_input", "variables", "watch_list", "wf_activity", "dv_wf_activity", "work_end", "work_notes", "work_notes_list", "work_start"}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas quitadas", each [opened_at] >= #datetime(2022, 1, 1, 0, 0, 0)),
				    #"Consultas combinadas" = Table.NestedJoin(#"Filas filtradas", {"parent"}, Peticiones, {"sys_id"}, "Peticiones", JoinKind.LeftOuter),
				    #"Se expandió Peticiones" = Table.ExpandTableColumn(#"Consultas combinadas", "Peticiones", {"number"}, {"Peticiones.number"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Se expandió Peticiones", each [Peticiones.number] <> null and [Peticiones.number] <> ""),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Filas filtradas1", "dv_state", "dv_state - Copia"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna duplicada",{{"dv_state - Copia", "_dv_state - español"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","Open","Abierto",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Work in Progress","En curso",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","On hold","En espera",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","Closed Complete","Cerrado completo",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","Closed Incomplete","Cerrado incompleto",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","Closed Skipped","Cerrado omitido",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Columna duplicada1" = Table.DuplicateColumn(#"Valor reemplazado5", "number", "number - Copia"),
				    #"Filas ordenadas" = Table.Sort(#"Columna duplicada1",{{"number", Order.Ascending}}),
				    #"Duplicados quitados" = Table.Distinct(#"Filas ordenadas", {"number"})
				in
				    #"Duplicados quitados"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

