table BI_Aplicación
	lineageTag: 82b2279e-d662-45a3-9255-f6bf1a762a3f

	measure 'Presupuesto Real €' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Evolutivos", 'BI_Aplicación'[Atributo] = "Presupuesto")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: f68272cc-4fa2-4b2c-a229-5c91a7e3f12d

	measure 'Línea Base Real consumida €' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos", 'BI_Aplicación'[Atributo] = "Consumo Real", MONTH('BI_Aplicación'[Periodo]<= MONTH(TODAY())))
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 8d83a0bd-5eaa-4c04-9bf5-2661f5cacfb8

	measure '€_presupuesto restante' = [Presupuesto Real €] - [Línea Base Real consumida €]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: b5744447-0023-46cd-8c31-601ae92d1d6f

	measure Linea_Base_esperada_total = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Atributo]="Línea Base Objetivo", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: e5a58adf-70ff-44b2-aaf6-82c01999b7c9

	measure Linea_Base_esperada_total_mensual = CALCULATE(SUM('BI_Aplicación'[Valor])/12, 'BI_Aplicación'[Atributo]="Línea Base Objetivo", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 30bb2c67-e14b-4c04-a4fd-3cd070f8f7f8

	measure '€_Linea Base Real por Mes' =
			
			[Línea Base Real consumida €]/ [Meses_Restantes_Año_12_2]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 71234346-6fdc-455f-b969-4bb4765edfaa

	measure 'Linea Base Restante mes' = DIVIDE([€_presupuesto restante], [Meses_Restantes_Año_1], 0)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: b9d6d799-f4a4-4c9f-a0f8-1b864ae8855c

	measure Meses_Restantes_Año_1 =
			IF(
			    YEAR(TODAY()) > YEAR(MAX('BI_Aplicación'[Periodo])),
			    1,
			    12 - MONTH(TODAY())
			)
		formatString: 0
		lineageTag: 64800829-db79-4da8-9947-cd89c2efec59

	measure Desviacion-Proyectado = [Presupuesto Real €] - [Línea Base Real Consumida €] - [LB proyectada Evo €] - 47058
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: be5cc12f-bcc6-4914-83e1-1daea36cf1f2

	measure Línea_Real_Consumida_SamePeriodLastYear =
			
			[Línea Base Real consumida €] -
			
			CALCULATE(SUM('BI_Aplicación'[Valor]),
			 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos",
			  'BI_Aplicación'[Atributo] = "Consumo Real",
			   DATESBETWEEN(Fechas[Date], DATE(YEAR(TODAY()) -1,01,01), DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))))
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: dbbe8d66-ee09-4656-b363-6769bcda612f

	measure Total_LB_Uts_Real_Valor = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Evolutivos", 'BI_Aplicación'[Atributo] = "Consumo Real")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 4cb46602-443f-4d3c-a721-b5a9032279c0

	measure Comparación_Consumo_% =
			([Línea Base Real consumida €] - CALCULATE(SUM('BI_Aplicación'[Valor]),
			 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos",
			  'BI_Aplicación'[Atributo] = "Consumo Real",
			   DATESBETWEEN(Fechas[Date], DATE(YEAR(TODAY()) -1,01,01), DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))))) / CALCULATE(SUM('BI_Aplicación'[Valor]),
			 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos",
			  'BI_Aplicación'[Atributo] = "Consumo Real",
			   DATESBETWEEN(Fechas[Date], DATE(YEAR(TODAY()) -1,01,01), DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: b69452e7-fbb5-42ca-8def-f0fe026345ed

	measure 'Presupuesto Real Uts' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Evolutivos", 'BI_Aplicación'[Atributo] = "Presupuesto Uts")
		formatString: #,0.00
		lineageTag: aca46b56-644d-460b-afc5-2434a3063c2c

	measure Total_LB_Uts_Real_Aplicaciones = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Evolutivos", 'BI_Aplicación'[Atributo] = "Consumo Real Uts")
		formatString: #,0.00
		lineageTag: 2eb6147c-7fc8-4387-9ac1-b08161ed68cd

	measure UTS_restantes = [Presupuesto Real Uts]  - [Total_LB_Uts_Real_Aplicaciones]
		formatString: #,0.00
		lineageTag: 41e87eb0-4faf-4e1e-ad3a-911a120a4679

	measure UTS_Disponibles_Ppto = [Presupuesto Real Uts] - [Total_LB_Uts_Real_Aplicaciones] - [LB proyectada Evo]
		lineageTag: bc6af0dc-b7a7-4db7-b0d5-1ee2da82574d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Coste UT LB Objetivo' = [Linea_Base_esperada_total] / [UTS_totales_disponibles]
		lineageTag: 682b1a56-b616-4a6f-87eb-3ab4397fae25

	measure UTS_totales_disponibles = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Atributo] = "Línea Base Objetivo Uts", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos", ALL('BI_Aplicación'[Periodo]))
		lineageTag: 44f9b919-6124-4d1b-a9db-0eff47dbe3ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure UTS_restantes_mensual = [Presupuesto Real Uts] / 12
		formatString: #,0.00
		lineageTag: 886303cc-9935-4147-806e-3bca2e721eb3

	measure Total_LB_Uts_Real_Aplicaciones_mes = [Total_LB_Uts_Real_Aplicaciones] / [Meses_Restantes_Año_12_2]
		formatString: #,0.00
		lineageTag: e1358ac7-2c70-4998-bba0-f195e808171e

	measure 'UTS_mes_disponibles restantes' = DIVIDE([UTS_restantes] , [Meses_Restantes_Año_1], 0)
		formatString: #,0.00
		lineageTag: b2a3a6b8-3744-4fa4-8f29-54c72d518040

	measure Meses_Restantes_Año_12 =
			IF(
			    YEAR(TODAY()) > YEAR(MAX('BI_Aplicación'[Periodo])),
			    12,
			    12 - MONTH(TODAY()))
		formatString: 0.0
		lineageTag: eab1aa56-4060-4a47-9b9c-e747e95aef89

	measure Línea_Real_Consumida_Uts_SamePeriodLastYear = ```
			[Total_LB_Uts_Real_Aplicaciones] - 
			
			CALCULATE(SUM('BI_Aplicación'[Valor]),
			 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos",
			  'BI_Aplicación'[Atributo] = "Consumo Real Uts",
			   DATESBETWEEN(Fechas[Date], DATE(YEAR(TODAY()) -1,01,01), DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))))
			```
		formatString: #,0.00
		lineageTag: 967342c3-2427-419e-83f5-4d164a80fd7f

	measure 'Línea Base Real consumida €_C' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] = "Correctivos", 'BI_Aplicación'[Atributo] = "Consumo Real")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 127c015c-995b-441c-86d2-f2be105d5fd3

	measure 'Coste Fijo' = [Total_LB_UTs_C] * [Euro_Hora_Estimado_C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 27e44d6d-2698-42cc-b753-0422059a8b9f

	measure Consumido_PrecioHoraContratado = [Total_LB_Uts_Real_Aplicaciones_C] * [Precio_Hora_Contratado]
		lineageTag: 3f904350-722b-4880-98f2-f141e06aadec

	measure Precio_Hora_Contratado = [Linea_Base_esperada_total_C] / [UTS_totales_disponibles_ C]
		lineageTag: 6c755c12-1178-42e9-ba44-e4875552ffc7

	measure 'UTS_totales_disponibles_ C' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Atributo] = "Línea Base Objetivo Uts", 'BI_Aplicación'[Descripción Ámbito] = "Correctivos")
		lineageTag: 0a4c2a64-2e98-4ae7-a284-ed7fd170bf3e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Linea_Base_esperada_total_C = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Atributo]="Línea Base Objetivo", 'BI_Aplicación'[Descripción Ámbito] = "Correctivos")
		lineageTag: f8368757-9976-4f0e-9eaf-5e45649b6de5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Linea_Base_esperada_total_mes_C_2 = ([Linea_Base_esperada_total_mensual_C] * [Meses_Restantes_Año_12])
		lineageTag: 93b4f5e6-eb53-440a-8b21-a124d49e3875

	measure Linea_Base_esperada_total_mensual_C = CALCULATE(SUM('BI_Aplicación'[Valor])/12, 'BI_Aplicación'[Atributo]="Línea Base Objetivo", 'BI_Aplicación'[Descripción Ámbito] = "Correctivos")
		lineageTag: 2d18a0a6-d26f-43d2-9735-2909eb7ce59e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Total_LB_Uts_Real_Aplicaciones_C = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Correctivos", 'BI_Aplicación'[Atributo] = "Consumo Real Uts")
		formatString: 0.0
		lineageTag: a072f1a3-b372-4be2-8fd9-d90f12fc00a6

	measure Ahorro = [Coste Fijo] - [Gasto_Hipotetico_C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 4cfbdaa9-39b3-4712-b13f-bfe1e4f1316f

	measure Coste_FIjo_Horas_Incurridas = DIVIDE([Linea_Base_esperada_total_C], [Total_LB_Horas_Real_Aplicaciones_C], 0)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 5519d51e-e7ad-4789-9f08-2e711bfc4788

	measure Tendencia_LB_C = DIVIDE('BI_Aplicación'[Linea Base Real Consumida Total], [Meses_LB_Real_Total], 0)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 9f154ad7-8a8e-492d-a4ed-21b5c3c9e547

	measure Meses_LB_Real_Total = CALCULATE((DATEDIFF(FIRSTDATE('BI_Aplicación'[Periodo]), LASTDATE('BI_Aplicación'[Periodo]), MONTH) +1),'BI_Aplicación'[Atributo] = "Consumo Real", ALLEXCEPT('BI_Aplicación','BI_Aplicación'[Área],'BI_Aplicación'[SubÁrea],'BI_Aplicación'[Aplicación]), ALL(Fechas))
		formatString: 0
		lineageTag: d51fe5b3-f4cc-420e-b25a-22afc4cb5020

	measure 'Linea Base Real Consumida Total' = CALCULATE('BI_Aplicación'[Línea Base Real consumida €], ALL(Fechas))
		lineageTag: 99379ea1-1e9d-4103-ad21-5fea20148b96

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Linea Base Real Consumida Total C' = CALCULATE('BI_Aplicación'[Línea Base Real consumida €_C], ALL(Fechas))
		lineageTag: 36ffc5b9-9d4f-4959-bee4-15842ed88d3d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Total_LB_Uts_Real_Valor_C = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Correctivos", 'BI_Aplicación'[Atributo] = "Consumo Real")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: f46b442a-e122-4398-8a9a-65223304e570

	measure Euro_Hora_Estimado_C = [Linea_Base_esperada_total_C] / [Total_LB_UTs_C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 8b2ded0d-b07e-49f4-9b3f-4216ef61bc4c

	measure Total_LB_UTs_C =
			CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] = "Correctivos", 'BI_Aplicación'[Atributo] = "Línea Base Objetivo Uts", FILTER(ALL('BI_Aplicación'[Periodo]), IF(
			    YEAR(TODAY()) > YEAR(MAX('BI_Aplicación'[Periodo])),
			    12,
			    MONTH('BI_Aplicación'[Periodo]) <= MONTH(TODAY()))
			)
			)
		lineageTag: 853203da-73e3-46a7-bbeb-cd1c5b42b172

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Comparación_Euro_Hora = IF([Euro_Hora_Correctivo_C] < [Euro_Hora_Estimado_C], "#0EB194", "#CD5C5C")
		lineageTag: 930137fc-12fd-4d3f-8079-c9ce2ea30546

	measure Euro_hora_Correctivo_C = [Línea Base Real consumida €_C] / [Total_LB_Uts_Real_Aplicaciones_C]
		lineageTag: 384d992b-0534-4968-801b-5891ebce9fd8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'UTS_restantes C' = [UTS_totales_disponibles_ C] - [Total_LB_Horas_Real_Aplicaciones_C]
		formatString: 0.00
		lineageTag: c64b8d2d-c9f8-45fd-9e2c-f171ae474641

	measure Tendencia_Uts_C = DIVIDE([Total_LB_Horas_Real_Aplicaciones_C], [Meses_Restantes_Año_12_2])
		formatString: #,0.00
		lineageTag: 3a488925-3f06-4f2b-951f-4e8e09eef517

	measure Tendencia_Color = IF([Total_LB_Uts_Real_Aplicaciones_C] > [Linea_Base_esperada_total_C], 0, 1)
		formatString: 0
		lineageTag: 92ab65f3-93a2-4306-ad32-5cabc2ec1806

	measure Ppto_Restante_Año = [Presupuesto Real €] - [Línea Base Real consumida €]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 31181391-db97-4fb2-a5eb-c1c003ff8a3e

	measure Presupuesto€_Mes = [Presupuesto Real €] / 12
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 91899406-28cd-4003-b5bd-e2c747f08e0c

	measure Meses_Restantes_Año_12_2 =
			IF(
			    YEAR(TODAY()) > YEAR(MAX('BI_Aplicación'[Periodo])),
			    12,
			    MONTH(TODAY()))
		formatString: 0
		lineageTag: 8e9da8b8-599e-49a2-858e-a94f8bf8e4da

	measure Uts_desviacion-proyectado = [UTS_totales_disponibles] - ([Total_LB_Uts_Real_Aplicaciones_mes] * 12)
		lineageTag: 88b5967f-2ea3-455f-a861-ba1a9e804139

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Gasto_Hipotetico_C = [Euro_Hora_Estimado_C] * [Total_LB_Horas_Real_Aplicaciones_C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: f326b84c-204d-47b4-b463-4b7d5992a4b2

	measure Total_LB_Horas_Real_Aplicaciones_C = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Correctivos", 'BI_Aplicación'[Atributo] = "Consumo Real Uts")
		formatString: #,0.00
		lineageTag: 696ba9d1-0614-42a0-b7cd-6169ae0615f0

	measure Marcador_Ahorro = IF([Coste Fijo] > [Gasto_Hipotetico_C], "#0EB194", "#CD5C5C")
		lineageTag: b44a43cf-7b56-4ffc-b43d-db10f2259d3b

	measure 'LB proyectada Evo' = ```
			CALCULATE(SUM('BI_Aplicación'[Valor]), 
			'BI_Aplicación'[Atributo]="Línea Base Proyectada Uts", 
			'BI_Aplicación'[Descripción Ámbito] = "Evolutivos" )
			```
		lineageTag: 17478b28-2b4b-4f36-ae47-1801638403b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LB proyectada Evo €' = ```
			CALCULATE(SUM('BI_Aplicación'[Valor]), 
			'BI_Aplicación'[Atributo]="Línea Base Proyectada", 
			'BI_Aplicación'[Descripción Ámbito] = "Evolutivos" )
			```
		lineageTag: 6f11f86d-e42c-4d27-8453-8f25018cfc6c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Servicio TIC'
		dataType: string
		lineageTag: a44165bf-a6a6-4125-8a68-c166c2400c90
		summarizeBy: none
		sourceColumn: Servicio TIC

		annotation SummarizationSetBy = Automatic

	column Ámbito
		dataType: string
		lineageTag: 3055f89c-7a0f-4df2-8340-03ebe38f56b2
		summarizeBy: none
		sourceColumn: Ámbito

		annotation SummarizationSetBy = Automatic

	column 'Descripción Ámbito'
		dataType: string
		lineageTag: 9568bb83-40fb-4744-a9e9-5fd6f17fc3f6
		summarizeBy: none
		sourceColumn: Descripción Ámbito

		annotation SummarizationSetBy = Automatic

	column Área
		dataType: string
		lineageTag: 2b28d807-4412-47e4-a4e3-aab26b59dcc4
		summarizeBy: none
		sourceColumn: Área

		annotation SummarizationSetBy = Automatic

	column SubÁrea
		dataType: string
		lineageTag: 42a2e5b2-9da0-4728-bd09-278746e4a9bd
		summarizeBy: none
		sourceColumn: SubÁrea

		annotation SummarizationSetBy = Automatic

	column Aplicación
		dataType: string
		lineageTag: 71938e4a-f6f2-4179-b74e-d63669850554
		summarizeBy: none
		sourceColumn: Aplicación

		annotation SummarizationSetBy = Automatic

	column Periodo
		dataType: dateTime
		formatString: Long Date
		lineageTag: 61d0cfd5-eb9a-440e-bde2-6d6f7aaa6489
		summarizeBy: none
		sourceColumn: Periodo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Atributo
		dataType: string
		lineageTag: 90438f31-2fe7-4790-a605-3da4544839e0
		summarizeBy: none
		sourceColumn: Atributo
		sortByColumn: Orden_Leyenda

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: double
		lineageTag: da5cab40-fb37-4069-ba20-888e1b205d70
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Atributo - Leyenda'
		dataType: string
		lineageTag: 136129c5-8ed2-4f45-b425-4796c2b905c7
		summarizeBy: none
		sourceColumn: Atributo - Leyenda

		annotation SummarizationSetBy = Automatic

	column Orden_Leyenda
		dataType: double
		lineageTag: 3c3eacc2-ac43-4cfe-b82b-117ae1ea7440
		summarizeBy: sum
		sourceColumn: Orden_Leyenda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition BI_Aplicación-23dc3e5c-be57-4e8e-9c4e-5954961e74e4 = m
		mode: import
		queryGroup: 'Línea Base'
		source =
				let
				    URL = sharepointSource & Entorno & LBEnergia,
				    Origen = Excel.Workbook(Web.Contents(URL & "Líneas Base Energía v0.2 - Nuevos Presupuestos.xlsx"), null, true),
				    BI_Aplicación_Sheet = Origen{[Item="Bi_Maximo",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(BI_Aplicación_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Servicio TIC", type text}, {"Ámbito", type text}, {"Descripción Ámbito", type text}, {"Área", type text}, {"SubÁrea", type text}, {"Aplicación", type text}, {"Línea Base Real", type number}, {"Línea Base Proyectada", type number}, {"Línea Base Real Uts", type number}, {"Línea Base Proyectada Uts", type number}, {"Periodo", type date}, {"Tarifa", Int64.Type}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Tarifa"}),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Columnas quitadas",{{"Línea Base Real", type number}, {"Línea Base Proyectada", type number}, {"Presupuesto", type number}}),
				    #"Columna de anulación de dinamización" = Table.UnpivotOtherColumns(#"Tipo cambiado3", {"Servicio TIC", "Ámbito", "Descripción Ámbito", "Área", "SubÁrea", "Aplicación", "Periodo"}, "Atributo", "Valor"),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columna de anulación de dinamización",{{"Valor", type number}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado2","Línea Base Real Uts","Consumo Real Uts",Replacer.ReplaceText,{"Atributo"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Línea Base Real","Consumo Real",Replacer.ReplaceText,{"Atributo"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado1",{{"Valor", type number}}),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Tipo cambiado1", "Atributo", "Atributo - Copia"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna duplicada",{{"Atributo - Copia", "Atributo - Leyenda"}}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Columnas con nombre cambiado","Línea Base Objetivo","Fijo Correctivo",Replacer.ReplaceText,{"Atributo - Leyenda"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","Consumo Real","Gasto Correctivo Hipotético",Replacer.ReplaceText,{"Atributo - Leyenda"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado3","Gasto Correctivo Hipotético Uts","Gasto Correctivo Hipotético Horas",Replacer.ReplaceText,{"Atributo - Leyenda"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado5","Fijo Correctivo Uts","Fijo Correctivo Horas",Replacer.ReplaceText,{"Atributo - Leyenda"}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Valor reemplazado4", "Orden_Leyenda", each if [Atributo] = "Línea Base Objetivo" then 1 else if [Atributo] = "Línea Base Actual" then 2 else if [Atributo] = "Línea Base Máxima" then 3 else if [Atributo] = "Consumo Real" then 4 else if [Atributo] = "Línea Base Objetivo Uts" then 5 else if [Atributo] = "Línea Base Actual Uts" then 6 else if [Atributo] = "Línea Base Máxima Uts" then 7 else if [Atributo] = "Consumo Real Uts" then 8 else if [Atributo] = "Presupuesto" then 9 else null, type number)
				in
				    #"Columna condicional agregada"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

