table 'Parametros KGI24'
	excludeFromModelRefresh
	lineageTag: 25941647-e0b7-42d6-b7bb-c9c462fd381c

	column 'Número Máximo de Incidencias'
		dataType: int64
		formatString: 0
		lineageTag: 8148b378-58ad-4799-9fbc-2136b8c20015
		summarizeBy: sum
		sourceColumn: Número Máximo de Incidencias

		annotation SummarizationSetBy = Automatic

	column 'Cumplimiento Objetivo %'
		dataType: string
		lineageTag: d3a91233-9d0f-4cd3-8745-5c880fb53c20
		summarizeBy: none
		sourceColumn: Cumplimiento Objetivo %

		annotation SummarizationSetBy = Automatic

	column 'Peso %'
		dataType: int64
		formatString: 0
		lineageTag: e7fc9e9a-44a3-4719-8e00-02ee711531ce
		summarizeBy: sum
		sourceColumn: Peso %

		annotation SummarizationSetBy = Automatic

	column 'Puntos de KGI24'
		dataType: int64
		formatString: 0
		lineageTag: ccc2dde6-f8a9-46a2-be60-df2203779dd0
		summarizeBy: sum
		sourceColumn: Puntos de KGI24

		annotation SummarizationSetBy = Automatic

	column KGI
		dataType: string
		lineageTag: 0412fc96-153d-47e2-971f-c7b1fc6da0ae
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	partition 'Parametros KGI24-eb3c6bf0-c7db-4ea1-841f-0c7749dc2177' = m
		mode: import
		queryGroup: Parametros
		source =
				let
				    Source = Excel.Workbook(Web.Contents(globalPath & parametros & xlsx), null, true),
				    #"P_KGI24_Sheet" = Source{[Item="P_KGI24",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"P_KGI24_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Número Máximo de Incidencias", Int64.Type}, {"Cumplimiento Objetivo %", type text}, {"Peso %", Int64.Type}, {"Puntos de KGI24", Int64.Type}, {"KGI", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

