table 'PRO - Alegaciones del Servicio KGI21'
	lineageTag: ae64f3d1-d9f5-4076-b736-25da1b3e1f96

	column 'ID Alegación'
		dataType: string
		lineageTag: e479847d-aea9-427a-836f-7cf2a632b230
		summarizeBy: none
		sourceColumn: ID Alegación

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: d11998e8-6725-4d23-b093-b6a21e1959d6
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Entrada alegada'
		dataType: string
		lineageTag: e63be482-6174-47ea-bed6-8e1b89266df5
		summarizeBy: none
		sourceColumn: Entrada alegada

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: e16faf6d-ed0b-44c4-a9b1-f33a0dc83dd4
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: string
		lineageTag: fce9c454-3fd3-4f2d-b78a-1cca77466b2f
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		annotation SummarizationSetBy = Automatic

	column Clasificación
		dataType: string
		lineageTag: 368ba189-fc5d-4343-8c57-7d51dc7a208b
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: bfaca72d-de4d-492e-9307-279cbd7ee169
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: e699777d-41e6-4bb8-9612-141a3b78253e
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 8c8e334c-e748-40e1-8470-77a43dea308f
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: ea12fc2c-767e-46de-bb53-de6b9ec928f0
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1b5931bc-1c9e-4650-9cc4-cba8743e3374
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado - Copy

		variation Variación
			isDefault
			relationship: 68ab0335-55c9-4e98-99b8-c3cbaed208fe
			defaultHierarchy: LocalDateTable_7811f2c6-64e8-4715-b182-7151d8713b83.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Comentarios AE'
		dataType: string
		lineageTag: 212aeccb-69b0-471a-9b7f-d88ad23084c2
		summarizeBy: none
		sourceColumn: Comentarios AE

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI21-b36ba7f8-1741-4732-9cb2-a7f206f9b924' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Source = #"PRO - Alegaciones del Servicio",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([ANS] = "KGI 2-1"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

