table 'PRO - Incidencias con SLA_A'
	lineageTag: d75898ef-f91b-49cd-9c4b-3329b553b2fe

	column Número
		dataType: string
		lineageTag: beb87102-ea1d-4b75-ad46-b2871b1b59a0
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 115deef9-9b58-4675-a5ce-c572c51aaa0b
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Subcategoría
		dataType: string
		lineageTag: b1ed49c8-c3c3-4508-a781-213b8a759cfb
		summarizeBy: none
		sourceColumn: Subcategoría

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 1989c248-deec-4fe7-9636-7480b75af07a
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 7f8fa0d9-c09e-476a-8cd9-4be6d85b8aff
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: 618c746f-c13d-4acd-8351-8b96ded3f049
			defaultHierarchy: LocalDateTable_9956014c-20d7-4ffd-aad1-abaa1933034e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: b456705f-09ee-4307-baa6-65b8d1955419
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variation
			isDefault
			relationship: 3c6d2f1d-93d4-40c1-b28c-e59129435d72
			defaultHierarchy: LocalDateTable_9b37082e-1340-4c52-84e6-f843f0d5ab8c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 2e1083a3-579d-4f23-9f47-11bf3b632d36
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 512abfcc-e4a9-4ae7-8aa9-afdb7d386f31
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 39898335-e421-4216-a160-b09c7f36f0fd
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: 50d916eb-71f9-454b-9be4-1e63dc6b4feb
			defaultHierarchy: LocalDateTable_842716ec-50cb-4aa3-9510-61e1eea618e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 0a989e8c-32cb-4c55-a041-eb8f068d3d3d
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 26ea0f58-3d9f-47ad-9ec4-cd1acc0dc302
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: int64
		formatString: 0
		lineageTag: bd7ed532-a1d6-416c-85ec-094c68429431
		summarizeBy: sum
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 6554b8c2-a5fd-4bd5-adb4-b87686013573
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: cb73e0bf-b869-4344-8454-f76db128f141
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: int64
		lineageTag: 94193ae7-d0f2-4465-b47b-f77d7a63cdbe
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 8aaa4aa5-b865-485b-b2ee-809cb01ea9c9
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: d297e193-6487-499c-a015-d7628c851e70
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 4da478e6-f887-4384-95ef-24594e6fb361
			defaultHierarchy: LocalDateTable_a5eb309a-1108-4b1e-91da-b7dad908964d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 217da7a9-f16e-4558-bf47-0b1deed39c73
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 79abab5f-e32f-4b3a-ae1a-2df23a458d6a
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA_A-975bedd0-f3ff-45c0-b38f-d15ceeede48f' = m
		mode: import
		queryGroup: KGIs_II
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(globalPath & incidencias & xlsx), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Número", type text}, {"Breve descripción", type text}, {"Subcategoría", type text}, {"Prioridad", type text}, {"Abierto", type datetime}, {"Cerrado", type datetime}, {"Resuelto", type datetime}, {"Duración", Int64.Type}, {"Duración del negocio", Int64.Type}, {"Infringido", type logical}, {"Tiempo original de incumplimiento", type datetime}, {"Estado del incidente", type text}, {"Etapa", type text}, {"Código de resolución", type text}, {"Volver a abrir recuento", Int64.Type}, {"Tipo de Solución", type text}, {"Duración_1", Int64.Type}, {"Porcentaje de negocio trascurrido", Int64.Type}}),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Resuelto", "Fecha de resolución"}, {"Duración del negocio", "Duración real"}, {"Etapa", "Estado SLA"}, {"Estado del incidente", "Estado"}, {"Código de resolución", "Código de cierre"}, {"Volver a abrir recuento", "Reabierta"}, {"Tipo de Solución", "Tipo de solución"}, {"Duración_1", "Duración SLA"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = PRO - Incidencias con SLA_A

	annotation PBI_NavigationStepName = Navigation

