table 'PRO - Alegaciones del Servicio KGI13_23'
	lineageTag: 6f5ecdf8-cfb2-4bdf-bdbe-4679d7d9a71d

	column 'ID Alegación'
		dataType: string
		lineageTag: d8a4c152-e42e-4bc8-9701-c7499d87e6e2
		summarizeBy: none
		sourceColumn: ID Alegación

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: af7266b4-164e-4594-b5ac-d266821087e9
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Entrada alegada'
		dataType: string
		lineageTag: 97c2713b-b1ef-4a16-adb3-f8f170c64842
		summarizeBy: none
		sourceColumn: Entrada alegada

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: f417ce14-232c-4fd0-865f-99fb1a0d194a
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: string
		lineageTag: 9081d584-a0dc-4ce5-b3e4-6ee52173bed0
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		annotation SummarizationSetBy = Automatic

	column Clasificación
		dataType: string
		lineageTag: a4b75745-12f3-45e8-8934-ffce89b1214f
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 1ffec330-f020-4ede-9856-1692e7b49da4
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: 977cc968-23f8-428b-b70a-0d7c966712d9
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 96e6d82c-da70-44de-bdcf-9ff81c703995
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: bb39cffb-cb1c-4a6f-82b1-17afed0a1054
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c70983ab-51ce-411e-9273-644dd6b76ffe
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado - Copy

		variation Variación
			isDefault
			relationship: be6dc1ea-09f1-4042-bfcc-ae4dfd4b4a3f
			defaultHierarchy: LocalDateTable_b40fba2c-6eca-48ab-bb88-859632283595.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Comentarios AE'
		dataType: string
		lineageTag: 0099a984-91f1-446a-95ff-5262dd5b992e
		summarizeBy: none
		sourceColumn: Comentarios AE

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI13_23-5c9b7d15-13f1-4018-9be3-74f710745007' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Source = #"PRO - Alegaciones del Servicio",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([ANS] = "KGI 1-3" or [ANS] = "KGI 2-3"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

