table 'PRO - Incidencias con SLA_P_y_A_KGI21'
	lineageTag: 51fdb9a4-17f5-4bc5-867a-d6d9bc3b1bed

	column Número
		dataType: string
		lineageTag: 6b4f4373-bbc8-46a2-875c-8fa2a48d91f3
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: b1cd1a8e-d5a7-4c05-a622-9b3404a2a2ac
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: 741b88d0-2d8c-48b7-ba69-adca6287a93f
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 77321b7a-e3bd-4b2f-8dba-eed5a0e58d22
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 15d9a348-de41-4967-afd7-5f64241af95d
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: 1ec01b39-da8a-493e-84a6-1cba8e38daa4
			defaultHierarchy: LocalDateTable_09eca8cc-6f4a-43be-9d8b-1c6cc86bd723.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: e25b86eb-c874-466a-94a4-896d0d7e085a
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variación
			isDefault
			relationship: 4e13e8a4-1a04-4404-8e81-6ae3ae5e082b
			defaultHierarchy: LocalDateTable_82dc37d6-27e8-40ee-bb0c-00b72de728b5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 261b6abe-184b-46e1-bb58-0f141c2ad7b1
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 7d54bd2e-e42e-4dab-ae8a-d58ce737c6d5
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ae2dc9d8-f1a3-4d40-8730-ad2aeeda7f11
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: c9ad2a4c-c576-4bd7-b17f-fe6cd206d79e
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variación
			isDefault
			relationship: 910c8203-2e06-426f-9918-5082545b28b6
			defaultHierarchy: LocalDateTable_438363a8-b4b0-43dc-a101-568ee36e0528.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 4ac417e8-911c-406a-ae29-a0672a317c99
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 9ed432d6-e96d-4b3a-93ed-e2ad2a68de7a
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 00372868-ae30-410c-8deb-5bb777f44a3f
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: c12fa87a-f14c-4677-a240-2229881ed1a0
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: e7eecfb4-5ecb-40de-8ffa-433074cf3780
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: cd9ea12b-a7d7-48aa-90f8-f753cc81d9dd
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: e9199e66-ceee-43ce-b1bb-28528384b326
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3dda2f2b-85f9-410e-b4da-de5345b79071
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		variation Variación
			isDefault
			relationship: 8f2fec47-8b81-4ec5-9f80-c27d98f0657a
			defaultHierarchy: LocalDateTable_1a879c43-2580-40c9-8182-4f4f55099e6f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración excedida'
		dataType: string
		lineageTag: 22f74d16-1f6f-41b9-ab78-0123b3f073ca
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 14d21aed-40a7-482a-a26b-ce2327df0bce
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 025f23c8-afe4-447d-851b-f950aca7deee
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Infringidos Numérico' = IF('PRO - Incidencias con SLA_P_y_A_KGI21'[Infringido] = TRUE(),1,0)
		formatString: 0
		lineageTag: 32636d40-dd08-4407-b45a-77aeb2358448
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'No Infringidos Numerico' = IF('PRO - Incidencias con SLA_P_y_A_KGI21'[Infringido] = TRUE(),0,1)
		formatString: 0
		lineageTag: f44fd5b2-a955-4d5c-aec9-b6868c46aebd
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Duración D:HH:MM:SS' =
			
			VAR VDUR21_2 = 'PRO - Incidencias con SLA_P_y_A_KGI21'[Duración real]
			  RETURN INT
			    (VDUR21_2/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_2/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21_2/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21_2,60)),2)
		lineageTag: b351e9f3-4449-4cb4-844b-9b491684f647
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración_EX D:HH:MM:SS' =
			
			VAR VDUR21_EX_2 = 'PRO - Incidencias con SLA_P_y_A_KGI21'[Duración excedida]
			  RETURN INT
			    (VDUR21_EX_2/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_EX_2/3600,24)),2)&" HH"
		lineageTag: 9a7bba09-93a4-4736-a077-7979532323fd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA_P_y_A_KGI21'[Número])
		lineageTag: e72515a4-9f9c-4c4a-b725-d8f484e1a586
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 40cadc87-90e3-4b3b-818b-edae5f27639f
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 5b2f6412-0acb-4f37-a577-3b1757cf23fb
			defaultHierarchy: LocalDateTable_027dc1fc-f550-40ac-b182-5a5b8e172f3e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 40e03a3f-0c22-4680-a306-8dbb790ea7de
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA_P_y_A_KGI21-fff1a7e5-2741-461f-885c-fd6d97bfabdc' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Source = #"PRO - Incidencias con SLA_P_y_A",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"ANS_Alegado", "Estado_Alegación"}),
				    
				    //Une con tabla de alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"Número"}, #"PRO - Alegaciones del Servicio KGI21", {"ID"}, "PRO - Alegaciones del Servicio KGI21", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio KGI21" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio KGI21", {"ANS", "Estado"}, {"PRO - Alegaciones del Servicio KGI21.ANS", "PRO - Alegaciones del Servicio KGI21.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio KGI21",{{"PRO - Alegaciones del Servicio KGI21.ANS", "ANS_Alegado"}, {"PRO - Alegaciones del Servicio KGI21.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Infringido" si la alegación es aceptada
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1",each [Infringido],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI 2-1" then "FALSE" else [Infringido],Replacer.ReplaceValue,{"Infringido"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"Infringido", type logical}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = PRO - Incidencias con SLA_P_y_A_KGI21

	annotation PBI_NavigationStepName = Navigation

