table 'PRO - Incidencias con SLA_P_y_A_KGI22'
	lineageTag: ec635cfd-f13e-41cc-9124-faa1efb4dc74

	column Número
		dataType: string
		lineageTag: c4af3b58-0920-4ef2-b1e8-3bdb4490d6bf
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 9cd6c954-3d45-46f0-94b8-059e25f27cfe
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: ab38135e-e1ac-4c8b-8207-81098912c7ce
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: e680e88a-87d4-49a4-87e2-605b892d562a
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: ae9f8989-68b0-461d-86e3-097e7eb4a68a
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: 66b1ae4a-d1e1-4ab5-942c-8cc8f4184e3b
			defaultHierarchy: LocalDateTable_4c033515-6796-44ec-8d70-13811cd593a8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: 7e8dd912-543b-4a28-a2ef-811ff1ff15c7
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variación
			isDefault
			relationship: b9a7cf8e-7235-4951-9c20-60f513e4d612
			defaultHierarchy: LocalDateTable_9bfa5c72-b855-471a-8013-b507575ffc16.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 7af06df1-583f-476f-9aa1-ec30c568fde8
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 94f5f4a4-e3bf-4cac-a4f7-e19109e031d3
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 88f38f6e-b663-48e5-ab69-19efd078bb92
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1669e871-b558-4a6e-b6c3-7fda5761d565
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variación
			isDefault
			relationship: 37b4340a-8494-470a-b229-30650ba654ec
			defaultHierarchy: LocalDateTable_b2d335b0-ebaa-4914-ad1f-5153df347e2d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 854a74b5-f537-4a02-895a-482da42ea564
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: c86aa15a-9741-4b27-a676-d8f8c0e298ce
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 9b82ab4a-32d2-4ef6-85df-71529b2047c3
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 622a69d3-aac1-4f6b-bfac-160772d3052b
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 1e0f366f-4545-4132-b862-ec1291e9c000
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: e4fdd67f-d71f-47ba-ae77-036a4693c18f
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		lineageTag: 8de9b612-7a82-4ffd-bb92-9259aab61419
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 039462ff-d6e3-4c96-acbd-c983c171825f
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		variation Variación
			isDefault
			relationship: 6199b296-edf3-4a6c-bb84-4f36265ff38d
			defaultHierarchy: LocalDateTable_62a2f9d1-4ef5-4e54-9bec-a01c8ca8a062.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración excedida'
		dataType: string
		lineageTag: 272c16a5-c3da-4cc8-abd7-ba38072f87d4
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 5f32d8c3-efb5-42d4-b7f0-8d03f950b2b8
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 681e68d6-6419-44f9-a844-a964c039e40a
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column N_Reabierta = ```
			IF('PRO - Incidencias con SLA_P_y_A_KGI22'[Reabierta] = True,1) 
			```
		formatString: 0
		lineageTag: f3ef4ce8-83d8-4641-a85a-d7fd8b93a84c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 892d1fcb-9892-4b60-9a3d-dc73f5be3e44
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 5d2fa8f7-8655-44d8-b559-baa8750ceb95
			defaultHierarchy: LocalDateTable_bfec634e-dbb7-419b-a69b-3a2b25b322e9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: ae26c2ec-cfb8-4891-b40c-f55616347a73
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA_P_y_A_KGI22-cfad9582-c26a-47e0-a884-c82df30fa290' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Source = #"PRO - Incidencias con SLA_P_y_A",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"ANS_Alegado", "Estado_Alegación"}),
				    
				    //Une con tabla de alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"Número"}, #"PRO - Alegaciones del Servicio KGI22", {"ID"}, "PRO - Alegaciones del Servicio KGI22", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio KGI22" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio KGI22", {"ANS", "Estado"}, {"PRO - Alegaciones del Servicio KGI22.ANS", "PRO - Alegaciones del Servicio KGI22.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio KGI22",{{"PRO - Alegaciones del Servicio KGI22.ANS", "ANS_Alegado"}, {"PRO - Alegaciones del Servicio KGI22.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Infringido" si la alegación es aceptada
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1",each [Reabierta],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI 2-2" then "FALSE" else [Reabierta],Replacer.ReplaceValue,{"Reabierta"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"Reabierta", type logical}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = PRO - Incidencias con SLA_P_y_A_KGI22

	annotation PBI_NavigationStepName = Navigation

