table 'PRO - Jira - Defectos con SLA - UAT - Detalle'
	lineageTag: 8e8892f6-e580-4b7d-ac84-f64e0754453a

	column Components
		dataType: string
		lineageTag: 7391f3fe-8abd-4413-8668-3083088d0efc
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 0d362a44-94eb-476e-955e-8a2398def029
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: 912fa298-e6b1-41db-9600-cceda5b29209
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 6bee3316-ea34-4730-8faf-f656b647e4e0
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 71727302-2a25-4f59-98ba-0ea9033cfcda
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 72b4bfa6-0320-45f1-b9b5-0d0672b77fb1
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: d6753e74-80b4-4f3c-b4bc-78bce2a22dab
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 928bb5be-789e-4248-9ed9-023bded38db5
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: b31e40c8-cce3-4022-8416-3b72beb7c7ee
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 4724cb50-bf8e-497b-996f-b0cf6095a337
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 8827b11b-a208-4e1b-bf33-43ddfd5fae50
			defaultHierarchy: LocalDateTable_a7e540f8-d8f1-43a9-baf5-671c3905429b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 2e45b7b7-229f-4fa6-af77-0d34889ef9f0
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: ae24b3ec-eef7-4370-b2bc-f53cfad50c04
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: 6d34ac26-dad8-40a9-afb5-31bfc77a2f33
			defaultHierarchy: LocalDateTable_ca0bbf17-a230-456e-9ce5-8e984b1490b6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 2fa186c8-7543-4e23-b736-c021e460d63e
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Value (Bugs)'
		dataType: string
		lineageTag: 5865b4d9-7ee5-41a3-a893-dfd5b6351201
		summarizeBy: none
		sourceColumn: Value (Bugs)

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Status'
		dataType: string
		lineageTag: 9cd32927-6beb-4405-88ee-1049cdf08d98
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: b8681125-4fb4-45f5-b606-89268e7e5c3f
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved

		variation Variation
			isDefault
			relationship: f15fba8a-f275-4288-a9b8-a94996d4e4db
			defaultHierarchy: LocalDateTable_9c8c4320-96ca-4704-b8af-f5f3d52e3c80.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status'
		dataType: string
		lineageTag: a4851491-b909-40ee-875e-c47c320d9749
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba'
		dataType: string
		lineageTag: cc812af8-b1ad-473c-b007-c9a7c4fbe77d
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Pruebas con SLA.Priority'
		dataType: string
		lineageTag: 921be4d7-33b5-4e21-8c35-6f809f681b20
		summarizeBy: none
		sourceColumn: PRO - Jira - Pruebas con SLA.Priority

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Pruebas con SLA.Status'
		dataType: string
		lineageTag: 8d2272e5-eaa1-4fc3-a683-1b8f7ced39e7
		summarizeBy: none
		sourceColumn: PRO - Jira - Pruebas con SLA.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5b99e09b-b26a-4945-8176-001c61f0d2f8
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved - Copy

		variation Variation
			isDefault
			relationship: c9ee0f53-4958-4eb9-89ee-85921411fc61
			defaultHierarchy: LocalDateTable_563af6ac-887b-46e1-a013-31f56f730335.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: 150295fd-fcfa-470f-ae9d-96663ee860fa
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Defectos con SLA - UAT - Detalle-12eab267-1ac7-4501-b75a-7ffaf3903f0b' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = #"PRO - Jira - Defectos con SLA",
				
				    #"Filtered Rows" = Table.SelectRows(Source, each Text.Contains([#"PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba"], "UAT")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [Estado_Alegación] <> "1 - Aprobada")
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

