table 'PRO - Estimaciones con SLA'
	lineageTag: c2acd830-c1cb-40fa-8e85-ac2cafbf1ddb

	column Creado
		dataType: dateTime
		formatString: General Date
		lineageTag: 7caf2d33-41a8-4b21-9734-2685910c7ec6
		summarizeBy: none
		sourceColumn: Creado

		variation Variation
			isDefault
			relationship: c0611801-5c18-4987-8879-fd5ec90bc80e
			defaultHierarchy: LocalDateTable_4154b662-4c11-4acc-a8d5-92bda6f30c47.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 4ee2ff45-ebfa-4e13-a7b1-c5b722c528c5
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio'
		dataType: string
		lineageTag: e14b50fc-65f0-444d-b4fe-db002123c6de
		summarizeBy: none
		sourceColumn: Aplicación de Negocio

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 0bb18aad-7530-449c-b0d3-d2fad9a52817
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Tarea
		dataType: string
		lineageTag: 1394bcc9-0763-482b-abcf-e717b38f5803
		summarizeBy: none
		sourceColumn: Tarea

		annotation SummarizationSetBy = Automatic

	column Etapa
		dataType: string
		lineageTag: e7cbc41f-93ba-49ad-b16e-31ad85ebe088
		summarizeBy: none
		sourceColumn: Etapa

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de negocio restante'
		dataType: int64
		formatString: 0
		lineageTag: e826f3cf-5e62-4c4e-ba93-89b24301c131
		summarizeBy: sum
		sourceColumn: Tiempo de negocio restante

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: int64
		formatString: 0
		lineageTag: e4c3cebb-8aed-4142-b2cb-766586722857
		summarizeBy: sum
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 845f344b-b77b-4403-a7b3-7cd0957f1c58
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Hora de inicio'
		dataType: dateTime
		formatString: General Date
		lineageTag: eac37a39-9db8-4dae-a8f8-ff5984d551dd
		summarizeBy: none
		sourceColumn: Hora de inicio

		variation Variation
			isDefault
			relationship: 6ec0d742-c0d5-4084-a395-f93e42d2f643
			defaultHierarchy: LocalDateTable_6680e904-7959-4182-97d6-20c73bd3c6cc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de pausa'
		dataType: string
		lineageTag: a5f07a74-9823-49e8-b3a4-dcab46bbcb3e
		summarizeBy: none
		sourceColumn: Tiempo de pausa

		annotation SummarizationSetBy = Automatic

	column 'Hora de finalización'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5c06bd97-e778-4125-912c-fb98aaff239f
		summarizeBy: none
		sourceColumn: Hora de finalización

		variation Variation
			isDefault
			relationship: ae9a7f90-d090-4d82-acf4-55ce3d95b525
			defaultHierarchy: LocalDateTable_4993cfe9-4249-4821-9e60-ca1e53d9538c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: e8d2cec7-cdb2-4028-b4ff-7e8a35691a63
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Hora de finalización - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a719521e-1e6c-411e-9b57-b5434454423e
		summarizeBy: none
		sourceColumn: Hora de finalización - Copy

		variation Variation
			isDefault
			relationship: 65367430-15c7-4d2e-96e0-d485ed918178
			defaultHierarchy: LocalDateTable_41e01205-b8dc-49df-ae85-bd7a2fee388d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2d06f70e-be09-4e32-b756-777767975eac
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3e32c66e-034b-4190-b07a-5a6b61b66c72
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: f7a3fbaf-03d1-4627-91c1-af5858cf03da
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Hora de infracción'
		dataType: dateTime
		formatString: General Date
		lineageTag: ac0bde18-b89e-4d26-8729-fad894b6c401
		summarizeBy: none
		sourceColumn: Hora de infracción

		variation Variation
			isDefault
			relationship: a4af2088-38f3-4cd1-8c80-eced946c6a1e
			defaultHierarchy: LocalDateTable_7bf73a75-129b-41e3-95a6-8e72ebf7240c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Duración D:HH:MM:SS' =
			
			VAR VDUR13 = 'PRO - Estimaciones con SLA'[Duración del negocio]
			  RETURN INT
			    (VDUR13/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR13/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR13/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR13,60)),2)
		lineageTag: 981ae4e8-9a11-4d4a-9a10-159f561b9a2b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: 58e6d568-654f-4787-ba7e-fcde9bd9a0c7
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Duración excedida'
		dataType: string
		lineageTag: 0a39a204-67d4-4e24-83b9-941150a60cbe
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column 'Duración_EX D:HH:MM:SS' =
			
			VAR VDUR13_EX = 'PRO - Estimaciones con SLA'[Duración excedida]
			  RETURN INT
			    (VDUR13_EX/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR13_EX/3600,24)),2)&" HH"
		lineageTag: 3d2bc8cc-c7ad-4348-9337-a480b373bec1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Estimaciones con SLA'[Tarea])
		lineageTag: 3847ef11-1fec-41fe-b58f-c806c944ab94
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Estimaciones con SLA-5a40b48a-1e50-4be9-880e-a8884b495a6d' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    URL = sharepointSource & Entorno & sharepointSource2 & estimaciones & xlsx,
				    Origen = Excel.Workbook(Web.Contents(URL), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Creado", type datetime}, {"Número", type text}, {"Aplicación de Negocio", type text}, {"Prioridad", type text}, {"Tarea", type text}, {"Etapa", type text}, {"Tiempo de negocio restante", Int64.Type}, {"Duración del negocio", Int64.Type}, {"Porcentaje de negocio trascurrido", Percentage.Type}, {"Hora de inicio", type datetime}, {"Tiempo de pausa", type any}, {"Hora de finalización", type datetime}, {"Grupo de asignación", type text}, {"Infringido", type logical}, {"Hora de infracción", type datetime}, {"Duración", Int64.Type}}),
				    
				    //Genera Columna de Cerrado
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Hora de finalización", "Hora de finalización - Copy"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Duplicated Column",{{"Hora de finalización - Copy", type date}}),
				    #"Inserted Start of Month" = Table.AddColumn(#"Changed Type1", "Start of Month", each Date.StartOfMonth([#"Hora de finalización - Copy"]), type date),
				   
				   //Homologa las prioridades
				    #"AllReplace" = [#"1 - Crítica" = "Alta", #"2 - Alta" = "Alta", #"3 - Moderada" = "Media",#"4 - Baja" = "Baja",#"5 - Muy Baja" = "Baja"],    
				    #"Replaced Value" = Table.TransformColumns(#"Inserted Start of Month",{{"Prioridad",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    
				    //Pone "Nuevo Servicio" sobre Estimaciones de Demandas que no son Evolutivos
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",         "",             "Nuevo Servicio",Replacer.ReplaceValue,{"Aplicación de Negocio"}),
				
				    //Une con las alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value1", {"Tarea"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"Estado"}, {"PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Infringido" si la alegación es aceptada
				    #"Replaced Value6" = Table.ReplaceValue(#"Renamed Columns",each [Infringido],each if [Estado_Alegación] = "1 - Aprobada" then "FALSE" else [Infringido],Replacer.ReplaceValue,{"Infringido"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value6",{{"Infringido", type logical}}),
				
				    //Elimina los duplicados, y deja el último SLA finalizado
				    #"Sorted Rows" = Table.Buffer(Table.Sort(#"Changed Type2",{{"Hora de finalización - Copy", Order.Descending}})),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"Tarea"}),
				    
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Duplicates",{{"Duración", "Duración SLA"}}),
				
				    //Nuevo campo de Duración Excedida, respecto a SLA
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "Duración excedida", 
				    each if ([Duración del negocio]-[Duración SLA])<0 then 0 else 
				    ([Duración del negocio]-[Duración SLA])),
				    #"Divided Column" = Table.TransformColumns(#"Added Custom", {{"Porcentaje de negocio trascurrido", each _ / 100, Percentage.Type}})
				in
				    #"Divided Column"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

