table 'PRO - Jira - Defectos con SLA - FUN - Detalle'
	lineageTag: 1c2a2dac-ab78-4cdd-a1d7-ea9eba73f5f9

	column Components
		dataType: string
		lineageTag: be870516-f44c-4c1c-8058-963fdfecb88e
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 138e49e3-6cba-47f7-bf01-c00a28bc83de
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: e9e9c6e4-ae50-47ca-8892-5998db33384a
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 41b40728-6afe-4855-8bea-5787c921a0d4
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 43452c3b-7459-439c-8d1a-73e0962bfe8a
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 5b966c0d-eded-4399-a3fb-38b8d0490e1c
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 8256ef46-8efd-47ec-984d-6fd2d9668e56
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 52f1b89a-be85-467f-83b7-e13d917ca8b7
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 7b47e691-c59f-4200-a29e-9235697ce288
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 71bf0783-6af7-42b8-b6d7-4e7eb50932de
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: b606a951-db1d-4745-b6f5-d4b9b7d9c7e3
			defaultHierarchy: LocalDateTable_5ee0558c-c30a-4c85-9729-47e3b26a8b16.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 5c49a771-e706-4d4f-8039-5a34c309f4b6
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: a8269108-aca3-4800-a793-298bbbde2f78
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: 0a63252e-5978-41ab-929e-b236bcdc81e5
			defaultHierarchy: LocalDateTable_e25738bf-0ac5-4f30-b5c5-bb738d3cb418.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 77fdc30b-a57a-4b38-a93e-de2939174a3d
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Value (Bugs)'
		dataType: string
		lineageTag: 0f8d6b8d-80ad-4b9e-8904-224541cf2f63
		summarizeBy: none
		sourceColumn: Value (Bugs)

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Status'
		dataType: string
		lineageTag: 4d3df34a-ee94-4b1a-b61c-cc9189a2aecc
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: d8b95ede-f4c0-40ad-8c70-9266c2abda00
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved

		variation Variation
			isDefault
			relationship: 03e60a0b-c21a-44b4-ae19-cc5717f706eb
			defaultHierarchy: LocalDateTable_2edee785-ced3-4d09-b834-7a848acb911d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status'
		dataType: string
		lineageTag: 6756c916-2f00-486e-9b45-9c49e81d1baf
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba'
		dataType: string
		lineageTag: ce1eb7a3-776d-42a3-a91f-3f7265300230
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Pruebas con SLA.Priority'
		dataType: string
		lineageTag: fb1e93ee-255a-4ac3-8729-692c49bdb12d
		summarizeBy: none
		sourceColumn: PRO - Jira - Pruebas con SLA.Priority

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Pruebas con SLA.Status'
		dataType: string
		lineageTag: 90aa269f-726c-4e09-a3cf-50978926e9fe
		summarizeBy: none
		sourceColumn: PRO - Jira - Pruebas con SLA.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 16a15db0-cf68-44c9-8879-f86378eceae9
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved - Copy

		variation Variation
			isDefault
			relationship: d4919915-bfec-4ced-97a1-3836acf81f1e
			defaultHierarchy: LocalDateTable_e500c7ea-84d5-4ef1-ac31-bed1cb2d26ae.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: 05da8224-94f8-4a86-8f31-b4c3f8b632bd
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Defectos con SLA - FUN - Detalle-fdad26b4-5d9f-4d4d-b271-fd433890918a' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = #"PRO - Jira - Defectos con SLA",
				
				    #"Filtered Rows" = Table.SelectRows(Source, each ([#"PRO - Jira - Historias y Ejecuciones.Status"] = "Done") and ([#"PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba"] = "Pruebas Funcionales")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [Estado_Alegación] <> "1 - Aprobada")
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

