table 'PRO - Planificaciones PRJ y ENH con SLA'
	lineageTag: b2ddb5d1-026d-4a87-9625-8f87e8434b30

	column Demanda
		dataType: string
		lineageTag: 1f11b2c5-1209-4d7b-807e-9ccc4129ec8f
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 39da6fb8-d85a-4762-b2d3-5e2adbc37cfc
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 5e96ee03-5729-4cf9-a0e6-b37a702561ae
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5c4799fb-5077-448c-bbdb-4b94de626de3
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variation
			isDefault
			relationship: fd4b799a-e636-4850-9165-5103041c1f6e
			defaultHierarchy: LocalDateTable_cbe44c7a-b1cf-4d00-a27e-e5063836a862.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 354e7490-2f96-47ca-b26c-6108452e9323
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variation
			isDefault
			relationship: e83269ba-b99f-4ef6-ad9d-87bc25520034
			defaultHierarchy: LocalDateTable_f70a1ef5-4887-4557-b5ab-13907149e605.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 1673b676-1aa7-4f9f-9ed0-4bf9cac396c1
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: 1bfa7178-e295-4601-b85b-0f484202539f
		summarizeBy: none
		sourceColumn: Inicio

		variation Variation
			isDefault
			relationship: 2fc0c468-7c8c-4a4a-8d0c-cfdca082f41f
			defaultHierarchy: LocalDateTable_3b7dc721-8d9d-4a09-9c14-c575fb4024ba.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: 23e92412-1718-4613-97a8-57ea12e52b58
		summarizeBy: none
		sourceColumn: Fin

		variation Variation
			isDefault
			relationship: ae7d02c7-d061-4a82-b922-a24f4616d1cc
			defaultHierarchy: LocalDateTable_e52f7151-aa87-4747-a6fb-0c6eebaf8376.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4e0fd8f0-4a76-4dd5-acb9-100595643437
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: ec56ba0a-0bdc-48be-9b65-11f245a7f2fe
			defaultHierarchy: LocalDateTable_c2eadd93-34ab-4f0b-8e7d-d7f09e29571b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: c25758da-c857-4eca-8a67-c4da6e4f90f0
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: a8b0b940-9db3-4cdb-8e34-9cc0cdda63cf
			defaultHierarchy: LocalDateTable_909091cb-d835-454e-a1a9-e5c4cc0f6e39.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: f9a1911a-7a79-4a94-8dc6-b9bbf756ff25
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: a28eed6b-dc50-4917-a915-89a3a740b231
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 5bf09f5f-866b-439f-8c3b-ae44f1624d9b
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4e94a178-cb54-4a12-b431-e680a4bca3f6
		summarizeBy: none
		sourceColumn: Fecha fin real - Copy

		variation Variation
			isDefault
			relationship: 607894f4-8844-4c45-9eee-454ef429b4c6
			defaultHierarchy: LocalDateTable_42c6b304-4b9d-43fd-9680-f3686fcd5203.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: cd59f284-0889-4da2-bdaa-7deff78cc9bc
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: fd37e5ae-7863-488b-89c7-3de390fae0af
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Duración Planificada LB'
		dataType: double
		lineageTag: 8e98b102-770f-46e3-9e44-f9da8d4734ed
		summarizeBy: sum
		sourceColumn: Duración Planificada LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real LB'
		dataType: double
		lineageTag: 4478c188-d860-4fee-ae92-d4aaf0e7dcff
		summarizeBy: sum
		sourceColumn: Duración real LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa de desviación'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 714faaab-eef8-4ecc-b737-32ae6810cca7
		summarizeBy: sum
		sourceColumn: Tasa de desviación

		annotation SummarizationSetBy = Automatic

	column 'Estimación incumplida'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f99d10bf-2b6a-4b68-89ed-771700296566
		summarizeBy: none
		sourceColumn: Estimación incumplida

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: c6fdb75f-a7d6-4b5a-8675-633ae42abe90
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 2a3056e4-dc52-4b3b-b7ac-1c1100909396
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: 31c73999-8915-433e-9fb8-1a79ce97bda6
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Planificaciones PRJ y ENH con SLA'[Número])
		lineageTag: 4999b032-61fc-4c59-93a9-9e8508cb6d32
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Fecha límite planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0f414b02-6631-4f82-90d5-ca1aac491afb
		summarizeBy: none
		sourceColumn: Fecha límite planificada

		variation Variación
			isDefault
			relationship: eb2d71f0-b36b-49eb-afbc-c175dddaad33
			defaultHierarchy: LocalDateTable_6aacc48b-f329-45cb-af6c-e9e13ff135fd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones PRJ y ENH con SLA-c4488ef7-b8a5-455a-a73c-cefca85f53ea' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    URL = sharepointSource & Entorno & sharepointSource2 & PRJ & xlsx,
				    Origen = Excel.Workbook(Web.Contents(URL), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Promoted Headers",{{"Fecha de finalización planificada", "Fecha límite planificada"}}),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Demanda", type text}, {"Número", type text}, {"Tipo de Proyecto", type text}, {"Prioridad", type text}, {"Jefe de proyecto (Project Manager)", type text}, {"Aplicación de Negocio ", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha límite planificada", type datetime}, {"Nombre", type text}, {"Inicio", type datetime}, {"Fin", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Nombre de proyecto", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Nombre de proyecto", "Nombre de PRJ o MEJ"}}),
				
				    //Filtro por solo proyectos y mejoras de aplicaciones a cargo del proveedor iAR
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([#"Aplicación de Negocio "] 
				    = "MAXIMO: MAXIMO")    
				    and ([Tipo de Proyecto] <> "Mantenimiento de Aplicaciones")),
				
				    //Une tablas de Mejoras y Proyectos de Mantenimiento de Aplicaciones
				    #"Appended Query" = Table.Combine({#"Filtered Rows", #"PRO - Planificaciones ENH"}),
				    #"Appended Query1" = Table.Combine({#"Appended Query", #"PRO - Planificaciones MA"}),
				
				    //Homologa las prioridades
				    #"AllReplace" = [#"1 - Crítica" = "Alta", #"2 - Alta" = "Alta", #"3 - Moderada" = "Media",#"4 - Baja" = "Baja",#"5 - Muy Baja" = "Baja"],    
				    #"Replaced Value" = Table.TransformColumns( #"Appended Query1",{{"Prioridad",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    
				    //Nueva columna "Fecha (1er día de mes)"
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced Value", "Fecha fin real", "Fecha fin real - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Fecha fin real - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Fecha fin real - Copy", Date.StartOfMonth, type date}}),
				
				    //Nueva columna "Duración planificada de línea base"    
				    #"Added Custom1" = Table.AddColumn(#"Calculated Start of Month", "Duración Planificada LB", each [Fin]-[Inicio]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Duración Planificada LB", type number}}),
				
				   //Nueva columna "Duración real para cálculo con planificación de línea base" 
				    #"Added Custom2" = Table.AddColumn(#"Changed Type1", "Duración real LB", 
				    each if [Nombre] <> "" then ([Fecha fin real]-[Fecha de inicio real]) else ""),
				    
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom2",{{"Duración real LB", type number}}),
				
				    //Nueva columna "Tasa de desviación"
				    #"Added Custom3" = Table.AddColumn(#"Changed Type2", "Tasa de desviación",
				    each if [Nombre] = "" then (([Duración real]-[Duración planificada])/[Duración planificada]) 
				                          else (([Duración real LB]-[Duración Planificada LB])/[Duración Planificada LB])),
				 
				    //Quita los proyectos y mejoras que tienen por error duración real o planificada = 0
				    #"Filtered Rows1" = Table.SelectRows(#"Added Custom3", each ([Duración real] <> 0) and ([Duración planificada] <> 0)),
				
				    //Columna "Estimación incumplida"
				    #"Added Custom4" = Table.AddColumn(#"Filtered Rows1", "Estimación incumplida",
				    each if [Prioridad]="Alta" and [Tasa de desviación]>0 then "TRUE" else
				         if [Prioridad]="Media" and [Tasa de desviación]>0.05 then "TRUE" else
				         if [Prioridad]="Baja" and [Tasa de desviación]>0.10 then "TRUE" else "FALSE"),
				
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom4",{{"Tasa de desviación", Percentage.Type}}),
				
				    //Une con las alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type3", {"Número"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"Estado"}, {"PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Estimación incumplida" si la alegación es aceptada
				    #"Replaced Value5" = Table.ReplaceValue(#"Renamed Columns1",each [Estimación incumplida],each if [Estado_Alegación] = "1 - Aprobada" then "FALSE" else [Estimación incumplida],Replacer.ReplaceValue,{"Estimación incumplida"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value5",{{"Estimación incumplida", type logical}})
				in
				    #"Changed Type4"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

