table 'PRO - Jira - Pruebas con SLA'
	lineageTag: c7fcb0c7-91c7-43ff-b70e-329faf0674e8

	column Components
		dataType: string
		lineageTag: d8d7d12b-5c9b-4906-acf6-ee774179c23c
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 3674e719-d1c1-4712-9dc0-34ebe10ccebf
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: d8026928-1865-43de-aff1-0169b7869d76
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 18ad6498-9c85-4801-9a54-2bf25aee417a
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: affda8f8-32a5-42e7-adea-71825ebbe467
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: f4bf6bbe-577e-4aa4-b632-0248279cb5c9
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 157e6578-1ae0-494a-9968-da9e5494ccde
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 2acda0fc-7978-4b37-a309-1aaf3a7e5ff6
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 6c071bd7-872f-4843-b341-5f39d591f619
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 6f92c352-1fc5-4cd9-91f3-065ecded7260
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 60ef18b5-4367-4c33-ae94-7e7b87933a37
			defaultHierarchy: LocalDateTable_da3f77a5-cec4-4970-a42b-aa5096e5066e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 029145f8-a88e-4ccb-b7f9-bb0cb71d765c
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column 'Tipo de prueba'
		dataType: string
		lineageTag: 96f05663-9185-447b-862d-11b7c02ade33
		summarizeBy: none
		sourceColumn: Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: 00a8290f-e793-47e5-af90-9a43b49538f8
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: d4ed8bca-b1c1-4ee3-a90c-fa8bc12accb8
			defaultHierarchy: LocalDateTable_120e3cc7-e3f3-4a7e-bde6-112eb07f9899.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: fb99d90a-feba-4be7-870f-da23cb6a4e30
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Value (Tests)'
		dataType: string
		lineageTag: 4c40ee96-5278-49ef-80f0-589353407221
		summarizeBy: none
		sourceColumn: Value (Tests)

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias.Key'
		dataType: string
		lineageTag: bc637d93-bdc8-4f7a-af01-5de62a48f126
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias.Key

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias.Status'
		dataType: string
		lineageTag: eb3f737a-853a-4de9-b118-568695309836
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0e5abfa4-c7bd-4f16-802c-46d175bb2afb
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias.Resolved

		variation Variation
			isDefault
			relationship: 901a5652-e3df-424a-8eb5-9998c09892e6
			defaultHierarchy: LocalDateTable_a3fd6922-efff-4d7d-afbe-231406991c43.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5e8ef550-2300-4156-ae6c-645b65245fe6
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias.Resolved - Copy

		variation Variation
			isDefault
			relationship: c4b8057b-f194-4faf-b869-b4965c3d6361
			defaultHierarchy: LocalDateTable_6ce178c6-48b6-416d-8eb5-46d694d4e2f2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column UAT = IF ( CONTAINSSTRING('PRO - Jira - Pruebas con SLA'[Tipo de prueba],"UAT"),1,0)
		formatString: 0
		lineageTag: 7a28aea0-ad65-46c5-b312-d11660ad162e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column FUN = IF ( CONTAINSSTRING('PRO - Jira - Pruebas con SLA'[Tipo de prueba],"Funcional"),1,0)
		formatString: 0
		lineageTag: d41d3e70-b399-42c7-8ddb-d1693b744fd2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Pruebas con SLA-61f24a68-5eb8-43f1-8370-d881916bc54a' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    URL = sharepointSource & Entorno & sharepointSource2 & entregables & xlsx,
				    Origen = Excel.Workbook(Web.Contents(URL), null, true),
				    Tests_Sheet = Origen{[Item="Tests",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Tests_Sheet, [PromoteAllScalars=true]),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Components", type text}, {"Project", type text}, {"Issue Type", type text}, {"Key", type text}, {"Summary", type text}, {"Assignee", type text}, {"Reporter", type text}, {"Priority", type text}, {"Status", type text}, {"Created", type datetime}, {"Linked Issues", type text}, {"Sub-tasks", type text}, {"Tipo de prueba", type text}, {"Resolved", type datetime}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true),
				
				    //Separa los Linked Issues de cada Test
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Filtered Rows", "Linked Issues", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {
				        "Linked Issues.1",
				        "Linked Issues.2",
				        "Linked Issues.3",
				        "Linked Issues.4",
				        "Linked Issues.5",        
				        "Linked Issues.6",        
				        "Linked Issues.7",        
				        "Linked Issues.8",       
				        "Linked Issues.9",
				        "Linked Issues.10"        
				        }),
				
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{
				        {"Linked Issues.1", type text}, 
				        {"Linked Issues.2", type text}, 
				        {"Linked Issues.3", type text},
				        {"Linked Issues.4", type text},
				        {"Linked Issues.5", type text},
				        {"Linked Issues.6", type text},
				        {"Linked Issues.7", type text},
				        {"Linked Issues.8", type text},
				        {"Linked Issues.9", type text},
				        {"Linked Issues.10", type text}
				        }),
				
				    //Transforma la separación en tipo lista (Cada Test Link con el Test al cual está relacionado)
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type1", {"Components","Project", "Issue Type", "Key", "Summary", "Assignee", "Reporter", "Priority", "Status", "Created", "Sub-tasks", "Tipo de prueba", "Resolved"}, "Attribute", "Value (Tests)"),
				
				    //Une con las Historias
				    #"Merged Queries" = Table.NestedJoin(#"Unpivoted Columns", {"Value (Tests)"}, #"PRO - Jira - Historias", {"Key"}, "PRO - Jira - Historias", JoinKind.LeftOuter),
				    #"Expanded PRO - Jira - Historias" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Jira - Historias", {"Key", "Status", "Resolved"}, {"PRO - Jira - Historias.Key", "PRO - Jira - Historias.Status", "PRO - Jira - Historias.Resolved"}),
				    
				
				    //Nueva columna "Fecha Resolved" para relacionar a Fechas del CdM
				    #"Duplicated Column" = Table.DuplicateColumn(#"Expanded PRO - Jira - Historias", "PRO - Jira - Historias.Resolved", "PRO - Jira - Historias.Resolved - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"PRO - Jira - Historias.Resolved - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"PRO - Jira - Historias.Resolved - Copy", Date.StartOfMonth, type date}}),
				
				    //Homologa las prioridades
				    #"AllReplace" = [#"Highest" = "Grave", #"High" = "Grave", #"Medium" = "Media",#"Low" = "Leve",#"Lowest" = "Leve"],    
				    #"Replaced Value" = Table.TransformColumns(#"Calculated Start of Month",{{"Priority",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value", each true)
				
				in
				    #"Filtered Rows1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

