table 'PRO - Incidencias con SLA - Incumplidas'
	lineageTag: 769c2ff0-c7d6-41a8-9986-af04697dbff2

	column Prioridad
		dataType: string
		lineageTag: 4dd87cf4-9200-4719-8c13-cda55138762c
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado_1er_día_mes
		dataType: dateTime
		formatString: Long Date
		lineageTag: a850a0bf-07fc-41a5-b6fc-7d9981406a1a
		summarizeBy: none
		sourceColumn: Cerrado_1er_día_mes

		variation Variation
			isDefault
			relationship: 36d2c153-e33c-4697-ada9-6d52ab03e1ce
			defaultHierarchy: LocalDateTable_566d98f7-5bd5-4e47-986e-7c4acde88b8e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5d7b7534-9f32-46de-ac2b-b4abcf721842
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'INCs Incumplidas'
		dataType: double
		lineageTag: ed7d0d3e-7318-4412-833e-398d21d46db8
		summarizeBy: sum
		sourceColumn: INCs Incumplidas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'PRO - Incidencias con SLA - Incumplidas-8aaac431-853f-45ba-8fae-3cf1017a131b' = m
		mode: import
		queryGroup: KGIs_II
		source =
				let
				    Source = #"PRO - Incidencias con SLA_P_y_A",
				
				    #"Grouped Rows" = Table.Group(Source, {"Prioridad", "Infringido", "Cerrado - Copy"}, {{"Count", each Table.RowCount(_), type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Grouped Rows", each ([Infringido] = true)),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"Cerrado - Copy", "Cerrado_1er_día_mes"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Prioridad", "Cerrado_1er_día_mes", "Infringido", "Count"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"Count", "INCs Incumplidas"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

