table 'PRO - Estimaciones con SLA - Incumplidas'
	lineageTag: 6b71ca15-477d-45a0-a7a8-df384b4d5cd3

	column Prioridad
		dataType: string
		lineageTag: f89ac5b5-fc0b-4e30-9aae-30566377fffb
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c3fbcfa8-7b3f-4edd-b37c-137361a12616
		summarizeBy: none
		sourceColumn: Start of Month

		variation Variation
			isDefault
			relationship: f17eae2f-8964-4045-9588-52255c5fad8c
			defaultHierarchy: LocalDateTable_6b2e9b59-6630-4ec4-8cb0-2dc994965a42.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 07e4414c-d508-44d8-ba22-0f1f6dac5549
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: double
		lineageTag: 5e394538-b4f0-4a2b-8736-db39cc81642a
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'PRO - Estimaciones con SLA - Incumplidas-75432853-b8a0-4e25-8f03-2fac6963c72f' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = #"PRO - Estimaciones con SLA",
				
				    #"Grouped Rows" = Table.Group(Source, {"Prioridad", "Start of Month", "Infringido"}, {{"Count", each Table.RowCount(_), type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Grouped Rows", each ([Infringido] <> false))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

