table 'PRO - Alegaciones del Servicio KGI22'
	lineageTag: 3bf93faa-dbf2-4945-961c-7188f8faa3f8

	column 'ID Alegación'
		dataType: string
		lineageTag: 46d2f1b4-1c6c-430c-aefc-d53a86ac3c1b
		summarizeBy: none
		sourceColumn: ID Alegación

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: 1e214f99-582c-42fb-9944-f103ca54e28e
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Entrada alegada'
		dataType: string
		lineageTag: 5d9b9734-3f9d-4a66-9237-234d3df530e6
		summarizeBy: none
		sourceColumn: Entrada alegada

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: aa88d494-e741-4f4e-9c33-1acb1b2196c3
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: string
		lineageTag: dafee954-7899-4edc-84d2-e258700c5bf1
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		annotation SummarizationSetBy = Automatic

	column Clasificación
		dataType: string
		lineageTag: 0b3d86c5-c4f9-4660-a402-bcf03ed48aa8
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 6806c361-6dab-4b03-88aa-3b53a21d8531
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: 6d0376fc-2679-471c-9b51-e9d6154265ca
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: a9066795-324c-45aa-8557-c420d63c38e7
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: 82c859ff-ea2c-4ae3-8865-dd884d40962e
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1c3b9593-9382-4497-8227-b32e43b9e982
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado - Copy

		variation Variación
			isDefault
			relationship: 1c56f23f-f125-4424-ac5c-6d70bedc7da0
			defaultHierarchy: LocalDateTable_c56f3f91-7a68-4935-89c7-b9223bd66da4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Comentarios AE'
		dataType: string
		lineageTag: ac37c14c-74c7-4b25-ae7c-c43c99a2e438
		summarizeBy: none
		sourceColumn: Comentarios AE

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI22-a82fb82a-d193-4cf7-930a-5c80b5df6989' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Source = #"PRO - Alegaciones del Servicio",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([ANS] = "KGI 2-2"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

