table 'PRO - Jira - Entregables con SLA - Incumplidos'
	lineageTag: 3a2e69cd-a70b-40a8-8328-59ce85221733

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 57dc38b4-c9ef-43a0-9370-10cb4b5853dc
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		variation Variation
			isDefault
			relationship: dc9228cc-d374-4326-aac4-07cb9d63999f
			defaultHierarchy: LocalDateTable_f6d77335-acaf-468e-b12d-d59934b39afe.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Tipo
		dataType: string
		lineageTag: 33deb31b-edfa-4130-ad24-555751fc6663
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column 'Total Rechazados'
		dataType: double
		lineageTag: e4641b56-b6ac-4f48-848d-84bf4020d80f
		summarizeBy: sum
		sourceColumn: Total Rechazados

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'PRO - Jira - Entregables con SLA - Incumplidos-7403e0b2-ead3-4737-a9d2-0edf4a4c269e' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Source = #"PRO - Jira - Entregables con SLA",
				
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Resolved - Copy", "Cerrado - Copy"}}),
				   
				    //Filtra solamente por los entregables que han sido rechazados
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Rechazado] = true)),
				
				    //Agrupa el total de entregables rechazados por mes y tipo de gravedad
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"Cerrado - Copy", "Tipo"}, {{"Total Rechazados", each Table.RowCount(_), type number}})
				in
				    #"Grouped Rows"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

