table 'PRO - Incidencias con SLA_P_y_A_Abiertas_KGI13'
	lineageTag: fc50025a-2ca3-46d4-96fe-1ce61733b339

	column Número
		dataType: string
		lineageTag: 37f12535-e36e-4cee-8b29-f42e51de2c9a
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: ed1c0d2c-172a-46c0-ba70-6dfb2db882ae
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 2dd74b2b-f63a-4bf9-953e-3088db21faf9
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: faf8228c-7a8b-4a66-88f8-0661ce8a2390
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: 27a3928f-9e37-4c7f-86d1-5378152cd18e
			defaultHierarchy: LocalDateTable_e232f784-546d-4a9c-80ad-eb06e1df0355.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8aeeb054-93c5-4e87-8255-fb58f26ce3ff
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variation
			isDefault
			relationship: 69f62761-9721-49fc-a8e2-60ead9216c40
			defaultHierarchy: LocalDateTable_cdf7cd2e-cb6c-4022-9050-5bc17af1ac24.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		lineageTag: 46a33c6f-b541-41bc-a987-fe3fb632c705
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real'
		dataType: int64
		lineageTag: 2f3d3864-a5d8-48c3-9e26-8aa882980445
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 108f1f40-36a8-40d5-843d-b70846f487c9
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: a8bc7830-ee0b-48d4-8836-1c5b17c47e68
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: ae03dd8b-3244-49fc-a4e8-60414ab8a646
			defaultHierarchy: LocalDateTable_9e9f0108-fb5b-45f2-81f5-aee5a692e792.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 2e62730f-cc7f-4543-b08f-e9173700f0ac
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 5b602600-00b9-4304-90eb-19cd1c55c58c
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 6fbae0f0-8c5f-4bfa-873c-f5223620ce34
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: 14d966ea-02f4-4b70-908b-2b90609a02ac
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 1aead51f-7764-4ab1-a658-2062e7fb0295
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Abierto - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 82b980d4-9ddc-4f62-b034-545375cf03a7
		summarizeBy: none
		sourceColumn: Abierto - Copy

		variation Variation
			isDefault
			relationship: 4a870ffb-6613-4206-a38c-2a3e4cd9dcc1
			defaultHierarchy: LocalDateTable_48ace1d0-5746-4488-beec-826e48998bb3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Sistema
		dataType: string
		lineageTag: db3b8c24-823d-4165-a926-c9fcebbc9d4c
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: int64
		lineageTag: a489d6ed-f4b9-4624-be89-fa48f6675124
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: ed12a875-1d72-4038-ad49-89d10c7e1597
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 06b4371f-11d4-414d-9db0-240547ea5341
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 925b11bf-46ef-41d2-b1bb-329f4c8d5f3f
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA_P_y_A_Abiertas_KGI13'[Número])
		lineageTag: 5768a75f-5d1b-4e85-907e-d844a8f062ed
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 02366aac-6608-4432-ad74-3792f9f9413c
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: ec1527a8-7350-4ea2-9a08-f1641a059ee9
			defaultHierarchy: LocalDateTable_7687b0b7-3784-43da-8fca-79280bf84720.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 8aa81311-49cf-4378-a1e3-add0435388e4
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA_P_y_A_Abiertas_KGI13-049ff6fb-5618-4fef-8ac0-00cc3137868a' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Source = #"PRO - Incidencias con SLA_P_y_A_Abiertas",
				
				    //Unificar Prioridades, según definición del KGI13
				    #"Replaced Value" = Table.ReplaceValue(Source, "Crítica", "Alta",Replacer.ReplaceText,{"Prioridad"})
				  
				in
				    #"Replaced Value"
				```

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = PRO - Incidencias con SLA_P_y_A_Abiertas_KGI13

	annotation PBI_NavigationStepName = Navigation

