table 'PRO - Incidencias con SLA - Críticas'
	lineageTag: ff595851-9941-4a98-8021-93593e6fbfb5

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9529742f-a3b6-43f3-85d8-dc3131d886bd
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Número
		dataType: string
		lineageTag: 6529f38e-e95b-4d7b-a2bf-f4901e99d704
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 7a4da3f0-2e96-4333-80cb-db5ef85bc9d9
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: c31e8d5d-154d-4157-80d1-f5dc30342a0a
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 8d84e8c9-1ffe-4c7b-a959-cc9f4b8514ee
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: df3f57d9-ef15-4646-954e-eaa420dac074
			defaultHierarchy: LocalDateTable_3f06b27f-0510-4dd2-8d37-7f92ac44a3e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: a6d46cec-2355-4b78-831e-2ad4aa890472
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variation
			isDefault
			relationship: e13b252d-1c6e-4b70-95e6-dd9e64e846b9
			defaultHierarchy: LocalDateTable_fdbe50b0-deb1-435f-9b69-a8f177b7e3ee.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		lineageTag: 616675ef-bb52-4b46-b827-0a01c07aa80d
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real'
		dataType: int64
		lineageTag: 331f4403-63cd-4d0d-bd98-39ab84fd63b7
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 37f00e95-10f9-46fb-bee6-a291070042c9
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 876599e6-1d72-4846-81ee-6e0f0d30ba9d
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: 27f09365-442a-48fc-ab3c-e15d8571463f
			defaultHierarchy: LocalDateTable_e05ab479-eb64-4ed4-bf1c-8c4eb0dd5415.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 3ddb0ae4-dbfb-4b84-acdf-614d59959882
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: f178054a-4e8e-4935-9328-a81b2f0cae8b
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: a8e551fa-4d36-4337-8bce-b1df3be526ac
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: e5f89936-617a-47e7-bfad-0fe0b2905362
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 1809b1df-b050-45b9-8f36-c53230445510
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: e68b9405-ac3c-45a5-9355-7d493c5c881c
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: d5f92cb9-d8d4-46ec-a992-4bc743f0a50c
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		lineageTag: 405ad94d-6588-4e91-9bc7-ab0b3e41d5be
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración excedida'
		dataType: string
		lineageTag: 9c280149-2e98-4b46-9edc-3c7f49645907
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 43edf8c9-ad99-4cd4-903c-443f19af48d8
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: fa0a70f0-a5f6-435d-a561-61560f6097f8
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: b6e43d4b-7266-44c4-9b79-391e8dbcedad
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 179e39de-18bd-4b9e-a320-eaaa22ac83d9
			defaultHierarchy: LocalDateTable_50550d32-f994-4552-b7df-c6b4d7f24588.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 41d40800-59cc-41eb-bf08-c6aab8e65914
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA - Críticas-3d482670-727d-48d4-bcc2-80f967e74dae' = m
		mode: import
		queryGroup: KGIs_II
		source =
				let
				    Source = #"PRO - Incidencias con SLA_P_y_A",
				    #"Filtered Rows" = Table.SelectRows(Source, each (
				        [Prioridad] = "Crítica"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

