table 'PRO - Planificaciones ENH'
	lineageTag: c3111907-90bf-4fa9-962b-1f4e2b8fcaea

	column Demanda
		dataType: string
		lineageTag: 61e19e54-1168-411c-b77e-b666712fb70f
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 177ca984-65a1-4959-99e6-082f066e91d5
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: e8933325-2fc3-4448-ac07-7a4b010c97e9
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: a0e1fb64-4ae5-4994-b85c-a6c45dbba32c
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: b0fbbd9a-88be-4e94-a60b-11adb11763c2
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1237b0e0-7b93-4ad3-845b-df0f191bebca
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variation
			isDefault
			relationship: f0ac69d1-74c4-477c-bbf3-25f8da328df2
			defaultHierarchy: LocalDateTable_befbb3cf-edff-4711-be3c-e4d621d8d9e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: f8e38fda-5555-4c71-9ba3-2a4bbe64a653
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variation
			isDefault
			relationship: e03c0d1d-d449-473a-9df5-c056ff95f569
			defaultHierarchy: LocalDateTable_6eea4b99-fcc3-4a06-b65b-48208e52226d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 9dd645be-e37b-4384-a965-731eec7f1c9a
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: 7ed29280-ecc5-4381-bc40-3b9fb2998ec4
		summarizeBy: none
		sourceColumn: Inicio

		variation Variation
			isDefault
			relationship: 36e51c88-9c9e-4b5d-8ee2-886059cf8757
			defaultHierarchy: LocalDateTable_3dec0e66-0613-4adb-acfa-301fdf0b27c9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 602d43f3-1b11-4b28-996c-fc85cb20585a
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: adea5bb8-1431-45e3-8c6d-816ca9a188f9
			defaultHierarchy: LocalDateTable_540c6fb8-a493-4f6b-b868-407172f4dba2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8957d4ee-42f5-45aa-8b8f-6a97b62066ba
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: 1d7a852b-7c39-42bc-9de6-c121f816a844
			defaultHierarchy: LocalDateTable_db190ea0-f337-4efb-be85-5370ece8b6d3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: c8384abc-76e5-4e3c-b373-8a1c55c148ce
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: 0b85216f-7a4c-4b33-9c99-a4251dc7c121
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 1940b6c2-d456-4da4-9524-9fb7f2beaa9a
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: d4aaaa2c-3e18-400a-8fe1-c8d19138e9af
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 6af86671-b3a4-4f01-b7dc-be596b340bbf
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: 283f08ca-9edf-4b95-8173-44fba5bd844c
		summarizeBy: none
		sourceColumn: Fin

		variation Variación
			isDefault
			relationship: 65c948ce-ee17-4214-ab49-06c5e6751cdd
			defaultHierarchy: LocalDateTable_8d40e723-4386-4dce-8f7b-71455bbf2dfa.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones ENH-2190f109-9151-4b94-b221-5786518bc69d' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Source = Excel.Workbook(Web.Contents(globalPath & planificaciones & xlsx), null, true),
				    #"Page 1_Sheet" = Source{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Promoted Headers",{{"Fecha de finalización derivada de", "Fecha final derivada de"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Número", type text}, {"Número_1", type text}, {"Nombre de subtarea", type text}, {"Prioridad", type text}, {"Abierto por", type text}, {"Grupo de asignación", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha fin planificada", type datetime}, {"Principal", type text}, {"Fecha Inicio Estimada", type datetime}, {"Fecha final derivada de", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Breve descripción", type text}}),
				    
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{
				        {"Número",                  "Demanda"},
				        {"Nombre de subtarea",      "Tipo de Proyecto"},  
				        {"Número_1",                "Número"}, 
				        {"Abierto por",             "Jefe de proyecto (Project Manager)"}, 
				        {"Grupo de asignación",     "Aplicación de Negocio "}, 
				        {"Principal",               "Nombre"}, 
				        {"Fecha Inicio Estimada",   "Inicio"}, 
				        {"Fecha final derivada de", "Fin"},
				        {"Breve descripción",       "Nombre de PRJ o MEJ"}}),
				    
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns",  "EN.EJE.EVOMAX_EXT.AE",     "MAXIMO: MAXIMO",Replacer.ReplaceText,{"Aplicación de Negocio "}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value", null, "",Replacer.ReplaceValue,{"Nombre"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",null,"Mejora",Replacer.ReplaceValue,{"Tipo de Proyecto"})
				
				in
				    #"Replaced Value3"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

