table 'PRO - Incidencias con SLA_P_y_A_Abiertas'
	lineageTag: 67cdbbfc-6776-483c-9d71-f28941f9f581

	column Número
		dataType: string
		lineageTag: d86f77cd-bcaa-418e-bb02-3bceb065f817
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: a561970a-c104-4b1d-bf7f-4208734283f9
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: ec49d003-9d80-4fad-993f-651e0d54ce92
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 3ef4bb2d-8a9c-470a-801e-086d23520022
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: c9f01e86-3ed6-4642-8521-3e51237d671f
		summarizeBy: none
		sourceColumn: Abierto

		variation Variation
			isDefault
			relationship: 3b72396e-4dad-4fb6-9e29-5c970a061920
			defaultHierarchy: LocalDateTable_f0e8f3ee-5944-496c-847f-5fed64464983.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: c1a5e2b1-5d97-4efe-a486-fd065fd104c1
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: b1b25c2b-d9ec-42d5-9f1f-501a968ae94e
			defaultHierarchy: LocalDateTable_b0a601c1-f5c2-4f69-9ade-5e19c8ea8131.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: f917772f-6359-4e23-ba30-ec8de134d751
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variation
			isDefault
			relationship: c431fa6b-dcd5-4fc6-bae7-2aa1ffed8db3
			defaultHierarchy: LocalDateTable_2b6e293b-ce94-47bc-913f-13e106374b16.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		lineageTag: 0c86b943-3e30-433a-924a-844f28e3775b
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real'
		dataType: int64
		lineageTag: 09cc4a25-b000-4da1-b289-cd6164249037
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8fdc6cb9-af60-4e39-8e42-3eb7656a8de0
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 49b6a5ce-c73f-468f-b5b0-fd736230c734
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: f9710d8b-9664-4b6f-a99e-2469a270e57e
			defaultHierarchy: LocalDateTable_88e07209-1c25-4940-a3cf-9f34af6a454f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 233a7743-f5c7-4378-ade2-06fa0dcfd486
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 97bdc081-beee-44e6-bc49-15ce8e85a490
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 8b6c55c2-780a-4ee5-8ca7-55c9c7fe850d
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: b0ebcd24-0fe0-4e9f-9a74-818481812cc3
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 374b3045-c13b-4438-88ce-da112ba387fd
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Abierto - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a2db34d9-e4eb-4d0a-86b0-f1646371ddda
		summarizeBy: none
		sourceColumn: Abierto - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Porcentaje de negocio trascurrido'
		dataType: int64
		lineageTag: 2476e211-fd25-463e-9952-8ae8d603ae00
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: ecb38a5c-5ec1-46b1-afc0-8e5ecce5b956
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 0aca6fb4-2d77-4bc2-a4c1-b03b6c7c517e
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 593fa66a-2254-4303-b784-5c2010175b0d
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA_P_y_A_Abiertas'[Número])
		lineageTag: 45b9d232-a340-4370-acc3-f597a113e6d2
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 4e2948b0-21f9-48c5-885b-4fc30c628daf
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA_P_y_A_Abiertas-4a3c2bdf-d9cf-4cdd-9832-99d81a25d932' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    URL = sharepointSource & Entorno & sharepointSource2 & incprevias & xlsx,
				    Origen = Excel.Workbook(Web.Contents(URL), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Número", type text}, {"Breve descripción", type text}, {"Subcategoría", type text}, {"Prioridad", type text}, {"Abierto", type datetime}, {"Cerrado", type datetime}, {"Fecha de resolución", type datetime}, {"Duración", Int64.Type}, {"Duración real", Int64.Type}, {"Infringido", type logical}, {"Tiempo original de incumplimiento", type datetime}, {"Estado", type text}, {"Estado SLA", type text}, {"Código de cierre", type text}, {"Reabierta", type logical}, {"Tipo de solución", type text}, {"Duración SLA", Int64.Type}, {"Porcentaje de negocio trascurrido", Int64.Type}}),
				
				    #"Appended Query" = Table.Combine({#"Tipo cambiado", #"PRO - Incidencias con SLA_A"}),
				
				
				//Homologa las prioridades
				    #"AllReplace" = [#"1 - Crítica" = "Crítica", #"2 - Alta" = "Alta", #"3 - Moderada" = "Media",#"3 - Media" = "Media",#"4 - Baja" = "Baja",#"5 - Muy Baja" = "Baja"],    
				    #"Replaced Value" = Table.TransformColumns(#"Appended Query",{{"Prioridad",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    
				
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced Value", "Abierto", "Abierto - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Abierto - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Abierto - Copy", Date.StartOfMonth, type date}}),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Calculated Start of Month",{{"Subcategoría", "Sistema"}}),
				     //Une con tabla de alegaciones KGI13_23
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Número"}, #"PRO - Alegaciones del Servicio KGI13_23", {"ID"}, "PRO - Alegaciones del Servicio KGI13_23", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio KGI13_23" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio KGI13_23", {"ANS", "Estado"}, {"PRO - Alegaciones del Servicio KGI13_23.ANS", "PRO - Alegaciones del Servicio KGI13_23.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio KGI13_23",{{"PRO - Alegaciones del Servicio KGI13_23.ANS", "ANS_Alegado"}, {"PRO - Alegaciones del Servicio KGI13_23.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Estado" si la alegación es aceptada
				    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns1",each [Estado],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI 1-3" then "Cancelado" else [Estado],Replacer.ReplaceValue,{"Estado"}),
				
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",each [Estado],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI 2-3" then "Cancelado" else [Estado],Replacer.ReplaceValue,{"Estado"}),
				    #"Filtered Rows3" = Table.SelectRows(#"Replaced Value3", each not Text.StartsWith([Estado], "Cancelado")),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows3", {"Número"}),
				    #"Filas filtradas" = Table.SelectRows(#"Removed Duplicates", each ([Estado SLA] <> "En pausa"))
				in
				    #"Filas filtradas"
				```

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = PRO - Incidencias con SLA_P_y_A_Abiertas

	annotation PBI_NavigationStepName = Navigation

