table 'PRO - Incidencias con SLA_P_y_A'
	lineageTag: 05b274c3-1e46-4964-b627-d5568f8ef8be

	column Número
		dataType: string
		lineageTag: 7c9bd5ee-2605-464a-a7c8-5f7de2c011cb
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 2ca8e099-916c-4d0b-8d80-5d52a8fc6573
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: 8fc25efa-baed-4c1e-8ed6-95395599d479
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 36f01b5b-11d6-453c-ac4d-4cbf77362028
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 6d57e3a1-807b-4c69-8a75-c66a556bb5d8
		summarizeBy: none
		sourceColumn: Abierto

		variation Variation
			isDefault
			relationship: 8dea28c3-c966-4da4-8865-17f378c28358
			defaultHierarchy: LocalDateTable_2ccb886c-8264-42d8-ad56-c3c6b25a9f4f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: a09d388a-6d92-4e3b-a1a7-273de946a931
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: 5a2471d7-7ea4-4b25-947b-52b7fbedaad2
			defaultHierarchy: LocalDateTable_209201f4-7449-48d3-bbcb-0f0bfc302049.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: c4459023-829b-43ac-a1e7-06fd87dc0a61
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variación
			isDefault
			relationship: 97dbc0fc-fa44-493c-8a83-2efb93948800
			defaultHierarchy: LocalDateTable_bf271174-3d26-4d57-9f64-c770bd59cca3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 4d9a01f5-9e31-47a4-a170-e5cacf3d948a
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: a1256fd8-04bd-42ec-adbc-8eae7a921159
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 37bf3664-56fd-45a6-94b7-8a996644af8f
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: e3375ed9-00e6-4f62-9873-6cf9dd9f0d7d
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variación
			isDefault
			relationship: 9f845fd2-96ef-43b4-9f94-eb5fba9915e2
			defaultHierarchy: LocalDateTable_7ad0c178-9126-40dd-9ea3-5858445391dd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 9f1e3223-c4a7-46f6-93b5-c862a4c9b356
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: f7244acc-5fef-4302-97f2-ebd2a92789e6
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: fe6f9c55-c2aa-4208-b219-a45b3fea563d
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: ba053e39-2976-4a89-bc90-7f980a16d8d7
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 0db8813f-2891-4cad-8ae9-65bb8e5e36ba
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Infringidos Numérico' = IF('PRO - Incidencias con SLA_P_y_A'[Infringido] = TRUE(),1,0)
		formatString: 0
		lineageTag: d4995d99-4e79-4322-8560-99ad2f16c4ba
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'No Infringidos Numerico' = IF('PRO - Incidencias con SLA_P_y_A'[Infringido] = TRUE(),0,1)
		formatString: 0
		lineageTag: e45afa03-2db6-4883-94e3-837904a5cdbb
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Mes = MONTH('PRO - Incidencias con SLA_P_y_A'[Cerrado])
		formatString: 0
		lineageTag: 1a9ce053-30ef-4022-8a00-a7f44a509719
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Año = YEAR('PRO - Incidencias con SLA_P_y_A'[Cerrado])
		formatString: 0
		lineageTag: 02b874d0-58bf-4da9-91cb-20d75304bf4e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Reabierta Numérica' = IF('PRO - Incidencias con SLA_P_y_A'[Reabierta] = "TRUE",1,0)
		formatString: 0
		lineageTag: b8ab8871-674f-4fc0-b9da-b1ab2bfa5acc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column CerradoFecha = 'PRO - Incidencias con SLA_P_y_A'[Cerrado].[Date]
		formatString: dd/mm/yyyy
		lineageTag: ad923c0e-4931-422f-923f-6cbd85c250ac
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column AbiertoFecha = 'PRO - Incidencias con SLA_P_y_A'[Abierto].[Date]
		lineageTag: a72348cb-3e83-46c4-a584-b217fea54776
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 8098c35d-8a66-4109-949e-c7d330cd2d4f
			defaultHierarchy: LocalDateTable_171aad4c-05dd-4c25-94a5-c61b530c1fa0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d8f5be2-eddf-4b89-ac39-f70e537fea14
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		variation Variation
			isDefault
			relationship: a66d5235-c403-4232-8c6e-07fe88906a75
			defaultHierarchy: LocalDateTable_4607465a-a880-4db8-b384-5bea228541a6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración D:HH:MM:SS' =
			
			VAR VDUR21 = 'PRO - Incidencias con SLA_P_y_A'[Duración real]
			  RETURN INT
			    (VDUR21/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21,60)),2)
		lineageTag: a34df0c7-c597-4692-8043-235463340dd4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: d05ab883-dda1-449f-8373-b5d06d688556
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 4cde9fee-1937-4a05-9fdc-7de97170130b
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Duración excedida'
		dataType: string
		lineageTag: c25bb876-e667-4f85-9364-4a65700fa811
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column 'Duración_EX D:HH:MM:SS' =
			
			VAR VDUR21_EX = 'PRO - Incidencias con SLA_P_y_A'[Duración excedida]
			  RETURN INT
			    (VDUR21_EX/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_EX/3600,24)),2)&" HH"
		lineageTag: 54efb984-4024-4a7e-9f23-997b6fc5cfc0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 7ac91899-409a-4823-9e58-b7a6647f873b
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: c0e9377e-ca13-46f8-aa0e-045a173e7167
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: beffe040-fd09-45f5-a3a4-e2ab49c7f41d
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	hierarchy 'Reabierta Jerarquía'
		lineageTag: f837754b-decb-42d4-ba68-a9b5eb7e48e2

		level Reabierta
			lineageTag: 1ffbf51b-7712-4a99-bcc8-3fdae1f34631
			column: Reabierta

		level Sistema
			lineageTag: 4d23748e-beff-4b24-a431-0e9850f69ff4
			column: Sistema

	partition 'PRO - Incidencias con SLA_P_y_A-0372dffc-56a7-4dc5-b546-b758c41a1f06' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    URL = sharepointSource & Entorno & sharepointSource2 & incprevias & xlsx,
				    Origen = Excel.Workbook(Web.Contents(URL), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1", Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Número", type text}, {"Breve descripción", type text}, {"Subcategoría", type text}, {"Prioridad", type text}, {"Abierto", type datetime}, {"Cerrado", type datetime}, {"Fecha de resolución", type datetime}, {"Duración", Int64.Type}, {"Duración real", Int64.Type}, {"Infringido", type logical}, {"Tiempo original de incumplimiento", type datetime}, {"Estado", type text}, {"Estado SLA", type text}, {"Código de cierre", type text}, {"Reabierta", type logical}, {"Tipo de solución", type text}, {"Duración SLA", Int64.Type}, {"Porcentaje de negocio trascurrido", Int64.Type}}),
				    
				    #"Appended Query" = Table.Combine({#"Tipo cambiado", #"PRO - Incidencias con SLA_A"}),    
				
				      //Homologa las prioridades
				    #"AllReplace" = [#"1 - Crítica" = "Crítica", #"2 - Alta" = "Alta", #"3 - Moderada" = "Media",#"3 - Media" = "Media",#"4 - Baja" = "Baja",#"5 - Muy Baja" = "Baja"],    
				    #"Replaced Value" = Table.TransformColumns(#"Appended Query",{{"Prioridad",each Record.FieldOrDefault(AllReplace,_,_)}}),
				     
				    #"Filtered Rows3" = Table.SelectRows(#"Replaced Value", each ([Cerrado] <> null)),
				
				    #"Duplicated Column" = Table.DuplicateColumn(#"Filtered Rows3", "Cerrado", "Cerrado - Copy"),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Duplicated Column",{{"Cerrado - Copy", Date.StartOfMonth, type datetime}}),
				    #"Extracted Date" = Table.TransformColumns(#"Calculated Start of Month",{{"Cerrado - Copy", DateTime.Date, type date}}),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Extracted Date",{{"Subcategoría", "Sistema"}}),
				
				    //Une con tabla de alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Número"}, #"PRO - Alegaciones del Servicio KGI24", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"ANS", "Estado"}, {"PRO - Alegaciones del Servicio.ANS", "PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.ANS", "ANS_Alegado"}, {"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				
				
				    //Realiza la correcciones si la alegación es aceptada
				    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns1",each [Prioridad],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI 2-4" then "Alta" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value2",{{"Prioridad", type text}}),
				
				    //Nuevo campo de Duración excedida, respecto a SLA
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Duración excedida", 
				    each if ([Duración real]-[Duración SLA])<0 then 0 else 
				    ([Duración real]-[Duración SLA])),
				
				    #"Divided Column" = Table.TransformColumns(#"Added Custom", {{"Porcentaje de negocio trascurrido", each _ / 100, Percentage.Type}})
				in
				    #"Divided Column"
				```

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = PRO - Incidencias con SLA_P_y_A

	annotation PBI_NavigationStepName = Navigation

