table 'PRO - Jira - Defectos con SLA'
	lineageTag: 8bddc173-3430-49be-a34c-2d801cef0d85

	column Components
		dataType: string
		lineageTag: d18f596b-1cce-4321-b21c-215a68da7417
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 01bf1a42-4b8c-47ea-ab8f-b4fa64d15035
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: 9c0c0bd8-4b84-413a-84b7-4fb50fb908a3
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 34ef0015-2db8-4db2-a438-bddc1d238412
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 6e103f9a-048b-415f-b680-9707f78cfd79
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 7accc9f8-fcba-4e09-be13-5326bfcdbc7b
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: b1609130-e87d-4930-8543-ce0d721cd72a
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 37dfffed-c006-419e-9468-3ac8843a9988
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: d8ae1c04-35f4-44fb-a97a-66ef70dac4d9
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 8e3df965-7931-4d3a-bfc0-807211e60d30
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 65ea9571-c66b-455e-a135-9fb2a9e5c120
			defaultHierarchy: LocalDateTable_75732222-5cf5-43a7-aa9a-91a0f2bdbdf4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 4809439c-4519-4eff-a598-3da9ef7cd3c2
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: e3540eb7-4ab9-4c6c-b16d-a875ca5adc98
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: 950430a8-a8a9-4152-881b-e6485b5ed1c0
			defaultHierarchy: LocalDateTable_dfb0493d-f256-4af0-b4c9-b00b73cd76cc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 84008580-d443-4abd-881a-471ad397243a
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Value (Bugs)'
		dataType: string
		lineageTag: 7aa6006e-0866-4d35-bde5-78335e8dcf4e
		summarizeBy: none
		sourceColumn: Value (Bugs)

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Status'
		dataType: string
		lineageTag: 3213c987-54a8-4270-96ae-eab2994db244
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: 502aa876-211c-4bf2-85bf-4900a5b75208
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved

		variation Variation
			isDefault
			relationship: 959a1d9a-a3d2-4fe8-8a91-353286185dd2
			defaultHierarchy: LocalDateTable_4523824c-503e-4f43-985d-0dac67ee3934.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status'
		dataType: string
		lineageTag: acece4aa-5b9f-45ba-abc2-487692311974
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba'
		dataType: string
		lineageTag: 8e977040-2887-462b-8e75-a8d3191d9250
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Pruebas con SLA.Priority'
		dataType: string
		lineageTag: fb4f16c5-3b58-4efc-be28-b9a8689cfcd3
		summarizeBy: none
		sourceColumn: PRO - Jira - Pruebas con SLA.Priority

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Pruebas con SLA.Status'
		dataType: string
		lineageTag: abeb33b2-04fd-4cdf-b369-94587b1909d7
		summarizeBy: none
		sourceColumn: PRO - Jira - Pruebas con SLA.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f6d70dec-b1c7-4c95-b935-9a272bcc45ef
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved - Copy

		variation Variation
			isDefault
			relationship: 55e8f64e-23f1-446a-b0e7-cc2575c5fedd
			defaultHierarchy: LocalDateTable_8a54f5c0-0663-4d38-9175-dc93c9443319.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: 015892b4-d6f7-45b3-bdb2-7c1367854e7f
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Defectos con SLA-c529664e-4ce4-4b6a-8d96-3f11a751901e' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    URL = sharepointSource & Entorno & sharepointSource2 & entregables & xlsx,
				    Origen = Excel.Workbook(Web.Contents(URL), null, true),
				    Tests_Sheet = Origen{[Item="Bugs",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Tests_Sheet, [PromoteAllScalars=true]),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Components", type text}, {"Project", type text}, {"Issue Type", type text}, {"Key", type text}, {"Summary", type text}, {"Assignee", type text}, {"Reporter", type text}, {"Priority", type text}, {"Status", type text}, {"Created", type datetime}, {"Linked Issues", type text}, {"Sub-tasks", type text}, {"Tipo de prueba", type text}, {"Resolved", type datetime}}),
				
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Linked Issues", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {
				        "Linked Issues.1",
				        "Linked Issues.2",
				        "Linked Issues.3",
				        "Linked Issues.4",
				        "Linked Issues.5",        
				        "Linked Issues.6",        
				        "Linked Issues.7",        
				        "Linked Issues.8",       
				        "Linked Issues.9",
				        "Linked Issues.10"        
				        }),
				
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{
				        {"Linked Issues.1", type text}, 
				        {"Linked Issues.2", type text}, 
				        {"Linked Issues.3", type text},
				        {"Linked Issues.4", type text},
				        {"Linked Issues.5", type text},
				        {"Linked Issues.6", type text},
				        {"Linked Issues.7", type text},
				        {"Linked Issues.8", type text},
				        {"Linked Issues.9", type text},
				        {"Linked Issues.10", type text}
				        }),
				
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type1", {"Components","Project", "Issue Type", "Key", "Summary", "Assignee", "Reporter", "Priority", "Status", "Created", "Sub-tasks", "Resolved"}, "Attribute", "Value (Bugs)"),
				    
				    //Une con las Historias (Relación Defecto con la tabla de Historias y Ejecuciones)
				    #"Merged Queries" = Table.NestedJoin(#"Unpivoted Columns", {"Value (Bugs)"}, #"PRO - Jira - Historias y Ejecuciones", {"Value (Stories)"}, "PRO - Jira - Historias y Ejecuciones", JoinKind.LeftOuter),
				    #"Expanded PRO - Jira - Historias y Ejecuciones" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Jira - Historias y Ejecuciones", {"Status", "Resolved", "PRO - Jira - Ejecuciones.Status", "PRO - Jira - Ejecuciones.Tipo de prueba"}, {"PRO - Jira - Historias y Ejecuciones.Status", "PRO - Jira - Historias y Ejecuciones.Resolved", "PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status", "PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba"}),
				    
				    //Une con los Tests (Relación Defecto con su Test)
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded PRO - Jira - Historias y Ejecuciones", {"Value (Bugs)"}, #"PRO - Jira - Pruebas con SLA", {"Key"}, "PRO - Jira - Pruebas con SLA", JoinKind.LeftOuter),
				    #"Expanded PRO - Jira - Pruebas con SLA" = Table.ExpandTableColumn(#"Merged Queries1", "PRO - Jira - Pruebas con SLA", {"Priority", "Status"}, {"PRO - Jira - Pruebas con SLA.Priority", "PRO - Jira - Pruebas con SLA.Status"}),
				
				    //Homologa las prioridades
				    #"AllReplace" = [#"Highest" = "Grave", #"High" = "Grave", #"Medium" = "Media",#"Low" = "Leve",#"Lowest" = "Leve"],    
				    #"Replaced Value" = Table.TransformColumns(#"Expanded PRO - Jira - Pruebas con SLA",{{"Priority",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    
				    //Ajuste de campo de Hitorias & Ejecuciones para relacionar a fechas Dashboard
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced Value", "PRO - Jira - Historias y Ejecuciones.Resolved", "PRO - Jira - Historias y Ejecuciones.Resolved - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"PRO - Jira - Historias y Ejecuciones.Resolved - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"PRO - Jira - Historias y Ejecuciones.Resolved - Copy", Date.StartOfMonth, type date}}),
				
				    //Une con las alegaciones
				    #"Merged Queries2" = Table.NestedJoin(#"Calculated Start of Month", {"Key"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries2", "PRO - Alegaciones del Servicio", {"Estado"}, {"PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}})
				
				in
				    #"Renamed Columns1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

