table 'PRO - Jira - Defectos con SLA - UAT'
	lineageTag: 93766fb8-06d8-4a99-a8d7-a1517a093b37

	column Priority
		dataType: string
		lineageTag: 8a637826-7ab3-4454-a350-c9a6e25dfd99
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column 'Defectos UAT'
		dataType: double
		lineageTag: 64386154-d372-409a-9ff1-bf0391193a15
		summarizeBy: sum
		sourceColumn: Defectos UAT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PRO - Jira - Historias y Ejecuciones.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2dabe72c-a9f4-43b1-b918-1d64444dcf92
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved - Copy

		variation Variation
			isDefault
			relationship: 16d6e4ea-c83d-4db9-9970-668147cec754
			defaultHierarchy: LocalDateTable_c692f288-ae20-4a6f-b8b1-f1f10bd3302f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'PRO - Jira - Defectos con SLA - UAT-e53b2801-7053-41e3-9aad-452ef88f4cd7' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = #"PRO - Jira - Defectos con SLA",
				
				    #"Filtered Rows" = Table.SelectRows(Source, each Text.Contains([#"PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba"], "UAT")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [Estado_Alegación] <> "1 - Aprobada"),
				
				    #"Grouped Rows" = Table.Group(#"Filtered Rows1", {"PRO - Jira - Historias y Ejecuciones.Resolved - Copy", "Priority"}, {{"Defectos UAT", each Table.RowCount(_), type number}})
				in
				    #"Grouped Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

