table 'PRO - Jira - Entregables con SLA'
	lineageTag: 4494bbe5-3452-4eaf-942c-6538ad52357b

	column 'Issue Type'
		dataType: string
		lineageTag: e293efb8-8f22-4734-ba56-47659f51c014
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: e62106f5-9e4d-4e0d-bf3a-120bec7fdf60
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: cb1d687c-fd03-4c06-ab2a-9b7a18e78503
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Components
		dataType: string
		lineageTag: a68f3552-0895-4ffb-821f-c9acc87d7846
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: aa6c690a-4470-45da-9212-1382f3462346
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: f111da99-20b1-4d1d-a482-fd36c4bff9b9
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 280030d2-201b-4801-889c-d9c75fef51a0
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: e702bea3-f8a0-4aec-bc30-13bb3f8535e1
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'End Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: ae2864ee-4a22-42e4-ad23-9bf9fc5ac9be
		summarizeBy: none
		sourceColumn: End Date

		variation Variation
			isDefault
			relationship: d4b3148d-e3f0-408f-ad66-e40bd535cfe3
			defaultHierarchy: LocalDateTable_1c4405a5-e746-4d71-8b52-f0037ad20c4f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'End Real Date'
		dataType: string
		lineageTag: 459dced4-6c2d-4161-b538-5c3a15300abd
		summarizeBy: none
		sourceColumn: End Real Date

		annotation SummarizationSetBy = Automatic

	column 'Linked Issues'
		dataType: string
		lineageTag: 2899a407-ad3e-4bdb-b58f-9546cbf1add3
		summarizeBy: none
		sourceColumn: Linked Issues

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 11877cce-9b9c-434d-90da-cf27e9d4b1f9
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: fb4c0a3b-8f4a-4472-a951-7e7948c13390
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: 9b72112f-6fff-48bc-94a7-d04e91d59ccc
			defaultHierarchy: LocalDateTable_f1be6c47-0ab0-498b-8cf5-fb6ced484fb1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Rechazado
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ccb2deb3-4e87-43c7-9340-f8b52496a41f
		summarizeBy: none
		sourceColumn: Rechazado

		annotation SummarizationSetBy = Automatic

	column 'Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c9dec7e3-60d6-455a-8fcc-aa888fdad889
		summarizeBy: none
		sourceColumn: Resolved - Copy

		variation Variation
			isDefault
			relationship: 838891c5-1c00-400c-a468-8eb757a49a38
			defaultHierarchy: LocalDateTable_4ae39781-4ebd-494e-8cb2-49cfae8e3f40.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: e16f7cbe-951a-415e-a278-45ba8350ab05
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Deliverable type'
		dataType: string
		lineageTag: 03cbd99a-9a29-4da5-ac9a-b6c9ecffa4a0
		summarizeBy: none
		sourceColumn: Deliverable type

		annotation SummarizationSetBy = Automatic

	column 'Approval status'
		dataType: string
		lineageTag: 625dcf3b-da26-4d7d-8066-102d4bd705bd
		summarizeBy: none
		sourceColumn: Approval status

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 03a6862b-edc4-4c1c-a9e8-c92a4c491c15
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Entregables con SLA-5c54ffc6-de48-4fc9-8b50-725b12f7f0a8' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    URL = sharepointSource & Entorno & sharepointSource2 & entregables & xlsx,
				    Origen = Excel.Workbook(Web.Contents(URL), null, true),
				    #"Entregables Rechazados_Sheet" = Origen{[Item="Entregables",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Entregables Rechazados_Sheet", [PromoteAllScalars=true]),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Issue Type", type text}, {"Deliverable type", type text}, {"Project", type text}, {"Key", type text}, {"Components", type text}, {"Summary", type text}, {"Priority", type text}, {"Assignee", type text}, {"Status", type text}, {"Approval status", type text}, {"End Date", type datetime}, {"End Real Date", type text}, {"Linked Issues", type text}, {"Sub-tasks", type text}, {"Resolved", type datetime}, {"Rechazos", type logical}}),
				
				//Homologa las prioridades
				    #"AllReplace" = [#"Highest" = "Grave", #"High" = "Grave", #"Medium" = "Grave",#"Low" = "Leve",#"Lowest" = "Leve"],    
				    #"Replaced Value" = Table.TransformColumns(#"Changed Type",{{"Priority",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    
				    //Renombra la Prioridad por "Tipo" de incumplimiento como dice el ANS
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"Priority", "Tipo"}, {"Rechazos", "Rechazado"}}),
				
				    //Filtra por solo aplicaciones correspondientes a MAX
				    #"Filtered Rows3" = Table.SelectRows(#"Renamed Columns", each ([Components] 
				        = "MAXIMO: MAXIMO")),
				
				    //Copia el campo Resolved para relacionar a la tabla fechas
				    #"Duplicated Column" = Table.DuplicateColumn(#"Filtered Rows3", "Resolved", "Resolved - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Resolved - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Resolved - Copy", Date.StartOfMonth, type date}}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Calculated Start of Month",null,false,Replacer.ReplaceValue,{"Rechazado"}),
				
				    //Une con las alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value5", {"Key"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"Estado"}, {"PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Rechazado" si la alegación es aceptada
				    #"Replaced Value6" = Table.ReplaceValue(#"Renamed Columns1",each [Rechazado],each if [Estado_Alegación] = "1 - Aprobada" then "FALSE" else [Rechazado],Replacer.ReplaceValue,{"Rechazado"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value6",{{"Rechazado", type logical}})
				
				in
				    #"Changed Type4"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

