table 'PRO - Planificaciones PRJ y ENH con SLA - Relacionada'
	lineageTag: c4d7eb32-e817-46d7-b60a-2f3ba021def2

	column Demanda
		dataType: string
		lineageTag: 0674bc52-a57d-40bc-8837-07923cd031a0
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: eb38d3ac-d9fe-4c24-9459-a8381ca19bc0
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 2fb96a7f-1482-470e-99dd-31f4f687b2b4
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 2b52e24f-f567-4f3a-8546-d0428599f5c7
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: 5e7ff526-d5c8-464a-8f5e-e8ba68415d16
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: 15a1a2a6-7dd9-46e4-a3bc-6de4a72abab9
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1e860b2a-174e-4d63-b7fe-fd2100a5e0cf
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variación
			isDefault
			relationship: b7e7ca1d-9d5f-4054-ab8d-1a3f338de0fc
			defaultHierarchy: LocalDateTable_4c1dced5-3c7f-4ac9-a0a2-327fbae7ab6f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha límite planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 776c7f99-9667-4f4e-a604-c417c8c4d6e1
		summarizeBy: none
		sourceColumn: Fecha límite planificada

		variation Variación
			isDefault
			relationship: 136781b0-f7d2-41e7-8638-0da62a51519b
			defaultHierarchy: LocalDateTable_6a970996-0072-4818-88b8-456f3e4948e5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 6e02a2e4-257c-42b8-a3bd-b80c4f033501
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: 11117047-aa28-4be1-8326-4c5bfb7b2dd6
		summarizeBy: none
		sourceColumn: Inicio

		variation Variación
			isDefault
			relationship: f7bc4721-d891-46b5-9112-6156945a4473
			defaultHierarchy: LocalDateTable_d97e524f-5197-4ce1-921a-b69e5c536943.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: 81e97201-89f0-41bc-ac80-f101ee141506
		summarizeBy: none
		sourceColumn: Fin

		variation Variación
			isDefault
			relationship: 79aca3f4-567e-4a2a-9871-03a7c4ae7fff
			defaultHierarchy: LocalDateTable_e2b5481a-3785-4057-b6fa-acce4b8b1af4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 25b4247a-83cc-4ea2-a51e-7b6d72b88947
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variación
			isDefault
			relationship: 0901f08f-e851-474b-9f95-6208680fccc2
			defaultHierarchy: LocalDateTable_9ed1f548-534d-4e90-b088-daeba74210ad.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 800be6bd-2842-431e-95d3-cdaa3bb1613c
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variación
			isDefault
			relationship: f80cdbe8-af35-49f4-9edb-17010d18f5e2
			defaultHierarchy: LocalDateTable_723ae39b-0407-4161-843b-5e837592d42a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: 1ed70980-dcb3-40b3-ac02-9a2cfbc5cd8e
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: 68c63f5f-d5df-436e-8dae-cf8c1bb9c39a
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 57ba22a6-b5d7-4d27-9c68-4bf6f99d9551
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: b2729f7f-625a-4e80-a046-048f02f2e9de
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 653e5b08-4048-4f43-a6a3-9d93de0feea5
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variación
			isDefault
			relationship: 6cc7c33e-80de-4933-bfa3-f5451db4727f
			defaultHierarchy: LocalDateTable_0b6c9886-f603-4f83-b736-964680c9587e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 894b65b2-2fcd-45e7-b727-6fa78c28a0fe
		summarizeBy: none
		sourceColumn: Fecha fin real - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración Planificada LB'
		dataType: double
		lineageTag: 72e7447f-876e-474b-b0ec-29d48f6d967a
		summarizeBy: sum
		sourceColumn: Duración Planificada LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real LB'
		dataType: double
		lineageTag: 0ddf1eea-697c-4bc2-ad1c-7b33b5d30f9b
		summarizeBy: sum
		sourceColumn: Duración real LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa de desviación'
		dataType: double
		lineageTag: e84b361c-499e-4ef4-b5fe-906142427d5a
		summarizeBy: sum
		sourceColumn: Tasa de desviación

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimación incumplida'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0d88edfe-6dce-4ad1-b28f-75d428d9956a
		summarizeBy: none
		sourceColumn: Estimación incumplida

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: a6f1cd18-f551-4101-b70a-66f7b5b4a55f
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Incidencias - Relacionadas.Incidente'
		dataType: string
		lineageTag: 2b4e8c0b-5f99-4520-93e5-0010dd6a3683
		summarizeBy: none
		sourceColumn: Incidencias - Relacionadas.Incidente

		annotation SummarizationSetBy = Automatic

	column ServiceNow_Incidencia = CONCATENATE("https://acciona.service-now.com/incident.do?sysparm_query=number%3d", 'PRO - Planificaciones PRJ y ENH con SLA - Relacionada'[Incidencias - Relacionadas.Incidente])
		lineageTag: 4a33f0b8-2dc0-4b1b-ba98-ef222f459656
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ServiceNow-Tarea = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Planificaciones PRJ y ENH con SLA - Relacionada'[Número])
		lineageTag: 717551c6-bcde-4911-a698-b016458092d7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones PRJ y ENH con SLA - Relacionada-f32f2db9-b4d2-469e-b647-f6081a7e4df8' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Origen = #"PRO - Planificaciones PRJ y ENH con SLA",
				    #"Consultas combinadas" = Table.NestedJoin(Origen, {"Número"}, #"Incidencias - Relacionadas", {"Tarea"}, "Incidencias - Relacionadas", JoinKind.LeftOuter),
				    #"Se expandió Incidencias - Relacionadas" = Table.ExpandTableColumn(#"Consultas combinadas", "Incidencias - Relacionadas", {"Incidente"}, {"Incidencias - Relacionadas.Incidente"}),
				    #"Filas filtradas" = Table.SelectRows(#"Se expandió Incidencias - Relacionadas", each ([#"Incidencias - Relacionadas.Incidente"] <> null))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

