table 'PRO - Planificaciones MA'
	lineageTag: 05cc0f10-8c67-4846-a5eb-3285e459f683

	column Demanda
		dataType: string
		lineageTag: c81c8cfc-9ca1-48db-9e72-26c41b6b8354
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 4adba4bf-0435-49e0-be3c-aaa25fb07aa9
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: f033072f-eee8-49ad-b7e0-e6fb11a4cdce
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 0a492a4c-cb73-4a6a-988d-37516042c9d8
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: 7e6372f4-2475-40c2-abd2-ad609842dd0a
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: 3d80a87b-ba7d-4910-b04b-65dd99cd717c
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: b77776cc-7729-429a-9e8f-daeb1f22b593
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variation
			isDefault
			relationship: f1c2ff19-dc45-4733-8784-9e02b822521b
			defaultHierarchy: LocalDateTable_644e9fda-3758-4fae-9e15-df3d35706a7d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: ca3ddda5-a6eb-4d20-bcc7-a541969c1fe2
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variation
			isDefault
			relationship: 1ae4f115-06f5-4390-98e8-c517a86181c0
			defaultHierarchy: LocalDateTable_ace832ad-73d1-4c4a-aa40-fd51a45c9598.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 5a7037aa-d82c-46c7-8d66-77d3b48c5219
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: a88557c9-c70c-4dbc-b082-94f083ca5d0f
		summarizeBy: none
		sourceColumn: Inicio

		variation Variation
			isDefault
			relationship: 48cbcbc7-fc1c-4fc6-b397-2cbce740b4ea
			defaultHierarchy: LocalDateTable_ddf43091-aa12-45da-a017-7f828e5d2402.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 816c0b35-d7ce-4775-954c-3e2730d43d19
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: 26bcd3c3-82fa-4731-b5e6-c30cc4441105
			defaultHierarchy: LocalDateTable_f36d0a80-9527-472e-aaa5-7fca701fd1c2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 7f24756f-88d7-409d-b987-350f9a3d69e0
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: 94553bf3-6316-4935-8766-27a39c78b951
			defaultHierarchy: LocalDateTable_89940140-1b60-4c13-a603-b9525703d81d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: b5b6357f-1e0c-45a5-b4db-1f0ad77403b5
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: 7d806010-c2a2-4835-b115-1ca0608f6a93
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 847689a7-3ed0-49b0-b6aa-7c9a915dfe38
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: 49ffad1d-529b-4511-8087-a08d58594b2e
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: e8feb105-c2fa-4452-bb16-d5e8d6e7d491
		summarizeBy: none
		sourceColumn: Fin

		variation Variación
			isDefault
			relationship: 695289f7-6a9c-466f-9502-b41decbff255
			defaultHierarchy: LocalDateTable_144e7fd1-d652-4324-b1e3-10663ca8e249.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones MA-79bd6986-2989-4c18-863a-41eff1683ea9' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Source = Excel.Workbook(Web.Contents(globalPath & PRJMA & xlsx), null, true),
				    #"Page 1_Sheet" = Source{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Promoted Headers",{{"Fecha de finalización derivada de", "Fecha final derivada de"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Número", type text}, {"Número_1", type text}, {"Tipo de Proyecto", type text}, {"Prioridad", type text}, {"Jefe de proyecto (Project Manager)", type text}, {"Aplicación de Negocio ", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha fin planificada", type datetime}, {"Nombre de subtarea", type text}, {"Fecha de inicio derivada de", type datetime}, {"Fecha final derivada de", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Breve descripción", type text}}),
				
				    //Homologa cabeceras para realizar posterior Append con PRJs
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{
				        {"Número",                      "Demanda"},
				        {"Número_1",                    "Número"}, 
				        {"Nombre de subtarea",          "Nombre"}, 
				        {"Fecha de inicio derivada de", "Inicio"}, 
				        {"Fecha final derivada de",     "Fin"}, 
				        {"Breve descripción",           "Nombre de PRJ o MEJ"}})
				
				in
				    #"Renamed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

