table 'Resumen KGI12'
	lineageTag: bf625115-7082-47ab-97f7-644bf2dbaf23

	measure 'Puntos de KGI12_M' =
			
			var _KGI12_V = MIN('Resumen KGI12'[Puntos de KGI12])
			return
			IF(ISBLANK(_KGI12_V),30,_KGI12_V)
		lineageTag: 2c247831-4d92-4eaa-b38a-2c60c19229d6

	measure 'Peso Obtenido KGI12_M' = 1-SUM('Resumen KGI12'[Peso No Obtenido %])
		lineageTag: 4330d5c3-d0f5-4846-9c93-7eab3d146bbf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Puntos Obtenidos KGI12_M' = [Peso Obtenido KGI12_M]*[Puntos de KGI12_M]
		lineageTag: a9a72de8-8218-4d53-b0f9-4faff76bf385

	column Prioridad
		dataType: string
		lineageTag: 98397b8a-1eac-4fa2-be25-dea35a23269d
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e4b08b1d-5807-4e4e-b473-6db16d460f3c
		summarizeBy: none
		sourceColumn: Fecha fin real - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Cump. Objetivo %'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: e1f408d4-1e4f-4bc6-a64b-da1f9656ebd6
		summarizeBy: sum
		sourceColumn: Cump. Objetivo %

		annotation SummarizationSetBy = Automatic

	column 'Peso %'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 1171d7aa-1d39-4052-919c-22ec2a370ec9
		summarizeBy: sum
		sourceColumn: Peso %

		annotation SummarizationSetBy = Automatic

	column 'Planificaciones Cumplidas' = 'Resumen KGI12'[Total Planificaciones]-'Resumen KGI12'[Planificaciones Incumplidas]
		formatString: 0
		lineageTag: 5cce64b1-05b8-484c-9653-92175387b98d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Cump. Real %' = ('Resumen KGI12'[Planificaciones Cumplidas])/('Resumen KGI12'[Total Planificaciones])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 37e27cf3-785b-4b5d-bbc7-54f7e49f90f8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ¿Cumple? = IF('Resumen KGI12'[Cump. Real %]>='Resumen KGI12'[Cump. Objetivo %],"Si","No")
		lineageTag: 974f7b25-e0d6-4211-b570-535b5d52ac49
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Peso Obtenido %' = IF('Resumen KGI12'[¿Cumple?]="Si",'Resumen KGI12'[Peso %],0)
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: bbc23f4a-3e88-449f-90c1-a829a3736473
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column KGI
		dataType: string
		lineageTag: b894b852-3723-48b7-9037-c646b4a21e31
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	column 'Peso No Obtenido %' = IF('Resumen KGI12'[¿Cumple?]="No",'Resumen KGI12'[Peso %],0)
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 01cba141-b0b1-46b4-b3d2-b32e53c89907
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Total Planificaciones'
		dataType: double
		formatString: 0
		lineageTag: 1294100a-9d1c-4bc2-a177-5e0bfe4c5a33
		summarizeBy: sum
		sourceColumn: Total Planificaciones

		annotation SummarizationSetBy = Automatic

	column 'Puntos de KGI12'
		dataType: string
		lineageTag: 7de83c07-d2c0-4181-9b90-7e21835b2875
		summarizeBy: none
		sourceColumn: Puntos de KGI12

		annotation SummarizationSetBy = Automatic

	column 'Planificaciones Incumplidas'
		dataType: double
		formatString: 0
		lineageTag: 5f6f4fa9-fce4-4048-baf3-85030511cb2b
		summarizeBy: sum
		sourceColumn: Planificaciones Incumplidas

		annotation SummarizationSetBy = Automatic

	partition 'Resumen KGI12-92fbc821-a30e-445a-bc7f-df91b496157d' = m
		mode: import
		queryGroup: Resumen
		source = ```
				let
				    Source = #"PRO - Planificaciones PRJ y ENH con SLA",
				    
				    //Agrupar Total Planificaciones
				    #"Grouped Rows" = Table.Group(Source, {"Prioridad", "Fecha fin real - Copy"}, {{"Total Planificaciones", each Table.RowCount(_), type number}}),
				    
				    //Unir Total Planificaciones Incumplidas
				    #"Merged Queries" = Table.NestedJoin(#"Grouped Rows", {"Prioridad", "Fecha fin real - Copy"}, #"PRO - Planificaciones PRJ y ENH con SLA - Incumplidas", {"Prioridad", "Fecha fin real - Copy"}, "PRO - Planificaciones PRJ y ENH con SLA - Incumplidas", JoinKind.LeftOuter),    
				    #"Expanded PRO - Planificaciones PRJ y ENH con SLA - Incumplidas" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Planificaciones PRJ y ENH con SLA - Incumplidas", {"Estimación Incumplida"}, {"Planificaciones Incumplidas"}),    
				    
				    //Unir Tabla de Parámetros 
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded PRO - Planificaciones PRJ y ENH con SLA - Incumplidas", {"Prioridad"}, #"Parametros KGI12", {"Prioridad Hitos Evolutivos"}, "Parametros KGI1-2", JoinKind.LeftOuter),    
				    #"Expanded Parametros KGI1-2" = Table.ExpandTableColumn(#"Merged Queries1", "Parametros KGI1-2", {"% cumplimiento Objetivo", "Pesos %"}, {"Parametros KGI1-2.% cumplimiento Objetivo", "Parametros KGI1-2.Pesos %"}),    
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Parametros KGI1-2",{{"Parametros KGI1-2.% cumplimiento Objetivo", "Cump. Objetivo %"}, {"Parametros KGI1-2.Pesos %", "Peso %"}}),
				    
				    #"Sorted Rows" = Table.Sort(#"Renamed Columns1",{{"Fecha fin real - Copy", Order.Ascending}}),
				    
				    //Añadir otras columnas de valores constantes
				    #"Added Custom" = Table.AddColumn(#"Sorted Rows", "KGI", each "KGI1-2"),    
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Puntos de KGI12", each 30)
				in
				    #"Added Custom1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

