table 'Resumen KGI13_1_Críticas/Altas'
	lineageTag: 850b205a-1813-4a1f-9df5-e57ab253c334

	measure 'Puntos de KGI13_M_A' =
			
			var _KGI13_V = MIN('Resumen KGI13_1_Críticas/Altas'[Puntos de KGI13])
			return
			IF(ISBLANK(_KGI13_V),15,_KGI13_V)
		formatString: 0
		lineageTag: 5810ba4e-320c-49b5-b483-0d0bb2482674

	column Prioridad
		dataType: string
		lineageTag: b51f1dec-0da2-4de5-bb25-39ecaaabe26b
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Abierto - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8a872429-b89e-487f-b3ec-211a1cb4bdc3
		summarizeBy: none
		sourceColumn: Abierto - Copy

		variation Variation
			isDefault
			relationship: a9a73d7b-c742-4d3b-abab-0ed19da3d9cd
			defaultHierarchy: LocalDateTable_a05f5ad7-342d-4398-a911-6cc04ed0653f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Total Incidencias'
		dataType: double
		formatString: 0
		lineageTag: 29f35975-e621-414e-acc6-552fa68b6fcc
		summarizeBy: sum
		sourceColumn: Total Incidencias

		annotation SummarizationSetBy = Automatic

	column 'Tasa máxima permitida %'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 1a9ed626-33eb-4f68-a430-3770f1301178
		summarizeBy: sum
		sourceColumn: Tasa máxima permitida %

		annotation SummarizationSetBy = Automatic

	column 'Peso del KGI %'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 93348cb6-a9b6-495c-9d58-bd8b7b13d61a
		summarizeBy: sum
		sourceColumn: Peso del KGI %

		annotation SummarizationSetBy = Automatic

	column 'Puntos de KGI13'
		dataType: int64
		formatString: 0
		lineageTag: 734dfbf5-9e69-4a88-9bfd-8b94cb23a599
		summarizeBy: sum
		sourceColumn: Puntos de KGI13

		annotation SummarizationSetBy = Automatic

	column KGI
		dataType: string
		lineageTag: 38ed25bd-9172-404e-9cce-e9d9e9ed7633
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	column ¿Cumple? = [KGI13_P1 ¿Cumple?_M]
		lineageTag: 4d3c8d97-b921-42bf-b7f5-58a7ffe0c6bc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Resumen KGI13_1_Críticas/Altas-ab21f325-a94e-4538-a98a-fdbe6a03b45b' = m
		mode: import
		queryGroup: Resumen
		source = ```
				let
				    Source = #"PRO - Incidencias con SLA_P_y_A_Abiertas",
				
				    //Total Incidencias Abiertas por Prioridad
				    #"Grouped Rows" = Table.Group(Source, {"Prioridad", "Abierto - Copy"}, {{"Total Incidencias", each Table.RowCount(_), type number}}),
				
				      //Homologa las prioridades
				    #"AllReplace" = [#"1 - Crítica" = "Alta", #"2 - Alta" = "Alta", #"3 - Moderada" = "Media",#"4 - Baja" = "Baja",#"5 - Muy Baja" = "Baja",#"Crítica" = "Alta"],    
				    #"Replaced Value" = Table.TransformColumns(#"Grouped Rows",{{"Prioridad",each Record.FieldOrDefault(AllReplace,_,_)}}),
				
				    //Unir Tabla de Parámetros
				    #"Merged Queries" = Table.NestedJoin( #"Replaced Value", {"Prioridad"}, #"Parametros KGI13", {"Prioridad "}, "Parametros KGI1-3 (2)", JoinKind.LeftOuter),
				    #"Expanded Parametros KGI1-3" = Table.ExpandTableColumn(#"Merged Queries", "Parametros KGI1-3 (2)", {"Tasa máxima permitida %", "Peso del KGI %", "Puntos de KGI13", "KGI"}, {"Parametros KGI1-3 (2).Tasa máxima permitida %", "Parametros KGI1-3 (2).Peso del KGI %", "Parametros KGI1-3 (2).Puntos de KGI13", "Parametros KGI1-3 (2).KGI"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Parametros KGI1-3",{{"Parametros KGI1-3 (2).Tasa máxima permitida %", "Tasa máxima permitida %"}, {"Parametros KGI1-3 (2).Peso del KGI %", "Peso del KGI %"}, {"Parametros KGI1-3 (2).Puntos de KGI13", "Puntos de KGI13"}, {"Parametros KGI1-3 (2).KGI", "KGI"}}),
				
				    //Filtro por "Altas"
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Prioridad] = "Alta")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Tasa máxima permitida %", Percentage.Type}, {"Peso del KGI %", Percentage.Type}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

