table BI_Aplicación
	lineageTag: e50c3332-34aa-4ddf-a167-18cf04a882f7

	measure 'Presupuesto Real €' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Evolutivos", 'BI_Aplicación'[Atributo] = "Presupuesto")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 431a545d-b0fc-492d-8dbc-64a11aa8e761

	measure 'Línea Base Real consumida €' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos", 'BI_Aplicación'[Atributo] = "Consumo Real", MONTH('BI_Aplicación'[Periodo]<= MONTH(TODAY())))
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 4114ea38-a7b8-46cd-b3c5-3f1ac21f2039

	measure '€_presupuesto restante' = [Linea_Base_esperada_total] - 'BI_Aplicación'[Línea Base Real consumida €]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 14102199-e0af-4150-891c-f92762106214

	measure Linea_Base_esperada_total = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Atributo]="Línea Base Objetivo", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: f2de11d8-66ba-4c94-94f2-9d000d51ac74

	measure Linea_Base_esperada_total_mensual = CALCULATE(SUM('BI_Aplicación'[Valor])/12, 'BI_Aplicación'[Atributo]="Línea Base Objetivo", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 7dd9e543-c72c-4fdc-b014-e4148ae2a8f1

	measure '€_Linea Base Real por Mes' = ```
			
			[Línea Base Real consumida €]/ [Meses_Restantes_Año_12_2] 
			```
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: e3f5728f-f4a4-44db-9828-2ef87188c9f6

	measure 'Linea Base Restante mes' = DIVIDE([€_presupuesto restante], [Meses_Restantes_Año_1], 0)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: eb7b2e5a-1572-483d-bdbc-39f6b6c5949e

	measure Meses_Restantes_Año_1 =
			IF(
			    YEAR(TODAY()) > YEAR(MAX('BI_Aplicación'[Periodo])),
			    1,
			    12 - MONTH(TODAY())
			)
		formatString: 0
		lineageTag: 70f6e228-f293-4ca3-b6da-ad04fa13bf28

	measure Meses_Restantes_Año_12 =
			IF(
			    YEAR(TODAY()) > YEAR(MAX('BI_Aplicación'[Periodo])),
			    12,
			    12 - MONTH(TODAY()))
		formatString: 0
		lineageTag: 92341247-d4aa-4326-83f4-e05080d10e9b

	measure Desviacion-Proyectado = [Presupuesto Real €] - [Línea Base Real Consumida €] - [LB proyectada Evo €] - 10053
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 8c69ecbd-654f-4f19-983e-8698d9a54e42

	measure Línea_Real_Consumida_SamePeriodLastYear =
			
			[Línea Base Real consumida €] -
			
			CALCULATE(SUM('BI_Aplicación'[Valor]),
			 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos",
			  'BI_Aplicación'[Atributo] = "Consumo Real",
			   DATESBETWEEN(Fechas[Date], DATE(YEAR(TODAY()) -1,01,01), DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))))
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 83b96e8b-a751-41f5-9eeb-4d58daf623e6

	measure Total_LB_Uts_Real_Valor = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Evolutivos", 'BI_Aplicación'[Atributo] = "Consumo Real")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: e7e35359-cecf-49b6-af4f-ce9790b27d7c

	measure Comparación_Consumo_% =
			([Línea Base Real consumida €] - CALCULATE(SUM('BI_Aplicación'[Valor]),
			 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos",
			  'BI_Aplicación'[Atributo] = "Consumo Real",
			   DATESBETWEEN(Fechas[Date], DATE(YEAR(TODAY()) -1,01,01), DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))))) / CALCULATE(SUM('BI_Aplicación'[Valor]),
			 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos",
			  'BI_Aplicación'[Atributo] = "Consumo Real",
			   DATESBETWEEN(Fechas[Date], DATE(YEAR(TODAY()) -1,01,01), DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 0a12c727-0286-4e1b-a337-238c716661c8

	measure 'Presupuesto Real Uts' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Evolutivos", 'BI_Aplicación'[Atributo] = "Presupuesto Uts")
		formatString: #,0.00
		lineageTag: 3da25dd7-27c4-4d0d-9b00-ff54769772a1

	measure Total_LB_Uts_Real_Aplicaciones = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Evolutivos", 'BI_Aplicación'[Atributo] = "Consumo Real Uts")
		formatString: #,0.00
		lineageTag: 8e69ad12-2604-4f39-a8ae-a4ef6110997c

	measure UTS_restantes = [Presupuesto Real Uts] - [Total_LB_Uts_Real_Aplicaciones]
		formatString: #,0.00
		lineageTag: 63d72486-5fd8-4113-82f4-5a13593e194c

	measure UTS_Disponibles_Ppto = [Presupuesto Real Uts] - [Total_LB_Uts_Real_Aplicaciones] - [LB proyectada Evo] - 442.75
		lineageTag: 4ed55c35-d8bf-492b-8b7c-95389794a28e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Coste UT LB Objetivo' = [Linea_Base_esperada_total] / [UTS_totales_disponibles]
		lineageTag: 96d83a51-c2da-41ae-aa0a-1de45be40edb

	measure UTS_totales_disponibles = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Atributo] = "Línea Base Objetivo Uts", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos", ALL('BI_Aplicación'[Periodo]))
		lineageTag: 128c688e-c5ee-43da-b265-ce4492587a58

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure UTS_restantes_mensual = [Presupuesto Real Uts] / 12
		formatString: #,0.00
		lineageTag: 93b2acda-83c6-4ef7-a795-a9a1068bdad2

	measure Total_LB_Uts_Real_Aplicaciones_mes = [Total_LB_Uts_Real_Aplicaciones] / [Meses_Restantes_Año_12_2]
		formatString: #,0.00
		lineageTag: dd117d1d-2c8b-4d6b-a1ee-f2ecdf14663b

	measure 'Meses año actual' = MONTH(CALCULATE(MAX('BI_Aplicación'[Periodo]), 'BI_Aplicación'[Atributo] = "Consumo Real", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos"))
		formatString: 0
		lineageTag: b0d3b23c-11df-412a-abf7-77b176eb59e9

	measure 'UTS_mes_disponibles restantes' = DIVIDE([UTS_restantes] , [Meses_Restantes_Año_1], 0)
		formatString: #,0.00
		lineageTag: 6efd7a40-da77-4b4d-9850-38896f68b49e

	measure Línea_Real_Consumida_Uts_SamePeriodLastYear = ```
			[Total_LB_Uts_Real_Aplicaciones] - 
			
			CALCULATE(SUM('BI_Aplicación'[Valor]),
			 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos",
			  'BI_Aplicación'[Atributo] = "Consumo Real Uts",
			   DATESBETWEEN(Fechas[Date], DATE(YEAR(TODAY()) -1,01,01), DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))))
			```
		formatString: #,0.00
		lineageTag: 22538eba-fac9-4906-b6aa-f7e4f67faec4

	measure Total_LB_Uts_Real_Valor_C = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Correctivos", 'BI_Aplicación'[Atributo] = "Consumo Real")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 0d7a9413-2d0a-4998-ae4c-bc880a600bcc

	measure 'Línea Base Real consumida €_C' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] = "Correctivos", 'BI_Aplicación'[Atributo] = "Consumo Real")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: e6204b39-f0a1-4cb9-aed4-9b97d6c73270

	measure 'Coste Fijo' = [Total_LB_UTs_C] * [Euro_Hora_Estimado_C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: e7e9462a-87e3-44f6-8847-2fe21823c5c7

	measure Linea_Base_esperada_total_mes_C_2 = ([Linea_Base_esperada_total_mensual_C] * [Meses_Restantes_Año_12])
		lineageTag: dcddc7f6-fa2b-45f5-874b-a7bb68a13d3c

	measure Linea_Base_esperada_total_mensual_C = CALCULATE(SUM('BI_Aplicación'[Valor])/12, 'BI_Aplicación'[Atributo]="Línea Base Objetivo", 'BI_Aplicación'[Descripción Ámbito] = "Correctivos")
		lineageTag: e3b4ea76-5340-4655-8e96-df1247787ae2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Consumido_PrecioHoraContratado = [Total_LB_Uts_Real_Aplicaciones_C] * [Precio_Hora_Contratado]
		lineageTag: 51ea1d46-7f8c-48b1-a1ee-c0a4e880fc85

	measure Precio_Hora_Contratado = [Linea_Base_esperada_total_C] / [UTS_totales_disponibles_ C]
		lineageTag: 4ba90c37-7351-4169-905f-21408cfde553

	measure Linea_Base_esperada_total_C = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Atributo]="Línea Base Objetivo", 'BI_Aplicación'[Descripción Ámbito] = "Correctivos")
		lineageTag: 6f6fa386-c9f5-42bf-97b2-f22ee6e9bdda

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'UTS_totales_disponibles_ C' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Atributo] = "Línea Base Objetivo Uts", 'BI_Aplicación'[Descripción Ámbito] = "Correctivos", ALL('BI_Aplicación'[Periodo]))
		lineageTag: ebcbd4f9-540d-486d-8b6d-80167adaaff7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Total_LB_Uts_Real_Aplicaciones_C = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Correctivos", 'BI_Aplicación'[Atributo] = "Consumo Real Uts")
		formatString: #,0.00
		lineageTag: 6bd62bea-5d5c-4a76-9e17-7aa10f93e3d7

	measure Ahorro = [Coste Fijo] - [Gasto_Hipotetico_C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: ea741a4e-ee0a-42ac-a66a-410864241c65

	measure Euro_Hora_Estimado_C = [Linea_Base_esperada_total_C] / [Total_LB_UTs_C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 5541ab07-6cfd-4198-908b-d721fc5955e6

	measure Total_LB_UTs_C =
			CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] = "Correctivos", 'BI_Aplicación'[Atributo] = "Línea Base Objetivo Uts", FILTER(ALL('BI_Aplicación'[Periodo]), IF(
			    YEAR(TODAY()) > YEAR(MAX('BI_Aplicación'[Periodo])),
			    12,
			    MONTH('BI_Aplicación'[Periodo]) <= MONTH(TODAY()))
			)
			)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 6fd622d9-fff8-4a12-af38-e3b3cfe2ce7e

	measure Comparación_Euro_Hora = ```
			IF([Euro_Hora_Correctivo_C] >= [Euro_Hora_Estimado_C], "#0EB194", "#CD5C5C")    
			```
		lineageTag: f26a23db-f376-4549-887a-af4c61e135c4

	measure Euro_hora_Correctivo_C = [Línea Base Real consumida €_C] / [Total_LB_Uts_Real_Aplicaciones_C]
		lineageTag: b41dd9c2-4ae4-4095-8285-00d90d4c28ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Coste_FIjo_Horas_Incurridas = DIVIDE([Linea_Base_esperada_total_C], [Total_LB_Horas_Real_Aplicaciones_C], 0)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: b474cec7-38f3-42e7-8bbf-0d7757adbf05

	measure Tendencia_LB_C = DIVIDE('BI_Aplicación'[Linea Base Real Consumida Total], [Meses_LB_Real_Total], 0)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: ee0f5ef1-ba94-4478-8618-98290391488a

	measure 'Linea Base Real Consumida Total' = CALCULATE('BI_Aplicación'[Línea Base Real consumida €], ALL(Fechas))
		lineageTag: 4b0dfbdb-8ced-4f9d-9271-56ae00901399

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Meses_LB_Real_Total = CALCULATE((DATEDIFF(FIRSTDATE('BI_Aplicación'[Periodo]), LASTDATE('BI_Aplicación'[Periodo]), MONTH) +1),'BI_Aplicación'[Atributo] = "Consumo Real", ALLEXCEPT('BI_Aplicación','BI_Aplicación'[Área],'BI_Aplicación'[SubÁrea],'BI_Aplicación'[Aplicación]), ALL(Fechas))
		formatString: 0
		lineageTag: d8491635-a566-4cd9-abeb-d605bac579ed

	measure 'UTS_restantes C' = [UTS_totales_disponibles_ C] - [Total_LB_Horas_Real_Aplicaciones_C]
		formatString: #,0.00
		lineageTag: f5214e9b-23bd-44f8-b13b-975854d9c33d

	measure Tendencia_Uts_C = DIVIDE([Total_LB_Uts_Real_Aplicaciones_C], [Meses_Restantes_Año_12_2])
		formatString: 0.00
		lineageTag: f6b3c5b3-6196-44f1-9af9-11885fe166da

	measure Ppto_Restante_Año = [Presupuesto Real €] - [Línea Base Real consumida €]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: a608c29d-3434-488e-a55b-5096a007426f

	measure Presupuesto€_Mes = [Presupuesto Real €] / 12
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 81fe4c25-5069-44e7-b047-fa1889d89643

	measure Meses_Restantes_Año_12_2 =
			IF(
			    YEAR(TODAY()) > YEAR(MAX('BI_Aplicación'[Periodo])),
			    12,
			    MONTH(TODAY()))
		formatString: 0
		lineageTag: 31a3d297-9ee2-451c-959a-0880f2ea5ab5

	measure Uts_desviacion-proyectado = [UTS_totales_disponibles] - ([Total_LB_Uts_Real_Aplicaciones_mes] * 12)
		lineageTag: 66d134c7-13a8-4bb5-a12b-65ca0832e361

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Gasto_Hipotetico_C = [Euro_Hora_Estimado_C] * [Total_LB_Horas_Real_Aplicaciones_C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: a0b4f200-322d-4f7f-906e-c281d3f5d686

	measure Total_LB_Horas_Real_Aplicaciones_C = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Correctivos", 'BI_Aplicación'[Atributo] = "Consumo Real Uts")
		formatString: 0.00
		lineageTag: 433c9060-46a6-4919-9b83-1d7a4e784eca

	measure Marcador_Ahorro = IF([Coste Fijo] > [Gasto_Hipotetico_C], "#0EB194", "#CD5C5C")
		lineageTag: aae10043-5df0-4bee-8f69-5a5528e9001c

	measure Tendencia_Color = IF([Total_LB_Horas_Real_Aplicaciones_C] > [Linea_Base_esperada_total_C], 0, 1)
		formatString: 0
		lineageTag: 25c0580a-e5a1-4788-8fb1-c95e78955dc4

	measure 'LB proyectada Evo' = ```
			CALCULATE(SUM('BI_Aplicación'[Valor]), 
			'BI_Aplicación'[Atributo]="Línea Base Proyectada Uts Suma", 
			'BI_Aplicación'[Descripción Ámbito] = "Evolutivos")
			```
		formatString: #,0.00
		lineageTag: 83d2f8d8-5df9-48d1-b58d-662461608578

	measure 'LB proyectada Evo €' = ```
			CALCULATE(SUM('BI_Aplicación'[Valor]), 
			'BI_Aplicación'[Atributo]="Línea Base Proyectada Suma", 
			'BI_Aplicación'[Descripción Ámbito] = "Evolutivos")
			```
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 70bee312-7bb1-45a9-b0a9-730721815eec

	column 'Servicio TIC'
		dataType: string
		lineageTag: 41b5b2ba-0cc9-4ac9-ac2a-ca2e205a8b50
		summarizeBy: none
		sourceColumn: Servicio TIC

		annotation SummarizationSetBy = Automatic

	column Ámbito
		dataType: string
		lineageTag: 359f367e-537a-4ea3-9aff-2e51a6e24dcd
		summarizeBy: none
		sourceColumn: Ámbito

		annotation SummarizationSetBy = Automatic

	column 'Descripción Ámbito'
		dataType: string
		lineageTag: 15f7244b-b7e0-4d60-8596-54880a9ce6e1
		summarizeBy: none
		sourceColumn: Descripción Ámbito

		annotation SummarizationSetBy = Automatic

	column Área
		dataType: string
		lineageTag: febb6900-086f-40e4-8450-44994aa6e837
		summarizeBy: none
		sourceColumn: Área

		annotation SummarizationSetBy = Automatic

	column SubÁrea
		dataType: string
		lineageTag: 65500a64-eaff-4afd-924f-ac1c4ed2e722
		summarizeBy: none
		sourceColumn: SubÁrea

		annotation SummarizationSetBy = Automatic

	column Aplicación
		dataType: string
		lineageTag: 43aced91-3ac5-4fdb-8769-476245beb656
		summarizeBy: none
		sourceColumn: Aplicación

		annotation SummarizationSetBy = Automatic

	column Periodo
		dataType: dateTime
		formatString: Long Date
		lineageTag: 67261d18-9ef9-4081-9bd1-2c1e56a1feb9
		summarizeBy: none
		sourceColumn: Periodo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Atributo
		dataType: string
		lineageTag: 1272ec9c-52f8-4305-b5a3-f6b01c42c26d
		summarizeBy: none
		sourceColumn: Atributo
		sortByColumn: Orden_Leyenda

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: double
		lineageTag: 6ac2c311-dafd-4a24-bd69-5d7778e4fe74
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Atributo - Leyenda'
		dataType: string
		lineageTag: 9bd896a3-b6ab-4009-81bd-07ed4bac60f0
		summarizeBy: none
		sourceColumn: Atributo - Leyenda

		annotation SummarizationSetBy = Automatic

	column Orden_Leyenda
		dataType: double
		lineageTag: 4457d31b-1994-4f63-8c0f-53e76cde12a1
		summarizeBy: sum
		sourceColumn: Orden_Leyenda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition BI_Aplicación-569bb141-c6d6-40ab-930e-bbecc894a588 = m
		mode: import
		queryGroup: 'Línea Base'
		source = ```
				let
				
				    Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/Archivos comunes/03. Línea Base Energía/Líneas Base Energía v0.2 - Nuevos Presupuestos" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),   
				    BI_Aplicación_Sheet = Origen{[Item="CdM_Movilidad",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(BI_Aplicación_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Servicio TIC", type text}, {"Ámbito", type text}, {"Descripción Ámbito", type text}, {"Área", type text}, {"SubÁrea", type text}, {"Aplicación", type text}, {"Línea Base Real", type number}, {"Línea Base Proyectada", type number}, {"Línea Base Real Uts", type number}, {"Línea Base Proyectada Uts", type number}, {"Periodo", type date}, {"Tarifa", Int64.Type}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Tarifa"}),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Columnas quitadas",{{"Línea Base Real", type number}, {"Línea Base Proyectada", type number}, {"Presupuesto", type number}}),
				    #"Columna de anulación de dinamización" = Table.UnpivotOtherColumns(#"Tipo cambiado3", {"Servicio TIC", "Ámbito", "Descripción Ámbito", "Área", "SubÁrea", "Aplicación", "Periodo"}, "Atributo", "Valor"),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columna de anulación de dinamización",{{"Valor", type number}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado2","Línea Base Real Uts","Consumo Real Uts",Replacer.ReplaceText,{"Atributo"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Línea Base Real","Consumo Real",Replacer.ReplaceText,{"Atributo"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado1",{{"Valor", type number}}),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Tipo cambiado1", "Atributo", "Atributo - Copia"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna duplicada",{{"Atributo - Copia", "Atributo - Leyenda"}}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Columnas con nombre cambiado","Línea Base Objetivo","Fijo Correctivo",Replacer.ReplaceText,{"Atributo - Leyenda"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","Consumo Real","Gasto Correctivo Hipotético",Replacer.ReplaceText,{"Atributo - Leyenda"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","Fijo Correctivo Uts","Fijo Correctivo Horas",Replacer.ReplaceText,{"Atributo - Leyenda"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","Gasto Correctivo Hipotético Uts","Gasto Correctivo Hipotético Horas",Replacer.ReplaceText,{"Atributo - Leyenda"}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Valor reemplazado5", "Orden_Leyenda", each if [Atributo] = "Línea Base Objetivo" then 1 else if [Atributo] = "Línea Base Actual" then 2 else if [Atributo] = "Línea Base Máxima" then 3 else if [Atributo] = "Consumo Real" then 4 else if [Atributo] = "Línea Base Objetivo Uts" then 5 else if [Atributo] = "Línea Base Actual Uts" then 6 else if [Atributo] = "Línea Base Máxima Uts" then 7 else if [Atributo] = "Consumo Real Uts" then 8 else if [Atributo] = "Presupuesto" then 9 else null, type number)
				in
				    #"Columna condicional agregada"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

