table 'Parametros KGI17'
	excludeFromModelRefresh
	lineageTag: db69a12b-bc7c-490d-8590-ccf9eb27bcdd

	column 'Peso del KGI %'
		dataType: double
		lineageTag: b9530e63-949c-4f07-b959-71468a5a1fd4
		summarizeBy: sum
		sourceColumn: Peso del KGI %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Puntos de KGI17'
		dataType: int64
		formatString: 0
		lineageTag: 56bcb170-a232-4b20-9ef4-77852b356e0c
		summarizeBy: sum
		sourceColumn: Puntos de KGI17

		annotation SummarizationSetBy = Automatic

	column KGI
		dataType: string
		lineageTag: ddcc6a24-a86d-4ae6-a3c7-d0f727c29cc0
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	column 'Tasa de aprobación objetivo %'
		dataType: double
		lineageTag: 40a0835a-ce15-4656-aebd-1d879b8fc083
		summarizeBy: sum
		sourceColumn: Tasa de aprobación objetivo %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'No. Mínimo de propuestas por trimestre'
		dataType: int64
		formatString: 0
		lineageTag: 397322d3-8dba-4a72-8af0-2d857bca2151
		summarizeBy: sum
		sourceColumn: No. Mínimo de propuestas por trimestre

		annotation SummarizationSetBy = Automatic

	partition 'Parametros KGI17-1a7af5b9-e27d-4477-b400-b3039eafa313' = m
		mode: import
		queryGroup: Parametros
		source =
				let
				    Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/AMS_MOV/Ficheros del Servicio/" & AMS_IAR_CDM_ & "Parámetros KGIs" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),
				    #"Parametros KGI1-7_Sheet" = Origen{[Item="Parametros KGI1-7",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Parametros KGI1-7_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Tasa de aprobación objetivo %", Percentage.Type}, {"No. Mínimo de propuestas por trimestre", Int64.Type}, {"Peso del KGI %", Percentage.Type}, {"Puntos de KGI17", Int64.Type}, {"KGI", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

