table 'Parametros KGI11'
	excludeFromModelRefresh
	lineageTag: dc1f5127-3756-4b31-8555-4def456b5df6

	column Prioridad
		dataType: string
		lineageTag: 8a8b22dc-3740-4683-b0bc-cb266017c4fb
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'T. Resolución Máximo (Jornadas laborales)'
		dataType: int64
		formatString: 0
		lineageTag: ab20d86a-cc06-4ee8-bfc4-d806d9cb1f41
		summarizeBy: sum
		sourceColumn: T. Resolución Máximo (Jornadas laborales)

		annotation SummarizationSetBy = Automatic

	column '% cumplimiento Objetivo'
		dataType: double
		lineageTag: 7eb207df-9675-4cf0-9a70-37947bc7ade4
		summarizeBy: sum
		sourceColumn: % cumplimiento Objetivo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pesos %'
		dataType: double
		lineageTag: 7a5d9e48-df1b-4883-96c8-1a306ca07a2d
		summarizeBy: sum
		sourceColumn: Pesos %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Parametros KGI11-efbac5a5-2860-4c30-9a16-04cd7ccd28f6' = m
		mode: import
		queryGroup: Parametros
		source =
				let
				    Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/AMS_MOV/Ficheros del Servicio/" & AMS_IAR_CDM_ & "Parámetros KGIs" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),
				    #"Parametros KGI1-1_Sheet" = Origen{[Item="Parametros KGI1-1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Parametros KGI1-1_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Prioridad", type text}, {"T. Resolución Máximo (Jornadas laborales)", Int64.Type}, {"% cumplimiento Objetivo", type number}, {"Pesos %", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

