table 'Parametros KGI13'
	excludeFromModelRefresh
	lineageTag: fbb404da-d068-42d9-b862-7dd95f0980e2

	column 'Prioridad '
		dataType: string
		lineageTag: 85d85e42-9adc-4bda-879c-e0a10c061eee
		summarizeBy: none
		sourceColumn: "Prioridad "

		annotation SummarizationSetBy = Automatic

	column 'Puntos de KGI13'
		dataType: int64
		formatString: 0
		lineageTag: cf28ead5-d497-4de6-a76b-48b01b937058
		summarizeBy: sum
		sourceColumn: Puntos de KGI13

		annotation SummarizationSetBy = Automatic

	column KGI
		dataType: string
		lineageTag: 14aec1b4-1161-4d23-af47-e581c415de00
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	column 'Cumplimiento Objetivo %'
		dataType: double
		lineageTag: 0d5f227c-b7ee-450c-88ea-3de102800962
		summarizeBy: sum
		sourceColumn: Cumplimiento Objetivo %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa máxima permitida %'
		dataType: double
		lineageTag: 7129fb8f-8e63-48b3-8f0c-b491eb94473f
		summarizeBy: sum
		sourceColumn: Tasa máxima permitida %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Peso del KGI %'
		dataType: double
		lineageTag: cc9d3a2b-065e-4969-8342-20054f2b1efd
		summarizeBy: sum
		sourceColumn: Peso del KGI %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Parametros KGI13-527c0736-f334-49f9-95fb-a3a2c4ab5dde' = m
		mode: import
		queryGroup: Parametros
		source =
				let
				    Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/AMS_MOV/Ficheros del Servicio/" & AMS_IAR_CDM_ & "Parámetros KGIs" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),
				    #"Parametros KGI1-3 (2)_Sheet" = Origen{[Item="Parametros KGI1-3 (2)",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Parametros KGI1-3 (2)_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Prioridad ", type text}, {"Tasa máxima permitida %", type number}, {"Cumplimiento Objetivo %", type number}, {"Peso del KGI %", type number}, {"Puntos de KGI13", Int64.Type}, {"KGI", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

