table 'PRO - Alegaciones del Servicio KGI22'
	lineageTag: 7c13bda4-0acb-47bd-abc9-cf4fe80d8af3

	column ID
		dataType: string
		lineageTag: 871fe82b-2a96-4a22-b374-576930d7666e
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Entrada alegada'
		dataType: string
		lineageTag: 1c745c36-e071-4f05-9d89-b04697efd134
		summarizeBy: none
		sourceColumn: Entrada alegada

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: 0837066b-d82e-43a1-8db0-ffab9c8544e2
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: string
		lineageTag: 9056b872-3d1a-4004-8bde-b10dc634397f
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		annotation SummarizationSetBy = Automatic

	column Clasificación
		dataType: string
		lineageTag: b7660743-d006-4f0e-b8c5-dcfe5febcef0
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: a697d879-95be-4cf5-ba6f-5e26ce8ef54a
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: 7dca2bc5-4273-4e0f-bb54-b5656a98efd3
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: c8a606be-f0dd-43a5-966e-c9b65b93377c
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: 2433f608-67a5-4982-b9eb-65f0cae9d756
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0b2c547f-9ff7-47e3-80e4-2af387a33cda
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado - Copy

		variation Variación
			isDefault
			relationship: 1c56f23f-f125-4424-ac5c-6d70bedc7da0
			defaultHierarchy: LocalDateTable_c56f3f91-7a68-4935-89c7-b9223bd66da4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Comentarios AE'
		dataType: string
		lineageTag: 83d9bcf4-b10f-4683-a433-ca6f0a262399
		summarizeBy: none
		sourceColumn: Comentarios AE

		annotation SummarizationSetBy = Automatic

	column Columna1
		dataType: string
		lineageTag: a8afbd43-5ad7-401e-a645-38a7df6a7699
		summarizeBy: none
		sourceColumn: Columna1

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI22-a82fb82a-d193-4cf7-930a-5c80b5df6989' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Source = #"PRO - Alegaciones del Servicio",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([ANS] = "KGI 2-2"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

