table 'PRO - Jira - Entregables con SLA'
	lineageTag: 4ea1675a-826c-435d-aa31-7c9a4f40ee3d

	column 'Issue Type'
		dataType: string
		lineageTag: f54d183f-c8f4-4370-8527-dbcf992a63b6
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 615766da-7166-4bf5-a3a8-ba1d88827797
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 91d7d336-1b68-45b7-a12a-18ea5c989e4d
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Components
		dataType: string
		lineageTag: bef48a4c-f87e-41ee-b58f-894d15b7b371
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 1b8e4062-1f1a-4a42-88a9-300446d1de55
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 61c1473b-b80b-49d4-bc89-ab826b177f3c
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 46646271-6799-44a0-b1b1-0c7b8e887bd7
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 7de33046-c339-4bbd-a0d6-e38ec51437aa
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'End Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: afa006cf-2e81-412a-983a-94a45e45421a
		summarizeBy: none
		sourceColumn: End Date

		variation Variation
			isDefault
			relationship: d4b3148d-e3f0-408f-ad66-e40bd535cfe3
			defaultHierarchy: LocalDateTable_1c4405a5-e746-4d71-8b52-f0037ad20c4f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'End Real Date'
		dataType: string
		lineageTag: 74da2e97-7da0-42f2-a139-9a390ad5e662
		summarizeBy: none
		sourceColumn: End Real Date

		annotation SummarizationSetBy = Automatic

	column 'Linked Issues'
		dataType: string
		lineageTag: d0d3d5f3-2ca8-4203-b84b-d98120b99354
		summarizeBy: none
		sourceColumn: Linked Issues

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 27882181-d4f9-4020-9822-4f84f6762f1d
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: 5e25ddb5-9633-4695-87ca-d22ae8b5a8d4
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: 9b72112f-6fff-48bc-94a7-d04e91d59ccc
			defaultHierarchy: LocalDateTable_f1be6c47-0ab0-498b-8cf5-fb6ced484fb1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Rechazado
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6eb800ba-9985-4137-b482-01e772796f8c
		summarizeBy: none
		sourceColumn: Rechazado

		annotation SummarizationSetBy = Automatic

	column 'Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2bb8252c-495b-45c4-8427-d692897bf6ba
		summarizeBy: none
		sourceColumn: Resolved - Copy

		variation Variation
			isDefault
			relationship: 838891c5-1c00-400c-a468-8eb757a49a38
			defaultHierarchy: LocalDateTable_4ae39781-4ebd-494e-8cb2-49cfae8e3f40.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: aed39ef8-e399-4ccc-a7c5-932a28d82fb5
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Deliverable type'
		dataType: string
		lineageTag: 097345e6-5ab5-4c02-91e4-fadaa8da45e2
		summarizeBy: none
		sourceColumn: Deliverable type

		annotation SummarizationSetBy = Automatic

	column 'Approval status'
		dataType: string
		lineageTag: d6f256b3-9a1c-4117-aed8-528addcd920e
		summarizeBy: none
		sourceColumn: Approval status

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 6b4956fa-332b-4bcd-a86b-c8ec189688fd
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Entregables con SLA-5c54ffc6-de48-4fc9-8b50-725b12f7f0a8' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/AMS_MOV/Ficheros del Servicio/AMS_IAR_CDM_SLA_I_Entregables, Pruebas y Defectos" & xlsx, //& AMS_IAR_CDM_ & "Parámetros KGIs" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),
				    #"Entregables Rechazados_Sheet" = Origen{[Item="Entregables",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Entregables Rechazados_Sheet", [PromoteAllScalars=true]),
				    
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Issue Type", type text}, {"Deliverable type", type text}, {"Project", type text}, {"Key", type text}, {"Components", type text}, {"Summary", type text}, {"Priority", type text}, {"Assignee", type text}, {"Status", type text}, {"Approval status", type text}, {"End Date", type datetime}, {"End Real Date", type text}, {"Linked Issues", type text}, {"Sub-tasks", type text}, {"Resolved", type datetime}, {"Rechazos", type logical}}),
				
				    //Homgeneiza la prioridad proveniente de Jira a los valores de ANS
				    #"AllReplace" = [#"Highest" = "Grave", #"High" = "Grave", #"Medium" = "Grave",#"Low" = "Leve",#"Lowest" = "Leve"],    
				    #"Replaced Value" = Table.TransformColumns(#"Changed Type",{{"Priority",each Record.FieldOrDefault(AllReplace,_,_)}}),
				
				    //Renombra la Prioridad por "Tipo" de incumplimiento como dice el ANS
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"Priority", "Tipo"}, {"Rechazos", "Rechazado"}}),
				
				    //Filtra por solo aplicaciones correspondientes a iAR
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Components] 
				        = "EM: DAT"             or [Components] 
				        = "EM: MXM"             or [Components] 
				        = "EM: OAT"             or [Components] 
				        = "EM: WTM"             or [Components]
				        = "EM: RDO Movil"       or [Components] 
				        = "RDO"                 or [Components]  
				        = "HTFV"                or [Components]  
				        = "IOC"                 or [Components]  
				        = "MXM-HTVF"            or [Components]  
				        = "Web Calendario de Guardias")),
				
				    //Copia el campo Resolved para relacionar a la tabla fechas
				    #"Duplicated Column" = Table.DuplicateColumn(#"Filtered Rows", "Resolved", "Resolved - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Resolved - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Resolved - Copy", Date.StartOfMonth, type date}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Calculated Start of Month",null,false,Replacer.ReplaceValue,{"Rechazado"}),
				
				    //Une con las alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value1", {"Key"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"Estado"}, {"PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Rechazado" si la alegación es aceptada
				    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns1",each [Rechazado],each if [Estado_Alegación] = "1 - Aprobada" then "FALSE" else [Rechazado],Replacer.ReplaceValue,{"Rechazado"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value2",{{"Rechazado", type logical}})
				
				in
				    #"Changed Type1"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegación

