table 'PRO - Incidencias con SLA (NY y MAD)'
	lineageTag: 10b1a653-bc15-4025-b1f4-130c1271a17d

	column Número
		dataType: string
		lineageTag: 47c1f7e8-3cd1-410e-9628-287d86eec366
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: ce01860d-e7b8-491b-9c0f-2239dba65cc7
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: 8184637b-3fbb-4b02-ba8e-89397437fd65
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 55c0cf92-bba3-4224-940b-d1f43128cbce
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 0f0b81e3-234e-4f23-90df-2701c41012d6
		summarizeBy: none
		sourceColumn: Abierto

		variation Variation
			isDefault
			relationship: 8dea28c3-c966-4da4-8865-17f378c28358
			defaultHierarchy: LocalDateTable_2ccb886c-8264-42d8-ad56-c3c6b25a9f4f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: ff8b5e5b-0a1b-4b3e-adad-26a99b121155
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: 5a2471d7-7ea4-4b25-947b-52b7fbedaad2
			defaultHierarchy: LocalDateTable_209201f4-7449-48d3-bbcb-0f0bfc302049.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6d2744d1-57ec-4671-a710-0145d334cdaa
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variación
			isDefault
			relationship: 97dbc0fc-fa44-493c-8a83-2efb93948800
			defaultHierarchy: LocalDateTable_bf271174-3d26-4d57-9f64-c770bd59cca3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 901ff8c4-04e2-4779-a531-ed7223534e23
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 70d49a69-9cb6-4dba-a017-ad1f447225f4
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f5f74b0d-3544-442d-9fd7-7c52c3dffdfe
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9160fa9b-e210-4324-9bb9-687fece1c5d0
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variación
			isDefault
			relationship: 9f845fd2-96ef-43b4-9f94-eb5fba9915e2
			defaultHierarchy: LocalDateTable_7ad0c178-9126-40dd-9ea3-5858445391dd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 4ff83743-44fa-4eac-ac00-9a0359e46743
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 447f7fc6-15f6-439e-9211-23d0304dd759
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: a4368b22-37f3-4ab4-9fa7-906038c2d9e5
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: 21af3bb8-2242-4a27-b5f1-2253123e7160
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 02fa262c-560e-4ffd-be43-127900f2eeeb
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Infringidos Numérico' = IF('PRO - Incidencias con SLA (NY y MAD)'[Infringido] = TRUE(),1,0)
		formatString: 0
		lineageTag: 7c25800e-a002-4324-ab0f-bb5777e3726e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'No Infringidos Numerico' = IF('PRO - Incidencias con SLA (NY y MAD)'[Infringido] = TRUE(),0,1)
		formatString: 0
		lineageTag: 30c17287-92eb-4da5-a0f5-84c74b45d6f8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Mes = MONTH('PRO - Incidencias con SLA (NY y MAD)'[Cerrado])
		formatString: 0
		lineageTag: 1b8b3adc-04e8-496d-a527-83fc435441e4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Año = YEAR('PRO - Incidencias con SLA (NY y MAD)'[Cerrado])
		formatString: 0
		lineageTag: 4c0da070-34e4-4d21-9c27-1995e624d431
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Reabierta Numérica' = IF('PRO - Incidencias con SLA (NY y MAD)'[Reabierta] = "TRUE",1,0)
		formatString: 0
		lineageTag: 23bf0b4a-4cbb-487b-815d-a4f34286bbc5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column CerradoFecha = 'PRO - Incidencias con SLA (NY y MAD)'[Cerrado].[Date]
		formatString: dd/mm/yyyy
		lineageTag: dfd42e3f-3b52-4d09-89a8-dc9f019bdab0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column AbiertoFecha = 'PRO - Incidencias con SLA (NY y MAD)'[Abierto].[Date]
		lineageTag: c8866132-3f2e-4891-83bd-38bbcd41b25a
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 8098c35d-8a66-4109-949e-c7d330cd2d4f
			defaultHierarchy: LocalDateTable_171aad4c-05dd-4c25-94a5-c61b530c1fa0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 537728c2-e253-438a-b9ae-9fad9fc44ce0
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		variation Variation
			isDefault
			relationship: a66d5235-c403-4232-8c6e-07fe88906a75
			defaultHierarchy: LocalDateTable_4607465a-a880-4db8-b384-5bea228541a6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración D:HH:MM:SS' =
			
			VAR VDUR21 = 'PRO - Incidencias con SLA (NY y MAD)'[Duración real]
			  RETURN INT
			    (VDUR21/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21,60)),2)
		lineageTag: 55f022e7-c793-4a20-8028-0c13340a7e4a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: b36d4aab-66e5-48bd-80d4-76eb0f8fcc9b
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: caf3e1a9-c2af-46dc-9f69-1d79bf5f7b39
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Duración excedida'
		dataType: string
		lineageTag: 2c0e8642-187b-47a2-af91-71d3c8f5f794
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column 'Duración_EX D:HH:MM:SS' =
			
			VAR VDUR21_EX = 'PRO - Incidencias con SLA (NY y MAD)'[Duración excedida]
			  RETURN INT
			    (VDUR21_EX/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_EX/3600,24)),2)&" HH"
		lineageTag: eba0afc5-f5b5-401a-8a48-4b9c62350ff2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 20f1c4b8-376f-423b-871f-303787b5e2a2
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: c4918e96-dbbe-4828-a694-ddd91864fab0
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA (NY y MAD)'[Número])
		lineageTag: 00e2694f-d912-41f0-b7ca-cebf2196ed29
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: ec0a8ce2-0e18-4007-8626-1246d9ed2b0e
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	hierarchy 'Reabierta Jerarquía'
		lineageTag: c818846b-01a8-4e50-ac4a-8abc714d5f3b

		level Reabierta
			lineageTag: 83750a8b-cdf9-4539-8c51-5435bfef956b
			column: Reabierta

		level Sistema
			lineageTag: e034f671-fc43-4846-92f0-ab3384006867
			column: Sistema

	partition 'PRO - Incidencias con SLA (NY y MAD)-0372dffc-56a7-4dc5-b546-b758c41a1f06' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/AMS_MOV/Ficheros del Servicio/AMS_IAR_CDM_SLA_II_Incidencias (SN Madrid)" & xlsx, //& AMS_IAR_CDM_ & "Parámetros KGIs" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Número", type text}, {"Breve descripción", type text}, {"Subcategoría", type text}, {"Prioridad", type text}, {"Abierto", type datetime}, {"Cerrado", type datetime}, {"Fecha de resolución", type datetime}, {"Duración", Int64.Type}, {"Duración real", Int64.Type}, {"Infringido", type logical}, {"Tiempo original de incumplimiento", type datetime}, {"Estado", type text}, {"Estado SLA", type text}, {"Código de cierre", type text}, {"Reabierta", type logical}, {"Tipo de solución", type text}, {"Duración SLA", Int64.Type}, {"Porcentaje de negocio trascurrido", Int64.Type}}),
				    
				        #"Appended Query" = Table.Combine({#"Tipo cambiado", #"PRO - Incidencias con SLA (NY)"}),    
				       
				    #"Filtered Rows" = Table.SelectRows(#"Appended Query", each (
				        [Código de cierre] = "No user response" or 
				        [Código de cierre] = "Solucionado en remoto" or 
				        [Código de cierre] = "Solucionado nivel 2" or 
				        [Código de cierre] = "solucionado ON-SITE" or 
				        [Código de cierre] = "Solucionado Temporalmente" or
				        [Código de cierre] = "Solucionado mail" or
				        [Código de cierre] = "Solucionado por teléfono" or
				        [Código de cierre] = "Solucionado (solución temporal)" or 
				        [Código de cierre] = "Solucionado (de forma permanente)" or
				        [Código de cierre] = "Solucionado remotamente (solución temporal)" or 
				        [Código de cierre] = "Solucionado remotamente (de forma permanente)")),
				
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each not Text.StartsWith([Estado], "Cancelado")),
				    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each [Estado SLA] <> "Cancelado"),
				    #"Filtered Rows3" = Table.SelectRows(#"Filtered Rows2", each ([Cerrado] <> null)),
				
				    #"Duplicated Column" = Table.DuplicateColumn(#"Filtered Rows3", "Cerrado", "Cerrado - Copy"),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Duplicated Column",{{"Cerrado - Copy", Date.StartOfMonth, type datetime}}),
				    #"Extracted Date" = Table.TransformColumns(#"Calculated Start of Month",{{"Cerrado - Copy", DateTime.Date, type date}}),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Extracted Date",{{"Subcategoría", "Sistema"}}),
				
				    //Une con tabla de alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Número"}, #"PRO - Alegaciones del Servicio KGI24", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"ANS", "Estado"}, {"PRO - Alegaciones del Servicio.ANS", "PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.ANS", "ANS_Alegado"}, {"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				
				    //Realiza la correcciones si la alegación es aceptada
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1",each [Prioridad],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "11 - KGI 2-4" then "Alta" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"Prioridad", type text}}),
				
				    //Nuevo campo de Duración excedida, respecto a SLA
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Duración excedida", 
				    each if ([Duración real]-[Duración SLA])<0 then 0 else 
				    ([Duración real]-[Duración SLA])),
				
				    #"Divided Column" = Table.TransformColumns(#"Added Custom", {{"Porcentaje de negocio trascurrido", each _ / 100, Percentage.Type}}),
				    #"Filas filtradas" = Table.SelectRows(#"Divided Column", each [Número] <> null and [Número] <> "")
				in
				    #"Filas filtradas"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

