table 'PRO - Jira - Pruebas con SLA'
	lineageTag: 6dd1629a-88cb-43f0-9e30-27bdb763981d

	column Components
		dataType: string
		lineageTag: 50a00ed2-fad0-4d4f-9239-8cbec9b93e0e
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 50cbe6c9-1c8a-4011-90d3-38bdda11dc7e
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: b5e937ce-52aa-4525-a864-fbceb85301e8
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 45474e99-8812-4168-98a3-541293065394
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 350d8292-eeab-4450-9a1d-eb34c7e26dea
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 8e42b16d-ebc2-4b9a-b0c7-6f92b63449b9
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: ee6942a3-90a3-4671-8ffb-4d360ca1ae46
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 15655b0f-4a99-4010-9dc3-176794fc8e92
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: ac81d047-3722-45da-ae5d-ceab03da823a
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 1fecfbc1-68de-4eb8-bd55-cb1d41ea9146
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 60ef18b5-4367-4c33-ae94-7e7b87933a37
			defaultHierarchy: LocalDateTable_da3f77a5-cec4-4970-a42b-aa5096e5066e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 46d14f32-2a9a-4b68-af11-ceef9eadd201
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column 'Tipo de prueba'
		dataType: string
		lineageTag: c2cc57e8-4198-412a-b886-af490eaf608e
		summarizeBy: none
		sourceColumn: Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: f6429165-9500-44a8-915b-38661e9f07fa
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: d4ed8bca-b1c1-4ee3-a90c-fa8bc12accb8
			defaultHierarchy: LocalDateTable_120e3cc7-e3f3-4a7e-bde6-112eb07f9899.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 455b49a6-9b02-4708-933f-1c1789e40834
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Value (Tests)'
		dataType: string
		lineageTag: 00c4c45e-d59d-4e75-8f86-69e6be4de7c1
		summarizeBy: none
		sourceColumn: Value (Tests)

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias.Key'
		dataType: string
		lineageTag: 1e03122a-5141-4c7b-9046-01217c446d24
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias.Key

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias.Status'
		dataType: string
		lineageTag: f34130e1-47a4-4bb2-9f69-ce4b149f665d
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: 20548476-ac57-4f99-b35c-40c18212c3f9
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias.Resolved

		variation Variation
			isDefault
			relationship: 901a5652-e3df-424a-8eb5-9998c09892e6
			defaultHierarchy: LocalDateTable_a3fd6922-efff-4d7d-afbe-231406991c43.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e0f59018-ef78-4846-bb69-d48b0be0d144
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias.Resolved - Copy

		variation Variation
			isDefault
			relationship: c4b8057b-f194-4faf-b869-b4965c3d6361
			defaultHierarchy: LocalDateTable_6ce178c6-48b6-416d-8eb5-46d694d4e2f2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column UAT = IF ( CONTAINSSTRING('PRO - Jira - Pruebas con SLA'[Tipo de prueba],"UAT"),1,0)
		formatString: 0
		lineageTag: 2d2428dc-0c00-4fcb-8c4a-3cdb29cef168
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column FUN = IF ( CONTAINSSTRING('PRO - Jira - Pruebas con SLA'[Tipo de prueba],"Funcional"),1,0)
		formatString: 0
		lineageTag: 7a448186-903f-441d-8c74-576a07fbb089
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Pruebas con SLA-61f24a68-5eb8-43f1-8370-d881916bc54a' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				     Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/AMS_MOV/Ficheros del Servicio/AMS_IAR_CDM_SLA_I_Entregables, Pruebas y Defectos" & xlsx, //& AMS_IAR_CDM_ & "Parámetros KGIs" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),
				    Tests_Sheet = Origen{[Item="Tests",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Tests_Sheet, [PromoteAllScalars=true]),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Components", type text}, {"Project", type text}, {"Issue Type", type text}, {"Key", type text}, {"Summary", type text}, {"Assignee", type text}, {"Reporter", type text}, {"Priority", type text}, {"Status", type text}, {"Created", type datetime}, {"Linked Issues", type text}, {"Sub-tasks", type text}, {"Tipo de prueba", type text}, {"Resolved", type datetime}}),
				
				    //Separa los Linked Issues de cada Test
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Linked Issues", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {
				        "Linked Issues.1",
				        "Linked Issues.2",
				        "Linked Issues.3",
				        "Linked Issues.4",
				        "Linked Issues.5",        
				        "Linked Issues.6",        
				        "Linked Issues.7",        
				        "Linked Issues.8",       
				        "Linked Issues.9",
				        "Linked Issues.10"        
				        }),
				
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{
				        {"Linked Issues.1", type text}, 
				        {"Linked Issues.2", type text}, 
				        {"Linked Issues.3", type text},
				        {"Linked Issues.4", type text},
				        {"Linked Issues.5", type text},
				        {"Linked Issues.6", type text},
				        {"Linked Issues.7", type text},
				        {"Linked Issues.8", type text},
				        {"Linked Issues.9", type text},
				        {"Linked Issues.10", type text}
				        }),
				
				    //Transforma la separación en tipo lista (Cada Test Link con el Test al cual está relacionado)
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type1", {"Components","Project", "Issue Type", "Key", "Summary", "Assignee", "Reporter", "Priority", "Status", "Created", "Sub-tasks", "Tipo de prueba", "Resolved"}, "Attribute", "Value (Tests)"),
				
				    //Une con las Historias
				    #"Merged Queries" = Table.NestedJoin(#"Unpivoted Columns", {"Value (Tests)"}, #"PRO - Jira - Historias", {"Key"}, "PRO - Jira - Historias", JoinKind.LeftOuter),
				    #"Expanded PRO - Jira - Historias" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Jira - Historias", {"Key", "Status", "Resolved"}, {"PRO - Jira - Historias.Key", "PRO - Jira - Historias.Status", "PRO - Jira - Historias.Resolved"}),
				
				    //Nueva columna "Fecha Resolved" para relacionar a Fechas del CdM
				    #"Duplicated Column" = Table.DuplicateColumn(#"Expanded PRO - Jira - Historias", "PRO - Jira - Historias.Resolved", "PRO - Jira - Historias.Resolved - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"PRO - Jira - Historias.Resolved - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"PRO - Jira - Historias.Resolved - Copy", Date.StartOfMonth, type date}}),
				
				    //Homogeiniza la prioridad proveniente de Jira a los valores de ANS
				    #"AllReplace" = [#"Highest" = "Grave", #"High" = "Grave", #"Medium" = "Media",#"Low" = "Leve",#"Lowest" = "Leve"],    
				    #"Replaced Value" = Table.TransformColumns(#"Calculated Start of Month",{{"Priority",each Record.FieldOrDefault(AllReplace,_,_)}})
				
				in
				    #"Replaced Value"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

