table 'PRO - Incidencias con SLA (NY y MAD) KGI21'
	lineageTag: dacea08e-e495-4b83-b189-98a10b468634

	column Número
		dataType: string
		lineageTag: 88b0a279-ff72-45ef-bb6d-eaab1505af17
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 0b7d8e5e-e2fc-43b4-8ef6-56feee972722
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: c5512260-d255-4cf6-b5b9-673d41a91be6
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: dbe10752-45bd-489e-8823-252755659a03
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 0620094c-24ba-4a8e-bca4-343dc2a2a57e
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: 1ec01b39-da8a-493e-84a6-1cba8e38daa4
			defaultHierarchy: LocalDateTable_09eca8cc-6f4a-43be-9d8b-1c6cc86bd723.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: c2e74f47-a080-4fde-899a-63ff281285f0
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variación
			isDefault
			relationship: 4e13e8a4-1a04-4404-8e81-6ae3ae5e082b
			defaultHierarchy: LocalDateTable_82dc37d6-27e8-40ee-bb0c-00b72de728b5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: d5e8d24f-1713-43cb-bd1b-2c3b8df15bf5
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 921b7871-af8b-404a-a292-621659943256
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9b34490a-62a0-4db9-8559-7673698b6f69
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 924fda21-380e-4720-a868-a160a8928069
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variación
			isDefault
			relationship: 910c8203-2e06-426f-9918-5082545b28b6
			defaultHierarchy: LocalDateTable_438363a8-b4b0-43dc-a101-568ee36e0528.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 732708b6-4532-4fee-80f9-691d00181263
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: aee9b2cf-a598-4bd5-9193-a1d39603033d
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: d88ca663-31f0-463a-9771-66e261c9a35a
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: 4d1852c2-23e0-4e0e-8969-682de594bbbb
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: cf983822-842e-44da-a269-61334cfc2cb8
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: d8cc6f0b-cb72-4988-a77a-1c21c428476c
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: b91529ac-e58d-4269-baae-60f9051f0448
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3d5ae83c-a56b-414e-b4ea-a6f5bd9eec72
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		variation Variación
			isDefault
			relationship: 8f2fec47-8b81-4ec5-9f80-c27d98f0657a
			defaultHierarchy: LocalDateTable_1a879c43-2580-40c9-8182-4f4f55099e6f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración excedida'
		dataType: string
		lineageTag: ac1fc39f-bca9-4f29-b5b1-662319f42204
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 4f4bdf74-858d-472d-ba8c-99cdf8827227
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: d9e35a07-8e82-4c20-85b0-93fe8013fe9e
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Infringidos Numérico' = IF('PRO - Incidencias con SLA (NY y MAD) KGI21'[Infringido] = TRUE(),1,0)
		formatString: 0
		lineageTag: 1fbd8651-e4c9-4930-a218-877559e943f5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'No Infringidos Numerico' = IF('PRO - Incidencias con SLA (NY y MAD) KGI21'[Infringido] = TRUE(),0,1)
		formatString: 0
		lineageTag: 6344ca17-5200-43c4-9bb2-0bb104c8d572
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Duración D:HH:MM:SS' =
			
			VAR VDUR21_2 = 'PRO - Incidencias con SLA (NY y MAD) KGI21'[Duración real]
			  RETURN INT
			    (VDUR21_2/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_2/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21_2/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21_2,60)),2)
		lineageTag: ecb83939-f352-4ae7-933f-448bd4613e13
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración_EX D:HH:MM:SS' =
			
			VAR VDUR21_EX_2 = 'PRO - Incidencias con SLA (NY y MAD) KGI21'[Duración excedida]
			  RETURN INT
			    (VDUR21_EX_2/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_EX_2/3600,24)),2)&" HH"
		lineageTag: eac8c95f-a021-40a5-9141-7298b4899a04
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA (NY y MAD) KGI21'[Número])
		lineageTag: dafdf4ef-8099-4bb8-9c39-de8be9e80910
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 2f02bceb-e83d-4680-a59f-4adfa03aa785
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 12b39912-e8f3-460a-9c88-8acab15eda32
			defaultHierarchy: LocalDateTable_2320ec91-bfb1-4598-b959-46c2c3e6ed83.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 30330682-c3f8-4fde-9365-888af7bbe6ae
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA (NY y MAD) KGI21-fff1a7e5-2741-461f-885c-fd6d97bfabdc' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Source = #"PRO - Incidencias con SLA (NY y MAD)",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"ANS_Alegado", "Estado_Alegación"}),
				    
				    //Une con tabla de alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"Número"}, #"PRO - Alegaciones del Servicio KGI21", {"ID"}, "PRO - Alegaciones del Servicio KGI21", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio KGI21" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio KGI21", {"ANS", "Estado"}, {"PRO - Alegaciones del Servicio KGI21.ANS", "PRO - Alegaciones del Servicio KGI21.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio KGI21",{{"PRO - Alegaciones del Servicio KGI21.ANS", "ANS_Alegado"}, {"PRO - Alegaciones del Servicio KGI21.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Infringido" si la alegación es aceptada
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1",each [Infringido],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI 2-1" then "FALSE" else [Infringido],Replacer.ReplaceValue,{"Infringido"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"Infringido", type logical}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegación

