table 'PRO - Jira - Defectos con SLA - FUN - Detalle'
	lineageTag: 37bd0698-99fb-4b54-ac75-b9c78bb1e55e

	column Components
		dataType: string
		lineageTag: 8c1148df-1355-4667-8fdc-2f8a2788a9d8
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 709e2929-2843-4836-abec-4d02628096f0
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: b5cea229-5863-41ee-a798-1975b65f0acc
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: f0ed9c13-6907-4555-8466-010b8601f291
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 6f69347c-1c76-4fb8-b70b-9d362cf9daac
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: b02b39f2-e932-4330-8b91-feac41cdfcba
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 5feb974c-47c2-40bf-9e8d-87d63cfc2ea5
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: f0329f46-5151-4d27-9a2c-f5ee23893f11
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: c8e658f2-4d85-416f-a0a6-36cfa9184572
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 7520953b-51f1-4c37-a5ef-ed7da5a81d15
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: b606a951-db1d-4745-b6f5-d4b9b7d9c7e3
			defaultHierarchy: LocalDateTable_5ee0558c-c30a-4c85-9729-47e3b26a8b16.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: dc2ac714-8557-4bc8-bab7-c56ba8add2b0
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: 0dc6e7a2-d0d7-40ff-a4d7-c14f32adad43
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: 0a63252e-5978-41ab-929e-b236bcdc81e5
			defaultHierarchy: LocalDateTable_e25738bf-0ac5-4f30-b5c5-bb738d3cb418.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: bd69bb8d-8df3-46e7-8c92-f12094ae391b
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Value (Bugs)'
		dataType: string
		lineageTag: 24ddb29d-737b-4e96-9204-94fc012dfc87
		summarizeBy: none
		sourceColumn: Value (Bugs)

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Status'
		dataType: string
		lineageTag: a755cfdb-a458-43ac-9958-23616c26cd31
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: 838f0911-3a21-4d98-836f-c958018ad480
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved

		variation Variation
			isDefault
			relationship: 03e60a0b-c21a-44b4-ae19-cc5717f706eb
			defaultHierarchy: LocalDateTable_2edee785-ced3-4d09-b834-7a848acb911d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status'
		dataType: string
		lineageTag: af21eeed-4b18-498a-a4b0-c6144beaf4e0
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba'
		dataType: string
		lineageTag: 2c356a99-c43f-4ec1-adc9-3abb38ca17dc
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0d5558ad-0c13-4fe8-b1e7-feb77c1416af
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved - Copy

		variation Variation
			isDefault
			relationship: d4919915-bfec-4ced-97a1-3836acf81f1e
			defaultHierarchy: LocalDateTable_e500c7ea-84d5-4ef1-ac31-bed1cb2d26ae.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: dac11fac-0001-4454-a417-e706d14c735f
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Defectos con SLA - FUN - Detalle-fdad26b4-5d9f-4d4d-b271-fd433890918a' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = #"PRO - Jira - Defectos con SLA",
				
				    #"Filtered Rows" = Table.SelectRows(Source, each ([#"PRO - Jira - Historias y Ejecuciones.Status"] = "Done") and ([#"PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba"] = "Pruebas Funcionales")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [Estado_Alegación] <> "1 - Aprobada")
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

