table 'PRO - Alegaciones del Servicio'
	lineageTag: 8caa6b7b-4fa4-4d47-b06f-15a4930a98cb

	column ID
		dataType: string
		lineageTag: 2cd76bbb-0574-4fe4-afab-fae44b878658
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Entrada alegada'
		dataType: string
		lineageTag: f3e7a1c7-00a6-4ece-9d64-be1e9e61c99c
		summarizeBy: none
		sourceColumn: Entrada alegada

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: string
		lineageTag: 0ad44dd9-0c2c-4a86-bb44-45076866e03c
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		annotation SummarizationSetBy = Automatic

	column Clasificación
		dataType: string
		lineageTag: f0b63eaa-09a5-4d67-8539-0053b16508b3
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 25722599-363a-4ab8-a837-6c771d72078e
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: 6e82e6f2-e13f-4b99-a1a8-3312222f0faf
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 723f90d8-f69c-4197-a8fc-9182ea57780c
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: 8c632843-a091-4d4e-8871-d86f05381b95
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e7f43bdc-f186-4f16-9e8e-a4c984eafa97
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado - Copy

		variation Variation
			isDefault
			relationship: ba4df146-3cbb-401b-9e21-443328fe658d
			defaultHierarchy: LocalDateTable_070c756a-8fc0-436c-9e2b-284c7b3599b3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Sistema Afectado'
		dataType: string
		lineageTag: c0fd8ee3-a89d-459d-a4c7-30963e0e784a
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Comentarios AE'
		dataType: string
		lineageTag: 00a666e6-71cc-4c94-8d8b-0fa9b295813d
		summarizeBy: none
		sourceColumn: Comentarios AE

		annotation SummarizationSetBy = Automatic

	column Columna1
		dataType: string
		lineageTag: dedfc8a1-77e5-4065-979b-33cc64ba2ec6
		summarizeBy: none
		sourceColumn: Columna1

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio-46568dad-504f-4217-812b-f6f3a4b450bd' = m
		mode: import
		queryGroup: Alegaciones
		source = ```
				let
				    Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/AMS_MOV/Ficheros del Servicio/Proveedor_Cliente/AMS_IAR_CDM_Control de alegaciones" & xlsx, //& AMS_IAR_CDM_ & "Parámetros KGIs" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),
				    LBSTICAE_Plt401_TabParticipantes_Table = Origen{[Item="T_Alegaciones",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(LBSTICAE_Plt401_TabParticipantes_Table,{{"ID", type text}, {"Entrada alegada", type any}, {"Periodo de Medida del ANS alegado", type any}, {"Clasificación", type any}, {"ANS", type any}, {"Fecha", type any}, {"Estado", type any}, {"Comentarios", type any}}),
				    
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Periodo de Medida del ANS alegado", "Periodo de Medida del ANS alegado - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Periodo de Medida del ANS alegado - Copy", Date.StartOfMonth, type date}})
				in
				    #"Extracted Date"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

