table 'PRO - Alegaciones del Servicio KGI13_23'
	lineageTag: 5a6df837-ff77-41c0-81b3-03ff98709f7b

	column ID
		dataType: string
		lineageTag: 008b1261-4a4a-4356-b3e6-33d04322d93d
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Entrada alegada'
		dataType: string
		lineageTag: 39028d83-dda7-4fdd-b6c2-0a60a93c9f24
		summarizeBy: none
		sourceColumn: Entrada alegada

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: c67022b2-33c8-4e84-b307-377f04a9e562
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: string
		lineageTag: 3ea964b1-a76a-4d60-85f7-30f1c1bf852f
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		annotation SummarizationSetBy = Automatic

	column Clasificación
		dataType: string
		lineageTag: 962fa0e1-6c1e-4e4a-ab7c-c71833f60552
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 49a355bb-8fa4-4f75-93aa-978579e75f0f
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: d382c31c-78ad-48eb-9c9d-e35a570ce9e9
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 359da2f5-2fb0-4b18-a94f-3eef72d72a8d
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: 469fcd20-4a90-41c7-81c0-cc5d68d0f407
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a4ace484-9450-46fa-8b07-9ad47de8ecad
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado - Copy

		variation Variación
			isDefault
			relationship: be6dc1ea-09f1-4042-bfcc-ae4dfd4b4a3f
			defaultHierarchy: LocalDateTable_b40fba2c-6eca-48ab-bb88-859632283595.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Comentarios AE'
		dataType: string
		lineageTag: 96803d1f-8f47-4218-8578-181bad903684
		summarizeBy: none
		sourceColumn: Comentarios AE

		annotation SummarizationSetBy = Automatic

	column Columna1
		dataType: string
		lineageTag: e2c409e5-c88d-423f-a6a2-214eda9f48bb
		summarizeBy: none
		sourceColumn: Columna1

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI13_23-5c9b7d15-13f1-4018-9be3-74f710745007' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Source = #"PRO - Alegaciones del Servicio",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([ANS] = "KGI 1-3" or [ANS] = "KGI 2-3"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

