table 'PRO - Estimaciones con SLA'
	lineageTag: 60ebd202-44fa-456c-9e9a-fa04e424224d

	column Creado
		dataType: dateTime
		formatString: General Date
		lineageTag: 2928c13e-528a-4b47-b4d0-081dcd217467
		summarizeBy: none
		sourceColumn: Creado

		variation Variation
			isDefault
			relationship: c0611801-5c18-4987-8879-fd5ec90bc80e
			defaultHierarchy: LocalDateTable_4154b662-4c11-4acc-a8d5-92bda6f30c47.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 4be311f2-c351-4da4-9d33-9c86d9e1fa9b
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio'
		dataType: string
		lineageTag: d9a64efe-fe1e-42ae-ae18-b4a8df32cb8f
		summarizeBy: none
		sourceColumn: Aplicación de Negocio

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: d9d41705-b904-4ca7-9d53-42c233c849e5
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Tarea
		dataType: string
		lineageTag: eb3a63e9-4096-4e85-88bc-dc4ec48b82fc
		summarizeBy: none
		sourceColumn: Tarea

		annotation SummarizationSetBy = Automatic

	column Etapa
		dataType: string
		lineageTag: dd9f95dc-90d5-4088-9360-4aee5fdf0f16
		summarizeBy: none
		sourceColumn: Etapa

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de negocio restante'
		dataType: int64
		formatString: 0
		lineageTag: f98742ca-c010-48c3-bb12-7c39b720600c
		summarizeBy: sum
		sourceColumn: Tiempo de negocio restante

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: int64
		formatString: 0
		lineageTag: 7ac106fd-2a15-4c7c-9c2c-444387184321
		summarizeBy: sum
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: b08a5fe0-2e8f-4e99-a2fa-002be8b37448
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Hora de inicio'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4a0b0d33-c252-48bf-b0bc-e1eb217b196a
		summarizeBy: none
		sourceColumn: Hora de inicio

		variation Variation
			isDefault
			relationship: 6ec0d742-c0d5-4084-a395-f93e42d2f643
			defaultHierarchy: LocalDateTable_6680e904-7959-4182-97d6-20c73bd3c6cc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de pausa'
		dataType: string
		lineageTag: 51d69a37-f052-4bca-ba9d-bfc331736612
		summarizeBy: none
		sourceColumn: Tiempo de pausa

		annotation SummarizationSetBy = Automatic

	column 'Hora de finalización'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5c441b9f-e977-46c1-bc15-c8130de23a6c
		summarizeBy: none
		sourceColumn: Hora de finalización

		variation Variation
			isDefault
			relationship: ae9a7f90-d090-4d82-acf4-55ce3d95b525
			defaultHierarchy: LocalDateTable_4993cfe9-4249-4821-9e60-ca1e53d9538c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: b7f7f1a0-e6b1-42e3-ad1d-d9c03d06922a
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Hora de finalización - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4583c345-761f-48b3-ace7-d38dd979e668
		summarizeBy: none
		sourceColumn: Hora de finalización - Copy

		variation Variation
			isDefault
			relationship: 65367430-15c7-4d2e-96e0-d485ed918178
			defaultHierarchy: LocalDateTable_41e01205-b8dc-49df-ae85-bd7a2fee388d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9fb3e03b-953e-4cd1-b4cc-0af41fb320db
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5d758ef8-23ef-48b9-97e0-6165f02abb8c
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 569838a2-3f5d-4b08-85d1-e21ff69b6bf2
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Hora de infracción'
		dataType: dateTime
		formatString: General Date
		lineageTag: dfe72f52-24b0-4108-90ba-575de27e810b
		summarizeBy: none
		sourceColumn: Hora de infracción

		variation Variation
			isDefault
			relationship: a4af2088-38f3-4cd1-8c80-eced946c6a1e
			defaultHierarchy: LocalDateTable_7bf73a75-129b-41e3-95a6-8e72ebf7240c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Duración D:HH:MM:SS' =
			
			VAR VDUR13 = 'PRO - Estimaciones con SLA'[Duración del negocio]
			  RETURN INT
			    (VDUR13/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR13/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR13/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR13,60)),2)
		lineageTag: 2ca3e39e-cf4c-41c9-955f-feb32676df01
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: 21dc5fb6-260e-4d0a-95c4-9377ec740609
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Duración excedida'
		dataType: string
		lineageTag: e759f258-7c5f-4d01-809e-408f88b7c2c7
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column 'Duración_EX D:HH:MM:SS' =
			
			VAR VDUR13_EX = 'PRO - Estimaciones con SLA'[Duración excedida]
			  RETURN INT
			    (VDUR13_EX/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR13_EX/3600,24)),2)&" HH"
		lineageTag: 07e9fdf4-c87f-4ed6-8ada-467371173717
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Estimaciones con SLA'[Tarea])
		lineageTag: 2f98cb86-665f-43e9-8cbd-5e1037bb4531
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Estimaciones con SLA-5a40b48a-1e50-4be9-880e-a8884b495a6d' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/AMS_MOV/Ficheros del Servicio/AMS_IAR_CDM_SLA_I_Estimaciones" & xlsx, //& AMS_IAR_CDM_ & "Parámetros KGIs" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Creado", type datetime}, {"Número", type text}, {"Aplicación de Negocio", type text}, {"Prioridad", type text}, {"Tarea", type text}, {"Etapa", type text}, {"Tiempo de negocio restante", Int64.Type}, {"Duración del negocio", Int64.Type}, {"Porcentaje de negocio trascurrido", Percentage.Type}, {"Hora de inicio", type datetime}, {"Tiempo de pausa", type any}, {"Hora de finalización", type datetime}, {"Grupo de asignación", type text}, {"Infringido", type logical}, {"Hora de infracción", type datetime}, {"Duración", Int64.Type}}),
				    //Genera Columna de Cerrado
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Hora de finalización", "Hora de finalización - Copy"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Duplicated Column",{{"Hora de finalización - Copy", type date}}),
				    #"Inserted Start of Month" = Table.AddColumn(#"Changed Type1", "Start of Month", each Date.StartOfMonth([#"Hora de finalización - Copy"]), type date),
				   
				   //Homologa las prioridades
				    #"AllReplace" = [#"1 - Crítica" = "Alta", #"2 - Alta" = "Alta", #"3 - Moderada" = "Media",#"4 - Baja" = "Baja",#"5 - Muy Baja" = "Baja"],    
				    #"Replaced Value" = Table.TransformColumns(#"Inserted Start of Month",{{"Prioridad",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    
				    //Pone "Nuevo Servicio" sobre Estimaciones de Demandas que no son Evolutivos
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",         "",             "Nuevo Servicio",Replacer.ReplaceValue,{"Aplicación de Negocio"}),
				
				    //Une con las alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value1", {"Tarea"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"Estado"}, {"PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Infringido" si la alegación es aceptada
				    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns",each [Infringido],each if [Estado_Alegación] = "1 - Aprobada" then "FALSE" else [Infringido],Replacer.ReplaceValue,{"Infringido"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value2",{{"Infringido", type logical}}),
				
				    //Elimina los duplicados, y deja el último SLA finalizado
				    #"Sorted Rows" = Table.Buffer(Table.Sort(#"Changed Type2",{{"Hora de finalización - Copy", Order.Descending}})),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"Tarea"}),
				    
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Duplicates",{{"Duración", "Duración SLA"}}),
				
				    //Nuevo campo de Duración Excedida, respecto a SLA
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "Duración excedida", 
				    each if ([Duración del negocio]-[Duración SLA])<0 then 0 else 
				    ([Duración del negocio]-[Duración SLA])),
				    #"Divided Column" = Table.TransformColumns(#"Added Custom", {{"Porcentaje de negocio trascurrido", each _ / 100, Percentage.Type}})
				in
				    #"Divided Column"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

