table 'PRO - Planificaciones MA'
	lineageTag: 2d09f9ac-1d72-4440-ae5d-9bebdf1a51ea

	column Demanda
		dataType: string
		lineageTag: c86bfabb-398f-4bda-bab2-e34437efc962
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: c1f9abd0-5174-4532-b79c-8b5a7df9d71a
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 3e7ddce4-e1d9-4227-80af-7ae4b6e3d2eb
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: aa616f72-4fd2-40c7-946f-37d5ea3040b9
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: 9752700a-ea0a-441d-a55a-ab48902c877a
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: c7fc8b99-3257-474d-9c2e-119755ce8a05
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 87887cd1-2096-4975-9e60-b786259a7f68
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variation
			isDefault
			relationship: f1c2ff19-dc45-4733-8784-9e02b822521b
			defaultHierarchy: LocalDateTable_644e9fda-3758-4fae-9e15-df3d35706a7d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 07cace9a-725a-4c37-b54d-4d91203b8144
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variation
			isDefault
			relationship: 1ae4f115-06f5-4390-98e8-c517a86181c0
			defaultHierarchy: LocalDateTable_ace832ad-73d1-4c4a-aa40-fd51a45c9598.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 9bdcd7da-de99-4624-8e12-d456d369543d
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: a8d4161b-7cd3-4984-85b5-d0314be0dc25
		summarizeBy: none
		sourceColumn: Inicio

		variation Variation
			isDefault
			relationship: 48cbcbc7-fc1c-4fc6-b397-2cbce740b4ea
			defaultHierarchy: LocalDateTable_ddf43091-aa12-45da-a017-7f828e5d2402.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: b68aaf31-7258-4911-9197-0e4a45c7c638
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: 26bcd3c3-82fa-4731-b5e6-c30cc4441105
			defaultHierarchy: LocalDateTable_f36d0a80-9527-472e-aaa5-7fca701fd1c2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: f4f9d325-d8ab-4c28-a455-d5a1c35f0a0d
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: 94553bf3-6316-4935-8766-27a39c78b951
			defaultHierarchy: LocalDateTable_89940140-1b60-4c13-a603-b9525703d81d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: 4b3a89dc-9a06-4a7c-a01f-e90d0af6f150
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: ce414fd1-0d79-4c11-8b18-acd00450eb11
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: a81b5f09-824a-4324-8799-a574f2da94ec
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: b48a6350-bb8e-4313-b32f-d3a664d14767
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: 7a64e144-0114-4b54-b22a-5927a3f08418
		summarizeBy: none
		sourceColumn: Fin

		variation Variación
			isDefault
			relationship: c430c20e-4e7d-4587-a184-23be1e883d7c
			defaultHierarchy: LocalDateTable_3db8e3cb-d010-4745-859c-491c000e6ed1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones MA-79bd6986-2989-4c18-863a-41eff1683ea9' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/AMS_MOV/Ficheros del Servicio/AMS_IAR_CDM_SLA_I_Planificaciones de EVOs" & xlsx, //& AMS_IAR_CDM_ & "Parámetros KGIs" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Promoted Headers",{{"Fecha de finalización derivada de", "Fecha final derivada de"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Número", type text}, {"Número_1", type text}, {"Tipo de Proyecto", type text}, {"Prioridad", type text}, {"Jefe de proyecto (Project Manager)", type text}, {"Aplicación de Negocio ", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha fin planificada", type datetime}, {"Nombre de subtarea", type text}, {"Fecha de inicio derivada de", type datetime}, {"Fecha final derivada de", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Breve descripción", type text}}),
				
				    //Homologa cabeceras para realizar posterior Append con PRJs
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{
				        {"Número",                      "Demanda"},
				        {"Número_1",                    "Número"}, 
				        {"Nombre de subtarea",          "Nombre"}, 
				        {"Fecha de inicio derivada de", "Inicio"}, 
				        {"Fecha final derivada de",     "Fin"}, 
				        {"Breve descripción",           "Nombre de PRJ o MEJ"}})
				
				in
				    #"Renamed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

