table 'PRO - Alegaciones del Servicio KGI21'
	lineageTag: 0ebb323e-bc8a-4844-9920-a2806d7d5b23

	column ID
		dataType: string
		lineageTag: 98b5a8da-6c52-4aa1-9e06-3860731ac253
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Entrada alegada'
		dataType: string
		lineageTag: 320b0c38-5729-43c4-97ba-23456142262f
		summarizeBy: none
		sourceColumn: Entrada alegada

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: 8cb3f76f-a851-4f3e-9a24-0ab07859e1d5
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: string
		lineageTag: 4d18ea38-a7d2-4692-8c69-7c606469e7a5
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		annotation SummarizationSetBy = Automatic

	column Clasificación
		dataType: string
		lineageTag: 9df2e4ec-4563-49b2-b0e6-0da39cd20efe
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 5ef1a24f-1504-43bb-b4f3-9b3dbc999828
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: fc8a79d4-5665-45f9-8f62-f6f0893bfaa4
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: d91d2522-c3ee-4742-96a0-5f19991c1d88
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: 1622b44a-ea58-48de-98b5-537b031a516f
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e7aa0ab0-fa4e-4f15-8c3f-148e11b47172
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado - Copy

		variation Variación
			isDefault
			relationship: 68ab0335-55c9-4e98-99b8-c3cbaed208fe
			defaultHierarchy: LocalDateTable_7811f2c6-64e8-4715-b182-7151d8713b83.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Comentarios AE'
		dataType: string
		lineageTag: 205a9ad1-805e-4443-a183-99feb52587a1
		summarizeBy: none
		sourceColumn: Comentarios AE

		annotation SummarizationSetBy = Automatic

	column Columna1
		dataType: string
		lineageTag: a7d4de28-d1a5-412b-8d9b-db37a925abe0
		summarizeBy: none
		sourceColumn: Columna1

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI21-b36ba7f8-1741-4732-9cb2-a7f206f9b924' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Source = #"PRO - Alegaciones del Servicio",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([ANS] = "KGI 2-1"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

