table 'PRO - Incidencias con SLA (NY y MAD) KGI22'
	lineageTag: 3c917a18-2f90-4b54-975d-27769f36b8ae

	column Número
		dataType: string
		lineageTag: 83d74d45-51c0-4665-9c4b-d6425e34a65f
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 371b1a79-db09-4e46-a695-3006854464e5
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: 92a24dc8-f06b-4630-8c58-1787048b60c1
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 4c4fd82c-2269-4f2b-b639-e384cb8a86a8
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 311aa6e8-a51d-41dc-9c1b-78c426e7cbdd
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: 66b1ae4a-d1e1-4ab5-942c-8cc8f4184e3b
			defaultHierarchy: LocalDateTable_4c033515-6796-44ec-8d70-13811cd593a8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: 31829327-fcd8-4aee-8135-c175f0235c58
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variación
			isDefault
			relationship: b9a7cf8e-7235-4951-9c20-60f513e4d612
			defaultHierarchy: LocalDateTable_9bfa5c72-b855-471a-8013-b507575ffc16.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 97d091b1-3f08-4340-81ef-5fb0ad68135c
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 5243fea8-b89a-45a4-b0e5-48b99f538f79
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8389b176-c727-4d8f-8a3f-035524792ea7
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: ef8938bd-6ddb-4c15-8a8a-c1eb849d1b90
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variación
			isDefault
			relationship: 37b4340a-8494-470a-b229-30650ba654ec
			defaultHierarchy: LocalDateTable_b2d335b0-ebaa-4914-ad1f-5153df347e2d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: c2c38654-9275-4e9f-a74d-d7e307846112
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 98f1009e-a892-4dc1-94e0-bebd72065821
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: d0a0d460-6370-4a7c-a1dd-7b2240f78180
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: aee8f563-9494-4b3d-842f-7eec690a7262
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: fbbbfc7a-ac23-46a3-a33f-313b4ac6cfb9
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: 7183c5fe-f009-481d-b773-defbb7b84675
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		lineageTag: 1f80bed2-bdd4-4ecc-97c0-bd851df46acb
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5dc6c206-7a40-490b-aacd-9bd8c069a13f
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		variation Variación
			isDefault
			relationship: 6199b296-edf3-4a6c-bb84-4f36265ff38d
			defaultHierarchy: LocalDateTable_62a2f9d1-4ef5-4e54-9bec-a01c8ca8a062.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración excedida'
		dataType: string
		lineageTag: 30e06e70-e378-4985-9878-8ea6496c344a
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 78eb602d-3eae-4fbb-b039-376eeca51629
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: a787a3c2-7539-4e08-aa7a-6ea11c8b92ef
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column N_Reabierta = ```
			IF('PRO - Incidencias con SLA (NY y MAD) KGI22'[Reabierta] = True,1) 
			```
		formatString: 0
		lineageTag: e23f1cf4-b1aa-48f4-b523-ebc83b02d8a3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA (NY y MAD) KGI22'[Número])
		lineageTag: 73c4df3a-1e8d-4c30-8745-e3616329ef49
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: a10637c7-f868-45d9-9d22-cdfd8c5886eb
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: ea956684-df22-46be-862e-0df0dc629253
			defaultHierarchy: LocalDateTable_c617ab8e-65ff-4b04-a94d-438fd44b477c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 7043dd89-60e9-44e9-924a-1d6274664d23
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA (NY y MAD) KGI22-cfad9582-c26a-47e0-a884-c82df30fa290' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Source = #"PRO - Incidencias con SLA (NY y MAD)",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"ANS_Alegado", "Estado_Alegación"}),
				    
				    //Une con tabla de alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"Número"}, #"PRO - Alegaciones del Servicio KGI22", {"ID"}, "PRO - Alegaciones del Servicio KGI22", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio KGI22" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio KGI22", {"ANS", "Estado"}, {"PRO - Alegaciones del Servicio KGI22.ANS", "PRO - Alegaciones del Servicio KGI22.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio KGI22",{{"PRO - Alegaciones del Servicio KGI22.ANS", "ANS_Alegado"}, {"PRO - Alegaciones del Servicio KGI22.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Infringido" si la alegación es aceptada
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1",each [Reabierta],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI 2-2" then "FALSE" else [Reabierta],Replacer.ReplaceValue,{"Reabierta"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"Reabierta", type logical}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

