table 'PRO - Planificaciones PRJ y ENH con SLA-Relacionada'
	lineageTag: 002e8cf0-6bc9-4505-98cc-367cf2d67ddc

	column Demanda
		dataType: string
		lineageTag: e803619b-008c-4fbd-9f24-b3fd680c04a6
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: cb5c154a-1519-458c-a552-2b74042e85e6
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 4b3c476c-9d36-49ae-be7e-ab15897dff85
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 4e2f6ba7-b5e5-4973-afd5-75002ee1cfc0
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: ef2c3b0a-bf51-47da-b9d7-7ee6da1a452e
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: da39591c-ce02-4991-b643-bb5b44f4ce0a
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 3771fe8c-16e5-4c42-8750-8b96876a4093
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variación
			isDefault
			relationship: 130dc4f7-c133-4499-a3a2-c3749949015a
			defaultHierarchy: LocalDateTable_9a7f66e6-4bd0-430b-b1e4-17790ce7b9d0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha límite planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: d8e7fada-0e07-42bb-8c05-e7c578987a01
		summarizeBy: none
		sourceColumn: Fecha límite planificada

		variation Variación
			isDefault
			relationship: dd7e0c45-593b-4d1c-a473-09a9392b5e6b
			defaultHierarchy: LocalDateTable_a2c05246-1f26-45e0-b0ab-9e29fd1a7a83.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 27371922-6d48-46a8-9ab2-f0cb644cf280
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: 9816cc6b-958a-4004-af61-7e3f8b4351d3
		summarizeBy: none
		sourceColumn: Inicio

		variation Variación
			isDefault
			relationship: 294b6f5d-b763-4f48-b28e-9ba153bc15df
			defaultHierarchy: LocalDateTable_eba0ef32-e174-462b-b289-598a9941f6f3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: e48d4cf1-10f8-4066-b5d3-812220e43a63
		summarizeBy: none
		sourceColumn: Fin

		variation Variación
			isDefault
			relationship: 0f79dfbd-20fc-4866-8558-7a7adf31ffa0
			defaultHierarchy: LocalDateTable_26764ca1-4909-45cb-98dd-a5d065019e6e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: f7b513e7-2e6c-4ed5-b90f-1dde66168072
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variación
			isDefault
			relationship: 7d5931f9-7e22-4aa7-a071-badcade97aea
			defaultHierarchy: LocalDateTable_0191aad3-7166-40a5-a9d1-2100a7c62739.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 90ce37cf-7ee9-425d-b1ec-b83afc24a9d6
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variación
			isDefault
			relationship: dbb617d0-56a4-47fc-b8a0-81c3fa0fbf04
			defaultHierarchy: LocalDateTable_3256d64d-fc46-429e-aa3f-4e6bcae190f5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: 30ca898d-026b-420e-9e9a-d32db4563454
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: bdf2e2fe-0029-48eb-bf46-7909e73a7b9f
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 21061ee5-3895-4024-a554-d91ac5b407d2
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: f334d475-49c5-435f-8576-e37225c4b212
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4c1029b4-6eae-4855-85fa-022bdcc79c9f
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variación
			isDefault
			relationship: 7645e3f7-eee2-454c-aa6b-cb1c4461fb76
			defaultHierarchy: LocalDateTable_77003157-690f-4b5e-a0df-ee1e454800c4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c37d3bc5-a0be-43ec-866d-71fa5c22cc80
		summarizeBy: none
		sourceColumn: Fecha fin real - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración Planificada LB'
		dataType: double
		lineageTag: 4297aeaa-acbb-4449-b0ae-f65aae177ff4
		summarizeBy: sum
		sourceColumn: Duración Planificada LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real LB'
		dataType: double
		lineageTag: 2ab0d59f-d892-4b91-bfce-014975463537
		summarizeBy: sum
		sourceColumn: Duración real LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa de desviación'
		dataType: double
		lineageTag: 61ffca91-1612-425a-8ed8-32b7251b8fc7
		summarizeBy: sum
		sourceColumn: Tasa de desviación

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estimación incumplida'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 55dd5777-a2e5-439a-8cc9-cf472d96c12e
		summarizeBy: none
		sourceColumn: Estimación incumplida

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 10f29d8e-ba60-4e94-9cf0-d16dd57eed03
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Incidencias relacionadas.Incidente'
		dataType: string
		lineageTag: f909e4b4-2033-4a40-920e-1a481014eea7
		summarizeBy: none
		sourceColumn: Incidencias relacionadas.Incidente

		annotation SummarizationSetBy = Automatic

	column ServiceNow-Tarea = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Planificaciones PRJ y ENH con SLA-Relacionada'[Número])
		lineageTag: fd29016f-2b1f-4622-bad5-11247cc1da51
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ServiceNow_Incidencia = CONCATENATE("https://acciona.service-now.com/incident.do?sysparm_query=number%3d", 'PRO - Planificaciones PRJ y ENH con SLA-Relacionada'[Incidencias relacionadas.Incidente])
		lineageTag: 876ceb00-b5ba-4e56-9fc1-92263122f4b7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones PRJ y ENH con SLA-Relacionada-4445c01b-487f-4ae6-a40b-b608384dde3c' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Origen = #"PRO - Planificaciones PRJ y ENH con SLA",
				    #"Consultas combinadas" = Table.NestedJoin(Origen, {"Número"}, #"Incidencias relacionadas", {"Tarea"}, "Incidencias relacionadas", JoinKind.LeftOuter),
				    #"Se expandió Incidencias relacionadas" = Table.ExpandTableColumn(#"Consultas combinadas", "Incidencias relacionadas", {"Incidente"}, {"Incidencias relacionadas.Incidente"}),
				    #"Filas filtradas" = Table.SelectRows(#"Se expandió Incidencias relacionadas", each ([Incidencias relacionadas.Incidente] <> null))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegación

