table 'PRO - Jira - Defectos con SLA'
	lineageTag: 04d6242a-aa00-487d-a52e-7ac14363e13b

	column Components
		dataType: string
		lineageTag: 9674b1d2-145b-4736-ba4a-525afd81b1b9
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: b4c09c90-50a4-460d-a9f3-25f65d50a2cd
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: 3b06444e-1800-49a8-b843-21b42ef7188d
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: d04e4347-b154-4400-bc71-63fe7b05179c
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 77fc29c7-c18e-4ea1-a3f2-4cdb9b84f259
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 7eea3bc0-0cfc-40a0-8deb-57bc9f9fe51a
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 1e6fe22a-a59f-4308-bbe7-7f7c4856b5f6
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 428ef477-fc98-4322-8373-acda3082bbf2
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: ec32f765-ea5b-4da7-b1ef-56148062780a
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: d6db1df7-1c84-4dba-aa5c-9b1d85f25072
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 65ea9571-c66b-455e-a135-9fb2a9e5c120
			defaultHierarchy: LocalDateTable_75732222-5cf5-43a7-aa9a-91a0f2bdbdf4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 51fd75d4-d096-4e23-be0b-1d5e716a9a0e
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: 63677536-12b9-48b6-8a93-8ff415d552cc
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: 950430a8-a8a9-4152-881b-e6485b5ed1c0
			defaultHierarchy: LocalDateTable_dfb0493d-f256-4af0-b4c9-b00b73cd76cc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 31e05b91-d398-47dd-ac3f-e6a012008acd
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Value (Bugs)'
		dataType: string
		lineageTag: cedcec24-1050-4bdf-9c68-af45ad6ea236
		summarizeBy: none
		sourceColumn: Value (Bugs)

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Status'
		dataType: string
		lineageTag: a8e18a04-9c2e-4137-a101-fee12a349029
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: 72e85fca-0f47-4768-971b-0708c79d09f3
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved

		variation Variation
			isDefault
			relationship: 959a1d9a-a3d2-4fe8-8a91-353286185dd2
			defaultHierarchy: LocalDateTable_4523824c-503e-4f43-985d-0dac67ee3934.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status'
		dataType: string
		lineageTag: 137bb379-3461-4a15-9ac7-6c530c9b59f3
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba'
		dataType: string
		lineageTag: 8fa9b2b7-9808-44d0-82b9-57a546928406
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f0910ef0-cfe7-4236-997b-8e6219efd7d1
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved - Copy

		variation Variation
			isDefault
			relationship: 55e8f64e-23f1-446a-b0e7-cc2575c5fedd
			defaultHierarchy: LocalDateTable_8a54f5c0-0663-4d38-9175-dc93c9443319.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: 0d76ade8-9a9b-4033-9013-caf5069d3578
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Defectos con SLA-c529664e-4ce4-4b6a-8d96-3f11a751901e' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/AMS_MOV/Ficheros del Servicio/AMS_IAR_CDM_SLA_I_Entregables, Pruebas y Defectos" & xlsx, //& AMS_IAR_CDM_ & "Parámetros KGIs" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),
				    Tests_Sheet = Origen{[Item="Bugs",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Tests_Sheet, [PromoteAllScalars=true]),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Components", type text}, {"Project", type text}, {"Issue Type", type text}, {"Key", type text}, {"Summary", type text}, {"Assignee", type text}, {"Reporter", type text}, {"Priority", type text}, {"Status", type text}, {"Created", type datetime}, {"Linked Issues", type text}, {"Sub-tasks", type text}, {"Tipo de prueba", type text}, {"Resolved", type datetime}}),
				
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Linked Issues", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {
				        "Linked Issues.1",
				        "Linked Issues.2",
				        "Linked Issues.3",
				        "Linked Issues.4",
				        "Linked Issues.5",        
				        "Linked Issues.6",        
				        "Linked Issues.7",        
				        "Linked Issues.8",       
				        "Linked Issues.9",
				        "Linked Issues.10"        
				        }),
				
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{
				        {"Linked Issues.1", type text}, 
				        {"Linked Issues.2", type text}, 
				        {"Linked Issues.3", type text},
				        {"Linked Issues.4", type text},
				        {"Linked Issues.5", type text},
				        {"Linked Issues.6", type text},
				        {"Linked Issues.7", type text},
				        {"Linked Issues.8", type text},
				        {"Linked Issues.9", type text},
				        {"Linked Issues.10", type text}
				        }),
				
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type1", {"Components","Project", "Issue Type", "Key", "Summary", "Assignee", "Reporter", "Priority", "Status", "Created", "Sub-tasks", "Resolved"}, "Attribute", "Value (Bugs)"),
				    
				    //Une con las Historias (Relación Defecto con la tabla de Historias y Ejecuciones)
				    #"Merged Queries" = Table.NestedJoin(#"Unpivoted Columns", {"Value (Bugs)"}, #"PRO - Jira - Historias y Ejecuciones", {"Value (Stories)"}, "PRO - Jira - Historias y Ejecuciones", JoinKind.LeftOuter),
				    #"Expanded PRO - Jira - Historias y Ejecuciones" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Jira - Historias y Ejecuciones", {"Status", "Resolved", "PRO - Jira - Ejecuciones.Status", "PRO - Jira - Ejecuciones.Tipo de prueba"}, {"PRO - Jira - Historias y Ejecuciones.Status", "PRO - Jira - Historias y Ejecuciones.Resolved", "PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status", "PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba"}),
				    
				    //Homogeiniza la prioridad proveniente de Jira a los valores de ANS
				    #"AllReplace" = [#"Highest" = "Grave", #"High" = "Grave", #"Medium" = "Media",#"Low" = "Leve",#"Lowest" = "Leve"],    
				    #"Replaced Value" = Table.TransformColumns(#"Expanded PRO - Jira - Historias y Ejecuciones",{{"Priority",each Record.FieldOrDefault(AllReplace,_,_)}}),
				
				    //Ajuste de campo de Historias & Ejecuciones para relacionar a fechas
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced Value", "PRO - Jira - Historias y Ejecuciones.Resolved", "PRO - Jira - Historias y Ejecuciones.Resolved - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"PRO - Jira - Historias y Ejecuciones.Resolved - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"PRO - Jira - Historias y Ejecuciones.Resolved - Copy", Date.StartOfMonth, type date}}),
				
				    //Une con las alegaciones
				    #"Merged Queries2" = Table.NestedJoin(#"Calculated Start of Month", {"Key"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries2", "PRO - Alegaciones del Servicio", {"Estado"}, {"PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				
				    #"Filtered Rows1" = Table.SelectRows(#"Renamed Columns1", each [#"PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status"] <> null and [#"PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status"] <> ""),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows1", {"Key"})
				
				in
				    #"Removed Duplicates"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

