table 'PRO - Incidencias con SLA - Críticas'
	lineageTag: a7ed6fc0-cf57-43a3-91c3-8b6dcd47a513

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0f3ce0d8-2bf9-4b32-965d-80e989db3333
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Número
		dataType: string
		lineageTag: 33463d8e-92c4-4297-a23a-01312982959d
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: ed126596-0df8-4026-bd84-2c11f7341d18
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 010d7944-b396-4ba3-9d92-1b259d042087
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 09230216-ea31-491f-9f87-5df024cb5f3f
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: df3f57d9-ef15-4646-954e-eaa420dac074
			defaultHierarchy: LocalDateTable_3f06b27f-0510-4dd2-8d37-7f92ac44a3e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: c2299a5a-52a8-4a69-a1a3-df2266f27b63
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variation
			isDefault
			relationship: e13b252d-1c6e-4b70-95e6-dd9e64e846b9
			defaultHierarchy: LocalDateTable_fdbe50b0-deb1-435f-9b69-a8f177b7e3ee.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		lineageTag: 5fa61934-553a-4fad-aa41-9094dd430511
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real'
		dataType: int64
		lineageTag: 5c670e04-9730-47a9-a112-15567b874105
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 15fc10d7-2462-44f2-8a89-bc7c7f38429b
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 93628c6c-c2ca-4ae6-9780-15a804f66cda
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: 27f09365-442a-48fc-ab3c-e15d8571463f
			defaultHierarchy: LocalDateTable_e05ab479-eb64-4ed4-bf1c-8c4eb0dd5415.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 08137a71-cf95-4266-9699-a60e63cc1999
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 5517042f-b457-4526-8d48-7d052bc4c661
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 436e5462-94e8-4295-a88b-77aa19d369bc
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: 616e3c58-3857-4f8e-a336-9850811c5b1f
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: ac80010e-5c91-4afc-bbc2-d571718a7792
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: 09d7ce4d-f690-4202-afb6-67295c9d343f
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: 2ce7081d-2810-4fb5-a730-e117844e8bcb
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		lineageTag: b5ef3cbb-4c18-4ff3-b288-e8174b974811
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración excedida'
		dataType: string
		lineageTag: 1f195892-8d73-4690-a0d8-376d024255d4
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 6ee6f6bf-9721-4683-8e2d-77dc5f50a301
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 0ca3526f-ef1a-4705-9eea-90a1f9ba2afc
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 084442bf-1f9e-4743-bedb-c7d2768fe280
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 4e94c90c-cb11-40a7-ba51-8ffdead8541d
			defaultHierarchy: LocalDateTable_1ebef844-a9a3-4390-a464-3df8157e6d35.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 89389697-6c79-46a3-b1e2-a4f38fdb8abc
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA - Críticas-3d482670-727d-48d4-bcc2-80f967e74dae' = m
		mode: import
		queryGroup: KGIs_II
		source =
				let
				    Source = #"PRO - Incidencias con SLA (NY y MAD)",
				    #"Filtered Rows" = Table.SelectRows(Source, each (
				        [Prioridad] = "1 - Crítica" or
				        [Prioridad] = "Crítica"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

