table 'PRO - Incidencias con SLA (NY y MAD) - Abiertas_KGI13'
	lineageTag: eef80a0a-64bf-4ea8-82d0-391c6ad517cf

	column Número
		dataType: string
		lineageTag: 0a02743d-25c1-4ef7-8047-497d2022d109
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 4344d793-ea2e-4674-8258-b891b7394f8d
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: f2792b35-cfd4-469b-9022-b8112b33527b
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 6b0fd788-450d-4bce-b2fe-a046f7d5a4de
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: 27a3928f-9e37-4c7f-86d1-5378152cd18e
			defaultHierarchy: LocalDateTable_e232f784-546d-4a9c-80ad-eb06e1df0355.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: 069be506-d3f0-48bd-9695-96087ab7c750
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variation
			isDefault
			relationship: 69f62761-9721-49fc-a8e2-60ead9216c40
			defaultHierarchy: LocalDateTable_cdf7cd2e-cb6c-4022-9050-5bc17af1ac24.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		lineageTag: 3145af04-8649-47c3-89c3-d6227b96b978
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real'
		dataType: int64
		lineageTag: 176f9fff-11ef-4793-bcef-c8d6c21afd1a
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c1cafd21-9edf-4998-addb-7bbeb6dfdfef
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 383c480b-37bb-4ad7-b425-7e01508830a7
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: ae03dd8b-3244-49fc-a4e8-60414ab8a646
			defaultHierarchy: LocalDateTable_9e9f0108-fb5b-45f2-81f5-aee5a692e792.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 41fccbb4-dd37-4caa-905f-8431b84b754e
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: b1eb65b6-f380-48f5-8336-c6c2e9bab7e1
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: e2579054-590c-46d9-ba3b-5a334e9898d8
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: 31d62ed0-3f5d-44ce-8bd5-6f1816de564d
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 6528ab13-70bd-455e-a879-83e5a187e6a0
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Abierto - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d20e1c5d-bae6-4c0d-aa78-570c1889da16
		summarizeBy: none
		sourceColumn: Abierto - Copy

		variation Variation
			isDefault
			relationship: 4a870ffb-6613-4206-a38c-2a3e4cd9dcc1
			defaultHierarchy: LocalDateTable_48ace1d0-5746-4488-beec-826e48998bb3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Sistema
		dataType: string
		lineageTag: 0db1c4f2-8b16-4a06-b442-b396aabfe150
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: int64
		lineageTag: 57b77d68-656d-4293-adc4-4e48b71d4725
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: 38da510c-364d-408a-a8f2-287d5359fabf
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 9fedcaae-11e7-40ef-b84c-73b425139786
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 0f8bf112-7d32-493c-a605-d3639c2eb590
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA (NY y MAD) - Abiertas_KGI13'[Número])
		lineageTag: 7247a6bf-e7ae-4649-b062-252f7c33f1ae
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 65c72963-eabe-445f-a8e8-6ff1ee74960e
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 725601e9-14ae-4126-90b1-06e7117b0e41
			defaultHierarchy: LocalDateTable_d1b60d63-5fd0-4153-a3e3-282f90c45b71.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: acda9502-b266-4326-8e5e-a129e11fa1c6
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA (NY y MAD) - Abiertas_KGI13-049ff6fb-5618-4fef-8ac0-00cc3137868a' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Source = #"PRO - Incidencias con SLA (NY y MAD) - Abiertas",
				
				    //Unificar Prioridades, según definición del KGI13
				    #"Replaced Value" = Table.ReplaceValue(Source, "Crítica", "Alta",Replacer.ReplaceText,{"Prioridad"})
				  
				in
				    #"Replaced Value"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

