table 'PRO - Jira - Defectos con SLA - UAT - Detalle'
	lineageTag: 892444a5-2bc5-44c6-8b51-41a4f2f95b75

	column Components
		dataType: string
		lineageTag: dbe45954-985a-4cf9-b074-a6c71cebaabb
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 3770bf71-96d4-4ddb-8adc-b72b5d4a2705
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: a70d8052-63ce-4c75-a965-e9f512bce59f
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: f7eb86b8-5a70-44f1-b5d9-f7148a36caab
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 8c1e3869-5bd1-4406-860d-eb980bb489f4
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: c87f78fd-4515-47c2-ab47-0d9d89951f0c
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 2aefc50a-0859-469d-9db9-4f45a8efd132
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: e098ae6e-30ec-47f2-b013-b6797382397d
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: a489aa80-def5-4b05-8cc8-0b62046d1b4d
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 9a31b761-6822-452e-b0c5-f1516c91ddb5
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 8827b11b-a208-4e1b-bf33-43ddfd5fae50
			defaultHierarchy: LocalDateTable_a7e540f8-d8f1-43a9-baf5-671c3905429b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: d0b83d2c-0590-450b-a9a8-f46b53397682
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: 7167ccee-164d-410c-9bc0-8c04a4b46b59
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: 6d34ac26-dad8-40a9-afb5-31bfc77a2f33
			defaultHierarchy: LocalDateTable_ca0bbf17-a230-456e-9ce5-8e984b1490b6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 43df1316-2213-4d62-a64d-373e937d7b84
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column 'Value (Bugs)'
		dataType: string
		lineageTag: 50a6399d-26f7-48bb-953b-34ce6131627f
		summarizeBy: none
		sourceColumn: Value (Bugs)

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Status'
		dataType: string
		lineageTag: c0c023d3-e15b-422d-9c7a-0f0de4b429dc
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5082d4aa-6d4f-4d07-876b-f5b018cdd3c1
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved

		variation Variation
			isDefault
			relationship: f15fba8a-f275-4288-a9b8-a94996d4e4db
			defaultHierarchy: LocalDateTable_9c8c4320-96ca-4704-b8af-f5f3d52e3c80.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status'
		dataType: string
		lineageTag: 3edaa5ef-2040-4f83-aab1-bf894add93fa
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Status

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba'
		dataType: string
		lineageTag: d8157213-f1b8-4e97-88cd-8db09a2ad851
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column 'PRO - Jira - Historias y Ejecuciones.Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 42a84b22-b010-4337-86fa-f9f87eb519e3
		summarizeBy: none
		sourceColumn: PRO - Jira - Historias y Ejecuciones.Resolved - Copy

		variation Variation
			isDefault
			relationship: c9ee0f53-4958-4eb9-89ee-85921411fc61
			defaultHierarchy: LocalDateTable_563af6ac-887b-46e1-a013-31f56f730335.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: 9fd29274-51fc-4b8a-ba40-141457a1af5c
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Defectos con SLA - UAT - Detalle-12eab267-1ac7-4501-b75a-7ffaf3903f0b' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = #"PRO - Jira - Defectos con SLA",
				
				    #"Filtered Rows" = Table.SelectRows(Source, each Text.Contains([#"PRO - Jira - Historias y Ejecuciones.PRO - Jira - Ejecuciones.Tipo de prueba"], "UAT")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each ([Estado_Alegación] <> "1 - Aprobada"))
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

