table 'PRO - Planificaciones PRJ y ENH con SLA - Incumplidas'
	lineageTag: 73efaf76-d42b-43b8-bb71-55775f90f6c0

	column Prioridad
		dataType: string
		lineageTag: e7f9a269-0467-45d6-8c2c-6b9b94914fcd
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6bcd56d4-4118-487d-bdcf-beee1f3905d5
		summarizeBy: none
		sourceColumn: Fecha fin real - Copy

		variation Variation
			isDefault
			relationship: ed40dea1-9f23-462b-9c96-83482be26a80
			defaultHierarchy: LocalDateTable_78257d1d-f0f2-4de7-b37f-1b1a24dfb4eb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Estimación Incumplida'
		dataType: double
		lineageTag: 54681628-7e45-4eb6-a29d-993293aa5188
		summarizeBy: sum
		sourceColumn: Estimación Incumplida

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'PRO - Planificaciones PRJ y ENH con SLA - Incumplidas-897bbd85-3dae-4c27-b0ca-b3e8fa06d500' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = #"PRO - Planificaciones PRJ y ENH con SLA",
				
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Estimación incumplida] = true)),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"Prioridad", "Fecha fin real - Copy"}, {{"Estimación Incumplida", each Table.RowCount(_), type number}})
				in
				    #"Grouped Rows"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegación

