table 'PRO - Planificaciones ENH'
	lineageTag: 07930892-57e0-4905-9697-dc59ad4d2abf

	column Demanda
		dataType: string
		lineageTag: 6dc35f4e-d194-4043-bf38-6c51c28f17da
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 27d6a2c4-7d49-40b0-94ff-08723472c0cf
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 39e1a02f-471a-4927-8392-a7a6b6008d65
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: 89763e31-6b0b-457f-b4f0-241963767e23
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: 29e1eda3-6bb1-478f-b658-7d2589f4064f
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 57541ea7-4a1a-42ca-8ee9-331959cb11e6
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variation
			isDefault
			relationship: f0ac69d1-74c4-477c-bbf3-25f8da328df2
			defaultHierarchy: LocalDateTable_befbb3cf-edff-4711-be3c-e4d621d8d9e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: e0137712-cf8b-4aa7-bf23-ad3242efba39
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variation
			isDefault
			relationship: e03c0d1d-d449-473a-9df5-c056ff95f569
			defaultHierarchy: LocalDateTable_6eea4b99-fcc3-4a06-b65b-48208e52226d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 5e093c4e-492f-4783-9a39-3c45884c298e
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: d2e6774e-ef59-4f57-8f46-077d9990ef4e
		summarizeBy: none
		sourceColumn: Inicio

		variation Variation
			isDefault
			relationship: 36e51c88-9c9e-4b5d-8ee2-886059cf8757
			defaultHierarchy: LocalDateTable_3dec0e66-0613-4adb-acfa-301fdf0b27c9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8bafe855-8593-491f-93cc-3f0e7cd55e30
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: adea5bb8-1431-45e3-8c6d-816ca9a188f9
			defaultHierarchy: LocalDateTable_540c6fb8-a493-4f6b-b868-407172f4dba2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8b1bd5d1-3a70-4caf-b91a-8a9f27d66fc7
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: 1d7a852b-7c39-42bc-9de6-c121f816a844
			defaultHierarchy: LocalDateTable_db190ea0-f337-4efb-be85-5370ece8b6d3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: 51a64ea0-90c8-4281-8263-8ac444fa1461
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: dc2802c2-ffaf-4425-8e4d-cd10fe6042ab
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 8cc6815e-7f52-46ad-841f-4903e5426373
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: abde8102-c96f-43ad-ad94-5f3d50d336de
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 337c40e0-e8a7-4c2e-bb6d-e31e7912424e
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: e1939702-05ea-48d6-9a9b-1deb484c61a7
		summarizeBy: none
		sourceColumn: Fin

		variation Variación
			isDefault
			relationship: 8b980dc9-786b-41d9-b32e-ceae08efff1f
			defaultHierarchy: LocalDateTable_645ed8d7-f95b-473f-a93f-1a7c8f96386f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones ENH-2190f109-9151-4b94-b221-5786518bc69d' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/AMS_MOV/Ficheros del Servicio/AMS_IAR_CDM_SLA_I_Planificaciones de MEJs" & xlsx, //& AMS_IAR_CDM_ & "Parámetros KGIs" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Promoted Headers",{{"Fecha de finalización derivada de", "Fecha final derivada de"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Número", type text}, {"Número_1", type text}, {"Nombre de subtarea", type text}, {"Prioridad", type text}, {"Abierto por", type text}, {"Grupo de asignación", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha fin planificada", type datetime}, {"Principal", type text}, {"Fecha Inicio Estimada", type datetime}, {"Fecha final derivada de", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Breve descripción", type text}}),
				    
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{
				        {"Número",                  "Demanda"},
				        {"Nombre de subtarea",      "Tipo de Proyecto"},  
				        {"Número_1",                "Número"}, 
				        {"Abierto por",             "Jefe de proyecto (Project Manager)"}, 
				        {"Grupo de asignación",     "Aplicación de Negocio "}, 
				        {"Principal",               "Nombre"}, 
				        {"Fecha Inicio Estimada",   "Inicio"}, 
				        {"Fecha final derivada de", "Fin"},
				        {"Breve descripción",       "Nombre de PRJ o MEJ"}}),
				    
				   //Homologa las prioridades
				    #"AllReplace" = [#"EN.EJE.EVODAT_EXT.AE" = "EM: DAT", #"EN.EJE.EVOMXM_EXT.AE" = "EM: MXM", #"EN.EJE.EVOOAT_EXT.AE" = "EM: OAT",#"EN.EJE.EVOWTM_EXT.AE" = "EM: WTM",#"EN.EJE.EVORDO_EXT.AE" = "EM: RDO Movil",#"EN.EJE.EVOHTFV_EXT.AE" = "HTFV",#"EN.EJE.EVOIOC_EXT.AE" = "IOC",#"EN.EJE.EVOMXMHTFV_EXT.AE" = "MXM-HTVF",#"EN.EJE.EVOWBCG_EXT.AE" = "Web Calendario de Guardias"],    
				    #"Replaced Value" = Table.TransformColumns(#"Renamed Columns",{{"Aplicación de Negocio ",each Record.FieldOrDefault(AllReplace,_,_)}}),
				
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value", null, "",Replacer.ReplaceValue,{"Nombre"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",null,"Mejora",Replacer.ReplaceValue,{"Tipo de Proyecto"})
				
				in
				    #"Replaced Value2"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

