table 'PRO - Incidencias con SLA (NY)'
	lineageTag: 273690a7-ab29-415e-abd4-98544a26db99

	column Número
		dataType: string
		lineageTag: da870085-6c75-4b10-ba0f-73ae65164485
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 736910b8-70ba-494a-8745-8786540c7a60
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Subcategoría
		dataType: string
		lineageTag: 3ebb512a-060a-4806-801f-7514a19716be
		summarizeBy: none
		sourceColumn: Subcategoría

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 67e8514a-f169-4703-901c-e53b33b60e9c
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: be8b7440-ffbb-4f73-8a5b-3cc4eccbdb95
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: 618c746f-c13d-4acd-8351-8b96ded3f049
			defaultHierarchy: LocalDateTable_9956014c-20d7-4ffd-aad1-abaa1933034e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: 3566c0d8-8e3a-4586-8847-ab702b15176e
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variation
			isDefault
			relationship: 3c6d2f1d-93d4-40c1-b28c-e59129435d72
			defaultHierarchy: LocalDateTable_9b37082e-1340-4c52-84e6-f843f0d5ab8c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 2699a2e5-77e2-4c41-9768-4c2ccc54563b
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 44f3afb2-2e15-43f2-a37a-46f75e1e93e8
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 44ca9b64-02c4-4509-9577-88b33b4a1879
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: 50d916eb-71f9-454b-9be4-1e63dc6b4feb
			defaultHierarchy: LocalDateTable_842716ec-50cb-4aa3-9510-61e1eea618e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 9d1e2ef3-c756-4f5c-aa02-9873456d6dcd
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 324c0443-4d82-4ce7-8c4b-e784e6c4597c
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: int64
		formatString: 0
		lineageTag: e7337c28-9daf-4368-bef2-2d7242e6abdc
		summarizeBy: sum
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 9aa8bd0c-bb34-48db-b4fb-9473162ea710
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: 41569162-545f-4745-9c40-e8d1eb09536c
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: int64
		lineageTag: 64107950-3f67-4416-9001-224b457a979f
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 58022218-6d85-4b97-b8c0-ad273b3f399a
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: d4ea4dc6-5530-4504-af12-122ee5558c5c
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: d4122f0c-eedf-4bf9-83df-57c5b719808d
			defaultHierarchy: LocalDateTable_77ed55a2-6194-449e-af68-72413b02e207.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 31897e63-dd53-4bb9-86b9-cd6fb5917a6f
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 4e9229ef-41af-4b89-a231-ba08c1fc24a6
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA (NY)-975bedd0-f3ff-45c0-b38f-d15ceeede48f' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				Entorno = Entorno,
				    BaseUrl = "https://acciona365.sharepoint.com",
				    RelativePath ="/sites/EN_TIC_COORD_" & Entorno & "/Documentos compartidos/CdM_SMO/CdM_AMS/AMS_MOV/Ficheros del Servicio/AMS_IAR_CDM_SLA_II_Incidencias" & xlsx, //& AMS_IAR_CDM_ & "Parámetros KGIs" & xlsx,
				    Origen = Excel.Workbook(Web.Contents(BaseUrl & RelativePath), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Número", type text}, {"Breve descripción", type text}, {"Subcategoría", type text}, {"Prioridad", type text}, {"Abierto", type datetime}, {"Cerrado", type datetime}, {"Resuelto", type datetime}, {"Duración", Int64.Type}, {"Duración del negocio", Int64.Type}, {"Infringido", type logical}, {"Tiempo original de incumplimiento", type datetime}, {"Estado del incidente", type text}, {"Etapa", type text}, {"Código de resolución", type text}, {"Volver a abrir recuento", Int64.Type}, {"Tipo de Solución", type text}, {"Duración_1", Int64.Type}, {"Porcentaje de negocio trascurrido", Int64.Type}}),
				
				//Homologa las prioridades
				    #"AllReplace" = [#"1 - Crítica" = "Alta", #"2 - Alta" = "Alta", #"3 - Moderada" = "Media",#"4 - Baja" = "Baja",#"5 - Muy Baja" = "Baja",#"3 - Media" = "Media"],    
				    #"Replaced Value" = Table.TransformColumns(#"Changed Type",{{"Prioridad",each Record.FieldOrDefault(AllReplace,_,_)}}),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"Resuelto", "Fecha de resolución"}, {"Duración del negocio", "Duración real"}, {"Etapa", "Estado SLA"}, {"Estado del incidente", "Estado"}, {"Código de resolución", "Código de cierre"}, {"Volver a abrir recuento", "Reabierta"}, {"Tipo de Solución", "Tipo de solución"}, {"Duración_1", "Duración SLA"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

