table 'PRO - Alegaciones del Servicio KGI24'
	lineageTag: 4b8c838a-0686-4980-8008-740dbcd74d77

	column ID
		dataType: string
		lineageTag: 60d4f6f8-7f1c-443f-ab08-b537d767dc53
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Entrada alegada'
		dataType: string
		lineageTag: 1d321cc9-d5ce-49d1-960d-52a464edb311
		summarizeBy: none
		sourceColumn: Entrada alegada

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: 43bbf91c-c12e-4c26-ac33-8985256a8390
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: string
		lineageTag: 50419cf2-c9fa-4c39-b172-c01434df9e97
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		annotation SummarizationSetBy = Automatic

	column Clasificación
		dataType: string
		lineageTag: f0c33c6f-214c-47f2-bd5b-2f908f34d59b
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 6bcab134-cecc-46ef-a3e8-79848705d44d
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: 9001fa74-9536-4c0d-8e79-29eb97e975c7
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 235d6cdc-d20d-406a-9076-659b006fa199
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: 4e8bbccd-60bf-4dfe-bab2-dc8e7c194d8b
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: cf76f215-fe33-405a-b826-e33e10498ddf
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado - Copy

		variation Variación
			isDefault
			relationship: 30e52f16-a79b-48e5-9126-8f73d45f0e7c
			defaultHierarchy: LocalDateTable_acb4ecf6-b85c-4566-9263-8eae4db29203.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Comentarios AE'
		dataType: string
		lineageTag: 3318a8dd-bff7-4eb5-a655-7e3cddfb20ad
		summarizeBy: none
		sourceColumn: Comentarios AE

		annotation SummarizationSetBy = Automatic

	column Columna1
		dataType: string
		lineageTag: efc52c24-cd4b-45d9-b3c7-0f179733ef8a
		summarizeBy: none
		sourceColumn: Columna1

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI24-cf443284-1583-4b3f-bcca-529ee2a0ce62' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Source = #"PRO - Alegaciones del Servicio",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([ANS] = "KGI 2-4"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

