table 'PRO - Incidencias con SLA (NY y MAD) - Abiertas'
	lineageTag: 2d21dd48-3a4f-46df-bf4b-9f46b8471ff5

	column Número
		dataType: string
		lineageTag: 975334d5-1640-4fdc-8b99-4450489e18cd
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: a77070cd-5630-4ef6-85c9-83751c639e84
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: 4efc3d40-5cc9-41b1-a59f-e1cd80e8f492
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: c8116a4c-3e72-4f53-b3cf-761309a99250
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: b66f2944-0ce5-4148-b5ec-79af223a36df
		summarizeBy: none
		sourceColumn: Abierto

		variation Variation
			isDefault
			relationship: 3b72396e-4dad-4fb6-9e29-5c970a061920
			defaultHierarchy: LocalDateTable_f0e8f3ee-5944-496c-847f-5fed64464983.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: a1f05839-ff07-4360-a3de-e51b6540372e
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: b1b25c2b-d9ec-42d5-9f1f-501a968ae94e
			defaultHierarchy: LocalDateTable_b0a601c1-f5c2-4f69-9ade-5e19c8ea8131.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: d0842ff5-202c-44f1-b647-1dd5de765f8f
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variation
			isDefault
			relationship: c431fa6b-dcd5-4fc6-bae7-2aa1ffed8db3
			defaultHierarchy: LocalDateTable_2b6e293b-ce94-47bc-913f-13e106374b16.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		lineageTag: 41db24d2-22cd-496c-b1de-a06a94e77e25
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real'
		dataType: int64
		lineageTag: 0204ec8d-2b91-49ff-a0bf-79a93ddbe59c
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1de47b9c-81d1-4b56-aeda-c5b977c1aa97
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: b8a66244-2c8a-4529-82c6-c31137a61868
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: f9710d8b-9664-4b6f-a99e-2469a270e57e
			defaultHierarchy: LocalDateTable_88e07209-1c25-4940-a3cf-9f34af6a454f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 3ddfa92d-96c6-48a5-8eff-96a23e032011
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 6fab4d96-7613-449e-8745-a1a1e79c94e9
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 30683108-070d-4185-bbfb-7f339d852fcb
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: 1cb27fa6-7dd2-4af3-b658-3142e2f78ccd
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 203a16e8-0e2e-40e0-9684-f882b2da0940
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Abierto - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5954e7f8-a09e-4baf-b6b3-daac8f8e9534
		summarizeBy: none
		sourceColumn: Abierto - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Porcentaje de negocio trascurrido'
		dataType: int64
		lineageTag: e8df114d-27ee-4bdb-9b1c-1833e465bfca
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: eecab768-208b-46e1-9b15-e3dd203bdb29
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 0f644368-9850-4304-a7f9-c18d6895b246
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: fea41b88-47e7-4346-9bb2-ada3eaf54d97
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA (NY y MAD) - Abiertas'[Número])
		lineageTag: 619c9ea8-8db5-4724-b80b-db23530d46f3
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 853487fd-28d1-4802-9cc4-c83b091c67bb
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA (NY y MAD) - Abiertas-4a3c2bdf-d9cf-4cdd-9832-99d81a25d932' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Origen = #"PRO - Incidencias con SLA (NY y MAD) - Abiertas (staging)",
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Número", type text}, {"Breve descripción", type text}, {"Subcategoría", type text}, {"Prioridad", type text}, {"Abierto", type datetime}, {"Cerrado", type datetime}, {"Fecha de resolución", type datetime}, {"Duración", Int64.Type}, {"Duración real", Int64.Type}, {"Infringido", type logical}, {"Tiempo original de incumplimiento", type datetime}, {"Estado", type text}, {"Estado SLA", type text}, {"Código de cierre", type text}, {"Reabierta", type logical}, {"Tipo de solución", type text}, {"Duración SLA", Int64.Type}, {"Porcentaje de negocio trascurrido", Int64.Type}}),
				
				    #"Appended Query" = Table.Combine({#"Tipo cambiado", #"PRO - Incidencias con SLA (NY)"}),
				
				    #"Filtered Rows" = Table.SelectRows(#"Appended Query", each [Estado SLA] <> "Cancelado"),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each not Text.StartsWith([Estado], "Cancelado")),
				    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each (
				        [Código de cierre] = "" or 
				        [Código de cierre] = "No user response" or 
				        [Código de cierre] = "Solucionado en remoto" or 
				        [Código de cierre] = "Solucionado nivel 2" or 
				        [Código de cierre] = "solucionado ON-SITE" or 
				        [Código de cierre] = "Solucionado Temporalmente" or 
				        [Código de cierre] = "Solucionado mail" or 
				        [Código de cierre] = "Solucionado por teléfono" or 
				        [Código de cierre] = "Solucionado (solución temporal)" or 
				        [Código de cierre] = "Solucionado (de forma permanente)" or 
				        [Código de cierre] = "Solucionado remotamente (solución temporal)" or 
				        [Código de cierre] = "Solucionado remotamente (de forma permanente)")),
				
				    #"Duplicated Column" = Table.DuplicateColumn(#"Filtered Rows2", "Abierto", "Abierto - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Abierto - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Abierto - Copy", Date.StartOfMonth, type date}}),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Calculated Start of Month",{{"Subcategoría", "Sistema"}}),
				     //Une con tabla de alegaciones KGI13_23
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Número"}, #"PRO - Alegaciones del Servicio KGI13_23", {"ID"}, "PRO - Alegaciones del Servicio KGI13_23", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio KGI13_23" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio KGI13_23", {"ANS", "Estado"}, {"PRO - Alegaciones del Servicio KGI13_23.ANS", "PRO - Alegaciones del Servicio KGI13_23.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio KGI13_23",{{"PRO - Alegaciones del Servicio KGI13_23.ANS", "ANS_Alegado"}, {"PRO - Alegaciones del Servicio KGI13_23.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Estado" si la alegación es aceptada
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1",each [Estado],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "03 - KGI 1-3" then "Cancelado" else [Estado],Replacer.ReplaceValue,{"Estado"}),
				
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",each [Estado],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "10 - KGI 2-3" then "Cancelado" else [Estado],Replacer.ReplaceValue,{"Estado"}),
				    #"Filtered Rows3" = Table.SelectRows(#"Replaced Value1", each not Text.StartsWith([Estado], "Cancelado")),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows3", {"Número"}),
				    #"Filas filtradas" = Table.SelectRows(#"Removed Duplicates", each ([Cerrado] <> null))
				in
				    #"Filas filtradas"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegación

