table 'PRO - Planificaciones PRJ y ENH con SLA'
	lineageTag: 8533aa7b-24dd-403a-aa0f-6318df89a26f

	column Demanda
		dataType: string
		lineageTag: 5b2d2ed0-b650-4dcb-857d-a662f7f6e774
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: c761d4f2-b5d6-4dfe-9f1f-1d8515718bea
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 74f4e018-1f52-499a-9992-147327a12e48
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9b70f85f-373d-435c-9ca3-3d3f67654459
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variation
			isDefault
			relationship: fd4b799a-e636-4850-9165-5103041c1f6e
			defaultHierarchy: LocalDateTable_cbe44c7a-b1cf-4d00-a27e-e5063836a862.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5b631c49-d3c7-43e0-8ed2-a6c6c4909d31
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variation
			isDefault
			relationship: e83269ba-b99f-4ef6-ad9d-87bc25520034
			defaultHierarchy: LocalDateTable_f70a1ef5-4887-4557-b5ab-13907149e605.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: b6de8f8b-f31b-42c6-bf3a-20ae179c6a71
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: ef77cd7c-7025-499d-9da5-92a686b97ddc
		summarizeBy: none
		sourceColumn: Inicio

		variation Variation
			isDefault
			relationship: 2fc0c468-7c8c-4a4a-8d0c-cfdca082f41f
			defaultHierarchy: LocalDateTable_3b7dc721-8d9d-4a09-9c14-c575fb4024ba.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: 7d99a2b3-3148-4eb2-a06c-749211002159
		summarizeBy: none
		sourceColumn: Fin

		variation Variation
			isDefault
			relationship: ae7d02c7-d061-4a82-b922-a24f4616d1cc
			defaultHierarchy: LocalDateTable_e52f7151-aa87-4747-a6fb-0c6eebaf8376.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2cd7206f-1900-489a-a23e-695f92cef4ee
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: ec56ba0a-0bdc-48be-9b65-11f245a7f2fe
			defaultHierarchy: LocalDateTable_c2eadd93-34ab-4f0b-8e7d-d7f09e29571b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: de8574cb-aab8-41d4-ad82-89cc5617f724
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: a8b0b940-9db3-4cdb-8e34-9cc0cdda63cf
			defaultHierarchy: LocalDateTable_909091cb-d835-454e-a1a9-e5c4cc0f6e39.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: a7e3c87a-f649-4193-ae90-6fb002b6c824
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: 1240f5eb-c143-478f-9ecb-c5cfc0f139fd
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: ae906654-34f9-497a-b58e-792ec04c2cfd
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0da4ae42-e262-4fe7-b736-0642342b89e1
		summarizeBy: none
		sourceColumn: Fecha fin real - Copy

		variation Variation
			isDefault
			relationship: 607894f4-8844-4c45-9eee-454ef429b4c6
			defaultHierarchy: LocalDateTable_42c6b304-4b9d-43fd-9680-f3686fcd5203.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: 9f866dfc-1986-46df-b587-2c6caef71ded
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: 1a0415ea-2c8a-4bd7-83a2-16a2251f6abf
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Duración Planificada LB'
		dataType: double
		lineageTag: 7681ce7e-0306-4209-9cc7-63be6c1bd1d2
		summarizeBy: sum
		sourceColumn: Duración Planificada LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real LB'
		dataType: double
		lineageTag: 6cb9c07e-505b-4254-984c-e1e35980e26b
		summarizeBy: sum
		sourceColumn: Duración real LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa de desviación'
		dataType: double
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: ec273dba-d6ea-438f-a627-08764801e462
		summarizeBy: sum
		sourceColumn: Tasa de desviación

		annotation SummarizationSetBy = Automatic

	column 'Estimación incumplida'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 340ce681-3282-4adb-b735-e2dc2ba07ce3
		summarizeBy: none
		sourceColumn: Estimación incumplida

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 6652cbf3-8657-4b1a-ad71-36c7538d1701
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 35ab93a5-cf56-4a22-9a74-6f70b1af70b1
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: 15d3a07a-820b-428e-b595-772a0cb4047a
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Planificaciones PRJ y ENH con SLA'[Número])
		lineageTag: 955ad556-0422-4066-a03d-595b8a1a2250
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Fecha límite planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: f6cee3f5-7a2d-4e38-a701-c6fcc34dfecf
		summarizeBy: none
		sourceColumn: Fecha límite planificada

		variation Variación
			isDefault
			relationship: bbbcd01d-9b9b-41fc-9570-9181bcfa5f1d
			defaultHierarchy: LocalDateTable_177c8379-a886-47ee-bcd0-2b47ea6c2ff8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones PRJ y ENH con SLA-c4488ef7-b8a5-455a-a73c-cefca85f53ea' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Source = #"PRO - Planificaciones PRJ y ENH con SLA (staging)",
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Promoted Headers",{{"Fecha de finalización planificada", "Fecha límite planificada"}}),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Demanda", type text}, {"Número", type text}, {"Tipo de Proyecto", type text}, {"Prioridad", type text}, {"Jefe de proyecto (Project Manager)", type text}, {"Aplicación de Negocio ", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha límite planificada", type datetime}, {"Nombre", type text}, {"Inicio", type datetime}, {"Fin", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Nombre de proyecto", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Nombre de proyecto", "Nombre de PRJ o MEJ"}}),
				
				    //Filtro por solo proyectos y mejoras de aplicaciones a cargo del proveedor iAR
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([#"Aplicación de Negocio "] 
				    = "EM: DAT" or          [#"Aplicación de Negocio "] 
				    = "EM: MXM" or          [#"Aplicación de Negocio "] 
				    = "EM: OAT" or          [#"Aplicación de Negocio "] 
				    = "EM: WTM" or          [#"Aplicación de Negocio "] 
				    = "EM: RDO Movil" or    [#"Aplicación de Negocio "] 
				    = "HTFV" or             [#"Aplicación de Negocio "] 
				    = "IOC" or              [#"Aplicación de Negocio "] 
				    = "MXM-HTVF" or         [#"Aplicación de Negocio "] 
				    = "Web Calendario de Guardias")    
				    and ([Tipo de Proyecto] <> "Mantenimiento de Aplicaciones")),
				
				    //Une tablas de Mejoras y Proyectos de Mantenimiento de Aplicaciones
				    #"Appended Query" = Table.Combine({#"Filtered Rows", #"PRO - Planificaciones ENH"}),
				    #"Appended Query1" = Table.Combine({#"Appended Query", #"PRO - Planificaciones MA"}),
				
				    #"Replaced Value" = Table.ReplaceValue(#"Appended Query1",      "1 - Crítica",  "Alta",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",      "2 - Alta",     "Alta",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",     "3 - Moderada", "Media",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",     "4 - Baja",     "Baja",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3",     "5 - Muy Baja", "Baja",Replacer.ReplaceText,{"Prioridad"}),
				    
				    //Nueva columna "Fecha (1er día de mes)"
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced Value4", "Fecha fin real", "Fecha fin real - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Fecha fin real - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Fecha fin real - Copy", Date.StartOfMonth, type date}}),
				
				    //Nueva columna "Duración planificada de línea base"    
				    #"Added Custom1" = Table.AddColumn(#"Calculated Start of Month", "Duración Planificada LB", each [Fin]-[Inicio]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Duración Planificada LB", type number}}),
				
				   //Nueva columna "Duración real para cálculo con planificación de línea base" 
				    #"Added Custom2" = Table.AddColumn(#"Changed Type1", "Duración real LB", 
				    each if [Nombre] <> "" then ([Fecha fin real]-[Fecha de inicio real]) else ""),
				    
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom2",{{"Duración real LB", type number}}),
				
				    //Nueva columna "Tasa de desviación"
				    #"Added Custom3" = Table.AddColumn(#"Changed Type2", "Tasa de desviación",
				    each if [Nombre] = "" then (([Duración real]-[Duración planificada])/[Duración planificada]) 
				                          else (([Duración real LB]-[Duración Planificada LB])/[Duración Planificada LB])),
				 
				    //Quita los proyectos y mejoras que tienen por error duración real o planificada = 0
				    #"Filtered Rows1" = Table.SelectRows(#"Added Custom3", each ([Duración real] <> 0) and ([Duración planificada] <> 0)),
				
				    //Columna "Estimación incumplida"
				    #"Added Custom4" = Table.AddColumn(#"Filtered Rows1", "Estimación incumplida",
				    each if [Prioridad]="Alta" and [Tasa de desviación]>0 then "TRUE" else
				         if [Prioridad]="Media" and [Tasa de desviación]>0.05 then "TRUE" else
				         if [Prioridad]="Baja" and [Tasa de desviación]>0.10 then "TRUE" else "FALSE"),
				
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom4",{{"Tasa de desviación", Percentage.Type}}),
				
				    //Une con las alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type3", {"Número"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"Estado"}, {"PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Estimación incumplida" si la alegación es aceptada
				    #"Replaced Value5" = Table.ReplaceValue(#"Renamed Columns1",each [Estimación incumplida],each if [Estado_Alegación] = "1 - Aprobada" then "FALSE" else [Estimación incumplida],Replacer.ReplaceValue,{"Estimación incumplida"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Replaced Value5",{{"Estimación incumplida", type logical}})
				in
				    #"Tipo cambiado"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegación

