table 'Resumen KGI16'
	lineageTag: 440464bd-a817-4a17-8727-ce1d14daa39e

	column 'Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d87743b6-c5e3-40f4-9c52-c194a93e22b9
		summarizeBy: none
		sourceColumn: Resolved - Copy

		variation Variation
			isDefault
			relationship: e1895520-a459-4bac-8806-ecc048235f3f
			defaultHierarchy: LocalDateTable_91fdb6db-fd87-457b-926b-be377f7ed896.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Tipo
		dataType: string
		lineageTag: e1e6fab1-adc1-475d-8829-9897bdbb120d
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column 'Pruebas Funcionales'
		dataType: double
		formatString: 0
		lineageTag: f0a009c3-617b-4f71-b5eb-a809c4006e39
		summarizeBy: sum
		sourceColumn: Pruebas Funcionales

		annotation SummarizationSetBy = Automatic

	column 'Defectos Funcionales'
		dataType: double
		formatString: 0
		lineageTag: fd8dc12f-fec7-4acb-b7c3-232a4da6c38e
		summarizeBy: sum
		sourceColumn: Defectos Funcionales

		annotation SummarizationSetBy = Automatic

	column 'Tasa de desviación máxima %'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 9f1ecdba-2eca-47bc-8724-75101e1c86f8
		summarizeBy: sum
		sourceColumn: Tasa de desviación máxima %

		annotation SummarizationSetBy = Automatic

	column 'Peso del KGI %'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 0c1f9afe-df01-4eff-a8f4-aa8997109710
		summarizeBy: sum
		sourceColumn: Peso del KGI %

		annotation SummarizationSetBy = Automatic

	column 'Puntos de KGI16'
		dataType: int64
		formatString: 0
		lineageTag: 39aa172f-cf7a-4742-b25c-7916fd4b3678
		summarizeBy: sum
		sourceColumn: Puntos de KGI16

		annotation SummarizationSetBy = Automatic

	column KGI
		dataType: string
		lineageTag: 36fcf6eb-0d96-4356-8ba1-759ac9d39a4a
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	column 'Tasa Real %' = ('Resumen KGI16'[Defectos Funcionales])/'Resumen KGI16'[Pruebas Funcionales]
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: cdf6241f-5f9d-4ff7-ba87-b77274f16393
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ¿Cumple? = IF('Resumen KGI16'[Tasa Real %]<='Resumen KGI16'[Tasa de desviación máxima %],"Si","No")
		lineageTag: 591e859a-88f4-4c54-925f-12c17eed37e0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Peso Obtenido %' = IF('Resumen KGI16'[¿Cumple?]="Si",'Resumen KGI16'[Peso del KGI %],0)
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: d626c672-c43f-44ed-b0c3-c1aa7def4dab
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Peso No Obtenido %' = IF('Resumen KGI16'[¿Cumple?]="No",'Resumen KGI16'[Peso del KGI %],0)
		lineageTag: 08455704-d932-452e-9c1d-01065d1cb02b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Resumen KGI16-33bcd950-ab30-4ebb-bd13-a83b008ca720' = m
		mode: import
		queryGroup: Resumen
		source =
				let
				    Source = #"PRO - Jira - Pruebas con SLA",
				
				    #"Filtered Rows" = Table.SelectRows(Source, each Text.Contains([Tipo de prueba], "Funcionales")),
				
				    //Agrupación por número de pruebas por Historias con Estado = Cerrado
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"PRO - Jira - Historias.Resolved - Copy", "Priority"}, {{"Pruebas Funcionales", each Table.RowCount(_), type number}}),
				
				    //Une con tabla de defectos Funcionales
				    #"Merged Queries" = Table.NestedJoin(#"Grouped Rows", {"PRO - Jira - Historias.Resolved - Copy", "Priority"}, #"PRO - Jira - Defectos con SLA - FUN", {"PRO - Jira - Historias y Ejecuciones.Resolved - Copy", "Priority"}, "PRO - Jira - Defectos con SLA - FUN", JoinKind.LeftOuter),
				    #"Expanded PRO - Jira - Defectos con SLA - FUN" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Jira - Defectos con SLA - FUN", {"Defectos Funcionales"}, {"PRO - Jira - Defectos con SLA - FUN.Defectos Funcionales"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded PRO - Jira - Defectos con SLA - FUN",{{"PRO - Jira - Defectos con SLA - FUN.Defectos Funcionales", "Defectos Funcionales"}}),
				
				    //Une con tabla de Parámetros
				    #"Merged Queries1" = Table.NestedJoin(#"Renamed Columns", {"Priority"}, #"Parametros KGI16", {"Prioridad"}, "Parametros KGI1-6", JoinKind.LeftOuter),
				    #"Expanded Parametros KGI1-6" = Table.ExpandTableColumn(#"Merged Queries1", "Parametros KGI1-6", {"Tasa de desviación máxima %", "Peso del KGI %", "Puntos de KGI16", "KGI"}, {"Parametros KGI1-6.Tasa de desviación máxima %", "Parametros KGI1-6.Peso del KGI %", "Parametros KGI1-6.Puntos de KGI16", "Parametros KGI1-6.KGI"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Parametros KGI1-6",{{"Parametros KGI1-6.Tasa de desviación máxima %", "Tasa de desviación máxima %"}, {"Parametros KGI1-6.Peso del KGI %", "Peso del KGI %"}, {"Parametros KGI1-6.Puntos de KGI16", "Puntos de KGI16"}, {"Parametros KGI1-6.KGI", "KGI"}, {"PRO - Jira - Historias.Resolved - Copy", "Resolved - Copy"}, {"Priority", "Tipo"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

