table 'Resumen KGI17'
	lineageTag: 0b221f0e-3142-4cf7-989c-02cfac2c46a9

	column 'Total Propuestas'
		dataType: int64
		formatString: 0
		lineageTag: 07da2f47-c59e-4af9-9135-6be1981224e4
		summarizeBy: sum
		sourceColumn: Total Propuestas

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column KGI
		dataType: string
		lineageTag: 5ce118eb-865f-4708-a289-5bbe357c92cd
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	column 'Propuestas rechazadas'
		dataType: int64
		formatString: 0
		lineageTag: 07bd8bbe-f42a-423a-82a3-1e4176180c00
		summarizeBy: sum
		sourceColumn: Propuestas rechazadas

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Tasa real %' = ('Resumen KGI17'[Total Propuestas]-'Resumen KGI17'[Propuestas rechazadas])/'Resumen KGI17'[Total Propuestas]
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 35f71778-9e45-43ff-b2a0-b6cfd986dfb9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Fecha de Medición KGI'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1458646f-d55a-44b7-9b79-acb1d1e8ccda
		summarizeBy: none
		sourceColumn: Fecha de Medición KGI

		variation Variation
			isDefault
			relationship: 8818f00d-a545-437e-b0d0-04f7c8b2eae9
			defaultHierarchy: LocalDateTable_160de622-d32f-4e8e-8612-4a91b7285907.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ¿Cumple? = IF('Resumen KGI17'[Total Propuestas]>=3,IF('Resumen KGI17'[Tasa real %]>='Resumen KGI17'[Tasa de aprobación objetivo %],"Sí","No"),"No")
		lineageTag: 8f5ae20e-fe57-4305-9382-45135e0a54a3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Tasa de aprobación objetivo %'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 19c391dc-06ee-41eb-9dce-9fd50cf12468
		summarizeBy: sum
		sourceColumn: Tasa de aprobación objetivo %

		annotation SummarizationSetBy = Automatic

	column 'Mínimo de propuestas por trimestre'
		dataType: int64
		formatString: 0
		lineageTag: ef41a4bc-7d6d-4d43-9289-df475e8d7e25
		summarizeBy: sum
		sourceColumn: Mínimo de propuestas por trimestre

		annotation SummarizationSetBy = Automatic

	column 'Peso del KGI %'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: d3e14fad-c3d1-4329-98a2-727e707aceca
		summarizeBy: sum
		sourceColumn: Peso del KGI %

		annotation SummarizationSetBy = Automatic

	column 'Puntos de KGI17'
		dataType: int64
		formatString: 0
		lineageTag: de3c6e4c-bd8f-4119-a467-906ef505d560
		summarizeBy: sum
		sourceColumn: Puntos de KGI17

		annotation SummarizationSetBy = Automatic

	column 'Peso Obtenido %' = IF('Resumen KGI17'[¿Cumple?]="Sí",'Resumen KGI17'[Peso del KGI %],0)
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: e68ae275-d0ca-4203-b672-a78f04266478
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Peso No Obtenido %' = IF('Resumen KGI17'[¿Cumple?]="No",'Resumen KGI17'[Peso del KGI %],0)
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 06d4b523-9d13-4617-b8c3-88ad83c7cb76
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Resumen KGI17-9b1210f8-1db9-4268-934b-6cbbe3e16d76' = m
		mode: import
		queryGroup: Resumen
		source =
				let
				    Source = #"PRO - Mejoras propuestas",
				    #"Grouped Rows" = Table.Group(Source, {"Fecha de Medición KGI"}, {{"Total Propuestas", each Table.RowCount(_), type number}}),
				
				    #"Merged Queries" = Table.NestedJoin(#"Grouped Rows", {"Fecha de Medición KGI"}, #"PRO - Mejoras propuestas - Rechazadas", {"Fecha de Medición KGI"}, "PRO - Mejoras propuestas - Rechazadas", JoinKind.LeftOuter),
				    #"Expanded PRO - Mejoras propuestas - Rechazadas" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Mejoras propuestas - Rechazadas", {"Propuestas rechazadas"}, {"Propuestas rechazadas"}),
				
				    //Crear Columna para relacionar tabla de parámetros
				    #"Added Custom" = Table.AddColumn(#"Expanded PRO - Mejoras propuestas - Rechazadas", "KGI", each "KGI1-7"),
				
				    #"Merged Queries1" = Table.NestedJoin(#"Added Custom", {"KGI"}, #"Parametros KGI17", {"KGI"}, "Parametros KGI17", JoinKind.LeftOuter),
				    #"Expanded Parametros KGI17" = Table.ExpandTableColumn(#"Merged Queries1", "Parametros KGI17", {"Tasa de aprobación objetivo %", "No. Mínimo de propuestas por trimestre", "Peso del KGI %", "Puntos de KGI17"}, {"Tasa de aprobación objetivo %", "Mínimo de propuestas por trimestre", "Peso del KGI %", "Puntos de KGI17"}),
				    #"Filas filtradas" = Table.SelectRows(#"Expanded Parametros KGI17", each ([Fecha de Medición KGI] <> null))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

