table 'Resumen KGI13_1_Críticas/Altas'
	lineageTag: f3a701fe-c358-47b9-81d0-61ff8a2b4e8f

	measure 'Puntos de KGI13_M_A' =
			
			var _KGI13_V = MIN('Resumen KGI13_1_Críticas/Altas'[Puntos de KGI13])
			return
			IF(ISBLANK(_KGI13_V),15,_KGI13_V)
		formatString: 0
		lineageTag: 5fbe0ff6-868b-4124-9690-0fc4a269cc70

	column Prioridad
		dataType: string
		lineageTag: 192ae0a0-58af-4e26-bd3f-db0d3eb9ebb7
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Abierto - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3f661a03-99b3-4d33-86fa-439703c61544
		summarizeBy: none
		sourceColumn: Abierto - Copy

		variation Variation
			isDefault
			relationship: a9a73d7b-c742-4d3b-abab-0ed19da3d9cd
			defaultHierarchy: LocalDateTable_a05f5ad7-342d-4398-a911-6cc04ed0653f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Total Incidencias'
		dataType: double
		formatString: 0
		lineageTag: a274ad06-581a-46a7-8e8c-bfb8aa08e280
		summarizeBy: sum
		sourceColumn: Total Incidencias

		annotation SummarizationSetBy = Automatic

	column 'Tasa máxima permitida %'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 3a8b757c-fb5f-4be1-8931-43243b68af78
		summarizeBy: sum
		sourceColumn: Tasa máxima permitida %

		annotation SummarizationSetBy = Automatic

	column 'Peso del KGI %'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: fe39ec2f-4078-4d96-a425-fe4038c3505e
		summarizeBy: sum
		sourceColumn: Peso del KGI %

		annotation SummarizationSetBy = Automatic

	column 'Puntos de KGI13'
		dataType: int64
		formatString: 0
		lineageTag: 78d3b6ca-2b63-4bcf-8dc1-890ebfd0c3c3
		summarizeBy: sum
		sourceColumn: Puntos de KGI13

		annotation SummarizationSetBy = Automatic

	column KGI
		dataType: string
		lineageTag: 77f9d1fd-0565-458c-b0f1-24c171204377
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	column ¿Cumple? = [KGI13_P1 ¿Cumple?_M]
		lineageTag: 584647cd-018a-456f-b270-79f408fcd6c8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Resumen KGI13_1_Críticas/Altas-ab21f325-a94e-4538-a98a-fdbe6a03b45b' = m
		mode: import
		queryGroup: Resumen
		source = ```
				let
				    Source = #"PRO - Incidencias con SLA (NY y MAD) - Abiertas",
				
				    //Total Incidencias Abiertas por Prioridad
				    #"Grouped Rows" = Table.Group(Source, {"Prioridad", "Abierto - Copy"}, {{"Total Incidencias", each Table.RowCount(_), type number}}),
				
				    //Unificar Prioridades, según definición del ANS
				    #"Replaced Value" = Table.ReplaceValue(#"Grouped Rows",     "1 - Crítica",  "Alta",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",  "2 - Alta",     "Alta",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1", "3 - Moderada", "Media",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2", "4 - Baja",     "Baja",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3", "5 - Muy Baja", "Baja",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4", "Crítica",      "Alta",Replacer.ReplaceText,{"Prioridad"}),
				  
				    //Unir Tabla de Parámetros
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value5", {"Prioridad"}, #"Parametros KGI13", {"Prioridad "}, "Parametros KGI1-3 (2)", JoinKind.LeftOuter),
				    #"Expanded Parametros KGI1-3" = Table.ExpandTableColumn(#"Merged Queries", "Parametros KGI1-3 (2)", {"Tasa máxima permitida %", "Peso del KGI %", "Puntos de KGI13", "KGI"}, {"Parametros KGI1-3 (2).Tasa máxima permitida %", "Parametros KGI1-3 (2).Peso del KGI %", "Parametros KGI1-3 (2).Puntos de KGI13", "Parametros KGI1-3 (2).KGI"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Parametros KGI1-3",{{"Parametros KGI1-3 (2).Tasa máxima permitida %", "Tasa máxima permitida %"}, {"Parametros KGI1-3 (2).Peso del KGI %", "Peso del KGI %"}, {"Parametros KGI1-3 (2).Puntos de KGI13", "Puntos de KGI13"}, {"Parametros KGI1-3 (2).KGI", "KGI"}}),
				
				    //Filtro por "Altas"
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Prioridad] = "Alta")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Tasa máxima permitida %", Percentage.Type}, {"Peso del KGI %", Percentage.Type}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

