table Aplicaciones
	lineageTag: 5ee7944d-be26-4834-932c-7c099efac9c4

	column 'Aplicación identificada por Energía'
		dataType: string
		lineageTag: 4ee594e6-c1f7-4f01-a2e1-4954d4ec3759
		summarizeBy: none
		sourceColumn: Aplicación identificada por Energía

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio'
		dataType: string
		lineageTag: 273d3b06-c1a9-42b2-95ec-be0fab329353
		summarizeBy: none
		sourceColumn: Aplicación de Negocio

		annotation SummarizationSetBy = Automatic

	partition Aplicaciones-e0f50377-e90e-488e-8d7f-7843b52d9001 = m
		mode: import
		source =
				let
				    URL = sharepointSource & Entorno,
				    URLcompleta = sharepointSource & Entorno & sharepointSource2,
				    Origen = SharePoint.Files(URL, [ApiVersion = 15]),
				    #"Filas filtradas0" = Table.SelectRows(Origen, each ([Extension] = ".xlsx") and ([Name] = "Aplicaciones.xlsx")),
				    #"Filas filtradas" = Table.SelectRows(#"Filas filtradas0", each ([Extension] = ".xlsx") and ([Name] = "Aplicaciones.xlsx") and ([Folder Path] = URLcompleta)),
				    #"Archivos ocultos filtrados1" = Table.SelectRows(#"Filas filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar función personalizada1" = Table.AddColumn(#"Archivos ocultos filtrados1", "Transformar archivo (2)", each #"Transformar archivo (2)"([Content])),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Invocar función personalizada1", {"Name", "Source.Name"}),
				    #"Otras columnas quitadas1" = Table.SelectColumns(#"Columnas con nombre cambiado1", {"Source.Name", "Transformar archivo (2)"}),
				    #"Columna de tabla expandida1" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Transformar archivo (2)", Table.ColumnNames(#"Transformar archivo (2)"(#"Archivo de ejemplo (2)"))),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna de tabla expandida1",{{"Source.Name", type text}, {"Column1", type text}, {"Column2", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Source.Name"}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Columnas quitadas", [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Aplicación identificada por Energía", type text}, {"Aplicación de Negocio", type text}})
				in
				    #"Tipo cambiado1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

