table 'SERV_NOW risk'
	lineageTag: a9dee35d-d88d-46d2-a5b8-340eb64b55f3

	column description
		dataType: string
		lineageTag: ceb0728a-4c04-4ac8-92bf-abffc5b98ce7
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column due_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 76ce1475-0c37-4908-947a-ee8d65917794
		summarizeBy: none
		sourceColumn: due_date

		variation Variación
			isDefault
			relationship: 226e9a7f-2866-4377-bb18-00d9bc2ed503
			defaultHierarchy: LocalDateTable_50945107-156b-48ac-889b-2efc7911492d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column impact
		dataType: int64
		formatString: 0
		lineageTag: bf49f586-2919-4af0-aff3-97d5df6d2f79
		summarizeBy: sum
		sourceColumn: impact

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: 18bdc4e6-c278-445c-904e-8853a1097d1e
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column mitigation
		dataType: string
		lineageTag: c5de26b3-f358-4e6d-ab6c-5d34eada169d
		summarizeBy: none
		sourceColumn: mitigation

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: 37fb7da0-d5f5-42d1-b150-b0d520956c3a
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column original_task
		dataType: string
		lineageTag: e4f867a9-b26a-4cb3-a160-945837287db5
		summarizeBy: none
		sourceColumn: original_task

		annotation SummarizationSetBy = Automatic

	column dv_original_task
		dataType: string
		lineageTag: 540e0532-5c26-4490-aa23-cef179e54ed5
		summarizeBy: none
		sourceColumn: dv_original_task

		annotation SummarizationSetBy = Automatic

	column probability
		dataType: string
		lineageTag: 425e3b21-f39c-4b1a-bb41-afc9ed0ec7c4
		summarizeBy: none
		sourceColumn: probability

		annotation SummarizationSetBy = Automatic

	column dv_probability
		dataType: string
		lineageTag: 369edb0f-e8ae-4b87-9524-9d89e9fc7e4a
		summarizeBy: none
		sourceColumn: dv_probability

		annotation SummarizationSetBy = Automatic

	column risk_owner
		dataType: string
		lineageTag: 9df21d9f-019a-4a7c-8ec1-759cba24c32a
		summarizeBy: none
		sourceColumn: risk_owner

		annotation SummarizationSetBy = Automatic

	column dv_risk_owner
		dataType: string
		lineageTag: 51d8c735-f510-436e-948b-5b3729985929
		summarizeBy: none
		sourceColumn: dv_risk_owner

		annotation SummarizationSetBy = Automatic

	column risk_rank
		dataType: int64
		formatString: 0
		lineageTag: 7889682e-8c01-4adb-ae5d-cf5e78185702
		summarizeBy: sum
		sourceColumn: risk_rank

		annotation SummarizationSetBy = Automatic

	column risk_state
		dataType: int64
		formatString: 0
		lineageTag: fe916f49-d174-47d5-adb0-f5d1e3eb94ce
		summarizeBy: sum
		sourceColumn: risk_state

		annotation SummarizationSetBy = Automatic

	column dv_risk_state
		dataType: string
		lineageTag: b92ed1b0-9f47-4c81-a8c7-f05e4a1fa828
		summarizeBy: none
		sourceColumn: dv_risk_state

		annotation SummarizationSetBy = Automatic

	column risk_value
		dataType: string
		lineageTag: 407cac73-5ff9-4376-804f-d2d774433c00
		summarizeBy: none
		sourceColumn: risk_value

		annotation SummarizationSetBy = Automatic

	column dv_risk_value
		dataType: string
		lineageTag: 452458dc-ed5e-4836-a66c-11faa797de40
		summarizeBy: none
		sourceColumn: dv_risk_value

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: ffb657a6-3028-4893-9402-991295dd600f
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column show_on_status_report
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5e7204ac-7062-4fea-aa4b-4415b58b679e
		summarizeBy: none
		sourceColumn: show_on_status_report

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: aa04f789-f533-4e04-bae3-e3624fd797ff
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: d4d1626f-07ce-4819-8b2a-b50a4aed8293
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column sys_created_by
		dataType: string
		lineageTag: 1c026ded-f5f8-4a9f-83a6-deac9652d7d4
		summarizeBy: none
		sourceColumn: sys_created_by

		annotation SummarizationSetBy = Automatic

	column sys_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 74242897-a554-4e3f-9d88-985862c83412
		summarizeBy: none
		sourceColumn: sys_created_on

		variation Variación
			isDefault
			relationship: 6f2dee7a-a2cc-4109-9644-e8192e76590d
			defaultHierarchy: LocalDateTable_d365b86c-1f24-4541-bcb1-a5113bf7c492.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: 0660a8c5-55ca-401b-b33c-3073895169c0
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column sys_mod_count
		dataType: int64
		formatString: 0
		lineageTag: 35b2eba8-66c8-49cb-bd16-422ffd61d6d3
		summarizeBy: sum
		sourceColumn: sys_mod_count

		annotation SummarizationSetBy = Automatic

	column sys_updated_on
		dataType: dateTime
		formatString: General Date
		lineageTag: a820bd95-878d-4b57-a2e0-211736d3f4ad
		summarizeBy: none
		sourceColumn: sys_updated_on

		variation Variación
			isDefault
			relationship: e5c47bd1-4ea5-46c8-b7dd-e4a2d5118c28
			defaultHierarchy: LocalDateTable_11f8f8dd-d240-4be8-be8e-c31ed98a4750.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column task
		dataType: string
		lineageTag: 0333d4b3-17f4-43b5-b8cb-51412820b958
		summarizeBy: none
		sourceColumn: task

		annotation SummarizationSetBy = Automatic

	column dv_task
		dataType: string
		lineageTag: e6c02d07-f510-47b5-ac6a-ce37dbfb9bee
		summarizeBy: none
		sourceColumn: dv_task

		annotation SummarizationSetBy = Automatic

	column top_portfolio
		dataType: string
		lineageTag: 5c754f66-6ef2-4acb-8ad2-4257760c7e5e
		summarizeBy: none
		sourceColumn: top_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_top_portfolio
		dataType: string
		lineageTag: 5870e72a-1b23-49ea-ac95-eb7ce7f04908
		summarizeBy: none
		sourceColumn: dv_top_portfolio

		annotation SummarizationSetBy = Automatic

	column top_task
		dataType: string
		lineageTag: 066afd6d-affe-46f1-8538-7a72dd92b110
		summarizeBy: none
		sourceColumn: top_task

		annotation SummarizationSetBy = Automatic

	column dv_top_task
		dataType: string
		lineageTag: f05fe69f-4a8c-49a0-a69d-b8cd56d0d988
		summarizeBy: none
		sourceColumn: dv_top_task

		annotation SummarizationSetBy = Automatic

	column u_action
		dataType: string
		lineageTag: b00e0747-600d-4e7d-904a-188ec45d72b5
		summarizeBy: none
		sourceColumn: u_action

		annotation SummarizationSetBy = Automatic

	column dv_u_action
		dataType: string
		lineageTag: 62ff7316-ef8e-45a6-9f95-43e457c007e0
		summarizeBy: none
		sourceColumn: dv_u_action

		annotation SummarizationSetBy = Automatic

	column u_action_status
		dataType: string
		lineageTag: 10fff90b-8d4f-4fac-af4e-30b0c431ec1a
		summarizeBy: none
		sourceColumn: u_action_status

		annotation SummarizationSetBy = Automatic

	column dv_u_action_status
		dataType: string
		lineageTag: b7bac906-4752-4503-a4fa-9bac1e39ce5c
		summarizeBy: none
		sourceColumn: dv_u_action_status

		annotation SummarizationSetBy = Automatic

	column u_category
		dataType: string
		lineageTag: f7c02646-09d5-4b29-8eb0-805a529df45d
		summarizeBy: none
		sourceColumn: u_category

		annotation SummarizationSetBy = Automatic

	column dv_u_category
		dataType: string
		lineageTag: 9a019e6a-80ac-4b7f-b0d3-818b89796b07
		summarizeBy: none
		sourceColumn: dv_u_category

		annotation SummarizationSetBy = Automatic

	column 'ProyectosPadre.number'
		dataType: string
		lineageTag: 4d803688-77b7-447b-9071-855eb016fb4f
		summarizeBy: none
		sourceColumn: ProyectosPadre.number

		annotation SummarizationSetBy = Automatic

	column 'URL Riesgos' = CONCATENATE("https://acciona.service-now.com/risk.do?sysparm_query=number%3d",'SERV_NOW risk'[number])
		lineageTag: 7bdeff8a-a59b-49a8-8150-f9c5967d502b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'SERV_NOW risk-f26d4514-364a-42f2-8944-a46b4b033d3b' = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "DWH"),
				    SERV_NOW_risk = Origen{[Schema="SERV_NOW",Item="risk"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_risk,{"assigned_to", "dv_assigned_to", "sys_domain", "sys_domain_path", "sys_tags", "sys_updated_by", "top_program", "dv_top_program", "u_actuation_plan_responsible", "dv_u_actuation_plan_responsible", "u_assignment_group", "dv_u_assignment_group", "u_identification_time", "dv_u_identification_time", "u_impact", "dv_u_impact", "u_impacted", "dv_u_impacted", "u_mitigation_target_day", "u_observations", "u_priority", "dv_u_priority", "u_reaction_type", "dv_u_reaction_type", "u_related_risk_id", "dv_u_related_risk_id", "u_response_application_date", "u_risk_estimate_ocurred", "u_risk_owner_area", "dv_u_risk_owner_area", "u_risk_type", "dv_u_risk_type", "u_severity", "dv_u_severity", "u_strategy", "dv_u_strategy", "u_typology", "dv_u_typology", "work_cost", "work_notes", "cost"}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Columnas quitadas", {"dv_task"}, ProyectosPadre, {"number"}, "ProyectosPadre", JoinKind.LeftOuter),
				    #"Se expandió ProyectosPadre" = Table.ExpandTableColumn(#"Consultas combinadas", "ProyectosPadre", {"number"}, {"ProyectosPadre.number"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Se expandió ProyectosPadre", each [ProyectosPadre.number] <> null and [ProyectosPadre.number] <> ""),
				    #"Filas filtradas" = Table.SelectRows(#"Filas filtradas1", each ([dv_state] <> "Closed")),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Filas filtradas","Pending","Pendiente",Replacer.ReplaceText,{"dv_state"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Opened","Abierto",Replacer.ReplaceText,{"dv_state"})
				in
				    #"Valor reemplazado1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

