table SubProyectos-DesarrolloSW
	lineageTag: 93612975-b1f2-4bf5-ac32-ca2db692687f

	column demand
		dataType: string
		lineageTag: 52554ee2-4b45-4021-8cce-655c38b48e20
		summarizeBy: none
		sourceColumn: demand

		annotation SummarizationSetBy = Automatic

	column dv_demand
		dataType: string
		lineageTag: f9c8885f-afdd-4acd-ba4a-837327c13956
		summarizeBy: none
		sourceColumn: dv_demand

		annotation SummarizationSetBy = Automatic

	column end
		dataType: dateTime
		formatString: General Date
		lineageTag: 9c53879a-7094-4280-be9b-fcbd71f9bcc1
		summarizeBy: none
		sourceColumn: end

		variation Variación
			isDefault
			relationship: 0afdf45b-92f2-4567-87aa-6e37338a1830
			defaultHierarchy: LocalDateTable_4c11cce7-996d-4136-aabb-2f6a3ce9ea55.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: bb7cf421-9700-4f7e-ae2f-5fff8b3afe77
		summarizeBy: none
		sourceColumn: end_date

		variation Variación
			isDefault
			relationship: 2260134e-e6fe-415f-aeaa-9e9ca6e8db8f
			defaultHierarchy: LocalDateTable_22345677-8d53-4592-a921-ebff506da2bb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: af198fb2-33fa-4325-b81d-2e8dbcaf8892
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 4a0199f2-7144-4a7f-9f60-9958da40bbbe
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: efc0fb8d-bb92-44c6-860c-002e29eea483
			defaultHierarchy: LocalDateTable_d9942cf9-1556-4764-9b4d-4c38b6a8c59d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: 0143f409-09af-4d15-8fe3-d768db5bcc0e
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: cef11cb5-d3ea-40cb-afa4-202ffa6a5e52
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column schedule_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 97eb2547-6c90-4352-abe4-bbc5857a10ec
		summarizeBy: none
		sourceColumn: schedule_end_date

		variation Variación
			isDefault
			relationship: 1b2da8d3-9255-4418-9783-f0f10d2d6588
			defaultHierarchy: LocalDateTable_627e8895-6d37-4d03-b56a-dc3e16d14acb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column schedule_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 756500e3-938b-4f95-99c1-3d8bdbe955c3
		summarizeBy: none
		sourceColumn: schedule_start_date

		variation Variación
			isDefault
			relationship: 86122379-a604-4eb4-a1b3-8e36311c20f1
			defaultHierarchy: LocalDateTable_db2d0192-954e-4e4b-ac0a-82148c948b91.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: d7fbe6db-d468-4f64-a0cf-e5ea467c7ca0
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column start
		dataType: dateTime
		formatString: General Date
		lineageTag: 4d2d4a03-34b7-4ac8-aa90-305f4e3d7d4a
		summarizeBy: none
		sourceColumn: start

		variation Variación
			isDefault
			relationship: c8b1abe4-40ec-422d-8fd0-9cb8ec06c40b
			defaultHierarchy: LocalDateTable_391e96d9-073e-47a5-b1d5-ac202d0b431d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 69b7780c-9726-476f-a70c-7a1ceb588eb4
		summarizeBy: none
		sourceColumn: start_date

		variation Variación
			isDefault
			relationship: 6857d46c-ad95-49a3-9dfe-5fef20bfd2f3
			defaultHierarchy: LocalDateTable_22a8f781-076d-460d-b394-90742dcb33ee.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column state
		dataType: int64
		formatString: 0
		lineageTag: 8558be7b-5890-4d5f-a97a-0c93d6b22191
		summarizeBy: sum
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: d9acf1e8-4a59-4b84-86cb-82b91e632b2c
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: d23512e9-328a-4fa8-99f0-9318adff7776
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column dv_status
		dataType: string
		lineageTag: 38b49195-d822-49ff-9a21-321e7548862f
		summarizeBy: none
		sourceColumn: dv_status

		annotation SummarizationSetBy = Automatic

	column sub_tree_root
		dataType: string
		lineageTag: fa94a0c3-c57b-4ac6-8571-d09df483eb17
		summarizeBy: none
		sourceColumn: sub_tree_root

		annotation SummarizationSetBy = Automatic

	column dv_sub_tree_root
		dataType: string
		lineageTag: b5bf20dc-71aa-4ed9-9b22-ae862d7f8533
		summarizeBy: none
		sourceColumn: dv_sub_tree_root

		annotation SummarizationSetBy = Automatic

	column sys_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 19d5174b-f66c-4a78-9981-c6f0f99513fe
		summarizeBy: none
		sourceColumn: sys_created_on

		variation Variación
			isDefault
			relationship: 17d368bc-1941-4caa-8871-71e879f30d83
			defaultHierarchy: LocalDateTable_30496d10-8e55-40eb-9725-e5a36378259f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: b09c1b6a-a869-427b-b9ac-0fccac5f7fdb
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column top_portfolio
		dataType: string
		lineageTag: fa67c528-6fcf-48ac-bc0a-d4fd32bc9cb1
		summarizeBy: none
		sourceColumn: top_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_top_portfolio
		dataType: string
		lineageTag: 63bfe6a4-452d-4d68-be1e-497db0f75dd2
		summarizeBy: none
		sourceColumn: dv_top_portfolio

		annotation SummarizationSetBy = Automatic

	column top_task
		dataType: string
		lineageTag: cf6a7072-0901-45f5-a0d4-560763ca0e9d
		summarizeBy: none
		sourceColumn: top_task

		annotation SummarizationSetBy = Automatic

	column dv_top_task
		dataType: string
		lineageTag: be8a819a-9ce9-4b99-bb8c-e2a0a67421d4
		summarizeBy: none
		sourceColumn: dv_top_task

		annotation SummarizationSetBy = Automatic

	column u_project_phase
		dataType: string
		lineageTag: b793f7d4-5f18-492f-ac75-97f30f2f9c57
		summarizeBy: none
		sourceColumn: u_project_phase

		annotation SummarizationSetBy = Automatic

	column dv_u_project_phase
		dataType: string
		lineageTag: be0cf995-82b8-4f52-869b-cbfe44b43919
		summarizeBy: none
		sourceColumn: dv_u_project_phase

		annotation SummarizationSetBy = Automatic

	column dv_u_project_type
		dataType: string
		lineageTag: 9de94494-1a15-4ee4-9baf-9253c989c131
		summarizeBy: none
		sourceColumn: dv_u_project_type

		annotation SummarizationSetBy = Automatic

	column 'ProyectosPadre.number'
		dataType: string
		lineageTag: b9fb36a0-d0ab-48e9-b437-ae68ed044cfe
		summarizeBy: none
		sourceColumn: ProyectosPadre.number

		annotation SummarizationSetBy = Automatic

	column attr_based_planning
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 182b90b3-d4f3-4ba6-9fd7-b70d80d1edb5
		summarizeBy: none
		sourceColumn: attr_based_planning

		annotation SummarizationSetBy = Automatic

	column auto_save
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6b5d23a0-44b9-4b76-8caf-d8f5992a244b
		summarizeBy: none
		sourceColumn: auto_save

		annotation SummarizationSetBy = Automatic

	column contract
		dataType: string
		lineageTag: 075ce4b7-d1b9-4bfa-83c7-4d76145374ab
		summarizeBy: none
		sourceColumn: contract

		annotation SummarizationSetBy = Automatic

	column dv_contract
		dataType: string
		lineageTag: 5a48ba6a-48a3-4ed1-9dc6-12c0a879b663
		summarizeBy: none
		sourceColumn: dv_contract

		annotation SummarizationSetBy = Automatic

	column dv_expense_type
		dataType: string
		lineageTag: 6e5936fa-6f6d-4aff-ac8a-21153bc2eb30
		summarizeBy: none
		sourceColumn: dv_expense_type

		annotation SummarizationSetBy = Automatic

	column dv_model_id
		dataType: string
		lineageTag: fc094f84-3e5e-440f-944a-cac1a8962dd4
		summarizeBy: none
		sourceColumn: dv_model_id

		annotation SummarizationSetBy = Automatic

	column dv_software_model
		dataType: string
		lineageTag: 7a1ad337-0dd4-4009-b28a-5ba5fa0863c6
		summarizeBy: none
		sourceColumn: dv_software_model

		annotation SummarizationSetBy = Automatic

	column dv_u_devops_manager
		dataType: string
		lineageTag: 3af4747c-db26-4d79-9547-37a36e83a991
		summarizeBy: none
		sourceColumn: dv_u_devops_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_pmo_manager
		dataType: string
		lineageTag: 531ebab1-f076-4f67-9858-c7769279ddbe
		summarizeBy: none
		sourceColumn: dv_u_pmo_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_qa_manager
		dataType: string
		lineageTag: 4435c1b5-a508-4946-8b16-dee982d7457f
		summarizeBy: none
		sourceColumn: dv_u_qa_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_rfp_phases
		dataType: string
		lineageTag: 8117ac61-ad34-4f2a-bb33-8a287fdf9832
		summarizeBy: none
		sourceColumn: dv_u_rfp_phases

		annotation SummarizationSetBy = Automatic

	column expense_type
		dataType: string
		lineageTag: d0acf311-e3e6-402c-ba85-77daf01a73cf
		summarizeBy: none
		sourceColumn: expense_type

		annotation SummarizationSetBy = Automatic

	column group_resource_assignee
		dataType: string
		lineageTag: 6afdb7b0-8720-41cc-afa0-84f482abc54c
		summarizeBy: none
		sourceColumn: group_resource_assignee

		annotation SummarizationSetBy = Automatic

	column model_id
		dataType: string
		lineageTag: b9bb57fe-bd7c-47d0-ab12-2670827f2fa4
		summarizeBy: none
		sourceColumn: model_id

		annotation SummarizationSetBy = Automatic

	column resource_assignee
		dataType: string
		lineageTag: f35ae910-e24d-4f41-89a6-5f229a1df01b
		summarizeBy: none
		sourceColumn: resource_assignee

		annotation SummarizationSetBy = Automatic

	column software_model
		dataType: string
		lineageTag: 6dee96e1-c674-4dd3-b707-ab5a2c53c69b
		summarizeBy: none
		sourceColumn: software_model

		annotation SummarizationSetBy = Automatic

	column u_commented
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c26b5608-29a2-4f95-8d92-9b16e6797a13
		summarizeBy: none
		sourceColumn: u_commented

		annotation SummarizationSetBy = Automatic

	column u_devops_manager
		dataType: string
		lineageTag: b32a1714-fba6-415e-b356-13d12e0b8c54
		summarizeBy: none
		sourceColumn: u_devops_manager

		annotation SummarizationSetBy = Automatic

	column u_impacted_applications
		dataType: string
		lineageTag: b2fd91f9-4cd9-4ed9-bd1d-effff8b35aa3
		summarizeBy: none
		sourceColumn: u_impacted_applications

		annotation SummarizationSetBy = Automatic

	column u_operational_committee_comment
		dataType: string
		lineageTag: fca2617a-83fc-4487-b724-c02244fd9b09
		summarizeBy: none
		sourceColumn: u_operational_committee_comment

		annotation SummarizationSetBy = Automatic

	column u_project_typology
		dataType: string
		lineageTag: af2ee769-3e3e-44fa-b266-4f31ba9adb00
		summarizeBy: none
		sourceColumn: u_project_typology

		annotation SummarizationSetBy = Automatic

	column u_qa_manager
		dataType: string
		lineageTag: 1a97d561-125d-4c20-b265-3220bc13bb03
		summarizeBy: none
		sourceColumn: u_qa_manager

		annotation SummarizationSetBy = Automatic

	column u_relevant_project_for_cio
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7b06bd94-5b8e-4189-8efe-676972655351
		summarizeBy: none
		sourceColumn: u_relevant_project_for_cio

		annotation SummarizationSetBy = Automatic

	column u_rfp_phases
		dataType: string
		lineageTag: 87e945b7-1943-418a-b457-efc663afc6aa
		summarizeBy: none
		sourceColumn: u_rfp_phases

		annotation SummarizationSetBy = Automatic

	column u_percent_complete_estimated
		dataType: double
		lineageTag: ccc6bca6-2ac7-4a68-bfef-11fa69df612f
		summarizeBy: sum
		sourceColumn: u_percent_complete_estimated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition SubProyectos-DesarrolloSW-9b9453f8-5bc9-407f-a716-5e1229af571f = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "DWH"),
				    SERV_NOW_pm_project = Origen{[Schema="SERV_NOW",Item="pm_project"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_pm_project,{"active", "activity_due", "actual_benefits", "additional_assignee_list", "allow_dates_outside_schedule", "approval", "dv_approval", "approval_history", "approval_set", "approved_end_date", "approved_start_date", "assigned_to", "dv_assigned_to", "assignment_group", "dv_assignment_group", "assumptions", "backlog_definition", "dv_backlog_definition", "barriers", "benefits", "budget_cost", "business_applications", "business_capabilities", "business_case", "business_duration", "dv_business_duration", "business_service", "dv_business_service", "business_unit", "dv_business_unit", "calculation_type", "dv_calculation_type", "calendar_duration", "dv_calendar_duration", "capex_cost", "capex_estimate_to_completion", "capex_forecast_cost", "close_notes", "closed_at", "closed_by", "dv_closed_by", "cmdb_ci", "dv_cmdb_ci", "cmdb_ci_business_app", "dv_cmdb_ci_business_app", "comments", "comments_and_work_notes", "company", "dv_company", "constraint_date", "contact_type", "dv_contact_type", "correlation_display", "correlation_id", "cost", "critical_path", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "department", "dv_department", "dependency", "discount_rate", "due_date", "duration", "dv_duration", "effort", "dv_effort", "enablers", "end_date_derived_from", "dv_end_date_derived_from", "escalation", "dv_escalation", "estimate_to_completion", "execution_type", "dv_execution_type", "expected_start", "follow_up", "forecast_cost", "goal", "dv_goal", "goals", "group_list", "has_conflict", "impact", "dv_impact", "impacted_business_units", "in_scope", "investment_class", "dv_investment_class", "investment_type", "dv_investment_type", "irr_value", "key_milestone", "knowledge", "level", "location", "dv_location", "made_sla", "marked_for_delete", "milestone", "mpp_task_id", "npv_value", "opened_by", "dv_opened_by", "opex_cost", "opex_estimate_to_completion", "opex_forecast_cost", "order", "orig_sys_id", "dv_orig_sys_id", "orig_top_task_id", "dv_orig_top_task_id", "out_of_scope", "override_status", "percent_complete", "phase", "dv_phase", "phase_type", "dv_phase_type", "primary_portfolio", "dv_primary_portfolio", "primary_program", "dv_primary_program", "priority", "dv_priority", "project_manager", "dv_project_manager", "project_schedule_date_format", "dv_project_schedule_date_format", "project_type", "dv_project_type", "rate_model", "dv_rate_model", "reassignment_count", "rejection_goto", "dv_rejection_goto", "relation_applied", "dv_relation_applied", "remaining_duration", "dv_remaining_duration", "remaining_effort", "dv_remaining_effort", "resource_allocated_cost", "resource_planned_cost", "resources_from_resource_plan", "risk", "dv_risk", "risk_cost", "risk_of_not_performing", "risk_of_performing", "roi", "rollup", "route_reason", "dv_route_reason", "run_calc_brs", "schedule", "dv_schedule", "score", "score_risk", "dv_score_risk", "score_size", "dv_score_size", "score_value", "dv_score_value", "service_offering", "dv_service_offering", "shadow", "description", "show_on_program_status_report", "skills", "sla_due", "start_date_derived_from", "dv_start_date_derived_from", "strategic_objectives", "sys_class_name", "dv_sys_class_name", "sys_created_by", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "task", "task_effective_number", "task_for", "dv_task_for", "time_card_at_top_task", "time_card_preference", "dv_time_card_preference", "time_component_from_planned", "time_constraint", "dv_time_constraint", "time_worked", "dv_time_worked", "time_zone", "title", "top_program", "dv_top_program", "u_acciona_priority", "u_affected_portfolios", "u_ambito_global", "u_benefit_check", "u_benefits", "u_business_line", "dv_u_business_line", "u_catalog", "dv_u_catalog", "u_changes", "u_changes_comments", "u_conditions_restrictions", "u_cost_comments", "u_costs", "u_current_situation", "u_deliverables", "u_deliverables_comments", "u_demand_type_description", "u_department", "dv_u_department", "u_dependencies", "u_deviation_in_costs", "u_deviation_in_duration", "u_digital_transformation", "u_eficiency_using_rrhh", "u_end_date_deviation", "u_external_vendor", "dv_u_external_vendor", "u_id_plan", "u_impacted_companies", "u_impacted_countries", "u_incidents", "u_incidents_comments", "u_indicator_1", "u_lessons_learned", "u_live_changes", "u_live_risks", "u_metal", "dv_u_metal", "u_monitoring_indicators", "u_outsourcing", "u_payroll_area", "dv_u_payroll_area", "u_phone", "u_planned_demand", "dv_u_planned_demand", "u_planned_resource_plan_effort", "u_previous_groups", "u_problems", "u_progress", "u_project_impact", "u_project_monitoring", "u_reasons_for_delay_reject", "dv_u_reasons_for_delay_reject", "u_ref_country", "dv_u_ref_country", "u_relevant", "u_responded", "u_risks", "u_risks_comments", "u_run", "u_run_description", "u_schedule", "u_schedule_comments", "u_size", "dv_u_size", "u_state_date", "u_suggestions_to_improve", "u_sum_planned_hours", "u_sum_time_cards", "u_targets", "u_tic_unit", "dv_u_tic_unit", "u_url", "u_version", "u_volume_of_impacted_users", "universal_request", "dv_universal_request", "update_actual_effort_from_time_card", "dv_update_actual_effort_from_time_card", "update_score_on_value_change", "dv_update_score_on_value_change", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "urgency", "dv_urgency", "user_input", "value", "variables", "version", "watch_list", "wbs", "wbs_order", "wf_activity", "dv_wf_activity", "work_cost", "work_duration", "dv_work_duration", "work_effort", "dv_work_effort", "work_end", "work_notes", "work_notes_list", "work_start", "x_29185_external_f_total_financed", "dv_u_project_typology", "u_restrictions", "u_completion_criteria", "u_pmo_manager", "html_description", "u_project_type"}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas quitadas", each ([dv_u_project_type] = "SW Development")),
				    #"Consultas combinadas" = Table.NestedJoin(#"Filas filtradas", {"dv_parent"}, ProyectosPadre, {"number"}, "ProyectosPadre", JoinKind.LeftOuter),
				    #"Se expandió ProyectosPadre" = Table.ExpandTableColumn(#"Consultas combinadas", "ProyectosPadre", {"number"}, {"ProyectosPadre.number"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Se expandió ProyectosPadre", each ([ProyectosPadre.number] <> null))
				in
				    #"Filas filtradas1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

