table _EmpleadosPedidos
	lineageTag: 7b6ccd7b-2bdc-4389-a111-be83633be922

	column 'ID de usuario'
		dataType: string
		lineageTag: f3b6c794-bead-4a55-9072-574b7913c94e
		summarizeBy: none
		sourceColumn: ID de usuario

		annotation SummarizationSetBy = Automatic

	column 'Nombre completo'
		dataType: string
		lineageTag: 5dbf2a35-2dbe-4c21-bdd2-131d8a4ee0ee
		summarizeBy: none
		sourceColumn: Nombre completo

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 76b34084-0d56-41eb-b6f2-28454006cc53
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Departamento
		dataType: string
		lineageTag: b8ed5f47-80f1-4f47-ad5f-da2f588859ca
		summarizeBy: none
		sourceColumn: Departamento

		annotation SummarizationSetBy = Automatic

	partition _EmpleadosPedidos-08c7abde-b83b-494c-8e7c-86e9d181dade = m
		mode: import
		source =
				let
				    URL = sharepointSource & Entorno,
				    Origen = SharePoint.Files(URL, [ApiVersion = 15]),
				    #"Filas ordenadas" = Table.Sort(Origen,{{"Date created", Order.Descending}}),
				    #"Filas filtradas" = Table.SelectRows(#"Filas ordenadas", each ([Name] = "_EmpleadosPedidos.xlsx")),
				    #"Archivos ocultos filtrados1" = Table.SelectRows(#"Filas filtradas", each [Attributes]?[Hidden]? <> true),
				    #"Invocar función personalizada1" = Table.AddColumn(#"Archivos ocultos filtrados1", "Transformar archivo (3)", each #"Transformar archivo (3)"([Content])),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Invocar función personalizada1", {"Name", "Source.Name"}),
				    #"Filas filtradas2" = Table.SelectRows(#"Columnas con nombre cambiado1", each ([Folder Path] = "https://acciona365.sharepoint.com/sites/EN_TIC_COORD_PRE/Documentos compartidos/CdM_SMO/CdM_CROSS/CdM Cross Incidencias/01. Incidencias/")),
				    #"Otras columnas quitadas1" = Table.SelectColumns(#"Filas filtradas2", {"Source.Name", "Transformar archivo (3)"}),
				    #"Columna de tabla expandida1" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Transformar archivo (3)", Table.ColumnNames(#"Transformar archivo (3)"(#"Archivo de ejemplo (3)"))),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna de tabla expandida1",{{"Source.Name", type text}, {"ID de usuario", type text}, {"Nombre completo", type text}, {"ID", Int64.Type}, {"Departamento", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Source.Name"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Columnas quitadas", each ([ID de usuario] <> null))
				in
				    #"Filas filtradas1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

