table _Subcategorias
	lineageTag: 0e72bdb0-7758-4158-8092-a390bd450caa

	column Aplicacion
		dataType: string
		lineageTag: 06720f65-35db-42fe-9a02-e98875cb6f72
		summarizeBy: none
		sourceColumn: Aplicacion

		annotation SummarizationSetBy = Automatic

	column Subcat_BD
		dataType: string
		lineageTag: e2afa781-ce48-40d0-8f11-27958d67f0fc
		summarizeBy: none
		sourceColumn: Subcat_BD

		annotation SummarizationSetBy = Automatic

	partition _Subcategorias-7c5d0e28-efa4-4a1d-b044-faa3d09a6fb4 = m
		mode: import
		source =
				let
				    URL = sharepointSource & Entorno,
				    Origen = SharePoint.Files(URL, [ApiVersion = 15]),
				    #"Filas filtradas" = Table.SelectRows(Origen, each ([Extension] = ".xlsx")),
				    #"Filas ordenadas" = Table.Sort(#"Filas filtradas",{{"Date created", Order.Descending}}),
				    #"Filas filtradas1" = Table.SelectRows(#"Filas ordenadas", each ([Name] = "_Subcategorias.xlsx")),
				    #"Archivos ocultos filtrados1" = Table.SelectRows(#"Filas filtradas1", each [Attributes]?[Hidden]? <> true),
				    #"Invocar función personalizada1" = Table.AddColumn(#"Archivos ocultos filtrados1", "Transformar archivo", each #"Transformar archivo"([Content])),
				    #"Filas filtradas3" = Table.SelectRows(#"Invocar función personalizada1", each ([Folder Path] = "https://acciona365.sharepoint.com/sites/EN_TIC_COORD_PRE/Documentos compartidos/CdM_SMO/CdM_CROSS/CdM Cross Incidencias/01. Incidencias/")),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Filas filtradas3", {"Name", "Source.Name"}),
				    #"Otras columnas quitadas1" = Table.SelectColumns(#"Columnas con nombre cambiado1", {"Source.Name", "Transformar archivo"}),
				    #"Columna de tabla expandida1" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Transformar archivo", Table.ColumnNames(#"Transformar archivo"(#"Archivo de ejemplo"))),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna de tabla expandida1",{{"Source.Name", type text}, {"Column1", type text}, {"Column2", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Source.Name"}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Columnas quitadas", [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Aplicacion", type text}, {"Subcat_BD", type text}}),
				    #"Filas filtradas2" = Table.SelectRows(#"Tipo cambiado1", each ([Aplicacion] <> null))
				in
				    #"Filas filtradas2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

