table 'SERV_NOW pm_project_task'
	lineageTag: 033ad131-6925-48a5-9562-a6165c10007d

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 37320775-f107-46d5-ac02-6f913a37f40f
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: 4c7df63d-f996-4e47-a181-6a5e86a8a79c
			defaultHierarchy: LocalDateTable_36e73665-6bad-424b-b6b5-1b11795eb053.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column closed_by
		dataType: string
		lineageTag: 35448908-c12e-4016-8f5e-36b4a3dc4843
		summarizeBy: none
		sourceColumn: closed_by

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 122fc97c-0d50-4239-8d0a-16ec6dc9e782
		summarizeBy: none
		sourceColumn: end_date

		variation Variación
			isDefault
			relationship: c0856dd8-d8ed-4a98-90ff-190ba5a14c42
			defaultHierarchy: LocalDateTable_44bf226b-67b1-4e0b-a804-a6a737babae8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8fc4637a-6c3a-4f02-8190-169655e0e741
		summarizeBy: none
		sourceColumn: milestone

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: ae25868a-d3ca-44bf-828a-b95d68194a51
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 1453fef3-f84e-413a-a305-7f0804f9efe3
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: 2e310dc5-e6de-411e-9a76-ebe49d10e4bf
			defaultHierarchy: LocalDateTable_f5d9ccd0-443e-465a-989f-f4a8435b77d1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: 3adf0214-170f-437e-8f9d-15d3b0ac5471
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: c97b719f-8e60-477b-a294-ff50d874f385
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column percent_complete
		dataType: double
		lineageTag: 54788b27-8647-4e98-8532-456744e0f3a8
		summarizeBy: sum
		sourceColumn: percent_complete

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column project
		dataType: string
		lineageTag: 72d29a75-ee4b-44b9-ab63-97c44cda2d9c
		summarizeBy: none
		sourceColumn: project

		annotation SummarizationSetBy = Automatic

	column schedule_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: c6ba25af-2fb4-414d-8392-a93a95768fa7
		summarizeBy: none
		sourceColumn: schedule_end_date

		variation Variación
			isDefault
			relationship: 7c439aab-e4ca-4b31-a457-a47d923fd348
			defaultHierarchy: LocalDateTable_1adf6f8f-65ff-4b6a-8b57-0b34067b5557.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column schedule_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: a4ce9056-5f23-4d02-9c66-f7b5ab97dfbd
		summarizeBy: none
		sourceColumn: schedule_start_date

		variation Variación
			isDefault
			relationship: 24f79b07-4c4e-4da3-a578-44ae8cd76fcd
			defaultHierarchy: LocalDateTable_c84ff443-5130-4fdb-b904-7431df6ef3e0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: 901bd856-0b78-4b37-a891-a8f56184e3a1
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3a1ba1b9-9d10-4dab-9fcd-a5d25116b11f
		summarizeBy: none
		sourceColumn: start_date

		variation Variación
			isDefault
			relationship: adf77f4a-7de7-4f5f-8576-6333d55725db
			defaultHierarchy: LocalDateTable_dfcb9d61-057d-40eb-ae83-5ff6049b8942.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column state
		dataType: int64
		formatString: 0
		lineageTag: f2048546-d80e-4c7a-ab35-e2633be615c8
		summarizeBy: sum
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: 54f58995-ec12-4a00-b191-7919304301fe
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: b2744991-97d4-4e64-9de4-df9dd3b4d346
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column dv_status
		dataType: string
		lineageTag: 188361ea-890e-430a-ae7c-0933e0a2779d
		summarizeBy: none
		sourceColumn: dv_status

		annotation SummarizationSetBy = Automatic

	column sub_tree_root
		dataType: string
		lineageTag: 9528e16f-92a4-487c-a580-ed13cc205ffd
		summarizeBy: none
		sourceColumn: sub_tree_root

		annotation SummarizationSetBy = Automatic

	column dv_sub_tree_root
		dataType: string
		lineageTag: 7793822e-6795-44bb-8999-e9154bb9c044
		summarizeBy: none
		sourceColumn: dv_sub_tree_root

		annotation SummarizationSetBy = Automatic

	column sys_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 6cbf7fb9-2bf1-42d8-9354-34c5026e07d5
		summarizeBy: none
		sourceColumn: sys_created_on

		variation Variación
			isDefault
			relationship: bb4abf0f-d372-4856-9e4e-15bd1355a76b
			defaultHierarchy: LocalDateTable_78b4c4cd-fd5c-4081-8d73-fcfe232097d3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: dbe50cff-3e2e-45ff-8cb1-557496d6b31f
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column task
		dataType: string
		lineageTag: f9ad786e-6d2a-4677-a2b0-9aa03a7a9ffe
		summarizeBy: none
		sourceColumn: task

		annotation SummarizationSetBy = Automatic

	column top_task
		dataType: string
		lineageTag: 167ebf79-b2e3-438b-af1a-c02ad03bbc28
		summarizeBy: none
		sourceColumn: top_task

		annotation SummarizationSetBy = Automatic

	column dv_top_task
		dataType: string
		lineageTag: b840e672-e370-408e-a056-17d2a7a52abd
		summarizeBy: none
		sourceColumn: dv_top_task

		annotation SummarizationSetBy = Automatic

	column u_demand
		dataType: string
		lineageTag: 6e90d83f-c00a-4397-aa7f-622713e06f7e
		summarizeBy: none
		sourceColumn: u_demand

		annotation SummarizationSetBy = Automatic

	column dv_u_demand
		dataType: string
		lineageTag: e64b93a2-a47a-432e-8a1c-bb6a7da052ee
		summarizeBy: none
		sourceColumn: dv_u_demand

		annotation SummarizationSetBy = Automatic

	column 'SubProyectos-DesarrolloSW.number'
		dataType: string
		lineageTag: 8e01a8e6-8938-418b-8c87-f5a546c9a087
		summarizeBy: none
		sourceColumn: SubProyectos-DesarrolloSW.number

		annotation SummarizationSetBy = Automatic

	column 'SubProyectos-DesarrolloSW.ProyectosPadre.number'
		dataType: string
		lineageTag: 78c8068f-f1a7-44b0-b65e-3b0f4b311e4a
		summarizeBy: none
		sourceColumn: SubProyectos-DesarrolloSW.ProyectosPadre.number

		annotation SummarizationSetBy = Automatic

	column work_end
		dataType: dateTime
		formatString: Short Date
		lineageTag: e470023a-5285-4247-8ce4-da87a7734adc
		summarizeBy: none
		sourceColumn: work_end

		variation Variación
			isDefault
			relationship: 7e744308-ef7e-4467-a7e3-c625c5b60c0a
			defaultHierarchy: LocalDateTable_e3b738bf-c621-46ed-8a52-bb17c3adb92a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column work_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 7a3aa308-75f0-479e-a8d4-1bcd6cb9a90a
		summarizeBy: none
		sourceColumn: work_start

		variation Variación
			isDefault
			relationship: 26c0e539-beac-42d8-9666-b7f8418620c1
			defaultHierarchy: LocalDateTable_c48f9ed2-f74e-4fea-bb50-b45c3d66c612.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'URL Tareas' = CONCATENATE("https://acciona.service-now.com/pm_project_task.do?sysparm_query=number%3d",'SERV_NOW pm_project_task'[number])
		lineageTag: dc31649c-8f41-4cc1-83c7-b486f20e81f0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column dv_assignment_group
		dataType: string
		lineageTag: 94a72bf1-77b1-46e8-a530-5404609e678e
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column dv_business_service
		dataType: string
		lineageTag: 1f437278-1673-405a-a74d-3330e6efe723
		summarizeBy: none
		sourceColumn: dv_business_service

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci_business_app
		dataType: string
		lineageTag: ad2e7007-8407-4654-a4cc-38a8c6c7bfe1
		summarizeBy: none
		sourceColumn: dv_cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column top_portfolio
		dataType: string
		lineageTag: 09cdb875-ac39-40ff-836d-c917d1cfaee8
		summarizeBy: none
		sourceColumn: top_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_top_portfolio
		dataType: string
		lineageTag: 5142823f-4332-43b0-8d7d-2b7c804637f4
		summarizeBy: none
		sourceColumn: dv_top_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_u_business_line
		dataType: string
		lineageTag: 474ad781-2913-431f-91bd-ff9b28ff2e15
		summarizeBy: none
		sourceColumn: dv_u_business_line

		annotation SummarizationSetBy = Automatic

	partition 'SERV_NOW pm_project_task-029eb099-0ea7-46e9-a0d3-491fadbbdf62' = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "dwh"),
				    SERV_NOW_pm_project_task = Origen{[Schema="SERV_NOW",Item="pm_project_task"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_pm_project_task,{"active", "activity_due", "actual_benefits", "additional_assignee_list", "agile_rollup_dates", "allow_dates_outside_schedule", "approval", "dv_approval", "approval_history", "approval_set", "assigned_to", "dv_assigned_to", "assignment_group", "benefits", "budget_cost", "business_duration", "dv_business_duration", "business_service", "calculation_type", "dv_calculation_type", "calendar_duration", "dv_calendar_duration", "capex_cost", "close_notes", "dv_closed_by", "cmdb_ci", "dv_cmdb_ci", "cmdb_ci_business_app", "comments", "comments_and_work_notes", "company", "dv_company", "constraint_date", "contact_type", "dv_contact_type", "correlation_display", "correlation_id", "cost", "critical_path", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "dependency", "description", "due_date", "duration", "dv_duration", "effort", "dv_effort", "end_date_derived_from", "dv_end_date_derived_from", "end_sprint", "dv_end_sprint", "escalation", "dv_escalation", "expected_start", "follow_up", "group_list", "has_conflict", "html_description", "impact", "dv_impact", "knowledge", "level", "link", "location", "dv_location", "made_sla", "key_milestone", "mpp_task_id", "opened_by", "dv_opened_by", "opex_cost", "order", "orig_sys_id", "dv_orig_sys_id", "orig_top_task_id", "dv_orig_top_task_id", "phase_type", "dv_phase_type", "priority", "dv_priority", "reassignment_count", "rejection_goto", "dv_rejection_goto", "relation_applied", "dv_relation_applied", "remaining_duration", "dv_remaining_duration", "remaining_effort", "dv_remaining_effort", "resource_allocated_cost", "resource_planned_cost", "rollup", "route_reason", "dv_route_reason", "scrum_team", "dv_scrum_team", "service_offering", "dv_service_offering", "shadow", "skills", "sla_due", "start_date_derived_from", "dv_start_date_derived_from", "start_sprint", "dv_start_sprint", "sys_class_name", "dv_sys_class_name", "sys_created_by", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "task_effective_number", "task_for", "dv_task_for", "test_plan", "dv_test_plan", "time_card_at_top_task", "time_constraint", "dv_time_constraint", "time_worked", "dv_time_worked",  "top_program", "dv_top_program", "u_acciona_priority", "u_business_line", "u_catalog", "dv_u_catalog", "u_department", "dv_u_department", "u_estado_evolutivo", "dv_u_estado_evolutivo", "u_external_vendor", "dv_u_external_vendor", "u_metal", "dv_u_metal", "u_phone", "u_previous_groups", "u_progress", "u_ref_country", "dv_u_ref_country", "u_responded", "u_size", "dv_u_size", "u_state_date", "u_version", "universal_request", "dv_universal_request", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "urgency", "dv_urgency", "user_input", "variables", "version", "watch_list", "wbs", "wbs_order", "wf_activity", "dv_wf_activity", "work_cost", "work_duration", "dv_work_duration", "work_effort", "dv_work_effort", "work_notes", "work_notes_list"}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Columnas quitadas", {"parent"}, #"SubProyectos-DesarrolloSW", {"sys_id"}, "SubProyectos-DesarrolloSW", JoinKind.LeftOuter),
				    #"Se expandió SubProyectos-DesarrolloSW" = Table.ExpandTableColumn(#"Consultas combinadas", "SubProyectos-DesarrolloSW", {"number", "ProyectosPadre.number"}, {"SubProyectos-DesarrolloSW.number", "SubProyectos-DesarrolloSW.ProyectosPadre.number"}),
				    #"Filas filtradas" = Table.SelectRows(#"Se expandió SubProyectos-DesarrolloSW", each ([#"SubProyectos-DesarrolloSW.number"] <> null)),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Filas filtradas","Closed Incomplete","Cerrado incompleto",Replacer.ReplaceText,{"dv_state"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Closed Complete","Cerrado completo",Replacer.ReplaceText,{"dv_state"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","Pending","Pendiente",Replacer.ReplaceText,{"dv_state"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","Closed Skipped","Cerrado omitido",Replacer.ReplaceText,{"dv_state"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","Open","Abierto",Replacer.ReplaceText,{"dv_state"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","Work in Progress","En curso",Replacer.ReplaceText,{"dv_state"})
				in
				    #"Valor reemplazado5"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

