table 'SERV_NOW project_change_request'
	lineageTag: 01c2f95c-1a3f-44f2-bcbc-88ec89b06d80

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4db23401-7ba5-4184-8a4e-12a64a939610
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column approval
		dataType: string
		lineageTag: 01330177-569a-466b-881c-a50104c8703a
		summarizeBy: none
		sourceColumn: approval

		annotation SummarizationSetBy = Automatic

	column dv_approval
		dataType: string
		lineageTag: f9c7feea-5947-4d7c-b0e9-f13f461c1b73
		summarizeBy: none
		sourceColumn: dv_approval

		annotation SummarizationSetBy = Automatic

	column approval_set
		dataType: dateTime
		formatString: General Date
		lineageTag: f43d4e93-f2c2-46c2-9d55-a0c2b086c40c
		summarizeBy: none
		sourceColumn: approval_set

		variation Variación
			isDefault
			relationship: 563a0faf-3908-489b-8dba-a4c4d5685deb
			defaultHierarchy: LocalDateTable_9816d54d-7826-4ef8-90b0-12177765c207.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column business_justification
		dataType: string
		lineageTag: 60ce4a2e-4a5c-48b3-9c67-56648be746c4
		summarizeBy: none
		sourceColumn: business_justification

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: ae732863-97fd-41d6-bb74-1a8919ba6fc3
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: 152d41d2-2ea4-40bd-81c7-9f554f65979e
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: 99fc5368-0059-4e16-bee4-b0ec6a2ba3a2
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: 81c1f960-4ca4-4c1d-b993-2cfc019c1e20
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: int64
		formatString: 0
		lineageTag: 434dd17e-cd30-495e-b9b9-317a85ae5633
		summarizeBy: sum
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: 286555fb-a320-4121-b89b-cba50f535a26
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: baf9349d-1b5c-4899-a37f-60688f63c9c0
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: b304b970-0a73-491b-83d4-8fa90a7c56c0
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: edc85932-63e2-498a-96a1-2e8637813b87
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column 'ProyectosPadre.number'
		dataType: string
		lineageTag: cf80fe74-1e55-4d80-bb36-b1281bda094e
		summarizeBy: none
		sourceColumn: ProyectosPadre.number

		annotation SummarizationSetBy = Automatic

	column 'URL CambiosAlcance' = CONCATENATE("https://acciona.service-now.com/project_change_request.do?sysparm_query=number%3d",'SERV_NOW project_change_request'[number])
		lineageTag: dc5373bb-d19f-4b75-aa86-73d6c612fa9d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column dv_assignment_group
		dataType: string
		lineageTag: a9cf3f8b-e8a3-4b28-96f6-a1fcc27e8237
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column business_service
		dataType: string
		lineageTag: 38ff3430-5d62-427d-b692-3151d142856f
		summarizeBy: none
		sourceColumn: business_service

		annotation SummarizationSetBy = Automatic

	column dv_business_service
		dataType: string
		lineageTag: ccdc1f62-b189-4fd4-b152-0fec85e05e34
		summarizeBy: none
		sourceColumn: dv_business_service

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci_business_app
		dataType: string
		lineageTag: 2ac5bdb8-5eff-4f3f-94fa-578bac847c4d
		summarizeBy: none
		sourceColumn: dv_cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column dv_u_business_line
		dataType: string
		lineageTag: 2c2120ea-05e9-4b45-a2af-ff49c6c2b255
		summarizeBy: none
		sourceColumn: dv_u_business_line

		annotation SummarizationSetBy = Automatic

	column contract
		dataType: string
		lineageTag: b25e7fb5-70b4-4252-8e1e-e3aa3f77d759
		summarizeBy: none
		sourceColumn: contract

		annotation SummarizationSetBy = Automatic

	column dv_contract
		dataType: string
		lineageTag: 43d767af-7171-4ee1-9402-11bbd1f4e74c
		summarizeBy: none
		sourceColumn: dv_contract

		annotation SummarizationSetBy = Automatic

	column u_commented
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 11df790d-e99b-49ff-b637-546594f94146
		summarizeBy: none
		sourceColumn: u_commented

		annotation SummarizationSetBy = Automatic

	column u_operational_committee_comment
		dataType: string
		lineageTag: 0cfbef41-266f-4683-981c-9a562ff8e925
		summarizeBy: none
		sourceColumn: u_operational_committee_comment

		annotation SummarizationSetBy = Automatic

	column u_presented_validated_comitee
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7a51139f-5af6-49ae-af98-635d7789b35b
		summarizeBy: none
		sourceColumn: u_presented_validated_comitee

		annotation SummarizationSetBy = Automatic

	partition 'SERV_NOW project_change_request' = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "DWH"),
				    SERV_NOW_project_change_request = Origen{[Schema="SERV_NOW",Item="project_change_request"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_project_change_request,{"activity_due", "additional_assignee_list", "approval_history", "assigned_to", "dv_assigned_to", "assignment_group", "business_duration", "dv_business_duration", "calendar_duration", "dv_calendar_duration", "category", "dv_category", "close_notes", "closed_at", "closed_by", "dv_closed_by", "cmdb_ci", "dv_cmdb_ci", "cmdb_ci_business_app", "comments", "comments_and_work_notes", "company", "dv_company", "contact_type", "dv_contact_type", "correlation_display", "correlation_id", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "due_date", "escalation", "dv_escalation", "estimated_cost", "expected_start", "follow_up", "group_list", "impact", "knowledge", "location", "dv_location", "made_sla", "opened_at", "opened_by", "dv_opened_by", "order", "original_parent", "dv_original_parent", "parent", "reassignment_count", "rejection_goto", "dv_rejection_goto", "route_reason", "dv_route_reason", "service_offering", "dv_service_offering", "show_on_status_report", "skills", "sla_due", "state", "sys_class_name", "dv_sys_class_name", "sys_created_by", "sys_created_on", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "task_effective_number", "task_for", "dv_task_for", "time_worked", "dv_time_worked", "u_acciona_priority", "u_attributable_change", "dv_u_attributable_change", "u_business_line", "u_catalog", "dv_u_catalog", "u_department", "dv_u_department", "u_external_vendor", "dv_u_external_vendor", "u_metal", "dv_u_metal", "u_payroll_area", "dv_u_payroll_area", "u_phone", "u_previous_groups", "u_progress", "u_ref_country", "dv_u_ref_country", "u_responded", "u_size", "dv_u_size", "u_state_date", "u_type", "dv_u_type", "universal_request", "dv_universal_request", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "urgency", "dv_urgency", "user_input", "variables", "watch_list", "wf_activity", "dv_wf_activity", "work_end", "work_notes", "work_notes_list", "work_start"}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Columnas quitadas", {"dv_parent"}, ProyectosPadre, {"number"}, "ProyectosPadre", JoinKind.LeftOuter),
				    #"Se expandió ProyectosPadre" = Table.ExpandTableColumn(#"Consultas combinadas", "ProyectosPadre", {"number"}, {"ProyectosPadre.number"}),
				    #"Filas filtradas" = Table.SelectRows(#"Se expandió ProyectosPadre", each ([ProyectosPadre.number] <> null and [ProyectosPadre.number] <> "") and ([dv_state] <> "Closed" and [dv_state] <> "Rejected")),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Filas filtradas","Requested","Solicitado",Replacer.ReplaceText,{"dv_state"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Work In Progress","En Implantación",Replacer.ReplaceText,{"dv_state"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","In Evaluation","En Evaluación",Replacer.ReplaceText,{"dv_state"})
				in
				    #"Valor reemplazado2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

