table _GruposEstimacion
	lineageTag: 06187ce8-e8b7-4a0b-b2f5-ba38079421eb

	column Grupo
		dataType: string
		lineageTag: 0b05d685-ad98-446d-9a2b-f2e143ddce4f
		summarizeBy: none
		sourceColumn: Grupo

		annotation SummarizationSetBy = Automatic

	column Aplicación
		dataType: string
		lineageTag: 538409f3-a20e-4dea-8db7-b38e4377f336
		summarizeBy: none
		sourceColumn: Aplicación

		annotation SummarizationSetBy = Automatic

	column 'Descripción grupo'
		dataType: string
		lineageTag: e7d73f18-e136-487f-a71d-d658c78e5289
		summarizeBy: none
		sourceColumn: Descripción grupo

		annotation SummarizationSetBy = Automatic

	partition _GruposEstimacion-d3df7322-4a9b-43f1-921e-4c6f084d3330 = m
		mode: import
		source =
				let
				URL = sharepointSource & Entorno,
				URLcompleta = sharepointSource & Entorno & sharepointSource2,
				    Origen = SharePoint.Files(URL, [ApiVersion = 15]),
				    #"Filas filtradas" = Table.SelectRows(Origen, each ([Extension] = ".xlsx")),
				    #"Filas ordenadas" = Table.Sort(#"Filas filtradas",{{"Date created", Order.Descending}}),
				    #"Filas filtradas1" = Table.SelectRows(#"Filas ordenadas", each ([Name] = "GruposEstimacion.xlsx")),
				    #"Archivos ocultos filtrados1" = Table.SelectRows(#"Filas filtradas1", each [Attributes]?[Hidden]? <> true),
				    #"Invocar función personalizada1" = Table.AddColumn(#"Archivos ocultos filtrados1", "Transformar archivo (3)", each #"Transformar archivo (3)"([Content])),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Invocar función personalizada1", {"Name", "Source.Name"}),
				    #"Filas filtradas2" = Table.SelectRows(#"Columnas con nombre cambiado1", each ([Folder Path] = URLcompleta)),
				    #"Otras columnas quitadas1" = Table.SelectColumns(#"Filas filtradas2", {"Source.Name", "Transformar archivo (3)"}),
				    #"Columna de tabla expandida1" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Transformar archivo (3)", Table.ColumnNames(#"Transformar archivo (3)"(#"Archivo de ejemplo (3)"))),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna de tabla expandida1",{{"Source.Name", type text}, {"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Tipo cambiado", [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"GruposEstimacion.xlsx", type text}, {"Grupo", type text}, {"Aplicación", type text}, {"Descripción grupo", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado1",{"GruposEstimacion.xlsx"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

