table Fechas
	lineageTag: 5e0842a2-2fec-4cf5-a443-f84be1e7df6a

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 506fd533-d95e-494d-bd39-04560deb52e9
		summarizeBy: none
		sourceColumn: Date

		variation Variación
			isDefault
			relationship: 3f1c15e5-3d5f-49b7-918d-824430d3a337
			defaultHierarchy: LocalDateTable_0157dfbe-9001-45f2-955b-ee37952d28e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Date_1er_día_mes
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f1aa2c6e-69dd-42e9-896c-2dba38c02b96
		summarizeBy: none
		sourceColumn: Date_1er_día_mes
		sortByColumn: 'Periodo Contrato'

		variation Variación
			isDefault
			relationship: 65d69b04-7908-4efa-a6df-ffd4a474ecf8
			defaultHierarchy: LocalDateTable_739f91b2-b71c-436b-9784-bc6a62538cd5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column MesNombreComp
		dataType: string
		lineageTag: 246d4974-fd68-4f89-b28c-70724686a430
		summarizeBy: none
		sourceColumn: MesNombreComp
		sortByColumn: MesNumero

		annotation SummarizationSetBy = Automatic

	column MesNombreCorto
		dataType: string
		lineageTag: 384d9401-43f9-405d-ac6a-7f0bfa52a4f1
		summarizeBy: none
		sourceColumn: MesNombreCorto
		sortByColumn: MesNumero

		annotation SummarizationSetBy = Automatic

	column MesNumero
		dataType: int64
		formatString: 0
		lineageTag: 883db424-0445-4e50-b947-b4376cf41474
		summarizeBy: sum
		sourceColumn: MesNumero

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: int64
		formatString: 0
		lineageTag: d1c96648-4898-49e1-b66e-b511040e0a6d
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column SERVICE_P
		dataType: string
		lineageTag: bbce3103-a47a-4d37-8f1c-714378ac06b9
		summarizeBy: none
		sourceColumn: SERVICE_P

		annotation SummarizationSetBy = Automatic

	column Date_ult_día_mes
		dataType: dateTime
		formatString: Long Date
		lineageTag: 63818be3-8b64-4cc2-8ab3-bc7de59bdf03
		summarizeBy: none
		sourceColumn: Date_ult_día_mes

		variation Variación
			isDefault
			relationship: 58d6c2e4-3a28-46c5-9cda-738f6972b96c
			defaultHierarchy: LocalDateTable_82daabe3-b180-4542-b409-a9a261ab07f5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AñoContrato
		dataType: string
		lineageTag: abddb4b0-a3b7-480e-856c-dd5badffa5b0
		summarizeBy: none
		sourceColumn: AñoContrato

		annotation SummarizationSetBy = Automatic

	column Mes_Año
		dataType: string
		lineageTag: d6d9308e-433a-4103-ae5c-2d284726036a
		summarizeBy: none
		sourceColumn: Mes_Año
		sortByColumn: Date_1er_día_mes

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Periodo
		dataType: string
		lineageTag: d4fcaa24-a37f-43b0-bca2-c579d1f24936
		summarizeBy: none
		sourceColumn: Periodo
		sortByColumn: Periodo_num

		annotation SummarizationSetBy = Automatic

	column Periodo_num
		dataType: int64
		formatString: 0
		lineageTag: 4b98e730-9f28-49a3-a2d5-0bba7876276d
		summarizeBy: sum
		sourceColumn: Periodo_num

		annotation SummarizationSetBy = Automatic

	column Anio_chart
		dataType: string
		lineageTag: 2e8521ce-c14f-458f-a837-9c3fb48cb5e0
		summarizeBy: none
		sourceColumn: Anio_chart
		sortByColumn: Periodo_num

		annotation SummarizationSetBy = Automatic

	column Mes_Año_v2
		dataType: string
		lineageTag: 5ac99448-b308-4ce0-92df-bd7891b7edbc
		summarizeBy: none
		sourceColumn: Mes_Año_v2
		sortByColumn: Date_1er_día_mes

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Periodo Contrato'
		dataType: string
		lineageTag: 51761670-83a2-4831-b89b-f454d89ddedf
		summarizeBy: none
		sourceColumn: Periodo Contrato
		sortByColumn: Date_ult_día_mes

		annotation SummarizationSetBy = Automatic

	column Periodo_num_order
		dataType: string
		lineageTag: 689f85e1-ba72-44df-9af8-c2ff729b2eae
		summarizeBy: none
		sourceColumn: Periodo_num_order

		annotation SummarizationSetBy = Automatic

	partition Fechas-f914a229-adc7-4b29-a55e-bef413962c7f = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source =
				let
				    Duracion = Duration.TotalDays (FF-FI) + 1,
				    ListaFechas = List.Dates(FI,Duracion,#duration(1,0,0,0)),
				    TablaFechas = Table.FromList(ListaFechas, Splitter.SplitByNothing(), type table [Date = date], null, ExtraValues.Error),
				    #"Inicio del mes insertado" = Table.AddColumn(TablaFechas, "Date_1er_día_mes", each Date.StartOfMonth([Date]), type date),
				    Personalizado1 = Table.AddColumn(#"Inicio del mes insertado", "Date_ult_día_mes", each Date.EndOfMonth([Date]), type date),
				    ColumnaMes = Table.AddColumn(Personalizado1,"MesNombreComp", each Date.MonthName([Date]), type text),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(ColumnaMes,{{"MesNombreComp", Text.Proper, type text}}),
				    #"Agregar columna personalizada" = Table.AddColumn(#"Poner En Mayúsculas Cada Palabra", "MesNombreCorto", each Text.Start(Text.Proper(Date.ToText([Date], "MMM")), 3), type text),
				    ColumnaNroMes = Table.AddColumn(#"Agregar columna personalizada","MesNumero", each Date.Month([Date]), Int64.Type),
				    ColumnaAño = Table.AddColumn(ColumnaNroMes,"Año", each Date.Year([Date]), Int64.Type),
				    #"Columna condicional agregada" = Table.AddColumn(ColumnaAño, "SERVICE_P", each if [Date] >= FI and [Date] < Date.From(DateTime.LocalNow()) then 1 else 0),
				    #"Columna condicional agregada1" = Table.AddColumn(#"Columna condicional agregada", "AñoContrato", each if [MesNumero] >= StartofFiscalYear then "Año " & Text.From([Año] + 1 - 2024) else "Año " & Text.From([Año] - 2024)),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columna condicional agregada1","Año 0",null,Replacer.ReplaceValue,{"AñoContrato"}),
				    #"Columna combinada insertada" = Table.AddColumn(#"Valor reemplazado", "Mes_Año", each Text.Combine({"", [MesNombreComp], " ", Text.From([Año], "es-ES")}), type text),
				    #"Texto insertado después del delimitador1" = Table.AddColumn(#"Columna combinada insertada", "Mes_Año_v2", each Text.AfterDelimiter(Text.From([Date], "es-ES"), "/"), type text),
				    Periodo_num = Table.AddColumn(#"Texto insertado después del delimitador1", "Periodo_num", each if [MesNumero] >= StartofFiscalYear then [MesNumero] - StartofFiscalYear + 1 else if [MesNumero] < StartofFiscalYear then [MesNumero] - StartofFiscalYear + 12 + 1 else null, type text),
				    #"Columna condicional agregada2" = Table.AddColumn(Periodo_num, "Periodo_num_order", each if [AñoContrato] = null then null else [Periodo_num]),
				    #"Texto insertado después del delimitador" = Table.AddColumn(#"Columna condicional agregada2", "Periodo", each "P" & Number.ToText([Periodo_num]), type text),
				    #"Texto remplazado insertado" = Table.AddColumn(#"Texto insertado después del delimitador", "Anio_chart", each Text.Replace([AñoContrato], "ño ", "") & "-" & [Periodo] & " " & [Mes_Año_v2], type text),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Texto remplazado insertado",{{"Periodo_num", Int64.Type}}),
				    #"Periodo Contrato" = Table.AddColumn(#"Tipo cambiado","Periodo Contrato", each Text.AfterDelimiter([Anio_chart], "-"), type text)
				in
				    #"Periodo Contrato"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

