table KGI_II_Incidencias_Total_F_Abierta
	lineageTag: 8c275a69-99a2-4d45-93d3-eb1a28008628

	column 'Abierto mes'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 71b4a3e4-1563-4217-9054-578e231e33d3
		summarizeBy: none
		sourceColumn: Abierto mes

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'ID_KGI_2.3'
		dataType: string
		lineageTag: 8274f786-db28-444a-a62e-d97887ea6e37
		summarizeBy: none
		sourceColumn: ID_KGI_2.3

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_2.4'
		dataType: string
		lineageTag: d4ba3985-aed4-48a7-8aa7-b18353dd3891
		summarizeBy: none
		sourceColumn: ID_KGI_2.4

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_2.5'
		dataType: string
		lineageTag: 71a80da3-2eb9-49fc-9d01-3455a53a3a46
		summarizeBy: none
		sourceColumn: ID_KGI_2.5

		annotation SummarizationSetBy = Automatic

	column Subcategoría
		dataType: string
		lineageTag: 18bc8a5b-2b16-48ab-acda-5b945a9652b1
		summarizeBy: none
		sourceColumn: Subcategoría

		annotation SummarizationSetBy = Automatic

	column 'Prioridad grupo ANS1.3'
		dataType: string
		lineageTag: d3435cac-2a87-4349-8e74-c9261c62693c
		summarizeBy: none
		sourceColumn: Prioridad grupo ANS1.3

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: e6184789-96c3-4385-9985-70a427cfb18d
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Solución'
		dataType: string
		lineageTag: 7fcd1ccc-0e0d-4265-811c-e91b3e6e14b8
		summarizeBy: none
		sourceColumn: Tipo de Solución

		annotation SummarizationSetBy = Automatic

	column Infringido_alegaciones
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1ec41f30-40f8-478e-850e-5f2e1d5b98cb
		summarizeBy: none
		sourceColumn: Infringido_alegaciones

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 5d2a2f01-cf2d-4d6c-ba31-cb2e657a3097
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column 'Elemento de configuración'
		dataType: string
		lineageTag: 31ac4471-b9dd-47ee-85ff-97a022cd631d
		summarizeBy: none
		sourceColumn: Elemento de configuración

		annotation SummarizationSetBy = Automatic

	column 'Abierto por'
		dataType: string
		lineageTag: 1a33f58c-9636-4a51-8185-daad22a94019
		summarizeBy: none
		sourceColumn: Abierto por

		annotation SummarizationSetBy = Automatic

	column Alegaciones
		dataType: string
		lineageTag: 2397814b-adeb-4273-a24c-6dea6c85ecd6
		summarizeBy: none
		sourceColumn: Alegaciones

		annotation SummarizationSetBy = Automatic

	column Extracción
		dataType: dateTime
		formatString: Long Date
		lineageTag: f7c2d5e8-b508-4615-9d6d-2f47beb17220
		summarizeBy: none
		sourceColumn: Extracción

		variation Variación
			isDefault
			relationship: fc721c1c-1c2a-4024-a62f-3718de6836ec
			defaultHierarchy: LocalDateTable_c19b7e24-9d71-4e02-bdea-7a559c019b9e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Breve descripción'
		dataType: string
		lineageTag: bca075c3-cefe-43ff-9e6a-475857666cfb
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 709706d6-8848-41a1-b892-b64c9a39168a
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0f6abba8-c415-46c0-b176-bf411ae9ef6d
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: b2e0932e-3225-4bb4-820f-13a676d82e28
			defaultHierarchy: LocalDateTable_bd4ef2d2-406a-4cc2-a524-3a31131c236d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Cerrado
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6cb1bb67-9505-4a67-aecd-746651ab08b6
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: 0ba8ad20-c554-4418-8991-2d7d7d6a6726
			defaultHierarchy: LocalDateTable_b62674ad-1d49-4cfd-83a6-42a316151591.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: e844a946-70ea-455b-91e7-3a0e92a28ca4
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variación
			isDefault
			relationship: 9fae1edc-d8b6-45c2-aae0-d5eacac6c0b6
			defaultHierarchy: LocalDateTable_65e845f1-5080-4965-a94d-8ffa4f820c82.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: string
		lineageTag: 501c3a0a-9bc8-4a66-bd6e-1762ad410d64
		summarizeBy: none
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: int64
		formatString: 0
		lineageTag: 7f6661e1-9738-4c16-9331-07831a4104d1
		summarizeBy: sum
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6eb96a55-c5c9-4aaf-b017-7b42773aa5a1
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: double
		lineageTag: 68d39f85-0182-4725-9122-ff051c5cf144
		summarizeBy: sum
		sourceColumn: Tiempo original de incumplimiento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Estado SLA'
		dataType: string
		lineageTag: 2a6ccc0a-38ea-4ac5-ac94-077a5bf6f95c
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: int64
		formatString: 0
		lineageTag: 45811f60-07c5-4e91-a82c-4d84962e262e
		summarizeBy: sum
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: double
		lineageTag: 1a7147d1-7d98-4098-810c-ac45b9e405f8
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		lineageTag: fce3afba-da2f-4cec-9f99-08176a962bf5
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Principal
		dataType: string
		lineageTag: 8637371f-1968-43aa-8435-d3c24fb45075
		summarizeBy: none
		sourceColumn: Principal

		annotation SummarizationSetBy = Automatic

	column 'Usuarios interesados'
		dataType: string
		lineageTag: 9c20dcd5-c674-4443-9523-478f1af26b8e
		summarizeBy: none
		sourceColumn: Usuarios interesados

		annotation SummarizationSetBy = Automatic

	column 'Causa probable'
		dataType: string
		lineageTag: 86bbba47-2230-4b59-a12e-4e3cebd3dd3d
		summarizeBy: none
		sourceColumn: Causa probable

		annotation SummarizationSetBy = Automatic

	column 'Lista de notas de trabajo'
		dataType: string
		lineageTag: 3252d785-5635-4f7e-9de8-94a9f73c7dce
		summarizeBy: none
		sourceColumn: Lista de notas de trabajo

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 7abb395a-3efe-4e26-95c9-1102b1d6bf7d
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Entrada del usuario'
		dataType: string
		lineageTag: 5eca5d30-4dbc-4df1-9e04-2096696547ec
		summarizeBy: none
		sourceColumn: Entrada del usuario

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 4dd63c79-1048-4c78-b941-29856eb89ea7
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column 'Número de reasignación'
		dataType: string
		lineageTag: 612422b2-4128-49c1-b21b-168c2ec260df
		summarizeBy: none
		sourceColumn: Número de reasignación

		annotation SummarizationSetBy = Automatic

	column 'ID de correlación'
		dataType: string
		lineageTag: 49ca7768-ef69-4057-acab-5ac65420bc49
		summarizeBy: none
		sourceColumn: ID de correlación

		annotation SummarizationSetBy = Automatic

	column Combinada
		dataType: string
		lineageTag: 43838a25-2872-40c8-bde6-14304153f7e4
		summarizeBy: none
		sourceColumn: Combinada

		annotation SummarizationSetBy = Automatic

	column 'Cerrado mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: db3423ab-3531-49fb-8564-b8e2b0f3d39b
		summarizeBy: none
		sourceColumn: Cerrado mes

		variation Variación
			isDefault
			relationship: a5578104-13e4-4930-b3b0-10fd8b6e48fa
			defaultHierarchy: LocalDateTable_bffc2c1e-9b37-441e-9581-2868125dd6c9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Abiertas tres meses previos'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 66ab8c0a-ec1d-4d65-b50a-283fd77c0760
		summarizeBy: none
		sourceColumn: Abiertas tres meses previos

		variation Variación
			isDefault
			relationship: 5990c2ae-8d3d-4137-8828-2f924cd33591
			defaultHierarchy: LocalDateTable_60098a7c-3cf8-4c2e-9d85-cdbdb04a61a2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Abiertas seis meses previos'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d76447f1-e6ce-4f75-8da6-8cc9813c98d8
		summarizeBy: none
		sourceColumn: Abiertas seis meses previos

		variation Variación
			isDefault
			relationship: 4d461196-8940-46bf-9374-9c3e1999d7c7
			defaultHierarchy: LocalDateTable_047537ef-6aa8-4862-ad67-f58615652da2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Prioridad grupo ANS2.4'
		dataType: string
		lineageTag: f0aeb199-c3d0-4263-bc9d-e413c05fc56f
		summarizeBy: none
		sourceColumn: Prioridad grupo ANS2.4

		annotation SummarizationSetBy = Automatic

	column 'SLA_III_Peticiones.Solicitar elemento'
		dataType: string
		lineageTag: b4b344ba-ea93-462f-a08f-a1268f1ebebc
		summarizeBy: none
		sourceColumn: SLA_III_Peticiones.Solicitar elemento

		annotation SummarizationSetBy = Automatic

	column 'SLA_III_Peticiones.Nombre'
		dataType: string
		lineageTag: 02528d11-6f98-42fc-8e6a-720f35caa34a
		summarizeBy: none
		sourceColumn: SLA_III_Peticiones.Nombre

		annotation SummarizationSetBy = Automatic

	column 'SLA_III_Peticiones.Prioridad'
		dataType: string
		lineageTag: 365353d4-9721-4606-ad3e-128a0a0cc262
		summarizeBy: none
		sourceColumn: SLA_III_Peticiones.Prioridad

		annotation SummarizationSetBy = Automatic

	column 'SLA_III_Peticiones.Cerrado mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e9b01aed-3a19-4946-bbb7-a8a71d997e7b
		summarizeBy: none
		sourceColumn: SLA_III_Peticiones.Cerrado mes

		variation Variación
			isDefault
			relationship: 924fb989-6cca-44f1-9ba9-36b4aad28bf7
			defaultHierarchy: LocalDateTable_c6793fdc-87ef-4473-84a5-6093216613b5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Número'
		dataType: string
		lineageTag: 5bc5bcc6-e409-46aa-9e0c-1ebfa8240706
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Número

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Tipo de Proyecto'
		dataType: string
		lineageTag: 6e1adc22-e639-4258-af66-248d61c1ef5e
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad'
		dataType: string
		lineageTag: 42e6bdc5-5277-46cb-9be5-e8b4f17ab808
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Aplicación de Negocio'
		dataType: string
		lineageTag: d6171f77-add1-4aa6-a252-1a0ae8507285
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Aplicación de Negocio

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Nombre'
		dataType: string
		lineageTag: 62214de0-6f2b-475e-8074-5ff86e9cb5de
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Nombre

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Inicio'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6fafb073-65fe-40f7-a1e5-97d2b5e57f24
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Inicio

		variation Variación
			isDefault
			relationship: eed4ca41-c492-402d-9a61-4c6c33051b95
			defaultHierarchy: LocalDateTable_dc59418d-7f69-4450-a672-6beb673fa1dd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Fin'
		dataType: dateTime
		formatString: General Date
		lineageTag: e7cd47ee-b507-4079-ba16-407ff825f41b
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Fin

		variation Variación
			isDefault
			relationship: 05f550ab-2252-4d32-9d87-1b6b360d75d1
			defaultHierarchy: LocalDateTable_9cbcea17-e00b-486d-afad-f27a6b79d1bb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 3b3e1c61-2e88-4377-a6a3-7d5023dcd7aa
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Fecha fin real

		variation Variación
			isDefault
			relationship: e3f601ae-e76b-43a2-b91b-d0ece557ccee
			defaultHierarchy: LocalDateTable_71d835fa-a714-420c-bcf3-96f41ca45abb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.ID_KGI1.3'
		dataType: string
		lineageTag: 2fdf8ea5-b1c2-4180-83ed-9ad1593acff0
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.ID_KGI1.3

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Proyecto_Evolutivo'
		dataType: string
		lineageTag: f408f811-1aaa-4068-b2aa-8b9b3a8ca21b
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Proyecto_Evolutivo

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI1.3'
		dataType: string
		lineageTag: a5e12a24-17ac-456a-b988-5499ce3efca0
		summarizeBy: none
		sourceColumn: ID_KGI1.3

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI2.1'
		dataType: string
		lineageTag: 7a302413-a904-4aaf-b5a3-b7e4f20d8eaa
		summarizeBy: none
		sourceColumn: ID_KGI2.1

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_2.2'
		dataType: string
		lineageTag: 430d5f29-3601-47ca-a793-46a43feea78e
		summarizeBy: none
		sourceColumn: ID_KGI_2.2

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI3.2'
		dataType: string
		lineageTag: 1be0291f-4592-43a7-bfad-fab2443b1d51
		summarizeBy: none
		sourceColumn: ID_KGI3.2

		annotation SummarizationSetBy = Automatic

	column Proyecto_Evolutivo
		dataType: string
		lineageTag: 95e92080-84c5-4502-af39-3f75dbd495a4
		summarizeBy: none
		sourceColumn: Proyecto_Evolutivo

		annotation SummarizationSetBy = Automatic

	column Reabierta_texto
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 79740f67-311c-425a-9bf2-a473215a5c9d
		summarizeBy: none
		sourceColumn: Reabierta_texto

		annotation SummarizationSetBy = Automatic

	column Estado_abierta
		dataType: string
		lineageTag: a64b1dd2-1be9-4b9e-bd81-095a9664be17
		summarizeBy: none
		sourceColumn: Estado_abierta

		annotation SummarizationSetBy = Automatic

	column 'Duración excedida'
		dataType: string
		lineageTag: a43e1689-d31f-4070-887d-6844e9ea53e8
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column 'Prioridad (h.)'
		dataType: string
		lineageTag: b80e1cec-929b-462f-9e8f-52cce54b6f7e
		summarizeBy: none
		sourceColumn: Prioridad (h.)

		annotation SummarizationSetBy = Automatic

	column 'Valor objetivo'
		dataType: int64
		formatString: 0
		lineageTag: 0acfd337-28d8-4c09-8b3b-e85805b9e4bb
		summarizeBy: sum
		sourceColumn: Valor objetivo

		annotation SummarizationSetBy = Automatic

	column 'Duracion Horas'
		dataType: double
		lineageTag: c40a528f-2970-4559-be4a-9c231fb9c002
		summarizeBy: sum
		sourceColumn: Duracion Horas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa desviación'
		dataType: double
		lineageTag: 1985a663-94a9-4986-bf75-816408dc2317
		summarizeBy: sum
		sourceColumn: Tasa desviación

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa desviación2'
		dataType: double
		lineageTag: 0319d0bc-9ad3-44e3-aefe-017dee05736b
		summarizeBy: sum
		sourceColumn: Tasa desviación2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Personalizado
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1e99edb6-6b54-4bb8-9116-64a82710544c
		summarizeBy: none
		sourceColumn: Personalizado

		annotation SummarizationSetBy = Automatic

	column NumeroMes
		dataType: int64
		formatString: 0
		lineageTag: b68fa1b2-ebba-431d-93ff-dea7c007d545
		summarizeBy: sum
		sourceColumn: NumeroMes

		annotation SummarizationSetBy = Automatic

	column 'Estado del incidente'
		dataType: string
		lineageTag: 4f38fcd2-bfe1-4adc-a075-c6c5f2730128
		summarizeBy: none
		sourceColumn: Estado del incidente

		annotation SummarizationSetBy = Automatic

	partition KGI_II_Incidencias_Total_F_Abierta-5205b14a-08f1-455e-880f-2e6ea19c8942 = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source = ```
				let
				    Origen = KGI_II_Incidencias_Total,
				    ID_KGI_2.3 = Table.AddColumn(Origen, "ID_KGI_2.3", each "2-3-3-0"),
				    ID_KGI_2.4 = Table.AddColumn(ID_KGI_2.3, 
				                 "ID_KGI_2.4", 
				                 each if [Prioridad] = "1 - Crítica" then "2-4-3-1" 
				                      else if [Prioridad] = "2 - Alta" then "2-4-3-2" 
				                      else null, 
				                type text),
				    #"Filas agrupadas" = Table.Group(ID_KGI_2.4, {"Número", "Abierto mes", "Subcategoría", "Prioridad grupo ANS1.3", "Elemento de configuración", "Infringido_alegaciones", "Código de cierre", "Tipo de Solución", "ID_KGI_2.3", "ID_KGI_2.4", "ID_KGI_2.5", "Alegaciones", "Abierto por"}, {{"Recuento", each Table.RowCount(_), Int64.Type}, {"Duración acumulada", each List.Sum([Duración del negocio]), type nullable number}}),
				    Personalizado1 = Table.AddColumn(ID_KGI_2.4, "NumeroMes", each if [Abierto mes] = #date(2023, 6, 1) then 1 else if [Abierto mes] = #date(2023, 7, 1) then 2 else if [Abierto mes] = #date(2023, 8, 1) then 3 else if [Abierto mes] = #date(2023, 9, 1) then 4 else if [Abierto mes] = #date(2023, 10, 1) then 5 else if [Abierto mes] = #date(2023, 11, 1) then 6 else if [Abierto mes] = #date(2023, 12, 1) then 7 else if [Abierto mes] = #date(2024, 1, 1) then 8 else if [Abierto mes] = #date(2024, 2, 1) then 9 else if [Abierto mes] = #date(2024, 3, 1) then 10 else if [Abierto mes] = #date(2024, 4, 1) then 11 else if [Abierto mes] = #date(2024, 5, 1) then 12 else null),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Personalizado1,{{"NumeroMes", Int64.Type}})
				in
				    #"Tipo cambiado"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

