table KGI_I_Estimaciones
	lineageTag: eec3e591-c444-4d46-983c-41bc0f8f220e

	measure 'Duración Negocio Estimaciones(H.)' = AVERAGE(KGI_I_Estimaciones[Duracion negocio (h.)])
		formatString: 0.00
		lineageTag: 2934522c-8f40-4d92-a511-a88b436087bd

	column Creado
		dataType: dateTime
		formatString: General Date
		lineageTag: 4f3b83af-6f25-4a1f-a8eb-2b8fde812fe8
		summarizeBy: none
		sourceColumn: Creado

		variation Variación
			isDefault
			relationship: a002ea0c-a0b3-4a35-b68f-02788397b812
			defaultHierarchy: LocalDateTable_866d02f0-3191-45c1-8894-210dcb0201b0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 7160fc8e-5be5-4428-a4aa-284224956b34
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio'
		dataType: string
		lineageTag: 473bb4f4-f7e8-4c02-9cf5-782816b40cd8
		summarizeBy: none
		sourceColumn: Aplicación de Negocio

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 549892a5-4115-48ab-b7dc-2aa2e83edbf9
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Tarea
		dataType: string
		lineageTag: ec020f52-e4bb-4ce0-8f40-3347839c8556
		summarizeBy: none
		sourceColumn: Tarea

		annotation SummarizationSetBy = Automatic

	column Etapa
		dataType: string
		lineageTag: 234d6098-add1-4f83-9e55-dc2eb0183879
		summarizeBy: none
		sourceColumn: Etapa

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de negocio restante'
		dataType: int64
		formatString: 0
		lineageTag: 8b2a81fd-85f2-456b-938c-8e258344394b
		summarizeBy: sum
		sourceColumn: Tiempo de negocio restante

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: int64
		formatString: 0
		lineageTag: bd4c2f71-5e83-41d2-987b-91b6a32f4ef6
		summarizeBy: sum
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: f260bad9-65e5-4e7f-a492-702cc047d918
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Hora de inicio'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8f870a27-b270-4c6c-adfb-2b7d0dc0ef0a
		summarizeBy: none
		sourceColumn: Hora de inicio

		variation Variación
			isDefault
			relationship: 51384df7-60aa-4f25-bb54-cdf235940aa6
			defaultHierarchy: LocalDateTable_bdf6bd5f-629b-4ed7-9aba-7ec1247743de.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de pausa'
		dataType: string
		lineageTag: 8f1cf90d-90a3-44f7-9777-9e9abee0328f
		summarizeBy: none
		sourceColumn: Tiempo de pausa

		annotation SummarizationSetBy = Automatic

	column 'Hora de finalización'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 48456e00-d1ee-459a-bef1-458b311d2ae7
		summarizeBy: none
		sourceColumn: Hora de finalización

		variation Variación
			isDefault
			relationship: fc7af690-b02b-4015-bdce-f98e504f37f9
			defaultHierarchy: LocalDateTable_e943d039-d514-4b52-b19d-e624fd7cbd5b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Grupo de asignación'
		dataType: string
		lineageTag: 4603a24d-a675-4df6-bc2a-0095b99fc8e7
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9f0189d3-9c8e-4123-b335-d4e17c08181b
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Hora de infracción'
		dataType: dateTime
		formatString: General Date
		lineageTag: b95c5869-d7a5-401c-a64b-8e31629c5de7
		summarizeBy: none
		sourceColumn: Hora de infracción

		variation Variación
			isDefault
			relationship: 0b391070-c4fa-4cc9-8254-9a15fd4084c5
			defaultHierarchy: LocalDateTable_cdd35053-11b8-48cd-bfc0-cab7909be51e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: 42a99295-0603-41a4-9eb8-eea8bc727bd3
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Prioridad grupo'
		dataType: string
		lineageTag: 98c9cdc2-cb4b-4a77-9d06-3502e0e938a3
		summarizeBy: none
		sourceColumn: Prioridad grupo

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI1.1'
		dataType: string
		lineageTag: 55afdebb-654a-4efa-b228-38668f234ff2
		summarizeBy: none
		sourceColumn: ID_KGI1.1

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.ID Alegación'
		dataType: string
		lineageTag: 54a8aac6-36c1-4bb0-806b-c78b9a654b5e
		summarizeBy: none
		sourceColumn: T_Alegaciones.ID Alegación

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.Estado'
		dataType: string
		lineageTag: 286eecd2-e644-470a-b19d-9870fe087c78
		summarizeBy: none
		sourceColumn: T_Alegaciones.Estado

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.Solicitante'
		dataType: string
		lineageTag: 8862d819-17c5-4bf7-a448-2a0ac3a7ebcc
		summarizeBy: none
		sourceColumn: T_Alegaciones.Solicitante

		annotation SummarizationSetBy = Automatic

	column 'Finalización mes'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d3f88736-5813-4964-826f-0b9f13eca526
		summarizeBy: none
		sourceColumn: Finalización mes

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'T_Alegaciones.ANS'
		dataType: string
		lineageTag: 2c6a3bc2-db5f-4863-b562-d19135b3573a
		summarizeBy: none
		sourceColumn: T_Alegaciones.ANS

		annotation SummarizationSetBy = Automatic

	column 'Duración tabla' = ```
			
			
			VAR VDUR21_2 = KGI_I_Estimaciones[Duración del negocio]
			VAR _duracCalculada = INT (VDUR21_2/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_2/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21_2/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21_2,60)),2)
			
			RETURN 
			
			_duracCalculada
			```
		lineageTag: b2bf499a-da62-44b4-b76e-22b3ba31e152
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración excedida'
		dataType: string
		lineageTag: cc70aa19-c0bc-4138-b99f-90c8810cd34d
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column Duración_excedida_tabla = ```
			
			
			VAR VDUR21_EX_2 = KGI_I_Estimaciones[Duración excedida]
			VAR _duracCalculada = INT
			    (VDUR21_EX_2/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_EX_2/3600,24)),2)&" HH"
			
			RETURN 
			
			_duracCalculada
			```
		lineageTag: ce35d790-81f7-4ee7-b54e-2c3aed67ea17
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Infringido_alegaciones
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: afd3e0da-feb0-4cae-944c-a78591ccb5c4
		summarizeBy: none
		sourceColumn: Infringido_alegaciones

		annotation SummarizationSetBy = Automatic

	column 'Duracion Horas'
		dataType: double
		lineageTag: a84c8b2e-90a8-4c24-b88e-59eb8c736334
		summarizeBy: average
		sourceColumn: Duracion Horas

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duracion negocio (h.)' = KGI_I_Estimaciones[Duración del negocio] / 3600
		formatString: 0.00
		lineageTag: 5bbee771-cee1-4f1b-ab22-e83e665568cc
		summarizeBy: average

		annotation SummarizationSetBy = User

	column 'Prioridad jornadas'
		dataType: string
		lineageTag: 8876c37a-ad6d-4895-89f6-8616e3325546
		summarizeBy: none
		sourceColumn: Prioridad jornadas

		annotation SummarizationSetBy = Automatic

	column 'Valor Objetivo jornadas'
		dataType: int64
		formatString: 0
		lineageTag: 73f12599-02ec-46c5-9e32-a3490db8bcaa
		summarizeBy: sum
		sourceColumn: Valor Objetivo jornadas

		annotation SummarizationSetBy = Automatic

	column 'Duración negocio(h)'
		dataType: double
		lineageTag: 455b22f3-287c-4076-838b-7ce880fed477
		summarizeBy: sum
		sourceColumn: Duración negocio(h)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Valor Objetivo (h.)'
		dataType: int64
		formatString: 0
		lineageTag: a4d7b1d9-5a16-4997-8d58-881a699a337d
		summarizeBy: sum
		sourceColumn: Valor Objetivo (h.)

		annotation SummarizationSetBy = Automatic

	column 'Tasa desviación'
		dataType: double
		lineageTag: e0cf45c7-5009-466e-b8ae-f1924e11092d
		summarizeBy: sum
		sourceColumn: Tasa desviación

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Personalizado
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ca4e8242-4d71-4ce9-92c6-c577557657d5
		summarizeBy: none
		sourceColumn: Personalizado

		annotation SummarizationSetBy = Automatic

	column Empresa
		dataType: string
		lineageTag: 19b5d68b-c30a-43e5-919d-97a35ad93b15
		summarizeBy: none
		sourceColumn: Empresa

		annotation SummarizationSetBy = Automatic

	partition KGI_I_Estimaciones-6c038d24-7398-4a9c-a5f4-fbb4fdfc03ee = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source = ```
				let
				    Origen = #"KGI_I_Estimaciones (stagging)",
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Creado", type datetime}, {"Número", type text}, {"Aplicación de Negocio", type text}, {"Prioridad", type text}, {"Tarea", type text}, {"Etapa", type text}, {"Tiempo de negocio restante", Int64.Type}, {"Duración del negocio", Int64.Type}, {"Porcentaje de negocio trascurrido", type number}, {"Hora de inicio", type datetime}, {"Tiempo de pausa", type any}, {"Hora de finalización", type datetime}, {"Grupo de asignación", type text}, {"Infringido", type logical}, {"Hora de infracción", type datetime}, {"Duración", Int64.Type}}),
				    #"Inicio de mes insertado" = Table.AddColumn(#"Tipo cambiado", "Finalización mes", each Date.StartOfMonth([Hora de finalización]), type date),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Inicio de mes insertado",{{"Finalización mes", type date}}),
				    #"Texto en mayúsculas" = Table.TransformColumns(#"Tipo cambiado1",{{"Aplicación de Negocio", Text.Upper, type text}}),
				
				// Homologa prioridades
				
				    #"Columna condicional agregada" = Table.AddColumn(#"Texto en mayúsculas", "Prioridad grupo", each if [Prioridad] = "1 - Crítica" then "Crítica" else if [Prioridad] = "2 - Alta" then "Alta" 
				else if [Prioridad] = "3 - Moderada" then "Media" else if [Prioridad] = "4 - Baja" then "Baja" else if [Prioridad] = "5 - Muy Baja" then "Baja" else null, type text),
				    #"Columna condicional agregada1" = Table.AddColumn(#"Columna condicional agregada", "ID_KGI1.1", each if [Prioridad grupo] = "Crítica" then "1-1-2-1" else if [Prioridad grupo] = "Alta" then "1-1-2-2" else if [Prioridad grupo] = "Media" then "1-1-2-3" else if [Prioridad grupo] = "Baja" then "1-1-2-4" else null, type text),
				    #"Duración cambiado a Duración SLA" = Table.RenameColumns(#"Columna condicional agregada1",{{"Duración", "Duración SLA"}}),
				    #"Cálculo Duración excedida" = Table.AddColumn(#"Duración cambiado a Duración SLA", "Duración excedida", 
				    each if ([Duración del negocio]-[Duración SLA])<0 then 0 else 
				    ([Duración del negocio]-[Duración SLA])),
				    #"Transformado %_negocio" = Table.TransformColumns(#"Cálculo Duración excedida", {{"Porcentaje de negocio trascurrido", each _ / 100, Percentage.Type}}),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Transformado %_negocio", {"Tarea"}, T_Alegaciones, {"ID"}, "T_Alegaciones", JoinKind.LeftOuter),
				    #"Se expandió T_Alegaciones" = Table.ExpandTableColumn(#"Consultas combinadas1", "T_Alegaciones", {"ID Alegación", "Solicitante", "ANS", "Estado"}, {"T_Alegaciones.ID Alegación", "T_Alegaciones.Solicitante", "T_Alegaciones.ANS", "T_Alegaciones.Estado"}),
				    #"Infringido con alegaciones" = Table.AddColumn( #"Se expandió T_Alegaciones", "Infringido_alegaciones", each if [Infringido] = true and [T_Alegaciones.Estado] = "1 - Aprobada" and [T_Alegaciones.ANS] = "KGI 1-1" then false else [Infringido], Logical.Type),
				    #"Duplicados quitados" = Table.Distinct(#"Infringido con alegaciones", {"Tarea"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Duplicados quitados", "Duracion Horas", each [Duración del negocio] / 3600),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Duracion Horas", type number}}),
				    #"Columna condicional agregada5" = Table.AddColumn(#"Tipo cambiado2", "Prioridad jornadas", each if [Prioridad grupo] = "Alta" then "Alta - 3 Jornadas" else if [Prioridad grupo] = "Media" then "Media - 4 Jornadas" else if [Prioridad grupo] = "Baja" then "Baja - 5 Jornadas" else null),
				    #"Columna condicional agregada2" = Table.AddColumn(#"Columna condicional agregada5", "Valor Objetivo", each if [Prioridad grupo] = "Alta" then 3 else if [Prioridad grupo] = "Media" then 4 else if [Prioridad grupo] = "Baja" then 5 else null),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Columna condicional agregada2",{{"Valor Objetivo", Int64.Type}}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado3", "Duración negocio(h)", each [Duración del negocio] / 3600),
				    #"Personalizada agregada2" = Table.AddColumn(#"Personalizada agregada1", "Valor Objetivo (h.)", each [Valor Objetivo] * 8),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Personalizada agregada2",{"Creado", "Número", "Aplicación de Negocio", "Prioridad", "Tarea", "Etapa", "Tiempo de negocio restante", "Duración del negocio", "Porcentaje de negocio trascurrido", "Hora de inicio", "Tiempo de pausa", "Hora de finalización", "Grupo de asignación", "Infringido", "Hora de infracción", "Duración SLA", "Finalización mes", "Prioridad grupo", "ID_KGI1.1", "Duración excedida", "T_Alegaciones.ID Alegación", "T_Alegaciones.Solicitante", "T_Alegaciones.ANS", "T_Alegaciones.Estado", "Infringido_alegaciones", "Duracion Horas", "Prioridad jornadas", "Valor Objetivo", "Valor Objetivo (h.)", "Duración negocio(h)"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"Valor Objetivo", "Valor Objetivo jornadas"}}),
				    #"Tipo cambiado4" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Valor Objetivo (h.)", Int64.Type}, {"Duración negocio(h)", type number}}),
				    #"Personalizada agregada3" = Table.AddColumn(#"Tipo cambiado4", "Tasa desviación", each [#"Duración negocio(h)"] / [#"Valor Objetivo (h.)"]),
				    #"Tipo cambiado5" = Table.TransformColumnTypes(#"Personalizada agregada3",{{"Tasa desviación", type number}}),
				    #"Columna condicional agregada3" = Table.AddColumn(#"Tipo cambiado5", "Personalizado", each if [#"Duración negocio(h)"] > [#"Valor Objetivo (h.)"] then true else false),
				    #"Tipo cambiado6" = Table.TransformColumnTypes(#"Columna condicional agregada3",{{"Personalizado", type logical}})
				in
				    #"Tipo cambiado6"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

