table KGI_II_Incidencias_Total
	lineageTag: ac32378e-b508-4fee-830a-5fa5a12b37bc

	measure 'Duración Negocio In. Total(H.)' = AVERAGE(KGI_II_Incidencias_Total[Duracion(h.)])
		formatString: 0.00
		lineageTag: 88eb23a2-86cd-4142-8b82-a24696bc6f93

	column Número
		dataType: string
		lineageTag: a9465cde-7e7d-45d8-a75b-f3bf9700cd46
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 0aef3c4d-7123-47bd-9217-5f9737da34b1
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Subcategoría
		dataType: string
		lineageTag: 0e2baa89-3738-44fa-bc72-271bd7623dfe
		summarizeBy: none
		sourceColumn: Subcategoría

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 73e408aa-9a2e-48e0-858a-617231bfb1ca
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 5607d493-ee12-4a55-8ec4-8c5f08b91021
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 53a9e890-ae88-436d-9c2a-c95dd376d1be
			defaultHierarchy: LocalDateTable_2c910b64-ed85-4499-b215-864546c87296.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Cerrado
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a2700422-333d-4da5-813a-ac06212d4d71
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: 8bdefd5c-cc1e-46e7-a01a-88f47c691f91
			defaultHierarchy: LocalDateTable_e38940ac-6f47-4211-95bd-5d2845707eed.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Duración
		dataType: string
		lineageTag: 8cfe726b-a4f0-4f77-a913-b51701e2b2f8
		summarizeBy: none
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2c3244f2-3943-4c09-b67e-830223d13c99
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: double
		lineageTag: 2d35318f-1819-4607-b598-f885111fa487
		summarizeBy: sum
		sourceColumn: Tiempo original de incumplimiento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tipo de Solución'
		dataType: string
		lineageTag: 20522309-98c1-4518-8ba3-3e2f35b665b8
		summarizeBy: none
		sourceColumn: Tipo de Solución

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 6e45bfe8-15ca-493a-9080-7a6a9bb5fd61
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'ID de correlación'
		dataType: string
		lineageTag: 6d026922-9c5c-4462-9228-a016a50efd87
		summarizeBy: none
		sourceColumn: ID de correlación

		annotation SummarizationSetBy = Automatic

	column Principal
		dataType: string
		lineageTag: ce550bcd-0373-4951-9183-4cb898db984a
		summarizeBy: none
		sourceColumn: Principal

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: 90985722-ee30-4ca5-bf7e-6f46d2feb010
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variación
			isDefault
			relationship: 4bb29cb1-1476-44b3-8f54-28f26074fc4e
			defaultHierarchy: LocalDateTable_22b4de05-f895-45d1-9a8a-62c743234f81.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 91465c59-b450-4eee-8701-31d1b1dd2981
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column 'Abierto mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e9b56536-0428-446b-8c42-25c458cc1b25
		summarizeBy: none
		sourceColumn: Abierto mes

		variation Variación
			isDefault
			relationship: 8c6d659b-5212-4fea-8b36-2c9c54695ddf
			defaultHierarchy: LocalDateTable_8d30a9e5-932f-4ba7-8d8f-606ad6b025be.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Cerrado mes'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 470d526d-fa7d-4a9c-815c-f3094ea1d152
		summarizeBy: none
		sourceColumn: Cerrado mes

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Abiertas tres meses previos'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bfd61fca-58eb-4cd1-92db-2fe61c0b760d
		summarizeBy: none
		sourceColumn: Abiertas tres meses previos

		variation Variación
			isDefault
			relationship: c37ddcaf-9f42-4205-b0c7-faa57b7ae4a7
			defaultHierarchy: LocalDateTable_0f5a5f9a-ef6f-4df4-ab36-07136af9ca07.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Abiertas seis meses previos'
		dataType: dateTime
		formatString: Long Date
		lineageTag: de15397f-7401-46ab-9c82-3220305a1a05
		summarizeBy: none
		sourceColumn: Abiertas seis meses previos

		variation Variación
			isDefault
			relationship: d44d5825-d485-4cac-b758-6419f48db855
			defaultHierarchy: LocalDateTable_a5dde98e-94e8-434f-9ea7-87b5bbaf8c6b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Prioridad grupo ANS1.3'
		dataType: string
		lineageTag: 51c38d1c-7608-430a-928c-09d8f71ca040
		summarizeBy: none
		sourceColumn: Prioridad grupo ANS1.3

		annotation SummarizationSetBy = Automatic

	column 'Prioridad grupo ANS2.4'
		dataType: string
		lineageTag: 9f846c41-299c-4c7e-be82-67c476ececa2
		summarizeBy: none
		sourceColumn: Prioridad grupo ANS2.4

		annotation SummarizationSetBy = Automatic

	column 'SLA_III_Peticiones.Solicitar elemento'
		dataType: string
		lineageTag: 7031935c-1d59-499f-9f09-1be96d6a65f2
		summarizeBy: none
		sourceColumn: SLA_III_Peticiones.Solicitar elemento

		annotation SummarizationSetBy = Automatic

	column 'SLA_III_Peticiones.Cerrado mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 847494fc-9740-49b5-8915-717c12d36520
		summarizeBy: none
		sourceColumn: SLA_III_Peticiones.Cerrado mes

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ID_KGI2.1'
		dataType: string
		lineageTag: a2975ec1-ca2d-40cb-8392-6898da6b9a89
		summarizeBy: none
		sourceColumn: ID_KGI2.1

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_2.2'
		dataType: string
		lineageTag: 68b89669-7f7f-4a3d-849e-f922fe42725a
		summarizeBy: none
		sourceColumn: ID_KGI_2.2

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_2.5'
		dataType: string
		lineageTag: 6d63a68e-ac54-4d14-a455-bcb58ab1a859
		summarizeBy: none
		sourceColumn: ID_KGI_2.5

		annotation SummarizationSetBy = Automatic

	column 'SLA_III_Peticiones.Prioridad'
		dataType: string
		lineageTag: 9169c312-c5c1-4380-a539-46ccc3d7e2c2
		summarizeBy: none
		sourceColumn: SLA_III_Peticiones.Prioridad

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI3.2'
		dataType: string
		lineageTag: 182594ed-0500-4c84-8fbb-14e318bbd840
		summarizeBy: none
		sourceColumn: ID_KGI3.2

		annotation SummarizationSetBy = Automatic

	column Proyecto_Evolutivo
		dataType: string
		lineageTag: bf523a32-59aa-448b-a6f0-10077e2e55ed
		summarizeBy: none
		sourceColumn: Proyecto_Evolutivo

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI1.3'
		dataType: string
		lineageTag: 3e9d49b0-c845-4009-8587-abecdc862f01
		summarizeBy: none
		sourceColumn: ID_KGI1.3

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: int64
		formatString: 0
		lineageTag: 0cc285d2-6bf4-44ea-8cb2-351a8afa2dc6
		summarizeBy: sum
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: c20957e1-6785-4664-94fa-d3df5ccad3f9
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: int64
		formatString: 0
		lineageTag: e3886919-fa60-49c2-bced-ec870923a702
		summarizeBy: sum
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: double
		formatString: 0
		lineageTag: 5d01d5d8-cac9-483b-9aeb-e9cc8870eeba
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Número'
		dataType: string
		lineageTag: f7c2dde7-8106-423a-9cde-230314277e55
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Número

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Tipo de Proyecto'
		dataType: string
		lineageTag: f2787f1f-989a-4a80-97e2-206b880c1784
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad'
		dataType: string
		lineageTag: bbf1d7eb-4040-4d25-8910-8f6c23eb4576
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Nombre'
		dataType: string
		lineageTag: 05a6e781-49e9-4d25-9121-43686f950591
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Nombre

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Inicio'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1cd7d88c-b632-431e-a898-43728c5ec4aa
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Inicio

		variation Variación
			isDefault
			relationship: b5e357db-b64b-450e-980e-30e0164395a1
			defaultHierarchy: LocalDateTable_300e39ec-492c-4f9d-b0fd-d10d9a81cea3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Fin'
		dataType: dateTime
		formatString: General Date
		lineageTag: 53d78a11-c9c1-49b9-ac37-55383fc9ef5a
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Fin

		variation Variación
			isDefault
			relationship: 87afd660-c025-44b3-9074-1948726c000f
			defaultHierarchy: LocalDateTable_202ce28b-f63a-4e7d-a800-ef06f784db29.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 772874f8-41fb-4ff3-ae96-f0f2d83baac8
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Fecha fin real

		variation Variación
			isDefault
			relationship: 7f49c97a-7ada-481f-bd5b-23900e36ceb4
			defaultHierarchy: LocalDateTable_61671434-02d7-49bd-8148-28e37d4a9589.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.ID_KGI1.3'
		dataType: string
		lineageTag: 0868b442-1914-4541-9112-72f7601ab5b5
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.ID_KGI1.3

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Proyecto_Evolutivo'
		dataType: string
		lineageTag: 0640456b-8cd2-450e-a499-8ec40b5235ee
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Proyecto_Evolutivo

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Planificaciones PRJ y MEJ con SLA.Aplicación de Negocio'
		dataType: string
		lineageTag: 07b7f0dd-c825-4d1c-837f-aaca2159926e
		summarizeBy: none
		sourceColumn: KGI_I_Planificaciones PRJ y MEJ con SLA.Aplicación de Negocio

		annotation SummarizationSetBy = Automatic

	column 'Usuarios interesados'
		dataType: string
		lineageTag: 5ce5e824-560b-4088-a5d9-66ac4013b7f2
		summarizeBy: none
		sourceColumn: Usuarios interesados

		annotation SummarizationSetBy = Automatic

	column 'Causa probable'
		dataType: string
		lineageTag: ad566315-012a-4a42-9fae-d28c72efd7e4
		summarizeBy: none
		sourceColumn: Causa probable

		annotation SummarizationSetBy = Automatic

	column 'Lista de notas de trabajo'
		dataType: string
		lineageTag: 505b8f66-1a56-4613-9092-2e4dec6fbc6b
		summarizeBy: none
		sourceColumn: Lista de notas de trabajo

		annotation SummarizationSetBy = Automatic

	column 'Entrada del usuario'
		dataType: string
		lineageTag: f3fb0c08-0d0e-4ced-8823-ef884e6bacca
		summarizeBy: none
		sourceColumn: Entrada del usuario

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: dd142472-af61-480e-b47a-0355682f994b
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column 'Número de reasignación'
		dataType: string
		lineageTag: 10cf5011-81fa-46db-b62e-52ebbb6c32da
		summarizeBy: none
		sourceColumn: Número de reasignación

		annotation SummarizationSetBy = Automatic

	column 'Duración tabla' = ```
			
			
			VAR VDUR21_2 = KGI_II_Incidencias_Total[Duración del negocio]
			VAR _duracCalculada = INT (VDUR21_2/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_2/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21_2/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21_2,60)),2)
			
			RETURN 
			
			_duracCalculada
			```
		lineageTag: 014e1b05-f6a2-4912-8d36-f040a57609ce
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Infringido_alegaciones
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8b177523-7043-4fe6-9593-64f23168109d
		summarizeBy: none
		sourceColumn: Infringido_alegaciones

		annotation SummarizationSetBy = Automatic

	column Reabierta_texto
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 46bc960c-8e1b-4eac-9046-9c99c764b3ac
		summarizeBy: none
		sourceColumn: Reabierta_texto

		annotation SummarizationSetBy = Automatic

	column Estado_abierta
		dataType: string
		lineageTag: c1028d87-cefd-47cd-ae1f-ea7544134a9b
		summarizeBy: none
		sourceColumn: Estado_abierta

		annotation SummarizationSetBy = Automatic

	column 'SLA_III_Peticiones.Nombre'
		dataType: string
		lineageTag: 7ddd589e-1ad7-428f-978b-f42f8d433e57
		summarizeBy: none
		sourceColumn: SLA_III_Peticiones.Nombre

		annotation SummarizationSetBy = Automatic

	column Combinada
		dataType: string
		lineageTag: b336f197-08ce-44f8-9edf-40ce26c0112d
		summarizeBy: none
		sourceColumn: Combinada

		annotation SummarizationSetBy = Automatic

	column 'Duración excedida'
		dataType: string
		lineageTag: ce1e4c53-f5d9-4126-a06e-8b70fc48900d
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column 'Duración_EX D:HH:MM:SS' =
			
			VAR VDUR21_EX_2 = KGI_II_Incidencias_Total[Duración excedida]
			  RETURN INT
			    (VDUR21_EX_2/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_EX_2/3600,24)),2)&" HH"
		lineageTag: 9aa446af-03d1-4720-b882-e1326aead7c5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Extracción
		dataType: dateTime
		formatString: Long Date
		lineageTag: ebbe1524-cfc3-49bd-96a5-3961690b0430
		summarizeBy: none
		sourceColumn: Extracción

		variation Variación
			isDefault
			relationship: 2f2c83ff-145b-4672-8000-e48eff4fbc54
			defaultHierarchy: LocalDateTable_c517d549-143a-45bb-b412-5f0dfe8e709d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Elemento de configuración'
		dataType: string
		lineageTag: e3d81a13-851f-47a5-ae74-f072c04ce2d7
		summarizeBy: none
		sourceColumn: Elemento de configuración

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: f0a3b04d-7df2-4d49-978e-b8c160ea5561
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Abierto por'
		dataType: string
		lineageTag: 26580dd6-18fc-4e77-bbb0-6a37e7e1a4db
		summarizeBy: none
		sourceColumn: Abierto por

		annotation SummarizationSetBy = Automatic

	column Alegaciones
		dataType: string
		lineageTag: 5c79e282-caaf-4199-aeef-b20fd7cd49c0
		summarizeBy: none
		sourceColumn: Alegaciones

		annotation SummarizationSetBy = Automatic

	column 'Duracion(h.)' = KGI_II_Incidencias_Total[Duración del negocio] / 3600
		formatString: 0.00
		lineageTag: 68bce7be-bb3b-4f4c-98cd-785de9ec1461
		summarizeBy: average

		annotation SummarizationSetBy = User

	column 'Prioridad (h.)'
		dataType: string
		lineageTag: c0cec646-d965-4fa0-a049-e64f52eae076
		summarizeBy: none
		sourceColumn: Prioridad (h.)

		annotation SummarizationSetBy = Automatic

	column 'Valor objetivo'
		dataType: int64
		formatString: 0
		lineageTag: 01568295-76b0-44cb-b2a6-2ddf46895a84
		summarizeBy: sum
		sourceColumn: Valor objetivo

		annotation SummarizationSetBy = Automatic

	column 'Duracion Horas'
		dataType: double
		lineageTag: 46d0c777-7d99-40b2-8262-bc9ebf76e419
		summarizeBy: sum
		sourceColumn: Duracion Horas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa desviación'
		dataType: double
		lineageTag: 84722775-6ed1-407c-b326-0c1a01152307
		summarizeBy: sum
		sourceColumn: Tasa desviación

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa desviación2'
		dataType: double
		lineageTag: 99cd1c2e-2f69-461b-9be1-ddce71b8f08e
		summarizeBy: sum
		sourceColumn: Tasa desviación2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Personalizado
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d9ae3a1c-e11d-4c77-a835-fc02c477accb
		summarizeBy: none
		sourceColumn: Personalizado

		annotation SummarizationSetBy = Automatic

	column 'Estado del incidente'
		dataType: string
		lineageTag: 2efc57a0-1541-44ae-8f1c-ca960f9b3b08
		summarizeBy: none
		sourceColumn: Estado del incidente

		annotation SummarizationSetBy = Automatic

	partition KGI_II_Incidencias_Total-1056548c-b840-4e6a-92fc-5b3a52c592b7 = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source = ```
				let
				    Origen = Table.Combine({KGI_II_Incidencias, KGI_II_Incidencias_Previas}),
				    #"Filas filtradas" = Table.SelectRows(Origen, each true),
				    #"Columnas renombradas" = Table.RenameColumns(#"Filas filtradas",{{"Volver a abrir recuento", "Reabierta"},  {"Código de resolución", "Código de cierre"}, {"Duración_1", "Duración SLA"}, /*{"Duración del negocio", "Duración real"},*/ {"Etapa", "Estado SLA"}, {"Resuelto", "Fecha de resolución"}}),
				    #"Columna combinada insertada" = Table.AddColumn(#"Columnas renombradas", "Combinada", each Text.Combine({[Número], "$", [Subcategoría], "$", [Principal]}), type text),
				    #"Inicio del mes insertado" = Table.AddColumn(#"Columna combinada insertada", "Inicio del mes", each Date.StartOfMonth([Abierto]), type datetime),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Inicio del mes insertado",{{"Inicio del mes", "Abierto mes"}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Abierto mes", type date}, {"Reabierta", Int16.Type}, {"Duración del negocio", Int64.Type}, {"Infringido", Logical.Type}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado",null,#date(2100, 1, 1),Replacer.ReplaceValue,{"Cerrado"}),
				    #"Transforma Porcentaje negocio" = Table.TransformColumns(#"Valor reemplazado", {{"Porcentaje de negocio trascurrido", each _ / 100, Percentage.Type}}),
				    #"Inicio del mes insertado1" = Table.AddColumn(#"Transforma Porcentaje negocio", "Inicio del mes", each Date.StartOfMonth([Cerrado]), type datetime),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Inicio del mes insertado1",{{"Inicio del mes", "Cerrado mes"}}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas con nombre cambiado1",{{"Cerrado mes", type date},{"Cerrado", type date},{"Abierto", type date}}),
				    #"Tres meses previos" = Table.AddColumn(#"Tipo cambiado1", "Abiertas tres meses previos", 
				    each if [Abierto mes] = List.Max(#"Tipo cambiado1"[Abierto mes]) then null else if [Abierto mes] >= Date.AddMonths(List.Max(#"Tipo cambiado1"[Abierto mes]), -3) then [Abierto mes] else null),
				    #"Seis meses previos" = Table.AddColumn(#"Tres meses previos", "Abiertas seis meses previos", 
				    each if [Abierto mes] = List.Max(#"Tipo cambiado1"[Abierto mes]) then null else if [Abierto mes] >= Date.AddMonths(List.Max(#"Tipo cambiado1"[Abierto mes]), -6) then [Abierto mes] else null),
				    Personalizado1 = #"Seis meses previos",
				    #"Tipo cambiado2" = Table.TransformColumnTypes(Personalizado1,{{"Abiertas tres meses previos", type date}, {"Abiertas seis meses previos", type date}}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Tipo cambiado2", "Prioridad grupo ANS1.3", each if [Prioridad] = "1 - Crítica" then "Crítica" else if [Prioridad] = "2 - Alta" then "Alta" else if [Prioridad] = "3 - Moderada" then "Media" else "Baja", type text),
				    #"Columna condicional agregada2" = Table.AddColumn(#"Columna condicional agregada", "Prioridad grupo ANS2.4", each if [Prioridad] = "1 - Crítica" then "Crítica" else if [Prioridad] = "2 - Alta" then "Alta" else if [Prioridad] = "3 - Moderada" then "Media" else "Baja", type text),
				    #"Consultas combinadas" = Table.NestedJoin(#"Columna condicional agregada2", {"Principal"}, KGI_III_Peticiones, {"Solicitar elemento"}, "SLA_III_Peticiones", JoinKind.LeftOuter),
				    #"Se expandió SLA_III_Peticiones" = Table.ExpandTableColumn(#"Consultas combinadas", "SLA_III_Peticiones", {"Solicitar elemento", "Nombre", "Prioridad", "Cerrado mes"}, {"SLA_III_Peticiones.Solicitar elemento", "SLA_III_Peticiones.Nombre", "SLA_III_Peticiones.Prioridad", "SLA_III_Peticiones.Cerrado mes"}),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Se expandió SLA_III_Peticiones", {"Principal"}, #"KGI_I_Planificaciones PRJ y MEJ con SLA", {"Número"}, "KGI_I_Planificaciones PRJ y MEJ con SLA", JoinKind.LeftOuter),
				    #"Se expandió KGI_I_Planificaciones PRJ y MEJ con SLA" = Table.ExpandTableColumn(#"Consultas combinadas1", "KGI_I_Planificaciones PRJ y MEJ con SLA", {"Número", "Tipo de Proyecto", "Prioridad", "Aplicación de Negocio", "Nombre", "Inicio", "Fin", "Fecha fin real", "ID_KGI1.3", "Proyecto_Evolutivo"}, {"KGI_I_Planificaciones PRJ y MEJ con SLA.Número", "KGI_I_Planificaciones PRJ y MEJ con SLA.Tipo de Proyecto", "KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad", "KGI_I_Planificaciones PRJ y MEJ con SLA.Aplicación de Negocio", "KGI_I_Planificaciones PRJ y MEJ con SLA.Nombre", "KGI_I_Planificaciones PRJ y MEJ con SLA.Inicio", "KGI_I_Planificaciones PRJ y MEJ con SLA.Fin", "KGI_I_Planificaciones PRJ y MEJ con SLA.Fecha fin real", "KGI_I_Planificaciones PRJ y MEJ con SLA.ID_KGI1.3", "KGI_I_Planificaciones PRJ y MEJ con SLA.Proyecto_Evolutivo"}),
				    ID_KGI_1.3 = Table.AddColumn(#"Se expandió KGI_I_Planificaciones PRJ y MEJ con SLA", 
				                  "ID_KGI1.3", 
				                  each if [#"KGI_I_Planificaciones PRJ y MEJ con SLA.Tipo de Proyecto"] = "Proyecto" then 
				                       each if [#"KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad"] = "1 - Crítica" then "1-3-1-2" 
				                            else if [#"KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad"] = "2 - Alta" then "1-3-1-2" 
				                            else if [#"KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad"] = "3 - Media" then "1-3-1-3" 
				                            else if [#"KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad"] = "4 - Baja" then "1-3-1-4"
				                            else if [#"KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad"] = "5 - Muy baja" then "1-3-1-4"
				                            else null
				                   else if [#"KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad"] = "1 - Crítica" then "1-3-2-2" 
				                            else if [#"KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad"] = "2 - Alta" then "1-3-2-2" 
				                            else if [#"KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad"] = "3 - Media" then "1-3-2-3" 
				                            else if [#"KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad"] = "4 - Baja" then "1-3-2-4"
				                            else if [#"KGI_I_Planificaciones PRJ y MEJ con SLA.Prioridad"] = "5 - Muy baja" then  "1-3-2-4"
				                   else null, type text),
				    ID_KGI_2.1 = Table.AddColumn(ID_KGI_1.3, 
				                 "ID_KGI2.1", 
				                 each if [Prioridad] = "1 - Crítica" then "2-1-3-1" 
				                      else if [Prioridad] = "2 - Alta" then "2-1-3-2" 
				                      else if [Prioridad] = "3 - Moderada" then "2-1-3-3" 
				                      else if [Prioridad] = "4 - Baja" then "2-1-3-4"
				                      else if [Prioridad] = "5 - Muy Baja" then "2-1-3-4" 
				                      else null, 
				                type text),
				    ID_KGI_2.2 = Table.AddColumn(ID_KGI_2.1, "ID_KGI_2.2", each "2-2-3-0"),
				    ID_KGI_2.5 = Table.AddColumn(ID_KGI_2.2, "ID_KGI_2.5", each Text.Replace([ID_KGI2.1], "2-1", "2-5"), type text),
				    ID_KGI_3.2 = Table.AddColumn(#"ID_KGI_2.5", 
				                 "ID_KGI3.2", 
				                 each if [SLA_III_Peticiones.Prioridad] = "1 - Crítica" then "4-2-4-1" 
				                      else if [SLA_III_Peticiones.Prioridad] = "2 - Alta" then "4-2-4-1" 
				                      else if [SLA_III_Peticiones.Prioridad] = "3 - Moderada" then "4-2-4-1" 
				                      else if [SLA_III_Peticiones.Prioridad] = "4 - Baja" then "4-2-4-1"
				                      else if [SLA_III_Peticiones.Prioridad] = "5 - Muy Baja" then "4-2-4-1" 
				                      else null, 
				                type text),
				    #"Consultas combinadas2" = Table.NestedJoin(ID_KGI_3.2, {"Número"}, T_Alegaciones_Resumen, {"ID"}, "T_Alegaciones_Resumen", JoinKind.LeftOuter),
				    #"Se expandió T_Alegaciones" = Table.ExpandTableColumn(#"Consultas combinadas2", "T_Alegaciones_Resumen", {"Alegaciones"}, {"Alegaciones"}),
				    #"Columna condicional agregada1" = Table.AddColumn(#"Se expandió T_Alegaciones", "Proyecto_Evolutivo", each if [#"KGI_I_Planificaciones PRJ y MEJ con SLA.Tipo de Proyecto"] = "Proyecto" then "Proyectos" else "Evolutivos"),
				    #"Infringido con alegaciones" = Table.AddColumn(#"Columna condicional agregada1", "Infringido_alegaciones", each if [Infringido] = true and [Alegaciones] <> null and Text.Contains([Alegaciones],"2-1") then false else [Infringido], Logical.Type),
				    #"Columna condicional agregada3" = Table.AddColumn(#"Infringido con alegaciones", "Reabierta_texto", each if [Reabierta] > 0 and [Alegaciones] <> null and Text.Contains([Alegaciones],"2-2") then false else if [Reabierta] = 0 then false else true,Logical.Type),
				    #"Columna condicional agregada4" = Table.AddColumn(#"Columna condicional agregada3", "Estado_abierta", each if Date.Month([Cerrado]) > Date.Month([Abierto]) or Date.Year([Cerrado]) > Date.Year([Abierto]) then true else false),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Columna condicional agregada4",null,0,Replacer.ReplaceValue,{"Duración SLA"}),
				    #"Duración excedida añadida" = Table.AddColumn(#"Valor reemplazado1", "Duración excedida", 
				    each if [Duración del negocio] = null then null
				    else if ([Duración del negocio]-[Duración SLA])<0 then 0 
				    else ([Duración del negocio]-[Duración SLA])),
				    #"Columna condicional agregada5" = Table.AddColumn(#"Duración excedida añadida", "Prioridad (h.)", each if [Prioridad grupo ANS1.3] = "Crítica" then "Crítica 8(h.)" else if [Prioridad grupo ANS1.3] = "Alta" then "Alta 72(h.)" else if [Prioridad grupo ANS1.3] = "Media" then "Media 48(h.)" else if [Prioridad grupo ANS1.3] = "Baja" then "Baja 96(h.)" else null),
				    Personalizado2 = Table.AddColumn(#"Columna condicional agregada5", "Valor objetivo", each if [Prioridad grupo ANS1.3] = "Crítica" then 8 else if [Prioridad grupo ANS1.3] = "Alta" then 72 else if [Prioridad grupo ANS1.3] = "Media" then 48 else if [Prioridad grupo ANS1.3] = "Baja" then 96 else null),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(Personalizado2,{{"Valor objetivo", Int64.Type}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Tipo cambiado3", "Duracion Horas", each [Duración del negocio] / 3600),
				    #"Tipo cambiado4" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Duracion Horas", type number}}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado4", "Tasa desviación", each ([Duracion Horas] - [Valor objetivo])/[Valor objetivo]),
				    #"Tipo cambiado5" = Table.TransformColumnTypes(#"Personalizada agregada1",{{"Tasa desviación", type number}}),
				    Personalizado3 = Table.AddColumn(#"Tipo cambiado5", "Tasa desviación2", each [Duracion Horas] /[Valor objetivo]),
				    #"Tipo cambiado6" = Table.TransformColumnTypes(Personalizado3,{{"Tasa desviación2", type number}}),
				    #"Columna condicional agregada6" = Table.AddColumn(#"Tipo cambiado6", "Personalizado", each if [Duracion Horas] > [Valor objetivo] then true else false),
				    #"Tipo cambiado7" = Table.TransformColumnTypes(#"Columna condicional agregada6",{{"Personalizado", type logical}})
				in
				    #"Tipo cambiado7"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

