table Maestro_tipo_proyecto
	lineageTag: f78e555a-2c47-408d-9f4c-67d92ac38628

	column 'Proyectos / Evolutivos'
		dataType: string
		lineageTag: 809ec90a-6899-4080-bcac-d54813aaeb78
		summarizeBy: none
		sourceColumn: Proyectos / Evolutivos

		annotation SummarizationSetBy = Automatic

	column Servicio
		dataType: int64
		formatString: 0
		lineageTag: 4ed4590f-6988-43bb-83ec-c93015137c0f
		summarizeBy: sum
		sourceColumn: Servicio

		annotation SummarizationSetBy = Automatic

	partition Maestro_tipo_proyecto-82966382-fdf3-4650-b8a1-923e10c496d9 = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCijKr0xNLskvVtJRMlSK1YlWci3LzyktySwDCxkpxcYCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Proyectos / Evolutivos" = _t, Servicio = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Proyectos / Evolutivos", type text},{"Servicio", Int8.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

