table KGI_III_Encuestas_new
	lineageTag: 238aca47-aa27-4267-ad25-f39ce85caa4b

	measure Encuesta_p1_CIO = SELECTEDVALUE(KGI_III_Encuestas_new[P1 - Valoración General])
		displayFolder: CIO
		lineageTag: 58334a47-81c6-44f3-9bf4-9085696b6b32

	measure Encuesta_p2_CIO = SELECTEDVALUE(KGI_III_Encuestas_new[P2 - Tiempo de respuesta])
		displayFolder: CIO
		lineageTag: 75005877-e29f-4409-a861-cce3c8fc01f3

	measure Encuesta_p3_CIO = SELECTEDVALUE(KGI_III_Encuestas_new[P3 - Aptitud])
		displayFolder: CIO
		lineageTag: f82123d9-4e00-444e-ac64-21cb6b377a47

	measure Encuesta_p4_CIO = SELECTEDVALUE(KGI_III_Encuestas_new[P4 - Actitud])
		displayFolder: CIO
		lineageTag: 2c804730-72ee-40ea-aef4-c7b147c6a37b

	measure Encuesta_p5_CIO = SELECTEDVALUE(KGI_III_Encuestas_new[P5 - Seguimiento])
		displayFolder: CIO
		lineageTag: fead8c2a-ff2a-4663-a17a-3942e49390d5

	column Instancia
		dataType: string
		lineageTag: a359d732-65cf-4dce-86ad-6dd5410e9b9d
		summarizeBy: none
		sourceColumn: Instancia

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: Long Date
		lineageTag: c194e17a-a886-4c29-b2b0-d1d6a251fbd4
		summarizeBy: none
		sourceColumn: Cerrado

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Actualizado
		dataType: dateTime
		formatString: General Date
		lineageTag: 27906b53-44ef-49c3-86a7-f4407a34a9f1
		summarizeBy: none
		sourceColumn: Actualizado

		variation Variación
			isDefault
			relationship: b3879539-3c47-46f6-979b-af8a47501482
			defaultHierarchy: LocalDateTable_ab63d75b-023b-45b5-a05b-ee2ef2e343bc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: e6fa1805-9a89-4de8-8829-343970b90234
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Número_1
		dataType: string
		lineageTag: bba1374c-0401-44ad-af10-e4e9fbb6372e
		summarizeBy: none
		sourceColumn: Número_1

		annotation SummarizationSetBy = Automatic

	column Elemento
		dataType: string
		lineageTag: 9ab230f5-9a0f-4e16-8051-07f6d3a7f2d4
		summarizeBy: none
		sourceColumn: Elemento

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: d1363693-79ad-44e0-8b8c-248ad9a9c179
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Creación encuesta mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 684bddc4-4dc1-4d2e-8432-9b2f7f4cdd1d
		summarizeBy: none
		sourceColumn: Creación encuesta mes

		variation Variación
			isDefault
			relationship: 68c8292c-2bc3-45f6-bd00-c3b7ef829985
			defaultHierarchy: LocalDateTable_81e17fa8-21da-4225-b5b4-7073b76b9bd8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'P3 - Aptitud'
		dataType: string
		lineageTag: 99f05f2d-b986-42f5-9543-8e35dde91117
		summarizeBy: none
		sourceColumn: P3 - Aptitud

		annotation SummarizationSetBy = Automatic

	column 'P4 - Actitud'
		dataType: string
		lineageTag: aa7dfb82-dd46-4fa4-ae17-5e8b681da2ea
		summarizeBy: none
		sourceColumn: P4 - Actitud

		annotation SummarizationSetBy = Automatic

	column 'P5 - Seguimiento'
		dataType: string
		lineageTag: ca66fa02-578b-4db0-b2f3-432533b8b3a6
		summarizeBy: none
		sourceColumn: P5 - Seguimiento

		annotation SummarizationSetBy = Automatic

	column 'P1 - Valoración General'
		dataType: string
		lineageTag: 7bc8cffd-3cd0-4365-80bf-4c30e9bcf381
		summarizeBy: none
		sourceColumn: P1 - Valoración General

		annotation SummarizationSetBy = Automatic

	column 'P2 - Tiempo de respuesta'
		dataType: string
		lineageTag: 4f91fe79-d8aa-454d-bc66-74bb04f07f42
		summarizeBy: none
		sourceColumn: P2 - Tiempo de respuesta

		annotation SummarizationSetBy = Automatic

	column 'Nota Media' = ```
			
			
			IF(KGI_III_Encuestas_new[P3 - Aptitud] = "N/A" || KGI_III_Encuestas_new[P3 - Aptitud] = "N/D", 
			        IF(KGI_III_Encuestas_new[P4 - Actitud] = "N/A" || KGI_III_Encuestas_new[P4 - Actitud] = "N/D", 
			        (KGI_III_Encuestas_new[P1 - Valoración General] * 2 + KGI_III_Encuestas_new[P2 - Tiempo de respuesta] * 2 + KGI_III_Encuestas_new[P5 - Seguimiento] * 2) / 3,
			        (KGI_III_Encuestas_new[P1 - Valoración General] * 2 + KGI_III_Encuestas_new[P2 - Tiempo de respuesta] * 2 + KGI_III_Encuestas_new[P5 - Seguimiento] * 2 + KGI_III_Encuestas_new[P4 - Actitud] * 2.5) / 4),
			            IF(KGI_III_Encuestas_new[P4 - Actitud] = "N/A" || KGI_III_Encuestas_new[P4 - Actitud] = "N/D",
			            (KGI_III_Encuestas_new[P1 - Valoración General] * 2 + KGI_III_Encuestas_new[P2 - Tiempo de respuesta] * 2 + KGI_III_Encuestas_new[P5 - Seguimiento] * 2 + KGI_III_Encuestas_new[P3 - Aptitud] * 2.5) / 4,
			            (KGI_III_Encuestas_new[P1 - Valoración General] * 2 + KGI_III_Encuestas_new[P2 - Tiempo de respuesta] * 2 + KGI_III_Encuestas_new[P3 - Aptitud] * 2.5 + KGI_III_Encuestas_new[P4 - Actitud] * 2.5 + KGI_III_Encuestas_new[P5 - Seguimiento] * 2) / 5))
			```
		lineageTag: 2921436b-9b46-48a7-829f-c36d25e8b205
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Abierto por'
		dataType: string
		lineageTag: 090c9711-f6ba-450c-b055-d71663f6bb51
		summarizeBy: none
		sourceColumn: Abierto por

		annotation SummarizationSetBy = Automatic

	column Satisfaction
		dataType: string
		lineageTag: 9c167419-889b-4a30-8753-6797a023178d
		summarizeBy: none
		sourceColumn: Satisfaction

		annotation SummarizationSetBy = Automatic

	column 'Definición de SLA'
		dataType: string
		lineageTag: 92abfff2-41f0-4fbf-862e-7450036dab01
		summarizeBy: none
		sourceColumn: Definición de SLA

		annotation SummarizationSetBy = Automatic

	partition KGI_III_Encuestas_new-4c9b194a-b84e-4bcc-8347-750a866f4407 = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source = ```
				let
				    Origen = KGI_III_Encuestas_new2,
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Cerrado", type date}, {"Actualizado", type date}}),
				    #"Inicio del mes insertado" = Table.AddColumn(#"Tipo cambiado", "Creación encuesta mes", each Date.StartOfMonth([Cerrado]), type date),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Inicio del mes insertado",{{"Creación encuesta mes", type date}, {"Valor real", Int64.Type}, {"Cerrado", type date}, {"Actualizado", type datetime}}),
				    #"Valor reemplazado" = Table.ReplaceValue(
				#"Tipo cambiado1", 
				each [Pregunta],
				each if [Pregunta] = "Aptitude" then "P3 - Aptitud" 
				else if [Pregunta] = "Attitude" then "P4 - Actitud"
				else if [Pregunta] = "Follow-up" then "P5 - Seguimiento"
				else if [Pregunta] = "Overall Rating" then "P1 - Valoración General"
				else if [Pregunta] = "Response time" then "P2 - Tiempo de respuesta"
				else [Pregunta],
				Replacer.ReplaceValue,{"Pregunta"}
				),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Valor reemplazado",{"Valor real", "Elemento métrico"}),
				    #"Columna dinamizada" = Table.Pivot(#"Columnas quitadas", List.Distinct(#"Columnas quitadas"[Pregunta]), "Pregunta", "Valor de cadena"),
				    #"Consulta anexada" = Table.Combine({#"Columna dinamizada", #"Peticiones (2)"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Consulta anexada",null,"5",Replacer.ReplaceValue,{"P5 - Seguimiento"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1",null,"5",Replacer.ReplaceValue,{"P1 - Valoración General"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2",null,"5",Replacer.ReplaceValue,{"P2 - Tiempo de respuesta"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3",null,"4",Replacer.ReplaceValue,{"P3 - Aptitud"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4",null,"4",Replacer.ReplaceValue,{"P4 - Actitud"})
				in
				    #"Valor reemplazado5"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

