table KGI_12_Jira
	lineageTag: dd3adc13-533d-4a71-ad5f-df5fb6526a8c

	column 'Epic Link'
		dataType: string
		lineageTag: e698296e-b7e0-474e-85c3-d801e5757281
		summarizeBy: none
		sourceColumn: Epic Link

		annotation SummarizationSetBy = Automatic

	column 'Task Number'
		dataType: string
		lineageTag: 5cd4d73f-01c8-4cf0-bf86-8ae8b04a8b42
		summarizeBy: none
		sourceColumn: Task Number

		annotation SummarizationSetBy = Automatic

	column Entregables
		dataType: string
		lineageTag: 773b679b-6df4-4621-b92a-4d3dda601d9c
		summarizeBy: none
		sourceColumn: Entregables

		annotation SummarizationSetBy = Automatic

	column 'Nombre del entregable'
		dataType: string
		lineageTag: d9aef98f-275d-4722-909c-6cfe56185024
		summarizeBy: none
		sourceColumn: Nombre del entregable

		annotation SummarizationSetBy = Automatic

	column Rechazos
		dataType: string
		lineageTag: 0ad40ab3-bad3-4466-ad6f-90cfda9b189c
		summarizeBy: none
		sourceColumn: Rechazos

		annotation SummarizationSetBy = Automatic

	column 'Begin Date'
		dataType: string
		lineageTag: 51c0d82e-1d18-4b84-8dc4-6f44f1c0f890
		summarizeBy: none
		sourceColumn: Begin Date

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: 7ad4026e-a908-4df7-b6c2-39942cf7e6e0
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 22881080-5079-4292-adc9-e8ffe66d8b4f
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 9dd76ceb-3e0b-4fd4-8072-1f71d02ab1e5
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: e4427ea8-29f5-4dd2-b032-3fa8ccc93f72
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: fee3bd6c-5a5c-4d28-9345-ee81b7aa6c7a
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 50eada42-74cd-47a6-8259-57cea74260c7
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 6ee7d73c-06a4-486c-8479-a43da47172bd
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: string
		lineageTag: b5ae3744-ad77-469b-ac3b-c3db75231f25
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column 'Σ Original Estimate'
		dataType: string
		lineageTag: c6094b97-ddd7-405d-bb5b-48f4b4f943e7
		summarizeBy: none
		sourceColumn: Σ Original Estimate

		annotation SummarizationSetBy = Automatic

	column 'Σ Remaining Estimate'
		dataType: string
		lineageTag: f64e6b48-170e-41d4-a339-6b45203635e7
		summarizeBy: none
		sourceColumn: Σ Remaining Estimate

		annotation SummarizationSetBy = Automatic

	column 'Σ Time Spent'
		dataType: string
		lineageTag: 0345b0b4-be8a-458e-beb8-358f9f440de2
		summarizeBy: none
		sourceColumn: Σ Time Spent

		annotation SummarizationSetBy = Automatic

	column Components
		dataType: string
		lineageTag: 3ae8ae57-f4fe-4eb0-8b63-e3679aa68cbb
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column 'Start date'
		dataType: string
		lineageTag: 557538a1-dc99-439d-a628-41fa912d58e4
		summarizeBy: none
		sourceColumn: Start date

		annotation SummarizationSetBy = Automatic

	column 'Fecha PRE'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5edad185-0ad8-4d02-8bad-94c9ed27628a
		summarizeBy: none
		sourceColumn: Fecha PRE

		variation Variación
			isDefault
			relationship: 18bb03a0-4dcd-4e8a-b59e-6ec03ebc0215
			defaultHierarchy: LocalDateTable_c4efafac-94dd-4f03-9395-263fb912fcf2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Deliverable type'
		dataType: string
		lineageTag: d7553df1-b55a-40db-93e7-dd87d752145f
		summarizeBy: none
		sourceColumn: Deliverable type

		annotation SummarizationSetBy = Automatic

	column 'Due date'
		dataType: string
		lineageTag: 19f784b4-44eb-4057-8235-061bd7ec1106
		summarizeBy: none
		sourceColumn: Due date

		annotation SummarizationSetBy = Automatic

	partition KGI_12_Jira-5ec838cd-a781-482a-b032-d7c793774f84 = m
		mode: import
		queryGroup: 'Tablas No Modelo'
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(sharepointSource & Entorno & sharepointSource2 & "Jira_FechaPRE" & xlsx), null, true),
				    #"Your Jira Issues_Sheet" = Origen{[Item="Your Jira Issues",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Your Jira Issues_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Resolved", type datetime}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"Resolved", "Fecha PRE"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

