table KGI_I_Entregables_Jira
	lineageTag: 0f10d30e-5adf-4567-90ec-deb95427c9db

	column 'Issue Type'
		dataType: string
		lineageTag: 006c7f4a-fba2-4918-a35a-d9bbac355b06
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column 'Deliverable type'
		dataType: string
		lineageTag: f5ba535e-c615-472b-8c60-6c7bc067e780
		summarizeBy: none
		sourceColumn: Deliverable type

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 2d7dacaf-b68b-45f9-865e-46a37b2414b9
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 366c0967-bd1f-414e-a3ee-35f7d1c03e6a
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Components
		dataType: string
		lineageTag: f50c44e9-10a4-4d4a-b321-de4c98b549e6
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 7814f982-ae9d-4f60-9c87-be02f233aadc
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 3a870d00-19b0-4a25-84df-e89c484d720b
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: cc4d359f-8d50-49ff-bc2d-5fdb4a94761a
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 71e1b97e-eb25-4a41-930c-1b5d0f6857ef
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 0e23d799-4d35-4790-b429-168cb170c625
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Approval status'
		dataType: string
		lineageTag: af26395a-2e0c-4a1d-b02b-9df2b5917c3a
		summarizeBy: none
		sourceColumn: Approval status

		annotation SummarizationSetBy = Automatic

	column 'End Date'
		dataType: string
		lineageTag: 7e10820a-3027-45c9-9463-13bb5140b9ee
		summarizeBy: none
		sourceColumn: End Date

		annotation SummarizationSetBy = Automatic

	column 'End Real Date'
		dataType: string
		lineageTag: df58ab38-8042-493c-bafd-2c8fb00bf6cd
		summarizeBy: none
		sourceColumn: End Real Date

		annotation SummarizationSetBy = Automatic

	column 'Linked Issues'
		dataType: string
		lineageTag: f8b8eb1d-7437-4ab1-8ce7-3a99507b107b
		summarizeBy: none
		sourceColumn: Linked Issues

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 1a5da967-562e-4bf3-ac5f-2f8d3d413298
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: 8042bed4-4ec6-4f40-b09e-f53eeaf9edc7
		summarizeBy: none
		sourceColumn: Resolved

		variation Variación
			isDefault
			relationship: d72c495c-a5f6-4b9c-8f7c-74f0c5d8e902
			defaultHierarchy: LocalDateTable_2b708030-c1f8-4fbf-838f-b8ec3687c098.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Rechazos
		dataType: int64
		formatString: 0
		lineageTag: b958dac8-3373-42c4-b2dc-ff2d742b733a
		summarizeBy: sum
		sourceColumn: Rechazos

		annotation SummarizationSetBy = Automatic

	column 'Resolved mes'
		dataType: dateTime
		formatString: General Date
		lineageTag: 570238f5-d6a8-4482-8bfa-8e7978c4f150
		summarizeBy: none
		sourceColumn: Resolved mes

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: b1672aa8-69e8-478d-a3a1-526248ecddbb
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Project_starts_with
		dataType: string
		lineageTag: a00ab4ee-b214-4c16-8f9b-6270dd9f7c34
		summarizeBy: none
		sourceColumn: Project_starts_with

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_1.4'
		dataType: string
		lineageTag: 9fee28ab-3af6-4938-af63-a04ef7637dbb
		summarizeBy: none
		sourceColumn: ID_KGI_1.4

		annotation SummarizationSetBy = Automatic

	column Proyecto_Evolutivo
		dataType: string
		lineageTag: cbbf17ef-3196-4342-9ae2-469e188831ae
		summarizeBy: none
		sourceColumn: Proyecto_Evolutivo

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.ID Alegación'
		dataType: string
		lineageTag: a97385dd-5736-4d47-b1ed-5625cddeb0fa
		summarizeBy: none
		sourceColumn: T_Alegaciones.ID Alegación

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.Solicitante'
		dataType: string
		lineageTag: c97053fe-d924-4648-bd5b-45f57c1bb2d9
		summarizeBy: none
		sourceColumn: T_Alegaciones.Solicitante

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.ANS'
		dataType: string
		lineageTag: 7355cba0-9f6e-4711-8122-671932a00925
		summarizeBy: none
		sourceColumn: T_Alegaciones.ANS

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.Estado'
		dataType: string
		lineageTag: b68abeca-5268-4f47-aef3-398c8ea6097e
		summarizeBy: none
		sourceColumn: T_Alegaciones.Estado

		annotation SummarizationSetBy = Automatic

	column Rechazado
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 849cea5f-f4fa-40f9-9371-a0e76b23cfc9
		summarizeBy: none
		sourceColumn: Rechazado

		annotation SummarizationSetBy = Automatic

	partition KGI_I_Entregables_Jira-4db93c74-46c7-4004-ac63-4291adfb6af8 = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source = ```
				let
				    Origen = #"KGI_I_Entregables_Jira (stagging)",
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}}),
				    #"Encabezados promovidos1" = Table.PromoteHeaders(#"Tipo cambiado", [PromoteAllScalars=true]),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Encabezados promovidos1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Filas en blanco eliminadas",{{"Issue Type", type text}, {"Deliverable type", type text}, {"Project", type text}, {"Key", type text}, {"Components", type text}, {"Summary", type text}, {"Priority", type text}, {"Assignee", type text}, {"Reporter", type text}, {"Status", type text}, {"Approval status", type text}, {"End Date", type text}, {"End Real Date", type text}, {"Linked Issues", type text}, {"Sub-tasks", type text}, {"Resolved", type datetime}, {"Rechazos", Int64.Type}}),
				
				    #"AllReplace" = [#"Highest" = "Grave", #"High" = "Grave", #"Medium" = "Grave",#"Low" = "Leve",#"Lowest" = "Leve", #"null" = null],
				    #"Replaced Value" = Table.TransformColumns(#"Tipo cambiado1",{{"Priority",each Record.FieldOrDefault(AllReplace,_,_)}}),
				    #"Errores reemplazados" = Table.ReplaceErrorValues(#"Replaced Value", {{"Priority", null}}),
				
				    #"Inicio mes Resolved" = Table.AddColumn(#"Errores reemplazados", "Resolved mes", each Date.StartOfMonth([Resolved]), type datetime),
				    #"Personalizada agregada" = Table.AddColumn(#"Inicio mes Resolved", "Tipo de Proyecto", each null),
				    #"Primeros caracteres insertados" = Table.AddColumn(#"Personalizada agregada", "Project_starts_with", each Text.Start([Project], 4), type text),
				    #"Columna condicional agregada" = Table.AddColumn(#"Primeros caracteres insertados", "ID_KGI_1.4", 
				                                                    each if [Project_starts_with] <> "Mtto"  and [Priority] = "Grave" then "1-4-1-1" 
				                                                    else if [Project_starts_with] <> "Mtto"  and [Priority] = "Leve" then "1-4-1-2"
				                                                    else if [Project_starts_with] = "Mtto" and [Priority] = "Grave" then "1-4-2-1"
				                                                    else if [Project_starts_with] = "Mtto" and [Priority] = "Leve" then "1-4-2-2"
				                                                    else null
				),
				    #"Columna condicional agregada1" = Table.AddColumn(#"Columna condicional agregada", "Proyecto_Evolutivo", each if Text.StartsWith([Project], "Mtto") then "Evolutivos" else if [Project] = null then null else "Proyectos"),
				    #"Errores reemplazados1" = Table.ReplaceErrorValues(#"Columna condicional agregada1", {{"Proyecto_Evolutivo", null}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Errores reemplazados1", {"Key"}, T_Alegaciones, {"ID"}, "T_Alegaciones", JoinKind.LeftOuter),
				    #"Se expandió T_Alegaciones" = Table.ExpandTableColumn(#"Consultas combinadas", "T_Alegaciones", {"ID Alegación", "Solicitante", "ANS", "Estado"}, {"T_Alegaciones.ID Alegación", "T_Alegaciones.Solicitante", "T_Alegaciones.ANS", "T_Alegaciones.Estado"}),
				    #"Columna condicional agregada2" = Table.AddColumn(#"Se expandió T_Alegaciones", "Rechazado", each if [Rechazos] = 0 then false else if [Rechazos] = null then false else true, Logical.Type)
				in
				    #"Columna condicional agregada2"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

