table 'LB € y volumétrica'
	lineageTag: 76299805-dcc3-48c4-9183-0313a692c71e

	measure 'LB Comprometida € Medida' = SELECTEDVALUE('LB € y volumétrica'[LB Comprometida €])
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 85940b7c-5028-4c0b-a4a7-82c68595ec8b

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	measure 'LB Comprometida Volumen Medida' = SELECTEDVALUE('LB € y volumétrica'[LB Comprometida Volumen])
		lineageTag: 4668001c-dd43-467d-a94c-fe914bd96171

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Servicio TIC'
		dataType: string
		lineageTag: a4b39c11-279c-4ad6-b113-c81ea9b5fee3
		summarizeBy: none
		sourceColumn: Servicio TIC

		annotation SummarizationSetBy = Automatic

	column 'Ámbito del Servicio'
		dataType: string
		lineageTag: 4278a9b7-83c7-44d3-a474-533d85b90dd8
		summarizeBy: none
		sourceColumn: Ámbito del Servicio

		annotation SummarizationSetBy = Automatic

	column 'Descripción Ámbito Servicio'
		dataType: string
		lineageTag: e688eb5f-07c5-4ca1-b98f-83d5fc520453
		summarizeBy: none
		sourceColumn: Descripción Ámbito Servicio
		sortByColumn: 'Ámbito del Servicio'

		annotation SummarizationSetBy = Automatic

	column 'LB Esperada €'
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 55d849fe-a833-428d-aed3-ceff12735911
		summarizeBy: sum
		sourceColumn: LB Esperada €

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column 'LB Objetivo 0 €'
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 6c09ccd8-616b-47fe-a75c-ebe6ef31e8da
		summarizeBy: sum
		sourceColumn: LB Objetivo 0 €

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column 'LB Objetivo 1 €'
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: b8b5c717-54d4-4e6d-8ab9-6a1f23b2cac3
		summarizeBy: sum
		sourceColumn: LB Objetivo 1 €

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column 'LB Objetivo 2 €'
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 236e5f13-4b06-4d61-b314-8da4cd35866c
		summarizeBy: sum
		sourceColumn: LB Objetivo 2 €

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column 'LB Objetivo Máximo €'
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 39e253e9-3f52-49d4-b076-4ba8c9459c18
		summarizeBy: sum
		sourceColumn: LB Objetivo Máximo €

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column 'LB Real €'
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 7683990e-ddb7-460b-851b-ea4847ffeef8
		summarizeBy: sum
		sourceColumn: LB Real €

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column 'LB Esperada Volumen'
		dataType: int64
		formatString: 0
		lineageTag: 1750d996-257e-4a6f-a38b-596a1984a4e1
		summarizeBy: sum
		sourceColumn: LB Esperada Volumen

		annotation SummarizationSetBy = Automatic

	column 'LB Objetivo 0 Volumen'
		dataType: int64
		formatString: 0
		lineageTag: 66ce0037-2511-4dd3-8b88-751c459476ed
		summarizeBy: sum
		sourceColumn: LB Objetivo 0 Volumen

		annotation SummarizationSetBy = Automatic

	column 'LB Objetivo 1 Volumen'
		dataType: int64
		formatString: 0
		lineageTag: c4682e4c-e107-4b0d-a578-4462a942c134
		summarizeBy: sum
		sourceColumn: LB Objetivo 1 Volumen

		annotation SummarizationSetBy = Automatic

	column 'LB Objetivo 2 Volumen'
		dataType: int64
		formatString: 0
		lineageTag: 9c223758-2dd1-4f37-9214-0f70cef8db30
		summarizeBy: sum
		sourceColumn: LB Objetivo 2 Volumen

		annotation SummarizationSetBy = Automatic

	column 'LB Objetivo Máximo Volumen'
		dataType: int64
		formatString: 0
		lineageTag: 7745aff9-b6fa-4676-914f-a4b4b86f0431
		summarizeBy: sum
		sourceColumn: LB Objetivo Máximo Volumen

		annotation SummarizationSetBy = Automatic

	column 'LB Real Volumen'
		dataType: int64
		formatString: 0
		lineageTag: 9ed7be1c-5de7-4cca-bff7-ed66b4f72a71
		summarizeBy: sum
		sourceColumn: LB Real Volumen

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Período
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4838af8-6b21-403b-b615-6de05bd81fdc
		summarizeBy: none
		sourceColumn: Período

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'LB Proyectado/Reservado €'
		dataType: decimal
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: 536233fe-2d6e-43e8-97e4-6baac36ec4f3
		summarizeBy: sum
		sourceColumn: LB Proyectado/Reservado €

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column 'LB Proyectado/Reservado Volumen'
		dataType: int64
		formatString: #,0
		lineageTag: 4314007b-ea4c-40e9-b22e-fb43d49197e7
		summarizeBy: sum
		sourceColumn: LB Proyectado/Reservado Volumen

		annotation SummarizationSetBy = Automatic

	column 'LB Comprometida Volumen'
		dataType: double
		lineageTag: caf06fba-8772-4ef0-b411-ac632d560733
		summarizeBy: sum
		sourceColumn: LB Comprometida Volumen

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'LB Comprometida €'
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 83b14881-f257-45a5-acd4-279b2f32951d
		summarizeBy: sum
		sourceColumn: LB Comprometida €

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column 'Línea Base Comprometida'
		dataType: string
		lineageTag: dcf96424-9c22-44d6-8072-b7dff080f2d3
		summarizeBy: none
		sourceColumn: Línea Base Comprometida

		annotation SummarizationSetBy = Automatic

	column 'Línea Base Comprometida_1'
		dataType: string
		lineageTag: ec98969e-e799-4e44-b639-911956508724
		summarizeBy: none
		sourceColumn: Línea Base Comprometida_1

		annotation SummarizationSetBy = Automatic

	column 'LB Extra 1 €'
		dataType: string
		lineageTag: b1af5312-5f94-4f50-a849-59957406ebfe
		summarizeBy: none
		sourceColumn: LB Extra 1 €

		annotation SummarizationSetBy = Automatic

	column 'LB Extra 2 €'
		dataType: string
		lineageTag: 3b252050-bd97-435a-b332-5eca13cf6f47
		summarizeBy: none
		sourceColumn: LB Extra 2 €

		annotation SummarizationSetBy = Automatic

	column 'LB Extra 3 €'
		dataType: string
		lineageTag: ac5be684-6c89-418e-a035-7cfd1aaa58fb
		summarizeBy: none
		sourceColumn: LB Extra 3 €

		annotation SummarizationSetBy = Automatic

	column 'LB Extra 4 €'
		dataType: string
		lineageTag: 91acfefd-c559-414a-aeb5-7c58349ba2dd
		summarizeBy: none
		sourceColumn: LB Extra 4 €

		annotation SummarizationSetBy = Automatic

	column 'LB Extra 5 €'
		dataType: string
		lineageTag: 98cea83f-901b-4ec6-8b79-f6e868e36a72
		summarizeBy: none
		sourceColumn: LB Extra 5 €

		annotation SummarizationSetBy = Automatic

	column 'LB Extra Tope €'
		dataType: string
		lineageTag: 9020b411-2844-4aca-bea5-93cca5bdbff0
		summarizeBy: none
		sourceColumn: LB Extra Tope €

		annotation SummarizationSetBy = Automatic

	column 'LB Teorica €'
		dataType: string
		lineageTag: 1c1eddd9-179d-49cc-bd57-1ef33d13fcc0
		summarizeBy: none
		sourceColumn: LB Teorica €

		annotation SummarizationSetBy = Automatic

	column 'LB Extra 1 '
		dataType: string
		lineageTag: 1f68e5e1-b0fc-4e9c-938c-cb7e4827fe49
		summarizeBy: none
		sourceColumn: "LB Extra 1 "

		annotation SummarizationSetBy = Automatic

	column 'LB Extra 2'
		dataType: string
		lineageTag: 68f2d89a-1215-4621-b00f-3877fbab28c1
		summarizeBy: none
		sourceColumn: LB Extra 2

		annotation SummarizationSetBy = Automatic

	column 'LB Extra 3'
		dataType: string
		lineageTag: d7513a3f-b17f-44d2-8a41-6603f527e2f9
		summarizeBy: none
		sourceColumn: LB Extra 3

		annotation SummarizationSetBy = Automatic

	column 'LB Extra 4'
		dataType: string
		lineageTag: 2d7ff283-a008-49e9-8dea-3a2c69effa4f
		summarizeBy: none
		sourceColumn: LB Extra 4

		annotation SummarizationSetBy = Automatic

	column 'LB Extra 5'
		dataType: string
		lineageTag: ca393be3-ca99-4c94-9780-1a6b5e4c3a50
		summarizeBy: none
		sourceColumn: LB Extra 5

		annotation SummarizationSetBy = Automatic

	column 'LB Extra Tope'
		dataType: string
		lineageTag: 9b2e51a2-368d-45ff-8041-1f861b26316f
		summarizeBy: none
		sourceColumn: LB Extra Tope

		annotation SummarizationSetBy = Automatic

	column Column36
		dataType: string
		lineageTag: 77df6196-cdb4-43dc-8473-95077fcc6b9a
		summarizeBy: none
		sourceColumn: Column36

		annotation SummarizationSetBy = Automatic

	column Column37
		dataType: string
		lineageTag: 915c082e-bb3b-4225-8f6e-b7ecb6be4b8f
		summarizeBy: none
		sourceColumn: Column37

		annotation SummarizationSetBy = Automatic

	column Column38
		dataType: string
		lineageTag: 0c6eed6a-19ed-4b74-9b67-30a810e7b78a
		summarizeBy: none
		sourceColumn: Column38

		annotation SummarizationSetBy = Automatic

	column Column39
		dataType: string
		lineageTag: c9d07f13-79bc-4a53-9da6-1e0b9ee43523
		summarizeBy: none
		sourceColumn: Column39

		annotation SummarizationSetBy = Automatic

	column Column40
		dataType: string
		lineageTag: d7b57a64-608b-47bb-94bf-bd4f4e34cb76
		summarizeBy: none
		sourceColumn: Column40

		annotation SummarizationSetBy = Automatic

	column Column41
		dataType: string
		lineageTag: de79c263-0979-4867-af6b-889a5c955759
		summarizeBy: none
		sourceColumn: Column41

		annotation SummarizationSetBy = Automatic

	partition 'LB € y volumétrica-7d047a29-fbb9-4517-8af5-9def0f548c86' = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(sharepointSource & Entorno & lineaBase), null, true)
				
				//= Excel.Workbook(File.Contents("C:\Users\carlolopez\ACCIONA S.A\Oficina de Gestión de Servicios SMO - Acciona SMO Workspace - Documents\Acciona SMO Workspace\1. Otras Iniciativas\CDM Integral TIC\Maestro CDM Integral TIC v0.1 20210804.xlsx"), null, true)
				,
				    #"LB € y volumétrica_Sheet" = Origen{[Item="LB € y volumétrica",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"LB € y volumétrica_Sheet", [PromoteAllScalars=true]),
				    #"Filas filtradas" = Table.SelectRows(#"Encabezados promovidos", each ([Servicio TIC] = "OFINCIA_INTEGRACION")),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Filas filtradas",{{"Servicio TIC", type text}, {"LB Esperada €", Currency.Type}, {"LB Objetivo 0 €", Currency.Type}, {"LB Objetivo 1 €", Currency.Type}, {"LB Objetivo 2 €", Currency.Type}, {"LB Objetivo Máximo €", Currency.Type}, {"LB Real €", Currency.Type}, {"LB Proyectado/Reservado €", Currency.Type}, {"LB Esperada Volumen", Int64.Type}, {"LB Objetivo 0 Volumen", Int64.Type}, {"LB Objetivo 1 Volumen", Int64.Type}, {"LB Objetivo 2 Volumen", Int64.Type}, {"LB Objetivo Máximo Volumen", Int64.Type}, {"LB Real Volumen", Int64.Type}, {"LB Proyectado/Reservado Volumen", Int64.Type}, {"Período", type date}, {"LB Comprometida Volumen", type number}, {"LB Comprometida €", Currency.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

