table RM_Total
	lineageTag: bb0a0b52-cc14-48af-9aa1-5b9a3c040c46

	column Código
		dataType: string
		lineageTag: d78511a0-e215-463b-9bc2-a6f17356a90a
		summarizeBy: none
		sourceColumn: Código

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 177f7f33-874e-4521-b151-c690860a1007
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Nombre proyecto'
		dataType: string
		lineageTag: 41279421-3288-45b1-87a1-a2f437be3dce
		summarizeBy: none
		sourceColumn: Nombre proyecto

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: d50a10aa-28d5-4343-ba45-606032740d85
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 4bf1eb83-444e-49f7-b8fe-5b36891bafb5
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column 'Project Type'
		dataType: string
		lineageTag: 9ec42585-2577-477c-b73c-69f1ea8130af
		summarizeBy: none
		sourceColumn: Project Type

		annotation SummarizationSetBy = Automatic

	column 'Abierto por'
		dataType: string
		lineageTag: 8395160d-c5bb-4a63-a62c-6807666124bc
		summarizeBy: none
		sourceColumn: Abierto por

		annotation SummarizationSetBy = Automatic

	column 'Tipo fecha'
		dataType: string
		lineageTag: bfb07710-71a4-41b4-92e9-89cca4d81196
		summarizeBy: none
		sourceColumn: Tipo fecha

		annotation SummarizationSetBy = Automatic

	column 'Año Inicio Real'
		dataType: string
		lineageTag: 9b28c703-2648-415d-bd0f-41979529713d
		summarizeBy: none
		sourceColumn: Año Inicio Real

		annotation SummarizationSetBy = Automatic

	column 'Año Fin Real'
		dataType: string
		lineageTag: a6aa0ab3-6750-4941-9fa4-2f5feec12a95
		summarizeBy: none
		sourceColumn: Año Fin Real

		annotation SummarizationSetBy = Automatic

	column 'Año Inicio Planned'
		dataType: string
		lineageTag: c9c49080-46a8-4181-8753-534de01259ff
		summarizeBy: none
		sourceColumn: Año Inicio Planned

		annotation SummarizationSetBy = Automatic

	column 'Año Fin Planned'
		dataType: string
		lineageTag: f1340f69-a614-46d4-849b-9628f435bb1c
		summarizeBy: none
		sourceColumn: Año Fin Planned

		annotation SummarizationSetBy = Automatic

	column MesAño_IR
		dataType: string
		lineageTag: d6058129-63a5-4351-a540-8028e50b38fb
		summarizeBy: none
		sourceColumn: MesAño_IR
		sortByColumn: Date_1er_día_mes_IR

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MesAño_FR
		dataType: string
		lineageTag: 3945608f-a74e-438a-bd81-19d55206bfef
		summarizeBy: none
		sourceColumn: MesAño_FR

		annotation SummarizationSetBy = Automatic

	column MesAño_IP
		dataType: string
		lineageTag: 5a985c1d-9ddc-458f-aa0c-dc3d267ec12c
		summarizeBy: none
		sourceColumn: MesAño_IP
		sortByColumn: Date_1er_día_mes_IP

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MesAño_FP
		dataType: string
		lineageTag: c02118f0-9f38-4809-a9df-146a196f8228
		summarizeBy: none
		sourceColumn: MesAño_FP
		sortByColumn: Date_1er_día_mes_FP

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Date_1er_día_mes_IR
		dataType: dateTime
		formatString: Long Date
		lineageTag: a1aae88d-a457-4331-9acc-1d4ec1682f3e
		summarizeBy: none
		sourceColumn: Date_1er_día_mes_IR

		variation Variación
			isDefault
			relationship: 71183faf-0a86-44f4-8dfa-1078264568d2
			defaultHierarchy: LocalDateTable_389e7283-a404-43d7-b1ef-debf2b5e3d31.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date_1er_día_mes_FR
		dataType: dateTime
		formatString: Long Date
		lineageTag: 08df39e8-d075-49b3-b2e1-b0946d4a1870
		summarizeBy: none
		sourceColumn: Date_1er_día_mes_FR

		variation Variación
			isDefault
			relationship: 7e690d5b-2522-48fd-b6f7-eff8581596c9
			defaultHierarchy: LocalDateTable_389dbb90-9ec4-4c69-8260-af0f803c6344.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date_1er_día_mes_IP
		dataType: dateTime
		formatString: Long Date
		lineageTag: 46822038-c4d4-42c9-8f3e-f7ae726c33b7
		summarizeBy: none
		sourceColumn: Date_1er_día_mes_IP

		variation Variación
			isDefault
			relationship: e33ebc67-4a3d-4912-8a6f-0ad4b3f13380
			defaultHierarchy: LocalDateTable_1ae0004f-63fe-428b-b405-93047c7991c0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date_1er_día_mes_FP
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4c6fc267-2f3c-4479-a68f-43008eecd8f1
		summarizeBy: none
		sourceColumn: Date_1er_día_mes_FP

		variation Variación
			isDefault
			relationship: 302c973a-5630-44d3-9cbb-d01473e619c3
			defaultHierarchy: LocalDateTable_69ccbe6e-90a3-4975-abb0-a60dd13b34f1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Fecha_fin_planif = if(ISBLANK(RM_Total[Fecha fin planificada]) = TRUE, "N/A", CONVERT(RM_Total[Fecha fin planificada], STRING))
		lineageTag: e70a5767-5f35-4aeb-875e-3bff8f054cb5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio'
		dataType: string
		lineageTag: a461caa7-5182-486a-adff-3cae4312ec8a
		summarizeBy: none
		sourceColumn: Aplicación de Negocio

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: b4154f17-8b3d-40ce-a5fb-b950bcccad91
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Gestor de Demanda'
		dataType: string
		lineageTag: 41869da0-842d-4a74-9fe8-5b40bc31b263
		summarizeBy: none
		sourceColumn: Gestor de Demanda

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 693618a1-93eb-4c2b-a88a-669e0315af83
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Asignado a'
		dataType: string
		lineageTag: a41fbacb-f5d6-4287-80a3-97251574f04b
		summarizeBy: none
		sourceColumn: Asignado a

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 13b2d028-b823-44c0-b45f-75870ac4b93c
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5b791eaf-04bc-4cdb-9aeb-b287a0e399a8
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variación
			isDefault
			relationship: 8836a9cd-1cbe-4c73-a193-add54284c1b1
			defaultHierarchy: LocalDateTable_f435a63f-591a-4d80-a711-5567d2d8e4b3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: Short Date
		lineageTag: ef4110bb-2d69-4ed6-9e77-5900ab3ae354
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variación
			isDefault
			relationship: 18e00b47-1445-4638-84ef-d584e1bb2b60
			defaultHierarchy: LocalDateTable_48e43b31-4792-4c0d-aea5-a18c40f00384.'Jerarquía de fechas'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fecha fin real'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a35c7cba-f9c5-4938-81ef-6d0bfa284b67
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variación
			isDefault
			relationship: 21adf5d8-3aa2-420a-bcdc-9b1ffb23e5b5
			defaultHierarchy: LocalDateTable_ada63298-5001-44ff-b05a-35d3b46cc5f6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: Short Date
		lineageTag: b9ef25c9-326c-43b0-b9ef-0e7bca798e27
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variación
			isDefault
			relationship: b7bf304a-8a9a-44ea-88bf-3a54308ecd4c
			defaultHierarchy: LocalDateTable_4d88e3b4-608d-42bb-bb90-f3530e721f98.'Jerarquía de fechas'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Demanda
		dataType: string
		lineageTag: a3750af7-743a-4925-b36b-4b2c85527152
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Demand
		dataType: string
		lineageTag: a3b9ad92-b27f-471a-9342-2a889b04192f
		summarizeBy: none
		sourceColumn: Demand

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción_1'
		dataType: string
		lineageTag: d98d1635-b4dc-41a8-b42f-7fae20e2742b
		summarizeBy: none
		sourceColumn: Breve descripción_1

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 575065d4-e374-420f-8733-05fb7de2b375
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto'
		dataType: string
		lineageTag: 7a0cea29-17b9-44bb-8f7d-db77de5d4c2d
		summarizeBy: none
		sourceColumn: Jefe de proyecto

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: e35722cf-68f7-4fce-97b1-af0972e16b61
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Nombre de proyecto'
		dataType: string
		lineageTag: 286f6539-e8d0-4a8c-8cf0-50447554ce03
		summarizeBy: none
		sourceColumn: Nombre de proyecto

		annotation SummarizationSetBy = Automatic

	column Descripción
		dataType: string
		lineageTag: b4575db6-3fe7-4cb6-b23e-fe5cfd870925
		summarizeBy: none
		sourceColumn: Descripción

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: be936ec2-e0eb-40bb-9a70-2ebf1a82e09d
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column Fase
		dataType: string
		lineageTag: 063e9267-0c34-40fa-998a-320e4d714681
		summarizeBy: none
		sourceColumn: Fase

		annotation SummarizationSetBy = Automatic

	column 'Estado de la Fase (State)'
		dataType: string
		lineageTag: 3dcd2729-df34-481f-9364-16bff7d2c015
		summarizeBy: none
		sourceColumn: Estado de la Fase (State)

		annotation SummarizationSetBy = Automatic

	column Creado
		dataType: double
		lineageTag: 2bac5840-41ff-43fe-87ba-115375b05928
		summarizeBy: sum
		sourceColumn: Creado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Comentarios y notas de trabajo'
		dataType: string
		lineageTag: 7c2f9802-58af-4c19-96cc-c5dd4d040bba
		summarizeBy: none
		sourceColumn: Comentarios y notas de trabajo

		annotation SummarizationSetBy = Automatic

	partition RM_Total-b28718c5-0cf6-4f2b-bba0-8fe88f4b582a = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source = ```
				let
				    Origen = #"RM_Total (stagging)",
				    #"Valor reemplazado" = Table.ReplaceValue(Origen,null,DateTime.LocalNow(),Replacer.ReplaceValue,{"Fecha fin real"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Valor reemplazado", "Año Inicio Real", each Date.Year([Fecha de inicio real])),
				    #"Personalizada agregada1" = Table.AddColumn(#"Personalizada agregada", "Año Fin Real", each Date.Year([Fecha fin real])),
				    Personalizado1 = Table.AddColumn(#"Personalizada agregada1", "Año Inicio Planned", each Date.Year([Fecha de inicio planificada])),
				    Personalizado2 = Table.AddColumn(#"Personalizado1", "Año Fin Planned", each Date.Year([Fecha de inicio planificada])),
				    #"Traducción prioridad" = Table.ReplaceValue(
				Personalizado2, 
				each [Prioridad],
				each if [Prioridad] = "5 - Muy Baja" then "Baja" 
				else if [Prioridad] = "4 - Baja" then "Baja"
				else if [Prioridad] = "3 - Moderada" then "Moderada"
				else if [Prioridad] = "2 - Alta" then "Alta"
				else if [Prioridad] = "1 - Crítica" then "Crítica"
				else [Prioridad],
				Replacer.ReplaceValue,{"Prioridad"}
				),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Traducción prioridad",{{"Fecha de inicio planificada", type date}, {"Fecha fin planificada", type date}, {"Fecha de inicio real", type date}, {"Fecha fin real", type date}}),
				    MesAño_IR = Table.AddColumn(#"Tipo cambiado", "MesAño_IR", each Text.AfterDelimiter(Text.From([Fecha de inicio real], "es-ES"), "/"), type text),
				    MesAño_FR = Table.AddColumn(MesAño_IR, "MesAño_FR", each Text.AfterDelimiter(Text.From([Fecha fin real], "es-ES"), "/"), type text),
				    MesAño_IP = Table.AddColumn(MesAño_FR, "MesAño_IP", each Text.AfterDelimiter(Text.From([Fecha de inicio planificada], "es-ES"), "/"), type text),
				    MesAño_FP = Table.AddColumn(MesAño_IP, "MesAño_FP", each Text.AfterDelimiter(Text.From([Fecha fin planificada], "es-ES"), "/"), type text),
				    Personalizado3 = Table.AddColumn(#"MesAño_FP", "Date_1er_día_mes_IR", each Date.StartOfMonth([Fecha de inicio real]), type date),
				    Personalizado4 = Table.AddColumn(#"Personalizado3", "Date_1er_día_mes_FR", each Date.StartOfMonth([Fecha fin real]), type date),
				    Personalizado5 = Table.AddColumn(#"Personalizado4", "Date_1er_día_mes_IP", each Date.StartOfMonth([Fecha de inicio planificada]), type date),
				    Personalizado6 = Table.AddColumn(#"Personalizado5", "Date_1er_día_mes_FP", each Date.StartOfMonth([Fecha fin planificada]), type date)
				in
				    Personalizado6
				```

	annotation PBI_ResultType = Table

