table RM_Total_Gantt
	lineageTag: 6359fdcc-8159-499f-83c1-2ad300913530

	column Código
		dataType: string
		lineageTag: 3c5d9dd0-569c-42a6-bf79-c62200583e02
		summarizeBy: none
		sourceColumn: Código

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 4f271f75-516d-4ba1-8dbe-f8095a4c2dc8
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Nombre proyecto'
		dataType: string
		lineageTag: 49bf6c7d-7587-47b6-a089-da5027812a6a
		summarizeBy: none
		sourceColumn: Nombre proyecto

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 3b3947b7-8fbc-41e6-afb8-47a62c20ac1e
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 1617e7a3-86d2-4903-ae03-96b773e2babd
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column 'Project Type'
		dataType: string
		lineageTag: 2e107199-f88d-427f-802c-1ada015a5dd0
		summarizeBy: none
		sourceColumn: Project Type

		annotation SummarizationSetBy = Automatic

	column 'Abierto por'
		dataType: string
		lineageTag: d788ad8c-10c5-44c6-bd87-f4f238c838db
		summarizeBy: none
		sourceColumn: Abierto por

		annotation SummarizationSetBy = Automatic

	column 'Año Inicio'
		dataType: string
		lineageTag: 26e88ff2-9f8a-4eff-b4a9-a73d21ff622f
		summarizeBy: none
		sourceColumn: Año Inicio

		annotation SummarizationSetBy = Automatic

	column 'Año Fin'
		dataType: string
		lineageTag: ccd70047-4051-4634-8fa8-41950230f9cf
		summarizeBy: none
		sourceColumn: Año Fin

		annotation SummarizationSetBy = Automatic

	column 'Tipo fecha'
		dataType: string
		lineageTag: e6b8df9f-cde5-4c4c-9bd1-f46f624f0613
		summarizeBy: none
		sourceColumn: Tipo fecha

		annotation SummarizationSetBy = Automatic

	column 'Fecha inicio'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0f66fd28-b0ab-423e-8ed6-ff25ac7bb597
		summarizeBy: none
		sourceColumn: Fecha inicio

		variation Variación
			isDefault
			relationship: d29b5b42-e4b3-4d64-8b12-c28554b79e14
			defaultHierarchy: LocalDateTable_1e9e745e-0c52-4cc1-9426-20eca10bbc29.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin'
		dataType: dateTime
		formatString: General Date
		lineageTag: c507c303-b699-4427-9b6a-10e4abe7d796
		summarizeBy: none
		sourceColumn: Fecha fin

		variation Variación
			isDefault
			relationship: bbdd4a52-5b24-40c0-bf40-334baec9a257
			defaultHierarchy: LocalDateTable_a0ac73ce-36af-402c-96ae-ce4a89f1038b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio'
		dataType: string
		lineageTag: 871fbed6-9ed7-4c05-a2dd-e2b51e5ea9a0
		summarizeBy: none
		sourceColumn: Aplicación de Negocio

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: a36abec9-e727-4ea5-9a14-c39a20ee4b02
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Gestor de Demanda'
		dataType: string
		lineageTag: 166b537a-bc80-4e30-9dc8-7d1accacfe73
		summarizeBy: none
		sourceColumn: Gestor de Demanda

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: d11cfbe8-afd4-4198-bca4-42c24356ed60
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Asignado a'
		dataType: string
		lineageTag: 2f47bf4e-9b20-4ddc-8c07-623ea773e315
		summarizeBy: none
		sourceColumn: Asignado a

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: double
		lineageTag: 0f65ca7a-e135-4640-bbf5-51bb5073fc15
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 116b7620-2c1a-4d6c-a863-d330ab160716
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variación
			isDefault
			relationship: abc24ca8-bc8e-4446-b58c-5e67490bd724
			defaultHierarchy: LocalDateTable_74dbe03c-9ce2-477e-bedf-92f25a1bbae1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 94d2e00f-07ea-4f72-a748-d738687efaef
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variación
			isDefault
			relationship: 8d997a3d-82e6-4e50-a3f7-0c88abe7a761
			defaultHierarchy: LocalDateTable_97f1b6ea-1b40-4f00-99f7-c863a1bc2e3c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2793fd92-b6b8-41c4-b92f-f6bc1adcd2fa
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variación
			isDefault
			relationship: eacf6a64-0527-4ff5-856b-e41513e5cfa5
			defaultHierarchy: LocalDateTable_32d109bd-a788-43a9-9330-6a35c1134330.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6a6d57d8-b7c0-4894-8b57-0c09db7f2481
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variación
			isDefault
			relationship: 08fa549c-ef09-40fe-9ad7-c8735b198ed0
			defaultHierarchy: LocalDateTable_f926965a-474f-4917-89dd-a33e28340647.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Demanda
		dataType: string
		lineageTag: ac83be03-4741-48c5-ac95-bf46d039bca1
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Demand
		dataType: string
		lineageTag: 0ed84200-e9bf-4e04-a6be-e4abe1e24e8c
		summarizeBy: none
		sourceColumn: Demand

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción_1'
		dataType: string
		lineageTag: 51a73685-bdab-426e-af75-c96ebf4fc62e
		summarizeBy: none
		sourceColumn: Breve descripción_1

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 3615724e-966b-4953-bfec-e630d7b0c6dc
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto'
		dataType: string
		lineageTag: 82df05ec-3bb3-4504-8706-9f9b956b583a
		summarizeBy: none
		sourceColumn: Jefe de proyecto

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: 8e10dde8-2207-4af0-b521-cadcdb99ec0b
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Nombre de proyecto'
		dataType: string
		lineageTag: c2841632-8fd9-4b9e-9645-ba359ee1027b
		summarizeBy: none
		sourceColumn: Nombre de proyecto

		annotation SummarizationSetBy = Automatic

	column Descripción
		dataType: string
		lineageTag: 7cce3c1a-56e8-4e16-989b-a57f20987f84
		summarizeBy: none
		sourceColumn: Descripción

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: 9ee2dbdd-d5b4-4f23-9af6-0b65bdfeb582
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column Fase
		dataType: string
		lineageTag: 49ea1cf1-f321-40e8-9afd-8965aeff9539
		summarizeBy: none
		sourceColumn: Fase

		annotation SummarizationSetBy = Automatic

	column 'Estado de la Fase (State)'
		dataType: string
		lineageTag: c3cee98d-11b7-46fd-9af0-f2be646b71ea
		summarizeBy: none
		sourceColumn: Estado de la Fase (State)

		annotation SummarizationSetBy = Automatic

	column Creado
		dataType: double
		lineageTag: 17553abe-bbcf-482e-9d30-332d8d74535d
		summarizeBy: sum
		sourceColumn: Creado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Comentarios y notas de trabajo'
		dataType: string
		lineageTag: 42af71e8-c127-4942-b7e8-9f95fd6834d6
		summarizeBy: none
		sourceColumn: Comentarios y notas de trabajo

		annotation SummarizationSetBy = Automatic

	partition RM_Total_Gantt-1fd65ab8-a023-416f-bffc-6ba833180052 = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source =
				let
				    Origen = #"RM_Total (stagging)",
				    #"Valor reemplazado" = Table.ReplaceValue(Origen,null,DateTime.LocalNow(),Replacer.ReplaceValue,{"Fecha fin real"}),
				    #"Consulta anexada" = Table.Combine({#"Valor reemplazado", #"RM_Planned (stagging)"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Consulta anexada", "Año Inicio", each Date.Year([Fecha de inicio real])),
				    #"Personalizada agregada1" = Table.AddColumn(#"Personalizada agregada", "Año Fin", each Date.Year([Fecha fin real])),
				    #"Columna condicional agregada" = Table.AddColumn(#"Personalizada agregada1", "Fecha inicio", each if [Tipo fecha] = "Real" then [Fecha de inicio real] else if [Tipo fecha] = "Planificada" then [Fecha de inicio planificada] else null),
				    #"Columna condicional agregada1" = Table.AddColumn(#"Columna condicional agregada", "Fecha fin", each if [Tipo fecha] = "Real" then [Fecha fin real] else if [Tipo fecha] = "Planificada" then [Fecha fin planificada] else null),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna condicional agregada1",{{"Fecha inicio", type datetime}, {"Fecha fin", type datetime}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

