table KGI_I_Bugs_Jira
	lineageTag: 095056f7-717d-4aa6-86aa-eacfb058795a

	column Components
		dataType: string
		lineageTag: 3481900e-23d2-4aa9-aca7-10fef6a97e11
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 028576e3-a687-4f1e-b708-99037481b03b
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: db0b9bfc-5024-40e9-9ff6-4cc6138afe4d
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 4af981bf-79c6-4299-9e8f-e563be78c0b4
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 647c00db-cecd-4f6c-ba72-c472548cbd84
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 65854956-a50e-489d-b635-41c8a166e62c
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: a560d76a-25ce-4cd2-949b-071ccc5ff13d
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 7f2358a8-aacd-48ec-8f5b-eea64d7ea4bf
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 62ccedbe-a8e5-4642-a7c9-c241dac731b6
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: ed15701c-5f9b-4971-9ccb-a24c4cbf6a09
		summarizeBy: none
		sourceColumn: Created

		variation Variación
			isDefault
			relationship: 39dd1458-74b9-4af7-a350-247464c12778
			defaultHierarchy: LocalDateTable_514ee855-d37f-4482-ac7c-4c17297d1c15.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: e82c1bb9-3bfb-4503-b870-c411214e1017
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column 'Tipo de prueba'
		dataType: string
		lineageTag: 56cee531-7be1-4049-84e4-0725e4c905a6
		summarizeBy: none
		sourceColumn: Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: e6643aba-172e-48a7-9366-b0c7d96a6eb3
		summarizeBy: none
		sourceColumn: Resolved

		variation Variación
			isDefault
			relationship: 686f53ab-4f40-4167-9c1f-3bd64bac4236
			defaultHierarchy: LocalDateTable_b6547170-a7f5-42e9-b9d5-a2347fc78ee5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Resolution
		dataType: string
		lineageTag: eb4451ac-c617-4592-8690-0f197e199e1b
		summarizeBy: none
		sourceColumn: Resolution

		annotation SummarizationSetBy = Automatic

	column Atributo
		dataType: string
		lineageTag: e8b58c19-da9c-4acf-ab89-b5ca2e7d3f55
		summarizeBy: none
		sourceColumn: Atributo

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: string
		lineageTag: 7cfa86a6-a5a7-48d5-a657-58b5b7052fb1
		summarizeBy: none
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	column 'Stories.Key'
		dataType: string
		lineageTag: 4958a627-89b9-4c5e-99a4-a5c9ccbbc936
		summarizeBy: none
		sourceColumn: Stories.Key

		annotation SummarizationSetBy = Automatic

	column 'Stories.Priority'
		dataType: string
		lineageTag: 9b90dd6c-f682-440b-96a0-e7aaf3bb1fec
		summarizeBy: none
		sourceColumn: Stories.Priority

		annotation SummarizationSetBy = Automatic

	column 'Stories.Resolved'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: aba54e75-4b29-4114-a490-4104b5383abc
		summarizeBy: none
		sourceColumn: Stories.Resolved

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'ST Executions.Key'
		dataType: string
		lineageTag: f6317294-de47-44ef-946b-333bb2d7e205
		summarizeBy: none
		sourceColumn: ST Executions.Key

		annotation SummarizationSetBy = Automatic

	column 'ST Executions.Tipo de prueba'
		dataType: string
		lineageTag: 1f120f89-4776-42a5-9c80-e1b39cf50d08
		summarizeBy: none
		sourceColumn: ST Executions.Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column 'Stories.Resolved mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 024092a6-9e77-4ea8-a3e2-8c4503dd0e44
		summarizeBy: none
		sourceColumn: Stories.Resolved mes

		variation Variación
			isDefault
			relationship: bbf266c4-8397-4222-880e-0ec5b2d1e500
			defaultHierarchy: LocalDateTable_572463e2-2e0f-4b79-a6bd-2fd6b4c3628a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Project_starts_with
		dataType: string
		lineageTag: cc9fb11c-c38d-48f4-aff7-7ac92825acd5
		summarizeBy: none
		sourceColumn: Project_starts_with

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_1.5'
		dataType: string
		lineageTag: 4026fa6b-3d43-4a71-81c0-37cadbcc4bab
		summarizeBy: none
		sourceColumn: ID_KGI_1.5

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_1.6'
		dataType: string
		lineageTag: 68b3e5fd-16bc-4dbc-bed4-a77e19211a66
		summarizeBy: none
		sourceColumn: ID_KGI_1.6

		annotation SummarizationSetBy = Automatic

	column Proyecto_Evolutivo
		dataType: string
		lineageTag: 97d07ba9-7be0-4d83-8bd2-86a4210ca52a
		summarizeBy: none
		sourceColumn: Proyecto_Evolutivo

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.ID Alegación'
		dataType: string
		lineageTag: 1b060186-9d79-4c12-8ab1-379f4337d2b7
		summarizeBy: none
		sourceColumn: T_Alegaciones.ID Alegación

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.Solicitante'
		dataType: string
		lineageTag: 1df10866-e87d-4f97-8cf7-8835cb4ac3c4
		summarizeBy: none
		sourceColumn: T_Alegaciones.Solicitante

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.ANS'
		dataType: string
		lineageTag: 5d1b985a-5d16-4d47-8ba3-bd28ec8c25a9
		summarizeBy: none
		sourceColumn: T_Alegaciones.ANS

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.Estado'
		dataType: string
		lineageTag: 8eae02ef-b2ef-47a2-bdc1-cd52cfe04b87
		summarizeBy: none
		sourceColumn: T_Alegaciones.Estado

		annotation SummarizationSetBy = Automatic

	partition KGI_I_Bugs_Jira-64117e61-e646-47bd-bb1f-0772a8c854e9 = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source = ```
				let
				    Origen = #"KGI_I_Bugs_Jira (stagging)",
				    #"Encabezados promovidos1" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos1",{{"Components", type text}, {"Project", type text}, {"Issue Type", type text}, {"Key", type text}, {"Summary", type text}, {"Assignee", type text}, {"Reporter", type text}, {"Priority", type text}, {"Status", type text}, {"Created", type datetime}, {"Linked Issues", type text}, {"Sub-tasks", type text}, {"Tipo de prueba", type text}, {"Resolved", type datetime}, {"Resolution", type text}}),
				    #"Separación Linked-Issues" = Table.SplitColumn(#"Tipo cambiado1", "Linked Issues", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {
				        "Linked Issues.1",
				        "Linked Issues.2",
				        "Linked Issues.3",
				        "Linked Issues.4",
				        "Linked Issues.5",        
				        "Linked Issues.6",        
				        "Linked Issues.7",        
				        "Linked Issues.8",       
				        "Linked Issues.9",
				        "Linked Issues.10"        
				        }),
				    #"Columna de anulación de dinamización" = Table.UnpivotOtherColumns(#"Separación Linked-Issues", {"Components", "Project", "Issue Type", "Key", "Summary", "Assignee", "Reporter", "Priority", "Status", "Created", "Sub-tasks", "Tipo de prueba", "Resolved","Resolution"}, "Atributo", "Valor"),
				    #"Consultas combinadas2" = Table.NestedJoin(#"Columna de anulación de dinamización", {"Valor"}, KGI_I_Stories_Jira, {"Key"}, "Stories", JoinKind.Inner),
				    #"Se expandió Stories2" = Table.ExpandTableColumn(#"Consultas combinadas2", "Stories", {"Key", "Priority", "Resolved"}, {"Stories.Key", "Stories.Priority", "Stories.Resolved"}),
				    #"Consultas combinadas3" = Table.NestedJoin(#"Se expandió Stories2", {"Key"}, KGI_I_ST_Excecutions_Jira, {"Valor"}, "ST Executions", JoinKind.LeftOuter),
				    #"Se expandió ST Executions" = Table.ExpandTableColumn(#"Consultas combinadas3", "ST Executions", {"Key", "Tipo de prueba"}, {"ST Executions.Key", "ST Executions.Tipo de prueba"}),
				    #"Inicio del mes insertado" = Table.AddColumn(#"Se expandió ST Executions", "Stories.Resolved mes", each Date.StartOfMonth([Stories.Resolved]), type datetime),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Inicio del mes insertado",{{"Stories.Resolved mes", type date},{"Stories.Resolved", type date}}),
				    #"Primeros caracteres insertados" = Table.AddColumn(#"Tipo cambiado2", "Project_starts_with", each Text.Start([Project], 4), type text),
				    #"Columna condicional agregada" = Table.AddColumn(#"Primeros caracteres insertados", "ID_KGI_1.5", 
				                                                    each if [Project_starts_with] <> "Mtto"  and [Priority] = "Highest" then "1-5-1-1"
				                                                    else if [Project_starts_with] <> "Mtto"  and [Priority] = "High" then "1-5-1-1" 
				                                                    else if [Project_starts_with] <> "Mtto"  and [Priority] = "Medium" then "1-5-1-2"
				                                                    else if [Project_starts_with] <> "Mtto"  and [Priority] = "Low" then "1-5-1-3"
				                                                    else if [Project_starts_with] <> "Mtto"  and [Priority] = "Lowest" then "1-5-1-3"
				                                                    else if [Project_starts_with] = "Mtto" and [Priority] = "Highest" then "1-5-2-1"
				                                                    else if [Project_starts_with] = "Mtto" and [Priority] = "High" then "1-5-2-1"
				                                                    else if [Project_starts_with] = "Mtto" and [Priority] = "Medium" then "1-5-2-2"
				                                                    else if [Project_starts_with] = "Mtto" and [Priority] = "Low" then "1-5-2-3"
				                                                    else if [Project_starts_with] = "Mtto" and [Priority] = "Lowest" then "1-5-2-3"
				                                                    else null
				    ),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Columna condicional agregada", "ID_KGI_1.5", "ID_KGI_1.6"),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columna duplicada","5","6",Replacer.ReplaceText,{"ID_KGI_1.6"}),
				    #"Columna condicional agregada1" = Table.AddColumn(#"Valor reemplazado", "Proyecto_Evolutivo", each if Text.StartsWith([Project], "Mtto") then "Evolutivos" else if [Project] = null then null else "Proyectos"),
				    #"Proyecto_Evolutivo" = Table.ReplaceErrorValues(#"Columna condicional agregada1", {{"Proyecto_Evolutivo", null}}),
				    #"Consultas combinadas" = Table.NestedJoin(Proyecto_Evolutivo, {"Key"}, T_Alegaciones, {"ID"}, "T_Alegaciones", JoinKind.LeftOuter),
				    #"Se expandió T_Alegaciones" = Table.ExpandTableColumn(#"Consultas combinadas", "T_Alegaciones", {"ID Alegación", "Solicitante", "ANS", "Estado"}, {"T_Alegaciones.ID Alegación", "T_Alegaciones.Solicitante", "T_Alegaciones.ANS", "T_Alegaciones.Estado"})
				in
				    #"Se expandió T_Alegaciones"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

