table KGI_III_Peticiones
	lineageTag: c756babe-5ebf-4136-ad69-314f493a23ed

	column 'Solicitar elemento'
		dataType: string
		lineageTag: 0187e727-7d21-4ffd-8d03-dd70ca25b546
		summarizeBy: none
		sourceColumn: Solicitar elemento

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 55380a47-e5f9-430b-ab18-3790f6f65f88
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 1c1de32e-0ef0-4b19-8fae-bc0010f41bca
		summarizeBy: none
		sourceColumn: Cerrado

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Hora de inicio'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4db634c4-7fa2-4d93-b341-eafe52b71fdd
		summarizeBy: none
		sourceColumn: Hora de inicio

		variation Variación
			isDefault
			relationship: 0f1fd37d-4cba-4857-9d72-40f94763fe65
			defaultHierarchy: LocalDateTable_e23c4786-0b5f-4b57-a7f1-4c74a88fd4b0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Hora de finalización'
		dataType: dateTime
		formatString: General Date
		lineageTag: 7fbc6c4b-4c29-466f-b26f-d7f4a4e11f12
		summarizeBy: none
		sourceColumn: Hora de finalización

		variation Variación
			isDefault
			relationship: 02b90c6d-f610-4241-bc57-c85ebeacdf01
			defaultHierarchy: LocalDateTable_9864f95d-b453-4930-bef2-7733ad70ad79.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: int64
		formatString: 0
		lineageTag: cf9df877-cc12-4b0d-9303-cc7c36bb241c
		summarizeBy: sum
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 74ea3cad-c308-476b-afb5-6397304ab89c
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: double
		lineageTag: 44548e8a-d316-4a98-8b74-e27a2ba5702e
		summarizeBy: sum
		sourceColumn: Tiempo original de incumplimiento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Estado
		dataType: string
		lineageTag: e3cf9261-79b1-4575-99c6-c5deafd254a2
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Etapa
		dataType: string
		lineageTag: bdd691dc-2930-4a30-8f66-e535683bdcef
		summarizeBy: none
		sourceColumn: Etapa

		annotation SummarizationSetBy = Automatic

	column 'Número de reasignación'
		dataType: int64
		formatString: 0
		lineageTag: 38ca89b0-e4f7-466d-b16b-e049ed1b0a18
		summarizeBy: sum
		sourceColumn: Número de reasignación

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 1df3c19e-8c7f-478e-87a3-b4fba8f0b0cd
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 7f195789-992e-4254-b4ce-cd5702d7fc0f
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Cerrado mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9c18b081-5bf8-4f5b-918c-5586a19a344b
		summarizeBy: none
		sourceColumn: Cerrado mes

		variation Variación
			isDefault
			relationship: a9bb7d14-d234-4b30-82d9-7cd71999fef3
			defaultHierarchy: LocalDateTable_89016e15-1689-4f2f-b526-358432cbb4cb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Prioridad grupo'
		dataType: string
		lineageTag: 76c9ac65-6b15-44b6-a170-1c63fa00c5c0
		summarizeBy: none
		sourceColumn: Prioridad grupo

		annotation SummarizationSetBy = Automatic

	column 'Abierto mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 680c8ec6-811a-4e2c-aaaf-fd675e84626e
		summarizeBy: none
		sourceColumn: Abierto mes

		variation Variación
			isDefault
			relationship: e639af15-242b-41c3-ba7c-a41b3f955fd3
			defaultHierarchy: LocalDateTable_12916b93-b23f-4ebd-ae14-f2a329eecf96.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Nombre
		dataType: string
		lineageTag: a4c9ab3c-88b8-4f2b-b782-d42a2bd0da2a
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 8202727b-f1f2-463b-876a-0dfd099e40d4
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: b2466722-e069-4ff3-bbec-7ab1f56c6e6d
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Duración tabla' = ```
			
			
			VAR VDUR21_2 = KGI_III_Peticiones[Duración del negocio]
			VAR _duracCalculada = INT (VDUR21_2/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_2/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21_2/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21_2,60)),2)
			
			RETURN 
			
			_duracCalculada
			```
		lineageTag: 8cb8cd16-2496-491c-b425-651456cdea7b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Infringido_alegaciones
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 887ae7c8-e7e5-416e-955e-1f1f08b58de2
		summarizeBy: none
		sourceColumn: Infringido_alegaciones

		annotation SummarizationSetBy = Automatic

	column Duración_excedida_tabla = ```
			
			
			VAR VDUR21_EX_2 = KGI_III_Peticiones[Duración excedida]
			VAR _duracCalculada = INT
			    (VDUR21_EX_2/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_EX_2/3600,24)),2)&" HH"
			
			RETURN 
			
			_duracCalculada
			```
		lineageTag: e5689b30-cc17-4378-83db-d7de8c22e46c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración excedida'
		dataType: string
		lineageTag: a1719a85-2ca1-428e-8232-ebcb588d6e52
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column 'Incidencia.Subcategoría'
		dataType: string
		lineageTag: 3f9514c6-7e58-413c-a18d-fafd22a9d80d
		summarizeBy: none
		sourceColumn: Incidencia.Subcategoría

		annotation SummarizationSetBy = Automatic

	column 'Incidencia.Breve descripción'
		dataType: string
		lineageTag: 4295e264-c069-4656-8f23-2ee797b329b5
		summarizeBy: none
		sourceColumn: Incidencia.Breve descripción

		annotation SummarizationSetBy = Automatic

	column 'KGI_III_Encuestas.Cerrado'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0c6c725d-6a3f-476c-baba-93727054053d
		summarizeBy: none
		sourceColumn: KGI_III_Encuestas.Cerrado

		variation Variación
			isDefault
			relationship: e73ec779-9f55-47fa-a7e4-a88495c2b1cd
			defaultHierarchy: LocalDateTable_64174079-a21d-4d7e-9e97-ba117f57153d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'KGI_III_Encuestas.Valoración'
		dataType: string
		lineageTag: 0b881ff5-1386-4e9b-ac79-9ca56c150617
		summarizeBy: none
		sourceColumn: KGI_III_Encuestas.Valoración

		annotation SummarizationSetBy = Automatic

	column Extracción
		dataType: dateTime
		formatString: Long Date
		lineageTag: e572fc8d-fae8-445a-b264-a4e57506e49f
		summarizeBy: none
		sourceColumn: Extracción

		variation Variación
			isDefault
			relationship: eaeada1d-aacd-4d34-b06a-83d9581b05e1
			defaultHierarchy: LocalDateTable_cc4a0de1-68fa-46a3-a4a9-e1397a5ac2b5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Abierto
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4d942f81-14f7-4055-9b85-56e3a24b165d
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: cefcaa48-0e23-47f9-afba-3edd37b2d79e
			defaultHierarchy: LocalDateTable_a7abb4eb-084d-418c-99ca-b4d0f9ebc7cb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Abierto por'
		dataType: string
		lineageTag: b267a228-b5a2-4b88-9e83-b61be440aee1
		summarizeBy: none
		sourceColumn: Abierto por

		annotation SummarizationSetBy = Automatic

	column 'Incidencia.Alegaciones'
		dataType: string
		lineageTag: 44ca0d01-0fca-4cd3-97d1-01e124578509
		summarizeBy: none
		sourceColumn: Incidencia.Alegaciones

		annotation SummarizationSetBy = Automatic

	column 'Incidencia.Número'
		dataType: string
		lineageTag: 422c317d-647f-4905-8343-84ce9c17c2e9
		summarizeBy: none
		sourceColumn: Incidencia.Número

		annotation SummarizationSetBy = Automatic

	column 'Incidencia.Tipo de Solución'
		dataType: string
		lineageTag: 0994140a-07e0-4bab-a8fd-5b4e648632eb
		summarizeBy: none
		sourceColumn: Incidencia.Tipo de Solución

		annotation SummarizationSetBy = Automatic

	column 'Definición de SLA'
		dataType: string
		lineageTag: 39abfd8a-d6ea-4c22-b24a-33025a8bd70a
		summarizeBy: none
		sourceColumn: Definición de SLA

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_4.1'
		dataType: string
		lineageTag: 46ffbd37-b974-4a25-90bf-8138ed209060
		summarizeBy: none
		sourceColumn: ID_KGI_4.1

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_4.2'
		dataType: string
		lineageTag: 9a06151e-96c4-4b76-83f2-3194d121d8a0
		summarizeBy: none
		sourceColumn: ID_KGI_4.2

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_4.3'
		dataType: string
		lineageTag: b949c59b-2a98-488b-b2e9-74ea824073b3
		summarizeBy: none
		sourceColumn: ID_KGI_4.3

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_4.4'
		dataType: string
		lineageTag: e3f6bfef-5530-47ad-b0d7-bb80b6f11161
		summarizeBy: none
		sourceColumn: ID_KGI_4.4

		annotation SummarizationSetBy = Automatic

	column Alegaciones
		dataType: string
		lineageTag: 327b71e6-edf2-4b0d-80e6-6c29c37d7005
		summarizeBy: none
		sourceColumn: Alegaciones

		annotation SummarizationSetBy = Automatic

	partition KGI_III_Peticiones-bc0f8c67-81d9-43bb-9e77-ff181229b912 = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source = ```
				let
				    Origen = KGI_III_Peticiones_Actuales_Histórico,
				    #"Filas filtradas" = Table.SelectRows(Origen, let latest = List.Max(Origen[Extracción]) in each [Extracción] = latest),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Filas filtradas",{{"Abierto", type date}, {"Cerrado", type date}, {"Hora de inicio", type datetime}, {"Hora de finalización", type datetime}}),
				    #"Inicio del mes insertado" = Table.AddColumn(#"Tipo cambiado2", "Cerrado mes", each Date.StartOfMonth([Cerrado]), type datetime),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Inicio del mes insertado",{{"Cerrado mes", type date}, {"Tiempo original de incumplimiento", type datetime},  {"Cerrado", type datetime}, {"Abierto", type datetime}, {"Porcentaje de negocio trascurrido", type number}, {"Duración", Int64.Type}, {"Número de reasignación", Int64.Type}, {"Duración del negocio", Int64.Type}, {"Duración real", Int64.Type}, {"Infringido", Logical.Type}}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Tipo cambiado", "Prioridad grupo", each if [Prioridad] = "1 - Crítica" then "P1" else if [Prioridad] = "2 - Alta" then "P2" else if [Prioridad] = "3 - Moderada" then "P1" else "P1", type text),
				    #"Inicio del mes insertado1" = Table.AddColumn(#"Columna condicional agregada", "Abierto mes", each Date.StartOfMonth([Abierto]), type datetime),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Inicio del mes insertado1",{{"Abierto mes", type date}, {"Hora de inicio", type datetime}, {"Hora de finalización", type datetime}, {"Tiempo original de incumplimiento", type number},{"Abierto", type date}, {"Cerrado", type date}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Tipo cambiado1", {"Solicitar elemento"}, T_Alegaciones_Resumen, {"ID"}, "T_Alegaciones_Resumen", JoinKind.LeftOuter),
				    #"Se expandió T_Alegaciones_Resumen" = Table.ExpandTableColumn(#"Consultas combinadas", "T_Alegaciones_Resumen", {"KGI"}, {"T_Alegaciones_Resumen.KGI"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Se expandió T_Alegaciones_Resumen",{{"T_Alegaciones_Resumen.KGI", "Alegaciones"}}),
				    ID_KGI_3.1 = Table.AddColumn(#"Columnas con nombre cambiado", 
				                 "ID_KGI_4.1", 
				                 each if [Prioridad] = "1 - Crítica" then "4-1-4-1" 
				                      else if [Prioridad] = "2 - Alta" then "4-1-4-1" 
				                      else if [Prioridad] = "3 - Moderada" then "4-1-4-1" 
				                      else if [Prioridad] = "4 - Baja" then "4-1-4-1"
				                      else if [Prioridad] = "5 - Muy Baja" then "4-1-4-1" 
				                      else null, 
				                type text),
				    ID_KGI_3.2 = Table.AddColumn(#"ID_KGI_3.1", 
				                 "ID_KGI_4.2", 
				                 each if [Prioridad] = "1 - Crítica" then "4-2-4-1" 
				                      else if [Prioridad] = "2 - Alta" then "4-2-4-1" 
				                      else if [Prioridad] = "3 - Moderada" then "4-2-4-1" 
				                      else if [Prioridad] = "4 - Baja" then "4-2-4-1"
				                      else if [Prioridad] = "5 - Muy Baja" then "4-2-4-1" 
				                      else null, 
				                type text),
				    ID_KGI_3.3 = Table.AddColumn(ID_KGI_3.2, 
				                 "ID_KGI_4.3", 
				                 each if [Prioridad] = "1 - Crítica" then "4-3-4-1" 
				                      else if [Prioridad] = "2 - Alta" then "4-3-4-1" 
				                      else if [Prioridad] = "3 - Moderada" then "4-3-4-1" 
				                      else if [Prioridad] = "4 - Baja" then "4-3-4-1"
				                      else if [Prioridad] = "5 - Muy Baja" then "4-3-4-1" 
				                      else null, 
				                type text),
				    //ID_KGI_3.4 = Table.AddColumn(ID_KGI_3.3, "ID_KGI_3.4", each "3-4-3-1"),
				    #"Valor reemplazado" = Table.ReplaceValue(ID_KGI_3.3,null,#date(2100, 1, 1),Replacer.ReplaceValue,{"Cerrado"}),
				    #"Porcentaje de negocio / 100" = Table.TransformColumns(#"Valor reemplazado", {{"Porcentaje de negocio trascurrido", each _ / 100, Percentage.Type}}),
				    Infringido_alegaciones = Table.AddColumn(#"Porcentaje de negocio / 100", "Infringido_alegaciones", each if [Infringido] = true and [Alegaciones] <> null and Text.Contains([Alegaciones],"4-1") then false else [Infringido], Logical.Type),
				    #"Duración excedida" = Table.AddColumn(Infringido_alegaciones, "Duración excedida", each if [#"Infringido"] = false then 0 else ([Duración real]-[Duración])),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Duración excedida", {"Solicitar elemento"}, #"KGI_III_Incidencias Peticiones", {"Principal"}, "Combinada", JoinKind.LeftOuter),
				    #"Se expandió Combinada" = Table.ExpandTableColumn(#"Consultas combinadas1", "Combinada", {"Número", "Breve descripción", "Subcategoría", "Tipo de Solución", "Alegaciones"}, {"Incidencia.Número", "Incidencia.Breve descripción", "Incidencia.Subcategoría", "Incidencia.Tipo de Solución", "Incidencia.Alegaciones"}),
				    #"Consultas combinadas3" = Table.NestedJoin(#"Se expandió Combinada", {"Número"}, #"KGI_III_Incidencias Peticiones", {"Principal"}, "KGI_III_Incidencias Peticiones", JoinKind.LeftOuter),
				    #"Se expandió KGI_III_Incidencias Peticiones" = Table.ExpandTableColumn(#"Consultas combinadas3", "KGI_III_Incidencias Peticiones", {"Número", "Breve descripción", "Subcategoría", "Tipo de Solución", "Alegaciones"}, {"KGI_III_Incidencias Peticiones.Número", "KGI_III_Incidencias Peticiones.Breve descripción", "KGI_III_Incidencias Peticiones.Subcategoría", "KGI_III_Incidencias Peticiones.Tipo de Solución", "KGI_III_Incidencias Peticiones.Alegaciones"}),
				    #"Columnas combinadas" = Table.CombineColumns(Table.TransformColumnTypes(#"Se expandió KGI_III_Incidencias Peticiones", {{"Incidencia.Número", type text}}, "es-ES"),{"Incidencia.Número", "KGI_III_Incidencias Peticiones.Número"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Incidencia.Número"),
				    #"Columnas combinadas1" = Table.CombineColumns(Table.TransformColumnTypes(#"Columnas combinadas", {{"Incidencia.Breve descripción", type text}}, "es-ES"),{"Incidencia.Breve descripción", "KGI_III_Incidencias Peticiones.Breve descripción"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Incidencia.Breve descripción"),
				    #"Columnas combinadas2" = Table.CombineColumns(Table.TransformColumnTypes(#"Columnas combinadas1", {{"Incidencia.Subcategoría", type text}}, "es-ES"),{"Incidencia.Subcategoría", "KGI_III_Incidencias Peticiones.Subcategoría"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Incidencia.Subcategoría"),
				    #"Columnas combinadas3" = Table.CombineColumns(Table.TransformColumnTypes(#"Columnas combinadas2", {{"Incidencia.Tipo de Solución", type text}}, "es-ES"),{"Incidencia.Tipo de Solución", "KGI_III_Incidencias Peticiones.Tipo de Solución"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Incidencia.Tipo de Solución"),
				    #"Columnas combinadas4" = Table.CombineColumns(#"Columnas combinadas3",{"Incidencia.Alegaciones", "KGI_III_Incidencias Peticiones.Alegaciones"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Incidencia.Alegaciones"),
				    #"Consultas combinadas2" = Table.NestedJoin(#"Columnas combinadas4", {"Número"}, KGI_III_Encuestas, {"Número_1"}, "KGI_III_Encuestas", JoinKind.LeftOuter),
				    #"Se expandió KGI_III_Encuestas1" = Table.ExpandTableColumn(#"Consultas combinadas2", "KGI_III_Encuestas", {"Cerrado", "Valoración"}, {"KGI_III_Encuestas.Cerrado", "KGI_III_Encuestas.Valoración"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Se expandió KGI_III_Encuestas1",
				                     each [KGI_III_Encuestas.Valoración], 
				                     each if [KGI_III_Encuestas.Valoración] = null or Text.Contains([Alegaciones],"3-4") /*and Date.EndOfMonth([Cerrado]) < Date.From(DateTime.LocalNow())*/ then "Alta" 
				                     else [KGI_III_Encuestas.Valoración],Replacer.ReplaceValue,
				                    {"KGI_III_Encuestas.Valoración"}),
				    ID_KGI_3.4 = Table.AddColumn(#"Valor reemplazado1", 
				                 "ID_KGI_4.4", 
				                 each if [KGI_III_Encuestas.Valoración] = "Alta" then "4-4-4-1" 
				                      else if [KGI_III_Encuestas.Valoración] = "Media" then "4-4-4-1" 
				                      else if [KGI_III_Encuestas.Valoración] = "Baja" then "4-4-4-1" 
				                      else null, 
				                type text),
				    #"Valor reemplazado2" = Table.ReplaceValue(ID_KGI_3.4,"",null,Replacer.ReplaceValue,{"Incidencia.Número"}),
				    #"Duplicados quitados" = Table.Distinct(#"Valor reemplazado2", {"Solicitar elemento"})
				in
				    #"Duplicados quitados"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

