table KGI_II_Incidencias_Backlog
	lineageTag: e8a5de70-43b8-4567-a379-35ce3991803c

	column Número
		dataType: string
		lineageTag: fe65b0c2-90b4-4fdc-a775-1abf2b23bf96
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Subcategoría
		dataType: string
		lineageTag: 6697da91-8862-4d4e-9d30-0aa87fcd743f
		summarizeBy: none
		sourceColumn: Subcategoría

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3cff7080-b335-40af-aef5-30ba674e5ddf
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: f44a954b-ddc3-4e29-9f56-1a5b508c4119
			defaultHierarchy: LocalDateTable_47a60c37-df48-41a2-9299-8073fec2489f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Cerrado
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0b2b09a7-dc9b-4001-8c3a-1bd6b9ba5d37
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: 611e478f-b417-44cd-b551-11794414d9ce
			defaultHierarchy: LocalDateTable_87edeaa6-4b9c-4bd4-82ec-1f5d5764794e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración del negocio'
		dataType: int64
		formatString: 0
		lineageTag: df0ea385-7be4-4332-b2a3-6f8ea49f941c
		summarizeBy: sum
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: b86f3bee-82a1-4d52-9bc2-b1f04258c83c
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column Extracción
		dataType: dateTime
		formatString: Long Date
		lineageTag: eb179fc0-8bfa-41b6-8ac2-ccb4d624198a
		summarizeBy: none
		sourceColumn: Extracción

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Prioridad grupo ANS1.3'
		dataType: string
		lineageTag: fa13fb2c-d2b2-49aa-8222-7854b05d82ec
		summarizeBy: none
		sourceColumn: Prioridad grupo ANS1.3

		annotation SummarizationSetBy = Automatic

	column Estado_abierta
		dataType: string
		lineageTag: a471bcf0-cf19-4853-9584-e0d42175020e
		summarizeBy: none
		sourceColumn: Estado_abierta

		annotation SummarizationSetBy = Automatic

	column 'Duración tabla' = ```
			
			
			VAR VDUR21_2 = KGI_II_Incidencias_Backlog[Duración del negocio]
			VAR _duracCalculada = INT (VDUR21_2/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_2/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21_2/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21_2,60)),2)
			
			RETURN 
			
			_duracCalculada
			```
		lineageTag: b08e0a76-0ed3-4e52-a1e0-24ce21fccc0a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración (h.)' = KGI_II_Incidencias_Backlog[Duración del negocio] / 3600
		formatString: 0.00
		lineageTag: dea43626-2078-4279-95f3-4771a7303f34
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_2.5'
		dataType: string
		lineageTag: ab70124f-f6b2-4f9e-9046-2fbe219b36c1
		summarizeBy: none
		sourceColumn: ID_KGI_2.5

		annotation SummarizationSetBy = Automatic

	column Alegación_aceptada
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 397019e1-7bec-4832-a156-c412d23782d7
		summarizeBy: none
		sourceColumn: Alegación_aceptada

		annotation SummarizationSetBy = Automatic

	column 'Abierto mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e70047f0-e0ad-4260-b2c0-8e4a1f76f560
		summarizeBy: none
		sourceColumn: Abierto mes

		variation Variación
			isDefault
			relationship: 99f58efa-360b-4ca1-9171-cb1306ddd1bd
			defaultHierarchy: LocalDateTable_29c5a511-133a-482d-a997-1d7753098989.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Cerrado mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b16ec1ba-1a0a-4409-aabc-3bd16dabf814
		summarizeBy: none
		sourceColumn: Cerrado mes

		variation Variación
			isDefault
			relationship: f201279f-baf0-4bff-8f5b-b46981255eab
			defaultHierarchy: LocalDateTable_e91d2d06-0ed7-4026-be24-51e2d57b916c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Elemento de configuración'
		dataType: string
		lineageTag: 4f2fdb74-156a-4d53-b26a-05f1f082f140
		summarizeBy: none
		sourceColumn: Elemento de configuración

		annotation SummarizationSetBy = Automatic

	column 'Abierto por'
		dataType: string
		lineageTag: 6fa6ec57-9b4d-451b-b95d-741f61b5d80f
		summarizeBy: none
		sourceColumn: Abierto por

		annotation SummarizationSetBy = Automatic

	partition KGI_II_Incidencias_Backlog-d5288b77-88b8-449c-bff4-5556c42196de = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source = ```
				let
				    Origen = Table.Combine({KGI_II_Incidencias_Actuales_Histórico, KGI_II_Incidencias_Previas}),
				    #"Filas filtradas" = Table.SelectRows(Origen, each ([Número] <> null)),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Filas filtradas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Columnas renombradas" = Table.RenameColumns(#"Filas en blanco eliminadas",{{"Volver a abrir recuento", "Reabierta"}, {"Código de resolución", "Código de cierre"}, {"Duración_1", "Duración SLA"}, /*{"Duración del negocio", "Duración real"},*/ {"Etapa", "Estado SLA"}, {"Resuelto", "Fecha de resolución"}}),
				    #"Inicio del mes insertado" = Table.AddColumn(#"Columnas renombradas", "Abierto mes", each Date.StartOfMonth([Abierto]), type datetime),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Inicio del mes insertado",null,#date(2100, 1, 1),Replacer.ReplaceValue,{"Cerrado"}),
				    #"Transforma Porcentaje negocio" = Table.TransformColumns(#"Valor reemplazado", {{"Porcentaje de negocio trascurrido", each _ / 100, Percentage.Type}}),
				    #"Inicio del mes insertado1" = Table.AddColumn(#"Transforma Porcentaje negocio", "Cerrado mes", each Date.StartOfMonth([Cerrado]), type datetime),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Inicio del mes insertado1",{{"Abierto mes", type date}, {"Reabierta", Int16.Type}, {"Duración del negocio", Int64.Type}, {"Infringido", Logical.Type},{"Cerrado mes", type date},{"Cerrado", type date},{"Abierto", type date},{"Extracción", type date}}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Tipo cambiado1", "Prioridad grupo ANS1.3", each if [Prioridad] = "1 - Crítica" then "Crítica" else if [Prioridad] = "2 - Alta" then "Alta" else if [Prioridad] = "3 - Moderada" then "Media" else "Baja", type text),
				    ID_KGI_2.1 = Table.AddColumn(#"Columna condicional agregada", 
				                 "ID_KGI2.1", 
				                 each if [Prioridad] = "1 - Crítica" then "2-1-4-1" 
				                      else if [Prioridad] = "2 - Alta" then "2-1-4-2" 
				                      else if [Prioridad] = "3 - Moderada" then "2-1-4-3" 
				                      else if [Prioridad] = "4 - Baja" then "2-1-4-4"
				                      else if [Prioridad] = "5 - Muy Baja" then "2-1-4-4" 
				                      else null, 
				                type text),
				    ID_KGI_2.5 = Table.AddColumn(ID_KGI_2.1, "ID_KGI_2.5", each Text.Replace([ID_KGI2.1], "2-1", "2-5"), type text),
				/*    ID_KGI_3.2 = Table.AddColumn(#"ID_KGI_2.5", 
				                 "ID_KGI3.2", 
				                 each if [SLA_III_Peticiones.Prioridad] = "1 - Crítica" then "3-2-3-1" 
				                      else if [SLA_III_Peticiones.Prioridad] = "2 - Alta" then "3-2-3-2" 
				                      else if [SLA_III_Peticiones.Prioridad] = "3 - Moderada" then "3-2-3-2" 
				                      else if [SLA_III_Peticiones.Prioridad] = "4 - Baja" then "3-2-3-3"
				                      else if [SLA_III_Peticiones.Prioridad] = "5 - Muy Baja" then "3-2-3-3" 
				                      else null, 
				                type text),
				*/
				    #"Consultas combinadas2" = Table.NestedJoin(ID_KGI_2.5, {"Número"}, T_Alegaciones_Resumen, {"ID"}, "T_Alegaciones_Resumen", JoinKind.LeftOuter),
				    #"Se expandió T_Alegaciones" = Table.ExpandTableColumn(#"Consultas combinadas2", "T_Alegaciones_Resumen", {"Alegaciones"}, {"Alegaciones"}),
				    #"Infringido con alegaciones" = Table.AddColumn(#"Se expandió T_Alegaciones", "Alegación_aceptada", each if /*[Infringido] = true and*/ [Alegaciones] <> null and Text.Contains([Alegaciones],"2-5")  then true else false, Logical.Type),
				    #"Columna condicional agregada4" = Table.AddColumn(#"Infringido con alegaciones", "Estado_abierta", 
				                  each if [Abierto mes] <= [Extracción] and (([Cerrado mes] > [Extracción] and [Cerrado mes] > [Abierto mes])
				                                                              or ([Cerrado mes] = null)
				                                                            )  then true 
				                        else false),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Columna condicional agregada4",{"Extracción", "Número", "Subcategoría", "Abierto", "Abierto por", "Cerrado", "Duración del negocio", "Porcentaje de negocio trascurrido", "Elemento de configuración", "Abierto mes", "Cerrado mes", "Prioridad grupo ANS1.3", "ID_KGI_2.5", "Alegación_aceptada", "Estado_abierta"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Otras columnas quitadas", each ([Estado_abierta] = true)),
				    #"Filas filtradas4" = Table.SelectRows(#"Filas filtradas1", each [Alegación_aceptada] = false)
				in
				    #"Filas filtradas4"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

