table 'SERV_NOW cmdb_ci_appl'
	lineageTag: 19db452c-769f-4aa5-80b4-08fe81c64620

	column sys_id
		dataType: string
		lineageTag: 2d2ca524-a65c-4912-8b26-bba49f7ea631
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column dv_u_catalog
		dataType: string
		lineageTag: e46fd785-7785-4a78-97a6-033c543967c6
		summarizeBy: none
		sourceColumn: dv_u_catalog

		annotation SummarizationSetBy = Automatic

	column dv_u_platform
		dataType: string
		lineageTag: 1966bfd3-6ef3-49c8-ba66-b11fe1c37da1
		summarizeBy: none
		sourceColumn: dv_u_platform

		annotation SummarizationSetBy = Automatic

	column u_complexity
		dataType: string
		lineageTag: e5201791-2b22-4134-9386-e0219879e743
		summarizeBy: none
		sourceColumn: u_complexity

		annotation SummarizationSetBy = Automatic

	column dv_u_complexity
		dataType: string
		lineageTag: fc76a49b-8e7c-4621-9263-ba6a7b138384
		summarizeBy: none
		sourceColumn: dv_u_complexity

		annotation SummarizationSetBy = Automatic

	column u_contract_number
		dataType: string
		lineageTag: 206f5ed7-c16c-4a79-a0e2-4c3515f6ef1f
		summarizeBy: none
		sourceColumn: u_contract_number

		annotation SummarizationSetBy = Automatic

	column dv_u_country
		dataType: string
		lineageTag: 624b2ac7-59e0-4257-813b-b1dfdbe88d7f
		summarizeBy: none
		sourceColumn: dv_u_country

		annotation SummarizationSetBy = Automatic

	column u_data_source
		dataType: string
		lineageTag: c179af4b-b672-444e-89e1-e2e95f489f2a
		summarizeBy: none
		sourceColumn: u_data_source

		annotation SummarizationSetBy = Automatic

	column dv_u_data_source
		dataType: string
		lineageTag: 6fb1ac18-a3ec-4151-a1e1-6f41e68a4935
		summarizeBy: none
		sourceColumn: dv_u_data_source

		annotation SummarizationSetBy = Automatic

	column u_date_albaran
		dataType: dateTime
		formatString: General Date
		lineageTag: ad6e8a84-b416-4a69-bc56-82d152d204c1
		summarizeBy: none
		sourceColumn: u_date_albaran

		variation Variación
			isDefault
			relationship: ed1e3d22-303d-4bc6-81a6-dc7d3cd78fcf
			defaultHierarchy: LocalDateTable_64f6e106-ff79-4347-9449-8bf32a3dad41.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_date_end_contract
		dataType: dateTime
		formatString: General Date
		lineageTag: e0254f9d-551b-41e7-8877-05284288f15f
		summarizeBy: none
		sourceColumn: u_date_end_contract

		variation Variación
			isDefault
			relationship: 7dbd0c12-922f-4a99-a6ac-9b4f9de1f427
			defaultHierarchy: LocalDateTable_5ccd0343-a62c-44a6-b9b2-de59298924e5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_date_start_contract
		dataType: dateTime
		formatString: General Date
		lineageTag: a2b149bc-da82-45cb-b0c4-0d94cdc454ef
		summarizeBy: none
		sourceColumn: u_date_start_contract

		variation Variación
			isDefault
			relationship: 20c359a0-47fd-4e6d-9478-af51ee504893
			defaultHierarchy: LocalDateTable_79a697a3-57a7-4314-8d76-8f780b0f40fa.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_delivery_address
		dataType: string
		lineageTag: 13207b86-11aa-43f4-b7da-71a4a2baa098
		summarizeBy: none
		sourceColumn: u_delivery_address

		annotation SummarizationSetBy = Automatic

	column u_detail_status
		dataType: string
		lineageTag: aced056c-059f-4fb2-bce4-4e0b8b8515e2
		summarizeBy: none
		sourceColumn: u_detail_status

		annotation SummarizationSetBy = Automatic

	column dv_u_detail_status
		dataType: string
		lineageTag: 4732f909-0abf-4834-9b23-9e9b1d9bff7b
		summarizeBy: none
		sourceColumn: dv_u_detail_status

		annotation SummarizationSetBy = Automatic

	column dv_u_environment
		dataType: string
		lineageTag: 4e6e8b89-bf4c-41e1-82ee-d0a72023fdf2
		summarizeBy: none
		sourceColumn: dv_u_environment

		annotation SummarizationSetBy = Automatic

	column dv_u_functional_responsible_group
		dataType: string
		lineageTag: 92181740-5e3c-4cee-86a5-55b5a3ae8105
		summarizeBy: none
		sourceColumn: dv_u_functional_responsible_group

		annotation SummarizationSetBy = Automatic

	column u_label
		dataType: string
		lineageTag: bcf652d8-2ff0-40de-9d69-4686ee12db28
		summarizeBy: none
		sourceColumn: u_label

		annotation SummarizationSetBy = Automatic

	column u_manual_managed_by
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: af464d21-df6a-4817-8f7e-f0cb0e6004d3
		summarizeBy: none
		sourceColumn: u_manual_managed_by

		annotation SummarizationSetBy = Automatic

	column u_metal
		dataType: string
		lineageTag: 820abe3c-f25e-480f-a895-ef36fa74ab0b
		summarizeBy: none
		sourceColumn: u_metal

		annotation SummarizationSetBy = Automatic

	column dv_u_metal
		dataType: string
		lineageTag: dd3a9ad9-3c04-4922-87e3-a1dcfeadfb0a
		summarizeBy: none
		sourceColumn: dv_u_metal

		annotation SummarizationSetBy = Automatic

	column u_moebius_billable
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8e581da0-7cb9-4a24-a1f7-b5546f204bab
		summarizeBy: none
		sourceColumn: u_moebius_billable

		annotation SummarizationSetBy = Automatic

	column u_moebius_cpd
		dataType: string
		lineageTag: 71910e28-1b63-410f-9075-60eabdfdeff4
		summarizeBy: none
		sourceColumn: u_moebius_cpd

		annotation SummarizationSetBy = Automatic

	column dv_u_moebius_cpd
		dataType: string
		lineageTag: 6f2a735a-f044-44c8-8a01-35d994847782
		summarizeBy: none
		sourceColumn: dv_u_moebius_cpd

		annotation SummarizationSetBy = Automatic

	column u_moebiusdisclaimer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8517ab4e-9e9b-4bc5-b259-8d56e4194735
		summarizeBy: none
		sourceColumn: u_moebiusdisclaimer

		annotation SummarizationSetBy = Automatic

	column u_moebiussupport
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 82843018-3839-47a7-9a51-7814676dbdcc
		summarizeBy: none
		sourceColumn: u_moebiussupport

		annotation SummarizationSetBy = Automatic

	column dv_u_owner
		dataType: string
		lineageTag: c5a557db-f0b4-433d-8dc0-f36cc008c85c
		summarizeBy: none
		sourceColumn: dv_u_owner

		annotation SummarizationSetBy = Automatic

	column u_price
		dataType: double
		lineageTag: a579acf6-d49d-44bf-8b32-e7936adc85b1
		summarizeBy: sum
		sourceColumn: u_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_purchase_request_item
		dataType: string
		lineageTag: 2bc91051-5419-4b5c-9b17-6b76877b3736
		summarizeBy: none
		sourceColumn: u_purchase_request_item

		annotation SummarizationSetBy = Automatic

	column dv_u_purchase_request_item
		dataType: string
		lineageTag: 0b86d6a6-2544-475c-b318-14c0d69783ac
		summarizeBy: none
		sourceColumn: dv_u_purchase_request_item

		annotation SummarizationSetBy = Automatic

	column dv_u_responsible_tic
		dataType: string
		lineageTag: 31bb2853-578f-4d6f-9cf9-35ea10cd69f1
		summarizeBy: none
		sourceColumn: dv_u_responsible_tic

		annotation SummarizationSetBy = Automatic

	column dv_u_service
		dataType: string
		lineageTag: a6ec4566-47f9-47da-a31a-8cde85c4f476
		summarizeBy: none
		sourceColumn: dv_u_service

		annotation SummarizationSetBy = Automatic

	column dv_u_service_provider
		dataType: string
		lineageTag: 93881aae-60f8-4663-8f10-63dec8d1790d
		summarizeBy: none
		sourceColumn: dv_u_service_provider

		annotation SummarizationSetBy = Automatic

	column dv_u_service_schedule
		dataType: string
		lineageTag: f13896c3-d89a-4a2c-9040-12984cdb0ce2
		summarizeBy: none
		sourceColumn: dv_u_service_schedule

		annotation SummarizationSetBy = Automatic

	column dv_u_status
		dataType: string
		lineageTag: 5f67d85a-8282-4e54-9aba-fa0625e98ffc
		summarizeBy: none
		sourceColumn: dv_u_status

		annotation SummarizationSetBy = Automatic

	column dv_u_substatus
		dataType: string
		lineageTag: 60626a7a-f91c-4374-b6fc-2b8027bf6a4b
		summarizeBy: none
		sourceColumn: dv_u_substatus

		annotation SummarizationSetBy = Automatic

	column dv_u_type
		dataType: string
		lineageTag: cad1f95c-7bd2-4dab-9325-d5fb910e6d11
		summarizeBy: none
		sourceColumn: dv_u_type

		annotation SummarizationSetBy = Automatic

	column u_urmoebius
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d3adacd2-db35-4f36-9706-134951468b33
		summarizeBy: none
		sourceColumn: u_urmoebius

		annotation SummarizationSetBy = Automatic

	column u_zone
		dataType: string
		lineageTag: 2926e0c9-ba51-4ab1-b938-37cd79632507
		summarizeBy: none
		sourceColumn: u_zone

		annotation SummarizationSetBy = Automatic

	column dv_u_zone
		dataType: string
		lineageTag: b8a1b53d-a7ce-432a-965c-20eb911f10c6
		summarizeBy: none
		sourceColumn: dv_u_zone

		annotation SummarizationSetBy = Automatic

	column unverified
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c09a291c-2224-4ff5-9ce4-165d02dab9d4
		summarizeBy: none
		sourceColumn: unverified

		annotation SummarizationSetBy = Automatic

	column used_for
		dataType: string
		lineageTag: dc7db3e8-e57f-4d5f-be36-4707569f6d02
		summarizeBy: none
		sourceColumn: used_for

		annotation SummarizationSetBy = Automatic

	column dv_used_for
		dataType: string
		lineageTag: d5570951-7c83-4e3b-9825-1bd060574c87
		summarizeBy: none
		sourceColumn: dv_used_for

		annotation SummarizationSetBy = Automatic

	column vendor
		dataType: string
		lineageTag: 69f1f043-2256-489f-ad2c-db5fe1483967
		summarizeBy: none
		sourceColumn: vendor

		annotation SummarizationSetBy = Automatic

	column dv_vendor
		dataType: string
		lineageTag: 034eb418-621b-4848-8faa-58ee7905a202
		summarizeBy: none
		sourceColumn: dv_vendor

		annotation SummarizationSetBy = Automatic

	column version
		dataType: string
		lineageTag: 84b8c1d8-e3b1-4f8e-bae3-dce5a94207b9
		summarizeBy: none
		sourceColumn: version

		annotation SummarizationSetBy = Automatic

	column warranty_expiration
		dataType: dateTime
		formatString: General Date
		lineageTag: 7b6bc5db-1106-4111-bc1b-5973d3b4b093
		summarizeBy: none
		sourceColumn: warranty_expiration

		variation Variación
			isDefault
			relationship: f288183e-63f9-4146-9db5-e08f57d4ed6d
			defaultHierarchy: LocalDateTable_37962f22-e4eb-4106-9fb1-568b47671f64.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column x_avne2_addm_to_se_td_key
		dataType: string
		lineageTag: 78b9e1a8-718f-4a28-9d38-551d3ac5f2d2
		summarizeBy: none
		sourceColumn: x_avne2_addm_to_se_td_key

		annotation SummarizationSetBy = Automatic

	column x_tsirm_tio_cmdb_asset_attributes
		dataType: string
		lineageTag: 70ef2bbd-c721-42d2-ace5-7ff5610c260e
		summarizeBy: none
		sourceColumn: x_tsirm_tio_cmdb_asset_attributes

		annotation SummarizationSetBy = Automatic

	column dv_x_tsirm_tio_cmdb_asset_attributes
		dataType: string
		lineageTag: 6709ca10-2ad7-4e03-8a48-66a6f0ef2c59
		summarizeBy: none
		sourceColumn: dv_x_tsirm_tio_cmdb_asset_attributes

		annotation SummarizationSetBy = Automatic

	partition 'SERV_NOW cmdb_ci_appl-ca625e63-9b42-4141-b677-3097500ff0c5' = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "DWH"),
				    SERV_NOW_cmdb_ci_appl = Origen{[Schema="SERV_NOW",Item="cmdb_ci_appl"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_cmdb_ci_appl,{"asset", "dv_asset", "asset_tag", "assigned", "assigned_to", "dv_assigned_to", "assignment_group", "dv_assignment_group", "attestation_score", "attested", "attested_by", "dv_attested_by", "attested_date", "attributes", "can_print", "category", "dv_category", "change_control", "dv_change_control", "checked_in", "checked_out", "cl_port", "comments", "company", "dv_company", "config_directory", "config_file", "correlation_id", "cost", "cost_cc", "dv_cost_cc", "cost_center", "dv_cost_center", "delivery_date", "department", "dv_department", "discovery_source", "dv_discovery_source", "dns_domain", "due", "due_in", "dv_due_in", "duplicate_of", "dv_duplicate_of", "edition", "environment", "dv_environment", "fault_count", "first_discovered", "fqdn", "gl_account", "install_date", "install_directory", "install_status", "dv_install_status", "invoice_number", "ip_address", "is_clustered", "justification", "last_discovered", "lease_id", "life_cycle_stage", "dv_life_cycle_stage", "life_cycle_stage_status", "dv_life_cycle_stage_status", "location", "dv_location", "mac_address", "maintenance_schedule", "dv_maintenance_schedule", "managed_by", "dv_managed_by", "managed_by_group", "dv_managed_by_group", "managed_domain", "manufacturer", "dv_manufacturer", "model_id", "dv_model_id", "model_number", "monitor", "name", "operational_status", "dv_operational_status", "order_date", "owned_by", "dv_owned_by", "pid", "po_number", "purchase_date", "rp_command_hash", "rp_key_parameters_hash", "running_process_command", "running_process_key_parameters", "schedule", "dv_schedule", "serial_number", "short_description", "skip_sync", "software_install", "dv_software_install", "start_date", "subcategory", "dv_subcategory", "support_group", "dv_support_group", "supported_by", "dv_supported_by", "sys_class_name", "dv_sys_class_name", "sys_class_path", "sys_created_by", "sys_created_on", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "tcp_port", "u_albaran", "u_approval_for_change_request", "u_availability", "dv_u_availability", "u_backup_frequency", "dv_u_backup_frequency", "u_catalog"}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas quitadas", each ([dv_u_catalog] = "Energía") and ([dv_u_platform] = "RPA"))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

