table pm_project
	lineageTag: abac282c-d012-42f5-9010-db14a7fd0553

	column business_applications
		dataType: string
		lineageTag: 8d8ad439-4841-4500-aea6-aeac68874846
		summarizeBy: none
		sourceColumn: business_applications

		annotation SummarizationSetBy = Automatic

	column capex_cost
		dataType: double
		lineageTag: a843d565-0d94-4e00-a69a-6121439321e7
		summarizeBy: sum
		sourceColumn: capex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 2c7d9c42-888e-42cf-a754-8d5b5cb511b1
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: f8941bd1-83d2-4341-a4c3-c3a696f225a2
			defaultHierarchy: LocalDateTable_6b48bdab-e11f-4626-a453-25d97e44348c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci_business_app
		dataType: string
		lineageTag: 2219bbad-1076-41ed-b398-def068bf18c2
		summarizeBy: none
		sourceColumn: dv_cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column demand
		dataType: string
		lineageTag: ec71d939-8f34-4e05-99d6-a41cfaf62419
		summarizeBy: none
		sourceColumn: demand

		annotation SummarizationSetBy = Automatic

	column dv_demand
		dataType: string
		lineageTag: bfc55c79-4376-474e-b58b-54267c5d5397
		summarizeBy: none
		sourceColumn: dv_demand

		annotation SummarizationSetBy = Automatic

	column dv_department
		dataType: string
		lineageTag: 8076ed62-9545-4ae9-b9ca-65a21b1ed87b
		summarizeBy: none
		sourceColumn: dv_department

		annotation SummarizationSetBy = Automatic

	column dependency
		dataType: string
		lineageTag: 52fe602c-975f-4d42-87ef-03a4b3737d6d
		summarizeBy: none
		sourceColumn: dependency

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 5f5430ba-e5d5-4f0c-ae2e-1a4c15f193f7
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column discount_rate
		dataType: double
		lineageTag: 37e257ba-1650-4379-a9da-6f85bd2712d2
		summarizeBy: sum
		sourceColumn: discount_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column due_date
		dataType: dateTime
		formatString: General Date
		lineageTag: db6effcd-39fc-4a50-8162-4ea4064c8d2e
		summarizeBy: none
		sourceColumn: due_date

		variation Variación
			isDefault
			relationship: 9d180262-a9ea-4cc8-b7e8-fc364b1b5f21
			defaultHierarchy: LocalDateTable_c032fa77-c3d4-4110-a402-0dc925e79536.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column duration
		dataType: dateTime
		formatString: General Date
		lineageTag: a14064dc-5a3b-434b-885e-2e8e9fc351bb
		summarizeBy: none
		sourceColumn: duration

		variation Variación
			isDefault
			relationship: 6be782bc-9acd-409f-9f2c-12043c279758
			defaultHierarchy: LocalDateTable_ee656bdd-d738-4893-ae67-a30e1a64c931.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_duration
		dataType: string
		lineageTag: 344d6721-ad1d-41cd-9a4a-02c401eeb22b
		summarizeBy: none
		sourceColumn: dv_duration

		annotation SummarizationSetBy = Automatic

	column dv_effort
		dataType: string
		lineageTag: a09fe5a6-d56f-4b7c-8948-2d2ef873df40
		summarizeBy: none
		sourceColumn: dv_effort

		annotation SummarizationSetBy = Automatic

	column end
		dataType: dateTime
		formatString: General Date
		lineageTag: 1f36c10e-194b-4e34-811e-45c9acad9ea9
		summarizeBy: none
		sourceColumn: end

		variation Variación
			isDefault
			relationship: 2541a6df-542d-4708-92a4-226b1e29ab52
			defaultHierarchy: LocalDateTable_551578ad-b76c-4959-b721-639fcca92fbe.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0258bd67-88dd-4d3c-925b-de97a811ba03
		summarizeBy: none
		sourceColumn: end_date

		variation Variación
			isDefault
			relationship: a1f5ad10-2578-4536-8c1c-fdf4b4d34d42
			defaultHierarchy: LocalDateTable_3bab8657-96f8-49eb-99eb-a979b1676651.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column execution_type
		dataType: string
		lineageTag: 98ac69d4-2344-4be8-a671-5715369be630
		summarizeBy: none
		sourceColumn: execution_type

		annotation SummarizationSetBy = Automatic

	column dv_execution_type
		dataType: string
		lineageTag: d746b455-c27c-465a-b3de-12451e9a0803
		summarizeBy: none
		sourceColumn: dv_execution_type

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: 5d07d7e8-f79b-43d2-8df1-4f376fbca7e2
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: 93b63d13-eb2f-4013-b3f8-c6405103f6f3
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 7a7dda01-6e2c-424a-86e1-c1c8a86dd781
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: cc3ad2fb-cb4d-468d-9d2c-868c0580ec65
			defaultHierarchy: LocalDateTable_04c1217d-5792-4ff0-a33a-b68fed369240.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column opex_cost
		dataType: double
		lineageTag: e42c831f-fbbb-4254-a1b2-203f048d21af
		summarizeBy: sum
		sourceColumn: opex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dv_parent
		dataType: string
		lineageTag: 39e5d192-a8e4-45a9-b88d-f797f1946c4b
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column percent_complete
		dataType: double
		lineageTag: c9765a95-8979-46e7-adbe-a1c2cc17d518
		summarizeBy: sum
		sourceColumn: percent_complete

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dv_phase
		dataType: string
		lineageTag: 06d8ee2e-c38e-4cda-9d95-86ad7533cb86
		summarizeBy: none
		sourceColumn: dv_phase

		annotation SummarizationSetBy = Automatic

	column dv_phase_type
		dataType: string
		lineageTag: 986e1a15-bafb-4053-bc5c-cc4de99d52d7
		summarizeBy: none
		sourceColumn: dv_phase_type

		annotation SummarizationSetBy = Automatic

	column dv_primary_portfolio
		dataType: string
		lineageTag: 77e9d23d-1368-49b2-a91f-dc51fa8b76fa
		summarizeBy: none
		sourceColumn: dv_primary_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: c14509c5-2822-4aca-a297-51d91ef9be35
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column dv_risk
		dataType: string
		lineageTag: aa935b13-6013-42d0-967c-6a5dda1a6db5
		summarizeBy: none
		sourceColumn: dv_risk

		annotation SummarizationSetBy = Automatic

	column risk_cost
		dataType: double
		lineageTag: f083a644-6476-4e98-9b47-5ed6b27ff57f
		summarizeBy: sum
		sourceColumn: risk_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column schedule_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7e6e51fe-cfaa-48c8-ab12-42bc23529b2b
		summarizeBy: none
		sourceColumn: schedule_end_date

		variation Variación
			isDefault
			relationship: ff58d434-fecf-455f-8059-36c8e46f324d
			defaultHierarchy: LocalDateTable_3dc4674d-8f03-4ae9-8ce3-45fb859c58f4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column schedule_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: e4980f48-8fe9-4fc1-94a3-73144bd14b32
		summarizeBy: none
		sourceColumn: schedule_start_date

		variation Variación
			isDefault
			relationship: 1ea3e0fd-60c0-42cb-862a-c9bd3bc693ea
			defaultHierarchy: LocalDateTable_2486e1b9-6a05-46cd-94a5-a5c3d7b01ab9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: a47956ad-437c-44c7-8caa-58cc7f70c26c
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column start
		dataType: dateTime
		formatString: General Date
		lineageTag: cdbce660-2eba-43d0-baa3-f5c1fb6b5e67
		summarizeBy: none
		sourceColumn: start

		variation Variación
			isDefault
			relationship: 74ca7f13-1bd6-4529-8846-b4490dd62e05
			defaultHierarchy: LocalDateTable_7ba40933-b110-46a0-a370-6545f336af02.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 7f12123a-186a-44e6-8a38-93a1c0bca51d
		summarizeBy: none
		sourceColumn: start_date

		variation Variación
			isDefault
			relationship: 3db1acf0-65db-403f-9c84-2e68a0384baa
			defaultHierarchy: LocalDateTable_378cc2f1-8ab0-4531-a794-eac2e69220da.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: eea20911-1f04-4ffe-acd6-dff1f17c81bf
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column dv_status
		dataType: string
		lineageTag: c73fcf51-a5a1-4e9d-afa4-ceb4be2f487c
		summarizeBy: none
		sourceColumn: dv_status

		annotation SummarizationSetBy = Automatic

	column dv_sub_tree_root
		dataType: string
		lineageTag: 8d2657e0-0ca1-49fd-8f67-6d5fdb284256
		summarizeBy: none
		sourceColumn: dv_sub_tree_root

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: b40ca4cf-9650-4886-a0bb-5619daf068bc
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column task
		dataType: string
		lineageTag: 05d1ea60-0f9e-4952-ad0e-ce9015e75369
		summarizeBy: none
		sourceColumn: task

		annotation SummarizationSetBy = Automatic

	column task_effective_number
		dataType: string
		lineageTag: f905e8e8-fafb-4954-aa7f-9dfc34cc63ad
		summarizeBy: none
		sourceColumn: task_effective_number

		annotation SummarizationSetBy = Automatic

	column top_task
		dataType: string
		lineageTag: 5ef3cc00-ce04-45ec-aa76-44da2d2fbcdc
		summarizeBy: none
		sourceColumn: top_task

		annotation SummarizationSetBy = Automatic

	column dv_top_task
		dataType: string
		lineageTag: eab8e477-f5dc-4239-a3cc-b60be55d2cd1
		summarizeBy: none
		sourceColumn: dv_top_task

		annotation SummarizationSetBy = Automatic

	column dv_urgency
		dataType: string
		lineageTag: 634e6a6e-89ea-4932-8747-36549c5f933a
		summarizeBy: none
		sourceColumn: dv_urgency

		annotation SummarizationSetBy = Automatic

	column work_end
		dataType: dateTime
		formatString: General Date
		lineageTag: bc1950a6-97e3-4959-8eca-9e129b05fecf
		summarizeBy: none
		sourceColumn: work_end

		variation Variación
			isDefault
			relationship: b4ca9a86-b4d9-4222-a8b2-e2df5198d48a
			defaultHierarchy: LocalDateTable_7dfa8156-057e-4a7c-bf4f-c97f2140d6b5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column work_start
		dataType: dateTime
		formatString: General Date
		lineageTag: c72b48ec-ba7d-41f9-b221-7964d46fa4ad
		summarizeBy: none
		sourceColumn: work_start

		variation Variación
			isDefault
			relationship: c7eb9172-c706-43b3-8e05-c6b640d7b9bf
			defaultHierarchy: LocalDateTable_e856bb2d-2cca-43d9-b493-e647c94450fa.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column approval_set
		dataType: dateTime
		formatString: General Date
		lineageTag: 45a05a46-bc39-4022-982e-a09ce614c34b
		summarizeBy: none
		sourceColumn: approval_set

		variation Variación
			isDefault
			relationship: 73094c6e-2e90-4593-8d6b-d9f4f210146c
			defaultHierarchy: LocalDateTable_3da61c1d-87e5-4a4f-903a-fce195827a12.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column attr_based_planning
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 90159e75-0875-438a-adea-67ed228e5099
		summarizeBy: none
		sourceColumn: attr_based_planning

		annotation SummarizationSetBy = Automatic

	column auto_save
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8bd4efe9-f221-4e22-8d66-bddfabf75a1e
		summarizeBy: none
		sourceColumn: auto_save

		annotation SummarizationSetBy = Automatic

	column contract
		dataType: string
		lineageTag: 1f494f58-2228-466d-9fe8-ac3fd4707d49
		summarizeBy: none
		sourceColumn: contract

		annotation SummarizationSetBy = Automatic

	column dv_contract
		dataType: string
		lineageTag: fc5b5f55-b601-4c55-aaf5-392346216c31
		summarizeBy: none
		sourceColumn: dv_contract

		annotation SummarizationSetBy = Automatic

	column dv_expense_type
		dataType: string
		lineageTag: bed18a24-962d-424e-9063-3683ccdca825
		summarizeBy: none
		sourceColumn: dv_expense_type

		annotation SummarizationSetBy = Automatic

	column dv_model_id
		dataType: string
		lineageTag: a6e2982b-86a9-4ecc-a60a-94971a6f0618
		summarizeBy: none
		sourceColumn: dv_model_id

		annotation SummarizationSetBy = Automatic

	column dv_software_model
		dataType: string
		lineageTag: cbc08c01-0322-4c76-95ee-e89be1f77fb2
		summarizeBy: none
		sourceColumn: dv_software_model

		annotation SummarizationSetBy = Automatic

	column dv_u_devops_manager
		dataType: string
		lineageTag: da7264df-814d-4d20-8ea2-1cca0f867904
		summarizeBy: none
		sourceColumn: dv_u_devops_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_pmo_manager
		dataType: string
		lineageTag: bd7a844b-ccf5-4d98-b93d-69b5082b0be4
		summarizeBy: none
		sourceColumn: dv_u_pmo_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_qa_manager
		dataType: string
		lineageTag: 656be220-b6cb-4553-96b0-ddd0b28ba014
		summarizeBy: none
		sourceColumn: dv_u_qa_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_rfp_phases
		dataType: string
		lineageTag: dbd91093-3a82-4ed4-99ef-8711d6a013d8
		summarizeBy: none
		sourceColumn: dv_u_rfp_phases

		annotation SummarizationSetBy = Automatic

	column expense_type
		dataType: string
		lineageTag: b433e568-d252-45d1-8ec5-0991c159f86e
		summarizeBy: none
		sourceColumn: expense_type

		annotation SummarizationSetBy = Automatic

	column group_resource_assignee
		dataType: string
		lineageTag: 15f7d6b2-839c-4b48-905f-8b6aca7e21b2
		summarizeBy: none
		sourceColumn: group_resource_assignee

		annotation SummarizationSetBy = Automatic

	column model_id
		dataType: string
		lineageTag: cc48883e-2dae-4705-a4f8-7b6947b8cb87
		summarizeBy: none
		sourceColumn: model_id

		annotation SummarizationSetBy = Automatic

	column resource_assignee
		dataType: string
		lineageTag: fe9c26b6-6fac-4e51-bf36-e847ffb29ebf
		summarizeBy: none
		sourceColumn: resource_assignee

		annotation SummarizationSetBy = Automatic

	column software_model
		dataType: string
		lineageTag: 1c052f36-19b4-47f5-9026-263871733fcd
		summarizeBy: none
		sourceColumn: software_model

		annotation SummarizationSetBy = Automatic

	column u_commented
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e8aaaf41-f3d0-401e-9412-db7d0f1dcdb3
		summarizeBy: none
		sourceColumn: u_commented

		annotation SummarizationSetBy = Automatic

	column u_devops_manager
		dataType: string
		lineageTag: d2d6bc5f-8b65-451c-8f38-bad56709b5d1
		summarizeBy: none
		sourceColumn: u_devops_manager

		annotation SummarizationSetBy = Automatic

	column u_impacted_applications
		dataType: string
		lineageTag: fa33c2d7-0589-4e5f-ba69-66a556bc400a
		summarizeBy: none
		sourceColumn: u_impacted_applications

		annotation SummarizationSetBy = Automatic

	column u_operational_committee_comment
		dataType: string
		lineageTag: bc79d61c-13b2-4953-91ef-402d28d4cbb4
		summarizeBy: none
		sourceColumn: u_operational_committee_comment

		annotation SummarizationSetBy = Automatic

	column u_project_typology
		dataType: string
		lineageTag: e842b93a-35ec-48df-a04e-818ecc52dc4b
		summarizeBy: none
		sourceColumn: u_project_typology

		annotation SummarizationSetBy = Automatic

	column u_qa_manager
		dataType: string
		lineageTag: e380f16a-a697-4d11-8aab-c0c1d268af5e
		summarizeBy: none
		sourceColumn: u_qa_manager

		annotation SummarizationSetBy = Automatic

	column u_relevant_project_for_cio
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8aa6f1df-1c9a-4ebc-9f4e-f2806b3acb14
		summarizeBy: none
		sourceColumn: u_relevant_project_for_cio

		annotation SummarizationSetBy = Automatic

	column u_rfp_phases
		dataType: string
		lineageTag: 893eae0f-254b-48c6-a0df-08d966505169
		summarizeBy: none
		sourceColumn: u_rfp_phases

		annotation SummarizationSetBy = Automatic

	column u_percent_complete_estimated
		dataType: double
		lineageTag: e2cbd41c-6542-4327-be89-ca5b52463c2d
		summarizeBy: sum
		sourceColumn: u_percent_complete_estimated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition pm_project = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("QECCDWH.acciona.int,60001"),
				    DWH = Origen{[Name="DWH"]}[Data],
				    SERV_NOW_pm_project = DWH{[Schema="SERV_NOW",Item="pm_project"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_pm_project,{"active", "activity_due", "actual_benefits", "additional_assignee_list", "allow_dates_outside_schedule", "approval", "dv_approval", "approval_history", "approved_end_date", "approved_start_date", "assigned_to", "dv_assigned_to", "assignment_group", "dv_assignment_group", "assumptions", "backlog_definition", "dv_backlog_definition", "barriers", "benefits", "budget_cost", "business_capabilities", "business_case", "business_duration", "dv_business_duration", "business_service", "dv_business_service", "business_unit", "dv_business_unit", "calculation_type", "dv_calculation_type", "calendar_duration", "dv_calendar_duration", "capex_estimate_to_completion", "capex_forecast_cost", "close_notes", "closed_by", "dv_closed_by", "cmdb_ci", "dv_cmdb_ci", "cmdb_ci_business_app", "comments", "comments_and_work_notes", "company", "dv_company", "constraint_date", "contact_type", "dv_contact_type", "correlation_display", "correlation_id", "cost", "critical_path", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "department", "effort", "enablers", "end_date_derived_from", "dv_end_date_derived_from", "escalation", "dv_escalation", "estimate_to_completion", "expected_start", "follow_up", "forecast_cost", "goal", "dv_goal", "goals", "group_list", "has_conflict", "impact", "impacted_business_units", "in_scope", "investment_class", "dv_investment_class", "investment_type", "dv_investment_type", "irr_value", "key_milestone", "knowledge", "level", "location", "dv_location", "made_sla", "marked_for_delete", "milestone", "mpp_task_id", "npv_value", "opened_by", "dv_opened_by", "opex_estimate_to_completion", "opex_forecast_cost", "order", "orig_sys_id", "dv_orig_sys_id", "orig_top_task_id", "dv_orig_top_task_id", "out_of_scope", "override_status", "parent", "phase", "phase_type", "primary_portfolio", "primary_program", "dv_primary_program", "priority", "project_manager", "dv_project_manager", "project_schedule_date_format", "dv_project_schedule_date_format", "project_type", "dv_project_type", "rate_model", "dv_rate_model", "reassignment_count", "rejection_goto", "dv_rejection_goto", "relation_applied", "dv_relation_applied", "remaining_duration", "dv_remaining_duration", "remaining_effort", "dv_remaining_effort", "resource_allocated_cost", "resource_planned_cost", "resources_from_resource_plan", "risk", "risk_of_not_performing", "risk_of_performing", "roi", "rollup", "route_reason", "dv_route_reason", "run_calc_brs", "schedule", "dv_schedule", "score", "score_risk", "dv_score_risk", "score_size", "dv_score_size", "score_value", "dv_score_value", "service_offering", "dv_service_offering", "shadow", "show_on_program_status_report", "skills", "sla_due", "start_date_derived_from", "dv_start_date_derived_from", "state", "status", "strategic_objectives", "sub_tree_root", "sys_class_name", "dv_sys_class_name", "sys_created_by", "sys_created_on", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "task_for", "dv_task_for", "time_card_at_top_task", "time_card_preference", "dv_time_card_preference", "time_component_from_planned", "time_constraint", "dv_time_constraint", "time_worked", "dv_time_worked", "time_zone", "title", "top_portfolio", "dv_top_portfolio", "top_program", "dv_top_program", "u_acciona_priority", "u_affected_portfolios", "u_ambito_global", "u_benefit_check", "u_benefits", "u_business_line", "dv_u_business_line", "u_catalog", "dv_u_catalog", "u_changes", "u_changes_comments", "u_conditions_restrictions", "u_cost_comments", "u_costs", "u_current_situation", "u_deliverables", "u_deliverables_comments", "u_demand_type_description", "u_department", "dv_u_department", "u_dependencies", "u_deviation_in_costs", "u_deviation_in_duration", "u_digital_transformation", "u_eficiency_using_rrhh", "u_end_date_deviation", "u_external_vendor", "dv_u_external_vendor", "u_id_plan", "u_impacted_companies", "u_impacted_countries", "u_incidents", "u_incidents_comments", "u_indicator_1", "u_lessons_learned", "u_live_changes", "u_live_risks", "u_metal", "dv_u_metal", "u_monitoring_indicators", "u_outsourcing", "u_payroll_area", "dv_u_payroll_area", "u_phone", "u_planned_demand", "dv_u_planned_demand", "u_planned_resource_plan_effort", "u_previous_groups", "u_problems", "u_progress", "u_project_impact", "u_project_monitoring", "u_project_phase", "dv_u_project_phase", "u_project_type", "dv_u_project_type", "u_reasons_for_delay_reject", "dv_u_reasons_for_delay_reject", "u_ref_country", "dv_u_ref_country", "u_relevant", "u_responded", "u_risks", "u_risks_comments", "u_run", "u_run_description", "u_schedule", "u_schedule_comments", "u_size", "dv_u_size", "u_state_date", "u_suggestions_to_improve", "u_sum_planned_hours", "u_sum_time_cards", "u_targets", "u_tic_unit", "dv_u_tic_unit", "u_url", "u_version", "u_volume_of_impacted_users", "universal_request", "dv_universal_request", "update_actual_effort_from_time_card", "dv_update_actual_effort_from_time_card", "update_score_on_value_change", "dv_update_score_on_value_change", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "urgency", "user_input", "value", "variables", "version", "watch_list", "wbs", "wbs_order", "wf_activity", "dv_wf_activity", "work_cost", "work_duration", "dv_work_duration", "work_effort", "dv_work_effort", "work_notes", "work_notes_list", "x_29185_external_f_total_financed", "dv_u_project_typology", "u_restrictions", "u_completion_criteria", "u_pmo_manager", "html_description"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

