table Ev3-Mantener
	lineageTag: 84855ccd-2bd2-449c-adac-126c211949d7

	measure '_% Percent_complete_SIN_ERROR_Ev3' = (AVERAGE('Ev3-Mantener'[percent_complete])/100)+0
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 3992cf38-00af-4dd6-8e81-5aa449215bf6

	measure '_% comparativo entre teorico y real_MEDIDA_SIN_ERROR_Ev3' = (AVERAGE('Ev3-Mantener'[% comparativo entre teorico y real]))+0
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 4ac69f0b-1a17-433c-9e5f-985308b9f3c7

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0b02d8f7-c81e-43fa-9b55-3908d4e39ebe
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column actual_benefits
		dataType: double
		lineageTag: fd0477e3-91dd-465c-894b-55b701b21abe
		summarizeBy: sum
		sourceColumn: actual_benefits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column additional_assignee_list
		dataType: string
		lineageTag: 8f992fd1-479d-4758-979d-7b38ca6dbc3c
		summarizeBy: none
		sourceColumn: additional_assignee_list

		annotation SummarizationSetBy = Automatic

	column allow_dates_outside_schedule
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cc7d9b9d-b90d-4a49-9dc4-3a9796c73c90
		summarizeBy: none
		sourceColumn: allow_dates_outside_schedule

		annotation SummarizationSetBy = Automatic

	column approval
		dataType: string
		lineageTag: 1d8fdc4d-3664-4933-ae9c-ef1cc3a9e124
		summarizeBy: none
		sourceColumn: approval

		annotation SummarizationSetBy = Automatic

	column dv_approval
		dataType: string
		lineageTag: 3fe3378a-7388-40e7-b71f-809ea30f9699
		summarizeBy: none
		sourceColumn: dv_approval

		annotation SummarizationSetBy = Automatic

	column assigned_to
		dataType: string
		lineageTag: 2e90a2cf-c20d-4338-90e9-379258107139
		summarizeBy: none
		sourceColumn: assigned_to

		annotation SummarizationSetBy = Automatic

	column dv_assigned_to
		dataType: string
		lineageTag: abf14d87-30a7-4ac2-b90e-a289f10845ef
		summarizeBy: none
		sourceColumn: dv_assigned_to

		annotation SummarizationSetBy = Automatic

	column assignment_group
		dataType: string
		lineageTag: f528ca4b-5943-4489-84f3-67774637f0f6
		summarizeBy: none
		sourceColumn: assignment_group

		annotation SummarizationSetBy = Automatic

	column dv_assignment_group
		dataType: string
		lineageTag: 63f2c6d6-16f8-4acb-a21c-8eb8a5f1a22b
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column benefits
		dataType: double
		lineageTag: 4d080e09-9619-44ca-9d87-734c2622b680
		summarizeBy: sum
		sourceColumn: benefits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column budget_cost
		dataType: double
		lineageTag: 016ba909-4728-45f6-b5af-f9b5b1be90c5
		summarizeBy: sum
		sourceColumn: budget_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column calculation_type
		dataType: string
		lineageTag: 8a16e869-fa04-4e63-b4ad-5c1e55c53d4d
		summarizeBy: none
		sourceColumn: calculation_type

		annotation SummarizationSetBy = Automatic

	column dv_calculation_type
		dataType: string
		lineageTag: 21a1ea00-29bb-4df6-b5d6-5b6fde3c4c28
		summarizeBy: none
		sourceColumn: dv_calculation_type

		annotation SummarizationSetBy = Automatic

	column capex_cost
		dataType: double
		lineageTag: 96b9b093-4d7f-4bd4-90bb-1bcc981928aa
		summarizeBy: sum
		sourceColumn: capex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 47449874-26a5-422d-9150-5ca4db79b6b2
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: e5a635bb-e8d5-4cc8-9144-82642dd1728e
			defaultHierarchy: LocalDateTable_d4eb7c57-1a6c-44df-ad0a-5fa19fc70955.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column closed_by
		dataType: string
		lineageTag: a5619ad5-c037-43d7-83a5-a1028e75d7ae
		summarizeBy: none
		sourceColumn: closed_by

		annotation SummarizationSetBy = Automatic

	column dv_closed_by
		dataType: string
		lineageTag: 52dc1950-9aa3-4f15-a9d0-3a25c86248fa
		summarizeBy: none
		sourceColumn: dv_closed_by

		annotation SummarizationSetBy = Automatic

	column correlation_id
		dataType: string
		lineageTag: 5a843831-838c-4633-9e33-76066c9e93d5
		summarizeBy: none
		sourceColumn: correlation_id

		annotation SummarizationSetBy = Automatic

	column cost
		dataType: double
		lineageTag: 19d01174-6581-474e-9a54-8e871a96dfe4
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column critical_path
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cf623ead-c757-4fdb-a066-4becc8534fc6
		summarizeBy: none
		sourceColumn: critical_path

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: c2f32b3f-fbca-4600-b939-5028b87f3f91
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 805be4b2-1ac4-4528-b241-3c4567481b8e
		summarizeBy: none
		sourceColumn: duration

		variation Variación
			isDefault
			relationship: bbe137c3-cc9c-41ef-9d3b-592ed55c8ced
			defaultHierarchy: LocalDateTable_ff2bc327-6665-47bd-959d-5132b9007360.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_duration
		dataType: string
		lineageTag: a11b5e9a-ff44-427a-80b7-df8f09fc2673
		summarizeBy: none
		sourceColumn: dv_duration

		annotation SummarizationSetBy = Automatic

	column effort
		dataType: dateTime
		formatString: General Date
		lineageTag: 20be9f8c-f42f-46f4-a24b-1b66bae8ea0b
		summarizeBy: none
		sourceColumn: effort

		variation Variación
			isDefault
			relationship: 3dfbf2be-f779-41e5-ba99-e87bc7b3bf25
			defaultHierarchy: LocalDateTable_49889ab1-a318-4dcd-b81e-bc26942b19c3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_effort
		dataType: string
		lineageTag: 12bcd18a-c094-4ab9-a547-a6d08e3ee894
		summarizeBy: none
		sourceColumn: dv_effort

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 522534c7-62b9-429a-9ecc-867f986d2026
		summarizeBy: none
		sourceColumn: end_date

		variation Variación
			isDefault
			relationship: b5e4eba8-cbaf-4e45-b8a6-e99a80dcffd1
			defaultHierarchy: LocalDateTable_8085f1e2-71b1-4659-a5c2-c123835b7b35.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column escalation
		dataType: int64
		formatString: 0
		lineageTag: 58e66813-f09f-41b9-94ca-cbcc97f70304
		summarizeBy: sum
		sourceColumn: escalation

		annotation SummarizationSetBy = Automatic

	column dv_escalation
		dataType: string
		lineageTag: 19daf6b8-f469-403e-97e4-830d1ebeca6d
		summarizeBy: none
		sourceColumn: dv_escalation

		annotation SummarizationSetBy = Automatic

	column group_list
		dataType: string
		lineageTag: 68192ab2-142c-43ad-b54c-0f39b03a1a41
		summarizeBy: none
		sourceColumn: group_list

		annotation SummarizationSetBy = Automatic

	column has_conflict
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 99bc0bf7-5041-408b-bf7e-b5f20e05d207
		summarizeBy: none
		sourceColumn: has_conflict

		annotation SummarizationSetBy = Automatic

	column impact
		dataType: int64
		formatString: 0
		lineageTag: 01b1f7fe-cd55-4155-8c50-3c7999c25400
		summarizeBy: sum
		sourceColumn: impact

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: 2724d10a-d600-41d1-b67f-6125e6afb597
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column key_milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 24efeb1b-d818-46bd-ae10-54650713886f
		summarizeBy: none
		sourceColumn: key_milestone

		annotation SummarizationSetBy = Automatic

	column knowledge
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: de9f441b-4dc8-451f-95f8-e3c8b7fb01b9
		summarizeBy: none
		sourceColumn: knowledge

		annotation SummarizationSetBy = Automatic

	column level
		dataType: int64
		formatString: 0
		lineageTag: bd687ca7-0ddd-4de3-8893-eafaa8124873
		summarizeBy: sum
		sourceColumn: level

		annotation SummarizationSetBy = Automatic

	column made_sla
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d2414a82-4833-41b3-89ed-07832c14cfac
		summarizeBy: none
		sourceColumn: made_sla

		annotation SummarizationSetBy = Automatic

	column milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 55cb27a9-26e6-430e-84e2-6d55b04a14d8
		summarizeBy: none
		sourceColumn: milestone

		annotation SummarizationSetBy = Automatic

	column mpp_task_id
		dataType: int64
		formatString: 0
		lineageTag: c0c78f03-29fe-4a02-9f6a-21e14986facb
		summarizeBy: sum
		sourceColumn: mpp_task_id

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: 118183ca-d612-46e0-be5f-c5e9d96c209b
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 0c33a692-f942-44bd-81c6-134527ad71f0
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: e2250848-3a0b-491d-b157-f7fb49ac7105
			defaultHierarchy: LocalDateTable_ad639d9c-e6e6-4414-a5ad-cda8fa1229a3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column opened_by
		dataType: string
		lineageTag: 8dc2d844-61de-4bdf-a842-64acdd690db7
		summarizeBy: none
		sourceColumn: opened_by

		annotation SummarizationSetBy = Automatic

	column dv_opened_by
		dataType: string
		lineageTag: 7b77a30e-9a0b-4e2a-ac00-bfcbf0520a79
		summarizeBy: none
		sourceColumn: dv_opened_by

		annotation SummarizationSetBy = Automatic

	column opex_cost
		dataType: double
		lineageTag: 9ad62ed5-95be-4193-9f48-764fc1f218da
		summarizeBy: sum
		sourceColumn: opex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order
		dataType: int64
		formatString: 0
		lineageTag: e3af1f80-2622-45a4-a183-5c323a6eaaab
		summarizeBy: sum
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: 99b5f697-a403-4847-80a4-261ba576baa6
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: 36cf212d-b08e-42b3-8c1b-4774c1dfe98e
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column percent_complete
		dataType: double
		lineageTag: a3f5b9b5-2889-44b8-8a40-008ac204d061
		summarizeBy: sum
		sourceColumn: percent_complete

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column phase_type
		dataType: string
		lineageTag: 14bb2422-341c-4599-89c8-624e2ae16036
		summarizeBy: none
		sourceColumn: phase_type

		annotation SummarizationSetBy = Automatic

	column dv_phase_type
		dataType: string
		lineageTag: 1c71ccb1-bb0f-47df-9e5a-97176c2b84e1
		summarizeBy: none
		sourceColumn: dv_phase_type

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: int64
		formatString: 0
		lineageTag: e8f739f3-48cc-4338-b8b9-d0350663dc6f
		summarizeBy: sum
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: 518f9521-49c5-4557-bcb4-4fdcb0222648
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column reassignment_count
		dataType: int64
		formatString: 0
		lineageTag: 036a687f-815a-4579-8355-96267aca2e84
		summarizeBy: sum
		sourceColumn: reassignment_count

		annotation SummarizationSetBy = Automatic

	column remaining_effort
		dataType: dateTime
		formatString: General Date
		lineageTag: 86d76c5f-a1e0-4be9-a17a-52782077c484
		summarizeBy: none
		sourceColumn: remaining_effort

		variation Variación
			isDefault
			relationship: 5261adf2-8212-4008-ac71-ee83bb02c14f
			defaultHierarchy: LocalDateTable_07defce9-6e99-4755-9dc8-92a3ed7b94ea.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_remaining_effort
		dataType: string
		lineageTag: ef2961f3-5cd6-41df-ba14-7ca1b69239d5
		summarizeBy: none
		sourceColumn: dv_remaining_effort

		annotation SummarizationSetBy = Automatic

	column resource_allocated_cost
		dataType: double
		lineageTag: 5ffee788-c217-4639-94c5-0ff202170f17
		summarizeBy: sum
		sourceColumn: resource_allocated_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column resource_planned_cost
		dataType: double
		lineageTag: 38956c84-86c4-41c0-9a43-3f72f326f70c
		summarizeBy: sum
		sourceColumn: resource_planned_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rollup
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 84b0850f-dfc5-4587-93c1-a5cd0a08c2f7
		summarizeBy: none
		sourceColumn: rollup

		annotation SummarizationSetBy = Automatic

	column schedule_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8a378453-1897-4e36-865b-30735622a9e5
		summarizeBy: none
		sourceColumn: schedule_end_date

		variation Variación
			isDefault
			relationship: 4a22f565-6f35-4bab-aac0-10cea6bef5c6
			defaultHierarchy: LocalDateTable_979b6cac-1fd0-4eb3-bcee-40f3be78abf6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column schedule_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9788dbf4-beb6-40f7-9d2a-c47417621cdf
		summarizeBy: none
		sourceColumn: schedule_start_date

		variation Variación
			isDefault
			relationship: 0a080a42-fb4d-4649-bc9b-544736dd5ac2
			defaultHierarchy: LocalDateTable_fccaf3e9-67e1-4df6-a5ce-222442f5072c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column shadow
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 085ec7c9-6d71-4eca-b0de-521e469af8e9
		summarizeBy: none
		sourceColumn: shadow

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: a81f95e4-9be6-4b12-b03c-66b7ba4b6bc2
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b2db716d-30d0-4490-865d-1c6b08de3b76
		summarizeBy: none
		sourceColumn: start_date

		variation Variación
			isDefault
			relationship: 47b12c8c-ad12-4381-8343-09130ee6db92
			defaultHierarchy: LocalDateTable_caa50a64-43f7-4111-b80f-7a347cbb653f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column state
		dataType: int64
		formatString: 0
		lineageTag: 20eaa333-2a09-47a9-8dd6-e47a639933ea
		summarizeBy: sum
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: 3d6f63ad-2382-4da1-b8ab-32af160657b4
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 99db2d49-c1ce-439c-8699-08c72102fe46
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column dv_status
		dataType: string
		lineageTag: 365d3a4d-5073-45d4-95b7-37217edeea2f
		summarizeBy: none
		sourceColumn: dv_status

		annotation SummarizationSetBy = Automatic

	column sub_tree_root
		dataType: string
		lineageTag: 70a364ef-7534-484a-bf51-22a926599726
		summarizeBy: none
		sourceColumn: sub_tree_root

		annotation SummarizationSetBy = Automatic

	column dv_sub_tree_root
		dataType: string
		lineageTag: 99da2917-2ef3-42f4-90fd-de1d60192423
		summarizeBy: none
		sourceColumn: dv_sub_tree_root

		annotation SummarizationSetBy = Automatic

	column sys_class_name
		dataType: string
		lineageTag: a359682f-05b3-4c00-bae8-6c662a0c8356
		summarizeBy: none
		sourceColumn: sys_class_name

		annotation SummarizationSetBy = Automatic

	column dv_sys_class_name
		dataType: string
		lineageTag: 43cff2d8-02ae-4c4b-adf6-44bc2be49ae4
		summarizeBy: none
		sourceColumn: dv_sys_class_name

		annotation SummarizationSetBy = Automatic

	column sys_created_by
		dataType: string
		lineageTag: 00393809-84c8-49b1-83a0-5242214832cd
		summarizeBy: none
		sourceColumn: sys_created_by

		annotation SummarizationSetBy = Automatic

	column sys_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 587ce774-78f0-4da1-bcb2-ccaed7f52391
		summarizeBy: none
		sourceColumn: sys_created_on

		variation Variación
			isDefault
			relationship: 5d97575d-af65-446a-a827-fe50b537066a
			defaultHierarchy: LocalDateTable_c0bbd75a-ce1b-4c0c-84f0-52b18e73b0bc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column sys_domain
		dataType: string
		lineageTag: 332ad55f-0781-4232-9bea-707742e7f9c4
		summarizeBy: none
		sourceColumn: sys_domain

		annotation SummarizationSetBy = Automatic

	column sys_domain_path
		dataType: string
		lineageTag: d72271c4-5725-44f0-b41a-d6a1e7e4f36c
		summarizeBy: none
		sourceColumn: sys_domain_path

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: 727039f3-27ed-4b01-91f9-7cd8da892d74
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column sys_mod_count
		dataType: int64
		formatString: 0
		lineageTag: 9c07fecd-4675-4d74-bf73-d12dc49b0f32
		summarizeBy: sum
		sourceColumn: sys_mod_count

		annotation SummarizationSetBy = Automatic

	column sys_updated_by
		dataType: string
		lineageTag: f5db1600-9dd7-48b0-af3b-56079fc2d621
		summarizeBy: none
		sourceColumn: sys_updated_by

		annotation SummarizationSetBy = Automatic

	column sys_updated_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 92bd598e-e881-438b-be2d-271298bbd5af
		summarizeBy: none
		sourceColumn: sys_updated_on

		variation Variación
			isDefault
			relationship: 9647c736-17bd-4c1d-adad-11e6c59bbdd1
			defaultHierarchy: LocalDateTable_a2acadba-00e5-4072-8718-c3d34059491a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column task
		dataType: string
		lineageTag: f6b83a34-ab50-446a-8afc-4dc262e2d7f8
		summarizeBy: none
		sourceColumn: task

		annotation SummarizationSetBy = Automatic

	column task_effective_number
		dataType: string
		lineageTag: b8b8f5ff-a16f-43bd-862b-e2482e3cfa8a
		summarizeBy: none
		sourceColumn: task_effective_number

		annotation SummarizationSetBy = Automatic

	column time_card_at_top_task
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: da6a9422-e34f-48bc-8783-f99f255e659f
		summarizeBy: none
		sourceColumn: time_card_at_top_task

		annotation SummarizationSetBy = Automatic

	column time_constraint
		dataType: string
		lineageTag: 55f6b5d6-96a6-43e2-a387-d5ed3268a60f
		summarizeBy: none
		sourceColumn: time_constraint

		annotation SummarizationSetBy = Automatic

	column dv_time_constraint
		dataType: string
		lineageTag: 2303ec4f-17a1-4408-ac34-272bd7dac250
		summarizeBy: none
		sourceColumn: dv_time_constraint

		annotation SummarizationSetBy = Automatic

	column time_worked
		dataType: dateTime
		formatString: General Date
		lineageTag: b90404c1-0dec-4180-847b-727251bbe39e
		summarizeBy: none
		sourceColumn: time_worked

		variation Variación
			isDefault
			relationship: dcf1e726-8c25-4ca3-a2e6-fa7c576f9721
			defaultHierarchy: LocalDateTable_53a67181-9115-4f2d-b501-0fb15cf2eadb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_time_worked
		dataType: string
		lineageTag: bde0bc86-fb16-4c2f-a6ac-f546cbc9a3db
		summarizeBy: none
		sourceColumn: dv_time_worked

		annotation SummarizationSetBy = Automatic

	column top_task
		dataType: string
		lineageTag: cb0b7eed-1644-4331-beb6-d90766d8cf6d
		summarizeBy: none
		sourceColumn: top_task

		annotation SummarizationSetBy = Automatic

	column dv_top_task
		dataType: string
		lineageTag: ea7c9032-1f28-4ec4-9df0-f3d24f50a24f
		summarizeBy: none
		sourceColumn: dv_top_task

		annotation SummarizationSetBy = Automatic

	column u_acciona_priority
		dataType: int64
		formatString: 0
		lineageTag: 5dbbfb23-5651-47f6-975f-8f894ee0ebbd
		summarizeBy: sum
		sourceColumn: u_acciona_priority

		annotation SummarizationSetBy = Automatic

	column u_business_application
		dataType: string
		lineageTag: 4888d612-6b28-4bc4-a526-d8c113e32457
		summarizeBy: none
		sourceColumn: u_business_application

		annotation SummarizationSetBy = Automatic

	column dv_u_business_application
		dataType: string
		lineageTag: 528b1ad3-64cd-46e7-a212-3b482d9dbe2b
		summarizeBy: none
		sourceColumn: dv_u_business_application

		annotation SummarizationSetBy = Automatic

	column u_execution_type
		dataType: string
		lineageTag: 0ca38492-5e63-4684-b8e7-0f3af167ae1b
		summarizeBy: none
		sourceColumn: u_execution_type

		annotation SummarizationSetBy = Automatic

	column dv_u_execution_type
		dataType: string
		lineageTag: 9b12440d-2bca-442a-95e8-01577f4a3ee4
		summarizeBy: none
		sourceColumn: dv_u_execution_type

		annotation SummarizationSetBy = Automatic

	column u_previous_groups
		dataType: string
		lineageTag: 87721efd-f8cc-4ab9-9e3f-465eb0659056
		summarizeBy: none
		sourceColumn: u_previous_groups

		annotation SummarizationSetBy = Automatic

	column u_progress
		dataType: double
		lineageTag: ce048314-1f1d-4725-a964-4aaef37cacdd
		summarizeBy: sum
		sourceColumn: u_progress

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_responded
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9eef269c-8f73-459d-a7c8-66cd7b3272ef
		summarizeBy: none
		sourceColumn: u_responded

		annotation SummarizationSetBy = Automatic

	column u_size
		dataType: string
		lineageTag: fe03ce3a-dc20-44b7-8a42-888e03f75e78
		summarizeBy: none
		sourceColumn: u_size

		annotation SummarizationSetBy = Automatic

	column dv_u_size
		dataType: string
		lineageTag: 5b0e386d-21ed-44d6-91cd-fe764f3e6fda
		summarizeBy: none
		sourceColumn: dv_u_size

		annotation SummarizationSetBy = Automatic

	column u_state_date
		dataType: dateTime
		formatString: General Date
		lineageTag: e6561bd6-e4e7-479b-a45a-b3077ff33c8e
		summarizeBy: none
		sourceColumn: u_state_date

		variation Variación
			isDefault
			relationship: 22006a10-54d4-4ec8-a7c7-59c44a20e07c
			defaultHierarchy: LocalDateTable_2ba2308f-3482-4542-a33a-6f472f357f19.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column upon_approval
		dataType: string
		lineageTag: 92f41d1a-bf50-41a6-852e-4e60574f03cf
		summarizeBy: none
		sourceColumn: upon_approval

		annotation SummarizationSetBy = Automatic

	column dv_upon_approval
		dataType: string
		lineageTag: 9dd1382b-1eee-418b-b888-69e06a3457ee
		summarizeBy: none
		sourceColumn: dv_upon_approval

		annotation SummarizationSetBy = Automatic

	column upon_reject
		dataType: string
		lineageTag: f9e3bb7f-5bd8-47ed-adee-7be175c9ce96
		summarizeBy: none
		sourceColumn: upon_reject

		annotation SummarizationSetBy = Automatic

	column dv_upon_reject
		dataType: string
		lineageTag: 7571aad9-ebe1-4418-bdd2-bd84f5dade7b
		summarizeBy: none
		sourceColumn: dv_upon_reject

		annotation SummarizationSetBy = Automatic

	column urgency
		dataType: int64
		formatString: 0
		lineageTag: 710b2c21-f255-4bd5-98b9-a8b1097a8885
		summarizeBy: sum
		sourceColumn: urgency

		annotation SummarizationSetBy = Automatic

	column dv_urgency
		dataType: string
		lineageTag: d900892d-ec91-4160-b80b-211aa5f8c883
		summarizeBy: none
		sourceColumn: dv_urgency

		annotation SummarizationSetBy = Automatic

	column version
		dataType: int64
		formatString: 0
		lineageTag: 0aa470c7-c34c-44e1-aa2f-556d5a20bcc8
		summarizeBy: sum
		sourceColumn: version

		annotation SummarizationSetBy = Automatic

	column watch_list
		dataType: string
		lineageTag: b79ff480-6397-4ede-a5d2-00b9b1d97a11
		summarizeBy: none
		sourceColumn: watch_list

		annotation SummarizationSetBy = Automatic

	column wbs_order
		dataType: int64
		formatString: 0
		lineageTag: 0089801f-d5d2-4f70-b98b-80b71cec2a90
		summarizeBy: sum
		sourceColumn: wbs_order

		annotation SummarizationSetBy = Automatic

	column work_cost
		dataType: double
		lineageTag: fa0bb815-17cd-42f6-8c6a-d7ea48af1b62
		summarizeBy: sum
		sourceColumn: work_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column work_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 38bcb203-89db-4e88-ab15-e3501d148c78
		summarizeBy: none
		sourceColumn: work_duration

		variation Variación
			isDefault
			relationship: d2cd40a7-4af7-4700-ba26-3888f9011661
			defaultHierarchy: LocalDateTable_7b034080-0732-4012-a672-4abfb52b7f77.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_work_duration
		dataType: string
		lineageTag: 02c61ee6-7720-4c08-b618-7fa9b1e636c1
		summarizeBy: none
		sourceColumn: dv_work_duration

		annotation SummarizationSetBy = Automatic

	column work_effort
		dataType: dateTime
		formatString: General Date
		lineageTag: c8c0e4bc-beb4-4543-816b-adfe1bf8d16b
		summarizeBy: none
		sourceColumn: work_effort

		variation Variación
			isDefault
			relationship: 2390a212-7c90-465a-abcd-aba790d9e068
			defaultHierarchy: LocalDateTable_722dd833-ee65-4bbd-974c-cbcc58563c4f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_work_effort
		dataType: string
		lineageTag: 2a252ea1-e067-48cc-9363-e8566d4070a3
		summarizeBy: none
		sourceColumn: dv_work_effort

		annotation SummarizationSetBy = Automatic

	column work_end
		dataType: dateTime
		formatString: General Date
		lineageTag: a0b5f8dc-ac1c-4867-9603-3c1066a1cd43
		summarizeBy: none
		sourceColumn: work_end

		variation Variación
			isDefault
			relationship: 0830f259-d0ef-4409-949e-af062fcd4f67
			defaultHierarchy: LocalDateTable_97ac2da0-d933-48f3-8866-82636867094a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column work_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 51826855-9559-4223-8312-1e6e644fdc9c
		summarizeBy: none
		sourceColumn: work_start

		variation Variación
			isDefault
			relationship: 473ad9ba-b745-4e2e-b81e-de74c3a0bfd1
			defaultHierarchy: LocalDateTable_03b8564c-0847-4f5f-8acd-5f6d2e0aebe9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Ev3 = if(and(and('Ev3-Mantener'[Subcategoria-Demanda] = "Small",CONTAINS(_MejorasAux, _MejorasAux[enhancement], 'Ev3-Mantener'[sys_id])), CONTAINS(Aplicaciones, Aplicaciones[Aplicación de Negocio],'Ev3-Mantener'[dv_u_business_application])), TRUE(), FALSE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9900a66a-00f6-47e7-800c-c10324a67806
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Ev3Aux = SUBSTITUTE('Ev3-Mantener'[Ev3], "TRUE", "Mejora")
		lineageTag: c2544795-5a61-4cea-ac8e-e632cbeb8def
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DuracionProyecto = (DATEDIFF('Ev3-Mantener'[end_date], 'Ev3-Mantener'[start_date],DAY)*(-1))
		formatString: 0
		lineageTag: 440a3509-7e73-411e-8e98-112c7832fb64
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Dias de avance teorico' = ```
			IF('Ev3-Mantener'[end_date]<TODAY(), 
			    (DATEDIFF('Ev3-Mantener'[end_date], 'Ev3-Mantener'[start_date],DAY)*(-1)), 
			    (DATEDIFF(TODAY(),'Ev3-Mantener'[start_date],DAY)*(-1)))
			```
		formatString: 0
		lineageTag: 7f03fdd6-9d49-411c-8ae9-e9fbf932e6ed
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '% avance teorico' = DIVIDE('Ev3-Mantener'[Dias de avance teorico], 'Ev3-Mantener'[DuracionProyecto], 0)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 92413c8c-e06f-4376-90ed-b4c86f0259ef
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '% comparativo entre teorico y real' = 'Ev3-Mantener'[% avance teorico] - ('Ev3-Mantener'[percent_complete]/100)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 3a28756d-708d-4a4a-b834-9310881b23da
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Estado proyectos desviados en alcance' = IF('Ev3-Mantener'[% comparativo entre teorico y real]<=0.10,"Entre 0 y 10%",IF('Ev3-Mantener'[% comparativo entre teorico y real]<=0.25,"Entre 11 y 25%",IF('Ev3-Mantener'[% comparativo entre teorico y real]>0.25,">25%","Sin avance")))
		lineageTag: f8a00922-c393-47e8-91ea-edbf16f96c31
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column schedule_start_NOTBLANK = if('Ev3-Mantener'[schedule_start_date] = Blank(), 'Ev3-Mantener'[start_date], 'Ev3-Mantener'[schedule_start_date])
		formatString: General Date
		lineageTag: efe3dc0c-f79c-45a0-8d72-4e87820a7abe
		summarizeBy: none

		variation Variación
			isDefault
			relationship: f3bb1fd6-8c2c-42a7-a12d-af4814a79928
			defaultHierarchy: LocalDateTable_b03384ee-eaea-4f6e-b836-908e0ee1932b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Size = LOOKUPVALUE(Ev3Demandas[_dv_size - SoloLetra], Ev3Demandas[enhancement], 'Ev3-Mantener'[sys_id])
		lineageTag: d01f6181-e1b9-4464-b722-8a9c25a38213
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_dv_state - español'
		dataType: string
		lineageTag: 0976bee5-7a3d-4a8f-a01e-4751a7126180
		summarizeBy: none
		sourceColumn: _dv_state - español

		annotation SummarizationSetBy = Automatic

	column 'URL Mejoras' = CONCATENATE("https://acciona.service-now.com/rm_enhancement.do?sysparm_query=number%3d",'Ev3-Mantener'[number])
		lineageTag: c5b82fc5-db18-48d6-b571-38c0eb82f056
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ID-Demanda = LOOKUPVALUE(Ev3Demandas[number],Ev3Demandas[dv_enhancement], [number])
		lineageTag: bc734507-6c71-4e41-ae1b-9793550deb73
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'URL DemandaEnMejoras' = CONCATENATE("https://acciona.service-now.com/dmn_demand.do?sysparm_query=number%3d",'Ev3-Mantener'[ID-Demanda])
		lineageTag: f06bcf5d-9038-4a99-a3a4-fa4fca4655ab
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_dv_priority - español'
		dataType: string
		lineageTag: 3feeebb4-f507-4b31-aa22-b9e1c46d1efe
		summarizeBy: none
		sourceColumn: _dv_priority - español

		annotation SummarizationSetBy = Automatic

	column Subcategoria-Demanda = LOOKUPVALUE(Ev3Demandas[dv_u_subcategory],Ev3Demandas[number], [ID-Demanda])
		lineageTag: b30d31ec-cc94-46bb-b9fa-dc33c6d8347a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column __DiaAbierta_Info_BackLog = 'Ev3-Mantener'[opened_at].[Date]
		formatString: d/m/yy
		lineageTag: 6770ac36-fbb7-4454-9556-8b136ed19ba5
		summarizeBy: none

		variation Variación
			isDefault
			relationship: 9b6fe405-1eb3-453a-8fa7-1c8c7d6f8cc3
			defaultHierarchy: LocalDateTable_9bfca826-9543-46f9-8a45-513739d1910e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column _myMesAñoENHs_Info_BackLog = FORMAT('Ev3-Mantener'[__DiaAbierta_Info_BackLog],"YYYY MMM")
		lineageTag: 7b564cae-5664-4abb-8903-c6c61153d568
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column __Util_para_Ev3_Info_BackLog = if('Ev3-Mantener'[Ev3Aux] = "Mejora", "Si", "No")
		lineageTag: f3062815-3a0a-4374-a813-c4da55e20592
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column __EstadoGeneral_para_Ev3_Info_BackLog = if(OR('Ev3-Mantener'[dv_state]="Closed Complete",'Ev3-Mantener'[dv_state]="Cancelled"), "Cerrada", "Abierta")
		lineageTag: 454e9c83-95f8-4b44-886f-58421d56c6aa
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column __DiaCerrada_Info_BackLog = 'Ev3-Mantener'[closed_at].[Date]
		formatString: General Date
		lineageTag: a2d526fe-a67e-48f6-b616-889cafdee204
		summarizeBy: none

		variation Variación
			isDefault
			relationship: 537fa50d-da06-4d24-a032-2303fc01bddb
			defaultHierarchy: LocalDateTable_aa85a3d4-fb5f-443f-a298-ecb2f85858c1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column _myMesAñoENHsCerrada_Info_BackLog = FORMAT('Ev3-Mantener'[__DiaCerrada_Info_BackLog],"YYYY MMM")
		lineageTag: 2f292aeb-549c-49c8-9b27-66ea3259d58f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Tallaje-Demanda = LOOKUPVALUE(Ev3Demandas[_dv_size - SoloLetra],Ev3Demandas[number], [ID-Demanda])
		lineageTag: ad3b1724-7ec3-4cee-be17-4aae18a459bf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Estado-Demanda = LOOKUPVALUE(Ev3Demandas[dv_state],Ev3Demandas[number], [ID-Demanda])
		lineageTag: d424e348-b149-4963-a8df-f05b4c0ea712
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '_% Percent_complete' = (('Ev3-Mantener'[percent_complete])/100)+0
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 5dcdb4c6-a373-4ccd-8f37-9fa0aee6efa8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Ev3-Mantener-79c1f04a-68cd-4577-96a7-387932b138d2 = m
		mode: import
		source =
				let
				    Origen = Sql.Databases("QECCDWH.acciona.int,60001"),
				    DWH = Origen{[Name="DWH"]}[Data],
				    SERV_NOW_rm_enhancement = DWH{[Schema="SERV_NOW",Item="rm_enhancement"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_rm_enhancement,{"activity_due", "approval_history", "approval_set", "business_duration", "dv_business_duration", "business_service", "dv_business_service", "calendar_duration", "dv_calendar_duration", "close_notes", "cmdb_ci", "dv_cmdb_ci", "cmdb_ci_business_app", "dv_cmdb_ci_business_app", "comments", "comments_and_work_notes", "work_notes_list", "work_notes", "wf_activity", "dv_wf_activity", "wbs", "user_input", "variables", "universal_request", "dv_universal_request", "u_ref_country", "dv_u_ref_country", "u_phone", "dv_u_metal", "u_metal", "u_external_vendor", "dv_u_external_vendor", "u_department", "dv_u_department", "u_catalog", "dv_u_catalog", "u_business_line", "dv_u_business_line", "top_program", "dv_top_program", "top_portfolio", "dv_top_portfolio", "task_for", "dv_task_for", "sys_tags", "start_date_derived_from", "dv_start_date_derived_from", "skills", "sla_due", "service_offering", "dv_service_offering", "route_reason", "dv_route_reason", "remaining_duration", "dv_remaining_duration", "relation_applied", "dv_relation_applied", "rejection_goto", "dv_rejection_goto", "product", "dv_product", "orig_top_task_id", "dv_orig_top_task_id", "orig_sys_id", "dv_orig_sys_id", "location", "dv_location", "html_description", "expected_start", "follow_up", "end_date_derived_from", "dv_end_date_derived_from", "due_date", "dependency", "delivery_task", "dv_delivery_task", "delivery_plan", "dv_delivery_plan", "correlation_display", "contact_type", "dv_contact_type", "constraint_date", "dv_company", "company"}),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Columnas quitadas", "dv_state", "dv_state - Copia"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna duplicada",{{"dv_state - Copia", "_dv_state - español"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","Draft","Borrador",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","In Analysis","En Análisis",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","In Development","En proceso",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","Closed Complete","Cerrado",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","Testing/QA","En pruebas",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","Cancelled","Cancelado",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Valor reemplazado6" = Table.ReplaceValue(#"Valor reemplazado5","On Hold","En espera",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Columna duplicada1" = Table.DuplicateColumn(#"Valor reemplazado6", "dv_priority", "dv_priority - Copia"),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columna duplicada1",{{"dv_priority - Copia", "_dv_priority - español"}}),
				    #"Valor reemplazado7" = Table.ReplaceValue(#"Columnas con nombre cambiado1","1 - Critical","1 - Crítica",Replacer.ReplaceText,{"_dv_priority - español"}),
				    #"Valor reemplazado8" = Table.ReplaceValue(#"Valor reemplazado7","2 - High","2 - Alta",Replacer.ReplaceText,{"_dv_priority - español"}),
				    #"Valor reemplazado9" = Table.ReplaceValue(#"Valor reemplazado8","3 - Moderate","3 - Moderada",Replacer.ReplaceText,{"_dv_priority - español"}),
				    #"Valor reemplazado10" = Table.ReplaceValue(#"Valor reemplazado9","4 - Low","4 - Baja",Replacer.ReplaceText,{"_dv_priority - español"}),
				    #"Valor reemplazado11" = Table.ReplaceValue(#"Valor reemplazado10","5 - Very Low","5 - Muy Baja",Replacer.ReplaceText,{"_dv_priority - español"}),
				    #"Filas filtradas" = Table.SelectRows(#"Valor reemplazado11", each [opened_at] > #datetime(2022, 1, 1, 0, 0, 0)),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Filas filtradas",{{"percent_complete", type number}}),
				    #"Valor reemplazado12" = Table.ReplaceValue(#"Tipo cambiado","Deploy/Launch","Despliegue",Replacer.ReplaceText,{"_dv_state - español"}),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Valor reemplazado12",{"active", "actual_benefits", "additional_assignee_list", "allow_dates_outside_schedule", "approval", "dv_approval", "assigned_to", "dv_assigned_to", "assignment_group", "dv_assignment_group", "benefits", "budget_cost", "calculation_type", "dv_calculation_type", "capex_cost", "closed_at", "closed_by", "dv_closed_by", "correlation_id", "cost", "critical_path", "description", "duration", "dv_duration", "effort", "dv_effort", "escalation", "dv_escalation", "group_list", "has_conflict", "impact", "dv_impact", "key_milestone", "knowledge", "level", "made_sla", "milestone", "mpp_task_id", "number", "opened_at", "opened_by", "dv_opened_by", "opex_cost", "order", "parent", "dv_parent", "percent_complete", "phase_type", "dv_phase_type", "priority", "dv_priority", "reassignment_count", "remaining_effort", "dv_remaining_effort", "resource_allocated_cost", "resource_planned_cost", "rollup", "schedule_end_date", "schedule_start_date", "shadow", "short_description", "start_date", "end_date", "state", "dv_state", "status", "dv_status", "sub_tree_root", "dv_sub_tree_root", "sys_class_name", "dv_sys_class_name", "sys_created_by", "sys_created_on", "sys_domain", "sys_domain_path", "sys_id", "sys_mod_count", "sys_updated_by", "sys_updated_on", "task", "task_effective_number", "time_card_at_top_task", "time_constraint", "dv_time_constraint", "time_worked", "dv_time_worked", "top_task", "dv_top_task", "u_acciona_priority", "u_business_application", "dv_u_business_application", "u_execution_type", "dv_u_execution_type", "u_previous_groups", "u_progress", "u_responded", "u_size", "dv_u_size", "u_state_date", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "urgency", "dv_urgency", "version", "watch_list", "wbs_order", "work_cost", "work_duration", "dv_work_duration", "work_effort", "dv_work_effort", "work_end", "work_start", "_dv_state - español", "_dv_priority - español"})
				in
				    #"Columnas reordenadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

