table REFERENCIA_Demandas_Unicas
	lineageTag: e7ec9ef1-1bf3-4a07-a0ea-a8a604928027

	measure __UltimaActualizacion = today()
		formatString: Short Date
		lineageTag: 1682a2ea-2fe6-4ecf-baf8-1dd4eaea4171

	column number
		dataType: string
		lineageTag: 5f3f2dc3-a555-4d9f-aff4-7c5ec8ddc512
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: b26309ad-1194-449d-b6f6-d02510604540
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column 'EVOLUTIVOS_COMPLETO_Number - URL'
		dataType: string
		lineageTag: fc60f324-8f40-4acf-8c45-c0c1fdc61694
		summarizeBy: none
		sourceColumn: EVOLUTIVOS_COMPLETO_Number - URL

		annotation SummarizationSetBy = Automatic

	column DEMANDA_NUMBER_FICTICIO
		dataType: string
		lineageTag: 75380184-f9b5-42cc-b8ff-65319ca9f28a
		summarizeBy: none
		sourceColumn: DEMANDA_NUMBER_FICTICIO

		annotation SummarizationSetBy = Automatic

	column DMNs_TASKs_AplicacionNegocio
		dataType: string
		lineageTag: 50be5085-5b1e-4b4f-9920-0f86af202e92
		summarizeBy: none
		sourceColumn: DMNs_TASKs_AplicacionNegocio

		annotation SummarizationSetBy = Automatic

	column REF_DMN-APLIC-ES-ENERGIA = if(CONTAINS(Aplicaciones, Aplicaciones[Aplicación de Negocio],'REFERENCIA_Demandas_Unicas'[Aplicaciones_Energia_DEFINITIVAS]), TRUE(), FALSE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 79e0d6e4-1111-44c0-97e0-542240e5b9a2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column u_affected_portfolios
		dataType: string
		lineageTag: 4e030f1d-06e2-4302-a858-29dc13cc5660
		summarizeBy: none
		sourceColumn: u_affected_portfolios

		annotation SummarizationSetBy = Automatic

	column 'SERV_NOW dmn_demand.PortfolioVisualizarEnergia_FINAL'
		dataType: string
		lineageTag: dd3b9cd7-a93e-4a79-8c01-3e8ee99ba697
		summarizeBy: none
		sourceColumn: SERV_NOW dmn_demand.PortfolioVisualizarEnergia_FINAL

		annotation SummarizationSetBy = Automatic

	column 'SERV_NOW dmn_demand.EVOLUTIVOS_COMPLETO_PortfolioaMostrar'
		dataType: string
		lineageTag: 7d30cfb5-272f-468d-8dbb-ac26e3da7a81
		summarizeBy: none
		sourceColumn: SERV_NOW dmn_demand.EVOLUTIVOS_COMPLETO_PortfolioaMostrar

		annotation SummarizationSetBy = Automatic

	column Aplicaciones_Energia_DEFINITIVAS =
			IF (
			'REFERENCIA_Demandas_Unicas'[SERV_NOW dmn_demand.EVOLUTIVOS_COMPLETO_PortfolioaMostrar] = "EN.Supply Chain", 'REFERENCIA_Demandas_Unicas'[DMNs_TASKs_AplicacionNegocio], "Aplicación Afectada")
		lineageTag: 05238595-edfa-498b-9368-697f13626d78
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column approved_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f92a8e82-3d43-42d0-af37-c0b5632ed4cd
		summarizeBy: none
		sourceColumn: approved_end_date

		variation Variación
			isDefault
			relationship: e895e6f3-966d-4f1c-9bfe-57f118c91a83
			defaultHierarchy: LocalDateTable_0597b626-dc55-495d-ba1f-c9efa87d2973.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column approved_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 27111580-dbcf-4a54-9fa9-0bba80a77d59
		summarizeBy: none
		sourceColumn: approved_start_date

		variation Variación
			isDefault
			relationship: 0f2572a1-8882-4d80-a02e-bf1584f5cdeb
			defaultHierarchy: LocalDateTable_e79fbce3-8981-43fe-95cd-d8fdfdf615cb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column calculation_type
		dataType: string
		lineageTag: e0c79f17-1bf9-4bb8-ab13-9c1dfd54557c
		summarizeBy: none
		sourceColumn: calculation_type

		annotation SummarizationSetBy = Automatic

	column dv_calculation_type
		dataType: string
		lineageTag: fe5d7d72-1e0f-4034-8ccd-07333ce6a9cf
		summarizeBy: none
		sourceColumn: dv_calculation_type

		annotation SummarizationSetBy = Automatic

	column contract
		dataType: string
		lineageTag: ae4c054b-07bc-4ce0-b842-8ea707991605
		summarizeBy: none
		sourceColumn: contract

		annotation SummarizationSetBy = Automatic

	column dv_contract
		dataType: string
		lineageTag: 94b30116-8d0b-47b1-aea1-020cd4f99b25
		summarizeBy: none
		sourceColumn: dv_contract

		annotation SummarizationSetBy = Automatic

	column model_id
		dataType: string
		lineageTag: 9197c800-1d71-4e9d-b94d-0196daca1850
		summarizeBy: none
		sourceColumn: model_id

		annotation SummarizationSetBy = Automatic

	column dv_model_id
		dataType: string
		lineageTag: 2eee74de-a85e-4107-b5d5-4dca56d31f83
		summarizeBy: none
		sourceColumn: dv_model_id

		annotation SummarizationSetBy = Automatic

	column software_model
		dataType: string
		lineageTag: 6454481f-9bb1-4a1f-8274-a94625a4c8dc
		summarizeBy: none
		sourceColumn: software_model

		annotation SummarizationSetBy = Automatic

	column dv_software_model
		dataType: string
		lineageTag: 00d6f42a-6fc0-4d06-b8f5-65be2fd04270
		summarizeBy: none
		sourceColumn: dv_software_model

		annotation SummarizationSetBy = Automatic

	column u_commented
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 63b139ad-96f8-474c-a52e-e751dd96350f
		summarizeBy: none
		sourceColumn: u_commented

		annotation SummarizationSetBy = Automatic

	column u_deferred_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: c6265010-67e7-4595-a90d-35e348dc1f25
		summarizeBy: none
		sourceColumn: u_deferred_end_date

		variation Variación
			isDefault
			relationship: f58ae691-a362-4b91-8c23-156bb8c05e4e
			defaultHierarchy: LocalDateTable_71b19ad1-de71-4c7f-9874-d16c95ab5094.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_deferred_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1208e73b-7310-4953-b372-d492b06f85e0
		summarizeBy: none
		sourceColumn: u_deferred_start_date

		variation Variación
			isDefault
			relationship: 9bfc7647-d91a-4b03-b4ee-1284d0834ca0
			defaultHierarchy: LocalDateTable_1d14ee05-2fdb-4f06-814e-26fecb338752.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column u_digital_transformation
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: adb14eb3-641f-43bf-9fd6-820744ebf19a
		summarizeBy: none
		sourceColumn: u_digital_transformation

		annotation SummarizationSetBy = Automatic

	column u_fases_rfi
		dataType: string
		lineageTag: 5bb238a8-2230-42cd-97a8-7a01b25ee5fa
		summarizeBy: none
		sourceColumn: u_fases_rfi

		annotation SummarizationSetBy = Automatic

	column dv_u_fases_rfi
		dataType: string
		lineageTag: dedf0f62-082b-49c7-a0b5-40ba9c462e60
		summarizeBy: none
		sourceColumn: dv_u_fases_rfi

		annotation SummarizationSetBy = Automatic

	column u_operational_committee_comment
		dataType: string
		lineageTag: c12af1c3-188a-4dab-9823-bd23fff07239
		summarizeBy: none
		sourceColumn: u_operational_committee_comment

		annotation SummarizationSetBy = Automatic

	column u_origin_country_of_the_demand
		dataType: string
		lineageTag: 010e7dbe-d723-479b-926c-adc997631e08
		summarizeBy: none
		sourceColumn: u_origin_country_of_the_demand

		annotation SummarizationSetBy = Automatic

	column u_payroll_area
		dataType: string
		lineageTag: 58c60baf-5630-442b-95b3-93d65faee95f
		summarizeBy: none
		sourceColumn: u_payroll_area

		annotation SummarizationSetBy = Automatic

	column dv_u_payroll_area
		dataType: string
		lineageTag: 27215be3-1e92-4747-91ba-90eaa1fdd378
		summarizeBy: none
		sourceColumn: dv_u_payroll_area

		annotation SummarizationSetBy = Automatic

	column u_planned_capital
		dataType: double
		lineageTag: badae3e2-40db-463f-9e44-7ebac6f90817
		summarizeBy: sum
		sourceColumn: u_planned_capital

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_planned_operating
		dataType: double
		lineageTag: eaae9c80-3739-475e-8c17-b1a7c0b6faec
		summarizeBy: sum
		sourceColumn: u_planned_operating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_program_manager
		dataType: string
		lineageTag: d213b2cf-ef85-4d2b-8b16-12c08cff00ca
		summarizeBy: none
		sourceColumn: u_program_manager

		annotation SummarizationSetBy = Automatic

	column dv_u_program_manager
		dataType: string
		lineageTag: c51ff1fc-7c1a-4d7c-8202-46d6cbef2fdb
		summarizeBy: none
		sourceColumn: dv_u_program_manager

		annotation SummarizationSetBy = Automatic

	column u_relevant_project_for_cio
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fa59dda0-66e3-4709-94e6-6bd09ca362e4
		summarizeBy: none
		sourceColumn: u_relevant_project_for_cio

		annotation SummarizationSetBy = Automatic

	column u_rfi
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 112a897c-0208-45ff-a6bf-fd9cbd480e9c
		summarizeBy: none
		sourceColumn: u_rfi

		annotation SummarizationSetBy = Automatic

	column u_selected_suppliers
		dataType: string
		lineageTag: 2d33b2c7-7a2f-4dd8-a414-bb6a240f25a6
		summarizeBy: none
		sourceColumn: u_selected_suppliers

		annotation SummarizationSetBy = Automatic

	column u_targets
		dataType: string
		lineageTag: 14e15286-d794-4818-9df2-ecbcd6a0ec59
		summarizeBy: none
		sourceColumn: u_targets

		annotation SummarizationSetBy = Automatic

	column u_total_planned_cost
		dataType: double
		lineageTag: 3ff11ac2-a652-4f28-b92c-63a9f0da48b6
		summarizeBy: sum
		sourceColumn: u_total_planned_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition REFERENCIA_Demandas_Unicas-845f1f8c-e66a-4a2e-828c-4e5d15c9ddfc = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "DWH"),
				    SERV_NOW_dmn_demand = Origen{[Schema="SERV_NOW",Item="dmn_demand"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(SERV_NOW_dmn_demand, each ([dv_state] = "Approved" or [dv_state] = "Completed") and ([dv_u_subcategory] = "Small") and ([dv_type] = "Service Upgrade")),
				    #"Consultas combinadas" = Table.NestedJoin(#"Filas filtradas", {"sys_id"}, #"SERV_NOW pm_project - Multitarea", {"demand"}, "SERV_NOW pm_project", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW pm_project" = Table.ExpandTableColumn(#"Consultas combinadas", "SERV_NOW pm_project", {"number", "closed_at", "end_date", "opened_at", "percent_complete", "phase", "dv_phase", "priority", "dv_priority", "start_date", "state", "dv_state", "dv_u_project_type", "dv_cmdb_ci_business_app", "short_description"}, {"SERV_NOW pm_project.number", "SERV_NOW pm_project.closed_at", "SERV_NOW pm_project.end_date", "SERV_NOW pm_project.opened_at", "SERV_NOW pm_project.percent_complete", "SERV_NOW pm_project.phase", "SERV_NOW pm_project.dv_phase", "SERV_NOW pm_project.priority", "SERV_NOW pm_project.dv_priority", "SERV_NOW pm_project.start_date", "SERV_NOW pm_project.state", "SERV_NOW pm_project.dv_state", "SERV_NOW pm_project.dv_u_project_type", "SERV_NOW pm_project.dv_cmdb_ci_business_app", "SERV_NOW pm_project.short_description"}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Se expandió SERV_NOW pm_project",{"activity_due", "additional_assignee_list", "apm_idea_action", "dv_apm_idea_action", "approval", "dv_approval", "approval_history", "approval_set", "assessment_required", "assigned_to", "dv_assigned_to", "assignment_group", "dv_assignment_group", "assumptions", "barriers", "business_capabilities", "business_case", "business_duration", "dv_business_duration", "business_service", "dv_business_service", "business_unit", "dv_business_unit", "calendar_duration", "dv_calendar_duration", "change", "dv_change", "close_notes", "cmdb_ci", "dv_cmdb_ci", "collaborators", "comments", "comments_and_work_notes", "company", "dv_company", "contact_type", "dv_contact_type", "correlation_display", "correlation_id", "defect", "dv_defect", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "description", "escalation", "dv_escalation", "idea", "dv_idea", "in_scope", "investment_class", "dv_investment_class", "investment_type", "dv_investment_type", "knowledge", "labor_costs", "location", "dv_location", "made_sla", "out_of_scope", "dv_parent", "primary_program", "dv_primary_program", "project_manager", "dv_project_manager", "rate_model", "dv_rate_model", "reassignment_count", "rejection_goto", "dv_rejection_goto"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas quitadas",{{"related_records", type text}}),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Tipo cambiado",{"requested_by", "resource_allocated_cost", "resource_planned_cost", "risk_of_not_performing", "risk_of_performing", "route_reason", "dv_route_reason", "scrum_epic", "dv_scrum_epic", "scrum_story", "dv_scrum_story", "service_offering", "dv_service_offering", "skills", "sla_due", "strategic_objectives", "sys_class_name", "dv_sys_class_name", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "task_for", "dv_task_for", "time_worked", "dv_time_worked", "u_acciona_priority", "u_architecture_analysis", "u_business_line", "dv_u_business_line", "u_catalog", "dv_u_catalog", "u_company", "dv_u_company", "u_concurrent_users", "dv_u_concurrent_users", "u_country", "dv_u_country", "u_criticality_level", "dv_u_criticality_level", "u_current_situation", "u_demand_type_description", "u_department", "dv_u_department", "u_dependencies", "u_external_vendor", "dv_u_external_vendor", "u_first_commettee_state", "dv_u_first_commettee_state", "u_first_committee_date", "dv_u_first_committee_date", "u_frecuency_of_use", "dv_u_frecuency_of_use", "u_impacted_companies", "u_impacted_countries", "u_impacted_groups", "follow_up", "goal", "dv_goal", "goals"}),
				    #"Columnas quitadas2" = Table.RemoveColumns(#"Columnas quitadas1",{"close_demand", "dv_close_demand", "closed_by", "dv_closed_by", "demand_actual_effort", "dv_demand_actual_effort", "demand_manager", "dv_demand_manager", "department", "dv_department", "discount_rate", "due_date", "enablers", "expected_risk", "dv_expected_risk", "expected_roi", "expected_start", "group_list", "irr_value", "npv_value", "opened_by", "dv_opened_by", "order", "other_costs", "score", "score_cost", "score_risk", "dv_score_risk", "score_size", "score_strategic_allignment", "score_value", "dv_score_value", "stage", "submitter", "dv_submitter", "sys_created_by", "sys_updated_by", "u_ambito_global", "u_analysis_date", "u_approval_sent", "u_approver", "dv_u_approver", "u_due_date", "u_execution_type", "dv_u_execution_type", "u_phone", "u_pilot", "u_planned_demand", "dv_u_planned_demand", "u_previous_groups", "u_priority_justification", "u_reasons_for_delay", "dv_u_reasons_for_delay", "u_ref_country", "dv_u_ref_country", "u_reg_country", "dv_u_reg_country", "u_reg_department", "dv_u_reg_department", "u_reg_division", "dv_u_reg_division", "u_reg_user", "dv_u_reg_user", "u_second_commettee_state", "dv_u_second_commettee_state", "u_second_committee_date", "dv_u_second_committee_date", "u_idl", "u_id_plan"}),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Columnas quitadas2", {"enhancement"}, #"SERV_NOW rm_enhancement", {"sys_id"}, "SERV_NOW rm_enhancement", JoinKind.LeftOuter),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Consultas combinadas1",{{"SERV_NOW rm_enhancement", "DEMANDAS-MEJORAS"}}),
				    #"Se expandió DEMNDAS-MEJORAS" = Table.ExpandTableColumn(#"Columnas con nombre cambiado", "DEMANDAS-MEJORAS", {"number","closed_at", "end_date", "opened_at", "percent_complete", "priority", "dv_priority", "start_date", "state", "dv_state","dv_u_business_application","short_description"}, {"DEMANDAS-MEJORAS.number","DEMANDAS-MEJORAS.closed_at", "DEMANDAS-MEJORAS.end_date", "DEMANDAS-MEJORAS.opened_at", "DEMANDAS-MEJORAS.percent_complete", "DEMANDAS-MEJORAS.priority", "DEMANDAS-MEJORAS.dv_priority", "DEMANDAS-MEJORAS.start_date", "DEMANDAS-MEJORAS.state", "DEMANDAS-MEJORAS.dv_state", "DEMANDAS-MEJORAS.dv_u_business_application", "DEMANDAS-MEJORAS.short_description"}),
				    #"Consultas combinadas2" = Table.NestedJoin(#"Se expandió DEMNDAS-MEJORAS", {"sys_id"}, #"SERV_NOW TAREAS - ConDemanda", {"u_demand"}, "SERV_NOW pm_project_task", JoinKind.LeftOuter),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Consultas combinadas2",{{"SERV_NOW pm_project_task", "TAREAS-ASOCIADAS-DEMANDAS"}}),
				    #"Se expandió TAREAS-ASOCIADAS-DEMANDAS" = Table.ExpandTableColumn(#"Columnas con nombre cambiado1", "TAREAS-ASOCIADAS-DEMANDAS", {"number"}, {"TAREAS-ASOCIADAS-DEMANDAS.number"}),
				    #"Columnas combinadas" = Table.CombineColumns(#"Se expandió TAREAS-ASOCIADAS-DEMANDAS",{"SERV_NOW pm_project.dv_priority", "DEMANDAS-MEJORAS.dv_priority"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"PJRs_ENHs_Prioridad"),
				    #"Columnas combinadas1" = Table.CombineColumns(#"Columnas combinadas",{"SERV_NOW pm_project.number", "DEMANDAS-MEJORAS.number"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"PRJs_ENHs-ID"),
				    #"Columnas combinadas2" = Table.CombineColumns(Table.TransformColumnTypes(#"Columnas combinadas1", {{"SERV_NOW pm_project.closed_at", type text}, {"DEMANDAS-MEJORAS.closed_at", type text}}, "es-ES"),{"SERV_NOW pm_project.closed_at", "DEMANDAS-MEJORAS.closed_at"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"PRJs_ENHs_closed_at"),
				    #"Columnas combinadas3" = Table.CombineColumns(Table.TransformColumnTypes(#"Columnas combinadas2", {{"SERV_NOW pm_project.end_date", type text}, {"DEMANDAS-MEJORAS.end_date", type text}}, "es-ES"),{"SERV_NOW pm_project.end_date", "DEMANDAS-MEJORAS.end_date"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"PRJs_ENHs_end_date"),
				    #"Columnas combinadas4" = Table.CombineColumns(Table.TransformColumnTypes(#"Columnas combinadas3", {{"SERV_NOW pm_project.opened_at", type text}, {"DEMANDAS-MEJORAS.opened_at", type text}}, "es-ES"),{"SERV_NOW pm_project.opened_at", "DEMANDAS-MEJORAS.opened_at"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"PRJs_ENHs_opened_at"),
				    #"Columnas combinadas5" = Table.CombineColumns(Table.TransformColumnTypes(#"Columnas combinadas4", {{"SERV_NOW pm_project.percent_complete", type text}, {"DEMANDAS-MEJORAS.percent_complete", type text}}, "es-ES"),{"SERV_NOW pm_project.percent_complete", "DEMANDAS-MEJORAS.percent_complete"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"PRJs_ENHs_percent_complete"),
				    #"Columnas combinadas6" = Table.CombineColumns(Table.TransformColumnTypes(#"Columnas combinadas5", {{"SERV_NOW pm_project.start_date", type text}, {"DEMANDAS-MEJORAS.start_date", type text}}, "es-ES"),{"SERV_NOW pm_project.start_date", "DEMANDAS-MEJORAS.start_date"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"PRJs_ENHs_start_date"),
				    #"Columnas combinadas7" = Table.CombineColumns(#"Columnas combinadas6",{"SERV_NOW pm_project.dv_state", "DEMANDAS-MEJORAS.dv_state"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"PRJs_ENHs_Estado"),
				    #"Filas filtradas1" = Table.SelectRows(#"Columnas combinadas7", each true),
				    #"Consulta anexada" = Table.Combine({#"Filas filtradas1", #"SERV_NOW TAREAS - SinDemanda"}),
				    #"Columnas quitadas5" = Table.RemoveColumns(#"Consulta anexada",{"TAREAS-SINDEMANDA-active", "TAREAS-SINDEMANDA-assignment_group", "TAREAS-SINDEMANDA-dv_assignment_group", "TAREAS-SINDEMANDA-closed_at", "TAREAS-SINDEMANDA-end_date", "TAREAS-SINDEMANDA-milestone", "TAREAS-SINDEMANDA-opened_at", "TAREAS-SINDEMANDA-parent", "TAREAS-SINDEMANDA-dv_parent", "TAREAS-SINDEMANDA-percent_complete", "TAREAS-SINDEMANDA-priority", "TAREAS-SINDEMANDA-dv_priority", "TAREAS-SINDEMANDA-short_description", "TAREAS-SINDEMANDA-start_date", "TAREAS-SINDEMANDA-dv_state", "TAREAS-SINDEMANDA-sys_id", "TAREAS-SINDEMANDA-top_task", "TAREAS-SINDEMANDA-dv_top_task", "TAREAS-SINDEMANDA-u_demand", "TAREAS-SINDEMANDA-dv_u_demand"}),
				    #"Columnas combinadas13" = Table.CombineColumns(#"Columnas quitadas5",{"dv_u_business_applications", "SERV_NOW pm_project - Mto.dv_cmdb_ci_business_app"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"DMNs_TASKs_AplicacionNegocio"),
				    #"Columnas combinadas15" = Table.CombineColumns(#"Columnas combinadas13",{"SERV_NOW pm_project.dv_u_project_type", "SERV_NOW pm_project - Mto.dv_u_project_type"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"PRJs_TOPTASKs_dv_u_project_type"),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Columnas combinadas15", "PRJs_ENHs-ID", "PRJs_ENHs-ID - Copia"),
				    #"Columnas con nombre cambiado2" = Table.RenameColumns(#"Columna duplicada",{{"PRJs_ENHs-ID - Copia", "EVOLUTIVOS"}}),
				    #"Columnas combinadas8" = Table.CombineColumns(#"Columnas con nombre cambiado2",{"TAREAS-SINDEMANDA-number", "EVOLUTIVOS"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"EVOLUTIVOS-ConTareasSinDemanda"),
				    #"Columna duplicada1" = Table.DuplicateColumn(#"Columnas combinadas8", "EVOLUTIVOS-ConTareasSinDemanda", "EVOLUTIVOS-ConTareasSinDemanda - Copia"),
				    #"Columnas con nombre cambiado3" = Table.RenameColumns(#"Columna duplicada1",{{"EVOLUTIVOS-ConTareasSinDemanda - Copia", "EVOLUTIVOS_COMPLETO_Number"}}),
				    #"Columnas combinadas9" = Table.CombineColumns(#"Columnas con nombre cambiado3",{"EVOLUTIVOS_COMPLETO_Number", "TAREAS-ASOCIADAS-DEMANDAS.number"},Combiner.CombineTextByDelimiter(",", QuoteStyle.None),"EVOLUTIVOS_COMPLETO_Number"),
				    #"Dividir columna por delimitador2" = Table.ExpandListColumn(Table.TransformColumns(#"Columnas combinadas9", {{"EVOLUTIVOS_COMPLETO_Number", Splitter.SplitTextByEachDelimiter({","}, QuoteStyle.Csv, true), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "EVOLUTIVOS_COMPLETO_Number"),
				    #"Filas filtradas3" = Table.SelectRows(#"Dividir columna por delimitador2", each ([EVOLUTIVOS_COMPLETO_Number] <> "")),
				    #"Duplicados quitados" = Table.Distinct(#"Filas filtradas3", {"EVOLUTIVOS_COMPLETO_Number"}),
				    #"Errores quitados" = Table.RemoveRowsWithErrors(#"Duplicados quitados", {"EVOLUTIVOS_COMPLETO_Number"}),
				    #"Consultas combinadas4" = Table.NestedJoin(#"Errores quitados", {"EVOLUTIVOS_COMPLETO_Number"}, #"SERV_NOW TAREAS - ConDemanda", {"number"}, "SERV_NOW TAREAS - ConDemanda", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW TAREAS - ConDemanda1" = Table.ExpandTableColumn(#"Consultas combinadas4", "SERV_NOW TAREAS - ConDemanda", {"closed_at", "end_date", "opened_at", "dv_parent", "percent_complete", "dv_priority", "short_description", "start_date", "dv_state", "dv_top_task", "Proyectos_Padre_Evo4&5.dv_phase"}, {"SERV_NOW TAREAS - ConDemanda.closed_at", "SERV_NOW TAREAS - ConDemanda.end_date", "SERV_NOW TAREAS - ConDemanda.opened_at", "SERV_NOW TAREAS - ConDemanda.dv_parent", "SERV_NOW TAREAS - ConDemanda.percent_complete", "SERV_NOW TAREAS - ConDemanda.dv_priority", "SERV_NOW TAREAS - ConDemanda.short_description", "SERV_NOW TAREAS - ConDemanda.start_date", "SERV_NOW TAREAS - ConDemanda.dv_state", "SERV_NOW TAREAS - ConDemanda.dv_top_task", "SERV_NOW TAREAS - ConDemandaProyectos_Padre_Evo4&5.dv_phase"}),
				    #"Consultas combinadas5" = Table.NestedJoin(#"Se expandió SERV_NOW TAREAS - ConDemanda1", {"EVOLUTIVOS_COMPLETO_Number"}, #"SERV_NOW TAREAS - ConDemanda", {"number"}, "SERV_NOW TAREAS - ConDemanda", JoinKind.LeftOuter),
				    #"Consultas combinadas6" = Table.NestedJoin(#"Consultas combinadas5", {"EVOLUTIVOS_COMPLETO_Number"}, #"SERV_NOW TAREAS - SinDemanda", {"TAREAS-SINDEMANDA-number"}, "SERV_NOW TAREAS - SinDemanda", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW TAREAS - SinDemanda" = Table.ExpandTableColumn(#"Consultas combinadas6", "SERV_NOW TAREAS - SinDemanda", {"TAREAS-SINDEMANDA-closed_at", "TAREAS-SINDEMANDA-end_date", "TAREAS-SINDEMANDA-opened_at", "TAREAS-SINDEMANDA-dv_parent", "TAREAS-SINDEMANDA-percent_complete", "TAREAS-SINDEMANDA-dv_priority", "TAREAS-SINDEMANDA-short_description", "TAREAS-SINDEMANDA-start_date", "TAREAS-SINDEMANDA-dv_state", "TAREAS-SINDEMANDA-dv_top_task", "TAREAS-SINDEMANDA-Proyectos_Padre_Evo4&5.dv_phase"}, {"SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-closed_at", "SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-end_date", "SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-opened_at", "SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-dv_parent", "SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-percent_complete", "SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-dv_priority", "SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-short_description", "SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-start_date", "SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-dv_state", "SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-dv_top_task", "SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-Proyectos_Padre_Evo4&5.dv_phase"}),
				    #"Columnas con nombre cambiado13" = Table.RenameColumns(#"Se expandió SERV_NOW TAREAS - SinDemanda",{{"SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-dv_top_task", "TAREAS-SINDEMANDA-dv_top_task"}, {"SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-dv_state", "TAREAS-SINDEMANDA-dv_state"}, {"SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-start_date", "TAREAS-SINDEMANDA-start_date"}, {"SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-short_description", "TAREAS-SINDEMANDA-short_description"}, {"SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-dv_priority", "TAREAS-SINDEMANDA-dv_priority"}, {"SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-percent_complete", "TAREAS-SINDEMANDA-percent_complete"}, {"SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-dv_parent", "TAREAS-SINDEMANDA-dv_parent"}, {"SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-opened_at", "TAREAS-SINDEMANDA-opened_at"}, {"SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-end_date", "TAREAS-SINDEMANDA-end_date"}, {"SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-closed_at", "TAREAS-SINDEMANDA-closed_at"}}),
				    #"Consultas combinadas7" = Table.NestedJoin(#"Columnas con nombre cambiado13", {"EVOLUTIVOS_COMPLETO_Number"}, #"SERV_NOW PROYECTOS - Mto", {"number"}, "SERV_NOW PROYECTOS - Mto", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW PROYECTOS - Mto" = Table.ExpandTableColumn(#"Consultas combinadas7", "SERV_NOW PROYECTOS - Mto", {"short_description", "closed_at","dv_cmdb_ci_business_app", "dv_demand", "number", "opened_at", "dv_parent", "percent_complete", "dv_phase", "dv_priority", "start_date", "end_date", "dv_state", "sys_id", "dv_top_task", "dv_u_project_phase", "dv_u_project_type", "dv_u_project_typology"}, {"SERV_NOW PROYECTOS - Mto.short_description", "SERV_NOW PROYECTOS - Mto.closed_at","SERV_NOW PROYECTOS - Mto.dv_cmdb_ci_business_app", "SERV_NOW PROYECTOS - Mto.dv_demand", "SERV_NOW PROYECTOS - Mto.number", "SERV_NOW PROYECTOS - Mto.opened_at", "SERV_NOW PROYECTOS - Mto.dv_parent", "SERV_NOW PROYECTOS - Mto.percent_complete", "SERV_NOW PROYECTOS - Mto.dv_phase", "SERV_NOW PROYECTOS - Mto.dv_priority", "SERV_NOW PROYECTOS - Mto.start_date", "SERV_NOW PROYECTOS - Mto.end_date", "SERV_NOW PROYECTOS - Mto.dv_state", "SERV_NOW PROYECTOS - Mto.sys_id", "SERV_NOW PROYECTOS - Mto.dv_top_task", "SERV_NOW PROYECTOS - Mto.dv_u_project_phase", "SERV_NOW PROYECTOS - Mto.dv_u_project_type", "SERV_NOW PROYECTOS - Mto.dv_u_project_typology"}),
				    #"Consultas combinadas8" = Table.NestedJoin(#"Se expandió SERV_NOW PROYECTOS - Mto", {"EVOLUTIVOS_COMPLETO_Number"}, #"SERV_NOW pm_project - Multitarea", {"number"}, "SERV_NOW pm_project - Multitarea", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW pm_project - Multitarea" = Table.ExpandTableColumn(#"Consultas combinadas8", "SERV_NOW pm_project - Multitarea", {"opened_at","closed_at", "start_date", "end_date", "dv_priority", "dv_state", "percent_complete", "short_description", "dv_phase", "dv_u_project_type"}, {"SERV_NOW pm_project - Multitarea.opened_at", "SERV_NOW pm_project - Multitarea.closed_at", "SERV_NOW pm_project - Multitarea.start_date", "SERV_NOW pm_project - Multitarea.end_date", "SERV_NOW pm_project - Multitarea.dv_priority", "SERV_NOW pm_project - Multitarea.dv_state", "SERV_NOW pm_project - Multitarea.percent_complete", "SERV_NOW pm_project - Multitarea.short_description", "SERV_NOW pm_project - Multitarea.dv_phase", "SERV_NOW pm_project - Multitarea.dv_u_project_type"}),
				    #"Consultas combinadas9" = Table.NestedJoin(#"Se expandió SERV_NOW pm_project - Multitarea", {"EVOLUTIVOS_COMPLETO_Number"}, #"SERV_NOW rm_enhancement", {"number"}, "SERV_NOW rm_enhancement", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW rm_enhancement" = Table.ExpandTableColumn(#"Consultas combinadas9", "SERV_NOW rm_enhancement", {"opened_at",  "closed_at", "start_date", "end_date", "dv_priority", "dv_state", "percent_complete", "short_description"}, {"SERV_NOW rm_enhancement.opened_at","SERV_NOW rm_enhancement.closed_at", "SERV_NOW rm_enhancement.start_date", "SERV_NOW rm_enhancement.end_date", "SERV_NOW rm_enhancement.dv_priority", "SERV_NOW rm_enhancement.dv_state", "SERV_NOW rm_enhancement.percent_complete", "SERV_NOW rm_enhancement.short_description"}),
				    EVOLUTIVOS_COMPLETO_closed_at = Table.CombineColumns(Table.TransformColumnTypes(#"Se expandió SERV_NOW rm_enhancement", {{"SERV_NOW rm_enhancement.closed_at", type text}, {"SERV_NOW pm_project - Multitarea.closed_at", type text}, {"SERV_NOW PROYECTOS - Mto.closed_at", type text}, {"TAREAS-SINDEMANDA-closed_at", type text}, {"SERV_NOW TAREAS - ConDemanda.closed_at", type text}}, "es-ES"),{"SERV_NOW rm_enhancement.closed_at", "SERV_NOW pm_project - Multitarea.closed_at", "SERV_NOW PROYECTOS - Mto.closed_at", "TAREAS-SINDEMANDA-closed_at", "SERV_NOW TAREAS - ConDemanda.closed_at"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"EVOLUTIVOS_COMPLETO_closed_at"),
				    EVOLUTIVOS_COMPLETO_opened_at = Table.CombineColumns(Table.TransformColumnTypes(EVOLUTIVOS_COMPLETO_closed_at, {{"SERV_NOW rm_enhancement.opened_at", type text}, {"SERV_NOW pm_project - Multitarea.opened_at", type text}, {"SERV_NOW PROYECTOS - Mto.opened_at", type text}, {"TAREAS-SINDEMANDA-opened_at", type text}, {"SERV_NOW TAREAS - ConDemanda.opened_at", type text}}, "es-ES"),{"SERV_NOW rm_enhancement.opened_at", "SERV_NOW pm_project - Multitarea.opened_at", "SERV_NOW PROYECTOS - Mto.opened_at", "TAREAS-SINDEMANDA-opened_at", "SERV_NOW TAREAS - ConDemanda.opened_at"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"EVOLUTIVOS_COMPLETO_opened_at"),
				    EVOLUTIVOS_COMPLETO_start_date = Table.CombineColumns(Table.TransformColumnTypes(EVOLUTIVOS_COMPLETO_opened_at, {{"SERV_NOW rm_enhancement.start_date", type text}, {"SERV_NOW pm_project - Multitarea.start_date", type text}, {"SERV_NOW PROYECTOS - Mto.start_date", type text}, {"TAREAS-SINDEMANDA-start_date", type text}, {"SERV_NOW TAREAS - ConDemanda.start_date", type text}}, "es-ES"),{"SERV_NOW rm_enhancement.start_date", "SERV_NOW pm_project - Multitarea.start_date", "SERV_NOW PROYECTOS - Mto.start_date", "TAREAS-SINDEMANDA-start_date", "SERV_NOW TAREAS - ConDemanda.start_date"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"EVOLUTIVOS_COMPLETO_start_date"),
				    EVOLUTIVOS_COMPLETO_end_date = Table.CombineColumns(Table.TransformColumnTypes(EVOLUTIVOS_COMPLETO_start_date, {{"SERV_NOW pm_project - Multitarea.end_date", type text}, {"SERV_NOW rm_enhancement.end_date", type text}, {"SERV_NOW PROYECTOS - Mto.end_date", type text}, {"TAREAS-SINDEMANDA-end_date", type text}, {"SERV_NOW TAREAS - ConDemanda.end_date", type text}}, "es-ES"),{"SERV_NOW pm_project - Multitarea.end_date", "SERV_NOW rm_enhancement.end_date", "SERV_NOW PROYECTOS - Mto.end_date", "TAREAS-SINDEMANDA-end_date", "SERV_NOW TAREAS - ConDemanda.end_date"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"EVOLUTIVOS_COMPLETO_end_date"),
				    EVOLUTIVOS_COMPLETO_dv_priority = Table.CombineColumns(EVOLUTIVOS_COMPLETO_end_date,{"SERV_NOW rm_enhancement.dv_priority", "SERV_NOW pm_project - Multitarea.dv_priority", "SERV_NOW PROYECTOS - Mto.dv_priority", "TAREAS-SINDEMANDA-dv_priority", "SERV_NOW TAREAS - ConDemanda.dv_priority"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"EVOLUTIVOS_COMPLETO_dv_priority"),
				    EVOLUTIVOS_COMPLETO_dv_state = Table.CombineColumns(EVOLUTIVOS_COMPLETO_dv_priority,{"SERV_NOW rm_enhancement.dv_state", "SERV_NOW pm_project - Multitarea.dv_state", "SERV_NOW PROYECTOS - Mto.dv_state", "TAREAS-SINDEMANDA-dv_state", "SERV_NOW TAREAS - ConDemanda.dv_state"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"EVOLUTIVOS_COMPLETO_dv_state"),
				    EVOLUTIVOS_COMPLETO_percent_complete = Table.CombineColumns(Table.TransformColumnTypes(EVOLUTIVOS_COMPLETO_dv_state, {{"SERV_NOW rm_enhancement.percent_complete", type text}, {"SERV_NOW pm_project - Multitarea.percent_complete", type text}, {"SERV_NOW PROYECTOS - Mto.percent_complete", type text}, {"TAREAS-SINDEMANDA-percent_complete", type text}, {"SERV_NOW TAREAS - ConDemanda.percent_complete", type text}}, "es-ES"),{"SERV_NOW rm_enhancement.percent_complete", "SERV_NOW pm_project - Multitarea.percent_complete", "SERV_NOW PROYECTOS - Mto.percent_complete", "TAREAS-SINDEMANDA-percent_complete", "SERV_NOW TAREAS - ConDemanda.percent_complete"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"EVOLUTIVOS_COMPLETO_percent_complete"),
				    EVOLUTIVOS_COMPLETO_short_description = Table.CombineColumns(Table.TransformColumnTypes(EVOLUTIVOS_COMPLETO_percent_complete, {{"SERV_NOW PROYECTOS - Mto.short_description", type text}}, "es-ES"),{"SERV_NOW rm_enhancement.short_description", "SERV_NOW pm_project - Multitarea.short_description", "SERV_NOW PROYECTOS - Mto.short_description", "TAREAS-SINDEMANDA-short_description", "SERV_NOW TAREAS - ConDemanda.short_description"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"EVOLUTIVOS_COMPLETO_short_description"),
				    #"Tipo cambiado4" = Table.TransformColumnTypes(EVOLUTIVOS_COMPLETO_short_description,{{"EVOLUTIVOS_COMPLETO_percent_complete", type number}}),
				    EVOLUTIVOS_PROYECTOS_PROYECTOSPADRE_dv_phase = Table.CombineColumns(#"Tipo cambiado4",{"SERV_NOW pm_project.dv_phase", "SERV_NOW TAREAS - SinDemanda.TAREAS-SINDEMANDA-Proyectos_Padre_Evo4&5.dv_phase", "SERV_NOW TAREAS - ConDemandaProyectos_Padre_Evo4&5.dv_phase"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"EVOLUTIVOS_PROYECTOS_PROYECTOSPADRE_dv_phase"),
				    #"Columna duplicada2" = Table.DuplicateColumn(EVOLUTIVOS_PROYECTOS_PROYECTOSPADRE_dv_phase, "dv_size", "dv_size - Copia"),
				    #"Columnas con nombre cambiado4" = Table.RenameColumns(#"Columna duplicada2",{{"dv_size - Copia", "_dv_size - SoloLetra"}}),
				    #"Dividir columna por delimitador1" = Table.SplitColumn(#"Columnas con nombre cambiado4", "_dv_size - SoloLetra", Splitter.SplitTextByDelimiter(":", QuoteStyle.Csv), {"_dv_size - SoloLetra.1", "_dv_size - SoloLetra.2"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Dividir columna por delimitador1",{{"_dv_size - SoloLetra.1", type text}, {"_dv_size - SoloLetra.2", type text}}),
				    #"Columnas con nombre cambiado5" = Table.RenameColumns(#"Tipo cambiado1",{{"_dv_size - SoloLetra.2", "_dv_size - Texto"}, {"_dv_size - SoloLetra.1", "_dv_size - SoloLetra"}}),
				    #"Columna duplicada3" = Table.DuplicateColumn(#"Columnas con nombre cambiado5", "EVOLUTIVOS_COMPLETO_opened_at", "EVOLUTIVOS_COMPLETO_opened_at - Copia"),
				    #"Columnas con nombre cambiado6" = Table.RenameColumns(#"Columna duplicada3",{{"EVOLUTIVOS_COMPLETO_opened_at - Copia", "EVOLUTIVOS_COMPLETO_opened_at - Formato Fecha"}}),
				    #"Columnas quitadas3" = Table.RemoveColumns(#"Columnas con nombre cambiado6",{"EVOLUTIVOS_COMPLETO_opened_at - Formato Fecha", "u_tic_unit", "dv_u_tic_unit", "u_time_to_manage_a_demand", "u_time_to_reach_analysis", "u_total_effort", "u_total_effort_req", "dv_u_total_effort_req", "u_volume_impacted_users", "universal_request", "dv_universal_request", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "user_input", "variables", "visited_state", "watch_list", "wf_activity", "dv_wf_activity", "work_notes", "work_notes_list"}),
				    #"Columnas quitadas4" = Table.RemoveColumns(#"Columnas quitadas3",{"u_duration_to_manage_a_demand", "dv_u_duration_to_manage_a_demand", "u_duration_to_reach_analysis", "dv_u_duration_to_reach_analysis", "u_parent_demand", "dv_u_parent_demand"}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Columnas quitadas4", "EVOLUTIVOS_FINAL_dv_priority", each if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_priority], "1 - Critical") then "1 - Crítica" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_priority], "2 - High") then "2 - Alta" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_priority], "3 - Moderate") then "3 - Moderada" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_priority], "4 - Low") then "4 - Baja" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_priority], "5 - Very Low") then "5 - Muy Baja" else null),
				    #"Columna condicional agregada1" = Table.AddColumn(#"Columna condicional agregada", "EVOLUTIVOS_FINAL_dv_state", each if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "Open") then "Abierto" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "Work in Progress") then "En curso" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "Pendig") then "Pendiente" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "Closed Complete") then "Cerrado completo" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "Closed Incomplete") then "Cerrado incompleto" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "Closed Skipped") then "Cerrado omitido" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "Draft") then "Borrador" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "In Analysis") then "En Análisis" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "In Development") then "En proceso" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "Testing/QA") then "En pruebas" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "Deploy/Launch") then "Despliegue" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "On Hold") then "En espera" else if Text.StartsWith([EVOLUTIVOS_COMPLETO_dv_state], "Cancelled") then "Cancelado" else null),
				    #"Columna duplicada6" = Table.DuplicateColumn(#"Columna condicional agregada1", "EVOLUTIVOS_COMPLETO_Number", "EVOLUTIVOS_COMPLETO_Number - Copia"),
				    #"Columnas con nombre cambiado11" = Table.RenameColumns(#"Columna duplicada6",{{"EVOLUTIVOS_COMPLETO_Number - Copia", "EVOLUTIVOS_COMPLETO_Number - URL"}}),
				    #"Columna condicional agregada2" = Table.AddColumn(#"Columnas con nombre cambiado11", "Personalizado", each if Text.StartsWith([#"EVOLUTIVOS_COMPLETO_Number - URL"], "PRJTASK") then "Tarea" else if Text.StartsWith([#"EVOLUTIVOS_COMPLETO_Number - URL"], "ENHC") then "Mejora" else if Text.StartsWith([#"EVOLUTIVOS_COMPLETO_Number - URL"], "PRJ0") then "Proyecto" else null),
				    #"Columnas con nombre cambiado12" = Table.RenameColumns(#"Columna condicional agregada2",{{"Personalizado", "TABLA_SEGUN_ID"}}),
				    #"Columna duplicada4" = Table.DuplicateColumn(#"Columnas con nombre cambiado12", "EVOLUTIVOS_COMPLETO_start_date", "EVOLUTIVOS_COMPLETO_start_date - Copia"),
				    #"Columnas con nombre cambiado7" = Table.RenameColumns(#"Columna duplicada4",{{"EVOLUTIVOS_COMPLETO_start_date - Copia", "EVOLUTIVOS_COMPLETO_Fecha Apertura"}}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas con nombre cambiado7",{{"EVOLUTIVOS_COMPLETO_Fecha Apertura", type datetime}}),
				    #"Columnas con nombre cambiado8" = Table.RenameColumns(#"Tipo cambiado2",{{"EVOLUTIVOS_COMPLETO_Fecha Apertura", "EVOLUTIVOS_COMPLETO_Fecha Apertura ConFormatoFecha"}}),
				    #"Columna duplicada5" = Table.DuplicateColumn(#"Columnas con nombre cambiado8", "EVOLUTIVOS_COMPLETO_Fecha Apertura ConFormatoFecha", "EVOLUTIVOS_COMPLETO_Fecha Apertura ConFormatoFecha - Copia"),
				    #"Columnas con nombre cambiado9" = Table.RenameColumns(#"Columna duplicada5",{{"EVOLUTIVOS_COMPLETO_Fecha Apertura ConFormatoFecha - Copia", "EVOLUTIVOS_COMPLETO_Fecha Apertura"}}),
				    #"Fecha extraída" = Table.TransformColumns(#"Columnas con nombre cambiado9",{{"EVOLUTIVOS_COMPLETO_Fecha Apertura", DateTime.Date, type date}}),
				    #"Columna duplicada7" = Table.DuplicateColumn(#"Fecha extraída", "EVOLUTIVOS_COMPLETO_closed_at", "EVOLUTIVOS_COMPLETO_closed_at - Copia"),
				    #"Columnas con nombre cambiado10" = Table.RenameColumns(#"Columna duplicada7",{{"EVOLUTIVOS_COMPLETO_closed_at - Copia", "EVOLUTIVOS_COMPLETO_Fecha Cierre ConFormato"}}),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Columnas con nombre cambiado10",{{"EVOLUTIVOS_COMPLETO_Fecha Cierre ConFormato", type datetime}}),
				    #"Columna duplicada8" = Table.DuplicateColumn(#"Tipo cambiado3", "EVOLUTIVOS_COMPLETO_Fecha Cierre ConFormato", "EVOLUTIVOS_COMPLETO_Fecha Cierre ConFormato - Copia"),
				    #"Columnas con nombre cambiado14" = Table.RenameColumns(#"Columna duplicada8",{{"EVOLUTIVOS_COMPLETO_Fecha Cierre ConFormato - Copia", "EVOLUTIVOS_COMPLETO_Fecha Cierre"}}),
				    #"Fecha extraída1" = Table.TransformColumns(#"Columnas con nombre cambiado14",{{"EVOLUTIVOS_COMPLETO_Fecha Cierre", DateTime.Date, type date}}),
				    #"Columna condicional agregada3" = Table.AddColumn(#"Fecha extraída1", "Personalizado", each if [dv_type] = "Service Upgrade" then "Evolución" else null),
				    #"Columnas con nombre cambiado15" = Table.RenameColumns(#"Columna condicional agregada3",{{"Personalizado", "_dv_type - español"}}),
				    #"Columna condicional agregada4" = Table.AddColumn(#"Columnas con nombre cambiado15", "Personalizado", each if [PRJs_TOPTASKs_dv_u_project_type] = "Multitask Enhancement" then "Evolutivo Multitarea" else if [PRJs_TOPTASKs_dv_u_project_type] = "Applications Maintenance" then "Mantenimiento de Aplicaciones" else null),
				    #"Columnas con nombre cambiado16" = Table.RenameColumns(#"Columna condicional agregada4",{{"Personalizado", "PRJs_TOPTASKs_dv_u_project_type - español"}}),
				    #"Columna condicional agregada5" = Table.AddColumn(#"Columnas con nombre cambiado16", "EVOLUTIVOS_PROYECTOS_PROYECTOSPADRE_dv_phase-español", each if [EVOLUTIVOS_PROYECTOS_PROYECTOSPADRE_dv_phase] = "Initiating" then "Iniciando" else if [EVOLUTIVOS_PROYECTOS_PROYECTOSPADRE_dv_phase] = "Planning" then "Planificación" else if [EVOLUTIVOS_PROYECTOS_PROYECTOSPADRE_dv_phase] = "Executing" then "Ejecución" else if [EVOLUTIVOS_PROYECTOS_PROYECTOSPADRE_dv_phase] = "Closing" then "Cierre" else null),
				    #"Filas ordenadas" = Table.Sort(#"Columna condicional agregada5",{{"number", Order.Descending}, {"EVOLUTIVOS_COMPLETO_Number - URL", Order.Ascending}}),
				    #"Columna condicional agregada6" = Table.AddColumn(#"Filas ordenadas", "DEMANDA_NUMBER_FICTICIO", each if [number] = null then [EVOLUTIVOS_COMPLETO_Number] else [number]),
				    #"Duplicados quitados1" = Table.Distinct(#"Columna condicional agregada6", {"DEMANDA_NUMBER_FICTICIO"}),
				    #"Columnas quitadas6" = Table.RemoveColumns(#"Duplicados quitados1",{"TABLA_SEGUN_ID", "EVOLUTIVOS_COMPLETO_Fecha Apertura ConFormatoFecha", "EVOLUTIVOS_COMPLETO_Fecha Apertura", "EVOLUTIVOS_COMPLETO_Fecha Cierre ConFormato", "EVOLUTIVOS_COMPLETO_Fecha Cierre", "_dv_type - español", "PRJs_TOPTASKs_dv_u_project_type - español", "EVOLUTIVOS_PROYECTOS_PROYECTOSPADRE_dv_phase-español", "sys_updated_on", "task_effective_number", "total_costs", "type", "dv_type", "u_actual_end_date", "u_actual_start_date", "u_approved_date", "u_business_applications", "u_demand_category", "dv_u_demand_category", "u_impact", "dv_u_impact", "u_is_parent", "u_metal", "dv_u_metal", "u_module", "dv_u_module", "u_old_state", "u_openned_up", "u_progress", "u_project_manager", "dv_u_project_manager", "u_qualification_date", "u_rejected_date", "u_relevant", "u_responded", "u_rfp", "dv_u_rfp", "u_run", "u_run_description", "u_size", "dv_u_size", "u_sourcing", "u_start_date", "u_state_date", "u_status_report", "u_subcategory", "dv_u_subcategory", "u_submission_date", "u_total_budget", "u_total_planned_hours", "urgency", "dv_urgency", "work_end", "work_start", "SERV_NOW pm_project.phase", "SERV_NOW pm_project.priority", "SERV_NOW pm_project.state", "SERV_NOW pm_project.dv_cmdb_ci_business_app", "SERV_NOW pm_project.short_description", "PRJs_ENHs-ID", "PRJs_ENHs_closed_at", "PRJs_ENHs_end_date", "PRJs_ENHs_opened_at", "PRJs_ENHs_percent_complete", "DEMANDAS-MEJORAS.priority", "PJRs_ENHs_Prioridad", "PRJs_ENHs_start_date", "DEMANDAS-MEJORAS.state", "PRJs_ENHs_Estado", "DEMANDAS-MEJORAS.dv_u_business_application", "DEMANDAS-MEJORAS.short_description", "EVOLUTIVOS_COMPLETO_Number", "dv_top_portfolio", "SERV_NOW pm_project - Mto.number", "SERV_NOW pm_project - Mto.sys_id", "PRJs_TOPTASKs_dv_u_project_type", "TAREAS-SINDEMANDA-Proyectos_Padre_Evo4&5.dv_phase", "EVOLUTIVOS-ConTareasSinDemanda", "EVOLUTIVOS_COMPLETO_closed_at", "EVOLUTIVOS_COMPLETO_end_date", "EVOLUTIVOS_COMPLETO_opened_at", "SERV_NOW TAREAS - ConDemanda.dv_parent", "EVOLUTIVOS_COMPLETO_percent_complete", "EVOLUTIVOS_COMPLETO_dv_priority", "EVOLUTIVOS_COMPLETO_short_description", "EVOLUTIVOS_COMPLETO_start_date", "EVOLUTIVOS_COMPLETO_dv_state", "SERV_NOW TAREAS - ConDemanda.dv_top_task", "EVOLUTIVOS_PROYECTOS_PROYECTOSPADRE_dv_phase", "SERV_NOW TAREAS - ConDemanda", "TAREAS-SINDEMANDA-dv_parent", "TAREAS-SINDEMANDA-dv_top_task", "SERV_NOW PROYECTOS - Mto.dv_cmdb_ci_business_app", "SERV_NOW PROYECTOS - Mto.dv_demand", "SERV_NOW PROYECTOS - Mto.number", "SERV_NOW PROYECTOS - Mto.dv_parent", "SERV_NOW PROYECTOS - Mto.dv_phase", "SERV_NOW PROYECTOS - Mto.sys_id", "SERV_NOW PROYECTOS - Mto.dv_top_task", "SERV_NOW PROYECTOS - Mto.dv_u_project_phase", "SERV_NOW PROYECTOS - Mto.dv_u_project_type", "SERV_NOW PROYECTOS - Mto.dv_u_project_typology", "SERV_NOW pm_project - Multitarea.dv_phase", "SERV_NOW pm_project - Multitarea.dv_u_project_type", "_dv_size - SoloLetra", "_dv_size - Texto", "EVOLUTIVOS_FINAL_dv_priority", "EVOLUTIVOS_FINAL_dv_state", "opened_at", "operational_budget", "operational_outlay", "parent", "portfolio", "dv_portfolio", "priority", "dv_priority", "project", "dv_project", "related_records", "short_description", "size", "dv_size", "start_date", "state", "dv_state", "submitted_date", "sys_created_on", "active", "business_applications", "capital_budget", "capital_outlay", "category", "dv_category", "closed_at", "cmdb_ci_business_app", "dv_cmdb_ci_business_app", "demand", "demand_actual_cost", "enhancement", "dv_enhancement", "financial_benefit", "financial_return", "impact", "dv_impact", "impacted_business_units"}),
				    #"Consultas combinadas3" = Table.NestedJoin(#"Columnas quitadas6", {"EVOLUTIVOS_COMPLETO_Number - URL"}, #"SERV_NOW dmn_demand", {"EVOLUTIVOS_COMPLETO_Number - URL"}, "SERV_NOW dmn_demand", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW dmn_demand" = Table.ExpandTableColumn(#"Consultas combinadas3", "SERV_NOW dmn_demand", {"PortfolioVisualizarEnergia_FINAL", "EVOLUTIVOS_COMPLETO_PortfolioaMostrar"}, {"SERV_NOW dmn_demand.PortfolioVisualizarEnergia_FINAL", "SERV_NOW dmn_demand.EVOLUTIVOS_COMPLETO_PortfolioaMostrar"}),
				    #"Filas filtradas2" = Table.SelectRows(#"Se expandió SERV_NOW dmn_demand", each ([SERV_NOW dmn_demand.PortfolioVisualizarEnergia_FINAL] = "SI"))
				in
				    #"Filas filtradas2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

