table 'SERV_NOW rm_enhancement'
	lineageTag: 190576fc-2090-48a6-8594-7bc0c58875a3

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e36083b8-f2a9-4889-8cd2-cb77bff2522c
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column activity_due
		dataType: dateTime
		formatString: General Date
		lineageTag: 2c10c46f-648b-432c-a6b3-d9809eedbc00
		summarizeBy: none
		sourceColumn: activity_due

		variation Variación
			isDefault
			relationship: 9bf2becc-2ece-481e-908c-e147ce4656c2
			defaultHierarchy: LocalDateTable_7646ea9f-a210-4d27-aa9d-58355491af27.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column actual_benefits
		dataType: double
		lineageTag: 7404d8dd-4291-4a48-9168-b8db18783479
		summarizeBy: sum
		sourceColumn: actual_benefits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column additional_assignee_list
		dataType: string
		lineageTag: 909aae3d-d2ec-47c6-a961-1d881076a965
		summarizeBy: none
		sourceColumn: additional_assignee_list

		annotation SummarizationSetBy = Automatic

	column allow_dates_outside_schedule
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: af2a3c06-0b63-421e-8a55-0b2804bac5cc
		summarizeBy: none
		sourceColumn: allow_dates_outside_schedule

		annotation SummarizationSetBy = Automatic

	column approval
		dataType: string
		lineageTag: ca8c0ed2-62bf-4421-a83b-cf88f30b730d
		summarizeBy: none
		sourceColumn: approval

		annotation SummarizationSetBy = Automatic

	column dv_approval
		dataType: string
		lineageTag: f9f6f0fa-5cf1-466f-a17a-a32e5026a7b3
		summarizeBy: none
		sourceColumn: dv_approval

		annotation SummarizationSetBy = Automatic

	column approval_history
		dataType: string
		lineageTag: ce0fdf00-5c30-4271-b807-ca3999d80fa2
		summarizeBy: none
		sourceColumn: approval_history

		annotation SummarizationSetBy = Automatic

	column approval_set
		dataType: dateTime
		formatString: General Date
		lineageTag: aa955acc-3267-437e-94fc-2c00707b85b0
		summarizeBy: none
		sourceColumn: approval_set

		variation Variación
			isDefault
			relationship: fc98654b-1021-4c5c-880a-b54a5d152437
			defaultHierarchy: LocalDateTable_bcfdb32c-0cc1-42da-b038-019cfe3cc5e0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column assigned_to
		dataType: string
		lineageTag: 8eda2cbb-0fba-4f81-9f3c-cd749a51a35b
		summarizeBy: none
		sourceColumn: assigned_to

		annotation SummarizationSetBy = Automatic

	column dv_assigned_to
		dataType: string
		lineageTag: e759b3f0-0fc5-4ba0-909f-b6ae3f788e22
		summarizeBy: none
		sourceColumn: dv_assigned_to

		annotation SummarizationSetBy = Automatic

	column assignment_group
		dataType: string
		lineageTag: 045c080c-aa9b-49a7-b914-c9652a81f8a4
		summarizeBy: none
		sourceColumn: assignment_group

		annotation SummarizationSetBy = Automatic

	column dv_assignment_group
		dataType: string
		lineageTag: 6cd92bed-44f8-4b94-bc42-9bf424640a4b
		summarizeBy: none
		sourceColumn: dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column benefits
		dataType: double
		lineageTag: 36b7b0df-4e4b-45ac-a4f6-75b75c8945bc
		summarizeBy: sum
		sourceColumn: benefits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column budget_cost
		dataType: double
		lineageTag: 30a2c909-5231-4ff0-b45e-472b3178929f
		summarizeBy: sum
		sourceColumn: budget_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column business_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: fbbcfd50-f148-4a61-b1fd-8f64d433405d
		summarizeBy: none
		sourceColumn: business_duration

		variation Variación
			isDefault
			relationship: f0ed9c04-6424-4dbc-a854-6342b08720bc
			defaultHierarchy: LocalDateTable_536adfe2-d6dc-44ef-8757-c12e8ec87c5b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_business_duration
		dataType: string
		lineageTag: bd46d4aa-cbe0-4baf-993d-d469594890a9
		summarizeBy: none
		sourceColumn: dv_business_duration

		annotation SummarizationSetBy = Automatic

	column business_service
		dataType: string
		lineageTag: 12edcdb4-e459-43ef-b1b9-03e27068d353
		summarizeBy: none
		sourceColumn: business_service

		annotation SummarizationSetBy = Automatic

	column dv_business_service
		dataType: string
		lineageTag: b93a0823-1b72-4dcf-b0dd-4df188481374
		summarizeBy: none
		sourceColumn: dv_business_service

		annotation SummarizationSetBy = Automatic

	column calculation_type
		dataType: string
		lineageTag: 4d94e007-7da4-43c5-bdb7-3e0586465bac
		summarizeBy: none
		sourceColumn: calculation_type

		annotation SummarizationSetBy = Automatic

	column dv_calculation_type
		dataType: string
		lineageTag: 7aaf5f64-9bdd-48e8-9545-5d6e0f086e0d
		summarizeBy: none
		sourceColumn: dv_calculation_type

		annotation SummarizationSetBy = Automatic

	column calendar_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 5dfac409-8963-470c-924d-ea8d1df079dc
		summarizeBy: none
		sourceColumn: calendar_duration

		variation Variación
			isDefault
			relationship: 9de8c01e-2c12-4c14-9dcc-40dd0eceff81
			defaultHierarchy: LocalDateTable_a47585fa-1bb6-48b8-bc84-b7307f94cccb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_calendar_duration
		dataType: string
		lineageTag: caf0cf13-795a-448e-bd5b-046af365471d
		summarizeBy: none
		sourceColumn: dv_calendar_duration

		annotation SummarizationSetBy = Automatic

	column capex_cost
		dataType: double
		lineageTag: 63af3a88-75a5-404e-9373-a82e80ceb9d4
		summarizeBy: sum
		sourceColumn: capex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column close_notes
		dataType: string
		lineageTag: 4b6aa117-c863-4de2-948b-dc74a1c06128
		summarizeBy: none
		sourceColumn: close_notes

		annotation SummarizationSetBy = Automatic

	column closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 061fb740-3342-4dd9-a4fa-8f7159eb7553
		summarizeBy: none
		sourceColumn: closed_at

		variation Variación
			isDefault
			relationship: d58d16d2-64b9-41cd-8e4a-700cf38bc407
			defaultHierarchy: LocalDateTable_9f3fa329-f4f8-419f-8dc6-c7c9d0420719.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column closed_by
		dataType: string
		lineageTag: 05820553-c1cf-4e32-8efd-01d0d6b289f5
		summarizeBy: none
		sourceColumn: closed_by

		annotation SummarizationSetBy = Automatic

	column dv_closed_by
		dataType: string
		lineageTag: e68123b3-ace8-44d1-956a-fa6bf43d10a0
		summarizeBy: none
		sourceColumn: dv_closed_by

		annotation SummarizationSetBy = Automatic

	column cmdb_ci
		dataType: string
		lineageTag: 7463c2b5-220e-4369-9ebf-71f0d88b1b26
		summarizeBy: none
		sourceColumn: cmdb_ci

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci
		dataType: string
		lineageTag: e6beaf68-849c-4d0e-8bef-e9a202102b4d
		summarizeBy: none
		sourceColumn: dv_cmdb_ci

		annotation SummarizationSetBy = Automatic

	column cmdb_ci_business_app
		dataType: string
		lineageTag: 4b61d687-2be1-40a9-a821-ec34bc96e9d7
		summarizeBy: none
		sourceColumn: cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column dv_cmdb_ci_business_app
		dataType: string
		lineageTag: f79e86c2-d10b-4715-a358-9a22659a03b1
		summarizeBy: none
		sourceColumn: dv_cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column comments
		dataType: string
		lineageTag: 4852d549-4b61-4f8c-9981-eba2a4d6694c
		summarizeBy: none
		sourceColumn: comments

		annotation SummarizationSetBy = Automatic

	column comments_and_work_notes
		dataType: string
		lineageTag: c209d50c-57cd-460a-8633-0883fe23a2c1
		summarizeBy: none
		sourceColumn: comments_and_work_notes

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 3a72b75a-a6ab-4e60-84c9-252402632975
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column dv_company
		dataType: string
		lineageTag: e62d39f9-07cd-41f2-b69c-b94a60ab1cea
		summarizeBy: none
		sourceColumn: dv_company

		annotation SummarizationSetBy = Automatic

	column constraint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: fd7c859c-726f-40b1-9ee8-b8cc3079ce66
		summarizeBy: none
		sourceColumn: constraint_date

		variation Variación
			isDefault
			relationship: d777ff1e-2de9-4d1a-87a8-371baf6d88c4
			defaultHierarchy: LocalDateTable_9433691e-eb96-4053-bf0f-c69095dc42ed.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column contact_type
		dataType: string
		lineageTag: f86fc575-6a4e-484d-88ec-94bf43a44661
		summarizeBy: none
		sourceColumn: contact_type

		annotation SummarizationSetBy = Automatic

	column dv_contact_type
		dataType: string
		lineageTag: 7c77b5cd-5eb4-425c-a989-13d324c6789f
		summarizeBy: none
		sourceColumn: dv_contact_type

		annotation SummarizationSetBy = Automatic

	column correlation_display
		dataType: string
		lineageTag: 6dc1d382-39c6-46f0-a669-d88410e4f1da
		summarizeBy: none
		sourceColumn: correlation_display

		annotation SummarizationSetBy = Automatic

	column correlation_id
		dataType: string
		lineageTag: c5b91795-3b2b-4da6-8d4f-19b7058027eb
		summarizeBy: none
		sourceColumn: correlation_id

		annotation SummarizationSetBy = Automatic

	column cost
		dataType: double
		lineageTag: 5c673b96-f271-4d95-a06b-e7db2e7c2871
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column critical_path
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b359b465-3bc4-4bc7-b2d0-51f32ea95feb
		summarizeBy: none
		sourceColumn: critical_path

		annotation SummarizationSetBy = Automatic

	column delivery_plan
		dataType: string
		lineageTag: 0d63eafb-9088-4cf2-a96e-46e3af49d6c0
		summarizeBy: none
		sourceColumn: delivery_plan

		annotation SummarizationSetBy = Automatic

	column dv_delivery_plan
		dataType: string
		lineageTag: 2c192e80-fdb6-46ec-af41-fbbbc631c763
		summarizeBy: none
		sourceColumn: dv_delivery_plan

		annotation SummarizationSetBy = Automatic

	column delivery_task
		dataType: string
		lineageTag: b4ccb383-67d1-445f-8459-47979696da3b
		summarizeBy: none
		sourceColumn: delivery_task

		annotation SummarizationSetBy = Automatic

	column dv_delivery_task
		dataType: string
		lineageTag: 3e20b8e9-91f7-45dd-96d2-38a32244b3b6
		summarizeBy: none
		sourceColumn: dv_delivery_task

		annotation SummarizationSetBy = Automatic

	column dependency
		dataType: string
		lineageTag: 6732dda2-9ce3-4ebf-b018-d3b7878d9a41
		summarizeBy: none
		sourceColumn: dependency

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: d8f1630b-18de-4956-854e-af2806c2e70c
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column due_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 5ed28e9f-6f18-4dec-a160-8cdb13508fd6
		summarizeBy: none
		sourceColumn: due_date

		variation Variación
			isDefault
			relationship: 475b8bbf-3d04-47bb-a971-e8a702c3f811
			defaultHierarchy: LocalDateTable_2bdb79d5-11a7-4488-8200-68895a35e93e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column duration
		dataType: dateTime
		formatString: General Date
		lineageTag: 37336229-a169-455f-b127-c0c1420b3270
		summarizeBy: none
		sourceColumn: duration

		variation Variación
			isDefault
			relationship: 8fac4494-85a1-41fd-ae98-eae39b81fc6a
			defaultHierarchy: LocalDateTable_b5337f65-f392-4168-9b87-8599c59b190b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_duration
		dataType: string
		lineageTag: 5c1b1f86-fb27-41bf-8bf0-4f5d966be0de
		summarizeBy: none
		sourceColumn: dv_duration

		annotation SummarizationSetBy = Automatic

	column effort
		dataType: dateTime
		formatString: General Date
		lineageTag: e68dbcdc-0606-4e62-b1aa-7ae92c3fe412
		summarizeBy: none
		sourceColumn: effort

		variation Variación
			isDefault
			relationship: affd924d-a347-442a-b52e-b30f7f39d75f
			defaultHierarchy: LocalDateTable_01d3e5dd-a866-46e3-87f3-60479aa96520.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_effort
		dataType: string
		lineageTag: 67709340-1e61-4cb4-82bc-fb139f3afb12
		summarizeBy: none
		sourceColumn: dv_effort

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3d44170d-982f-4aee-bd05-698db3b07208
		summarizeBy: none
		sourceColumn: end_date

		variation Variación
			isDefault
			relationship: 288927eb-36c6-4af5-8205-d65c3817a908
			defaultHierarchy: LocalDateTable_9dcc8a85-c1c4-4654-96f4-7399f4ce293b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column end_date_derived_from
		dataType: string
		lineageTag: 8d655bb0-4e67-41ee-92c0-10f359368dde
		summarizeBy: none
		sourceColumn: end_date_derived_from

		annotation SummarizationSetBy = Automatic

	column dv_end_date_derived_from
		dataType: string
		lineageTag: dac23f2a-3087-4715-97f8-7d5f73bb14f5
		summarizeBy: none
		sourceColumn: dv_end_date_derived_from

		annotation SummarizationSetBy = Automatic

	column escalation
		dataType: int64
		formatString: 0
		lineageTag: e81745b0-aeba-433e-b73c-d87c5fdc3ee8
		summarizeBy: sum
		sourceColumn: escalation

		annotation SummarizationSetBy = Automatic

	column dv_escalation
		dataType: string
		lineageTag: c11b5342-fddb-4c14-949e-8272fef563a0
		summarizeBy: none
		sourceColumn: dv_escalation

		annotation SummarizationSetBy = Automatic

	column expected_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 22ee7d96-c6c1-4326-b76d-99b4ad186b36
		summarizeBy: none
		sourceColumn: expected_start

		variation Variación
			isDefault
			relationship: 62092ed4-2de0-4a5d-bf27-62adcdd76e89
			defaultHierarchy: LocalDateTable_65b10960-3052-402c-9d34-6507f76bf620.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column follow_up
		dataType: dateTime
		formatString: General Date
		lineageTag: 1c05684c-ea4e-4a43-a0db-80847e4bd14a
		summarizeBy: none
		sourceColumn: follow_up

		variation Variación
			isDefault
			relationship: 26955ba4-10b4-4d62-9ba9-c48d926e190a
			defaultHierarchy: LocalDateTable_44ea64d4-6a41-4633-aa45-6e483a68b807.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column group_list
		dataType: string
		lineageTag: e86fcac0-4b8e-46c7-b7ba-bb1fd514b278
		summarizeBy: none
		sourceColumn: group_list

		annotation SummarizationSetBy = Automatic

	column has_conflict
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e2777653-a13a-46e4-92f7-79e665ab757d
		summarizeBy: none
		sourceColumn: has_conflict

		annotation SummarizationSetBy = Automatic

	column html_description
		dataType: string
		lineageTag: 905c3f2a-77e7-4960-ab18-a27ee660965d
		summarizeBy: none
		sourceColumn: html_description

		annotation SummarizationSetBy = Automatic

	column impact
		dataType: int64
		formatString: 0
		lineageTag: 5ac57c69-e8bc-49dd-983c-155ad5581da2
		summarizeBy: sum
		sourceColumn: impact

		annotation SummarizationSetBy = Automatic

	column dv_impact
		dataType: string
		lineageTag: 0b5a0f5e-841c-48c4-a56d-1998f0532b58
		summarizeBy: none
		sourceColumn: dv_impact

		annotation SummarizationSetBy = Automatic

	column key_milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f155042b-e001-4350-8070-c88f2883e21c
		summarizeBy: none
		sourceColumn: key_milestone

		annotation SummarizationSetBy = Automatic

	column knowledge
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9eae3e9b-f87b-44ee-a38a-50863d8e6061
		summarizeBy: none
		sourceColumn: knowledge

		annotation SummarizationSetBy = Automatic

	column level
		dataType: int64
		formatString: 0
		lineageTag: a3665415-57bf-4e55-8484-bc667f7bbd45
		summarizeBy: sum
		sourceColumn: level

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 4c8b3db4-df0e-45a1-8721-08ce00f3b2f4
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column dv_location
		dataType: string
		lineageTag: 41694494-b279-430f-9b36-a4d48f42cd3a
		summarizeBy: none
		sourceColumn: dv_location

		annotation SummarizationSetBy = Automatic

	column made_sla
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d78bf2ca-f360-43b8-ab32-0bab3bb2b2b4
		summarizeBy: none
		sourceColumn: made_sla

		annotation SummarizationSetBy = Automatic

	column milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 406f8ee5-21c0-4750-aa83-7e5166100609
		summarizeBy: none
		sourceColumn: milestone

		annotation SummarizationSetBy = Automatic

	column mpp_task_id
		dataType: int64
		formatString: 0
		lineageTag: 50231379-ef58-4cd4-b403-22d5b7fdfd0a
		summarizeBy: sum
		sourceColumn: mpp_task_id

		annotation SummarizationSetBy = Automatic

	column number
		dataType: string
		lineageTag: 25a4af8b-9028-4ed6-876b-b923da344409
		summarizeBy: none
		sourceColumn: number

		annotation SummarizationSetBy = Automatic

	column opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 60df6e7b-bde9-4365-ad50-db4c33c7d4c3
		summarizeBy: none
		sourceColumn: opened_at

		variation Variación
			isDefault
			relationship: c32a1fc0-9bce-4004-aeea-01abed5d018d
			defaultHierarchy: LocalDateTable_b65feccb-865d-4582-8e2c-3814dd096e61.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column opened_by
		dataType: string
		lineageTag: b2c9c413-d88d-4ffc-9a13-dbdf5f8fff34
		summarizeBy: none
		sourceColumn: opened_by

		annotation SummarizationSetBy = Automatic

	column dv_opened_by
		dataType: string
		lineageTag: b228c20d-5830-49cf-b51d-25372297cabd
		summarizeBy: none
		sourceColumn: dv_opened_by

		annotation SummarizationSetBy = Automatic

	column opex_cost
		dataType: double
		lineageTag: 02ad28c4-a0e1-43a6-b9c9-0499fc3f6f27
		summarizeBy: sum
		sourceColumn: opex_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order
		dataType: int64
		formatString: 0
		lineageTag: 5550bd27-6fea-4424-a53e-7b22849fef88
		summarizeBy: sum
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	column orig_sys_id
		dataType: string
		lineageTag: 03156949-743e-4856-9471-68f83523821c
		summarizeBy: none
		sourceColumn: orig_sys_id

		annotation SummarizationSetBy = Automatic

	column dv_orig_sys_id
		dataType: string
		lineageTag: 54a2be36-de8a-4d2a-a777-3f9562067b98
		summarizeBy: none
		sourceColumn: dv_orig_sys_id

		annotation SummarizationSetBy = Automatic

	column orig_top_task_id
		dataType: string
		lineageTag: 34dbcee5-4a31-4ef9-8f88-e17d6fd97683
		summarizeBy: none
		sourceColumn: orig_top_task_id

		annotation SummarizationSetBy = Automatic

	column dv_orig_top_task_id
		dataType: string
		lineageTag: e591c722-a67c-4068-a1ec-c804fee9566d
		summarizeBy: none
		sourceColumn: dv_orig_top_task_id

		annotation SummarizationSetBy = Automatic

	column parent
		dataType: string
		lineageTag: ec264af8-450d-4a6c-b956-efc8e267125a
		summarizeBy: none
		sourceColumn: parent

		annotation SummarizationSetBy = Automatic

	column dv_parent
		dataType: string
		lineageTag: c68cb567-598d-4536-92f9-7e78edb10abe
		summarizeBy: none
		sourceColumn: dv_parent

		annotation SummarizationSetBy = Automatic

	column percent_complete
		dataType: double
		lineageTag: 0b9c87ca-ae9d-4eff-b850-e0a9230a9ea1
		summarizeBy: sum
		sourceColumn: percent_complete

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column phase_type
		dataType: string
		lineageTag: 8995bc34-ab18-475e-bb99-5db206f3aa07
		summarizeBy: none
		sourceColumn: phase_type

		annotation SummarizationSetBy = Automatic

	column dv_phase_type
		dataType: string
		lineageTag: d804fa36-cbfe-4e87-b7fb-6615128df550
		summarizeBy: none
		sourceColumn: dv_phase_type

		annotation SummarizationSetBy = Automatic

	column priority
		dataType: int64
		formatString: 0
		lineageTag: 85316a54-c4ad-4d1e-86f1-93678c8f9bb4
		summarizeBy: sum
		sourceColumn: priority

		annotation SummarizationSetBy = Automatic

	column dv_priority
		dataType: string
		lineageTag: 37d39735-6605-4919-a880-0dd922283b0d
		summarizeBy: none
		sourceColumn: dv_priority

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: 88e556d0-274c-4a88-a38a-5f1f14d6b0e1
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column dv_product
		dataType: string
		lineageTag: 28711f20-d440-4000-b121-e49b3e867003
		summarizeBy: none
		sourceColumn: dv_product

		annotation SummarizationSetBy = Automatic

	column reassignment_count
		dataType: int64
		formatString: 0
		lineageTag: 3ea1379d-aea9-4686-a758-971fa3eac84c
		summarizeBy: sum
		sourceColumn: reassignment_count

		annotation SummarizationSetBy = Automatic

	column rejection_goto
		dataType: string
		lineageTag: 54c9b29b-02e0-4cbe-8bf3-6fa410ef619b
		summarizeBy: none
		sourceColumn: rejection_goto

		annotation SummarizationSetBy = Automatic

	column dv_rejection_goto
		dataType: string
		lineageTag: f8e99e0c-cc23-44f2-89d9-85dadfa763f9
		summarizeBy: none
		sourceColumn: dv_rejection_goto

		annotation SummarizationSetBy = Automatic

	column relation_applied
		dataType: string
		lineageTag: 1de94036-5374-440e-82f6-bb2b4dc2b42e
		summarizeBy: none
		sourceColumn: relation_applied

		annotation SummarizationSetBy = Automatic

	column dv_relation_applied
		dataType: string
		lineageTag: c796f480-a7ae-441e-a5a7-bcbaac461645
		summarizeBy: none
		sourceColumn: dv_relation_applied

		annotation SummarizationSetBy = Automatic

	column remaining_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: c3d65347-e2a2-4773-a94a-583ce78476c6
		summarizeBy: none
		sourceColumn: remaining_duration

		variation Variación
			isDefault
			relationship: e28cbaab-8ad3-4c48-80c1-9918eb3de4ce
			defaultHierarchy: LocalDateTable_73100ca0-90cb-4754-bce0-a42b0d7a5acf.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_remaining_duration
		dataType: string
		lineageTag: d70ec4ba-efb4-4594-8985-896352743120
		summarizeBy: none
		sourceColumn: dv_remaining_duration

		annotation SummarizationSetBy = Automatic

	column remaining_effort
		dataType: dateTime
		formatString: General Date
		lineageTag: e1db33ab-75ee-420f-b083-206bad5fd9b4
		summarizeBy: none
		sourceColumn: remaining_effort

		variation Variación
			isDefault
			relationship: 5c808b78-1d3c-494b-ae0f-3312e162ccfa
			defaultHierarchy: LocalDateTable_1fabe468-4d02-4734-9b79-5ee5b5ae0cb4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_remaining_effort
		dataType: string
		lineageTag: c5c57de7-7d8b-47eb-9c99-0ad7f20655a4
		summarizeBy: none
		sourceColumn: dv_remaining_effort

		annotation SummarizationSetBy = Automatic

	column resource_allocated_cost
		dataType: double
		lineageTag: 98a95c28-9e9d-43ba-a897-76c9e7fe06a0
		summarizeBy: sum
		sourceColumn: resource_allocated_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column resource_planned_cost
		dataType: double
		lineageTag: 445387b1-f199-4962-af3d-de872ba7c67d
		summarizeBy: sum
		sourceColumn: resource_planned_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rollup
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4f85869a-0ad5-4a24-96ff-184b8f0d12e8
		summarizeBy: none
		sourceColumn: rollup

		annotation SummarizationSetBy = Automatic

	column route_reason
		dataType: int64
		formatString: 0
		lineageTag: 8ae94349-030d-4d35-ad37-8e4b2efc9ff5
		summarizeBy: sum
		sourceColumn: route_reason

		annotation SummarizationSetBy = Automatic

	column dv_route_reason
		dataType: string
		lineageTag: 6230006c-ab62-4879-ac8b-f1a4fc98b28f
		summarizeBy: none
		sourceColumn: dv_route_reason

		annotation SummarizationSetBy = Automatic

	column schedule_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 52ca2c7d-6b50-4c5e-b004-50f893239b80
		summarizeBy: none
		sourceColumn: schedule_end_date

		variation Variación
			isDefault
			relationship: 2a28798c-097d-4f7f-8304-4919ea075a80
			defaultHierarchy: LocalDateTable_50ce1e3d-79c6-4e99-8070-ac9d62c104c5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column schedule_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1fdadde3-a6f8-4e2b-92f5-9ab984af0ec7
		summarizeBy: none
		sourceColumn: schedule_start_date

		variation Variación
			isDefault
			relationship: 5ed61322-d83c-4545-a118-58ade2d05595
			defaultHierarchy: LocalDateTable_d5e22b03-872a-45c8-aa85-62a4073e7beb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column service_offering
		dataType: string
		lineageTag: a5bc602b-2b48-499e-8bff-2f76ef3b0061
		summarizeBy: none
		sourceColumn: service_offering

		annotation SummarizationSetBy = Automatic

	column dv_service_offering
		dataType: string
		lineageTag: 64957cf7-f3e2-40c5-b591-8abea7df87e8
		summarizeBy: none
		sourceColumn: dv_service_offering

		annotation SummarizationSetBy = Automatic

	column shadow
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5ba938ac-559e-4388-95e8-f64c6ba48ceb
		summarizeBy: none
		sourceColumn: shadow

		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: d989d08a-b00c-486a-98da-1c123e0d7bd1
		summarizeBy: none
		sourceColumn: short_description

		annotation SummarizationSetBy = Automatic

	column skills
		dataType: string
		lineageTag: 61b6e345-88c1-43c1-a809-f3753de35673
		summarizeBy: none
		sourceColumn: skills

		annotation SummarizationSetBy = Automatic

	column sla_due
		dataType: dateTime
		formatString: General Date
		lineageTag: e2ec5385-06fb-4489-b922-d25119b689d5
		summarizeBy: none
		sourceColumn: sla_due

		variation Variación
			isDefault
			relationship: 019e2474-545c-4d5a-b1c8-be87cc1c3172
			defaultHierarchy: LocalDateTable_d82d2b3b-f3d1-427b-a211-f5981475209c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 11d4a2a1-12ab-46f3-90b1-07a38732bb54
		summarizeBy: none
		sourceColumn: start_date

		variation Variación
			isDefault
			relationship: b032810f-2838-4481-9d91-515f5ba872d7
			defaultHierarchy: LocalDateTable_b32260a2-6e04-48e5-a3b1-47537451f9af.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column start_date_derived_from
		dataType: string
		lineageTag: 64e2a955-6612-42e9-b70d-015f021f5118
		summarizeBy: none
		sourceColumn: start_date_derived_from

		annotation SummarizationSetBy = Automatic

	column dv_start_date_derived_from
		dataType: string
		lineageTag: 8f76bd05-da10-4779-9959-193ea72fe74d
		summarizeBy: none
		sourceColumn: dv_start_date_derived_from

		annotation SummarizationSetBy = Automatic

	column state
		dataType: int64
		formatString: 0
		lineageTag: 09461297-3646-48c3-bbd8-57e8d9d6da23
		summarizeBy: sum
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column dv_state
		dataType: string
		lineageTag: c2f14d80-b36e-474d-81c6-4c6dbe4e9108
		summarizeBy: none
		sourceColumn: dv_state

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 05998837-e291-4381-b3fb-20174e91f119
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column dv_status
		dataType: string
		lineageTag: 3f2495ee-5c8f-41d7-8757-637865120c7f
		summarizeBy: none
		sourceColumn: dv_status

		annotation SummarizationSetBy = Automatic

	column sub_tree_root
		dataType: string
		lineageTag: 42afeedf-50d5-4f28-807c-6132d419b7c5
		summarizeBy: none
		sourceColumn: sub_tree_root

		annotation SummarizationSetBy = Automatic

	column dv_sub_tree_root
		dataType: string
		lineageTag: 1bc5f844-43b1-4b2d-aaae-0d9e7035ff14
		summarizeBy: none
		sourceColumn: dv_sub_tree_root

		annotation SummarizationSetBy = Automatic

	column sys_class_name
		dataType: string
		lineageTag: 35da52cd-e2cc-4d48-8ef6-b4657265bec4
		summarizeBy: none
		sourceColumn: sys_class_name

		annotation SummarizationSetBy = Automatic

	column dv_sys_class_name
		dataType: string
		lineageTag: 14133634-b1e3-48eb-a6fd-88fda0083406
		summarizeBy: none
		sourceColumn: dv_sys_class_name

		annotation SummarizationSetBy = Automatic

	column sys_created_by
		dataType: string
		lineageTag: d66599d9-9b79-4834-8a68-1c3c8178ccdc
		summarizeBy: none
		sourceColumn: sys_created_by

		annotation SummarizationSetBy = Automatic

	column sys_created_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 10ffcc80-f762-4725-b372-7466170c5c71
		summarizeBy: none
		sourceColumn: sys_created_on

		variation Variación
			isDefault
			relationship: 94a1558d-8be7-415f-8e43-569abaec141b
			defaultHierarchy: LocalDateTable_e43c8a24-5b63-4c38-b993-7aaa52443029.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column sys_domain
		dataType: string
		lineageTag: 2894f05c-a1a5-4417-b683-35a7a705e43f
		summarizeBy: none
		sourceColumn: sys_domain

		annotation SummarizationSetBy = Automatic

	column sys_domain_path
		dataType: string
		lineageTag: e19d47d4-73e8-4553-af14-41ae1f58181a
		summarizeBy: none
		sourceColumn: sys_domain_path

		annotation SummarizationSetBy = Automatic

	column sys_id
		dataType: string
		lineageTag: 2fbfed0a-7286-421d-9b24-cea4e71d8c7b
		summarizeBy: none
		sourceColumn: sys_id

		annotation SummarizationSetBy = Automatic

	column sys_mod_count
		dataType: int64
		formatString: 0
		lineageTag: eb4e029b-d96c-4450-9acd-27a34b561b05
		summarizeBy: sum
		sourceColumn: sys_mod_count

		annotation SummarizationSetBy = Automatic

	column sys_tags
		dataType: string
		lineageTag: e9a67a36-31ab-47e8-bde8-e86d20f5915f
		summarizeBy: none
		sourceColumn: sys_tags

		annotation SummarizationSetBy = Automatic

	column sys_updated_by
		dataType: string
		lineageTag: c863cc53-d530-41bb-8af7-dcd828dd23e8
		summarizeBy: none
		sourceColumn: sys_updated_by

		annotation SummarizationSetBy = Automatic

	column sys_updated_on
		dataType: dateTime
		formatString: General Date
		lineageTag: 81708790-b044-4e05-93c9-2f34afa3dc91
		summarizeBy: none
		sourceColumn: sys_updated_on

		variation Variación
			isDefault
			relationship: 2b8ad3df-b902-4dee-ada5-07b574ec4d15
			defaultHierarchy: LocalDateTable_5ad850e9-1045-4b03-a66b-2712d9c823c1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column task
		dataType: string
		lineageTag: 3b038803-23f0-4002-b01d-5b6b366a5f03
		summarizeBy: none
		sourceColumn: task

		annotation SummarizationSetBy = Automatic

	column task_effective_number
		dataType: string
		lineageTag: 4c92adf1-23ed-4e70-8fb4-e389340ab4d4
		summarizeBy: none
		sourceColumn: task_effective_number

		annotation SummarizationSetBy = Automatic

	column task_for
		dataType: string
		lineageTag: 8a6bee48-7d67-43f5-9de9-5c8bf0f00cd5
		summarizeBy: none
		sourceColumn: task_for

		annotation SummarizationSetBy = Automatic

	column dv_task_for
		dataType: string
		lineageTag: 12738073-db85-4511-a4c8-2a740b35f1c5
		summarizeBy: none
		sourceColumn: dv_task_for

		annotation SummarizationSetBy = Automatic

	column time_card_at_top_task
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 08c615ee-ebe7-4947-a625-1bfb8a7c921b
		summarizeBy: none
		sourceColumn: time_card_at_top_task

		annotation SummarizationSetBy = Automatic

	column time_constraint
		dataType: string
		lineageTag: cd1244c8-78e4-46c6-a3b1-e7cb8663bc10
		summarizeBy: none
		sourceColumn: time_constraint

		annotation SummarizationSetBy = Automatic

	column dv_time_constraint
		dataType: string
		lineageTag: 8a63a73c-38ba-4c5d-87aa-68f25a6e82ca
		summarizeBy: none
		sourceColumn: dv_time_constraint

		annotation SummarizationSetBy = Automatic

	column time_worked
		dataType: dateTime
		formatString: General Date
		lineageTag: 4ec83698-e1c7-4a8e-95a4-552eab4c8b32
		summarizeBy: none
		sourceColumn: time_worked

		variation Variación
			isDefault
			relationship: 4d77b96c-f2d5-41f7-8d01-df0e70d86cd2
			defaultHierarchy: LocalDateTable_3d310d2d-62be-4b43-8748-fde88935d0eb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_time_worked
		dataType: string
		lineageTag: 0341ce3c-1598-4bd5-8be5-88c6ab07be7b
		summarizeBy: none
		sourceColumn: dv_time_worked

		annotation SummarizationSetBy = Automatic

	column top_portfolio
		dataType: string
		lineageTag: 5960d0cc-57e3-4f6b-ad40-11da254adff5
		summarizeBy: none
		sourceColumn: top_portfolio

		annotation SummarizationSetBy = Automatic

	column dv_top_portfolio
		dataType: string
		lineageTag: e456fdc4-54a4-46bd-8f45-c3385cc1846a
		summarizeBy: none
		sourceColumn: dv_top_portfolio

		annotation SummarizationSetBy = Automatic

	column top_program
		dataType: string
		lineageTag: 25a447eb-6887-4643-af43-638bd79df4ea
		summarizeBy: none
		sourceColumn: top_program

		annotation SummarizationSetBy = Automatic

	column dv_top_program
		dataType: string
		lineageTag: 32aee831-6599-45e7-b6e0-8237f32652d6
		summarizeBy: none
		sourceColumn: dv_top_program

		annotation SummarizationSetBy = Automatic

	column top_task
		dataType: string
		lineageTag: 178b5170-1b74-46ba-8b9f-050ac77986f6
		summarizeBy: none
		sourceColumn: top_task

		annotation SummarizationSetBy = Automatic

	column dv_top_task
		dataType: string
		lineageTag: db4f8d45-4609-4140-9c1f-ebc5099fd3e5
		summarizeBy: none
		sourceColumn: dv_top_task

		annotation SummarizationSetBy = Automatic

	column u_acciona_priority
		dataType: int64
		formatString: 0
		lineageTag: ea62f013-71b3-4c74-99b9-8972f7209731
		summarizeBy: sum
		sourceColumn: u_acciona_priority

		annotation SummarizationSetBy = Automatic

	column u_business_application
		dataType: string
		lineageTag: c28a7449-7ddd-49ff-949b-1d081da39efa
		summarizeBy: none
		sourceColumn: u_business_application

		annotation SummarizationSetBy = Automatic

	column dv_u_business_application
		dataType: string
		lineageTag: e7411f71-f208-476e-9a75-c26c3beb8c43
		summarizeBy: none
		sourceColumn: dv_u_business_application

		annotation SummarizationSetBy = Automatic

	column u_business_line
		dataType: string
		lineageTag: f57b744f-e13a-48ff-bc19-35b1c1b11a96
		summarizeBy: none
		sourceColumn: u_business_line

		annotation SummarizationSetBy = Automatic

	column dv_u_business_line
		dataType: string
		lineageTag: 0b5318fe-5107-40b2-a6c8-306bd579b582
		summarizeBy: none
		sourceColumn: dv_u_business_line

		annotation SummarizationSetBy = Automatic

	column u_catalog
		dataType: string
		lineageTag: f807e0a1-12c3-44c5-92c3-f0366749cb53
		summarizeBy: none
		sourceColumn: u_catalog

		annotation SummarizationSetBy = Automatic

	column dv_u_catalog
		dataType: string
		lineageTag: 15e68dbb-833a-44e9-9578-bf57a955205f
		summarizeBy: none
		sourceColumn: dv_u_catalog

		annotation SummarizationSetBy = Automatic

	column u_department
		dataType: string
		lineageTag: 8eadad45-d354-4571-b2af-2c0f7ad18b9e
		summarizeBy: none
		sourceColumn: u_department

		annotation SummarizationSetBy = Automatic

	column dv_u_department
		dataType: string
		lineageTag: 325f892e-12bc-4d4f-be08-b9ab5674f971
		summarizeBy: none
		sourceColumn: dv_u_department

		annotation SummarizationSetBy = Automatic

	column u_execution_type
		dataType: string
		lineageTag: afeed5c7-d5b6-462b-ac74-94cb3217dcaf
		summarizeBy: none
		sourceColumn: u_execution_type

		annotation SummarizationSetBy = Automatic

	column dv_u_execution_type
		dataType: string
		lineageTag: 161f1a99-6ff1-4fce-b365-f89df020e714
		summarizeBy: none
		sourceColumn: dv_u_execution_type

		annotation SummarizationSetBy = Automatic

	column u_external_vendor
		dataType: string
		lineageTag: c65fbd45-7e99-498b-9f86-0ec3e925f623
		summarizeBy: none
		sourceColumn: u_external_vendor

		annotation SummarizationSetBy = Automatic

	column dv_u_external_vendor
		dataType: string
		lineageTag: d322366a-c371-4c0d-9230-abda4074ac57
		summarizeBy: none
		sourceColumn: dv_u_external_vendor

		annotation SummarizationSetBy = Automatic

	column u_metal
		dataType: string
		lineageTag: e9ffaa27-34ba-4438-b00e-9ab0d625a763
		summarizeBy: none
		sourceColumn: u_metal

		annotation SummarizationSetBy = Automatic

	column dv_u_metal
		dataType: string
		lineageTag: 6e4c6c71-e16a-41e2-b89b-0608b46528ca
		summarizeBy: none
		sourceColumn: dv_u_metal

		annotation SummarizationSetBy = Automatic

	column u_phone
		dataType: string
		lineageTag: deea7ddc-f6c3-4b33-82cc-eaa55d95851f
		summarizeBy: none
		sourceColumn: u_phone

		annotation SummarizationSetBy = Automatic

	column u_previous_groups
		dataType: string
		lineageTag: cc8b0d78-7f56-4fb0-9006-182855448a90
		summarizeBy: none
		sourceColumn: u_previous_groups

		annotation SummarizationSetBy = Automatic

	column u_progress
		dataType: double
		lineageTag: 440c0f14-e25a-403b-80a0-eddebc20fccf
		summarizeBy: sum
		sourceColumn: u_progress

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_ref_country
		dataType: string
		lineageTag: 6dff5114-17cb-42f2-b9be-aed992c80034
		summarizeBy: none
		sourceColumn: u_ref_country

		annotation SummarizationSetBy = Automatic

	column dv_u_ref_country
		dataType: string
		lineageTag: 859ecb53-7a2c-4adc-b38e-b58e721ff128
		summarizeBy: none
		sourceColumn: dv_u_ref_country

		annotation SummarizationSetBy = Automatic

	column u_responded
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b299ca88-c33e-44eb-91ab-1d551d32de94
		summarizeBy: none
		sourceColumn: u_responded

		annotation SummarizationSetBy = Automatic

	column u_size
		dataType: string
		lineageTag: 8cf59bf8-a3bf-49e7-80b1-7c4e44d43248
		summarizeBy: none
		sourceColumn: u_size

		annotation SummarizationSetBy = Automatic

	column dv_u_size
		dataType: string
		lineageTag: 0f841f57-50d1-409e-9a24-e5bf4c5072bd
		summarizeBy: none
		sourceColumn: dv_u_size

		annotation SummarizationSetBy = Automatic

	column u_state_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8759cda0-71d0-4fb9-b91a-8438e5bbc103
		summarizeBy: none
		sourceColumn: u_state_date

		variation Variación
			isDefault
			relationship: 5b7dad03-b916-49ee-96e2-a560ed4555b9
			defaultHierarchy: LocalDateTable_41bce996-5692-42fa-9c04-92c366249674.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column universal_request
		dataType: string
		lineageTag: 24429488-541e-481c-a0c8-34c51d99a02d
		summarizeBy: none
		sourceColumn: universal_request

		annotation SummarizationSetBy = Automatic

	column dv_universal_request
		dataType: string
		lineageTag: b4a7cd48-4a50-401c-94a9-1d099f617864
		summarizeBy: none
		sourceColumn: dv_universal_request

		annotation SummarizationSetBy = Automatic

	column upon_approval
		dataType: string
		lineageTag: 92d42220-0c0d-454c-81ad-e8f087d43f10
		summarizeBy: none
		sourceColumn: upon_approval

		annotation SummarizationSetBy = Automatic

	column dv_upon_approval
		dataType: string
		lineageTag: d83f6615-dd17-42c4-9ac4-cedd1137675d
		summarizeBy: none
		sourceColumn: dv_upon_approval

		annotation SummarizationSetBy = Automatic

	column upon_reject
		dataType: string
		lineageTag: 3f8f3d90-9dbb-40f3-9986-96a0395ddc2d
		summarizeBy: none
		sourceColumn: upon_reject

		annotation SummarizationSetBy = Automatic

	column dv_upon_reject
		dataType: string
		lineageTag: 71edddfa-bb9f-402e-9c9f-e49074a7296e
		summarizeBy: none
		sourceColumn: dv_upon_reject

		annotation SummarizationSetBy = Automatic

	column urgency
		dataType: int64
		formatString: 0
		lineageTag: 99d27106-34a7-495c-b238-a8f9994878cb
		summarizeBy: sum
		sourceColumn: urgency

		annotation SummarizationSetBy = Automatic

	column dv_urgency
		dataType: string
		lineageTag: b1c4ad39-0df6-4c99-8785-df03587dfd85
		summarizeBy: none
		sourceColumn: dv_urgency

		annotation SummarizationSetBy = Automatic

	column user_input
		dataType: string
		lineageTag: 099b0b02-352e-4325-8963-1dbf17a9d98b
		summarizeBy: none
		sourceColumn: user_input

		annotation SummarizationSetBy = Automatic

	column variables
		dataType: string
		lineageTag: 78613e8d-00da-46f9-9999-4f49af7abf34
		summarizeBy: none
		sourceColumn: variables

		annotation SummarizationSetBy = Automatic

	column version
		dataType: int64
		formatString: 0
		lineageTag: b0a6adb5-f033-4189-ad8b-1f5059d07b9c
		summarizeBy: sum
		sourceColumn: version

		annotation SummarizationSetBy = Automatic

	column watch_list
		dataType: string
		lineageTag: 038d373c-ca4c-4e69-9a6a-3c45695fad27
		summarizeBy: none
		sourceColumn: watch_list

		annotation SummarizationSetBy = Automatic

	column wbs
		dataType: string
		lineageTag: 42b483b5-2980-4380-941f-5114f1b5b932
		summarizeBy: none
		sourceColumn: wbs

		annotation SummarizationSetBy = Automatic

	column wbs_order
		dataType: int64
		formatString: 0
		lineageTag: 2c2cd3cc-15b5-484a-9ebb-6645bc2bc37d
		summarizeBy: sum
		sourceColumn: wbs_order

		annotation SummarizationSetBy = Automatic

	column wf_activity
		dataType: string
		lineageTag: d2c27c52-efc0-4cea-bcd0-81f6ffeda688
		summarizeBy: none
		sourceColumn: wf_activity

		annotation SummarizationSetBy = Automatic

	column dv_wf_activity
		dataType: string
		lineageTag: d91cedbc-aed9-4e78-8f35-bd3e0874e61f
		summarizeBy: none
		sourceColumn: dv_wf_activity

		annotation SummarizationSetBy = Automatic

	column work_cost
		dataType: double
		lineageTag: 51eeeb34-467f-4335-9f47-56e2f4e80120
		summarizeBy: sum
		sourceColumn: work_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column work_duration
		dataType: dateTime
		formatString: General Date
		lineageTag: a6f51b8a-5bbf-4aab-b7ed-3312f105719c
		summarizeBy: none
		sourceColumn: work_duration

		variation Variación
			isDefault
			relationship: 8ef9f2b4-d48d-4bb9-bb73-1c08e6671fa8
			defaultHierarchy: LocalDateTable_7dbee4d5-6b05-4705-ac5e-2acc9afc1567.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_work_duration
		dataType: string
		lineageTag: 61fab06d-d8c5-4862-9837-0fa684f5a422
		summarizeBy: none
		sourceColumn: dv_work_duration

		annotation SummarizationSetBy = Automatic

	column work_effort
		dataType: dateTime
		formatString: General Date
		lineageTag: 63f8c2a4-91d3-41ce-abe9-43d7f6ed6f03
		summarizeBy: none
		sourceColumn: work_effort

		variation Variación
			isDefault
			relationship: 452410a5-0e65-4103-9f32-82884b9dfbdf
			defaultHierarchy: LocalDateTable_cee20a2c-10b4-485f-9dc9-9c57bd6ad852.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column dv_work_effort
		dataType: string
		lineageTag: b1226268-afba-4abb-80ee-2f497f79a244
		summarizeBy: none
		sourceColumn: dv_work_effort

		annotation SummarizationSetBy = Automatic

	column work_end
		dataType: dateTime
		formatString: General Date
		lineageTag: 55b47259-d69f-4592-b7e8-08192d10dfa6
		summarizeBy: none
		sourceColumn: work_end

		variation Variación
			isDefault
			relationship: 7916f1b8-6d6d-418c-b235-f8874693bd9f
			defaultHierarchy: LocalDateTable_b4bc7237-2e94-44ae-8603-e9c95f3e5c82.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column work_notes
		dataType: string
		lineageTag: fb95a4d9-f499-4b61-b9ae-69ded24fad7c
		summarizeBy: none
		sourceColumn: work_notes

		annotation SummarizationSetBy = Automatic

	column work_notes_list
		dataType: string
		lineageTag: 53dded63-d55e-4574-9241-b62188eac19e
		summarizeBy: none
		sourceColumn: work_notes_list

		annotation SummarizationSetBy = Automatic

	column work_start
		dataType: dateTime
		formatString: General Date
		lineageTag: ce6721c2-9d79-404b-9a6d-b33e62979b0a
		summarizeBy: none
		sourceColumn: work_start

		variation Variación
			isDefault
			relationship: 8f040492-5b8e-4599-94bc-f02705c4588b
			defaultHierarchy: LocalDateTable_87617c93-e0ae-451f-a0a8-a9fef9473ed1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'SERV_NOW rm_enhancement-b0ff7132-b814-420b-a6c4-ec1392a4c373' = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "DWH"),
				    SERV_NOW_rm_enhancement = Origen{[Schema="SERV_NOW",Item="rm_enhancement"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(SERV_NOW_rm_enhancement, each [opened_at] >= #datetime(2020, 1, 11, 0, 0, 0))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

