table 'SERV_NOW TAREAS - SinDemanda'
	lineageTag: fb8f2f3f-3e60-4aa9-9692-14ec899d176a

	column TAREAS-SINDEMANDA-active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 47a49afc-5d67-4037-a904-6eb54f87d84d
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-active

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-assignment_group
		dataType: string
		lineageTag: db03ce32-5e9b-41c8-b07f-481c99d51860
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-assignment_group

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-dv_assignment_group
		dataType: string
		lineageTag: d85cf17e-b940-4ca1-9113-646b7f2c7701
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-dv_assignment_group

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-closed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 55b69a61-82ef-4814-adb6-5e74734b8b6e
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-closed_at

		variation Variación
			isDefault
			relationship: 14cee18c-4875-409e-8fe9-0171f8f0c92b
			defaultHierarchy: LocalDateTable_29c546f0-d139-4050-8645-f7a7eab7f61d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 32aec046-103e-4698-8ee7-8bc7f377ca72
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-end_date

		variation Variación
			isDefault
			relationship: b43f878b-3ee7-4888-9023-f12b765f9ed4
			defaultHierarchy: LocalDateTable_bcbea2fe-52cc-463c-b6d3-5fabfa952465.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-milestone
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5a42e982-592f-4ba4-a8c2-1ce90518002a
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-milestone

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-number
		dataType: string
		lineageTag: 62d6ca4c-622d-4919-a771-dbc9b8a9b5c4
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-number

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-opened_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 00d50c44-89fc-47a4-832b-230f20f98479
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-opened_at

		variation Variación
			isDefault
			relationship: 5dfadb5a-4f77-4640-87fc-a65270b45591
			defaultHierarchy: LocalDateTable_ebec8259-c4af-4e8b-98aa-c76d006cc178.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-parent
		dataType: string
		lineageTag: 56fd8637-7f7b-48b3-9a4d-1e0d4488dba9
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-parent

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-dv_parent
		dataType: string
		lineageTag: 108d4fda-a12f-431c-b562-a7840ef1f7d8
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-dv_parent

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-percent_complete
		dataType: double
		lineageTag: 86be327e-6007-45f4-87e1-478b402ce9e0
		summarizeBy: sum
		sourceColumn: TAREAS-SINDEMANDA-percent_complete

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TAREAS-SINDEMANDA-priority
		dataType: int64
		formatString: 0
		lineageTag: 432e3f0a-812a-47b0-99a6-65324b259cc4
		summarizeBy: sum
		sourceColumn: TAREAS-SINDEMANDA-priority

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-dv_priority
		dataType: string
		lineageTag: 0f7eee76-5757-4171-ae02-af53b3d64866
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-dv_priority

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: c63aa0ca-bdf9-4b7c-aab4-892fd0e6f450
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-start_date

		variation Variación
			isDefault
			relationship: 01e540f0-c4f2-4f4d-b928-ef4ba5c8b6dc
			defaultHierarchy: LocalDateTable_b39a9fa9-fc29-44e0-8c45-9784dd5b49e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-dv_state
		dataType: string
		lineageTag: b75b6ef0-d4a9-4213-886e-61a7457efe6e
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-dv_state

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-sys_id
		dataType: string
		lineageTag: 15d40c56-f776-4909-ad5b-d7e804db5882
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-sys_id

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-top_task
		dataType: string
		lineageTag: 2a0b5d9e-0ae0-45f2-828b-e365f3870943
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-top_task

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-dv_top_task
		dataType: string
		lineageTag: fa7bcbd6-233c-49ba-b948-f77c7828c3fe
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-dv_top_task

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-u_demand
		dataType: string
		lineageTag: 5ff3aee5-9f08-4d1a-a312-9d7ae2f9cafc
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-u_demand

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-dv_u_demand
		dataType: string
		lineageTag: 803e6343-de3d-421d-8682-6249c6d77bfc
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-dv_u_demand

		annotation SummarizationSetBy = Automatic

	column 'SERV_NOW pm_project - Mto.number'
		dataType: string
		lineageTag: 1c9e4fa3-2681-4506-810b-5a75c076892f
		summarizeBy: none
		sourceColumn: SERV_NOW pm_project - Mto.number

		annotation SummarizationSetBy = Automatic

	column 'SERV_NOW pm_project - Mto.sys_id'
		dataType: string
		lineageTag: fbd58cfc-740d-487c-b700-ba26e16fc909
		summarizeBy: none
		sourceColumn: SERV_NOW pm_project - Mto.sys_id

		annotation SummarizationSetBy = Automatic

	column 'SERV_NOW pm_project - Mto.dv_u_project_type'
		dataType: string
		lineageTag: 00d22490-ef9d-40bd-bffa-6876180ed745
		summarizeBy: none
		sourceColumn: SERV_NOW pm_project - Mto.dv_u_project_type

		annotation SummarizationSetBy = Automatic

	column 'SERV_NOW pm_project - Mto.dv_cmdb_ci_business_app'
		dataType: string
		lineageTag: b1736b58-a161-4d13-8598-5043c9053bf3
		summarizeBy: none
		sourceColumn: SERV_NOW pm_project - Mto.dv_cmdb_ci_business_app

		annotation SummarizationSetBy = Automatic

	column project
		dataType: string
		lineageTag: cf761e7c-2125-496d-b5d4-1eb2bf6e3fcf
		summarizeBy: none
		sourceColumn: project

		annotation SummarizationSetBy = Automatic

	column TAREAS-SINDEMANDA-short_description
		dataType: string
		lineageTag: 390881af-4cff-40f4-8f99-609a3552c0c6
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-short_description

		annotation SummarizationSetBy = Automatic

	column dv_top_portfolio
		dataType: string
		lineageTag: 9dc048db-1d8a-41cc-bbd7-7a3c59d9dcd4
		summarizeBy: none
		sourceColumn: dv_top_portfolio

		annotation SummarizationSetBy = Automatic

	column 'TAREAS-SINDEMANDA-Proyectos_Padre_Evo4&5.dv_phase'
		dataType: string
		lineageTag: 42b556d5-992e-47b2-94cb-6254e8720382
		summarizeBy: none
		sourceColumn: TAREAS-SINDEMANDA-Proyectos_Padre_Evo4&5.dv_phase

		annotation SummarizationSetBy = Automatic

	partition 'SERV_NOW TAREAS - SinDemanda-54ea5e1e-ae88-4aca-8f8d-a3d592e3b791' = m
		mode: import
		source =
				let
				    Origen = Sql.Database("QECCDWH.acciona.int,60001", "DWH"),
				    SERV_NOW_pm_project_task = Origen{[Schema="SERV_NOW",Item="pm_project_task"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(SERV_NOW_pm_project_task,{"activity_due", "actual_benefits", "additional_assignee_list", "agile_rollup_dates", "allow_dates_outside_schedule", "approval", "dv_approval", "approval_history", "approval_set", "assigned_to", "dv_assigned_to", "benefits", "budget_cost", "business_duration", "dv_business_duration", "business_service", "dv_business_service", "calculation_type", "dv_calculation_type", "calendar_duration", "dv_calendar_duration", "capex_cost", "close_notes", "closed_by", "dv_closed_by", "cmdb_ci", "dv_cmdb_ci", "cmdb_ci_business_app", "dv_cmdb_ci_business_app", "comments", "comments_and_work_notes", "company", "dv_company", "constraint_date", "contact_type", "dv_contact_type", "correlation_display", "correlation_id", "cost", "critical_path", "delivery_plan", "dv_delivery_plan", "delivery_task", "dv_delivery_task", "dependency", "description", "due_date", "duration", "dv_duration", "effort", "dv_effort", "end_date_derived_from", "dv_end_date_derived_from", "end_sprint", "dv_end_sprint", "escalation", "dv_escalation", "expected_start", "follow_up", "group_list", "has_conflict", "html_description", "impact", "dv_impact", "key_milestone", "knowledge", "level", "link", "location", "dv_location", "made_sla", "mpp_task_id", "opened_by", "dv_opened_by", "opex_cost", "order", "orig_sys_id", "dv_orig_sys_id", "orig_top_task_id", "dv_orig_top_task_id", "phase_type", "dv_phase_type", "reassignment_count", "rejection_goto", "dv_rejection_goto", "relation_applied", "dv_relation_applied", "remaining_duration", "dv_remaining_duration", "remaining_effort", "dv_remaining_effort", "resource_allocated_cost", "resource_planned_cost", "rollup", "route_reason", "dv_route_reason", "schedule_end_date", "schedule_start_date", "scrum_team", "dv_scrum_team", "service_offering", "dv_service_offering", "shadow", "skills", "sla_due", "start_date_derived_from", "dv_start_date_derived_from", "start_sprint", "dv_start_sprint", "dv_status", "sys_class_name", "dv_sys_class_name", "sys_created_by", "sys_created_on", "sys_domain", "sys_domain_path", "sys_mod_count", "sys_tags", "sys_updated_by", "sys_updated_on", "task", "task_effective_number", "task_for", "dv_task_for", "test_plan", "dv_test_plan", "time_card_at_top_task", "time_constraint", "dv_time_constraint", "time_worked", "dv_time_worked", "top_portfolio", "top_program", "dv_top_program", "u_acciona_priority", "u_business_line", "dv_u_business_line", "u_catalog", "dv_u_catalog"}),
				    #"Filas filtradas5" = Table.SelectRows(#"Columnas quitadas", each ([dv_top_portfolio] = "EN.Supply Chain")),
				    #"Filas filtradas3" = Table.SelectRows(#"Filas filtradas5", each ([milestone] = false)),
				    #"Filas filtradas" = Table.SelectRows(#"Filas filtradas3", each ([dv_u_demand] = "")),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Filas filtradas",{"u_department", "dv_u_department", "u_estado_evolutivo", "dv_u_estado_evolutivo", "u_external_vendor", "dv_u_external_vendor", "u_metal", "dv_u_metal", "u_phone", "u_previous_groups", "u_progress", "u_ref_country", "dv_u_ref_country", "u_responded", "u_size", "dv_u_size", "u_state_date", "u_version", "universal_request", "dv_universal_request", "upon_approval", "dv_upon_approval", "upon_reject", "dv_upon_reject", "urgency", "dv_urgency", "user_input", "variables", "version", "watch_list", "wbs", "wbs_order", "wf_activity", "dv_wf_activity", "work_cost", "work_duration", "dv_work_duration", "work_effort", "dv_work_effort", "work_end", "work_notes", "work_notes_list", "work_start"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Columnas quitadas1", each Text.StartsWith([dv_parent], "PRJ")),
				    #"Filas filtradas2" = Table.SelectRows(#"Filas filtradas1", each not Text.StartsWith([dv_parent], "PRJTASK")),
				    #"Consultas combinadas" = Table.NestedJoin(#"Filas filtradas2", {"top_task"}, #"SERV_NOW PROYECTOS - Mto", {"sys_id"}, "SERV_NOW pm_project - Mto", JoinKind.LeftOuter),
				    #"Se expandió SERV_NOW pm_project - Mto" = Table.ExpandTableColumn(#"Consultas combinadas", "SERV_NOW pm_project - Mto", {"number", "sys_id", "dv_u_project_type", "dv_cmdb_ci_business_app"}, {"SERV_NOW pm_project - Mto.number", "SERV_NOW pm_project - Mto.sys_id", "SERV_NOW pm_project - Mto.dv_u_project_type",  "SERV_NOW pm_project - Mto.dv_cmdb_ci_business_app"}),
				    #"Filas filtradas4" = Table.SelectRows(#"Se expandió SERV_NOW pm_project - Mto", each ([#"SERV_NOW pm_project - Mto.dv_u_project_type"] = "Applications Maintenance")),
				    #"Columnas quitadas2" = Table.RemoveColumns(#"Filas filtradas4",{"status"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas2",{{"active", "TAREAS-SINDEMANDA-active"}, {"assignment_group", "TAREAS-SINDEMANDA-assignment_group"}, {"dv_assignment_group", "TAREAS-SINDEMANDA-dv_assignment_group"}, {"closed_at", "TAREAS-SINDEMANDA-closed_at"}, {"end_date", "TAREAS-SINDEMANDA-end_date"}, {"milestone", "TAREAS-SINDEMANDA-milestone"}, {"number", "TAREAS-SINDEMANDA-number"}, {"opened_at", "TAREAS-SINDEMANDA-opened_at"}, {"parent", "TAREAS-SINDEMANDA-parent"}, {"dv_parent", "TAREAS-SINDEMANDA-dv_parent"}, {"percent_complete", "TAREAS-SINDEMANDA-percent_complete"}, {"priority", "TAREAS-SINDEMANDA-priority"}, {"dv_priority", "TAREAS-SINDEMANDA-dv_priority"}}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columnas con nombre cambiado",{{"start_date", "TAREAS-SINDEMANDA-start_date"}, {"short_description", "TAREAS-SINDEMANDA-short_description"}}),
				    #"Columnas quitadas4" = Table.RemoveColumns(#"Columnas con nombre cambiado1",{"state"}),
				    #"Columnas con nombre cambiado2" = Table.RenameColumns(#"Columnas quitadas4",{{"dv_state", "TAREAS-SINDEMANDA-dv_state"}}),
				    #"Columnas quitadas5" = Table.RemoveColumns(#"Columnas con nombre cambiado2",{"sub_tree_root", "dv_sub_tree_root"}),
				    #"Columnas con nombre cambiado3" = Table.RenameColumns(#"Columnas quitadas5",{{"sys_id", "TAREAS-SINDEMANDA-sys_id"}, {"top_task", "TAREAS-SINDEMANDA-top_task"}, {"dv_top_task", "TAREAS-SINDEMANDA-dv_top_task"}, {"u_demand", "TAREAS-SINDEMANDA-u_demand"}, {"dv_u_demand", "TAREAS-SINDEMANDA-dv_u_demand"}}),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Columnas con nombre cambiado3", {"TAREAS-SINDEMANDA-dv_top_task"}, #"Proyectos_Padre_Evo4&5", {"number"}, "Proyectos_Padre_Evo4&5", JoinKind.LeftOuter),
				    #"Se expandió Proyectos_Padre_Evo4&5" = Table.ExpandTableColumn(#"Consultas combinadas1", "Proyectos_Padre_Evo4&5", {"dv_phase"}, {"Proyectos_Padre_Evo4&5.dv_phase"}),
				    #"Columnas con nombre cambiado4" = Table.RenameColumns(#"Se expandió Proyectos_Padre_Evo4&5",{{"Proyectos_Padre_Evo4&5.dv_phase", "TAREAS-SINDEMANDA-Proyectos_Padre_Evo4&5.dv_phase"}})
				in
				    #"Columnas con nombre cambiado4"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

