table BI_Aplicación
	lineageTag: bcb4ca90-aa1b-49cc-8c3e-2dc7a3bac88f

	measure '€ Presupuesto Restante Global' = 'BI_Aplicación'[€_presupuesto restante] + [Linea Base Restante mes] + 'BI_Aplicación'[Linea Base Restante mes _C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: d5057606-f58a-403a-aaca-3e2d9320e831

	measure '€_presupuesto restante' = [Presupuesto Real €] - [Línea Base Real consumida €]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 2aff5031-3364-4da0-8533-8c93d1c67d80

	measure 'Linea Base Restante mes' = DIVIDE([€_presupuesto restante], [Meses_Restantes_Año_1], 0)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 860a68ef-9e7e-4f16-ac4e-a24b1296455c

	measure Meses_Restantes_Año_1 =
			IF(
			    YEAR(TODAY()) > YEAR(MAX('BI_Aplicación'[Periodo])),
			    1,
			    12 - MONTH(CALCULATE(MAX('BI_Aplicación'[Periodo]), 'BI_Aplicación'[Atributo] = "Consumo Real", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos"))
			)
		formatString: 0
		lineageTag: 5d2b5ed6-e68a-4314-9060-f5bab5c6274e

	measure 'Linea Base Restante mes _C' = DIVIDE('BI_Aplicación'[Linea_Base_esperada_total_C] - 'BI_Aplicación'[Línea Base Real consumida €_C], [Meses_Restantes_Año_1], 0)
		lineageTag: 261b6145-86be-4e68-b6ab-be64c4de5cd4

	measure Linea_Base_esperada_total_C = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Atributo]="Línea Base Objetivo", 'BI_Aplicación'[Descripción Ámbito] = "Correctivos")
		lineageTag: 568a5ddf-b367-4319-9912-272f69658670

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Línea Base Real consumida €_C' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] = "Correctivos", 'BI_Aplicación'[Atributo] = "Consumo Real")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: efc36f8d-a84d-462a-832e-1cc51e8a13a1

	measure Linea_Base_esperada_total = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Atributo]="Línea Base Objetivo", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos")
		lineageTag: 922b2247-65dd-46b8-be67-eec27f9209c1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Línea Base Real consumida €' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos", 'BI_Aplicación'[Atributo] = "Consumo Real", MONTH('BI_Aplicación'[Periodo]<= MONTH(TODAY())))
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 7d5289e4-47bc-4cab-94df-99306b1ab71b

	measure 'Presupuesto Real €' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Evolutivos", 'BI_Aplicación'[Atributo] = "Presupuesto")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: a12ed524-4803-49c7-ad70-2f30b4daea0c

	measure Linea_Base_esperada_total_mensual = CALCULATE(SUM('BI_Aplicación'[Valor])/12, 'BI_Aplicación'[Atributo]="Línea Base Objetivo", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 67d5458a-98ab-4038-9e01-731110692590

	measure '€_Linea Base Real por Mes' =
			
			[Línea Base Real consumida €]/ [Meses_Restantes_Año_12_2]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 81aad18e-2716-4a87-8654-94ca802865b3

	measure Desviacion-Proyectado = [Presupuesto Real €] - [Línea Base Real Consumida €] - [LB proyectada €]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 65aa48f9-21a2-4ea7-98f5-c18453115e0a

	measure Línea_Real_Consumida_SamePeriodLastYear =
			
			[Línea Base Real consumida €] -
			
			CALCULATE(SUM('BI_Aplicación'[Valor]),
			 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos",
			  'BI_Aplicación'[Atributo] = "Consumo Real",
			   DATESBETWEEN(Fechas[Date], DATE(YEAR(TODAY()) -1,01,01), DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))))
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: daf83c0d-71d8-4429-976c-1d38303c89de

	measure Comparación_Consumo_% =
			([Línea Base Real consumida €] - CALCULATE(SUM('BI_Aplicación'[Valor]),
			 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos",
			  'BI_Aplicación'[Atributo] = "Consumo Real",
			   DATESBETWEEN(Fechas[Date], DATE(YEAR(TODAY()) -1,01,01), DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))))) / CALCULATE(SUM('BI_Aplicación'[Valor]),
			 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos",
			  'BI_Aplicación'[Atributo] = "Consumo Real",
			   DATESBETWEEN(Fechas[Date], DATE(YEAR(TODAY()) -1,01,01), DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 287b06fa-539d-4b41-8852-1fef07aad1e1

	measure Total_LB_Uts_Real_Valor = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Evolutivos", 'BI_Aplicación'[Atributo] = "Consumo Real")
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: f428c94f-78dc-4376-b837-cf03d381e8d5

	measure Total_LB_Uts_Real_Aplicaciones = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Evolutivos", 'BI_Aplicación'[Atributo] = "Consumo Real Uts")
		formatString: #,0.00
		lineageTag: e163b831-4635-41ad-84f1-0264affe12fa

	measure 'Presupuesto Real Uts' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Evolutivos", 'BI_Aplicación'[Atributo] = "Presupuesto Uts")
		formatString: #,0.00
		lineageTag: 00f1cff2-5649-40dc-845c-81588c39609b

	measure UTS_restantes = [Presupuesto Real Uts] - [Total_LB_Uts_Real_Aplicaciones]
		formatString: #,0.00
		lineageTag: 27b40896-ec62-4fbc-81ba-f5cd442c514f

	measure UTS_Disponibles_Ppto = [Presupuesto Real Uts] - [Total_LB_Uts_Real_Aplicaciones] - [LB proyectada Evo]
		formatString: #,0.00
		lineageTag: dacdaf68-29e5-45b2-9aef-d1a47c803dfc

	measure 'Coste UT LB Objetivo' = [Linea_Base_esperada_total] / [UTS_totales_disponibles]
		lineageTag: 6cd89003-2452-4862-a6bc-cc9faa2674ef

	measure UTS_totales_disponibles = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Atributo] = "Línea Base Objetivo Uts", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos", ALL('BI_Aplicación'[Periodo]))
		lineageTag: 82df0078-3747-4a6c-846a-0885a11cfe12

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure UTS_restantes_mensual = [Presupuesto Real Uts] / 12
		formatString: #,0.00
		lineageTag: 16fba26c-3085-423a-b8d1-78f249a2680a

	measure Total_LB_Uts_Real_Aplicaciones_mes = [Total_LB_Uts_Real_Aplicaciones] / [Meses_Restantes_Año_12_2]
		formatString: #,0.00
		lineageTag: 987ab635-49e5-44dd-ba96-fa0a45dca134

	measure 'Meses año actual' = MONTH(CALCULATE(MAX('BI_Aplicación'[Periodo]), 'BI_Aplicación'[Atributo] = "Consumo Real", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos"))
		formatString: 0
		lineageTag: 153fd116-5b33-4459-bffa-529c98cc19d3

	measure 'UTS_mes_disponibles restantes' = DIVIDE([UTS_restantes] , [Meses_Restantes_Año_1], 0)
		formatString: #,0.00
		lineageTag: 5fa51825-ea20-4054-89f0-2b687b7dfd7b

	measure 'Meses restantes' = 12 - MONTH(CALCULATE(MAX('BI_Aplicación'[Periodo]), 'BI_Aplicación'[Atributo] = "Consumo Real", 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos"))
		formatString: 0
		lineageTag: 3884800b-90d9-427c-94d0-1799e21f03fd

	measure Línea_Real_Consumida_Uts_SamePeriodLastYear = ```
			[Total_LB_Uts_Real_Aplicaciones] - 
			
			CALCULATE(SUM('BI_Aplicación'[Valor]),
			 'BI_Aplicación'[Descripción Ámbito] = "Evolutivos",
			  'BI_Aplicación'[Atributo] = "Consumo Real Uts",
			   DATESBETWEEN(Fechas[Date], DATE(YEAR(TODAY()) -1,01,01), DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))))
			```
		formatString: #,0.00
		lineageTag: 59c5b0c0-279b-4b93-a950-86ece2e01a53

	measure Total_LB_Uts_Real_Aplicaciones_C = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Correctivos", 'BI_Aplicación'[Atributo] = "Consumo Real Uts")
		formatString: 0.00
		lineageTag: 7ac35ede-2625-4440-b9e1-75a2942b8a70

	measure 'UTS_restantes C' = [UTS_totales_disponibles_ C] - [Total_LB_Uts_Real_Aplicaciones_C]
		formatString: 0.00
		lineageTag: d9956a60-e82a-4013-846f-cb85af569d0c

	measure 'UTS_totales_disponibles_ C' = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Atributo] = "Línea Base Objetivo Uts", 'BI_Aplicación'[Descripción Ámbito] = "Correctivos", ALL('BI_Aplicación'[Periodo]))
		lineageTag: ca5b903e-7009-4684-a861-c64f17a75f81

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tendencia_Uts_C = DIVIDE([Total_LB_Uts_Real_Total_C], [Meses_Uts_Real_Total])
		formatString: 0.00
		lineageTag: 05fe4abf-820e-4ace-b602-6da2b216c510

	measure Total_LB_Uts_Real_Total_C = CALCULATE('BI_Aplicación'[Total_LB_Uts_Real_Aplicaciones_C], ALL(Fechas))
		lineageTag: 41c15bf8-23b4-4e12-8162-efc8dd095535

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Meses_Uts_Real_Total = CALCULATE((DATEDIFF(FIRSTDATE('BI_Aplicación'[Periodo]), LASTDATE('BI_Aplicación'[Periodo]), MONTH) +1),'BI_Aplicación'[Atributo] = "Consumo Real Uts", ALLEXCEPT('BI_Aplicación','BI_Aplicación'[Área],'BI_Aplicación'[SubÁrea],'BI_Aplicación'[Aplicación]), ALL(Fechas))
		formatString: 0
		lineageTag: 1aa9283c-fe47-4523-84c6-6a9897bf96ea

	measure Total_LB_Uts_Real_Valor_C = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Correctivos", 'BI_Aplicación'[Atributo] = "Consumo Real")
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: 2fa35cd3-ebc8-4a32-bd4d-b08d9498bcbd

	measure Euro_Hora_Estimado_C = [Linea_Base_esperada_total_C] / [Total_LB_UTs_C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 9dfd7808-a491-45a3-b1b5-e749b21acbd2

	measure Total_LB_UTs_C =
			CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] = "Correctivos", 'BI_Aplicación'[Atributo] = "Línea Base Objetivo Uts", FILTER(ALL('BI_Aplicación'[Periodo]), IF(
			    YEAR(TODAY()) > YEAR(MAX('BI_Aplicación'[Periodo])),
			    12,
			    MONTH('BI_Aplicación'[Periodo]) <= MONTH(TODAY()))
			)
			)
		lineageTag: 8ade6854-c822-4556-8203-7503de7b8698

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tendencia_LB_C = DIVIDE('BI_Aplicación'[Linea Base Real Consumida Total], [Meses_LB_Real_Total], 0)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: ade2e0a2-7c88-429a-81b4-5586f06766a0

	measure Meses_LB_Real_Total = CALCULATE((DATEDIFF(FIRSTDATE('BI_Aplicación'[Periodo]), LASTDATE('BI_Aplicación'[Periodo]), MONTH) +1),'BI_Aplicación'[Atributo] = "Consumo Real", ALLEXCEPT('BI_Aplicación','BI_Aplicación'[Área],'BI_Aplicación'[SubÁrea],'BI_Aplicación'[Aplicación]), ALL(Fechas))
		formatString: 0
		lineageTag: 70fa70be-fbd5-4518-a1da-af200131f8f9

	measure 'Linea Base Real Consumida Total' = CALCULATE('BI_Aplicación'[Línea Base Real consumida €], ALL(Fechas))
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: fe5b1b94-c4f3-4cbf-ab0a-7bd2e739f10f

	measure Coste_FIjo_Horas_Incurridas = DIVIDE([Linea_Base_esperada_total_C], [Total_LB_Horas_Real_Aplicaciones_C], 0)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 8867f81d-0818-4be4-91d4-88b2c15e6f47

	measure 'Coste Fijo' = [Total_LB_UTs_C] * [Euro_Hora_Estimado_C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: a97b0162-c2b6-4b9a-afd7-7aefec8945fd

	measure Linea_Base_esperada_total_mes_C_2 = ([Linea_Base_esperada_total_mensual_C] * [Meses_Restantes_Año_12])
		lineageTag: 91d92a58-ab5b-46a0-82f5-d225204154e6

	measure Linea_Base_esperada_total_mensual_C = CALCULATE(SUM('BI_Aplicación'[Valor])/12, 'BI_Aplicación'[Atributo]="Línea Base Objetivo", 'BI_Aplicación'[Descripción Ámbito] = "Correctivos")
		lineageTag: ef23e6fb-4527-4135-af27-8a80ef0b0f44

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Meses_Restantes_Año_12 =
			IF(
			    YEAR(TODAY()) > YEAR(MAX('BI_Aplicación'[Periodo])),
			    12,
			    12 - MONTH(TODAY()))
		formatString: 0
		lineageTag: 11bac99a-be18-43c5-99f5-d587e44b181d

	measure Consumido_PrecioHoraContratado = [Total_LB_Uts_Real_Aplicaciones_C] * [Precio_Hora_Contratado]
		lineageTag: 7a3722dc-a0f0-40d1-92c2-bcb812a26f06

	measure Precio_Hora_Contratado = [Linea_Base_esperada_total_C] / [UTS_totales_disponibles_ C]
		lineageTag: 2a647e28-4838-4f40-9d1c-8eef671a35c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Ahorro = [Coste Fijo] - [Gasto_Hipotetico_C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 7227a829-255e-46cc-a213-5fb8511433a3

	measure Comparación_Euro_Hora = IF([Coste_FIjo_Horas_Incurridas] <= [Euro_Hora_Estimado_C], "#0EB194", "#CD5C5C")
		lineageTag: d0a21eaa-e455-4395-a831-9d6f8f9b9c5f

	measure Euro_hora_Correctivo_C = [Línea Base Real consumida €_C] / [Total_LB_Uts_Real_Aplicaciones_C]
		lineageTag: 42173cba-2810-4480-8eb8-83a90fe2c2f7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Uts_desviacion-proyectado = [UTS_totales_disponibles] - ([Total_LB_Uts_Real_Aplicaciones_mes] * 12)
		lineageTag: 2aa4e495-d64f-4245-82e8-b26aa4020552

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tendencia_Color = IF([Total_LB_Uts_Real_Aplicaciones_C] > [Linea_Base_esperada_total_C], 0, 1)
		formatString: 0
		lineageTag: a5730c88-3a8d-415e-b2da-bfedda39eb4c

	measure Ppto_Restante_Año = [Presupuesto Real €] - [Línea Base Real consumida €]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 49d3fc58-bc9a-4cd9-b79f-dd9943668219

	measure Presupuesto€_Mes = [Presupuesto Real €] / 12
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: bb64402d-9095-4faf-acde-ec71d2080003

	measure Meses_Restantes_Año_12_2 =
			IF(
			    YEAR(TODAY()) > YEAR(MAX('BI_Aplicación'[Periodo])),
			    12,
			    MONTH(TODAY()))
		formatString: 0
		lineageTag: ce7733ac-d171-4dfa-91db-a85a75698d63

	measure Gasto_Hipotetico_C = [Euro_Hora_Estimado_C] * [Total_LB_Horas_Real_Aplicaciones_C]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: a72424c3-8a2f-460a-9457-e82747cc046b

	measure Total_LB_Horas_Real_Aplicaciones_C = CALCULATE(SUM('BI_Aplicación'[Valor]), 'BI_Aplicación'[Descripción Ámbito] ="Correctivos", 'BI_Aplicación'[Atributo] = "Consumo Real Uts")
		lineageTag: e18bf3ad-b654-4e43-944b-26b3476a17bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LB proyectada Evo' = ```
			CALCULATE(SUM('BI_Aplicación'[Valor]), 
			'BI_Aplicación'[Atributo]="Línea Base Proyectada Uts Suma", 
			'BI_Aplicación'[Descripción Ámbito] = "Evolutivos")
			```
		formatString: #,0.00
		lineageTag: 929ee512-901c-47f3-bc76-5fb2357eff5a

	measure 'LB proyectada €' = ```
			CALCULATE(SUM('BI_Aplicación'[Valor]), 
			'BI_Aplicación'[Atributo]="Línea Base Proyectada Suma", 
			'BI_Aplicación'[Descripción Ámbito] = "Evolutivos")
			```
		lineageTag: f77efcfa-83a4-4f4f-b550-0250fc593704

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Servicio TIC'
		dataType: string
		lineageTag: 21c6cf97-d467-49c8-ae4a-5645ee638d2f
		summarizeBy: none
		sourceColumn: Servicio TIC

		annotation SummarizationSetBy = Automatic

	column Ámbito
		dataType: string
		lineageTag: 37c6853a-c13d-42de-8015-04b904dc9904
		summarizeBy: none
		sourceColumn: Ámbito

		annotation SummarizationSetBy = Automatic

	column 'Descripción Ámbito'
		dataType: string
		lineageTag: 6f5bcfa8-613d-495a-b3f9-3a195cb78879
		summarizeBy: none
		sourceColumn: Descripción Ámbito

		annotation SummarizationSetBy = Automatic

	column Área
		dataType: string
		lineageTag: f72a7dcf-6922-479b-8d68-aece66e7b553
		summarizeBy: none
		sourceColumn: Área

		annotation SummarizationSetBy = Automatic

	column SubÁrea
		dataType: string
		lineageTag: 5b0d625e-af35-4917-b8b3-5ddbad5b1e3b
		summarizeBy: none
		sourceColumn: SubÁrea

		annotation SummarizationSetBy = Automatic

	column Aplicación
		dataType: string
		lineageTag: a1cd2fe9-f9d3-4f49-94b1-1b5373d3572a
		summarizeBy: none
		sourceColumn: Aplicación

		annotation SummarizationSetBy = Automatic

	column Periodo
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8018746f-c8b0-453c-a48b-b9f1946bb1e6
		summarizeBy: none
		sourceColumn: Periodo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Atributo
		dataType: string
		lineageTag: 8bae4453-0b7e-42f7-b5b3-8fa8a9021815
		summarizeBy: none
		sourceColumn: Atributo
		sortByColumn: Orden_Leyenda

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: double
		lineageTag: 180481dd-ab58-45d6-8a50-3596749f0a6e
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Atributo - Leyenda'
		dataType: string
		lineageTag: a531e47b-d2ca-4229-add4-cbf49761fe73
		summarizeBy: none
		sourceColumn: Atributo - Leyenda

		annotation SummarizationSetBy = Automatic

	column Orden_Leyenda
		dataType: double
		lineageTag: 0fd750c5-3dbe-47c0-b033-15eceded13b8
		summarizeBy: sum
		sourceColumn: Orden_Leyenda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fin de mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1762a6dd-ce5d-41d8-aea6-bb939f86d713
		summarizeBy: none
		sourceColumn: Fin de mes

		variation Variación
			isDefault
			relationship: c01bd9f9-ed73-458a-9da8-39025e08162b
			defaultHierarchy: LocalDateTable_5f1c36c9-6cbe-4136-92e1-347c535a1809.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition BI_Aplicación-d15bea12-50ed-421c-8979-e6b5c50b80ae = m
		mode: import
		queryGroup: 'Línea Base'
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(LB & "Líneas Base Energía v0.2 - Nuevos Presupuestos" & xlsx), null, true),
				    BI_Aplicación_Sheet = Origen{[Item="CdM_Core",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(BI_Aplicación_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Servicio TIC", type text}, {"Ámbito", type text}, {"Descripción Ámbito", type text}, {"Área", type text}, {"SubÁrea", type text}, {"Aplicación", type text}, {"Línea Base Real", type number}, {"Línea Base Proyectada", type number}, {"Línea Base Real Uts", type number}, {"Línea Base Proyectada Uts", type number}, {"Periodo", type date}, {"Tarifa", Int64.Type}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Tarifa"}),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Columnas quitadas",{{"Línea Base Real", type number}, {"Línea Base Proyectada", type number}, {"Presupuesto", type number}}),
				    #"Columna de anulación de dinamización" = Table.UnpivotOtherColumns(#"Tipo cambiado3", {"Servicio TIC", "Ámbito", "Descripción Ámbito", "Área", "SubÁrea", "Aplicación", "Periodo"}, "Atributo", "Valor"),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columna de anulación de dinamización",{{"Valor", type number}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado2","Línea Base Real Uts","Consumo Real Uts",Replacer.ReplaceText,{"Atributo"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Línea Base Real","Consumo Real",Replacer.ReplaceText,{"Atributo"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Valor reemplazado1",{{"Valor", type number}}),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Tipo cambiado1", "Atributo", "Atributo - Copia"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna duplicada",{{"Atributo - Copia", "Atributo - Leyenda"}}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Columnas con nombre cambiado","Línea Base Objetivo","Fijo Correctivo",Replacer.ReplaceText,{"Atributo - Leyenda"}),
				    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado2","Fijo Correctivo Uts","Fijo Correctivo Horas",Replacer.ReplaceText,{"Atributo - Leyenda"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado5","Consumo Real","Gasto Correctivo Hipotético",Replacer.ReplaceText,{"Atributo - Leyenda"}),
				    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","Gasto Correctivo Hipotético Uts","Gasto Correctivo Hipotético Horas",Replacer.ReplaceText,{"Atributo - Leyenda"}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Valor reemplazado4", "Orden_Leyenda", each if [Atributo] = "Línea Base Objetivo" then 1 else if [Atributo] = "Línea Base Actual" then 2 else if [Atributo] = "Línea Base Máxima" then 3 else if [Atributo] = "Consumo Real" then 4 else if [Atributo] = "Línea Base Objetivo Uts" then 5 else if [Atributo] = "Línea Base Actual Uts" then 6 else if [Atributo] = "Línea Base Máxima Uts" then 7 else if [Atributo] = "Consumo Real Uts" then 8 else if [Atributo] = "Presupuesto" then 9 else null, type number),
				    #"Fin de mes insertado" = Table.AddColumn(#"Columna condicional agregada", "Fin de mes", each Date.EndOfMonth([Periodo]), type date)
				in
				    #"Fin de mes insertado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

