table Incidencias_relacionadas
	lineageTag: 95e89d0f-052f-4d85-958e-a2da1f651bce

	column Incidente
		dataType: string
		lineageTag: d612bb92-a4c6-4efe-b9cb-7adc44417226
		summarizeBy: none
		sourceColumn: Incidente

		annotation SummarizationSetBy = Automatic

	column Tarea
		dataType: string
		lineageTag: 0ac3a0cf-5cfe-49d7-ae26-92402ba27865
		summarizeBy: none
		sourceColumn: Tarea

		annotation SummarizationSetBy = Automatic

	partition Incidencias_relacionadas-9dd9608a-0659-4d53-aafb-ec16669ee53f = m
		mode: import
		queryGroup: Parametros
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(sharepointRoot2 & incidenciasRel & xlsx), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Page 1_Sheet",{{"Column1", type text}, {"Column2", type text}}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Tipo cambiado", [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Incidente", type text}, {"Tarea", type text}})
				in
				    #"Tipo cambiado1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

