table 'Parametros KGI1-2'
	excludeFromModelRefresh
	lineageTag: 3c137642-f219-4004-bca4-c03a43e2ddeb

	column 'Prioridad Hitos Evolutivos'
		dataType: string
		lineageTag: eb4f9add-b0d0-43a2-ae6c-ba2b0685d07d
		summarizeBy: none
		sourceColumn: Prioridad Hitos Evolutivos

		annotation SummarizationSetBy = Automatic

	column 'Tasa de Desviación Máxima'
		dataType: double
		lineageTag: 6e042c54-1010-4c9e-af68-3dc474f33344
		summarizeBy: sum
		sourceColumn: Tasa de Desviación Máxima

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% cumplimiento Objetivo'
		dataType: double
		lineageTag: 96fc361e-c092-4673-b327-3e97cecf0cce
		summarizeBy: sum
		sourceColumn: % cumplimiento Objetivo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pesos %'
		dataType: double
		lineageTag: a8c762aa-2eec-47e9-8ee2-b52f19b6b97c
		summarizeBy: sum
		sourceColumn: Pesos %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Parametros KGI1-2-ec248a53-f3ac-4b15-b71a-8aa57e95b632' = m
		mode: import
		queryGroup: Parametros
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(sharepointRoot2 & tablaParametros & xlsx), null, true),
				    #"Parametros KGI1-2_Sheet" = Origen{[Item="Parametros KGI1-2",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Parametros KGI1-2_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Prioridad Hitos Evolutivos", type text}, {"Tasa de Desviación Máxima", type number}, {"% cumplimiento Objetivo", type number}, {"Pesos %", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

