table 'Parametros KGI1-3'
	excludeFromModelRefresh
	lineageTag: ddf84843-26e4-46ca-8cbe-ffeaff8ea4c9

	column 'Prioridad Hitos '
		dataType: string
		lineageTag: 9f97d85c-8f58-4252-8d1f-5968fbc0e0ba
		summarizeBy: none
		sourceColumn: "Prioridad Hitos "

		annotation SummarizationSetBy = Automatic

	column 'Tasa de Desviación Máxima'
		dataType: double
		lineageTag: 31e774f8-8678-4eab-ac69-eb5bc95a9c95
		summarizeBy: sum
		sourceColumn: Tasa de Desviación Máxima

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pesos %'
		dataType: double
		lineageTag: 737b9b69-846e-4806-924c-e358004d1a90
		summarizeBy: sum
		sourceColumn: Pesos %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Parametros KGI1-3-08728a7c-a7fb-45ed-bbcf-6996e7012e5d' = m
		mode: import
		queryGroup: Parametros
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(sharepointRoot2 & tablaParametros & xlsx), null, true),
				    #"Parametros KGI1-3_Sheet" = Origen{[Item="Parametros KGI1-3",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Parametros KGI1-3_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Tasa de Desviación Máxima", Percentage.Type}, {"Pesos %", Percentage.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

