table 'PRO - Planificaciones ENH'
	lineageTag: f5c1e323-3f44-4b80-a10a-85b1ecc28603

	column Demanda
		dataType: string
		lineageTag: 397555bf-ef5f-456e-8606-89d52e9cc1e3
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 726c3289-878e-4648-9300-2cc70b282ad5
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: a37bac22-09f2-427b-b986-fe6491933158
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: a0521e1e-4ca8-4b31-aae9-484286af862b
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: 5f52c6f2-60ad-4e05-8d2c-fc026b83ffc5
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9e94bf0e-86b1-4538-b265-1e900a79df22
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variation
			isDefault
			relationship: f0ac69d1-74c4-477c-bbf3-25f8da328df2
			defaultHierarchy: LocalDateTable_befbb3cf-edff-4711-be3c-e4d621d8d9e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6d71ea26-ee4a-412f-be22-046747c0117c
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variation
			isDefault
			relationship: e03c0d1d-d449-473a-9df5-c056ff95f569
			defaultHierarchy: LocalDateTable_6eea4b99-fcc3-4a06-b65b-48208e52226d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 040ddb60-95bb-4455-97b7-c97b48de0044
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: 3db504db-f159-4ed2-af20-850e5b735ecf
		summarizeBy: none
		sourceColumn: Inicio

		variation Variation
			isDefault
			relationship: 36e51c88-9c9e-4b5d-8ee2-886059cf8757
			defaultHierarchy: LocalDateTable_3dec0e66-0613-4adb-acfa-301fdf0b27c9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 68486817-4162-43aa-99c8-9d8f86602505
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: adea5bb8-1431-45e3-8c6d-816ca9a188f9
			defaultHierarchy: LocalDateTable_540c6fb8-a493-4f6b-b868-407172f4dba2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9ca32530-60b9-46c4-98bd-53ad97962dd2
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: 1d7a852b-7c39-42bc-9de6-c121f816a844
			defaultHierarchy: LocalDateTable_db190ea0-f337-4efb-be85-5370ece8b6d3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: 6017f6bc-97ca-4e10-976c-3b30044383b1
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: 46bfae67-3056-429c-9398-eed9aac4168d
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 69820bd3-88db-459d-a9c4-6ef1ad6fcff7
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: c5e633ec-0159-4946-9b7d-fd9ab96cf139
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 6af639b3-fc36-4549-9d70-0e866dabf327
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: 594902a3-940b-4a62-8635-75f9e0957e49
		summarizeBy: none
		sourceColumn: Fin

		variation Variación
			isDefault
			relationship: 6bed888b-735a-4dfe-bf8c-d551d9e4acb5
			defaultHierarchy: LocalDateTable_c1f7fcb5-a2f8-4fac-80c9-51a47aacd86b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones ENH-2190f109-9151-4b94-b221-5786518bc69d' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Source = Excel.Workbook(Web.Contents(sharepointRoot2 & ENH & xlsx), null, true),
				    #"Page 1_Sheet" = Source{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Promoted Headers",{{"Fecha de finalización derivada de", "Fecha final derivada de"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Número", type text}, {"Número_1", type text}, {"Nombre de subtarea", type text}, {"Prioridad", type text}, {"Abierto por", type text}, {"Grupo de asignación", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha fin planificada", type datetime}, {"Principal", type text}, {"Fecha Inicio Estimada", type datetime}, {"Fecha final derivada de", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Breve descripción", type text}}),
				    
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{
				        {"Número",                  "Demanda"},
				        {"Nombre de subtarea",      "Tipo de Proyecto"},  
				        {"Número_1",                "Número"}, 
				        {"Abierto por",             "Jefe de proyecto (Project Manager)"}, 
				        {"Grupo de asignación",     "Aplicación de Negocio "}, 
				        {"Principal",               "Nombre"}, 
				        {"Fecha Inicio Estimada",   "Inicio"}, 
				        {"Fecha final derivada de", "Fin"},
				        {"Breve descripción",       "Nombre de PRJ o MEJ"}}),
				    
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns",  "EN.EJE.EVODDAM_EXT.AE",      "DDAMM: DDAMM",                                           Replacer.ReplaceText,{"Aplicación de Negocio "}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",  "EN.EJE.EVOTDEM_EXT.AE",      "AAE: TDEM",                                              Replacer.ReplaceText,{"Aplicación de Negocio "}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1", "EN.EJE.EVOOMTE_EXT.AE",      "AAE: OMTE",                                              Replacer.ReplaceText,{"Aplicación de Negocio "}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2", "EN.EJE_EVO.COVE",            "AAE: Seguimiento y Control de Contratos de Venta AE",    Replacer.ReplaceText,{"Aplicación de Negocio "}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3", "EN.EJE.EVOSOLA_EXT.AE",      "AAE: SOLA (Acciona Solar)",                              Replacer.ReplaceText,{"Aplicación de Negocio "}),
				
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4", "EN.EJE.EVOAIRE_EXT.AE",      "AIRe (Asset Information Repository)",                    Replacer.ReplaceText,{"Aplicación de Negocio "}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5", "EN.EJE.EVOPGB_EXT.AE",       "AAE: PGB",                                               Replacer.ReplaceText,{"Aplicación de Negocio "}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6", "EJE.EVOPEPC_EXT.AE",         "PE Presas y Canales",                                    Replacer.ReplaceText,{"Aplicación de Negocio "}),    
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7", "EJE.EVOENERGYDB_EXT.AE",     "EnergyDashboard Web (Web de países)",                    Replacer.ReplaceText,{"Aplicación de Negocio "}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8", "EN.EJE.EVOACTIONPLAN_EXT.AE","Plan Acción AE: Plan Acción AE",                         Replacer.ReplaceText,{"Aplicación de Negocio "}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","EN.EJE.EVOMONITOR_EXT.AE",   "MAGUS",                                                  Replacer.ReplaceText,{"Aplicación de Negocio "}),
				        
				
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10", null, "",      Replacer.ReplaceValue,{"Nombre"}),
				    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11",null,"Mejora", Replacer.ReplaceValue,{"Tipo de Proyecto"})
				in
				    #"Replaced Value12"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

