table 'PRO - Estimaciones con SLA'
	lineageTag: 92ed336c-7d79-482d-8bcb-a491910be569

	column Creado
		dataType: dateTime
		formatString: General Date
		lineageTag: 4361fb03-b5e4-4f09-ab4b-20b3e3c80c5b
		summarizeBy: none
		sourceColumn: Creado

		variation Variation
			isDefault
			relationship: c0611801-5c18-4987-8879-fd5ec90bc80e
			defaultHierarchy: LocalDateTable_4154b662-4c11-4acc-a8d5-92bda6f30c47.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 4d99fdc9-82a1-42d7-b094-9a02eab3839f
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio'
		dataType: string
		lineageTag: 722c6c83-6489-4f1b-8473-5450c8db549d
		summarizeBy: none
		sourceColumn: Aplicación de Negocio

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 3dcea964-a150-45d9-8dc3-1c75289901b4
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Tarea
		dataType: string
		lineageTag: 0c755fc8-59c5-46c1-80ad-77afd16b51bf
		summarizeBy: none
		sourceColumn: Tarea

		annotation SummarizationSetBy = Automatic

	column Etapa
		dataType: string
		lineageTag: 2ef41e5f-9831-4cc4-a552-22af3fe37122
		summarizeBy: none
		sourceColumn: Etapa

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de negocio restante'
		dataType: int64
		formatString: 0
		lineageTag: 7a8b1574-4b2f-4687-9e2a-f7025ad0d908
		summarizeBy: sum
		sourceColumn: Tiempo de negocio restante

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: int64
		formatString: 0
		lineageTag: 54942a6c-7415-4c17-8779-d3e52edd9977
		summarizeBy: sum
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 3fd9a9d4-34f3-4a41-ac3e-5f4957e6bbc6
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Hora de inicio'
		dataType: dateTime
		formatString: General Date
		lineageTag: afb8c850-9798-4465-afc4-f0da627085ca
		summarizeBy: none
		sourceColumn: Hora de inicio

		variation Variation
			isDefault
			relationship: 6ec0d742-c0d5-4084-a395-f93e42d2f643
			defaultHierarchy: LocalDateTable_6680e904-7959-4182-97d6-20c73bd3c6cc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de pausa'
		dataType: string
		lineageTag: 2df01687-a884-4d5e-bef8-f2078a74853f
		summarizeBy: none
		sourceColumn: Tiempo de pausa

		annotation SummarizationSetBy = Automatic

	column 'Hora de finalización'
		dataType: dateTime
		formatString: General Date
		lineageTag: f18e76b2-f698-40ae-b104-cc6f8c00455b
		summarizeBy: none
		sourceColumn: Hora de finalización

		variation Variation
			isDefault
			relationship: ae9a7f90-d090-4d82-acf4-55ce3d95b525
			defaultHierarchy: LocalDateTable_4993cfe9-4249-4821-9e60-ca1e53d9538c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: e92dc53d-cee7-41a0-a47c-9be8d288884e
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Hora de finalización - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a5a23e2a-b02f-4893-8305-2afe357a999b
		summarizeBy: none
		sourceColumn: Hora de finalización - Copy

		variation Variation
			isDefault
			relationship: 65367430-15c7-4d2e-96e0-d485ed918178
			defaultHierarchy: LocalDateTable_41e01205-b8dc-49df-ae85-bd7a2fee388d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d0422279-0c6f-409c-a0ff-dc2a8c241e27
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7814d6d0-1d60-4659-9903-65c53ffd0ac8
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: d4fe648a-dfe0-46c9-a049-b62bfaaf7966
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Hora de infracción'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6bdc0e3d-cf73-4c5c-a425-2946bdc4e724
		summarizeBy: none
		sourceColumn: Hora de infracción

		variation Variation
			isDefault
			relationship: be06a05c-b94d-4a8c-a35d-6a44505e04d2
			defaultHierarchy: LocalDateTable_33b11963-4813-4752-8de2-a55c3421210c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: d7717594-9b0b-4423-acdf-46ea3577f614
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Duración excedida'
		dataType: string
		lineageTag: a129395f-195d-4795-88bb-f2f3f0cb48b9
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column 'Duración D:HH:MM:SS' =
			
			VAR VDUR13 = 'PRO - Estimaciones con SLA'[Duración del negocio]
			  RETURN INT
			    (VDUR13/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR13/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR13/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR13,60)),2)
		lineageTag: 575b3a12-bbb4-4a85-850a-3a35fca346d2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración_EX D:HH:MM:SS' =
			
			VAR VDUR13_EX = 'PRO - Estimaciones con SLA'[Duración excedida]
			  RETURN INT
			    (VDUR13_EX/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR13_EX/3600,24)),2)&" HH"
		lineageTag: 7cf1a4fa-e743-450a-82f5-140904f08721
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: a6e8c2e9-acab-4cf4-b8b0-e6f733e8aad4
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column Acción
		dataType: string
		lineageTag: 76be9fbe-9403-4a7d-9eda-d5428b5f5e2c
		summarizeBy: none
		sourceColumn: Acción

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 202a11e6-82d8-4b7a-ae67-4e9bd46b2b79
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Estimaciones con SLA'[Tarea])
		lineageTag: 9e56888c-b0b7-4453-a40d-1af563fd2efd
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Estimaciones con SLA-5a40b48a-1e50-4be9-880e-a8884b495a6d' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Source = #"PRO - Estimaciones con SLA (staging)",
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Creado", type datetime}, {"Número", type text}, {"Aplicación de Negocio", type text}, {"Prioridad", type text}, {"Tarea", type text}, {"Etapa", type text}, {"Tiempo de negocio restante", Int64.Type}, {"Duración del negocio", Int64.Type}, {"Porcentaje de negocio trascurrido", Percentage.Type}, {"Hora de inicio", type datetime}, {"Tiempo de pausa", type any}, {"Hora de finalización", type datetime}, {"Grupo de asignación", type text}, {"Infringido", type logical}, {"Hora de infracción", type datetime}, {"Duración", Int64.Type}}),
				    
				    //Genera Columna de Cerrado
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Hora de finalización", "Hora de finalización - Copy"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Duplicated Column",{{"Hora de finalización - Copy", type date}}),
				    #"Inserted Start of Month" = Table.AddColumn(#"Changed Type1", "Start of Month", each Date.StartOfMonth([#"Hora de finalización - Copy"]), type date),
				   
				   //Homologa las prioridades
				    #"Replaced Value" = Table.ReplaceValue(#"Inserted Start of Month",  "1 - Crítica",  "Alta",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",          "2 - Alta",     "Alta",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",         "3 - Moderada", "Media",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",         "4 - Baja",     "Baja",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3",         "5 - Muy Baja", "Baja",Replacer.ReplaceText,{"Prioridad"}),
				
				    //Pone "Nuevo Servicio" sobre Estimaciones de Demandas que no son Evolutivos
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4",         "",             "Nuevo Servicio",Replacer.ReplaceValue,{"Aplicación de Negocio"}),
				    //Une con las alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value5", {"Tarea"}, #"PRO - Alegaciones del Servicio KGI11", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"Solicitante", "Acción", "ANS", "Estado"}, {"PRO - Alegaciones del Servicio.Solicitante", "PRO - Alegaciones del Servicio.Acción", "PRO - Alegaciones del Servicio.ANS", "PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}, {"PRO - Alegaciones del Servicio.Solicitante", "Solicitante"}, {"PRO - Alegaciones del Servicio.Acción", "Acción"}, {"PRO - Alegaciones del Servicio.ANS", "ANS"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Infringido" si la alegación es aceptada y pedida por el Proveedor del Servicio (De True a False)
				    #"Replaced Value6" = Table.ReplaceValue(#"Renamed Columns",each [Infringido],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]="KGI_11" and [Solicitante]="Proveedor" and [Acción] ="Cambio Estimación Infringida"  then "FALSE" else [Infringido],Replacer.ReplaceValue,{"Infringido"}),
				
				    // Realiza la correción sobre el cumplimiento de la columna INfringido si la alegación es aceptada y pedida por el Cliente (De false a True)
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6",each [Infringido],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]="KGI _11" and [Solicitante]="Cliente" and [Acción] = "Cambio Estimación Infringida" then "TRUE" else [Infringido],Replacer.ReplaceValue,{"Infringido"}),
				
				    //Realiza la correción sobre la columna Prioridad si la alegación es aceptada y la Prioridad es Crítica
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7",each [Prioridad],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]="KGI _11" and [Acción]="Cambio Prioridad a Crítica" then "Alta" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				
				    //Realiza la correción sobre la columna Prioridad si la alegación es aceptada y la Prioridad es Alta
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8",each [Prioridad],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]="KGI _11" and [Acción]="Cambio Prioridad a Alta" then "Alta" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				
				    //Realiza la correción sobre la columna Prioridad si la alegación es aceptada y la Prioridad es Media
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9",each [Prioridad],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]="KGI _11" and [Acción]="Cambio Prioridad a Media" then "Media" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				
				    //Realiza la correción sobre la columna Prioridad si la alegación es aceptada y la Prioridad es Baja
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10",each [Prioridad],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]="KGI _11" and [Acción]="Cambio Prioridad a Baja" then "Baja" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value11",{{"Infringido", type logical}}),
				
				    //Elimina los duplicados, y deja el último SLA finalizado
				    #"Sorted Rows" = Table.Buffer(Table.Sort(#"Changed Type2",{{"Hora de finalización - Copy", Order.Descending}})),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"Tarea"}),
				
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Duplicates",{{"Duración", "Duración SLA"}}),
				
				    //Nuevo campo de Duración Excedida, respecto a SLA
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "Duración excedida", 
				    each if ([Duración del negocio]-[Duración SLA])<0 then 0 else 
				    ([Duración del negocio]-[Duración SLA])),
				    #"Divided Column" = Table.TransformColumns(#"Added Custom", {{"Porcentaje de negocio trascurrido", each _ / 100, Percentage.Type}})
				in
				    #"Divided Column"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

