table 'PRO - Alegaciones del Servicio KGI12'
	lineageTag: 5b9b412d-71e9-4bf6-81eb-9c46b8d15508

	column 'ID Alegación'
		dataType: string
		lineageTag: 3be54503-77d0-4472-a5e0-471cf3cffbcc
		summarizeBy: none
		sourceColumn: ID Alegación

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: 12c08333-b810-44df-83b8-1a57c78cb06d
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: 03736b00-e9df-4071-b183-5cb6b9c7bf24
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: 558c8345-aac0-4b65-b548-0c3ff00e82bc
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column Acción
		dataType: string
		lineageTag: 12bc9aae-ff23-405e-a44a-74aedcad6b28
		summarizeBy: none
		sourceColumn: Acción

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: dd5fa1a2-6801-4673-8dd4-0cf8a6ffd7c0
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1e261610-2dfc-4884-ac01-d2996978a55f
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		variation Variación
			isDefault
			relationship: 70736849-4edd-492e-abb3-146e5b2bed24
			defaultHierarchy: LocalDateTable_9002a2d1-cd93-4225-84c3-20e0d0b7134e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Clasificación
		dataType: string
		lineageTag: 27e438d0-e108-4a8a-9c36-15860d945b34
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: f6305e1a-02cb-4910-8347-6cd0d983e06e
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 9b2d85a0-deb1-4bb2-9128-7cdae5748c94
			defaultHierarchy: LocalDateTable_2b19cb59-d122-4621-a612-f6954ec02d7e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado
		dataType: string
		lineageTag: 7e899b7d-6dd1-41ad-be8a-72f88c5b3b89
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: d1480655-90db-4a36-9f13-783e7af611c5
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Comentarios Acciona'
		dataType: string
		lineageTag: f8a88fd5-13ce-403c-90a4-544d84e70739
		summarizeBy: none
		sourceColumn: Comentarios Acciona

		annotation SummarizationSetBy = Automatic

	column 'Comentarios Proveedor'
		dataType: string
		lineageTag: 0963de97-6581-41a0-9d4e-becade9a83b1
		summarizeBy: none
		sourceColumn: Comentarios Proveedor

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI12-00399769-0f18-4a9a-96d6-1e020a341721' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Origen = #"PRO - Alegaciones del Servicio",
				    #"Filas filtradas" = Table.SelectRows(Origen, each [ANS] = "KGI_12")
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

