table 'PRO - Incidencias con SLA (NY)'
	lineageTag: b90564b4-c446-49fe-bfc7-8aa0f9eee447

	column Número
		dataType: string
		lineageTag: 687abb47-839d-49bd-bae5-4082a71cdfe7
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 04290105-33a0-4444-852e-26700d5dcd61
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Subcategoría
		dataType: string
		lineageTag: 5dc9c187-e7e7-49a1-ac0c-e6aeff037618
		summarizeBy: none
		sourceColumn: Subcategoría

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 0ec721fe-b074-4961-9522-67c9a16fc8c9
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: ada0f961-bfd0-4e2c-9c7b-0d73e1ae9e7d
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: 618c746f-c13d-4acd-8351-8b96ded3f049
			defaultHierarchy: LocalDateTable_9956014c-20d7-4ffd-aad1-abaa1933034e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: 43f368c5-01b1-4c53-9d80-f66cf3cc340a
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variation
			isDefault
			relationship: 3c6d2f1d-93d4-40c1-b28c-e59129435d72
			defaultHierarchy: LocalDateTable_9b37082e-1340-4c52-84e6-f843f0d5ab8c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 750d2a5d-9d69-437c-8777-3d6fb5b0403d
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1eaf1018-fd52-452c-9c46-f01878bb415c
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2b30bd06-0e9b-4c93-93f1-531c00bde925
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: 50d916eb-71f9-454b-9be4-1e63dc6b4feb
			defaultHierarchy: LocalDateTable_842716ec-50cb-4aa3-9510-61e1eea618e3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 9a88352a-9224-410c-aedf-bff54e90a71a
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 050f5036-715a-4791-ad18-b437033427c1
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: int64
		formatString: 0
		lineageTag: 35c020b0-5260-4a27-8ce9-60a4977bb74d
		summarizeBy: sum
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 5f5ded6b-9c75-47e4-8302-dd82cbad0ba7
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: a38a6229-a05a-4d10-adff-392696b8253f
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: int64
		formatString: 0
		lineageTag: 48c0c7bc-01f4-4eec-ba00-25a3844de44b
		summarizeBy: sum
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: int64
		formatString: 0
		lineageTag: fb42c87d-2cfe-44ab-8b9d-494eb602d8ec
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 652ad514-8722-4d67-bc53-4558a0f0a489
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 292285ae-b113-44ef-81ec-66be43da3387
			defaultHierarchy: LocalDateTable_8aee61ed-97cd-47fe-9cf6-46814d0a6b90.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: d45695cd-7372-4e40-afbc-614554b5b1ce
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 0bf5296d-f756-4b98-954c-37d8d2dae98f
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: 57c718dc-9164-4328-bfaf-f75dd712df06
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Notas de trabajo'
		dataType: string
		lineageTag: cc3e1968-05e3-4dd4-883c-c94f48aea19d
		summarizeBy: none
		sourceColumn: Notas de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA (NY)-975bedd0-f3ff-45c0-b38f-d15ceeede48f' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Source = Excel.Workbook(Web.Contents(sharepointRoot2 & incidencias & xlsx), null, true),
				    #"Page 1_Sheet" = Source{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Columna condicional agregada" = Table.AddColumn(#"Promoted Headers", "¿Tiene que contar?", each if [Número] = "INC1898186" then "Si" else if [Número] = "INC1882874" then "Si" else if [Número] = "INC1894584" then "Si" else if [Grupo de asignación] = "EJE.SOPOMTE_EXT.AE" then "Si" else if [Grupo de asignación] = "EJE.SOPTDEM_EXT.AE" then "Si" else if [Grupo de asignación] = "EJE.SOPDDAM_EXT.AE" then "Si" else if [Grupo de asignación] = "EJE.SOPCOVE_EXT.AE" then "Si" else if [Grupo de asignación] = "EJE.SOPSOLA_EXT.AE" then "Si" else if [Grupo de asignación] = "EN.EJE.SOPAIRE_EXT.AE" then "Si" else if [Grupo de asignación] = "EN.EJE.SOPPGB_EXT.AE" then "Si" else if [Grupo de asignación] = "EJE.SOPPEPC_EXT.AE" then "Si" else if [Grupo de asignación] = "EJE.SOPENERGYDB_EXT.AE" then "Si" else if [Grupo de asignación] = "EN.EJE.SOPACTIONPLAN_EXT.AE" then "Si" else if [Grupo de asignación] = "EJE.SOPMONITOR_EXT.AE" then "Si" else if [Grupo de asignación] = "EJE.SOPWER_EXT.AE" then "Si" else if Text.Contains([Notas de trabajo], "#INCReasignadaInetum") then "Si" else "No"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Columna condicional agregada",{{"Número", type text}, {"Breve descripción", type text}, {"Subcategoría", type text}, {"Prioridad", type text}, {"Abierto", type datetime}, {"Cerrado", type datetime}, {"Resuelto", type datetime}, {"Duración", Int64.Type}, {"Duración del negocio", Int64.Type}, {"Infringido", type logical}, {"Tiempo original de incumplimiento", type datetime}, {"Estado del incidente", type text}, {"Etapa", type text}, {"Código de resolución", type text}, {"Volver a abrir recuento", Int64.Type}, {"Tipo de Solución", type text}, {"Duración_1", Int64.Type}, {"Porcentaje de negocio trascurrido", Int64.Type}}),
				    #"Filas filtradas" = Table.SelectRows(#"Changed Type", each ([#"¿Tiene que contar?"] = "Si")),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Filas filtradas",{"¿Tiene que contar?"}),
				
				    #"Replaced Value" = Table.ReplaceValue(#"Columnas quitadas",     "1 - Crítica",     "Crítica",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",  "2 - Alta",        "Alta",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1", "3 - Media",       "Media",Replacer.ReplaceText,{"Prioridad"}),    
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2", "4 - Baja",        "Baja",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3", "5 - Muy Baja",    "Baja",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4", "3 - Moderada",    "Media",Replacer.ReplaceText,{"Prioridad"}),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value5",{{"Resuelto", "Fecha de resolución"}, {"Duración del negocio", "Duración real"}, {"Etapa", "Estado SLA"}, {"Estado del incidente", "Estado"}, {"Código de resolución", "Código de cierre"}, {"Volver a abrir recuento", "Reabierta"}, {"Tipo de Solución", "Tipo de solución"}, {"Duración_1", "Duración SLA"}}),
				    #"Duplicados quitados" = Table.Distinct(#"Renamed Columns", {"Número"})
				in
				    #"Duplicados quitados"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

