table 'PRO - Incidencias con SLA (NY y MAD)- Tabla relacionada'
	lineageTag: 55c4b93a-2c26-45f6-8fb4-91c351fbf636

	column Número
		dataType: string
		lineageTag: 40555e6b-1809-4461-a63d-13fc749bf00d
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 5713f85d-171b-4e5b-9b0a-5b5eb23be393
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: a39241fd-99f1-486a-bf9d-415ac1a379ee
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 94326172-a2ce-4135-acfc-084d75b16e17
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: c334a2f0-1383-4628-b884-7456e685360e
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: a3203aab-c725-41df-8e53-decfd2bae2d0
			defaultHierarchy: LocalDateTable_c99aa787-df8d-46f4-b3ab-af45d17c7041.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: a92571bb-92e9-488f-bab8-055eca4d8fee
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variación
			isDefault
			relationship: 1bbd573f-73ae-440c-8a8e-c1a5a8e0615c
			defaultHierarchy: LocalDateTable_a5e80d8b-110e-46c8-8b45-48bce16ce00d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 569e41f8-5d04-42ae-94b0-3836efa356f5
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 6fa903ab-4c0e-43b8-8e2c-6d005b68efc7
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 19ea60ad-6dc1-45e6-92cb-a1a3de42db5c
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4a3f4bbd-d3e5-4df4-9ec5-7ae2b3a726cc
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variación
			isDefault
			relationship: b93429c3-4582-444e-98ff-9aacf0b1ce57
			defaultHierarchy: LocalDateTable_9511226c-1ab1-4a91-b8f3-34b137ef399a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 41f29d7d-33a7-4c05-beca-67242c21ed34
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 0ec8cee9-99a8-4561-b309-c818899142c6
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 111100c0-aae9-41d0-bb91-b9aab3e4dd3d
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: 0f328626-a5a3-4cd6-8d6c-48f7c9a9b0e1
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 12f714ed-ccb4-4919-93f5-61af8eeea43b
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: string
		lineageTag: 087e8aab-4cbc-44c4-8eea-cc7b983fa19c
		summarizeBy: none
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: b44fee04-6fab-48b9-9b41-67f47fdcf15b
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 3b22d1e8-a908-40e0-9e48-cb8fba68859a
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Estado_Alegado
		dataType: string
		lineageTag: 7cdadb82-a862-43d0-b695-c5b5661692a2
		summarizeBy: none
		sourceColumn: Estado_Alegado

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: 627d05c0-200f-48b2-95b6-f635b110cd87
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column Acción_ANS
		dataType: string
		lineageTag: 09585c40-44ce-4613-bcf8-af7d9f46a187
		summarizeBy: none
		sourceColumn: Acción_ANS

		annotation SummarizationSetBy = Automatic

	column 'Duración excedida'
		dataType: string
		lineageTag: a255b146-d072-48be-84e8-b338b964198b
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column 'Incidencias_relacionadas.Tarea'
		dataType: string
		lineageTag: f36cb972-bbb0-4842-b2c1-7d7d94511a87
		summarizeBy: none
		sourceColumn: Incidencias_relacionadas.Tarea

		annotation SummarizationSetBy = Automatic

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4d36f8b1-dde0-42c7-adaa-c131f23392d6
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ServiceNow_Incidencia = CONCATENATE("https://acciona.service-now.com/incident.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA (NY y MAD)- Tabla relacionada'[Número])
		lineageTag: d6787a70-2ebd-402a-97a4-5516e95ae217
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ServiceNow_Tarea = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA (NY y MAD)- Tabla relacionada'[Incidencias_relacionadas.Tarea])
		lineageTag: cc912714-2fb4-48da-9a30-4255248ec11b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 40c66b91-410a-4441-b1a2-f22d478ac2c4
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: f151f30d-e3b6-4626-9975-0f86575d3084
			defaultHierarchy: LocalDateTable_7ab69e59-c29f-479c-a198-d65ca9080c98.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: b7ba2ea3-53bd-45b0-961c-38cc4549fa71
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: f2b62cce-7a36-4d26-a720-49f44768270a
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Notas de trabajo'
		dataType: string
		lineageTag: 322803ce-2363-4d98-b6d7-c4721dce3d1c
		summarizeBy: none
		sourceColumn: Notas de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA (NY y MAD)- Tabla relacionada-aaee1e3e-2933-4f91-92df-5f377880a71d' = m
		mode: import
		queryGroup: KGIs_II
		source =
				let
				    Origen = #"PRO - Incidencias con SLA (NY y MAD)",
				    #"Consultas combinadas" = Table.NestedJoin(Origen, {"Número"}, Incidencias_relacionadas, {"Incidente"}, "Incidencias_relacionadas", JoinKind.LeftOuter),
				    #"Se expandió Incidencias_relacionadas" = Table.ExpandTableColumn(#"Consultas combinadas", "Incidencias_relacionadas", {"Tarea"}, {"Incidencias_relacionadas.Tarea"}),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Se expandió Incidencias_relacionadas", {"Incidencias_relacionadas.Tarea"}, #"PRO - Planificaciones PRJ y ENH con SLA", {"Número"}, "PRO - Planificaciones PRJ y ENH con SLA", JoinKind.LeftOuter),
				    #"Se expandió PRO - Planificaciones PRJ y ENH con SLA" = Table.ExpandTableColumn(#"Consultas combinadas1", "PRO - Planificaciones PRJ y ENH con SLA", {"Fecha fin real - Copy"}, {"PRO - Planificaciones PRJ y ENH con SLA.Fecha fin real - Copy"}),
				    #"Filas filtradas" = Table.SelectRows(#"Se expandió PRO - Planificaciones PRJ y ENH con SLA", each ([Incidencias_relacionadas.Tarea] <> null)),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Filas filtradas",{"Cerrado - Copy"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas",{{"PRO - Planificaciones PRJ y ENH con SLA.Fecha fin real - Copy", "Cerrado - Copy"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

