table 'PRO - Alegaciones del Servicio KGI13_23'
	lineageTag: 93dc8714-1534-44bb-bb5f-31098537139a

	column 'ID Alegación'
		dataType: string
		lineageTag: a50aa3dc-9cbf-4d6d-ac75-7e24806a85e2
		summarizeBy: none
		sourceColumn: ID Alegación

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: 62141619-65db-47ae-b86b-2bf024b1034b
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: c7ccc549-a7d1-4b55-b571-1ec8a8b540aa
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8caa11d4-ee58-48b9-bd02-302583f5e36d
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		variation Variation
			isDefault
			relationship: 3d88ffdf-39c5-4f4d-a4bb-2b5e591d228d
			defaultHierarchy: LocalDateTable_574ac9ac-778f-47e4-bd38-9aa2b1d6f0c2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Clasificación
		dataType: string
		lineageTag: 4162227b-4729-4084-a8de-18a3c2d98748
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 52421a80-47cf-4eec-9055-f7bcaaf37b90
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 05a3eb3f-56fd-4966-8edc-92ec47996c4d
		summarizeBy: none
		sourceColumn: Fecha

		variation Variation
			isDefault
			relationship: 60f1d5e0-7151-4844-9f0a-9b78400939e2
			defaultHierarchy: LocalDateTable_d6f0f1fe-9b08-4c1f-ad6d-cf0ac8a21b1e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado
		dataType: string
		lineageTag: ae87a17b-bfca-4526-b203-03cd70aa37ca
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: 6b085af6-86ea-421b-aa10-a91e2487fe8f
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: f17527da-ce37-42a3-a92c-a4d9c827ab28
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column Acción
		dataType: string
		lineageTag: 5af7ba88-e068-47ed-a933-085f8f663346
		summarizeBy: none
		sourceColumn: Acción

		annotation SummarizationSetBy = Automatic

	column 'Comentarios Acciona'
		dataType: string
		lineageTag: fb0e3cb8-c691-4661-8e55-6a0bbe30d898
		summarizeBy: none
		sourceColumn: Comentarios Acciona

		annotation SummarizationSetBy = Automatic

	column 'Comentarios Proveedor'
		dataType: string
		lineageTag: cb0e2ecf-94c7-4c99-b365-6520581d491f
		summarizeBy: none
		sourceColumn: Comentarios Proveedor

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI13_23-787f99d6-f47d-466c-9bfa-2d0cec7f3b40' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Source = #"PRO - Alegaciones del Servicio",
				    #"Filtered Rows" = Table.SelectRows(Source, each [ANS] = "Cambio_Estado_Incidencia")
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

