table 'PRO - Incidencias con SLA (NY y MAD) KGI22'
	lineageTag: 4086135c-f5df-4865-8425-751a6b812343

	column Número
		dataType: string
		lineageTag: 233332da-885d-4305-b7c7-0eba7c9a9c60
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 6376cb4d-8a7e-44fa-8658-22e360e9d90f
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: d131eed3-f7b7-43e9-b8bd-20ca84de7564
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 7b542233-3bbc-4f1b-a76d-c073510b1cfb
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 13f8b71b-4c34-42b3-aade-5c73593d89fe
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: 50f69d06-9a6d-4a28-8078-27e64240bba6
			defaultHierarchy: LocalDateTable_6a5d59cc-551e-478e-a3e0-786a085fc267.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: 3a8e3952-1fa9-447e-91b0-e6dd1bee4d47
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variation
			isDefault
			relationship: 1ea3464d-b1c5-4022-9fe6-cfd9009b99aa
			defaultHierarchy: LocalDateTable_dbdf5187-3a55-4053-a7d0-d4ecb1ecb0e5.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: bdfef2cc-ae60-41e9-b47c-d2ba711541c5
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: c3e276a0-6298-46a4-913f-671274c73eab
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3e939a51-6317-4d92-bd9b-0e0ed4d1fed7
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: 85aad20d-cf8b-4ae7-95e3-b4e4eb49e840
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: ba6b8db8-9bfc-4143-a9a1-2ded9630ff65
			defaultHierarchy: LocalDateTable_db76f728-ce90-4d0a-9848-4f0989c735e4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: d2b6c3d8-015d-4714-aebe-5cffb462f093
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 311d07ae-39aa-42d7-93b3-996986f15ff8
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 5b0933de-9207-4e79-ae04-dc974e5a26ec
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 19a9cec1-bfeb-418c-bc44-f3c23e4c2fab
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: b1234c65-d395-47c0-8c22-99b5130df758
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: string
		lineageTag: 55a059af-9a8f-4e5a-ad97-311559b2fa96
		summarizeBy: none
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		lineageTag: 12343cbf-9dc6-45f3-9ad5-f705656eff7d
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 380629d4-0987-4011-afe3-29b9b31d5eb3
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		variation Variation
			isDefault
			relationship: fe542435-e74f-4d4c-8858-729aee24c2a9
			defaultHierarchy: LocalDateTable_9f2b2f1e-537f-4727-8e95-f16b2c07c3b8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración excedida'
		dataType: string
		lineageTag: 0e68ffe4-ff48-4e49-bc00-af605ae44783
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 579d769c-54a8-413d-b3a7-9940bf3ced99
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 2d210150-b350-4394-a00e-e6725f50a36b
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column Acción
		dataType: string
		lineageTag: 3091bef1-f9ce-4c7e-b5ef-da2b46d3005d
		summarizeBy: none
		sourceColumn: Acción

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: b96ab04d-f846-4aa0-b228-dd7691e0960e
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA (NY y MAD) KGI22'[Número])
		lineageTag: 45826a47-a2ae-40f7-9a8c-c11e5518cd3f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 2bd56906-837e-47b9-916d-1f69dd7ce597
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 056a1581-d5a3-495e-a982-80359f9529b5
			defaultHierarchy: LocalDateTable_0bfdfe93-b40c-48be-beab-3a060753bee7.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: a8808260-93b6-44e8-ae8f-8eb597343914
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: ba5f7778-587c-436f-8312-0ec7ce605364
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Notas de trabajo'
		dataType: string
		lineageTag: 12a3709e-ba9f-41ac-ade8-ba88eb224f43
		summarizeBy: none
		sourceColumn: Notas de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA (NY y MAD) KGI22-c9215f40-3e03-4500-8f98-ad7060976968' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Source = #"PRO - Incidencias con SLA (NY y MAD)",
				    #"Columnas quitadas" = Table.RemoveColumns(Source,{"ANS", "Estado_Alegado", "Solicitante", "Acción_ANS"}),
				    //Une con tabla de alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Columnas quitadas", {"Número"}, #"PRO - Alegaciones del Servicio KGI22", {"ID"}, "PRO - Alegaciones del Servicio KGI22", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio KGI22" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio KGI22", {"Acción", "ANS", "Estado", "Solicitante"}, {"PRO - Alegaciones del Servicio KGI22.Acción", "PRO - Alegaciones del Servicio KGI22.ANS", "PRO - Alegaciones del Servicio KGI22.Estado", "PRO - Alegaciones del Servicio KGI22.Solicitante"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio KGI22",{{"PRO - Alegaciones del Servicio KGI22.ANS", "ANS_Alegado"}, {"PRO - Alegaciones del Servicio KGI22.Estado", "Estado_Alegación"}, {"PRO - Alegaciones del Servicio KGI22.Solicitante", "Solicitante"}, {"PRO - Alegaciones del Servicio KGI22.Acción", "Acción"}}),
				    //Realiza la corrección sobre el cumplimiento de la columna "Reabierta" si la alegación es aceptada
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1",each [Reabierta],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI_22" and [Solicitante] = "Proveedor" and [Acción] = "Cambio Incidencia Reabierta" then "FALSE" else [Reabierta],Replacer.ReplaceValue,{"Reabierta"}),
				    
				    // Realiza la correción sobre el cumplimiento de la columna Reabierta a True si la alegación es pedida por el Cliente (acciona)
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",each [Reabierta],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI_22" and [Solicitante] = "Acciona" and [Acción] ="Cambio Incidencia Reabierta" then "True" else [Reabierta],Replacer.ReplaceValue,{"Reabierta"}),
				
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value1",{{"Reabierta", type logical}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

