table 'PRO - Incidencias con SLA (NY y MAD) - Abiertas'
	lineageTag: 9bf93f6f-19bc-471c-98f6-ce2acc8a99f9

	column Número
		dataType: string
		lineageTag: 61691430-b466-4a4f-b4c4-c0d596f5890e
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: ba702c26-af61-442e-b52a-81bc5dd39f23
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: 0067bb59-89e7-466e-93bb-2ee826d285f0
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: b91376e7-874c-4ff4-80a6-7198f179ed89
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: string
		lineageTag: 06e9cb46-e79d-4fdd-b8e6-91371defb86e
		summarizeBy: none
		sourceColumn: Abierto

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: string
		lineageTag: c1a5adc5-3f35-4a23-b56f-a219027ff022
		summarizeBy: none
		sourceColumn: Cerrado

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: string
		lineageTag: 99fdd014-ff45-4a62-9af8-2f756054df0a
		summarizeBy: none
		sourceColumn: Fecha de resolución

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: string
		lineageTag: 36dafce3-2d95-4e3f-99d3-8ea3b08a732c
		summarizeBy: none
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: string
		lineageTag: 1b302d44-534c-4ec3-9acf-0b8a4a0789ec
		summarizeBy: none
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: string
		lineageTag: 634bdd5f-ea7a-4805-910e-56687d2497ee
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: string
		lineageTag: f342262b-6262-4f39-9602-34ff7db935a0
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 2aab6a0a-7069-49fe-9fc3-5250d5fe30c8
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: bad4d62b-668f-40a9-8be7-50edbb081404
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 70b40f5d-d0d6-43ed-af13-8b90c809b61c
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: fe16f33d-f33b-4d09-88bc-d6b3e1a7dc4d
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 6c8c020b-ba8d-43e8-95da-f5658f070638
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Abierto - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4cb4b9b-0a2c-47dd-86f1-3ae4b8e8594a
		summarizeBy: none
		sourceColumn: Abierto - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración SLA'
		dataType: string
		lineageTag: 4a52c656-d933-4f57-b7f5-5dcc63f6e442
		summarizeBy: none
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: string
		lineageTag: 21c8772b-aa71-43e4-bbce-a9182b378e1a
		summarizeBy: none
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: 06fc40c5-d7eb-44ab-ae46-b0ed6f6b5c09
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: d33c271c-0456-46ca-a3cf-13c5e7607c2e
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Acción_ANS
		dataType: string
		lineageTag: d189251f-acc9-44c4-abff-b2e43c8d7923
		summarizeBy: none
		sourceColumn: Acción_ANS

		annotation SummarizationSetBy = Automatic

	column Estado_Alegado
		dataType: string
		lineageTag: cd8289a3-7922-4cf7-9813-f34989fa2da7
		summarizeBy: none
		sourceColumn: Estado_Alegado

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA (NY y MAD) - Abiertas'[Número])
		lineageTag: 9ca3aca9-62ea-4657-b0d4-f641cc8a7a74
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: fa828116-9550-4ca9-bdca-b9f6b993d8bc
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: 536982c3-7caa-41ec-acfe-ea5e1baf1aad
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Notas de trabajo'
		dataType: string
		lineageTag: 3477b949-8f20-46d3-a673-d455865afdf7
		summarizeBy: none
		sourceColumn: Notas de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA (NY y MAD) - Abiertas-4a3c2bdf-d9cf-4cdd-9832-99d81a25d932' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Origen = Excel.Workbook(Web.Contents(sharepointRoot2 & incidenciasSN & xlsx), null, true),
				
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Número", type text}, {"Breve descripción", type text}, {"Subcategoría", type text}, {"Prioridad", type text}, {"Abierto", type datetime}, {"Cerrado", type datetime}, {"Fecha de resolución", type datetime}, {"Duración", Int64.Type}, {"Duración real", Int64.Type}, {"Infringido", type logical}, {"Tiempo original de incumplimiento", type datetime}, {"Estado", type text}, {"Estado SLA", type text}, {"Código de cierre", type text}, {"Reabierta", type logical}, {"Tipo de solución", type text}, {"Duración SLA", Int64.Type}, {"Porcentaje de negocio trascurrido", Int64.Type}}),
				
				    #"Appended Query" = Table.Combine({#"Encabezados promovidos", #"PRO - Incidencias con SLA (NY)"}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Appended Query", "Abierto", "Abierto - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Abierto - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Abierto - Copy", Date.StartOfMonth, type date}}),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Calculated Start of Month",{{"Subcategoría", "Sistema"}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Renamed Columns", {"Número"}, #"PRO - Alegaciones del Servicio KGI13_23", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Se expandió PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Consultas combinadas", "PRO - Alegaciones del Servicio", {"Solicitante", "ANS", "Acción", "Estado"}, {"PRO - Alegaciones del Servicio.Solicitante", "PRO - Alegaciones del Servicio.ANS", "PRO - Alegaciones del Servicio.Acción", "PRO - Alegaciones del Servicio.Estado"}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Se expandió PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Solicitante", "Solicitante"}, {"PRO - Alegaciones del Servicio.ANS", "ANS"}, {"PRO - Alegaciones del Servicio.Acción", "Acción_ANS"}, {"PRO - Alegaciones del Servicio.Estado", "Estado_Alegado"}}),
				
				    #"Replaced Value" = Table.ReplaceValue(#"Columnas con nombre cambiado1", each [Estado],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Estado_Incidencia" and [Acción_ANS] = "Cambio Estado Incidencia" and [Solicitante]="Cliente"  then "Cerrado" else [Estado],Replacer.ReplaceValue,{"Estado"}),
				
				    // Realiza la correción sobre el campo Estado y modificarlo de cerrado a cancelado si la alegación es pedida por el Proveedor
				
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value", each [Estado],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Estado_Incidencia" and [Acción_ANS] = "Cambio Estado Incidencia" and [Solicitante]="Proveedor"  then "Cancelado" else [Estado],Replacer.ReplaceValue,{"Estado"}),
				        
				        
				     //Cambio criticidad a crítica si la alegación es de cambio de criticidad
				     
				     #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1", each [Prioridad],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Crítica" then "Crítica" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				    //Cambio criticidad a Alta si la alegación es de cambio de criticidad
				     #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2", each [Prioridad],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Alta" then "Alta" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				    //Cambio criticidad a Media si la alegación es de cambio de criticidad
				     #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3", each [Prioridad],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Media" then "Media" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				    
				    //Cambio criticidad a Baja si la alegación es de cambio de criticidad
				     #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4", each [Prioridad],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Baja" then "Baja" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				
				    //Reemplazamos la duración de la criticidad Crítica a la duración correcta:
				     #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5", each [Duración SLA],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Crítica" then "14400" else [Duración SLA],Replacer.ReplaceValue,{"Duración SLA"}),
				    
				     #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6", each [Duración SLA],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Alta" then "43200" else [Duración SLA],Replacer.ReplaceValue,{"Duración SLA"}),
				
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7", each [Duración SLA],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Media" then "173800" else [Duración SLA],Replacer.ReplaceValue,{"Duración SLA"}),
				    
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8", each [Duración SLA],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Baja" then "345600" else [Duración SLA],Replacer.ReplaceValue,{"Duración SLA"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Replaced Value9", each [Estado] <> "Cancelado"),
				    #"Filtered Rows2" = Table.SelectRows(#"Filas filtradas1", each (
				    [Código de cierre] = "" or
				    [Código de cierre] = "No user response" or
				    [Código de cierre] = "Solucionado en remoto" or
				    [Código de cierre] = "Solucionado nivel 2" or
				    [Código de cierre] = "solucionado ON-SITE" or
				    [Código de cierre] = "Solucionado Temporalmente" or
				    [Código de cierre] = "Solucionado mail" or
				    [Código de cierre] = "Solucionado por teléfono" or
				    [Código de cierre] = "Solucionado (solución temporal)" or
				    [Código de cierre] = "Solucionado (de forma permanente)" or
				    [Código de cierre] = "Solucionado remotamente (solución temporal)" or
				    [Código de cierre] = "Solucionado remotamente (de forma permanente)")),
				    #"Duplicados quitados1" = Table.Distinct(#"Filtered Rows2", {"Número"})
				in
				    #"Duplicados quitados1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

