table 'PRO - Planificaciones MA'
	lineageTag: 035301b5-3c74-48f0-8a4f-243201a87ccb

	column Demanda
		dataType: string
		lineageTag: 03b9f2f2-5d14-41b9-861e-b56e1d5c4fdc
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 6ad84cbe-7d5f-4257-8497-ec88fb599453
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 3c568560-f7df-4cfb-9ed9-94c54bc6e34b
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: c4346e56-c9be-4efc-937e-10a5d502aba5
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: 4f49f4e5-f8d4-4bfb-bdaf-35f16befdde9
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: 0f74b51f-4a9f-4468-a3ab-671c0e8b81e7
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: d378c816-65ba-4cec-ba69-cc75682bd7cd
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variation
			isDefault
			relationship: c0dc5dea-f6c6-4a2b-881b-472e59e45fe4
			defaultHierarchy: LocalDateTable_87f238ce-74bd-430f-a234-b3268f5e603a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: c2ada413-c475-44b6-a9b5-7d895d918d5c
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variation
			isDefault
			relationship: d00d1fa5-eab4-4feb-a783-77cb00b41f0c
			defaultHierarchy: LocalDateTable_bc49cfaf-ddfe-47c9-8456-63973c478459.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 9dc75a02-cc1a-43ab-9d25-50950cc26b5f
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: 55f43c1d-8efa-4c1e-8537-1961bda21168
		summarizeBy: none
		sourceColumn: Inicio

		variation Variation
			isDefault
			relationship: 4197dd68-fe91-4c8b-800c-e8030444f8cd
			defaultHierarchy: LocalDateTable_fab4f37c-ada9-4051-9aac-7c3b8ea35895.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 93e7332a-fce8-449f-8642-2e91935f554c
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: 8d39ee24-2def-4f18-82be-b1167cd6d1b1
			defaultHierarchy: LocalDateTable_db21fe7b-a358-4ea7-9fa2-a06c7427c2e6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1cdca09a-acb1-40d1-ab25-aa71c3721232
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: 8dd4b141-d074-47b0-8f08-85421abfc9a3
			defaultHierarchy: LocalDateTable_2e572349-472e-41a3-996a-c0b1b9e10b8f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: bfccac2d-b9d9-43c3-8aa0-3228e5c1d44e
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: 9cc63d30-bb3e-43f3-94f6-0cd079951417
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 30a530fc-53ca-49f6-95be-a26fd0d980e8
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: 07d2ada7-792f-415b-a297-ca35dec677a1
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: 603ca23e-2cce-4805-a28a-f8bda14b1637
		summarizeBy: none
		sourceColumn: Fin

		variation Variación
			isDefault
			relationship: bf6a6163-4199-4ee1-b95c-85a94213ae4b
			defaultHierarchy: LocalDateTable_5b1b0b05-5159-42f2-af91-71ed74546426.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones MA-1bbf12c3-f8b5-4d8f-a1ed-7153b6d995b3' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Source = Excel.Workbook(Web.Contents(sharepointRoot2 & EVO & xlsx), null, true),
				    #"Page 1_Sheet" = Source{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Promoted Headers",{{"Fecha de finalización derivada de", "Fecha final derivada de"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Número", type text}, {"Número_1", type text}, {"Tipo de Proyecto", type text}, {"Prioridad", type text}, {"Jefe de proyecto (Project Manager)", type text}, {"Aplicación de Negocio ", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha fin planificada", type datetime}, {"Nombre de subtarea", type text}, {"Fecha de inicio derivada de", type datetime}, {"Fecha final derivada de", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Breve descripción", type text}}),
				
				    //Homologa cabeceras para realizar posterior Append con PRJs
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{
				        {"Número",                      "Demanda"},
				        {"Número_1",                    "Número"}, 
				        {"Nombre de subtarea",          "Nombre"}, 
				        {"Fecha de inicio derivada de", "Inicio"}, 
				        {"Fecha final derivada de",     "Fin"}, 
				        {"Breve descripción",           "Nombre de PRJ o MEJ"}})
				
				in
				    #"Renamed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

