table 'PRO - Planificaciones PRJ y ENH con SLA'
	lineageTag: 5cf9b13f-e0fe-4319-83de-09d2a2c36239

	column Demanda
		dataType: string
		lineageTag: 5065e6b6-8bb8-4cd6-8545-3c1bc7762290
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: a73e985e-f405-4bc7-b8e6-fd220ea7fee8
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 6563bd2d-3803-42ee-afee-e3f42b68168d
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 00a8e8bb-b911-44d4-ad26-32868e4610e6
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variation
			isDefault
			relationship: fd4b799a-e636-4850-9165-5103041c1f6e
			defaultHierarchy: LocalDateTable_cbe44c7a-b1cf-4d00-a27e-e5063836a862.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 20a01368-3f02-4950-968c-fbed8dab0edb
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variation
			isDefault
			relationship: e83269ba-b99f-4ef6-ad9d-87bc25520034
			defaultHierarchy: LocalDateTable_f70a1ef5-4887-4557-b5ab-13907149e605.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 4956ad37-ea72-4be1-9326-cc9f6a67dea9
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: 814916e5-0fab-4875-9e92-1f5a0b629be9
		summarizeBy: none
		sourceColumn: Inicio

		variation Variation
			isDefault
			relationship: 2fc0c468-7c8c-4a4a-8d0c-cfdca082f41f
			defaultHierarchy: LocalDateTable_3b7dc721-8d9d-4a09-9c14-c575fb4024ba.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: 2b4a17d6-7cda-47f4-919b-c0ba1a0ea9e4
		summarizeBy: none
		sourceColumn: Fin

		variation Variation
			isDefault
			relationship: ae7d02c7-d061-4a82-b922-a24f4616d1cc
			defaultHierarchy: LocalDateTable_e52f7151-aa87-4747-a6fb-0c6eebaf8376.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: eebaca6f-ceb9-469b-bff8-c615db73e8ed
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variation
			isDefault
			relationship: ec56ba0a-0bdc-48be-9b65-11f245a7f2fe
			defaultHierarchy: LocalDateTable_c2eadd93-34ab-4f0b-8e7d-d7f09e29571b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: b87a82b3-7fd2-42ce-84ac-7f0e60bb9055
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variation
			isDefault
			relationship: a8b0b940-9db3-4cdb-8e34-9cc0cdda63cf
			defaultHierarchy: LocalDateTable_909091cb-d835-454e-a1a9-e5c4cc0f6e39.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: 730d1ef8-8736-494c-9e6d-c04b96f0c35d
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: 8b27780b-56a1-4ce6-808a-43273e58d8a1
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 99f78b5b-4092-4413-92cb-abdcc1d097ed
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9654cceb-4272-4c7f-96ea-ef8b6b0d0cab
		summarizeBy: none
		sourceColumn: Fecha fin real - Copy

		variation Variation
			isDefault
			relationship: 607894f4-8844-4c45-9eee-454ef429b4c6
			defaultHierarchy: LocalDateTable_42c6b304-4b9d-43fd-9680-f3686fcd5203.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: 4d0feac5-c362-4719-b9e7-7e357c3678d0
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: aa8e3c26-020e-439b-a623-5d138595d6de
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Duración Planificada LB'
		dataType: double
		lineageTag: fb535403-3956-4d88-94a3-dec259a4bc72
		summarizeBy: sum
		sourceColumn: Duración Planificada LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real LB'
		dataType: double
		lineageTag: a6941a35-779c-4e35-83bf-b25458561320
		summarizeBy: sum
		sourceColumn: Duración real LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa de desviación'
		dataType: double
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 4c31c520-0c6e-4682-af0e-6ad04de2af1d
		summarizeBy: sum
		sourceColumn: Tasa de desviación

		annotation SummarizationSetBy = Automatic

	column 'Estimación incumplida'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6c9d3d73-380e-40ff-a9a8-36391b4a4828
		summarizeBy: none
		sourceColumn: Estimación incumplida

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: e7dead72-08e9-4a75-9482-4d9656e5b9b2
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 0da93ad3-85b6-4e5a-824d-634f2d7ca28c
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio '
		dataType: string
		lineageTag: 48b23d04-6d93-44b4-9654-826b27b36f5b
		summarizeBy: none
		sourceColumn: "Aplicación de Negocio "

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: 27bd954c-5167-4c5d-a6f0-807854525575
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column Acción
		dataType: string
		lineageTag: 2b714ea2-5888-4bed-83ed-7827d72c4e74
		summarizeBy: none
		sourceColumn: Acción

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: b9ed71e4-5bd0-4199-97de-0298458c053d
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Planificaciones PRJ y ENH con SLA'[Número])
		lineageTag: ced3bef3-be53-4c4a-ac9a-ac407473066c
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Fecha límite planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1497b735-ddc9-4172-8a8b-c565c010c96a
		summarizeBy: none
		sourceColumn: Fecha límite planificada

		variation Variación
			isDefault
			relationship: 566f75b8-83b9-40d5-a15a-9a1fc3d94cc2
			defaultHierarchy: LocalDateTable_108840d2-135b-4e77-b8d3-dcccc612ceb9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Planificaciones PRJ y ENH con SLA-c4488ef7-b8a5-455a-a73c-cefca85f53ea' = m
		mode: import
		queryGroup: KGIs_I
		source = ```
				let
				    Source = #"PRO - Planificaciones PRJ y ENH con SLA (staging)",
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Promoted Headers",{{"Fecha de finalización planificada", "Fecha límite planificada"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Demanda", type text}, {"Número", type text}, {"Tipo de Proyecto", type text}, {"Prioridad", type text}, {"Jefe de proyecto (Project Manager)", type text}, {"Aplicación de Negocio ", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha límite planificada", type datetime}, {"Nombre", type text}, {"Inicio", type datetime}, {"Fin", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Nombre de proyecto", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Nombre de proyecto", "Nombre de PRJ o MEJ"}}),
				
					//Filtro por solo proyectos y mejoras de aplicaciones a cargo del proveedor GFI
					#"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Tipo de Proyecto] <> "Mantenimiento de Aplicaciones")),
				
				    //Une tablas de Mejoras y Proyectos de Mantenimiento de Aplicaciones
				    #"Appended Query" = Table.Combine({#"Filtered Rows", #"PRO - Planificaciones ENH"}),
				    #"Appended Query1" = Table.Combine({#"Appended Query", #"PRO - Planificaciones MA"}),
				
				    #"Replaced Value" = Table.ReplaceValue(#"Appended Query1",      "1 - Crítica",  "Alta",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",      "2 - Alta",     "Alta",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",     "3 - Moderada", "Media",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",     "4 - Baja",     "Baja",Replacer.ReplaceText,{"Prioridad"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3",     "5 - Muy Baja", "Baja",Replacer.ReplaceText,{"Prioridad"}),
				
				    //Nueva columna "Fecha (1er día de mes)"
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced Value4", "Fecha fin real", "Fecha fin real - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Fecha fin real - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Fecha fin real - Copy", Date.StartOfMonth, type date}}),
				
				    //Nueva columna "Duración planificada de línea base"    
				    #"Added Custom1" = Table.AddColumn(#"Calculated Start of Month", "Duración Planificada LB", each [Fin]-[Inicio]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Duración Planificada LB", type number}}),
				
				   //Nueva columna "Duración real para cálculo con planificación de línea base" 
				    #"Added Custom2" = Table.AddColumn(#"Changed Type1", "Duración real LB", 
				    each if [Nombre] <> "" then ([Fecha fin real]-[Fecha de inicio real]) else ""),
				    
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom2",{{"Duración real LB", type number}}),
				
				    //Nueva columna "Tasa de desviación"
				    #"Added Custom3" = Table.AddColumn(#"Changed Type2", "Tasa de desviación",
				    each if [Nombre] = "" then (([Duración real]-[Duración planificada])/[Duración planificada]) else (([Duración real]-[Duración planificada])/[Duración planificada])),
				 
				    //Quita los proyectos y mejoras que tienen por error duración real o planificada = 0
				    #"Filtered Rows1" = Table.SelectRows(#"Added Custom3", each ([Duración real] <> 0) and ([Duración planificada] <> 0)),
				
				    //Columna "Estimación incumplida"
				    #"Added Custom4" = Table.AddColumn(#"Filtered Rows1", "Estimación incumplida",
				    each if [Prioridad]="Alta" and [Tasa de desviación]>0 then "TRUE" else
				         if [Prioridad]="Media" and [Tasa de desviación]>0.05 then "TRUE" else
				         if [Prioridad]="Baja" and [Tasa de desviación]>0.10 then "TRUE" else "FALSE"),
				
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom4",{{"Tasa de desviación", Percentage.Type}}),
				    //Une con las alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type3", {"Número"}, #"PRO - Alegaciones del Servicio KGI12", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"Solicitante", "Acción", "ANS", "Estado"}, {"PRO - Alegaciones del Servicio.Solicitante", "PRO - Alegaciones del Servicio.Acción", "PRO - Alegaciones del Servicio.ANS", "PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}, {"PRO - Alegaciones del Servicio.Solicitante", "Solicitante"}, {"PRO - Alegaciones del Servicio.Acción", "Acción"}, {"PRO - Alegaciones del Servicio.ANS", "ANS"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Estimación incumplida" si la alegación es aceptada y pedida por el Proveedor (De True a False)
				    #"Replaced Value5" = Table.ReplaceValue(#"Renamed Columns1",each [Estimación incumplida],each if [Estado_Alegación] = "1 - Aprobada" and [ANS] ="KGI_12" and [Solicitante] ="Proveedor"  and [Acción] ="Cambio Planificación Infringida" then "FALSE" else [Estimación incumplida],Replacer.ReplaceValue,{"Estimación incumplida"}),
				
				    //Realiza la correción sobre el cumplimiento de la columna "Estimación incumplida" si la alegación es aceptada y pedida por el Cliente (De False a True)
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5",each [Estimación incumplida],each if [Estado_Alegación] = "1 - Aprobada" and [ANS] ="KGI_12" and [Solicitante] ="Acciona" and [Acción] ="Cambio Planificación Infringida" then "TRUE" else [Estimación incumplida],Replacer.ReplaceValue,{"Estimación incumplida"}),
				
				    //Realiza la correción sobre la columna Prioridad si la alegación es aceptada y la Prioridad es Crítica
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6",each [Prioridad],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]="KGI_12" and [Acción]="Cambio Prioridad a Crítica" then "Alta" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				
				    //Realiza la correción sobre la columna Prioridad si la alegación es aceptada y la Prioridad es Alta
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7",each [Prioridad],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]="KGI_12" and [Acción]="Cambio Prioridad a Alta" then "Alta" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				
				    //Realiza la correción sobre la columna Prioridad si la alegación es aceptada y la Prioridad es Media
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8",each [Prioridad],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]="KGI_12" and [Acción]="Cambio Prioridad a Media" then "Media" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				
				    //Realiza la correción sobre la columna Prioridad si la alegación es aceptada y la Prioridad es Baja
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9",each [Prioridad],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]="KGI_12" and [Acción]="Cambio Prioridad a Baja" then "Baja" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				
				
				    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value10",{{"Estimación incumplida", type logical}}),
				    #"Duplicados quitados" = Table.Distinct(#"Changed Type4", {"Número"})
				in
				    #"Duplicados quitados"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

