table 'PRO - Alegaciones del Servicio KGI14'
	lineageTag: 215880a5-b5c8-46a2-a480-d9de0777b917

	column 'ID Alegación'
		dataType: string
		lineageTag: cad39775-b49d-42a6-86eb-a470c3a83efb
		summarizeBy: none
		sourceColumn: ID Alegación

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: 86b0d055-9f58-4bb2-b2bf-ec86c7b0eccb
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: 2739f533-8540-4efa-b4b9-b838a164dd3e
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: 3ab56863-36ea-45c2-af55-8f3c67c04f57
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 10eec387-d208-4963-ba03-6e263ca35df1
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Acción
		dataType: string
		lineageTag: 13353a38-89b6-4580-8ec5-c796bd530f40
		summarizeBy: none
		sourceColumn: Acción

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a7848dbf-c9a7-4528-a7c8-40675e02d694
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		variation Variación
			isDefault
			relationship: 7a5b52c2-8fd1-4c3b-8393-d96674fb5bd4
			defaultHierarchy: LocalDateTable_dacfb988-ec3e-4f0b-b88d-fc4a03f42512.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Clasificación
		dataType: string
		lineageTag: dcb5ab32-a217-4d06-86d9-b23437203cf6
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: c07a9184-fdd1-4759-997a-39a48f5de440
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 5e3c9f63-24e0-4873-b3c0-78a444ad1cf0
			defaultHierarchy: LocalDateTable_b2ad0b8a-3a15-47cc-ab08-e05f9f165f95.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado
		dataType: string
		lineageTag: 078227e2-47ee-43d5-a246-aa18c1d38a99
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: 8096a5af-47e3-46d4-a304-4a5dfd684263
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column 'Comentarios Acciona'
		dataType: string
		lineageTag: e98b6d8c-1c42-45de-998a-419bb92cab96
		summarizeBy: none
		sourceColumn: Comentarios Acciona

		annotation SummarizationSetBy = Automatic

	column 'Comentarios Proveedor'
		dataType: string
		lineageTag: 58dffc7c-abcc-454e-a9b6-aaa4e30a92f1
		summarizeBy: none
		sourceColumn: Comentarios Proveedor

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI14-e1036ebe-7716-45e8-a466-de1f490d828f' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Origen = #"PRO - Alegaciones del Servicio",
				    #"Filas filtradas" = Table.SelectRows(Origen, each ([ANS] = "KGI_14"))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

