table 'PRO - Jira - Entregables con SLA'
	lineageTag: c39dd0b2-2ba8-49dd-b73b-61ead2a2bc8a

	column 'Issue Type'
		dataType: string
		lineageTag: ba97a79e-594f-4878-bbc2-a9c29cf893bb
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column 'Deliverable type'
		dataType: string
		lineageTag: 5b91e41b-bd03-46a9-b5b8-dd9b3f934c0c
		summarizeBy: none
		sourceColumn: Deliverable type

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: a6471cb7-fbc8-41aa-93d3-98d10af57d12
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 0dcda3c7-dff6-434e-877a-b40b83a7e934
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Components
		dataType: string
		lineageTag: 59703e69-b337-4435-8fdf-921fae7e3515
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: ea8dbb72-e93d-45c7-9ccb-ec42f05b08ef
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 5cd80d71-e0ba-4c50-8ef4-444292262ffa
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 1e37c3e8-f1db-4503-a3fc-e19d31d9fe58
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 0c8aa90b-6cf5-4acf-9c6b-481967f6f9f3
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Approval status'
		dataType: string
		lineageTag: 6f916e6b-5ca1-4614-be10-d46088789644
		summarizeBy: none
		sourceColumn: Approval status

		annotation SummarizationSetBy = Automatic

	column 'End Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: c7961b55-c161-428a-bee1-134d1742bfbb
		summarizeBy: none
		sourceColumn: End Date

		variation Variation
			isDefault
			relationship: 7b4ec046-1469-4caf-966e-318ff31328ef
			defaultHierarchy: LocalDateTable_6e423e19-7dcc-4bc9-b608-96246d23fd1c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'End Real Date'
		dataType: string
		lineageTag: 382439af-50d7-42dc-b54d-84d276947e4d
		summarizeBy: none
		sourceColumn: End Real Date

		annotation SummarizationSetBy = Automatic

	column 'Linked Issues'
		dataType: string
		lineageTag: 8dce9086-a6ac-48ed-b7f4-e4ab1266ccb3
		summarizeBy: none
		sourceColumn: Linked Issues

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 10b3638c-8196-423e-b560-78d1c7a19de1
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: 3d941d18-013a-415a-8ca3-173e1406aaef
		summarizeBy: none
		sourceColumn: Resolved

		variation Variation
			isDefault
			relationship: aa53e35f-ae8b-4895-8f91-7fb89cddf609
			defaultHierarchy: LocalDateTable_46a76802-ae76-4760-bbed-491a88a809ca.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Rechazado
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 68f62685-a1b4-4b8a-8519-a68ce44955bf
		summarizeBy: none
		sourceColumn: Rechazado

		annotation SummarizationSetBy = Automatic

	column 'Resolved - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 35b778f6-5d65-4628-91c4-714fdb78b976
		summarizeBy: none
		sourceColumn: Resolved - Copy

		variation Variation
			isDefault
			relationship: d1a6849a-a35c-4578-b17c-6b193b4c5e63
			defaultHierarchy: LocalDateTable_53f1cfb0-ae1d-4f42-a817-e08f280299c1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado_Alegación
		dataType: string
		lineageTag: 549e6adb-7a75-423a-874f-f18bf9399e73
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 497ceab4-a762-4068-bef6-6ac0fce4d614
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: 3238a60a-1bf9-4ae8-89ad-dae996e634da
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column Acción
		dataType: string
		lineageTag: cd7e3d9a-2fba-47e1-b492-d573f42aa7d3
		summarizeBy: none
		sourceColumn: Acción

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: cc1bb231-fe4e-430e-a2cc-8db49f910ed3
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Jira - Entregables con SLA-026f8374-c7bc-4278-aef1-d2db0b540af0' = m
		mode: import
		queryGroup: KGIs_I
		source =
				let
				    Source = #"PRO - Jira - Entregables con SLA (staging)",
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Issue Type", type text}, {"Deliverable type", type text}, {"Project", type text}, {"Key", type text}, {"Components", type text}, {"Summary", type text}, {"Priority", type text}, {"Assignee", type text}, {"Status", type text}, {"Approval status", type text}, {"End Date", type datetime}, {"End Real Date", type text}, {"Linked Issues", type text}, {"Sub-tasks", type text}, {"Resolved", type datetime}, {"Rechazos", type logical}}),
				
				    //Todos los Entregables terminados = Done
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Status] = "Done")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each ([Deliverable type] = "Document")),
				
				    //Homgeneiza la prioridad proveniente de Jira a los valores de ANS
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows1",   "Highest",  "Grave",Replacer.ReplaceText,{"Priority"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",  "High",     "Grave",Replacer.ReplaceText,{"Priority"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1", "Medium",   "Grave",Replacer.ReplaceText,{"Priority"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2", "Low",      "Leve",Replacer.ReplaceText,{"Priority"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3", "Lowest",   "Leve",Replacer.ReplaceText,{"Priority"}),
				
				    //Renombra la Prioridad por "Tipo" de incumplimiento como dice el ANS
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value4",{{"Priority", "Tipo"}, {"Rechazos", "Rechazado"}}),
				
				    //Copia el campo Resolved para relacionar a la tabla fechas
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "Resolved", "Resolved - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Resolved - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Resolved - Copy", Date.StartOfMonth, type date}}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Calculated Start of Month",null,false,Replacer.ReplaceValue,{"Rechazado"}),
				
				    //Une con las alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value5", {"Key"}, #"PRO - Alegaciones del Servicio", {"ID"}, "PRO - Alegaciones del Servicio", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio", {"Solicitante", "Acción", "ANS", "Estado"}, {"PRO - Alegaciones del Servicio.Solicitante", "PRO - Alegaciones del Servicio.Acción", "PRO - Alegaciones del Servicio.ANS", "PRO - Alegaciones del Servicio.Estado"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio",{{"PRO - Alegaciones del Servicio.Estado", "Estado_Alegación"}, {"PRO - Alegaciones del Servicio.Solicitante", "Solicitante"}, {"PRO - Alegaciones del Servicio.Acción", "Acción"}, {"PRO - Alegaciones del Servicio.ANS", "ANS"}}),
				
				    //Realiza la corrección sobre el cumplimiento de la columna "Rechazado" si la alegación es aceptada y pedida por el Proveedor (TRUE a False)
				    #"Replaced Value6" = Table.ReplaceValue(#"Renamed Columns1",each [Rechazado],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]= "KGI_14" and [Solicitante] = "Proveedor" and [Acción] = "Cambio Estado Entregable" then "FALSE" else [Rechazado],Replacer.ReplaceValue,{"Rechazado"}),
				
				    //Realiza la correción sobre el cumplimiento de la columna "Rechazado" si la alegación es aceptada y Pedida por el CLiente (De False a True)
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6",each [Rechazado],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]= "KGI_14" and [Solicitante] = "Cliente" and [Acción]="Cambio Estado Entregable" then "TRUE" else [Rechazado],Replacer.ReplaceValue,{"Rechazado"}),
				
				    //Realiza la correción sobre la criticidad
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value6",each [Tipo],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]= "KGI_14" and [Acción]="Cambio Prioridad a Grave" then "Grave" else [Tipo],Replacer.ReplaceValue,{"Tipo"}),
				
				       //Realiza la correción sobre la criticidad
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value6",each [Tipo],each if [Estado_Alegación] = "1 - Aprobada" and [ANS]= "KGI_14" and [Acción]="Cambio Prioridad a Leve" then "Leve" else [Tipo],Replacer.ReplaceValue,{"Tipo"}),
				
				    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value9",{{"Rechazado", type logical}})
				
				in
				    #"Changed Type4"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

