table 'PRO - Incidencias con SLA (NY y MAD) KGI21'
	lineageTag: 4194496a-74a8-4502-8763-fd633e9fda09

	column Número
		dataType: string
		lineageTag: eb6f976f-c77e-4ffc-aadd-4856c20512a7
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: 521e2937-952a-4ac0-bd83-f3d9299920e1
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: 0e665248-8766-46f4-bde0-430a687e33b8
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: c3b29672-1d4b-4b66-ae5a-f5f2904ec1e2
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: f28cabbc-b036-416a-9911-a1b6d8aa386f
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variation
			isDefault
			relationship: 51176925-b9d2-4a3a-97cd-57b9d4e438e9
			defaultHierarchy: LocalDateTable_ef0465c2-99de-4cde-8a86-09863bda60b0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: a62b177d-6050-44f9-a6e0-8e4b4644f742
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variation
			isDefault
			relationship: d9bc3cbc-359a-41f4-a593-b1345e477a5c
			defaultHierarchy: LocalDateTable_e16fe118-d775-48c0-b0e0-f8a74a77974e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		formatString: 0
		lineageTag: 6c725630-31d5-4e97-b9f4-a4efa5688ee5
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 259c4045-9321-471f-b43b-48af4cc0833a
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b84d8bee-bb67-44f8-8771-4492212df599
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: ca5b25ea-5efb-4033-b3a2-1cf2d9b6c41c
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: 41b9d9c0-60f6-4961-b4f4-a176f7e4b7ad
			defaultHierarchy: LocalDateTable_fa4343de-3d81-470c-970b-2fe1f3a1363d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: b887a406-e01a-49a7-b4fe-afa1ba81f4cc
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: aff53334-35a3-449f-b4f0-eaee1d364e13
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 96c248d2-e13f-4d20-8c80-dd2ffe697536
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: b74f28bc-5192-4932-9b73-96fca5940258
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: d254e333-6312-48a7-9de5-e477585a910c
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: string
		lineageTag: 1d99604b-133e-4c28-b8f7-f08ecb16d3ac
		summarizeBy: none
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: b2eb9594-418d-424a-95f4-f17e002350e6
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d352a025-cf1f-4c6c-a798-fba0333f0855
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		variation Variation
			isDefault
			relationship: b3095bf3-8df4-4761-9a5d-ea8d56b9eb61
			defaultHierarchy: LocalDateTable_29d64ec7-e0fa-4eae-b057-c183cac6374b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración excedida'
		dataType: string
		lineageTag: f458a0fb-fdee-4ca4-b2b8-6ea66419482d
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column ANS_Alegado
		dataType: string
		lineageTag: 99f28f15-d8c4-4b0d-b9fb-9741ad527ae8
		summarizeBy: none
		sourceColumn: ANS_Alegado

		annotation SummarizationSetBy = Automatic

	column Estado_Alegación
		dataType: string
		lineageTag: 7f757bdc-168e-4482-a9e0-c312eb20b200
		summarizeBy: none
		sourceColumn: Estado_Alegación

		annotation SummarizationSetBy = Automatic

	column 'Infringidos Numérico' = IF('PRO - Incidencias con SLA (NY y MAD) KGI21'[Infringido] = TRUE(),1,0)
		formatString: 0
		lineageTag: cd1c6a06-c9ee-4947-9323-135255fa3514
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Duración D:HH:MM:SS' =
			
			VAR VDUR21 = 'PRO - Incidencias con SLA (NY y MAD) KGI21'[Duración real]
			  RETURN INT
			    (VDUR21/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21,60)),2)
		lineageTag: 73a0f2b4-0008-40c4-a298-18d574de7035
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración_EX D:HH:MM:SS' =
			
			VAR VDUR21_EX = 'PRO - Incidencias con SLA (NY y MAD) KGI21'[Duración excedida]
			  RETURN INT
			    (VDUR21_EX/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_EX/3600,24)),2)&" HH"
		lineageTag: 12190fbd-58e3-4804-ad34-174a7029f5b8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'No Infringidos Numerico' = IF('PRO - Incidencias con SLA (NY y MAD) KGI21'[Infringido] = TRUE(),0,1)
		formatString: 0
		lineageTag: c5a33dd9-5b72-4af0-94ae-c5e2e736dd08
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Acción
		dataType: string
		lineageTag: d521915d-22ae-443e-8969-1621c13467de
		summarizeBy: none
		sourceColumn: Acción

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: dac99c2f-a38f-4f36-beb8-3b658f2fcde5
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column ServiceNow = CONCATENATE("https://acciona.service-now.com/task.do?sysparm_query=number%3d", 'PRO - Incidencias con SLA (NY y MAD) KGI21'[Número])
		lineageTag: c61aa317-a834-4f0b-8d4b-96e5d92a3004
		dataCategory: WebUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 504af52b-05a7-4f13-836a-a968d41b9169
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: f9254baf-d926-4571-9fb9-805f40d585e8
			defaultHierarchy: LocalDateTable_31e30ba9-2b1b-4556-a485-905b121a326f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 5e06c998-a562-499e-959c-16a43c79f6dc
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: 487a0c0a-0619-466f-9377-bf29a9e8b914
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Notas de trabajo'
		dataType: string
		lineageTag: cfe6a18f-6dd8-4530-90db-332c8a60464d
		summarizeBy: none
		sourceColumn: Notas de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA (NY y MAD) KGI21-2a92e743-acb1-41c9-a2da-3ce76d79c137' = m
		mode: import
		queryGroup: KGIs_II
		source =
				let
				    Source = #"PRO - Incidencias con SLA (NY y MAD)",
				    #"Columnas quitadas" = Table.RemoveColumns(Source,{"ANS", "Estado_Alegado", "Solicitante", "Acción_ANS"}),
				    //Une con tabla de alegaciones
				    #"Merged Queries" = Table.NestedJoin(#"Columnas quitadas", {"Número"}, #"PRO - Alegaciones del Servicio KGI21", {"ID"}, "PRO - Alegaciones del Servicio KGI21", JoinKind.LeftOuter),
				    #"Expanded PRO - Alegaciones del Servicio KGI21" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Alegaciones del Servicio KGI21", {"Acción", "ANS", "Estado", "Solicitante"}, {"PRO - Alegaciones del Servicio KGI21.Acción", "PRO - Alegaciones del Servicio KGI21.ANS", "PRO - Alegaciones del Servicio KGI21.Estado", "PRO - Alegaciones del Servicio KGI21.Solicitante"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded PRO - Alegaciones del Servicio KGI21",{{"PRO - Alegaciones del Servicio KGI21.ANS", "ANS_Alegado"}, {"PRO - Alegaciones del Servicio KGI21.Estado", "Estado_Alegación"}, {"PRO - Alegaciones del Servicio KGI21.Solicitante", "Solicitante"}, {"PRO - Alegaciones del Servicio KGI21.Acción", "Acción"}}),
				    //Realiza la corrección sobre el cumplimiento de la columna "Infringido" si la alegación es aceptada y el peticionario es el Proveedor de Servicios
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1",each [Infringido],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI_21" and [Solicitante] = "Proveedor" then "FALSE" else [Infringido],Replacer.ReplaceValue,{"Infringido"}),
				
				    //Realiza la correción de Infringido, cambiando de Infringido False a Infringido True
				
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value", each [Infringido],
				        each if [Estado_Alegación] = "1 - Aprobada" and [ANS_Alegado] = "KGI_21" and [Solicitante] = "Acciona" and [Acción]="Cambio Incidencia Infringida" then "True" else [Infringido],Replacer.ReplaceValue,{"Infringido"}),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value1",{{"Infringido", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

