table 'PRO - Incidencias con SLA (NY y MAD)'
	lineageTag: ad33ce06-80c8-403c-9771-22de2c9231d6

	measure 'No. INCs cerradas_M' = COUNTROWS('PRO - Incidencias con SLA (NY y MAD)')
		formatString: 0
		lineageTag: 37fa1f2c-292a-45a8-8cf6-00117cabf70d

	column Número
		dataType: string
		lineageTag: 6acedf04-6ed1-4487-8407-eebc6dcc1a8a
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: db416e25-f465-4e1d-acf3-0bfbd9192148
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Sistema
		dataType: string
		lineageTag: e8067616-32b6-454c-b796-f35cc6fa6d32
		summarizeBy: none
		sourceColumn: Sistema

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 61c9bcd9-55fa-44d0-b1d3-90a1fbaa673f
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: db07d5f2-47a7-4231-97ed-9f26d9fa2b42
		summarizeBy: none
		sourceColumn: Abierto

		variation Variation
			isDefault
			relationship: 8dea28c3-c966-4da4-8865-17f378c28358
			defaultHierarchy: LocalDateTable_2ccb886c-8264-42d8-ad56-c3c6b25a9f4f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 5b614bd2-739b-4864-94bb-e8be91777c15
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: 5a2471d7-7ea4-4b25-947b-52b7fbedaad2
			defaultHierarchy: LocalDateTable_209201f4-7449-48d3-bbcb-0f0bfc302049.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: f143661e-622e-43a4-a438-c4a6354ecb6b
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variación
			isDefault
			relationship: 97dbc0fc-fa44-493c-8a83-2efb93948800
			defaultHierarchy: LocalDateTable_bf271174-3d26-4d57-9f64-c770bd59cca3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: int64
		lineageTag: cb05c12c-abec-4059-b509-ff4773ce84ff
		summarizeBy: sum
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real'
		dataType: int64
		lineageTag: a5e5c99a-6572-48de-bf9d-e699243182c8
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Infringido
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f724462b-cbd1-49ed-a426-8fddb3616086
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: dateTime
		formatString: General Date
		lineageTag: ff532383-6f89-47e3-a6d6-b7f1ebd55327
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		variation Variation
			isDefault
			relationship: 9ac7a0e2-a22f-4582-8b51-f492670bf948
			defaultHierarchy: LocalDateTable_c5f95c27-c66a-4ce2-be2a-25732842f539.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: eb6b3e42-0cdc-419f-b615-e3b8ea3306e1
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: 8da4c8ed-5557-43dd-a8b6-a9adc7e2493f
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: d41f4d73-d53c-4899-9940-e77d36918558
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: a5bcb685-f043-4303-941a-dc89bdec3bc9
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de solución'
		dataType: string
		lineageTag: 5b7a66d0-44e6-4d54-8dac-c0de186a3ade
		summarizeBy: none
		sourceColumn: Tipo de solución

		annotation SummarizationSetBy = Automatic

	column 'Infringidos Numérico' = IF('PRO - Incidencias con SLA (NY y MAD)'[Infringido] = TRUE(),1,0)
		formatString: 0
		lineageTag: fb473532-5dd3-4cc7-b649-794d93a57145
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'No Infringidos Numerico' = IF('PRO - Incidencias con SLA (NY y MAD)'[Infringido] = TRUE(),0,1)
		formatString: 0
		lineageTag: 986db6f0-b966-4b87-8940-888ba2277b65
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Mes = MONTH('PRO - Incidencias con SLA (NY y MAD)'[Cerrado])
		formatString: 0
		lineageTag: d832afb3-7f6a-4b4e-8ff3-5ab380d65b8c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Año = YEAR('PRO - Incidencias con SLA (NY y MAD)'[Cerrado])
		formatString: 0
		lineageTag: 4e7f36c2-95ae-44db-8b65-8216677008a9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Reabierta Numérica' = IF('PRO - Incidencias con SLA (NY y MAD)'[Reabierta] = TRUE(),1,0)
		formatString: 0
		lineageTag: 9e848583-fb3e-4811-8212-ec06bbb775a7
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column CerradoFecha = 'PRO - Incidencias con SLA (NY y MAD)'[Cerrado].[Date]
		formatString: dd/mm/yyyy
		lineageTag: 6d8fcd3e-6a97-4559-a99e-b59a4e6df3ef
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column AbiertoFecha = 'PRO - Incidencias con SLA (NY y MAD)'[Abierto].[Date]
		lineageTag: a173a185-dd26-425d-a67e-590a5481d886
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 8098c35d-8a66-4109-949e-c7d330cd2d4f
			defaultHierarchy: LocalDateTable_171aad4c-05dd-4c25-94a5-c61b530c1fa0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Cerrado - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5db204d1-21c7-46d9-90c7-3f0e044a3e91
		summarizeBy: none
		sourceColumn: Cerrado - Copy

		variation Variation
			isDefault
			relationship: a66d5235-c403-4232-8c6e-07fe88906a75
			defaultHierarchy: LocalDateTable_4607465a-a880-4db8-b384-5bea228541a6.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Duración SLA'
		dataType: string
		lineageTag: b3987308-5234-481e-b0e4-52ce489cc310
		summarizeBy: none
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7b282e41-5cca-40a7-bf6c-33f5dc6001d3
		summarizeBy: sum
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Duración excedida'
		dataType: string
		lineageTag: 1475b4b9-1b14-42d7-8315-7071c33017c1
		summarizeBy: none
		sourceColumn: Duración excedida

		annotation SummarizationSetBy = Automatic

	column 'Duración D:HH:MM:SS' =
			
			VAR VDUR21 = 'PRO - Incidencias con SLA (NY y MAD)'[Duración real]
			  RETURN INT
			    (VDUR21/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21/3600,24)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21/60,60)),2)&":"&
			    RIGHT("0" & INT(MOD(VDUR21,60)),2)
		lineageTag: a09f1539-bf02-46ca-be32-59379b04d882
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Duración_EX D:HH:MM:SS' =
			
			VAR VDUR21_EX = 'PRO - Incidencias con SLA (NY y MAD)'[Duración excedida]
			  RETURN INT
			    (VDUR21_EX/86400)&" Día(s) "&
			    RIGHT("0" & INT(MOD(VDUR21_EX/3600,24)),2)&" HH"
		lineageTag: 9dcf8bfb-ccc6-460c-933a-80c023e6bf76
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 7d30d7dc-da9d-4e57-857f-02d1d9e3f0a3
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Estado_Alegado
		dataType: string
		lineageTag: 370c8086-1ccd-4a02-96fe-112612bc042a
		summarizeBy: none
		sourceColumn: Estado_Alegado

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: c4246a09-89e8-4bb4-8993-186f913b4b58
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column Acción_ANS
		dataType: string
		lineageTag: 399fab65-c3cd-4024-8f5e-290468d4687a
		summarizeBy: none
		sourceColumn: Acción_ANS

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 2bcc5225-8a82-4145-8093-7306483d10c5
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column 'Grupo de asignación'
		dataType: string
		lineageTag: 3bfcb811-190a-46ee-8c6d-8c863ecec293
		summarizeBy: none
		sourceColumn: Grupo de asignación

		annotation SummarizationSetBy = Automatic

	column 'Notas de trabajo'
		dataType: string
		lineageTag: f6e01b70-e318-4ba5-9ff0-30d1dec602b0
		summarizeBy: none
		sourceColumn: Notas de trabajo

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Incidencias con SLA (NY y MAD)-0372dffc-56a7-4dc5-b546-b758c41a1f06' = m
		mode: import
		queryGroup: KGIs_II
		source = ```
				let
				    Origen = Excel.Workbook(Web.Contents(sharepointRoot2 & incidenciasSN & xlsx), null, true),
				    #"Page 1_Sheet" = Origen{[Item="Page 1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Page 1_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Número", type text}, {"Breve descripción", type text}, {"Subcategoría", type text}, {"Prioridad", type text}, {"Abierto", type datetime}, {"Cerrado", type datetime}, {"Fecha de resolución", type datetime}, {"Duración", Int64.Type}, {"Duración real", Int64.Type}, {"Infringido", type logical}, {"Tiempo original de incumplimiento", type datetime}, {"Estado", type text}, {"Estado SLA", type text}, {"Código de cierre", type text}, {"Reabierta", type logical}, {"Tipo de solución", type text}, {"Duración SLA", Int64.Type}, {"Porcentaje de negocio trascurrido", Int64.Type}}),
				
				    #"Appended Query" = Table.Combine({#"Tipo cambiado", #"PRO - Incidencias con SLA (NY)"}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Appended Query", "Cerrado", "Cerrado - Copy"),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Duplicated Column",{{"Estado", type text}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Tipo cambiado1",{{"Cerrado - Copy", Date.StartOfMonth, type datetime}}),
				    #"Extracted Date" = Table.TransformColumns(#"Calculated Start of Month",{{"Cerrado - Copy", DateTime.Date, type date}}),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Extracted Date",{{"Subcategoría", "Sistema"}}),
				    // Se une con las alegaciones que afectarán a todos los KGIs de M.Correctivo (Cambio de criticidad y cambio de estado).
				      
				   #"Consultas combinadas" = Table.NestedJoin(#"Renamed Columns", {"Número"}, #"PRO - Alegaciones del Servicio Todos KGIs", {"ID"}, "PRO - Alegaciones del Servicio Todos KGIs", JoinKind.LeftOuter),
				    #"Se expandió PRO - Alegaciones del Servicio Todos KGIs" = Table.ExpandTableColumn(#"Consultas combinadas", "PRO - Alegaciones del Servicio Todos KGIs", {"ANS", "Estado", "Solicitante", "Acción"}, {"PRO - Alegaciones del Servicio Todos KGIs.ANS", "PRO - Alegaciones del Servicio Todos KGIs.Estado", "PRO - Alegaciones del Servicio Todos KGIs.Solicitante", "PRO - Alegaciones del Servicio Todos KGIs.Acción"}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Se expandió PRO - Alegaciones del Servicio Todos KGIs",{{"PRO - Alegaciones del Servicio Todos KGIs.ANS", "ANS"}, {"PRO - Alegaciones del Servicio Todos KGIs.Estado", "Estado_Alegado"}, {"PRO - Alegaciones del Servicio Todos KGIs.Acción", "Acción_ANS"}, {"PRO - Alegaciones del Servicio Todos KGIs.Solicitante", "Solicitante"}}),
				    //Realiza la correción sobre el campo Estado y modificarlo de cancelado a cerrado si la alegación es pedida por el Cliente (Acciona).
				
				    #"Replaced Value" = Table.ReplaceValue(#"Columnas con nombre cambiado1", each [Estado],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Estado_Incidencia" and [Acción_ANS] = "Cambio Estado Incidencia" and [Solicitante]="Cliente"  then "Cerrado" else [Estado],Replacer.ReplaceValue,{"Estado"}),
				
				    // Realiza la correción sobre el campo Estado y modificarlo de cerrado a cancelado si la alegación es pedida por el Proveedor
				
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value", each [Estado],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Estado_Incidencia" and [Acción_ANS] = "Cambio Estado Incidencia" and [Solicitante]="Proveedor"  then "Cancelado" else [Estado],Replacer.ReplaceValue,{"Estado"}),
				        
				        
				     //Cambio criticidad a crítica si la alegación es de cambio de criticidad
				     
				     #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1", each [Prioridad],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Crítica" then "Crítica" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				    //Cambio criticidad a Alta si la alegación es de cambio de criticidad
				     #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2", each [Prioridad],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Alta" then "Alta" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				    //Cambio criticidad a Media si la alegación es de cambio de criticidad
				     #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3", each [Prioridad],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Media" then "Media" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				    
				    //Cambio criticidad a Baja si la alegación es de cambio de criticidad
				     #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4", each [Prioridad],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Baja" then "Baja" else [Prioridad],Replacer.ReplaceValue,{"Prioridad"}),
				
				    //Reemplazamos la duración de la criticidad Crítica a la duración correcta:
				     #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5", each [Duración SLA],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Crítica" then "14400" else [Duración SLA],Replacer.ReplaceValue,{"Duración SLA"}),
				    
				     #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6", each [Duración SLA],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Alta" then "43200" else [Duración SLA],Replacer.ReplaceValue,{"Duración SLA"}),
				
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7", each [Duración SLA],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Media" then "173800" else [Duración SLA],Replacer.ReplaceValue,{"Duración SLA"}),
				    
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8", each [Duración SLA],
				        each if [Estado_Alegado] = "1 - Aprobada" and [ANS] = "Cambio_Prioridad_Incidencia" and [Acción_ANS]="Cambio Prioridad a Baja" then "345600" else [Duración SLA],Replacer.ReplaceValue,{"Duración SLA"}),
				    //Nuevo campo de Duración excedida, respecto a SLA
				    #"Added Custom" = Table.AddColumn(#"Replaced Value9", "Duración excedida", 
				    each if ([Duración real]-[Duración SLA])<0 then 0 else 
				    ([Duración real]-[Duración SLA])),
				    #"Divided Column" = Table.TransformColumns(#"Added Custom", {{"Porcentaje de negocio trascurrido", each _ / 100, Percentage.Type}}),
				    #"Filas filtradas" = Table.SelectRows(#"Divided Column", each ([Estado] = "Cerrado")),
				    #"Duplicados quitados" = Table.Distinct(#"Filas filtradas", {"Número"})
				in
				    #"Duplicados quitados"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

