table 'PRO - Alegaciones del Servicio KGI22'
	lineageTag: cf9cc193-caaf-44d7-86d3-20c011508445

	column 'ID Alegación'
		dataType: string
		lineageTag: 22931cdd-56fb-41c3-9922-d15f12b77eec
		summarizeBy: none
		sourceColumn: ID Alegación

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: string
		lineageTag: 3277fa56-841d-43d0-aa4f-79f4a06bfad1
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Sistema Afectado'
		dataType: string
		lineageTag: 89a8c3bc-5500-4a99-8dfb-58bd9682dff4
		summarizeBy: none
		sourceColumn: Sistema Afectado

		annotation SummarizationSetBy = Automatic

	column 'Periodo de Medida del ANS alegado'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 34efbe86-5234-43e7-b345-160c18d41bbc
		summarizeBy: none
		sourceColumn: Periodo de Medida del ANS alegado

		variation Variation
			isDefault
			relationship: 7bad7327-e14e-49fb-9213-3a986c1db2ad
			defaultHierarchy: LocalDateTable_2d4b7552-2b8c-42f4-92f8-344e071e5c20.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Clasificación
		dataType: string
		lineageTag: 0b751f82-4e8b-4872-a69b-1ec8de21b740
		summarizeBy: none
		sourceColumn: Clasificación

		annotation SummarizationSetBy = Automatic

	column ANS
		dataType: string
		lineageTag: 34d78fb5-23f4-481d-8179-c1171393a52c
		summarizeBy: none
		sourceColumn: ANS

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6de677b5-6525-4367-855d-53cf2e47bc8c
		summarizeBy: none
		sourceColumn: Fecha

		variation Variation
			isDefault
			relationship: 7c70917f-c906-413f-8a19-1054999c9fa9
			defaultHierarchy: LocalDateTable_3873bd1d-36bd-4a16-a006-a7d34138d346.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Estado
		dataType: string
		lineageTag: 64951983-5dc1-4fe3-950d-0b402fdff537
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Comentarios
		dataType: string
		lineageTag: eb7bf471-c4d1-421a-8857-25d57591e4af
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column Solicitante
		dataType: string
		lineageTag: 37b68546-23dc-4514-a536-632abc76878f
		summarizeBy: none
		sourceColumn: Solicitante

		annotation SummarizationSetBy = Automatic

	column Acción
		dataType: string
		lineageTag: e4bff6d3-54dc-466f-8f7c-95b42f095b76
		summarizeBy: none
		sourceColumn: Acción

		annotation SummarizationSetBy = Automatic

	column 'Comentarios Acciona'
		dataType: string
		lineageTag: 2edef9d3-7da9-40f3-9267-6f191e32716a
		summarizeBy: none
		sourceColumn: Comentarios Acciona

		annotation SummarizationSetBy = Automatic

	column 'Comentarios Proveedor'
		dataType: string
		lineageTag: 8dd8c497-9797-4450-893c-4b565b9d316b
		summarizeBy: none
		sourceColumn: Comentarios Proveedor

		annotation SummarizationSetBy = Automatic

	partition 'PRO - Alegaciones del Servicio KGI22-e46ea911-7a75-444c-b992-f10a177d5dca' = m
		mode: import
		queryGroup: Alegaciones
		source =
				let
				    Source = #"PRO - Alegaciones del Servicio",
				    #"Filas filtradas" = Table.SelectRows(Source, each [ANS] = "KGI_22")
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

