table 'Resumen KGI1-2 Final'
	lineageTag: 6994b197-8fb8-4ca8-841f-e4de729f174f

	measure 'Peso Obtenido KGI12_M' = IF(MAX(Fechas[SERVICE_P])=0,"N/A",1-SUM('Resumen KGI1-2 Final'[Peso No Obtenido %]))
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 6cc513f2-fe91-420f-a070-e81af8be248e

	measure 'Puntos de KGI12_M' =
			
			var _KGI12_V = MIN('Resumen KGI1-2 Final'[Puntos de KGI12])
			return
			IF(ISBLANK(_KGI12_V),35,_KGI12_V)
		formatString: 0
		lineageTag: c3a615c3-1b24-45f7-82fc-e83190ce86bf

	measure 'Puntos Obtenidos KGI12_M' = IF(MAX(Fechas[SERVICE_P])=0,"N/A",[Peso Obtenido KGI12_M]*[Puntos de KGI12_M])
		formatString: 0
		lineageTag: 6e746655-a2fb-46ef-ab0c-943d20b574da

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Peso Obtenido KGI12_M average' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('Fechas'[MesNombreComp])),
				CALCULATE([Peso Obtenido KGI12_M])
			)
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 0b0cdc3f-bf3c-4050-9ba0-59c37c9d596c

	measure 'Puntos Obtenidos KGI12_M average' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('Fechas'[MesNombreCorto])),
				CALCULATE([Puntos Obtenidos KGI12_M])
			)
		formatString: 0.0
		lineageTag: ead9ca41-1daa-4a77-ba6f-cc177a2d2198

	column Prioridad
		dataType: string
		lineageTag: 44f5b35e-114f-4410-9022-555ddb8a50e4
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real - Copy'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 65ba5518-4686-4d7e-bf32-4fc7321ff69e
		summarizeBy: none
		sourceColumn: Fecha fin real - Copy

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Cump. Objetivo %'
		dataType: double
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: f96f148f-fdad-4cff-a884-4ead7e68936c
		summarizeBy: sum
		sourceColumn: Cump. Objetivo %

		annotation SummarizationSetBy = Automatic

	column 'Peso %'
		dataType: double
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 9546d19a-5cf3-45c7-98ac-d111640a62e3
		summarizeBy: sum
		sourceColumn: Peso %

		annotation SummarizationSetBy = Automatic

	column 'Planificaciones Cumplidas' = 'Resumen KGI1-2 Final'[Total Planificaciones]-'Resumen KGI1-2 Final'[Planificaciones Incumplidas]
		formatString: 0
		lineageTag: 7b75edf3-bc05-4a2c-997c-63e215f2b8cb
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Cump. Real %' = ('Resumen KGI1-2 Final'[Planificaciones Cumplidas])/('Resumen KGI1-2 Final'[Total Planificaciones])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 8ae9333d-8d7d-4af8-8dfb-003ad8acd32d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ¿Cumple? = IF('Resumen KGI1-2 Final'[Cump. Real %]>='Resumen KGI1-2 Final'[Cump. Objetivo %],"Si","No")
		lineageTag: 1681504c-cb01-4ecd-b6bb-adee6bc70888
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Peso Obtenido %' = IF('Resumen KGI1-2 Final'[¿Cumple?]="Si",'Resumen KGI1-2 Final'[Peso %],0)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: c86b8772-0a75-4648-91f9-0d49615ab646
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column KGI
		dataType: string
		lineageTag: 0200a415-a4d8-4bb7-9ce8-88aebe90cc2b
		summarizeBy: none
		sourceColumn: KGI

		annotation SummarizationSetBy = Automatic

	column 'Peso No Obtenido %' = IF('Resumen KGI1-2 Final'[¿Cumple?]="No",'Resumen KGI1-2 Final'[Peso %],0)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 2b346724-ceac-4121-8ff9-bdfdf7a36350
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Total Planificaciones'
		dataType: double
		formatString: 0
		lineageTag: a4714dd7-fcfa-4ebd-8418-44aba260ab29
		summarizeBy: sum
		sourceColumn: Total Planificaciones

		annotation SummarizationSetBy = Automatic

	column 'Planificaciones Incumplidas'
		dataType: double
		formatString: 0
		lineageTag: b20d55fa-7f42-42f2-9efd-b0454f2a3f4f
		summarizeBy: sum
		sourceColumn: Planificaciones Incumplidas

		annotation SummarizationSetBy = Automatic

	column 'Puntos de KGI12'
		dataType: string
		lineageTag: be428f12-140c-490f-85b9-fb5de3704d7b
		summarizeBy: none
		sourceColumn: Puntos de KGI12

		annotation SummarizationSetBy = Automatic

	partition 'Resumen KGI1-2 Final-92fbc821-a30e-445a-bc7f-df91b496157d' = m
		mode: import
		queryGroup: Resumen
		source = ```
				let
				    Source = #"PRO - Planificaciones PRJ y ENH con SLA",
				    
				    //Agrupar Total Planificaciones
				    #"Grouped Rows" = Table.Group(Source, {"Prioridad", "Fecha fin real - Copy"}, {{"Total Planificaciones", each Table.RowCount(_), type number}}),
				
				    //Unir Total Planificaciones Incumplidas
				    #"Merged Queries" = Table.NestedJoin(#"Grouped Rows", {"Prioridad", "Fecha fin real - Copy"}, #"PRO - Planificaciones PRJ y ENH con SLA - Incumplidas", {"Prioridad", "Fecha fin real - Copy"}, "PRO - Planificaciones PRJ y ENH con SLA - Incumplidas", JoinKind.LeftOuter),    
				    #"Expanded PRO - Planificaciones PRJ y ENH con SLA - Incumplidas" = Table.ExpandTableColumn(#"Merged Queries", "PRO - Planificaciones PRJ y ENH con SLA - Incumplidas", {"Estimación Incumplida"}, {"Planificaciones Incumplidas"}),    
				   
				    //Unir Tabla de Parámetros 
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded PRO - Planificaciones PRJ y ENH con SLA - Incumplidas", {"Prioridad"}, #"Parametros KGI1-2", {"Prioridad Hitos Evolutivos"}, "Parametros KGI1-2", JoinKind.LeftOuter),    
				    #"Expanded Parametros KGI1-2" = Table.ExpandTableColumn(#"Merged Queries1", "Parametros KGI1-2", {"% cumplimiento Objetivo", "Pesos %"}, {"Parametros KGI1-2.% cumplimiento Objetivo", "Parametros KGI1-2.Pesos %"}),    
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Parametros KGI1-2",{{"Parametros KGI1-2.% cumplimiento Objetivo", "Cump. Objetivo %"}, {"Parametros KGI1-2.Pesos %", "Peso %"}}),
				 
				    #"Sorted Rows" = Table.Sort(#"Renamed Columns1",{{"Fecha fin real - Copy", Order.Ascending}}),
				    
				    //Añadir otras columnas de valores constantes
				    #"Added Custom" = Table.AddColumn(#"Sorted Rows", "KGI", each "KGI1-2"),    
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Puntos de KGI12", each 35)
				in
				    #"Added Custom1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

