table KGI_I_Stories_ST_Executions_Jira
	lineageTag: dd370f1a-75d6-4daa-8c5b-1ef8d4b20487

	column Components
		dataType: string
		lineageTag: ee614569-71d1-41ae-996b-20c9345c4040
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: 767c7ea9-ba89-4167-9f8e-42adb789bfee
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: f0f52a0c-932b-40ca-8262-0479d98a9439
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 1b41f9d0-6536-4576-8e60-4c88fdc971a7
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 5fe62012-8cea-4037-865f-f3970d493014
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: 71a71a20-463a-477a-82a8-aaeb91ef9785
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: 92dd7008-d2b5-4b3f-8204-4c5a439ad888
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 04788342-2696-44cf-9ed4-e0ed564f3202
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 74afdb9d-4212-4248-b856-90fc25942414
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 6171b751-2fad-41fd-9ba6-d1aba2f941fc
		summarizeBy: none
		sourceColumn: Created

		variation Variación
			isDefault
			relationship: 1ca0caa6-d4d9-4959-96cc-011c1f3a6533
			defaultHierarchy: LocalDateTable_87301f5f-b5b2-4f8b-8efa-fec33e88e4c9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Linked Issues'
		dataType: string
		lineageTag: 93084a1d-1c5e-4c86-ad76-cd6b8630f3ac
		summarizeBy: none
		sourceColumn: Linked Issues

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: 3538853c-465b-4b0b-a5df-229a5595c7b8
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column 'Tipo de prueba'
		dataType: string
		lineageTag: 88477981-a493-4b5b-abfd-0af5e9a82ff9
		summarizeBy: none
		sourceColumn: Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: 5718c2c5-a7c2-4e6d-b865-7a67fa0d9934
		summarizeBy: none
		sourceColumn: Resolved

		variation Variación
			isDefault
			relationship: f86c3daf-61c4-4955-91cb-b8ea3c9bcb49
			defaultHierarchy: LocalDateTable_488cb73f-b057-4970-89de-f359fe1348b2.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'ST_Executions.Key'
		dataType: string
		lineageTag: 36ce5dab-a027-48a3-b554-ffe9e000eac1
		summarizeBy: none
		sourceColumn: ST_Executions.Key

		annotation SummarizationSetBy = Automatic

	column 'ST_Executions.Priority'
		dataType: string
		lineageTag: dfc08ac8-03ca-4c0b-b92a-d9bc01530c7b
		summarizeBy: none
		sourceColumn: ST_Executions.Priority

		annotation SummarizationSetBy = Automatic

	column 'ST_Executions.Status'
		dataType: string
		lineageTag: f328ecee-a77d-406c-879a-53c9a102b732
		summarizeBy: none
		sourceColumn: ST_Executions.Status

		annotation SummarizationSetBy = Automatic

	column 'ST_Executions.Tipo de prueba'
		dataType: string
		lineageTag: 85c38780-72ef-4e0a-b0e6-970f412a5fda
		summarizeBy: none
		sourceColumn: ST_Executions.Tipo de prueba

		annotation SummarizationSetBy = Automatic

	column 'ST_Executions.Resolved'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4a5723dc-942f-4f2a-ae32-c5d0b615e8ec
		summarizeBy: none
		sourceColumn: ST_Executions.Resolved

		variation Variación
			isDefault
			relationship: 0f32f1ec-c80c-41a2-b940-6ca758be7e0c
			defaultHierarchy: LocalDateTable_49536935-0745-43d5-a473-d595d09693f1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'ST_Executions.Valor'
		dataType: string
		lineageTag: 2ed750bc-a580-498b-9a1a-85bb2232ad4f
		summarizeBy: none
		sourceColumn: ST_Executions.Valor

		annotation SummarizationSetBy = Automatic

	column 'Resolved mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 54675443-f129-4b39-b1bf-9a5d281c461b
		summarizeBy: none
		sourceColumn: Resolved mes

		variation Variación
			isDefault
			relationship: ba9ce9d6-9ce3-47c7-9c5b-453af89d961e
			defaultHierarchy: LocalDateTable_7a0006fd-d1ce-4314-a1a9-7babc33a3235.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Prioridad grupo'
		dataType: string
		lineageTag: 285fbe27-6c2a-4389-a80c-fc5c13834198
		summarizeBy: none
		sourceColumn: Prioridad grupo

		annotation SummarizationSetBy = Automatic

	column Proyecto_Evolutivo
		dataType: string
		lineageTag: 47b0ee11-7bb3-4a46-a721-e68887b213c7
		summarizeBy: none
		sourceColumn: Proyecto_Evolutivo

		annotation SummarizationSetBy = Automatic

	partition KGI_I_Stories_ST_Executions_Jira-1648158b-4d16-4a84-8d36-4730afd5bf93 = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source =
				let
				    Origen = Table.NestedJoin(KGI_I_Stories_Jira, {"Key"}, KGI_I_ST_Excecutions_Jira, {"Valor"}, "ST Executions", JoinKind.LeftOuter),
				    #"Se expandió ST_Executions" = Table.ExpandTableColumn(Origen, "ST Executions", {"Key", "Priority", "Status", "Tipo de prueba", "Resolved", "Valor"}, {"ST_Executions.Key", "ST_Executions.Priority", "ST_Executions.Status", "ST_Executions.Tipo de prueba", "ST_Executions.Resolved", "ST_Executions.Valor"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Se expandió ST_Executions",{{"Resolved mes", type date}}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Tipo cambiado", "Personalizado", each if [Priority] = "Highest" then "Grave" else if [Priority] = "High" then "Grave" else if [Priority] = "Medium" then "Media" else if [Priority] = "Low" then "Leve" else if [Priority] = "Lowest" then "Leve" else null),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columna condicional agregada",{{"Personalizado", "Prioridad grupo"}}),
				    #"Columna condicional agregada1" = Table.AddColumn(#"Columnas con nombre cambiado", "Proyecto_Evolutivo", each if Text.StartsWith([Project], "Mtto") then "Evolutivos" else if [Project] = null then null else "Proyectos"),
				    #"Proyecto_Evolutivo" = Table.ReplaceErrorValues(#"Columna condicional agregada1", {{"Proyecto_Evolutivo", null}})
				in
				    Proyecto_Evolutivo

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

