table KGI_I_Tests_Jira
	lineageTag: ec48769e-d66b-4eb3-9218-88844e05b422

	column Components
		dataType: string
		lineageTag: 4d011445-4dba-47db-aba5-6feb29adcb16
		summarizeBy: none
		sourceColumn: Components

		annotation SummarizationSetBy = Automatic

	column Project
		dataType: string
		lineageTag: f2adb517-b177-4fa9-8f6d-81ff2e753c44
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column 'Issue Type'
		dataType: string
		lineageTag: 659b0541-0fd0-4fd4-8ed0-8774d26c5713
		summarizeBy: none
		sourceColumn: Issue Type

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 9056f7be-125b-4bc4-b2f9-1e0c3818e74a
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 2c7329f9-b482-4205-ae5d-96dc9cb6c37c
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column Assignee
		dataType: string
		lineageTag: ac17c652-6b9f-4a50-ad90-06dff5729a6b
		summarizeBy: none
		sourceColumn: Assignee

		annotation SummarizationSetBy = Automatic

	column Reporter
		dataType: string
		lineageTag: c02df110-dcf3-4ba7-86eb-99c95a2d43f6
		summarizeBy: none
		sourceColumn: Reporter

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 7f623629-02fb-4d71-88f5-f0b6709cc9a1
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 2c6b709c-3a0e-42c4-891e-f0e86a198b8a
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: 2b7a8465-be96-4fe5-aa59-f9e53ee4d07b
		summarizeBy: none
		sourceColumn: Created

		variation Variación
			isDefault
			relationship: 24b1dddb-5ad2-4370-8fc4-96b0be4b8386
			defaultHierarchy: LocalDateTable_c43196b2-11d5-4a9e-a1aa-eab3378a083f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Sub-tasks
		dataType: string
		lineageTag: e0d894d4-ac59-4bd9-b482-f7b5792b8b8b
		summarizeBy: none
		sourceColumn: Sub-tasks

		annotation SummarizationSetBy = Automatic

	column Resolved
		dataType: dateTime
		formatString: General Date
		lineageTag: 0ea5a1ba-d12d-47d0-95fc-4247217fffcf
		summarizeBy: none
		sourceColumn: Resolved

		variation Variación
			isDefault
			relationship: b48960a8-8d04-4a1a-b37b-de4f72bdea29
			defaultHierarchy: LocalDateTable_4946a3d4-7f25-4dd4-9c6f-5c555d56369c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Atributo
		dataType: string
		lineageTag: d1b4b853-562a-4b07-8620-c35e7cddfc65
		summarizeBy: none
		sourceColumn: Atributo

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: string
		lineageTag: 452cf1f0-2ae4-49eb-81e2-1a756f07ced0
		summarizeBy: none
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	column 'Tipo de prueba.1'
		dataType: string
		lineageTag: 3e15a1a5-f44f-4709-b44c-9bbd1b22c571
		summarizeBy: none
		sourceColumn: Tipo de prueba.1

		annotation SummarizationSetBy = Automatic

	column 'Tipo de prueba.2'
		dataType: string
		lineageTag: 4631e1e6-f963-4032-9f78-d552da00a181
		summarizeBy: none
		sourceColumn: Tipo de prueba.2

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Stories_Jira.Resolved mes'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 28b96a0b-a324-4cad-8f8a-35829ada616f
		summarizeBy: none
		sourceColumn: KGI_I_Stories_Jira.Resolved mes

		variation Variación
			isDefault
			relationship: 0794bfa9-d92c-40d1-95a9-caa025e717a9
			defaultHierarchy: LocalDateTable_2dcb06f0-bbcd-4a57-8eaf-ab5923f8b246.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'KGI_I_Stories_Jira.Key'
		dataType: string
		lineageTag: b0469361-c7b2-4ed1-8dfe-8a461440a9d6
		summarizeBy: none
		sourceColumn: KGI_I_Stories_Jira.Key

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Stories_Jira.Priority'
		dataType: string
		lineageTag: 77c88e32-8272-43a2-a0d0-ad1eba51fb57
		summarizeBy: none
		sourceColumn: KGI_I_Stories_Jira.Priority

		annotation SummarizationSetBy = Automatic

	column 'KGI_I_Stories_Jira.Resolved'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: abddd260-1927-4c6e-9a7c-4995521fc1cf
		summarizeBy: none
		sourceColumn: KGI_I_Stories_Jira.Resolved

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Project_starts_with
		dataType: string
		lineageTag: 2074dfef-c3ef-4f8b-b488-631fd88d77c0
		summarizeBy: none
		sourceColumn: Project_starts_with

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_1.5'
		dataType: string
		lineageTag: 3bd09a91-a754-4200-a3f1-48f5e8769086
		summarizeBy: none
		sourceColumn: ID_KGI_1.5

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_1.6'
		dataType: string
		lineageTag: 39c8ebc9-8d12-4ae4-85d8-7fdf9cf24a2c
		summarizeBy: none
		sourceColumn: ID_KGI_1.6

		annotation SummarizationSetBy = Automatic

	column Proyecto_Evolutivo
		dataType: string
		lineageTag: 07bc333c-dc13-42dc-8dee-d8573d88f3a3
		summarizeBy: none
		sourceColumn: Proyecto_Evolutivo

		annotation SummarizationSetBy = Automatic

	partition KGI_I_Tests_Jira-a94dd7e3-e18e-4f3c-9d85-073ea0532b5d = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source = ```
				let
				    Origen = #"KGI_I_Tests_Jira (stagging)",
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Created", type datetime}, {"Resolved", type datetime}}),
				    #"Separación Linked-Issues" = Table.SplitColumn(#"Tipo cambiado", "Linked Issues", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {
				        "Linked Issues.1",
				        "Linked Issues.2",
				        "Linked Issues.3",
				        "Linked Issues.4",
				        "Linked Issues.5",        
				        "Linked Issues.6",        
				        "Linked Issues.7",        
				        "Linked Issues.8",       
				        "Linked Issues.9",
				        "Linked Issues.10"        
				        }),
				    #"Columna de anulación de dinamización" = Table.UnpivotOtherColumns(#"Separación Linked-Issues", {"Components", "Project", "Issue Type", "Key", "Summary", "Assignee", "Reporter", "Priority", "Status", "Created", "Sub-tasks", "Tipo de prueba", "Resolved"}, "Atributo", "Valor"),
				    #"Consultas combinadas" = Table.NestedJoin(#"Columna de anulación de dinamización", {"Valor"}, KGI_I_Stories_Jira, {"Key"}, "KGI_I_Stories_Jira", JoinKind.LeftOuter),
				    #"Se expandió KGI_I_Stories_Jira" = Table.ExpandTableColumn(#"Consultas combinadas", "KGI_I_Stories_Jira", {"Resolved mes", "Key", "Priority", "Resolved"}, {"KGI_I_Stories_Jira.Resolved mes", "KGI_I_Stories_Jira.Key", "KGI_I_Stories_Jira.Priority", "KGI_I_Stories_Jira.Resolved"}),
				/*
				    //Homologa las prioridades
				    #"AllReplace" = [#"Highest" = "Grave", #"High" = "Grave", #"Medium" = "Media",#"Low" = "Leve",#"Lowest" = "Leve"],    
				    #"Replaced Value" = Table.TransformColumns(#"Se expandió KGI_I_Stories_Jira",{{"Priority",each Record.FieldOrDefault(AllReplace,_,_)}}),
				*/
				    #"Dividir columna por delimitador" = Table.SplitColumn(#"Se expandió KGI_I_Stories_Jira", "Tipo de prueba", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {"Tipo de prueba.1", "Tipo de prueba.2"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Dividir columna por delimitador",{{"Tipo de prueba.1", type text}, {"Tipo de prueba.2", type text}, {"KGI_I_Stories_Jira.Resolved mes", type date}, {"KGI_I_Stories_Jira.Resolved", type date}}),
				    #"Primeros caracteres insertados" = Table.AddColumn(#"Tipo cambiado1", "Project_starts_with", each Text.Start([Project], 4), type text),
				    #"Columna condicional agregada" = Table.AddColumn(#"Primeros caracteres insertados", "ID_KGI_1.5", 
				                                                    each if [Project_starts_with] <> "Mtto"  and [Priority] = "Highest" then "1-5-1-1"
				                                                    else if [Project_starts_with] <> "Mtto"  and [Priority] = "High" then "1-5-1-1" 
				                                                    else if [Project_starts_with] <> "Mtto"  and [Priority] = "Medium" then "1-5-1-2"
				                                                    else if [Project_starts_with] <> "Mtto"  and [Priority] = "Low" then "1-5-1-3"
				                                                    else if [Project_starts_with] <> "Mtto"  and [Priority] = "Lowest" then "1-5-1-3"
				                                                    else if [Project_starts_with] = "Mtto" and [Priority] = "Highest" then "1-5-2-1"
				                                                    else if [Project_starts_with] = "Mtto" and [Priority] = "High" then "1-5-2-1"
				                                                    else if [Project_starts_with] = "Mtto" and [Priority] = "Medium" then "1-5-2-2"
				                                                    else if [Project_starts_with] = "Mtto" and [Priority] = "Low" then "1-5-2-3"
				                                                    else if [Project_starts_with] = "Mtto" and [Priority] = "Lowest" then "1-5-2-3"
				                                                    else null
				),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Columna condicional agregada", "ID_KGI_1.5", "ID_KGI_1.6"),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columna duplicada","5","6",Replacer.ReplaceText,{"ID_KGI_1.6"}),
				    #"Columna condicional agregada1" = Table.AddColumn(#"Valor reemplazado", "Proyecto_Evolutivo", each if Text.StartsWith([Project], "Mtto") then "Evolutivos" else if [Project] = null then null else "Proyectos"),
				    #"Proyecto_Evolutivo" = Table.ReplaceErrorValues(#"Columna condicional agregada1", {{"Proyecto_Evolutivo", null}})
				in
				    Proyecto_Evolutivo
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

