table 'KGI_I_Planificaciones PRJ y MEJ con SLA'
	lineageTag: f3084963-8d5e-47fa-8ce0-410d323eac5e

	column Demanda
		dataType: string
		lineageTag: 516fe0a4-aa23-42f4-8fb8-2271520eda5d
		summarizeBy: none
		sourceColumn: Demanda

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: ba4dc9c4-8d1b-43af-b850-dc91c0864fd7
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Proyecto'
		dataType: string
		lineageTag: 70280d91-1c3c-4557-9584-64f2bfdef153
		summarizeBy: none
		sourceColumn: Tipo de Proyecto

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 12a9b12e-9f0a-440f-8aba-558f46e814a6
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column 'Jefe de proyecto (Project Manager)'
		dataType: string
		lineageTag: 9bf54107-d64e-4701-87c9-aa60f2cc7268
		summarizeBy: none
		sourceColumn: Jefe de proyecto (Project Manager)

		annotation SummarizationSetBy = Automatic

	column 'Aplicación de Negocio'
		dataType: string
		lineageTag: 1bf159a3-79a9-4944-b8b4-f3a9a25798b0
		summarizeBy: none
		sourceColumn: Aplicación de Negocio

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: b7407693-451b-443b-b875-d9db294722e0
		summarizeBy: none
		sourceColumn: Fecha de inicio planificada

		variation Variación
			isDefault
			relationship: a1f62a95-8f3f-44b1-abc7-1935bf3822d2
			defaultHierarchy: LocalDateTable_38852019-bfcf-4352-b752-1c26ccbe35f4.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 02372d3b-011e-4cec-9a33-06ffdc4d655c
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: 1b6d3cb3-1d6d-415c-95c7-d5871c15bdf6
		summarizeBy: none
		sourceColumn: Inicio

		variation Variación
			isDefault
			relationship: 6947cfe4-bac0-49f2-8302-4208d454e5b0
			defaultHierarchy: LocalDateTable_80316a94-47b7-4092-a004-9cf66dbb44c0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Fin
		dataType: dateTime
		formatString: General Date
		lineageTag: 24b64f29-e686-474a-99c4-d48574cabbf1
		summarizeBy: none
		sourceColumn: Fin

		variation Variación
			isDefault
			relationship: c4f74a8e-63a5-48e5-8f32-3da1a34611f6
			defaultHierarchy: LocalDateTable_894d9d5b-6ade-49d5-92c6-eba50337bca3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de inicio real'
		dataType: dateTime
		formatString: General Date
		lineageTag: 0472393c-b73c-440a-a234-e0889a7603a5
		summarizeBy: none
		sourceColumn: Fecha de inicio real

		variation Variación
			isDefault
			relationship: 599598c9-b3e8-4d30-b663-05dd283e3292
			defaultHierarchy: LocalDateTable_3f379f3c-a0c9-4cc5-8410-1123cd3481ae.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real'
		dataType: dateTime
		formatString: General Date
		lineageTag: a9efa2d4-c075-4ed0-98f4-eb4e19384054
		summarizeBy: none
		sourceColumn: Fecha fin real

		variation Variación
			isDefault
			relationship: 948973d1-55a7-4cf2-898f-755366f22c21
			defaultHierarchy: LocalDateTable_bef501cf-4202-4605-bb71-b59c5fb18621.'Jerarquía de fechas'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje completado'
		dataType: int64
		formatString: 0
		lineageTag: e8ff8961-4d56-4e6c-8b4b-61b51b54b7d2
		summarizeBy: sum
		sourceColumn: Porcentaje completado

		annotation SummarizationSetBy = Automatic

	column 'Duración planificada'
		dataType: int64
		formatString: 0
		lineageTag: 9d9b0e59-fbda-4d14-b9f3-7bd83982b718
		summarizeBy: sum
		sourceColumn: Duración planificada

		annotation SummarizationSetBy = Automatic

	column 'Duración real'
		dataType: int64
		formatString: 0
		lineageTag: 8367d6e1-f92a-46b5-9357-135ba2c4d3c1
		summarizeBy: sum
		sourceColumn: Duración real

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: a13266e1-23eb-41c2-bf62-9f52f536b6cc
		summarizeBy: none
		sourceColumn: Fecha fin planificada

		variation Variación
			isDefault
			relationship: 6e8776c5-2de6-43d5-aa86-64d5b41c8eb6
			defaultHierarchy: LocalDateTable_be673b3b-0334-4472-9577-88cccb81a813.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha fin real mes'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 847b3f02-a5e6-4a27-b760-30d505e09cd5
		summarizeBy: none
		sourceColumn: Fecha fin real mes

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Duración Planificada LB'
		dataType: double
		lineageTag: 3e6d98c4-bf33-4102-992c-c0866c151f81
		summarizeBy: sum
		sourceColumn: Duración Planificada LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Duración real LB'
		dataType: double
		lineageTag: b557c500-0869-447b-a182-e38ce1404c62
		summarizeBy: sum
		sourceColumn: Duración real LB

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tasa de desviación'
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7c72f481-bf0f-4d32-80ad-039955d97772
		summarizeBy: sum
		sourceColumn: Tasa de desviación

		annotation SummarizationSetBy = Automatic

	column 'Estimación incumplida'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0e55265e-3005-472c-a509-e0954be83f3c
		summarizeBy: none
		sourceColumn: Estimación incumplida

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI1.2'
		dataType: string
		lineageTag: ce8a97b4-2978-49d3-b05a-38237b6aa249
		summarizeBy: none
		sourceColumn: ID_KGI1.2

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI1.3'
		dataType: string
		lineageTag: aee0c96c-f087-45be-b462-6d2772fe271f
		summarizeBy: none
		sourceColumn: ID_KGI1.3

		annotation SummarizationSetBy = Automatic

	column Proyecto_Evolutivo
		dataType: string
		lineageTag: 095ed8d5-73bc-472e-b628-e07d29f3b68a
		summarizeBy: none
		sourceColumn: Proyecto_Evolutivo

		annotation SummarizationSetBy = Automatic

	column 'Prioridad grupo'
		dataType: string
		lineageTag: 90e66348-a7f6-4716-82c9-9a682d843602
		summarizeBy: none
		sourceColumn: Prioridad grupo

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.ID Alegación'
		dataType: string
		lineageTag: eb158de4-8e73-42c8-83f0-27b8c2c59060
		summarizeBy: none
		sourceColumn: T_Alegaciones.ID Alegación

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.Solicitante'
		dataType: string
		lineageTag: b62b3f5a-f5a0-4c06-acae-dca949c3ce5f
		summarizeBy: none
		sourceColumn: T_Alegaciones.Solicitante

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.ANS'
		dataType: string
		lineageTag: 3ff4a2be-20bd-4163-83ba-cb64e23cf371
		summarizeBy: none
		sourceColumn: T_Alegaciones.ANS

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.Estado'
		dataType: string
		lineageTag: 88ad02fe-318d-4530-9235-f7b3a30f5148
		summarizeBy: none
		sourceColumn: T_Alegaciones.Estado

		annotation SummarizationSetBy = Automatic

	column Infringido_alegaciones
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c123eeed-2af1-4b7d-a9ca-bb10ba6bfbaa
		summarizeBy: none
		sourceColumn: Infringido_alegaciones

		annotation SummarizationSetBy = Automatic

	column 'KGI_II_Incidencias.Número'
		dataType: string
		lineageTag: 60856bfd-e3a4-4cbd-8af7-0233ce71f4e7
		summarizeBy: none
		sourceColumn: KGI_II_Incidencias.Número

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones_Resumen.Alegaciones'
		dataType: string
		lineageTag: 05294d67-9aea-4f73-af8b-758c56d25025
		summarizeBy: none
		sourceColumn: T_Alegaciones_Resumen.Alegaciones

		annotation SummarizationSetBy = Automatic

	column 'KGI_II_Incidencias.Breve descripción'
		dataType: string
		lineageTag: 26bfeda9-f0c4-4a81-a35b-34cbc35261f3
		summarizeBy: none
		sourceColumn: KGI_II_Incidencias.Breve descripción

		annotation SummarizationSetBy = Automatic

	column 'KGI_II_Incidencias.Tipo de Solución'
		dataType: string
		lineageTag: 54093e54-f9f7-42f4-9b7e-8561f0a771fa
		summarizeBy: none
		sourceColumn: KGI_II_Incidencias.Tipo de Solución

		annotation SummarizationSetBy = Automatic

	column 'Fecha PRE'
		dataType: dateTime
		formatString: General Date
		lineageTag: cc0d7ce6-ce74-498f-9035-7f6d5c5da29b
		summarizeBy: none
		sourceColumn: Fecha PRE

		variation Variación
			isDefault
			relationship: 590010b4-f974-4b72-b2d4-dcbd7c605b09
			defaultHierarchy: LocalDateTable_b9d14709-f8b5-46d2-9d0e-c5a1d0f5ee70.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Duración real v2'
		dataType: string
		lineageTag: 56e1c823-22e8-47e7-b8a9-0322cecfd3bc
		summarizeBy: none
		sourceColumn: Duración real v2

		annotation SummarizationSetBy = Automatic

	column Descripción
		dataType: string
		lineageTag: 0ebda12e-78d2-405e-88eb-fb9c96304f87
		summarizeBy: none
		sourceColumn: Descripción

		annotation SummarizationSetBy = Automatic

	column Responsable
		dataType: string
		lineageTag: d7071f26-b54e-45cf-9ccb-d8443eea5142
		summarizeBy: none
		sourceColumn: Responsable

		annotation SummarizationSetBy = Automatic

	column 'Estado de Aprobación'
		dataType: string
		lineageTag: f920c86c-8c10-4f3c-a3c2-07c86c398e50
		summarizeBy: none
		sourceColumn: Estado de Aprobación

		annotation SummarizationSetBy = Automatic

	column 'Fecha de Medición KGI'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d0f1e298-6ea4-4e81-b22c-71da4864f8c9
		summarizeBy: none
		sourceColumn: Fecha de Medición KGI

		variation Variación
			isDefault
			relationship: 00b59647-3d56-48da-93db-fa35a0f1e5e9
			defaultHierarchy: LocalDateTable_d1d840b3-08c6-423b-8e8f-591c8783691e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fecha de Aprobación / Rechazo'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ce604096-675d-4477-acc1-60548bb1cd0c
		summarizeBy: none
		sourceColumn: Fecha de Aprobación / Rechazo

		variation Variación
			isDefault
			relationship: 87c71b48-4591-4aea-93dd-03fbdc21fa90
			defaultHierarchy: LocalDateTable_2cdc2c7c-1a7e-4c6b-b43b-67c2ee4b1c77.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Comentarios
		dataType: string
		lineageTag: d406c282-c011-4d8b-9d86-6b66258b3da2
		summarizeBy: none
		sourceColumn: Comentarios

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 076261d9-4696-4eea-9d8e-bfaec32e7b68
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 0baba82a-cc89-4442-bbe7-9e82371de3b7
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column 'ID_KGI_1.7'
		dataType: string
		lineageTag: 72ecc529-b807-474a-8ea8-d2c3371191c3
		summarizeBy: none
		sourceColumn: ID_KGI_1.7

		annotation SummarizationSetBy = Automatic

	column 'T_Alegaciones.Alegacion_aceptada'
		dataType: string
		lineageTag: b97c78ad-59dd-4663-9e04-d65ca203d2a6
		summarizeBy: none
		sourceColumn: T_Alegaciones.Alegacion_aceptada

		annotation SummarizationSetBy = Automatic

	column 'Fecha límite planificada'
		dataType: dateTime
		formatString: General Date
		lineageTag: bf87e053-a25a-4524-9966-4f53e831cae1
		summarizeBy: none
		sourceColumn: Fecha límite planificada

		variation Variación
			isDefault
			relationship: ae019e1a-6041-4d82-bd40-1a895525e8a6
			defaultHierarchy: LocalDateTable_6f59878f-f85b-4ece-a881-f74b8b32bf76.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Nombre de PRJ o MEJ'
		dataType: string
		lineageTag: 8fdc4c86-6895-4097-bffe-b5c1fad2aa3c
		summarizeBy: none
		sourceColumn: Nombre de PRJ o MEJ

		annotation SummarizationSetBy = Automatic

	column 'Nombre de proyecto'
		dataType: string
		lineageTag: 9fac06c3-afc7-4ac6-9bd5-866812ce370c
		summarizeBy: none
		sourceColumn: Nombre de proyecto

		annotation SummarizationSetBy = Automatic

	partition 'KGI_I_Planificaciones PRJ y MEJ con SLA-a29d8a36-d8f9-4119-bda6-c891b1f3a0a8' = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source = ```
				let
				    Source = #"KGI_I_Planificaciones PRJ",
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(Source,{{"Fecha de finalización planificada", "Fecha límite planificada"}}),
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado1",{{"Demanda", type text}, {"Número", type text}, {"Tipo de Proyecto", type text}, {"Prioridad", type text}, {"Jefe de proyecto (Project Manager)", type text}, {"Aplicación de Negocio ", type text}, {"Fecha de inicio planificada", type datetime}, {"Fecha límite planificada", type datetime}, {"Nombre", type text}, {"Inicio", type datetime}, {"Fin", type datetime}, {"Fecha de inicio real", type datetime}, {"Fecha fin real", type datetime}, {"Porcentaje completado", Int64.Type}, {"Duración planificada", Int64.Type}, {"Duración real", Int64.Type}, {"Nombre de proyecto", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Nombre de proyecto", "Nombre de PRJ o MEJ"},{"Aplicación de Negocio ", "Aplicación de Negocio"}}),
				
				    //Filtro por solo proyectos y mejoras de aplicaciones a cargo del proveedor iAR
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each (
				//[#"Aplicación de Negocio "] 
				//    = "MAXIMO: MAXIMO")    
				//    and (
				[Tipo de Proyecto] <> "Mantenimiento de Aplicaciones")),
				
				    //Une tablas de Mejoras y Proyectos de Mantenimiento de Aplicaciones
				    #"Appended Query" = Table.Combine({#"Filtered Rows", #"KGI_I_Mejoras propuestas"}),
				    #"Appended Query1" = Table.Combine({#"Appended Query", #"KGI_I_Planificaciones EVO"}),
				    /*
				    //Homologa las prioridades
				    #"AllReplace" = [#"1 - Crítica" = "Crítica", #"2 - Alta" = "Alta", #"3 - Moderada" = "Media",#"4 - Baja" = "Baja",#"5 - Muy Baja" = "Baja"],    
				    #"Replaced Value" = Table.TransformColumns( #"Appended Query1",{{"Prioridad",each Record.FieldOrDefault(AllReplace,_,_)}}),
				*/
				    //Nueva columna "Fecha (1er día de mes)"
				    #"Duplicated Column" = Table.DuplicateColumn(#"Appended Query1", "Fecha fin real", "Fecha fin real - Copy"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"Fecha fin real - Copy", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"Fecha fin real - Copy", Date.StartOfMonth, type date}}),
				    KGI_12_PRE = Table.NestedJoin(#"Calculated Start of Month", {"Número"}, KGI_12_Epica_Evolutivo, {"Task Number"}, "KGI_12_Epica_Evolutivo", JoinKind.LeftOuter),
				    #"Se expandió KGI_12_Epica_Evolutivo" = Table.ExpandTableColumn(KGI_12_PRE, "KGI_12_Epica_Evolutivo", {"Fecha PRE"}, {"Fecha PRE"}),
				    #"Duración real v2" = Table.AddColumn(#"Se expandió KGI_12_Epica_Evolutivo", "Duración real v2", each if [Fecha PRE] = null then [Duración real] else Duration.TotalSeconds([Fecha PRE]-[Fecha de inicio real])),
				
				    //Nueva columna "Duración planificada de línea base"    
				    #"Added Custom1" = Table.AddColumn(#"Duración real v2", "Duración Planificada LB", each [Fin]-[Inicio]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Duración Planificada LB", type number}}),
				
				   //Nueva columna "Duración real para cálculo con planificación de línea base" 
				    #"Added Custom2" = Table.AddColumn(#"Changed Type1", "Duración real LB", 
				    each if [Nombre] <> "" then ([Fecha fin real]-[Fecha de inicio real]) else ""),
				    
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom2",{{"Duración real LB", type number}}),
				
				    //Nueva columna "Tasa de desviación"
				    #"Added Custom3" = Table.AddColumn(#"Changed Type2", "Tasa de desviación", each if [Nombre] = "" then (([Duración real v2]-[Duración planificada])/[Duración planificada]) 
				                          else (([Duración real LB]-[Duración Planificada LB])/[Duración Planificada LB])),
				 
				    //Quita los proyectos y mejoras que tienen por error duración real o planificada = 0
				    #"Filtered Rows1" = Table.SelectRows(#"Added Custom3", each ([Duración real] <> 0) and ([Duración planificada] <> 0)),
				    #"Prioridad grupo" = Table.AddColumn(#"Filtered Rows1", "Prioridad grupo", each if [Prioridad] = "1 - Crítica" then "Crítica" else if [Prioridad] = "2 - Alta" then "Alta" else if [Prioridad] = "3 - Media" then "Media" else "Baja", type text),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Prioridad grupo",{{"Tasa de desviación", Percentage.Type}}),
				
				    //Columna "Estimación incumplida"
				    #"Added Custom4" = Table.AddColumn(#"Changed Type3", "Estimación incumplida",
				    each if [Prioridad grupo]="Crítica" and [Tasa de desviación]>0.1 then true else
				         if [Prioridad grupo]="Alta" and [Tasa de desviación]>0.1 then true else
				         if [Prioridad grupo]="Media" and [Tasa de desviación]>0.15 then true else
				         if [Prioridad grupo]="Baja" and [Tasa de desviación]>0.2 then true else false,
				         Logical.Type),
				
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Added Custom4",{{"Fecha fin real - Copy", "Fecha fin real mes"}}),
				    ID_KGI_1.2 = Table.AddColumn(#"Columnas con nombre cambiado", 
				                  "ID_KGI1.2", 
				                  each if [Tipo de Proyecto] = "Proyecto" then 
				                       each if [Prioridad] = "1 - Crítica" then "1-2-1-2" 
				                            else if [Prioridad] = "2 - Alta" then "1-2-1-2" 
				                            else if [Prioridad] = "3 - Moderada" then "1-2-1-3" 
				                            else if [Prioridad] = "4 - Baja" then "1-2-1-4"
				                            else if [Prioridad] = "5 - Muy Baja" then "1-2-1-4"
				                            else null
				                   else if [Prioridad] = "1 - Crítica" then "1-2-2-2" 
				                            else if [Prioridad] = "2 - Alta" then "1-2-2-2" 
				                            else if [Prioridad] = "3 - Moderada" then "1-2-2-3" 
				                            else if [Prioridad] = "4 - Baja" then "1-2-2-4"
				                            else if [Prioridad] = "5 - Muy Baja" then  "1-2-2-4"
				                   else null, type text),
				    ID_KGI_1.3 = Table.AddColumn(#"ID_KGI_1.2", 
				                  "ID_KGI1.3", 
				                  each if [Tipo de Proyecto] = "Proyecto" then 
				                       each if [Prioridad] = "1 - Crítica" then "1-3-1-2" 
				                            else if [Prioridad] = "2 - Alta" then "1-3-1-2" 
				                            else if [Prioridad] = "3 - Moderada" then "1-3-1-3" 
				                            else if [Prioridad] = "4 - Baja" then "1-3-1-4"
				                            else if [Prioridad] = "5 - Muy Baja" then "1-3-1-4"
				                            else null
				                   else if [Prioridad] = "1 - Crítica" then "1-3-2-2" 
				                            else if [Prioridad] = "2 - Alta" then "1-3-2-2" 
				                            else if [Prioridad] = "3 - Moderada" then "1-3-2-3" 
				                            else if [Prioridad] = "4 - Baja" then "1-3-2-4"
				                            else if [Prioridad] = "5 - Muy Baja" then  "1-3-2-4"
				                   else null, type text),
				    #"Columna condicional agregada" = Table.AddColumn(ID_KGI_1.3, "Proyecto_Evolutivo", each if [Tipo de Proyecto] = "Proyecto" then "Proyectos" else "Evolutivos"),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Columna condicional agregada", {"Número"}, T_Alegaciones, {"ID"}, "T_Alegaciones", JoinKind.LeftOuter),
				    #"Se expandió T_Alegaciones" = Table.ExpandTableColumn(#"Consultas combinadas1", "T_Alegaciones", {"ID Alegación", "Solicitante", "ANS", "Estado"}, {"T_Alegaciones.ID Alegación", "T_Alegaciones.Solicitante", "T_Alegaciones.ANS", "T_Alegaciones.Estado"}),
				    #"Infringido con alegaciones" = Table.AddColumn( #"Se expandió T_Alegaciones", "Infringido_alegaciones", each if [Estimación incumplida] = true and [T_Alegaciones.Estado] = "1 - Aprobada" and [T_Alegaciones.ANS] = "KGI 1-2" then false else [Estimación incumplida] , Logical.Type),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Infringido con alegaciones",{{"Infringido_alegaciones", type text}}),
				    #"Consultas combinadas2" = Table.NestedJoin(#"Tipo cambiado", {"Número"}, KGI_II_Incidencias, {"Principal"}, "KGI_II_Incidencias", JoinKind.LeftOuter),
				    #"Se expandió KGI_II_Incidencias" = Table.ExpandTableColumn(#"Consultas combinadas2", "KGI_II_Incidencias", {"Número", "Breve descripción", "Tipo de Solución"}, {"KGI_II_Incidencias.Número", "KGI_II_Incidencias.Breve descripción", "KGI_II_Incidencias.Tipo de Solución"}),
				    #"Consultas combinadas3" = Table.NestedJoin(#"Se expandió KGI_II_Incidencias", {"KGI_II_Incidencias.Número"}, T_Alegaciones_Resumen, {"ID"}, "T_Alegaciones_Resumen", JoinKind.LeftOuter),
				    #"Se expandió T_Alegaciones_Resumen" = Table.ExpandTableColumn(#"Consultas combinadas3", "T_Alegaciones_Resumen", {"Alegaciones"}, {"T_Alegaciones_Resumen.Alegaciones"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Se expandió T_Alegaciones_Resumen",{{"Estimación incumplida", type logical}, {"Infringido_alegaciones", type logical}})
				in
				    #"Tipo cambiado1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

