table Componentes
	lineageTag: f90932ae-2113-482c-bdcf-7bfd011cf8c5

	column BI
		dataType: string
		lineageTag: d0a7a5cd-81c9-4960-a864-956230df5ad4
		summarizeBy: none
		sourceColumn: BI

		annotation SummarizationSetBy = Automatic

	column MERCADOS
		dataType: string
		lineageTag: f30c4ef9-1f3c-4b33-9520-9fcedc882425
		summarizeBy: none
		sourceColumn: MERCADOS

		annotation SummarizationSetBy = Automatic

	column EMS
		dataType: string
		lineageTag: 37926958-18df-44dd-903d-dc7a41078462
		summarizeBy: none
		sourceColumn: EMS

		annotation SummarizationSetBy = Automatic

	column 'CRM Energia'
		dataType: string
		lineageTag: 3ff5f399-ef44-4508-86da-e5d22a3dd064
		summarizeBy: none
		sourceColumn: CRM Energia

		annotation SummarizationSetBy = Automatic

	column LEGAL
		dataType: string
		lineageTag: e1bd7fbe-9b71-42ec-a157-71c59aabe2d8
		summarizeBy: none
		sourceColumn: LEGAL

		annotation SummarizationSetBy = Automatic

	partition Componentes-52f57b4e-de8c-42d5-8f9a-5e7c1f7acde0 = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(componentesPath & xlsx), null, true),
				    Personalizado1 = Origen{[Name="Componentes Jira por Servicio"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Personalizado1, [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ENABLON", type text}, {"MAXIMO", type text}, {"IAR", type text}, {"AMS CORE GFI", type text}, {"SERVICENOW", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado1",{"MAXIMO", "IAR", "AMS CORE GFI", "SERVICENOW", "CRMSF", "GDOC", "LWAS", "RPA", "BESTINVER", "SAPHR", "BESTINVERAPP", "SAC", "SCS", "ENABLON"}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas quitadas", each ([BI] <> null))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

