table 'KGI_III_Incidencias Peticiones'
	excludeFromModelRefresh
	lineageTag: cef7827f-3a5c-4a1a-9e31-2d5610b265aa

	column Subcategoría
		dataType: string
		lineageTag: d91aa4e9-3dee-4e60-b01b-30ab21b3c869
		summarizeBy: none
		sourceColumn: Subcategoría

		annotation SummarizationSetBy = Automatic

	column Principal
		dataType: string
		lineageTag: 44ec0bef-a03a-4a4d-9fa7-af7407ff9dd1
		summarizeBy: none
		sourceColumn: Principal

		annotation SummarizationSetBy = Automatic

	column 'Breve descripción'
		dataType: string
		lineageTag: cf20b123-d942-4589-b088-6fab0b98fc69
		summarizeBy: none
		sourceColumn: Breve descripción

		annotation SummarizationSetBy = Automatic

	column Alegaciones
		dataType: string
		lineageTag: 829ade2a-afb5-4bef-9c53-7fbfc78c24eb
		summarizeBy: none
		sourceColumn: Alegaciones

		annotation SummarizationSetBy = Automatic

	column Extracción
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3eea04d3-4133-4f95-81f3-14e0e5be0024
		summarizeBy: none
		sourceColumn: Extracción

		variation Variación
			isDefault
			relationship: 62c6608f-80d6-413b-a9cc-3b6cef12b5d6
			defaultHierarchy: LocalDateTable_0ac27659-60f5-499e-9efd-90c2a8830442.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Número
		dataType: string
		lineageTag: a8108a56-55ca-4ecd-adec-751b840fa251
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: 8e966b40-7f47-43a1-b800-3fdc57311320
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Abierto
		dataType: dateTime
		formatString: General Date
		lineageTag: 21827bd9-aed4-4a87-93e7-0ebe4f8c824b
		summarizeBy: none
		sourceColumn: Abierto

		variation Variación
			isDefault
			relationship: 3f542008-46d4-4d4e-acde-ab1c4b8e4628
			defaultHierarchy: LocalDateTable_6da9990a-325c-4a1d-bc35-6b1c0042b316.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Cerrado
		dataType: dateTime
		formatString: General Date
		lineageTag: 2efef87a-1129-4b27-8e20-e21aab76a345
		summarizeBy: none
		sourceColumn: Cerrado

		variation Variación
			isDefault
			relationship: 1fe57e6f-75f2-4676-8674-162b1aadf3c8
			defaultHierarchy: LocalDateTable_879584a5-c39e-4415-9dc3-50d8fa938b1c.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column 'Fecha de resolución'
		dataType: dateTime
		formatString: General Date
		lineageTag: b5a9a613-08b1-45a3-a7bb-b78bdf7cee45
		summarizeBy: none
		sourceColumn: Fecha de resolución

		variation Variación
			isDefault
			relationship: 660938ac-9482-43b5-8b2d-daa7758c97ec
			defaultHierarchy: LocalDateTable_10acf163-844f-4502-b8b1-67f07d3ca8e0.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duración
		dataType: string
		lineageTag: e6524826-9d73-42b0-987f-daae5cf77f01
		summarizeBy: none
		sourceColumn: Duración

		annotation SummarizationSetBy = Automatic

	column 'Duración del negocio'
		dataType: string
		lineageTag: 7d5aab62-8373-4953-9fcf-61151d250c6a
		summarizeBy: none
		sourceColumn: Duración del negocio

		annotation SummarizationSetBy = Automatic

	column Infringido
		dataType: string
		lineageTag: b4c9d6cc-fd40-41ee-a70e-0ce945a2ab7c
		summarizeBy: none
		sourceColumn: Infringido

		annotation SummarizationSetBy = Automatic

	column 'Tiempo original de incumplimiento'
		dataType: string
		lineageTag: a62abc01-7326-48ff-8a6c-246593f2e2c7
		summarizeBy: none
		sourceColumn: Tiempo original de incumplimiento

		annotation SummarizationSetBy = Automatic

	column 'Estado de la incidencia'
		dataType: string
		lineageTag: 86c7f8a4-dfb3-4de3-8bfe-88c07be3a3fa
		summarizeBy: none
		sourceColumn: Estado de la incidencia

		annotation SummarizationSetBy = Automatic

	column 'Estado SLA'
		dataType: string
		lineageTag: fcb49428-6137-4c37-9503-a06797407af3
		summarizeBy: none
		sourceColumn: Estado SLA

		annotation SummarizationSetBy = Automatic

	column 'Código de cierre'
		dataType: string
		lineageTag: 8482fe7a-7144-4f77-a578-3db610eac514
		summarizeBy: none
		sourceColumn: Código de cierre

		annotation SummarizationSetBy = Automatic

	column Reabierta
		dataType: string
		lineageTag: 17281c46-7f45-4f1d-9afa-7a2b0cc9cff6
		summarizeBy: none
		sourceColumn: Reabierta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Solución'
		dataType: string
		lineageTag: 16d18a03-2107-4cd6-809d-31dbdb7008a3
		summarizeBy: none
		sourceColumn: Tipo de Solución

		annotation SummarizationSetBy = Automatic

	column 'Duración SLA'
		dataType: string
		lineageTag: 79c20124-ad08-4d41-99e7-59ad7d12c707
		summarizeBy: none
		sourceColumn: Duración SLA

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje de negocio trascurrido'
		dataType: string
		lineageTag: 4ebed771-9de3-4205-be5f-aff6794b05cc
		summarizeBy: none
		sourceColumn: Porcentaje de negocio trascurrido

		annotation SummarizationSetBy = Automatic

	column 'Elemento de configuración'
		dataType: string
		lineageTag: 2f103649-b89a-4008-b3f9-6a41ce081f6a
		summarizeBy: none
		sourceColumn: Elemento de configuración

		annotation SummarizationSetBy = Automatic

	column 'Abierto por'
		dataType: string
		lineageTag: 937a4a84-4d07-4033-9a70-1b6a62b13a90
		summarizeBy: none
		sourceColumn: Abierto por

		annotation SummarizationSetBy = Automatic

	column 'Tiempo de trabajo'
		dataType: string
		lineageTag: 6fdec2c5-0492-485b-870f-35a67b30f08e
		summarizeBy: none
		sourceColumn: Tiempo de trabajo

		annotation SummarizationSetBy = Automatic

	column 'ID de correlación'
		dataType: string
		lineageTag: bec63f13-7a96-424f-b3c7-5b08668881a5
		summarizeBy: none
		sourceColumn: ID de correlación

		annotation SummarizationSetBy = Automatic

	column 'Estado del incidente'
		dataType: string
		lineageTag: 216f14f1-68f4-4495-afa3-acf30b7e25e5
		summarizeBy: none
		sourceColumn: Estado del incidente

		annotation SummarizationSetBy = Automatic

	partition 'KGI_III_Incidencias Peticiones-aed9a172-48ba-483e-be9d-3aed3cdb319f' = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source =
				let
				    Origen = Table.Combine({KGI_II_Incidencias, KGI_II_Incidencias_Previas}),
				    #"Filas filtradas" = Table.SelectRows(Origen, each true),
				    #"Columnas renombradas" = Table.RenameColumns(#"Filas filtradas",{{"Volver a abrir recuento", "Reabierta"},  {"Código de resolución", "Código de cierre"}, {"Duración_1", "Duración SLA"}, /*{"Duración del negocio", "Duración real"},*/ {"Etapa", "Estado SLA"}, {"Resuelto", "Fecha de resolución"}}),
				    #"Filas filtradas1" = Table.SelectRows(#"Columnas renombradas", each ([Principal] <> "")),
				    #"Consultas combinadas" = Table.NestedJoin(#"Filas filtradas1", {"Número"}, T_Alegaciones_Resumen, {"ID"}, "T_Alegaciones_Resumen", JoinKind.LeftOuter),
				    #"Se expandió T_Alegaciones" = Table.ExpandTableColumn(#"Consultas combinadas", "T_Alegaciones_Resumen", {"Alegaciones"}, {"Alegaciones"})
				in
				    #"Se expandió T_Alegaciones"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

