table KGI_12_Epica_Evolutivo
	lineageTag: 09608d32-6bd8-472e-9b64-7c9ac4d8a158

	column 'Start date Epic'
		dataType: string
		lineageTag: ebc3b81f-e108-4168-9ffd-a767695c8745
		summarizeBy: none
		sourceColumn: Start date Epic

		annotation SummarizationSetBy = Automatic

	column 'Epic Link'
		dataType: string
		lineageTag: 58634ceb-0106-45b9-88c0-695af985f378
		summarizeBy: none
		sourceColumn: Epic Link

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Incidencia'
		dataType: string
		lineageTag: dbc011b4-0ee8-4c76-9e50-28f418acaeaf
		summarizeBy: none
		sourceColumn: Tipo de Incidencia

		annotation SummarizationSetBy = Automatic

	column Clave
		dataType: string
		lineageTag: 8275331c-0705-4cbd-b4d0-e8536c871fee
		summarizeBy: none
		sourceColumn: Clave

		annotation SummarizationSetBy = Automatic

	column Resumen
		dataType: string
		lineageTag: ce98a217-9b36-4179-b728-63b1af3c7132
		summarizeBy: none
		sourceColumn: Resumen

		annotation SummarizationSetBy = Automatic

	column Responsable
		dataType: string
		lineageTag: bba56034-cd7f-464c-a616-72bf2d8e3ef0
		summarizeBy: none
		sourceColumn: Responsable

		annotation SummarizationSetBy = Automatic

	column Informador
		dataType: string
		lineageTag: 5dc35e02-5002-4ab6-bf89-a18b1a4980df
		summarizeBy: none
		sourceColumn: Informador

		annotation SummarizationSetBy = Automatic

	column Prioridad
		dataType: string
		lineageTag: a75ea792-47f3-4c5f-a941-84069c2c3639
		summarizeBy: none
		sourceColumn: Prioridad

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 301485f6-4bbd-4ac8-8765-842f6df9ab07
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Creada
		dataType: string
		lineageTag: 68d4d53e-6e5d-4ea3-a741-912900c1b427
		summarizeBy: none
		sourceColumn: Creada

		annotation SummarizationSetBy = Automatic

	column 'Σ Estimación Restante'
		dataType: string
		lineageTag: d1dd8648-b51f-4af2-8cd5-1bb1bf7ee540
		summarizeBy: none
		sourceColumn: Σ Estimación Restante

		annotation SummarizationSetBy = Automatic

	column 'Σ Estimación original'
		dataType: string
		lineageTag: 3e719e4f-fd06-44ee-be4d-00ab76c0d324
		summarizeBy: none
		sourceColumn: Σ Estimación original

		annotation SummarizationSetBy = Automatic

	column 'Σ Tiempo empleado'
		dataType: string
		lineageTag: 769f3084-7d4f-4c58-b0a4-67e6451b2602
		summarizeBy: none
		sourceColumn: Σ Tiempo empleado

		annotation SummarizationSetBy = Automatic

	column Componentes
		dataType: string
		lineageTag: 03b2bd6a-57ba-468e-8b1b-92105069302e
		summarizeBy: none
		sourceColumn: Componentes

		annotation SummarizationSetBy = Automatic

	column 'Task Number'
		dataType: string
		lineageTag: 78b911d6-adfe-4ffc-8d93-93971a95b469
		summarizeBy: none
		sourceColumn: Task Number

		annotation SummarizationSetBy = Automatic

	column Resuelta
		dataType: string
		lineageTag: 34455c10-387f-445e-8669-8332e81be9fd
		summarizeBy: none
		sourceColumn: Resuelta

		annotation SummarizationSetBy = Automatic

	column 'Tipo de entregable'
		dataType: string
		lineageTag: 69ba0fe7-9bb3-4dc0-b6c5-c75e59f4100e
		summarizeBy: none
		sourceColumn: Tipo de entregable

		annotation SummarizationSetBy = Automatic

	column Entregables
		dataType: string
		lineageTag: 86ead99b-4c3f-435c-bce4-d209b04c0e7f
		summarizeBy: none
		sourceColumn: Entregables

		annotation SummarizationSetBy = Automatic

	column 'Nombre del entregable'
		dataType: string
		lineageTag: 0e0dd760-5590-4747-acdc-140fc476c696
		summarizeBy: none
		sourceColumn: Nombre del entregable

		annotation SummarizationSetBy = Automatic

	column Rechazos
		dataType: string
		lineageTag: 04f4c65c-f7c2-4356-ab34-485cf6dc11c1
		summarizeBy: none
		sourceColumn: Rechazos

		annotation SummarizationSetBy = Automatic

	column 'Begin Date'
		dataType: string
		lineageTag: 09fb2917-8f12-40b2-bc54-1861af637da9
		summarizeBy: none
		sourceColumn: Begin Date

		annotation SummarizationSetBy = Automatic

	column 'Fecha de vencimiento'
		dataType: string
		lineageTag: 373c552e-c114-427c-958e-e25ec7822a77
		summarizeBy: none
		sourceColumn: Fecha de vencimiento

		annotation SummarizationSetBy = Automatic

	column Resolución
		dataType: string
		lineageTag: 25cece80-af42-4897-8ede-25d3e80df997
		summarizeBy: none
		sourceColumn: Resolución

		annotation SummarizationSetBy = Automatic

	column 'End Date'
		dataType: string
		lineageTag: df3ab3fc-770f-4ef0-af48-b001a2f890a8
		summarizeBy: none
		sourceColumn: End Date

		annotation SummarizationSetBy = Automatic

	column 'End Real Date'
		dataType: string
		lineageTag: c0faa24a-b3a3-42de-bd8e-a891d3660f77
		summarizeBy: none
		sourceColumn: End Real Date

		annotation SummarizationSetBy = Automatic

	column 'Fecha PRE'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1973addd-ff2a-4ee0-a542-a6f7058c9ab8
		summarizeBy: none
		sourceColumn: Fecha PRE

		variation Variación
			isDefault
			relationship: d815bae0-e647-48a5-bc17-40e20e6805ce
			defaultHierarchy: LocalDateTable_272b6a4e-5076-4654-b4b4-1b6b00a02e9e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition KGI_12_Epica_Evolutivo-dd30dbf2-83af-4ae5-be57-1448d0b100a2 = m
		mode: import
		queryGroup: 'Tablas No Modelo'
		source =
				let
				    Origen = Excel.Workbook(Web.Contents(sharepointRoot & servicio & ficherosServicio & "Epica-Relacion Tarea" & xlsx), null, true),
				    #"Your Jira Issues_Sheet" = Origen{[Item="Your Jira Issues",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Your Jira Issues_Sheet", [PromoteAllScalars=true]),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Encabezados promovidos",{"Epic Link"}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Columnas quitadas", {"Clave"}, KGI_12_Jira, {"Epic Link"}, "KGI_12_Jira", JoinKind.LeftOuter),
				    #"Se expandió KGI_12_Jira" = Table.ExpandTableColumn(#"Consultas combinadas", "KGI_12_Jira", {"Epic Link", "Fecha PRE"}, {"Epic Link", "Fecha PRE"})
				in
				    #"Se expandió KGI_12_Jira"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

