table LB_leyenda
	lineageTag: e999c05a-7089-4758-b3c3-cae092d06bfa

	column LB
		dataType: string
		lineageTag: 04100e87-b5c0-4662-b923-c05163565f6a
		summarizeBy: none
		sourceColumn: LB

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: e5d25531-12fc-46d9-ad58-8130a6ffdd78
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	partition LB_leyenda-7a19b534-6561-4f28-a35e-43581526da8e = m
		mode: import
		queryGroup: 'Tablas Modelo'
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8nFSiCk1MDBOVnAtLkgtSkxJVNJRUnZzdjI3NFGK1QErQJaxMEkySYTL+CdlpZZkluUrGIDkTC0sLRItMOQMIXKmFuaYckZguWRTCxNMM30PL6zIzM0HqTBKNk0GqYgFAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [LB = _t, Color = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"LB", type text}, {"Color", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

